LLVM: lib/CodeGen/StackMapLivenessAnalysis.cpp File Reference
StackMapLivenessAnalysis.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "stackmaps"
Functions
STATISTIC (NumStackMapFuncVisited, "Number of functions visited")
STATISTIC (NumStackMapFuncSkipped, "Number of functions skipped")
STATISTIC (NumBBsVisited, "Number of basic blocks visited")
STATISTIC (NumBBsHaveNoStackmap, "Number of basic blocks with no stackmap")
STATISTIC (NumStackMaps, "Number of StackMaps visited")
INITIALIZE_PASS (StackMapLiveness, "stackmap-liveness", "StackMap Liveness Analysis", false, false) StackMapLiveness
Default construct and initialize the pass.
Variables
static cl::opt< bool > EnablePatchPointLiveness ("enable-patchpoint-liveness", cl::Hidden, cl::init(true), cl::desc("Enable PatchPoint Liveness Analysis Pass"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "stackmaps"
Definition at line 29 of file StackMapLivenessAnalysis.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (StackMapLiveness , "stackmap-liveness" , "StackMap Liveness Analysis" , false , false)
Default construct and initialize the pass.
Definition at line 87 of file StackMapLivenessAnalysis.cpp.
References llvm::MachineInstr::addOperand(), llvm::MachineFunction::allocateRegMask(), llvm::MachineOperand::CreateRegLiveOut(), llvm::dbgs(), E, EnablePatchPointLiveness, llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getName(), llvm::PassRegistry::getPassRegistry(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasPatchPoint(), I, llvm::initializeStackMapLivenessPass(), LLVM_DEBUG, llvm::BitmaskEnumDetail::Mask(), MI, Reg, llvm::AnalysisUsage::setPreservesAll(), llvm::AnalysisUsage::setPreservesCFG(), and TRI.
STATISTIC() [1/5]
STATISTIC (NumStackMapFuncVisited , "Number of functions visited")
STATISTIC() [2/5]
STATISTIC (NumStackMapFuncSkipped , "Number of functions skipped")
STATISTIC() [3/5]
STATISTIC (NumBBsVisited , "Number of basic blocks visited")
STATISTIC() [4/5]
STATISTIC (NumBBsHaveNoStackmap , "Number of basic blocks with no stackmap")
STATISTIC() [5/5]
STATISTIC (NumStackMaps , "Number of StackMaps visited")
Variable Documentation
EnablePatchPointLiveness
cl::opt<bool> EnablePatchPointLiveness("enable-patchpoint-liveness", cl::Hidden, cl::init(true), cl::desc("Enable PatchPoint Liveness Analysis Pass")) static
Referenced by INITIALIZE_PASS().