LLVM: lib/Transforms/IPO/StripDeadPrototypes.cpp File Reference
StripDeadPrototypes.cpp File Reference
#include "llvm/Transforms/IPO/StripDeadPrototypes.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/IPO.h"
Macros
#define DEBUG_TYPE "strip-dead-prototypes"
Functions
STATISTIC (NumDeadPrototypes, "Number of dead prototypes removed")
static bool stripDeadPrototypes (Module &M)
INITIALIZE_PASS (StripDeadPrototypesLegacyPass, "strip-dead-prototypes", "Strip Unused Function Prototypes", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "strip-dead-prototypes"
Definition at line 25 of file StripDeadPrototypes.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (StripDeadPrototypesLegacyPass , "strip-dead-prototypes" , "Strip Unused Function Prototypes" , false , false)
Definition at line 83 of file StripDeadPrototypes.cpp.
STATISTIC()
STATISTIC (NumDeadPrototypes , "Number of dead prototypes removed")
stripDeadPrototypes()
static bool stripDeadPrototypes (Module & M) static
Definition at line 29 of file StripDeadPrototypes.cpp.
References llvm::Module::begin(), E, llvm::Module::end(), llvm::GlobalVariable::eraseFromParent(), llvm::Function::eraseFromParent(), F(), llvm::Module::global_begin(), llvm::Module::global_end(), I, llvm::GlobalValue::isDeclaration(), and llvm::Value::use_empty().
Referenced by llvm::StripDeadPrototypesPass::run().