LLVM: lib/Support/StringRef.cpp File Reference
StringRef.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/edit_distance.h"
#include "llvm/Support/Error.h"
#include <bitset>
Functions
static int ascii_strncasecmp (const char *LHS, const char *RHS, size_t Length)
static unsigned GetAutoSenseRadix (StringRef &Str)
Function Documentation
ascii_strncasecmp()
static int ascii_strncasecmp (const char * LHS, const char * RHS, size_t Length) static
Definition at line 27 of file StringRef.cpp.
References I, and llvm::toLower().
Referenced by llvm::StringRef::compare_lower(), llvm::StringRef::endswith_lower(), and llvm::StringRef::startswith_lower().
GetAutoSenseRadix()
static unsigned GetAutoSenseRadix (StringRef & Str) static
Definition at line 389 of file StringRef.cpp.
References llvm::StringRef::empty(), llvm::isDigit(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::consumeUnsignedInteger(), and llvm::StringRef::getAsInteger().