LLVM: llvm::MemorySanitizerPass Struct Reference
llvm::MemorySanitizerPass Struct Reference
A function pass for msan instrumentation.
#include "llvm/Transforms/Instrumentation/MemorySanitizer.h"
Public Member Functions
MemorySanitizerPass (MemorySanitizerOptions Options)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MemorySanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A function pass for msan instrumentation.
Instruments functions to detect unitialized reads. This function pass inserts calls to runtime library functions. If the functions aren't declared yet, the pass inserts the declarations. Otherwise the existing globals are used.
Definition at line 39 of file MemorySanitizer.h.
Constructor & Destructor Documentation
MemorySanitizerPass()
llvm::MemorySanitizerPass::MemorySanitizerPass (MemorySanitizerOptions Options) inline
Definition at line 40 of file MemorySanitizer.h.
References F().
Member Function Documentation
run() [1/2]
PreservedAnalyses MemorySanitizerPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 648 of file MemorySanitizer.cpp.
References llvm::PreservedAnalyses::all(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
run() [2/2]
PreservedAnalyses MemorySanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 656 of file MemorySanitizer.cpp.
References llvm::PreservedAnalyses::all(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/MemorySanitizer.h
lib/Transforms/Instrumentation/MemorySanitizer.cpp