LLVM: llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type > Struct Template Reference
llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type > Struct Template Reference
Implementation of format_provider<T> for c-style strings and string objects such as std::string and llvm::StringRef.
#include "llvm/Support/FormatProviders.h"
Static Public Member Functions
static void format (const T &V, llvm::raw_ostream &Stream, StringRef Style)
Detailed Description
template<typename T>
struct llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >
Implementation of format_provider<T> for c-style strings and string objects such as std::string and llvm::StringRef.
The options string of a string type has the grammar:
string_options :: [length]
where length is an optional integer specifying the maximum number of characters in the string to print. If length is omitted, the string is printed up to the null terminator.
Definition at line 200 of file FormatProviders.h.
Member Function Documentation
format()
template<typename T > static void llvm::format_provider< T, typename std::enable_if< detail::use_string_formatter< T >::value >::type >::format (const T & V, llvm::raw_ostream & Stream, StringRef Style) inline static
Definition at line 202 of file FormatProviders.h.
References assert(), llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), N, llvm::StringRef::npos, and llvm::StringRef::substr().
The documentation for this struct was generated from the following file:
include/llvm/Support/FormatProviders.h