LLVM: llvm::format_provider< std::chrono::duration< Rep, Period > > Struct Template Reference
llvm::format_provider< std::chrono::duration< Rep, Period > > Struct Template Reference
#include "llvm/Support/Chrono.h"
Static Public Member Functions
static void format (const Dur &D, llvm::raw_ostream &Stream, StringRef Style)
Detailed Description
template<typename Rep, typename Period>
struct llvm::format_provider< std::chrono::duration< Rep, Period > >
Definition at line 112 of file Chrono.h.
Member Function Documentation
format()
template<typename Rep , typename Period > static void llvm::format_provider< std::chrono::duration< Rep, Period > >::format (const Dur & D, llvm::raw_ostream & Stream, StringRef Style) inline static
Definition at line 154 of file Chrono.h.
References assert(), llvm::count(), llvm::StringRef::empty(), and llvm::format().
The documentation for this struct was generated from the following file:
include/llvm/Support/Chrono.h