LLVM: llvm::DenseMapInfo< VTableSlotSummary > Struct Template Reference
llvm::DenseMapInfo< VTableSlotSummary > Struct Template Reference
Static Public Member Functions
static VTableSlotSummary getEmptyKey ()
static VTableSlotSummary getTombstoneKey ()
static unsigned getHashValue (const VTableSlotSummary &I)
static bool isEqual (const VTableSlotSummary &LHS, const VTableSlotSummary &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< VTableSlotSummary >
Definition at line 285 of file WholeProgramDevirt.cpp.
Member Function Documentation
getEmptyKey()
static VTableSlotSummary llvm::DenseMapInfo< VTableSlotSummary >::getEmptyKey () inline static
Definition at line 286 of file WholeProgramDevirt.cpp.
getHashValue()
static unsigned llvm::DenseMapInfo< VTableSlotSummary >::getHashValue (const VTableSlotSummary & I) inline static
Definition at line 294 of file WholeProgramDevirt.cpp.
References llvm::VTableSlotSummary::ByteOffset, and llvm::VTableSlotSummary::TypeID.
getTombstoneKey()
static VTableSlotSummary llvm::DenseMapInfo< VTableSlotSummary >::getTombstoneKey () inline static
Definition at line 290 of file WholeProgramDevirt.cpp.
isEqual()
static bool llvm::DenseMapInfo< VTableSlotSummary >::isEqual (const VTableSlotSummary & LHS, const VTableSlotSummary & RHS) inline static
Definition at line 298 of file WholeProgramDevirt.cpp.
References llvm::AnalysisUsage::addRequired(), Arg, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_empty(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::arg_end(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), B, llvm::tgtok::Bit, llvm::tgtok::Bits, llvm::VTableSlotSummary::ByteOffset, C, llvm::BranchInst::Create(), DEBUG_TYPE, llvm::dyn_cast(), F(), llvm::X86AS::FS, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCaller(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::DataLayout::getIntPtrType(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getType(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeWholeProgramDevirtPass(), Int32Ty, llvm::HexagonISD::JT, llvm::make_range(), Name, and llvm::VTableSlotSummary::TypeID.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/WholeProgramDevirt.cpp