LLVM: llvm::MachineFunctionInfo Struct Reference
llvm::MachineFunctionInfo Struct Reference
MachineFunctionInfo - This class can be derived from and used by targets to hold private target-specific information for each MachineFunction.
#include "llvm/CodeGen/MachineFunction.h"
Public Member Functions
virtual ~MachineFunctionInfo ()
Static Public Member Functions
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
MachineFunctionInfo - This class can be derived from and used by targets to hold private target-specific information for each MachineFunction.
Objects of type are accessed/created with MF::getInfo and destroyed when the MachineFunction is destroyed.
Definition at line 94 of file MachineFunction.h.
Constructor & Destructor Documentation
~MachineFunctionInfo()
MachineFunctionInfo::~MachineFunctionInfo () virtual default
Referenced by llvm::MachineFunctionProperties::print(), and llvm::MachineFunction::~MachineFunction().
Member Function Documentation
create()
template<typename Ty > static Ty* llvm::MachineFunctionInfo::create (BumpPtrAllocator & Allocator, MachineFunction & MF) inline static
Factory function: default behavior is to call new using the supplied allocator.
This function can be overridden in a derive class.
Definition at line 102 of file MachineFunction.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineFunction.cpp