LLVM: llvm::Intrinsic::IITDescriptor Struct Reference
llvm::Intrinsic::IITDescriptor Struct Reference
This is a type descriptor which explains the type requirements of an intrinsic.
#include "llvm/IR/Intrinsics.h"
Public Types
enum IITDescriptorKind {
Void, VarArg, MMX, Token,
Metadata, Half, Float, Double,
Quad, Integer, Vector, Pointer,
Struct, Argument, ExtendArgument, TruncArgument,
HalfVecArgument, SameVecWidthArgument, PtrToArgument, PtrToElt,
VecOfAnyPtrsToElt, VecElementArgument, ScalableVecArgument, Subdivide2Argument,
Subdivide4Argument, VecOfBitcastsToInt
}
enum ArgKind {
AK_Any, AK_AnyInteger, AK_AnyFloat, AK_AnyVector,
AK_AnyPointer, AK_MatchType = 7
}
Public Member Functions
unsigned getArgumentNumber () const
ArgKind getArgumentKind () const
unsigned getOverloadArgNumber () const
unsigned getRefArgNumber () const
Static Public Member Functions
static IITDescriptor get (IITDescriptorKind K, unsigned Field)
static IITDescriptor get (IITDescriptorKind K, unsigned short Hi, unsigned short Lo)
Public Attributes
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind Kind
union {
unsigned Integer_Width
unsigned Float_Width
unsigned Vector_Width
unsigned Pointer_AddressSpace
unsigned Struct_NumElements
unsigned Argument_Info
};
Detailed Description
This is a type descriptor which explains the type requirements of an intrinsic.
This is returned by getIntrinsicInfoTableEntries.
Definition at line 100 of file Intrinsics.h.
Member Enumeration Documentation
ArgKind
enum llvm::Intrinsic::IITDescriptor::ArgKind
Enumerator
AK_Any
AK_AnyInteger
AK_AnyFloat
AK_AnyVector
AK_AnyPointer
AK_MatchType
Definition at line 119 of file Intrinsics.h.
IITDescriptorKind
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind
Enumerator
Void
VarArg
MMX
Token
Metadata
Half
Float
Double
Quad
Integer
Vector
Pointer
Struct
Argument
ExtendArgument
TruncArgument
HalfVecArgument
SameVecWidthArgument
PtrToArgument
PtrToElt
VecOfAnyPtrsToElt
VecElementArgument
ScalableVecArgument
Subdivide2Argument
Subdivide4Argument
VecOfBitcastsToInt
Definition at line 101 of file Intrinsics.h.
Member Function Documentation
get() [1/2]
static IITDescriptor llvm::Intrinsic::IITDescriptor::get (IITDescriptorKind K, unsigned Field) inline static
Definition at line 157 of file Intrinsics.h.
References llvm::tgtok::Field.
get() [2/2]
static IITDescriptor llvm::Intrinsic::IITDescriptor::get (IITDescriptorKind K, unsigned short Hi, unsigned short Lo) inline static
Definition at line 162 of file Intrinsics.h.
References llvm::tgtok::Field, llvm::Intrinsic::getIntrinsicInfoTableEntries(), and llvm::MipsISD::Lo.
getArgumentKind()
ArgKind llvm::Intrinsic::IITDescriptor::getArgumentKind () const inline
Definition at line 137 of file Intrinsics.h.
References Argument_Info, assert(), ExtendArgument, HalfVecArgument, PtrToArgument, SameVecWidthArgument, Subdivide2Argument, Subdivide4Argument, TruncArgument, VecElementArgument, and VecOfBitcastsToInt.
getArgumentNumber()
unsigned llvm::Intrinsic::IITDescriptor::getArgumentNumber () const inline
Definition at line 128 of file Intrinsics.h.
References Argument_Info, assert(), ExtendArgument, HalfVecArgument, PtrToArgument, PtrToElt, SameVecWidthArgument, Subdivide2Argument, Subdivide4Argument, TruncArgument, VecElementArgument, and VecOfBitcastsToInt.
getOverloadArgNumber()
unsigned llvm::Intrinsic::IITDescriptor::getOverloadArgNumber () const inline
Definition at line 148 of file Intrinsics.h.
References Argument_Info, assert(), and VecOfAnyPtrsToElt.
getRefArgNumber()
unsigned llvm::Intrinsic::IITDescriptor::getRefArgNumber () const inline
Definition at line 152 of file Intrinsics.h.
References Argument_Info, assert(), and VecOfAnyPtrsToElt.
Member Data Documentation
@250
union { ... }
Argument_Info
unsigned llvm::Intrinsic::IITDescriptor::Argument_Info
Definition at line 116 of file Intrinsics.h.
Referenced by getArgumentKind(), getArgumentNumber(), getOverloadArgNumber(), and getRefArgNumber().
Float_Width
unsigned llvm::Intrinsic::IITDescriptor::Float_Width
Definition at line 112 of file Intrinsics.h.
Integer_Width
unsigned llvm::Intrinsic::IITDescriptor::Integer_Width
Definition at line 111 of file Intrinsics.h.
Kind
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind llvm::Intrinsic::IITDescriptor::Kind
Referenced by llvm::Intrinsic::matchIntrinsicVarArg().
Pointer_AddressSpace
unsigned llvm::Intrinsic::IITDescriptor::Pointer_AddressSpace
Definition at line 114 of file Intrinsics.h.
Struct_NumElements
unsigned llvm::Intrinsic::IITDescriptor::Struct_NumElements
Definition at line 115 of file Intrinsics.h.
Vector_Width
unsigned llvm::Intrinsic::IITDescriptor::Vector_Width
Definition at line 113 of file Intrinsics.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/Intrinsics.h