LLVM: llvm::DenseMapInfo< MCRegister > Struct Template Reference
llvm::DenseMapInfo< MCRegister > Struct Template Reference
#include "llvm/MC/MCRegister.h"
Static Public Member Functions
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
static unsigned getHashValue (const MCRegister &Val)
static bool isEqual (const MCRegister &LHS, const MCRegister &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< MCRegister >
Definition at line 93 of file MCRegister.h.
Member Function Documentation
getEmptyKey()
static unsigned llvm::DenseMapInfo< MCRegister >::getEmptyKey () inline static
Definition at line 94 of file MCRegister.h.
getHashValue()
static unsigned llvm::DenseMapInfo< MCRegister >::getHashValue (const MCRegister & Val) inline static
Definition at line 100 of file MCRegister.h.
References llvm::MCRegister::id().
getTombstoneKey()
static unsigned llvm::DenseMapInfo< MCRegister >::getTombstoneKey () inline static
Definition at line 97 of file MCRegister.h.
isEqual()
static bool llvm::DenseMapInfo< MCRegister >::isEqual (const MCRegister & LHS, const MCRegister & RHS) inline static
Definition at line 103 of file MCRegister.h.
References llvm::MCRegister::id(), and isEqual().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCRegister.h