LLVM: DeadCodeElimination::SetQueue< T > Struct Template Reference
DeadCodeElimination::SetQueue< T > Struct Template Reference
Public Member Functions
SetQueue ()
bool empty () const
T pop_front ()
void push_back (T V)
Detailed Description
template<typename T>
struct DeadCodeElimination::SetQueue< T >
Definition at line 28 of file RDFDeadCode.cpp.
Constructor & Destructor Documentation
SetQueue()
template<typename T> DeadCodeElimination::SetQueue< T >::SetQueue () inline
Definition at line 29 of file RDFDeadCode.cpp.
Member Function Documentation
empty()
template<typename T> bool DeadCodeElimination::SetQueue< T >::empty () const inline
Definition at line 31 of file RDFDeadCode.cpp.
pop_front()
template<typename T> T DeadCodeElimination::SetQueue< T >::pop_front () inline
Definition at line 34 of file RDFDeadCode.cpp.
push_back()
template<typename T> void DeadCodeElimination::SetQueue< T >::push_back (T V) inline
Definition at line 40 of file RDFDeadCode.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::RefNode::getOwner(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::rdf::NodeAddr< T >::Id, llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isPHI(), llvm::MachineInstr::isPosition(), llvm::MachineInstr::isReturn(), llvm::MachineInstr::mayStore(), llvm::rdf::CodeNode::members(), llvm::rdf::CodeNode::members_if(), MI, MRI, llvm::MachineInstr::operands(), DeadCodeElimination::SetQueue< T >::push_back(), RA, llvm::NVPTX::PTXCvtMode::RN, llvm::rdf::NodeAttrs::Stmt, and llvm::X86II::TA.
Referenced by DeadCodeElimination::SetQueue< T >::push_back().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/RDFDeadCode.cpp