LLVM: llvm::LocationMetadata Struct Reference
llvm::LocationMetadata Struct Reference
Frontend-provided metadata for source location.
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
Public Member Functions
LocationMetadata ()=default
bool empty () const
void parse (MDNode *MDN)
Public Attributes
StringRef Filename
int LineNo = 0
int ColumnNo = 0
Detailed Description
Frontend-provided metadata for source location.
Definition at line 24 of file AddressSanitizer.h.
Constructor & Destructor Documentation
LocationMetadata()
llvm::LocationMetadata::LocationMetadata () default
Member Function Documentation
empty()
bool llvm::LocationMetadata::empty () const inline
Definition at line 31 of file AddressSanitizer.h.
References llvm::StringRef::empty(), and parse().
parse()
void LocationMetadata::parse (MDNode * MDN)
Definition at line 1114 of file AddressSanitizer.cpp.
References assert(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::MDString::getString().
Referenced by empty(), and llvm::GlobalsMetadata::GlobalsMetadata().
Member Data Documentation
ColumnNo
int llvm::LocationMetadata::ColumnNo = 0
Definition at line 27 of file AddressSanitizer.h.
Referenced by createPrivateGlobalForSourceLoc().
Filename
StringRef llvm::LocationMetadata::Filename
Definition at line 25 of file AddressSanitizer.h.
Referenced by createPrivateGlobalForSourceLoc().
LineNo
int llvm::LocationMetadata::LineNo = 0
Definition at line 26 of file AddressSanitizer.h.
Referenced by createPrivateGlobalForSourceLoc().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/AddressSanitizer.h
lib/Transforms/Instrumentation/AddressSanitizer.cpp