LLVM: llvm::ILPValue Struct Reference
llvm::ILPValue Struct Reference
Represent the ILP of the subDAG rooted at a DAG node.
#include "llvm/CodeGen/ScheduleDFS.h"
Public Member Functions
ILPValue (unsigned count, unsigned length)
bool operator< (ILPValue RHS) const
bool operator> (ILPValue RHS) const
bool operator<= (ILPValue RHS) const
bool operator>= (ILPValue RHS) const
void print (raw_ostream &OS) const
void dump () const
Public Attributes
unsigned InstrCount
unsigned Length
Length may either correspond to depth or height, depending on direction, and cycles or nodes depending on context.
Detailed Description
Represent the ILP of the subDAG rooted at a DAG node.
ILPValues summarize the DAG subtree rooted at each node. ILPValues are valid for all nodes regardless of their subtree membership.
When computed using bottom-up DFS, this metric assumes that the DAG is a forest of trees with roots at the bottom of the schedule branching upward.
Definition at line 34 of file ScheduleDFS.h.
Constructor & Destructor Documentation
ILPValue()
llvm::ILPValue::ILPValue (unsigned count, unsigned length) inline
Definition at line 40 of file ScheduleDFS.h.
Referenced by llvm::SchedDFSResult::getILP().
Member Function Documentation
dump()
LLVM_DUMP_METHOD void ILPValue::dump () const
Definition at line 1511 of file ScheduleDAGInstrs.cpp.
References llvm::dbgs(), and LLVM_DUMP_METHOD.
Referenced by operator>=().
operator<()
bool llvm::ILPValue::operator< (ILPValue RHS) const inline
Definition at line 44 of file ScheduleDFS.h.
References InstrCount, and Length.
operator<=()
bool llvm::ILPValue::operator<= (ILPValue RHS) const inline
Definition at line 51 of file ScheduleDFS.h.
References InstrCount, and Length.
operator>()
bool llvm::ILPValue::operator> (ILPValue RHS) const inline
Definition at line 48 of file ScheduleDFS.h.
operator>=()
bool llvm::ILPValue::operator>= (ILPValue RHS) const inline
Definition at line 55 of file ScheduleDFS.h.
References dump(), and print().
print()
LLVM_DUMP_METHOD void ILPValue::print (raw_ostream & OS) const
Definition at line 1503 of file ScheduleDAGInstrs.cpp.
References llvm::format(), and InstrCount.
Referenced by llvm::operator<<(), and operator>=().
Member Data Documentation
InstrCount
unsigned llvm::ILPValue::InstrCount
Definition at line 35 of file ScheduleDFS.h.
Referenced by operator<(), and operator<=().
Length
unsigned llvm::ILPValue::Length
Length may either correspond to depth or height, depending on direction, and cycles or nodes depending on context.
Definition at line 38 of file ScheduleDFS.h.
Referenced by operator<(), and operator<=().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/ScheduleDFS.h
lib/CodeGen/ScheduleDAGInstrs.cpp