LLVM: llvm::MDNodeKeyImpl< DILexicalBlock > Struct Template Reference
llvm::MDNodeKeyImpl< DILexicalBlock > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *File, unsigned Line, unsigned Column)
MDNodeKeyImpl (const DILexicalBlock *N)
bool isKeyOf (const DILexicalBlock *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * File
unsigned Line
unsigned Column
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILexicalBlock >
Definition at line 728 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DILexicalBlock >::MDNodeKeyImpl (Metadata * Scope, Metadata * File, unsigned Line, unsigned Column) inline
Definition at line 734 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DILexicalBlock >::MDNodeKeyImpl (const DILexicalBlock * N) inline
Definition at line 736 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::getHashValue () const inline
Definition at line 745 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DILexicalBlock >::isKeyOf (const DILexicalBlock * RHS) const inline
Definition at line 740 of file LLVMContextImpl.h.
References llvm::DILexicalBlock::getColumn(), llvm::DILexicalBlock::getLine(), llvm::DIScope::getRawFile(), and llvm::DILexicalBlockBase::getRawScope().
Member Data Documentation
Column
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::Column
Definition at line 732 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DILexicalBlock >::File
Definition at line 730 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DILexicalBlock >::Line
Definition at line 731 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DILexicalBlock >::Scope
Definition at line 729 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h