LLVM: llvm::DWARFDebugArangeSet::Descriptor Struct Reference
llvm::DWARFDebugArangeSet::Descriptor Struct Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h"
Public Member Functions
uint64_t getEndAddress () const
void dump (raw_ostream &OS, uint32_t AddressSize) const
Public Attributes
uint64_t Address
uint64_t Length
Detailed Description
Definition at line 40 of file DWARFDebugArangeSet.h.
Member Function Documentation
dump()
void DWARFDebugArangeSet::Descriptor::dump (raw_ostream & OS, uint32_t AddressSize) const
Definition at line 19 of file DWARFDebugArangeSet.cpp.
References Address, llvm::format(), and getEndAddress().
getEndAddress()
uint64_t llvm::DWARFDebugArangeSet::Descriptor::getEndAddress () const inline
Definition at line 44 of file DWARFDebugArangeSet.h.
References llvm::DWARFDebugArangeSet::dump(), and llvm::DWARFDebugArangeSet::Header::Length.
Referenced by dump().
Member Data Documentation
Address
uint64_t llvm::DWARFDebugArangeSet::Descriptor::Address
Definition at line 41 of file DWARFDebugArangeSet.h.
Referenced by dump(), and llvm::DWARFDebugArangeSet::extract().
Length
uint64_t llvm::DWARFDebugArangeSet::Descriptor::Length
Definition at line 42 of file DWARFDebugArangeSet.h.
Referenced by llvm::DWARFDebugArangeSet::extract().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h
lib/DebugInfo/DWARF/DWARFDebugArangeSet.cpp