LLVM: llvm::DeadArgumentEliminationPass::RetOrArg Struct Reference
llvm::DeadArgumentEliminationPass::RetOrArg Struct Reference
Struct that represents (part of) either a return value or a function argument.
#include "llvm/Transforms/IPO/DeadArgumentElimination.h"
Public Member Functions
RetOrArg (const Function *F, unsigned Idx, bool IsArg)
bool operator< (const RetOrArg &O) const
Make RetOrArg comparable, so we can put it into a map.
bool operator== (const RetOrArg &O) const
Make RetOrArg comparable, so we can easily iterate the multimap.
std::string getDescription () const
Public Attributes
const Function * F
unsigned Idx
bool IsArg
Detailed Description
Struct that represents (part of) either a return value or a function argument.
Used so that arguments and return values can be used interchangeably.
Definition at line 44 of file DeadArgumentElimination.h.
Constructor & Destructor Documentation
RetOrArg()
llvm::DeadArgumentEliminationPass::RetOrArg::RetOrArg (const Function * F, unsigned Idx, bool IsArg) inline
Definition at line 49 of file DeadArgumentElimination.h.
Referenced by llvm::DeadArgumentEliminationPass::CreateArg(), and llvm::DeadArgumentEliminationPass::CreateRet().
Member Function Documentation
getDescription()
std::string llvm::DeadArgumentEliminationPass::RetOrArg::getDescription () const inline
Definition at line 62 of file DeadArgumentElimination.h.
References llvm::Value::getName().
operator<()
bool llvm::DeadArgumentEliminationPass::RetOrArg::operator< (const RetOrArg & O) const inline
Make RetOrArg comparable, so we can put it into a map.
Definition at line 53 of file DeadArgumentElimination.h.
References F, Idx, and IsArg.
operator==()
bool llvm::DeadArgumentEliminationPass::RetOrArg::operator== (const RetOrArg & O) const inline
Make RetOrArg comparable, so we can easily iterate the multimap.
Definition at line 58 of file DeadArgumentElimination.h.
References F, Idx, and IsArg.
Member Data Documentation
F
const Function* llvm::DeadArgumentEliminationPass::RetOrArg::F
Definition at line 45 of file DeadArgumentElimination.h.
Referenced by operator<(), and operator==().
Idx
unsigned llvm::DeadArgumentEliminationPass::RetOrArg::Idx
Definition at line 46 of file DeadArgumentElimination.h.
Referenced by operator<(), and operator==().
IsArg
bool llvm::DeadArgumentEliminationPass::RetOrArg::IsArg
Definition at line 47 of file DeadArgumentElimination.h.
Referenced by operator<(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/DeadArgumentElimination.h