LLVM: llvm::ArgDescriptor Struct Reference
llvm::ArgDescriptor Struct Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
ArgDescriptor (unsigned Val=0, unsigned Mask=~0u, bool IsStack=false, bool IsSet=false)
bool isSet () const
operator bool () const
bool isRegister () const
Register getRegister () const
unsigned getStackOffset () const
unsigned getMask () const
bool isMasked () const
void print (raw_ostream &OS, const TargetRegisterInfo *TRI=nullptr) const
Static Public Member Functions
static ArgDescriptor createRegister (Register Reg, unsigned Mask=~0u)
static ArgDescriptor createStack (unsigned Offset, unsigned Mask=~0u)
static ArgDescriptor createArg (const ArgDescriptor &Arg, unsigned Mask)
Friends
struct AMDGPUFunctionArgInfo
class AMDGPUArgumentUsageInfo
Detailed Description
Definition at line 26 of file AMDGPUArgumentUsageInfo.h.
Constructor & Destructor Documentation
ArgDescriptor()
llvm::ArgDescriptor::ArgDescriptor (unsigned Val = 0, unsigned Mask = ~0u, bool IsStack = false, bool IsSet = false) inline
Definition at line 43 of file AMDGPUArgumentUsageInfo.h.
Referenced by createArg(), createRegister(), and createStack().
Member Function Documentation
createArg()
static ArgDescriptor llvm::ArgDescriptor::createArg (const ArgDescriptor & Arg, unsigned Mask) inline static
Definition at line 55 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor(), and Reg.
Referenced by allocateVGPR32Input(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and llvm::SITargetLowering::passSpecialInputs().
createRegister()
static ArgDescriptor llvm::ArgDescriptor::createRegister (Register Reg, unsigned Mask = ~0u) inline static
Definition at line 47 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor().
Referenced by llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), allocateSGPR32InputImpl(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), allocateVGPR32Input(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::SIMachineFunctionInfo::setPrivateSegmentWaveByteOffset(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
createStack()
static ArgDescriptor llvm::ArgDescriptor::createStack (unsigned Offset, unsigned Mask = ~0u) inline static
Definition at line 51 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor().
Referenced by allocateVGPR32Input(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
getMask()
unsigned llvm::ArgDescriptor::getMask () const inline
Definition at line 81 of file AMDGPUArgumentUsageInfo.h.
Referenced by llvm::AMDGPULegalizerInfo::loadInputValue(), and llvm::AMDGPUTargetLowering::loadInputValue().
getRegister()
Register llvm::ArgDescriptor::getRegister () const inline
Definition at line 71 of file AMDGPUArgumentUsageInfo.h.
References assert(), and Reg.
Referenced by llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), llvm::SIMachineFunctionInfo::getImplicitBufferPtrUserSGPR(), llvm::SIMachineFunctionInfo::getPrivateSegmentWaveByteOffsetSystemSGPR(), llvm::SIMachineFunctionInfo::getQueuePtrUserSGPR(), llvm::SIMachineFunctionInfo::getWorkGroupIDSGPR(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::SITargetLowering::passSpecialInputs().
getStackOffset()
unsigned llvm::ArgDescriptor::getStackOffset () const inline
Definition at line 76 of file AMDGPUArgumentUsageInfo.h.
References assert(), and StackOffset.
Referenced by llvm::AMDGPUTargetLowering::loadInputValue().
isMasked()
bool llvm::ArgDescriptor::isMasked () const inline
Definition at line 85 of file AMDGPUArgumentUsageInfo.h.
References print(), and TRI.
Referenced by llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::SITargetLowering::passSpecialInputs().
isRegister()
bool llvm::ArgDescriptor::isRegister () const inline
Definition at line 67 of file AMDGPUArgumentUsageInfo.h.
Referenced by llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), and llvm::SITargetLowering::passSpecialInputs().
isSet()
bool llvm::ArgDescriptor::isSet () const inline
Definition at line 59 of file AMDGPUArgumentUsageInfo.h.
Referenced by operator bool().
operator bool()
llvm::ArgDescriptor::operator bool () const inline explicit
Definition at line 63 of file AMDGPUArgumentUsageInfo.h.
References isSet().
print()
void llvm::ArgDescriptor::print (raw_ostream & OS, const TargetRegisterInfo * TRI = nullptr) const
Referenced by llvm::AMDGPUArgumentUsageInfo::getAnalysisUsage(), isMasked(), and llvm::operator<<().
Friends And Related Function Documentation
AMDGPUArgumentUsageInfo
friend class AMDGPUArgumentUsageInfo friend
Definition at line 29 of file AMDGPUArgumentUsageInfo.h.
AMDGPUFunctionArgInfo
friend struct AMDGPUFunctionArgInfo friend
Definition at line 28 of file AMDGPUArgumentUsageInfo.h.
Member Data Documentation
Reg
Register llvm::ArgDescriptor::Reg
Definition at line 32 of file AMDGPUArgumentUsageInfo.h.
Referenced by createArg(), and getRegister().
StackOffset
unsigned llvm::ArgDescriptor::StackOffset
Definition at line 33 of file AMDGPUArgumentUsageInfo.h.
Referenced by getStackOffset().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h