LLVM: llvm::LanaiRegisterInfo Struct Reference
llvm::LanaiRegisterInfo Struct Reference
#include "Target/Lanai/LanaiRegisterInfo.h"
Public Member Functions
LanaiRegisterInfo ()
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
unsigned getRARegister () const
Register getFrameRegister (const MachineFunction &MF) const override
Register getBaseRegister () const
bool hasBasePointer (const MachineFunction &MF) const
int getDwarfRegNum (unsigned RegNum, bool IsEH) const
Detailed Description
Definition at line 23 of file LanaiRegisterInfo.h.
Constructor & Destructor Documentation
LanaiRegisterInfo()
LanaiRegisterInfo::LanaiRegisterInfo ()
Definition at line 35 of file LanaiRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void LanaiRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 136 of file LanaiRegisterInfo.cpp.
References llvm::LPAC::ADD, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineInstr::eraseFromParent(), llvm::RegScavenger::FindUnusedReg(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), getBaseRegister(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getOppositeALULoOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRRMOpcodeVariant(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasBasePointer(), llvm::TargetFrameLowering::hasFP(), llvm::LPCC::ICC_T, isALUArithLoOpcode(), llvm::isInt< 16 >(), llvm::isRMOpcode(), llvm::isSPLSOpcode(), llvm_unreachable, MI, Reg, llvm::RegScavenger::scavengeRegister(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::LPAC::SUB, and TII.
getBaseRegister()
Register LanaiRegisterInfo::getBaseRegister () const
Definition at line 266 of file LanaiRegisterInfo.cpp.
Referenced by llvm::LanaiFrameLowering::determineCalleeSaves(), eliminateFrameIndex(), and getReservedRegs().
getCalleeSavedRegs()
const uint16_t * LanaiRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = nullptr) const override
Definition at line 38 of file LanaiRegisterInfo.cpp.
getCallPreservedMask()
const uint32_t * LanaiRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const override
Definition at line 269 of file LanaiRegisterInfo.cpp.
Referenced by CC_Lanai32_VarArg().
getDwarfRegNum()
int llvm::LanaiRegisterInfo::getDwarfRegNum (unsigned RegNum, bool IsEH) const
getFrameRegister()
Register LanaiRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 262 of file LanaiRegisterInfo.cpp.
Referenced by eliminateFrameIndex().
getRARegister()
unsigned LanaiRegisterInfo::getRARegister () const
Definition at line 259 of file LanaiRegisterInfo.cpp.
Referenced by llvm::LanaiTargetLowering::LowerRETURNADDR().
getReservedRegs()
BitVector LanaiRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 42 of file LanaiRegisterInfo.cpp.
References getBaseRegister(), hasBasePointer(), R2, R4, and llvm::BitVector::set().
hasBasePointer()
bool LanaiRegisterInfo::hasBasePointer (const MachineFunction & MF) const
Definition at line 249 of file LanaiRegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::LanaiFrameLowering::determineCalleeSaves(), eliminateFrameIndex(), and getReservedRegs().
requiresRegisterScavenging()
bool LanaiRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const override
Definition at line 64 of file LanaiRegisterInfo.cpp.
trackLivenessAfterRegAlloc()
bool LanaiRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const override
Definition at line 69 of file LanaiRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/Lanai/LanaiRegisterInfo.h
lib/Target/Lanai/LanaiRegisterInfo.cpp