LLVM: llvm::LaneBitmask Struct Reference
llvm::LaneBitmask Struct Reference
#include "llvm/MC/LaneBitmask.h"
Public Types
enum : unsigned { BitWidth = 8*sizeof(Type) }
using Type = unsigned
Public Member Functions
constexpr LaneBitmask ()=default
constexpr LaneBitmask (Type V)
constexpr bool operator== (LaneBitmask M) const
constexpr bool operator!= (LaneBitmask M) const
constexpr bool operator< (LaneBitmask M) const
constexpr bool none () const
constexpr bool any () const
constexpr bool all () const
constexpr LaneBitmask operator~ () const
constexpr LaneBitmask operator| (LaneBitmask M) const
constexpr LaneBitmask operator & (LaneBitmask M) const
LaneBitmask & operator|= (LaneBitmask M)
LaneBitmask & operator &= (LaneBitmask M)
constexpr Type getAsInteger () const
unsigned getNumLanes () const
unsigned getHighestLane () const
Static Public Member Functions
static constexpr LaneBitmask getNone ()
static constexpr LaneBitmask getAll ()
static constexpr LaneBitmask getLane (unsigned Lane)
Static Public Attributes
static constexpr const char *const FormatStr = "%08X"
Detailed Description
Definition at line 39 of file LaneBitmask.h.
Member Typedef Documentation
Type
using llvm::LaneBitmask::Type = unsigned
Definition at line 41 of file LaneBitmask.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
BitWidth
Definition at line 42 of file LaneBitmask.h.
Constructor & Destructor Documentation
LaneBitmask() [1/2]
constexpr llvm::LaneBitmask::LaneBitmask () default
Referenced by getLane(), getNone(), operator &(), operator|(), and operator~().
LaneBitmask() [2/2]
constexpr llvm::LaneBitmask::LaneBitmask (Type V) inline explicit
Definition at line 46 of file LaneBitmask.h.
Member Function Documentation
all()
constexpr bool llvm::LaneBitmask::all () const inline
Definition at line 53 of file LaneBitmask.h.
Referenced by llvm::LivePhysRegs::available(), llvm::LiveRangeCalc::createDeadDefs(), llvm::SplitEditor::dump(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), getMopState(), and llvm::rdf::operator<<().
any()
constexpr bool llvm::LaneBitmask::any () const inline
Definition at line 52 of file LaneBitmask.h.
Referenced by addRegLanes(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::RegPressureTracker::advance(), llvm::LivePhysRegs::available(), decreaseSetPressure(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::SplitEditor::dump(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::GCNRegPressure::inc(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), instAccessReg(), isCrossCopy(), isDefInSubRange(), llvm::rdf::RegisterRef::operator bool(), llvm::RegPressureTracker::recede(), llvm::LiveInterval::refineSubRanges(), removeRegLanes(), llvm::rdf::DataFlowGraph::restrictRef(), llvm::LiveIntervals::HMEditor::updateAllRanges(), updateLiveIn(), and llvm::MachineFunction::verify().
getAll()
static constexpr LaneBitmask llvm::LaneBitmask::getAll () inline static
Definition at line 83 of file LaneBitmask.h.
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::MachineBasicBlock::addLiveIn(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::LiveRangeCalc::calculate(), ComputeCommonTailLength(), llvm::LiveRangeCalc::constructMainRangeFromSubranges(), llvm::SplitEditor::dump(), llvm::LiveRangeCalc::extendToUses(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::LaneMaskIndex::getLaneMaskForIndex(), llvm::ScheduleDAGInstrs::getLaneMaskForMO(), getLanesWithProperty(), getLiveLanesAt(), llvm::RegPressureTracker::getLiveLanesAt(), getMopState(), isCrossCopy(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::rdf::PhysicalRegisterInfo::mapTo(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::LiveIntervals::removeAllRegUnitsForPhysReg(), llvm::RegScavenger::scavengeRegister(), toString(), updateLiveIn(), and llvm::LiveInterval::verify().
getAsInteger()
constexpr Type llvm::LaneBitmask::getAsInteger () const inline
Definition at line 73 of file LaneBitmask.h.
Referenced by getSubRegForIndex(), and llvm::PrintLaneMask().
getHighestLane()
unsigned llvm::LaneBitmask::getHighestLane () const inline
Definition at line 78 of file LaneBitmask.h.
References llvm::Log2_32().
Referenced by getMopState().
getLane()
static constexpr LaneBitmask llvm::LaneBitmask::getLane (unsigned Lane) inline static
Definition at line 84 of file LaneBitmask.h.
References LaneBitmask().
Referenced by getUsedRegMask().
getNone()
static constexpr LaneBitmask llvm::LaneBitmask::getNone () inline static
Definition at line 82 of file LaneBitmask.h.
References LaneBitmask().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::ScheduleDAGMILive::collectVRegUses(), computeLiveOuts(), llvm::LiveRegSet::contains(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::SplitEditor::dump(), llvm::LiveRegSet::erase(), findUseBetween(), getLanesWithProperty(), llvm::RegPressureTracker::getLastUsedLanes(), llvm::RegPressureTracker::getLiveThroughAt(), getRegLanes(), llvm::getRegPressure(), llvm::RegPressureTracker::initLiveThru(), llvm::LiveRegSet::insert(), isCrossCopy(), isDefInSubRange(), llvm::RegPressureTracker::recede(), setRegZero(), llvm::LiveIntervals::shrinkToUses(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
getNumLanes()
unsigned llvm::LaneBitmask::getNumLanes () const inline
Definition at line 75 of file LaneBitmask.h.
References llvm::countPopulation().
Referenced by llvm::SplitEditor::dump(), and getMopState().
none()
constexpr bool llvm::LaneBitmask::none () const inline
Definition at line 51 of file LaneBitmask.h.
Referenced by llvm::LiveRegUnits::addRegMasked(), llvm::RegisterOperands::adjustLaneLiveness(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::rdf::Liveness::computePhiInfo(), decreaseSetPressure(), findUseBetween(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::GCNRegPressure::inc(), llvm::RegPressureTracker::increaseRegPressure(), increaseSetPressure(), llvm::rdf::RegisterAggr::makeRegRef(), llvm::RegPressureTracker::recede(), and llvm::LiveInterval::refineSubRanges().
operator &()
constexpr LaneBitmask llvm::LaneBitmask::operator& (LaneBitmask M) const inline
Definition at line 61 of file LaneBitmask.h.
References LaneBitmask().
operator &=()
LaneBitmask& llvm::LaneBitmask::operator&= (LaneBitmask M) inline
Definition at line 68 of file LaneBitmask.h.
operator!=()
constexpr bool llvm::LaneBitmask::operator!= (LaneBitmask M) const inline
Definition at line 49 of file LaneBitmask.h.
operator<()
constexpr bool llvm::LaneBitmask::operator< (LaneBitmask M) const inline
Definition at line 50 of file LaneBitmask.h.
operator==()
constexpr bool llvm::LaneBitmask::operator== (LaneBitmask M) const inline
Definition at line 48 of file LaneBitmask.h.
operator|()
constexpr LaneBitmask llvm::LaneBitmask::operator| (LaneBitmask M) const inline
Definition at line 58 of file LaneBitmask.h.
References LaneBitmask().
operator|=()
LaneBitmask& llvm::LaneBitmask::operator|= (LaneBitmask M) inline
Definition at line 64 of file LaneBitmask.h.
operator~()
constexpr LaneBitmask llvm::LaneBitmask::operator~ () const inline
Definition at line 55 of file LaneBitmask.h.
References LaneBitmask().
Member Data Documentation
FormatStr
constexpr const char* const llvm::LaneBitmask::FormatStr = "%08X" static
Definition at line 43 of file LaneBitmask.h.
Referenced by llvm::PrintLaneMask().
The documentation for this struct was generated from the following file:
include/llvm/MC/LaneBitmask.h