LLVM: llvm::DiagnosticInfoMIROptimization::MachineArgument Struct Reference
llvm::DiagnosticInfoMIROptimization::MachineArgument Struct Reference
MI-specific kinds of diagnostic Arguments.
#include "llvm/CodeGen/MachineOptimizationRemarkEmitter.h"
Public Member Functions
MachineArgument (StringRef Key, const MachineInstr &MI)
Print an entire MachineInstr.
Public Member Functions inherited from llvm::DiagnosticInfoOptimizationBase::Argument
Argument (StringRef Str="")
Argument (StringRef Key, const Value *V)
Argument (StringRef Key, const Type *T)
Argument (StringRef Key, StringRef S)
Argument (StringRef Key, const char *S)
Argument (StringRef Key, int N)
Argument (StringRef Key, float N)
Argument (StringRef Key, long N)
Argument (StringRef Key, long long N)
Argument (StringRef Key, unsigned N)
Argument (StringRef Key, unsigned long N)
Argument (StringRef Key, unsigned long long N)
Argument (StringRef Key, bool B)
Argument (StringRef Key, DebugLoc dl)
Additional Inherited Members
Public Attributes inherited from llvm::DiagnosticInfoOptimizationBase::Argument
std::string Key
std::string Val
DiagnosticLocation Loc
Detailed Description
MI-specific kinds of diagnostic Arguments.
Definition at line 39 of file MachineOptimizationRemarkEmitter.h.
Constructor & Destructor Documentation
MachineArgument()
DiagnosticInfoMIROptimization::MachineArgument::MachineArgument (StringRef Key, const MachineInstr & MI)
Print an entire MachineInstr.
Definition at line 24 of file MachineOptimizationRemarkEmitter.cpp.
References llvm::DiagnosticInfoMIROptimization::getBlock(), llvm::DiagnosticInfoOptimizationBase::Argument::Key, llvm::None, llvm::MachineInstr::print(), llvm::Remark, llvm::DiagnosticInfoOptimizationBase::setHotness(), and llvm::DiagnosticInfoOptimizationBase::Argument::Val.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineOptimizationRemarkEmitter.h
lib/CodeGen/MachineOptimizationRemarkEmitter.cpp