LLVM: llvm::DefaultContextualFoldingSetTrait< T, Ctx > Struct Template Reference
llvm::DefaultContextualFoldingSetTrait< T, Ctx > Struct Template Reference
DefaultContextualFoldingSetTrait - Like DefaultFoldingSetTrait, but for ContextualFoldingSets.
#include "llvm/ADT/FoldingSet.h"
Static Public Member Functions
static void Profile (T &X, FoldingSetNodeID &ID, Ctx Context)
static bool Equals (T &X, const FoldingSetNodeID &ID, unsigned IDHash, FoldingSetNodeID &TempID, Ctx Context)
static unsigned ComputeHash (T &X, FoldingSetNodeID &TempID, Ctx Context)
Detailed Description
template<typename T, typename Ctx>
struct llvm::DefaultContextualFoldingSetTrait< T, Ctx >
DefaultContextualFoldingSetTrait - Like DefaultFoldingSetTrait, but for ContextualFoldingSets.
Definition at line 255 of file FoldingSet.h.
Member Function Documentation
ComputeHash()
template<typename T , typename Ctx > unsigned llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash (T & X, FoldingSetNodeID & TempID, Ctx Context) inline static
Definition at line 390 of file FoldingSet.h.
References llvm::FoldingSetNodeID::ComputeHash(), and llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile().
Equals()
template<typename T , typename Ctx > bool llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals (T & X, const FoldingSetNodeID & ID, unsigned IDHash, FoldingSetNodeID & TempID, Ctx Context) inline static
Definition at line 380 of file FoldingSet.h.
References llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile().
Profile()
template<typename T , typename Ctx > static void llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile (T & X, FoldingSetNodeID & ID, Ctx Context) inline static
Definition at line 256 of file FoldingSet.h.
References llvm::IndexedInstrProf::ComputeHash(), Context, and X.
Referenced by llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash(), and llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals().
The documentation for this struct was generated from the following file:
include/llvm/ADT/FoldingSet.h