LLVM: llvm::PassRegistrationListener Struct Reference
llvm::PassRegistrationListener Struct Reference
PassRegistrationListener class - This class is meant to be derived from by clients that are interested in which passes get registered and unregistered at runtime (which can be because of the RegisterPass constructors being run as the program starts up, or may be because a shared object just got loaded).
#include "llvm/PassSupport.h"
Public Member Functions
PassRegistrationListener ()=default
virtual ~PassRegistrationListener ()=default
virtual void passRegistered (const PassInfo *)
Callback functions - These functions are invoked whenever a pass is loaded or removed from the current executable.
void enumeratePasses ()
enumeratePasses - Iterate over the registered passes, calling the passEnumerate callback on each PassInfo object.
virtual void passEnumerate (const PassInfo *)
passEnumerate - Callback function invoked when someone calls enumeratePasses on this PassRegistrationListener object.
Detailed Description
PassRegistrationListener class - This class is meant to be derived from by clients that are interested in which passes get registered and unregistered at runtime (which can be because of the RegisterPass constructors being run as the program starts up, or may be because a shared object just got loaded).
Definition at line 196 of file PassSupport.h.
Constructor & Destructor Documentation
PassRegistrationListener()
llvm::PassRegistrationListener::PassRegistrationListener () default
~PassRegistrationListener()
virtual llvm::PassRegistrationListener::~PassRegistrationListener () virtual default
Member Function Documentation
enumeratePasses()
void PassRegistrationListener::enumeratePasses ()
enumeratePasses - Iterate over the registered passes, calling the passEnumerate callback on each PassInfo object.
Definition at line 213 of file Pass.cpp.
References llvm::PassRegistry::enumerateWith(), and llvm::PassRegistry::getPassRegistry().
Referenced by llvm::PassNameParser::initialize().
passEnumerate()
virtual void llvm::PassRegistrationListener::passEnumerate (const PassInfo *) inline virtual
passEnumerate - Callback function invoked when someone calls enumeratePasses on this PassRegistrationListener object.
Reimplemented in llvm::PassNameParser.
Definition at line 210 of file PassSupport.h.
Referenced by llvm::PassRegistry::enumerateWith().
passRegistered()
virtual void llvm::PassRegistrationListener::passRegistered (const PassInfo *) inline virtual
Callback functions - These functions are invoked whenever a pass is loaded or removed from the current executable.
Reimplemented in llvm::PassNameParser.
Definition at line 202 of file PassSupport.h.
The documentation for this struct was generated from the following files:
include/llvm/PassSupport.h
lib/IR/Pass.cpp