LLVM: llvm::rdf::TargetOperandInfo Struct Reference
llvm::rdf::TargetOperandInfo Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Public Member Functions
TargetOperandInfo (const TargetInstrInfo &tii)
virtual ~TargetOperandInfo ()=default
virtual bool isPreserving (const MachineInstr &In, unsigned OpNum) const
virtual bool isClobbering (const MachineInstr &In, unsigned OpNum) const
virtual bool isFixedReg (const MachineInstr &In, unsigned OpNum) const
Public Attributes
const TargetInstrInfo & TII
Detailed Description
Definition at line 414 of file RDFGraph.h.
Constructor & Destructor Documentation
TargetOperandInfo()
llvm::rdf::TargetOperandInfo::TargetOperandInfo (const TargetInstrInfo & tii) inline
Definition at line 415 of file RDFGraph.h.
References llvm::tgtok::In.
~TargetOperandInfo()
virtual llvm::rdf::TargetOperandInfo::~TargetOperandInfo () virtual default
Member Function Documentation
isClobbering()
bool TargetOperandInfo::isClobbering (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 604 of file RDFGraph.cpp.
References assert(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
isFixedReg()
bool TargetOperandInfo::isFixedReg (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 617 of file RDFGraph.cpp.
References D, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getImplicitDefs(), llvm::MCInstrDesc::getImplicitUses(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isReturn(), llvm::RISCVFenceField::O, llvm::MachineInstr::operands(), and Reg.
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
isPreserving()
bool TargetOperandInfo::isPreserving (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 598 of file RDFGraph.cpp.
References llvm::HexagonInstrInfo::isPredicated(), and TII.
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
Member Data Documentation
TII
const TargetInstrInfo& llvm::rdf::TargetOperandInfo::TII
Definition at line 422 of file RDFGraph.h.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFGraph.h
lib/Target/Hexagon/RDFGraph.cpp