LLVM: llvm::BitTracker::BitMask Struct Reference
llvm::BitTracker::BitMask Struct Reference
#include "Target/Hexagon/BitTracker.h"
Public Member Functions
BitMask ()=default
BitMask (uint16_t b, uint16_t e)
uint16_t first () const
uint16_t last () const
Detailed Description
Definition at line 286 of file BitTracker.h.
Constructor & Destructor Documentation
BitMask() [1/2]
llvm::BitTracker::BitMask::BitMask () default
BitMask() [2/2]
llvm::BitTracker::BitMask::BitMask (uint16_t b, uint16_t e) inline
Definition at line 288 of file BitTracker.h.
Member Function Documentation
first()
uint16_t llvm::BitTracker::BitMask::first () const inline
Definition at line 290 of file BitTracker.h.
References B.
Referenced by llvm::BitTracker::RegisterCell::extract(), llvm::BitTracker::RegisterCell::insert(), and llvm::BitTracker::subst().
last()
uint16_t llvm::BitTracker::BitMask::last () const inline
Definition at line 291 of file BitTracker.h.
References B, and E.
Referenced by llvm::BitTracker::RegisterCell::extract(), llvm::BitTracker::RegisterCell::insert(), and llvm::BitTracker::subst().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/BitTracker.h