LLVM: llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy > Struct Template Reference
llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy > Struct Template Reference
#include "llvm/IR/ModuleSummaryIndexYAML.h"
Static Public Member Functions
static void inputOne (IO &io, StringRef Key, GlobalValueSummaryMapTy &V)
static void output (IO &io, GlobalValueSummaryMapTy &V)
Detailed Description
template<>
struct llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >
Definition at line 204 of file ModuleSummaryIndexYAML.h.
Member Function Documentation
inputOne()
static void llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::inputOne (IO & io, StringRef Key, GlobalValueSummaryMapTy & V) inline static
Definition at line 205 of file ModuleSummaryIndexYAML.h.
References llvm::StringRef::getAsInteger(), and llvm::StringRef::str().
output()
static void llvm::yaml::CustomMappingTraits< GlobalValueSummaryMapTy >::output (IO & io, GlobalValueSummaryMapTy & V) inline static
Definition at line 235 of file ModuleSummaryIndexYAML.h.
References llvm::yaml::FunctionSummaryYaml::Linkage, P, llvm::utostr(), and VI.
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndexYAML.h