LLVM: llvm::remarks::YAMLRemarkSerializer Struct Reference
llvm::remarks::YAMLRemarkSerializer Struct Reference
Serialize the remarks to YAML.
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLRemarkSerializer (raw_ostream &OS, SerializerMode Mode, Optional< StringTable > StrTab=None)
void emit (const Remark &Remark) override
Emit a remark to the stream.
std::unique_ptr< MetaSerializer > metaSerializer (raw_ostream &OS, Optional< StringRef > ExternalFilename=None) override
Return the corresponding metadata serializer.
Public Member Functions inherited from llvm::remarks::RemarkSerializer
RemarkSerializer (Format SerializerFormat, raw_ostream &OS, SerializerMode Mode)
virtual ~RemarkSerializer ()=default
This is just an interface.
Static Public Member Functions
static bool classof (const RemarkSerializer *S)
Public Attributes
yaml::Output YAMLOutput
The YAML streamer.
Public Attributes inherited from llvm::remarks::RemarkSerializer
Format SerializerFormat
The format of the serializer.
raw_ostream & OS
The open raw_ostream that the remark diagnostics are emitted to.
SerializerMode Mode
The serialization mode.
Optional< StringTable > StrTab
The string table containing all the unique strings used in the output.
Protected Member Functions
YAMLRemarkSerializer (Format SerializerFormat, raw_ostream &OS, SerializerMode Mode, Optional< StringTable > StrTab=None)
Detailed Description
Serialize the remarks to YAML.
One remark entry looks like this: — !<TYPE> Pass: <PASSNAME> Name: <REMARKNAME> DebugLoc: { File: <SOURCEFILENAME>, Line: <SOURCELINE>, Column: <SOURCECOLUMN> } Function: <FUNCTIONNAME> Args:
<KEY>:
DebugLoc: { File: <FILE>, Line: <LINE>, Column: <COL> } ...
Definition at line 33 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLRemarkSerializer() [1/2]
YAMLRemarkSerializer::YAMLRemarkSerializer (raw_ostream & OS, SerializerMode Mode, Optional< StringTable > StrTab = None)
Definition at line 161 of file YAMLRemarkSerializer.cpp.
Referenced by classof().
YAMLRemarkSerializer() [2/2]
YAMLRemarkSerializer::YAMLRemarkSerializer (Format SerializerFormat, raw_ostream & OS, SerializerMode Mode, Optional< StringTable > StrTab = None) protected
Definition at line 165 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::RemarkSerializer::StrTab.
Member Function Documentation
classof()
static bool llvm::remarks::YAMLRemarkSerializer::classof (const RemarkSerializer * S) inline static
Definition at line 45 of file YAMLRemarkSerializer.h.
References llvm::remarks::RemarkSerializer::Mode, llvm::None, llvm::remarks::RemarkSerializer::OS, llvm::remarks::RemarkSerializer::SerializerFormat, llvm::remarks::RemarkSerializer::StrTab, llvm::remarks::YAML, and YAMLRemarkSerializer().
emit()
void YAMLRemarkSerializer::emit (const Remark & Remark) override virtual
Emit a remark to the stream.
Implements llvm::remarks::RemarkSerializer.
Reimplemented in llvm::remarks::YAMLStrTabRemarkSerializer.
Definition at line 173 of file YAMLRemarkSerializer.cpp.
References YAMLOutput.
Referenced by llvm::remarks::YAMLStrTabRemarkSerializer::emit(), llvm::remarks::YAMLMetaSerializer::YAMLMetaSerializer(), llvm::remarks::YAMLStrTabMetaSerializer::YAMLStrTabMetaSerializer(), and llvm::remarks::YAMLStrTabRemarkSerializer::YAMLStrTabRemarkSerializer().
metaSerializer()
std::unique_ptr< MetaSerializer > YAMLRemarkSerializer::metaSerializer (raw_ostream & OS, Optional< StringRef > ExternalFilename = None) override virtual
Return the corresponding metadata serializer.
Implements llvm::remarks::RemarkSerializer.
Reimplemented in llvm::remarks::YAMLStrTabRemarkSerializer.
Definition at line 181 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::RemarkSerializer::OS.
Referenced by llvm::remarks::YAMLStrTabRemarkSerializer::emit(), and llvm::remarks::YAMLStrTabRemarkSerializer::YAMLStrTabRemarkSerializer().
Member Data Documentation
YAMLOutput
yaml::Output llvm::remarks::YAMLRemarkSerializer::YAMLOutput
The YAML streamer.
Definition at line 35 of file YAMLRemarkSerializer.h.
Referenced by emit().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp