LLVM: llvm::BitTracker::BitValue Struct Reference
llvm::BitTracker::BitValue Struct Reference
#include "Target/Hexagon/BitTracker.h"
Public Types
enum ValueType { Top, Zero, One, Ref }
Public Member Functions
BitValue (ValueType T=Top)
BitValue (bool B)
BitValue (unsigned Reg, uint16_t Pos)
bool operator== (const BitValue &V) const
bool operator!= (const BitValue &V) const
bool is (unsigned T) const
bool meet (const BitValue &V, const BitRef &Self)
bool num () const
operator bool () const
Static Public Member Functions
static BitValue ref (const BitValue &V)
static BitValue self (const BitRef &Self=BitRef())
Public Attributes
ValueType Type
BitRef RefI
Friends
raw_ostream & operator<< (raw_ostream &OS, const BitValue &BV)
Detailed Description
Definition at line 154 of file BitTracker.h.
Member Enumeration Documentation
ValueType
enum llvm::BitTracker::BitValue::ValueType
Enumerator
Top
Zero
One
Ref
Definition at line 155 of file BitTracker.h.
Constructor & Destructor Documentation
BitValue() [1/3]
llvm::BitTracker::BitValue::BitValue (ValueType T = Top) inline
Definition at line 193 of file BitTracker.h.
BitValue() [2/3]
llvm::BitTracker::BitValue::BitValue (bool B) inline
Definition at line 194 of file BitTracker.h.
BitValue() [3/3]
llvm::BitTracker::BitValue::BitValue (unsigned Reg, uint16_t Pos) inline
Definition at line 195 of file BitTracker.h.
Member Function Documentation
is()
bool llvm::BitTracker::BitValue::is (unsigned T) const inline
Definition at line 208 of file BitTracker.h.
References assert().
Referenced by llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), llvm::BitTracker::MachineEvaluator::eNOT(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::eXOR(), INITIALIZE_PASS(), and isDebug().
meet()
bool llvm::BitTracker::BitValue::meet (const BitValue & V, const BitRef & Self) inline
Definition at line 228 of file BitTracker.h.
References llvm::Ref, RefI, and Type.
num()
bool llvm::BitTracker::BitValue::num () const inline
Definition at line 256 of file BitTracker.h.
Referenced by llvm::BitTracker::MachineEvaluator::eADD(), and llvm::BitTracker::MachineEvaluator::eSUB().
operator bool()
llvm::BitTracker::BitValue::operator bool () const inline
Definition at line 260 of file BitTracker.h.
References assert(), and llvm::operator<<().
operator!=()
bool llvm::BitTracker::BitValue::operator!= (const BitValue & V) const inline
Definition at line 204 of file BitTracker.h.
References llvm::operator==().
operator==()
bool llvm::BitTracker::BitValue::operator== (const BitValue & V) const inline
Definition at line 197 of file BitTracker.h.
References llvm::Ref, RefI, and Type.
ref()
BitTracker::BitValue llvm::BitTracker::BitValue::ref (const BitValue & V) inline static
Definition at line 270 of file BitTracker.h.
References llvm::BitTracker::BitRef::Pos, llvm::Ref, RefI, llvm::BitTracker::BitRef::Reg, and Type.
Referenced by llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::eXOR(), and llvm::BitTracker::RegisterCell::ref().
self()
BitTracker::BitValue llvm::BitTracker::BitValue::self (const BitRef & Self = BitRef()) inline static
Definition at line 279 of file BitTracker.h.
References llvm::BitTracker::BitRef::Pos, and llvm::BitTracker::BitRef::Reg.
Referenced by llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), llvm::BitTracker::MachineEvaluator::eMLS(), llvm::BitTracker::MachineEvaluator::eMLU(), llvm::BitTracker::MachineEvaluator::eNOT(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::eXOR(), and llvm::BitTracker::RegisterCell::self().
Friends And Related Function Documentation
operator<<
raw_ostream& operator<< (raw_ostream & OS, const BitValue & BV) friend
Definition at line 97 of file BitTracker.cpp.
Member Data Documentation
RefI
BitRef llvm::BitTracker::BitValue::RefI
Definition at line 191 of file BitTracker.h.
Referenced by llvm::BitTracker::MachineEvaluator::evaluate(), INITIALIZE_PASS(), isDebug(), meet(), llvm::operator<<(), operator==(), ref(), llvm::BitTracker::RegisterCell::regify(), and llvm::BitTracker::subst().
Type
ValueType llvm::BitTracker::BitValue::Type
Definition at line 190 of file BitTracker.h.
Referenced by llvm::BitTracker::MachineEvaluator::evaluate(), INITIALIZE_PASS(), isDebug(), meet(), llvm::operator<<(), operator==(), ref(), llvm::BitTracker::RegisterCell::regify(), and llvm::BitTracker::subst().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/BitTracker.h