LLVM: llvm::coro::LowererBase Struct Reference
llvm::coro::LowererBase Struct Reference
#include "Transforms/Coroutines/CoroInternal.h"
Public Member Functions
LowererBase (Module &M)
Value * makeSubFnCall (Value *Arg, int Index, Instruction *InsertPt)
Public Attributes
Module & TheModule
LLVMContext & Context
PointerType *const Int8Ptr
FunctionType *const ResumeFnType
ConstantPointerNull *const NullPtr
Detailed Description
Definition at line 55 of file CoroInternal.h.
Constructor & Destructor Documentation
LowererBase()
coro::LowererBase::LowererBase (Module & M)
Definition at line 95 of file Coroutines.cpp.
Member Function Documentation
makeSubFnCall()
Value * coro::LowererBase::makeSubFnCall (Value * Arg, int Index, Instruction * InsertPt)
Definition at line 108 of file Coroutines.cpp.
References Arg, assert(), llvm::MCID::Bitcast, Context, llvm::CallInst::Create(), llvm::ConstantInt::get(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt8Ty(), llvm::Type::getPointerTo(), llvm::CoroSubFnInst::IndexFirst, llvm::CoroSubFnInst::IndexLast, ResumeFnType, and TheModule.
Referenced by prepareForSplit().
Member Data Documentation
Context
LLVMContext& llvm::coro::LowererBase::Context
Definition at line 57 of file CoroInternal.h.
Referenced by makeSubFnCall().
Int8Ptr
PointerType* const llvm::coro::LowererBase::Int8Ptr
Definition at line 58 of file CoroInternal.h.
NullPtr
ConstantPointerNull* const llvm::coro::LowererBase::NullPtr
Definition at line 60 of file CoroInternal.h.
ResumeFnType
FunctionType* const llvm::coro::LowererBase::ResumeFnType
Definition at line 59 of file CoroInternal.h.
Referenced by makeSubFnCall().
TheModule
Module& llvm::coro::LowererBase::TheModule
Definition at line 56 of file CoroInternal.h.
Referenced by makeSubFnCall().
The documentation for this struct was generated from the following files:
lib/Transforms/Coroutines/CoroInternal.h
lib/Transforms/Coroutines/Coroutines.cpp