LLVM: llvm::DOTGraphTraits< ScheduleDAG * > Struct Template Reference
llvm::DOTGraphTraits< ScheduleDAG * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const SUnit *SU, const ScheduleDAG *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Static Public Member Functions
static std::string getGraphName (const ScheduleDAG *G)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const SUnit *Node)
static std::string getNodeIdentifierLabel (const SUnit *Node, const ScheduleDAG *Graph)
static std::string getEdgeAttributes (const SUnit *Node, SUnitIterator EI, const ScheduleDAG *Graph)
If you want to override the dot attributes printed for a particular edge, override this method.
static std::string getNodeAttributes (const SUnit *N, const ScheduleDAG *Graph)
static void addCustomGraphFeatures (ScheduleDAG *G, GraphWriter< ScheduleDAG *> &GW)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
static bool isNodeHidden (const void *)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
template<>
struct llvm::DOTGraphTraits< ScheduleDAG * >
Definition at line 26 of file ScheduleDAGPrinter.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< ScheduleDAG * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 28 of file ScheduleDAGPrinter.cpp.
Member Function Documentation
addCustomGraphFeatures()
static void llvm::DOTGraphTraits< ScheduleDAG * >::addCustomGraphFeatures (ScheduleDAG * G, GraphWriter< ScheduleDAG *> & GW) inline static
Definition at line 69 of file ScheduleDAGPrinter.cpp.
References llvm::ScheduleDAG::addCustomGraphFeatures(), G, llvm::ScheduleDAG::getGraphNodeLabel(), and llvm::DefaultDOTGraphTraits::getNodeLabel().
getEdgeAttributes()
static std::string llvm::DOTGraphTraits< ScheduleDAG * >::getEdgeAttributes (const SUnit * Node, SUnitIterator EI, const ScheduleDAG * Graph) inline static
If you want to override the dot attributes printed for a particular edge, override this method.
Definition at line 52 of file ScheduleDAGPrinter.cpp.
getGraphName()
static std::string llvm::DOTGraphTraits< ScheduleDAG * >::getGraphName (const ScheduleDAG * G) inline static
Definition at line 30 of file ScheduleDAGPrinter.cpp.
References llvm::MachineFunction::getName(), and llvm::ScheduleDAG::MF.
getNodeAttributes()
static std::string llvm::DOTGraphTraits< ScheduleDAG * >::getNodeAttributes (const SUnit * N, const ScheduleDAG * Graph) inline static
Definition at line 64 of file ScheduleDAGPrinter.cpp.
getNodeIdentifierLabel()
static std::string llvm::DOTGraphTraits< ScheduleDAG * >::getNodeIdentifierLabel (const SUnit * Node, const ScheduleDAG * Graph) inline static
Definition at line 42 of file ScheduleDAGPrinter.cpp.
getNodeLabel()
std::string llvm::DOTGraphTraits< ScheduleDAG * >::getNodeLabel (const SUnit * SU, const ScheduleDAG * Graph)
isNodeHidden()
static bool llvm::DOTGraphTraits< ScheduleDAG * >::isNodeHidden (const SUnit * Node) inline static
Definition at line 38 of file ScheduleDAGPrinter.cpp.
renderGraphFromBottomUp()
static bool llvm::DOTGraphTraits< ScheduleDAG * >::renderGraphFromBottomUp () inline static
Definition at line 34 of file ScheduleDAGPrinter.cpp.
The documentation for this struct was generated from the following file:
lib/CodeGen/ScheduleDAGPrinter.cpp