LLVM: llvm::yaml::ScalarTraits< StringValue > Struct Template Reference
llvm::yaml::ScalarTraits< StringValue > Struct Template Reference
#include "llvm/CodeGen/MIRYamlMapping.h"
Static Public Member Functions
static void output (const StringValue &S, void *, raw_ostream &OS)
static StringRef input (StringRef Scalar, void *Ctx, StringValue &S)
static QuotingType mustQuote (StringRef S)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< StringValue >
Definition at line 47 of file MIRYamlMapping.h.
Member Function Documentation
input()
static StringRef llvm::yaml::ScalarTraits< StringValue >::input (StringRef Scalar, void * Ctx, StringValue & S) inline static
Definition at line 52 of file MIRYamlMapping.h.
References llvm::yaml::Node::getSourceRange(), llvm::yaml::StringValue::SourceRange, llvm::StringRef::str(), and llvm::yaml::StringValue::Value.
Referenced by llvm::yaml::ScalarTraits< FlowStringValue >::input(), and llvm::yaml::BlockScalarTraits< BlockStringValue >::input().
mustQuote()
static QuotingType llvm::yaml::ScalarTraits< StringValue >::mustQuote (StringRef S) inline static
Definition at line 60 of file MIRYamlMapping.h.
output()
static void llvm::yaml::ScalarTraits< StringValue >::output (const StringValue & S, void * , raw_ostream & OS) inline static
Definition at line 48 of file MIRYamlMapping.h.
References llvm::yaml::StringValue::Value.
Referenced by llvm::yaml::ScalarTraits< FlowStringValue >::output(), and llvm::yaml::BlockScalarTraits< BlockStringValue >::output().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MIRYamlMapping.h