LLVM: llvm::remarks::ParsedStringTable Struct Reference
llvm::remarks::ParsedStringTable Struct Reference
In-memory representation of the string table parsed from a buffer (e.g.
#include "llvm/Remarks/RemarkParser.h"
Public Member Functions
ParsedStringTable (StringRef Buffer)
ParsedStringTable (const ParsedStringTable &)=delete
Disable copy.
ParsedStringTable & operator= (const ParsedStringTable &)=delete
ParsedStringTable (ParsedStringTable &&)=default
Should be movable.
ParsedStringTable & operator= (ParsedStringTable &&)=default
size_t size () const
Expected< StringRef > operator[] (size_t Index) const
Public Attributes
StringRef Buffer
The buffer mapped from the section contents.
std::vector< size_t > Offsets
This object has high changes to be std::move'd around, so don't use a SmallVector for once.
Detailed Description
In-memory representation of the string table parsed from a buffer (e.g.
the remarks section).
Definition at line 59 of file RemarkParser.h.
Constructor & Destructor Documentation
ParsedStringTable() [1/3]
ParsedStringTable::ParsedStringTable (StringRef Buffer)
Definition at line 26 of file RemarkParser.cpp.
References Buffer, llvm::StringRef::data(), llvm::StringRef::empty(), Offsets, and llvm::StringRef::split().
ParsedStringTable() [2/3]
llvm::remarks::ParsedStringTable::ParsedStringTable (const ParsedStringTable &) delete
Disable copy.
ParsedStringTable() [3/3]
llvm::remarks::ParsedStringTable::ParsedStringTable (ParsedStringTable &&) default
Should be movable.
Member Function Documentation
operator=() [1/2]
ParsedStringTable& llvm::remarks::ParsedStringTable::operator= (const ParsedStringTable &) delete
operator=() [2/2]
ParsedStringTable& llvm::remarks::ParsedStringTable::operator= (ParsedStringTable &&) default
operator[]()
Expected< StringRef > ParsedStringTable::operator[] (size_t Index) const
Definition at line 36 of file RemarkParser.cpp.
References Buffer, llvm::createStringError(), llvm::StringRef::data(), llvm::make_error_code(), Offsets, and llvm::StringRef::size().
size()
size_t llvm::remarks::ParsedStringTable::size () const inline
Definition at line 74 of file RemarkParser.h.
References llvm::remarks::createRemarkParser(), llvm::remarks::createRemarkParserFromMeta(), and llvm::None.
Referenced by llvm::remarks::StringTable::StringTable().
Member Data Documentation
Buffer
StringRef llvm::remarks::ParsedStringTable::Buffer
The buffer mapped from the section contents.
Definition at line 61 of file RemarkParser.h.
Referenced by operator[](), and ParsedStringTable().
Offsets
std::vector<size_t> llvm::remarks::ParsedStringTable::Offsets
This object has high changes to be std::move'd around, so don't use a SmallVector for once.
Definition at line 64 of file RemarkParser.h.
Referenced by operator[](), and ParsedStringTable().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/RemarkParser.h
lib/Remarks/RemarkParser.cpp