LLVM: llvm::GCOVOptions Struct Reference
llvm::GCOVOptions Struct Reference
#include "llvm/Transforms/Instrumentation.h"
Static Public Member Functions
static GCOVOptions getDefault ()
Public Attributes
bool EmitNotes
bool EmitData
char Version [4]
bool UseCfgChecksum
bool NoRedZone
bool FunctionNamesInData
bool ExitBlockBeforeBody
std::string Filter
std::string Exclude
Detailed Description
Definition at line 52 of file Instrumentation.h.
Member Function Documentation
getDefault()
GCOVOptions GCOVOptions::getDefault () static
Definition at line 58 of file GCOVProfiling.cpp.
References llvm::AnalysisUsage::addRequired(), assert(), DefaultExitBlockBeforeBody, DefaultGCOVVersion, EmitData, EmitNotes, ExitBlockBeforeBody, F(), function, FunctionNamesInData, llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, INITIALIZE_PASS_END(), llvm::initializeGCOVProfilerLegacyPassPass(), NoRedZone, llvm::report_fatal_error(), UseCfgChecksum, and Version.
Member Data Documentation
EmitData
bool llvm::GCOVOptions::EmitData
Definition at line 59 of file Instrumentation.h.
Referenced by getDefault().
EmitNotes
bool llvm::GCOVOptions::EmitNotes
Definition at line 56 of file Instrumentation.h.
Referenced by getDefault().
Exclude
std::string llvm::GCOVOptions::Exclude
Definition at line 84 of file Instrumentation.h.
ExitBlockBeforeBody
bool llvm::GCOVOptions::ExitBlockBeforeBody
Definition at line 78 of file Instrumentation.h.
Referenced by getDefault(), and getFilename().
Filter
std::string llvm::GCOVOptions::Filter
Definition at line 81 of file Instrumentation.h.
FunctionNamesInData
bool llvm::GCOVOptions::FunctionNamesInData
Definition at line 74 of file Instrumentation.h.
Referenced by getDefault().
NoRedZone
bool llvm::GCOVOptions::NoRedZone
Definition at line 70 of file Instrumentation.h.
Referenced by getDefault().
UseCfgChecksum
bool llvm::GCOVOptions::UseCfgChecksum
Definition at line 67 of file Instrumentation.h.
Referenced by getDefault(), and getFilename().
Version
char llvm::GCOVOptions::Version[4]
Definition at line 63 of file Instrumentation.h.
Referenced by getDefault().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation.h
lib/Transforms/Instrumentation/GCOVProfiling.cpp