LLVM: llvm::MDNodeKeyImpl< DIDerivedType > Struct Template Reference
llvm::MDNodeKeyImpl< DIDerivedType > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, Optional< unsigned > DWARFAddressSpace, unsigned Flags, Metadata *ExtraData)
MDNodeKeyImpl (const DIDerivedType *N)
bool isKeyOf (const DIDerivedType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
MDString * Name
Metadata * File
unsigned Line
Metadata * Scope
Metadata * BaseType
uint64_t SizeInBits
uint64_t OffsetInBits
uint32_t AlignInBits
Optional< unsigned > DWARFAddressSpace
unsigned Flags
Metadata * ExtraData
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIDerivedType >
Definition at line 405 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIDerivedType >::MDNodeKeyImpl (unsigned Tag, MDString * Name, Metadata * File, unsigned Line, Metadata * Scope, Metadata * BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, Optional< unsigned > DWARFAddressSpace, unsigned Flags, Metadata * ExtraData) inline
Definition at line 419 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIDerivedType >::MDNodeKeyImpl (const DIDerivedType * N) inline
Definition at line 428 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::getHashValue () const inline
Definition at line 448 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIDerivedType >::isKeyOf (const DIDerivedType * RHS) const inline
Definition at line 436 of file LLVMContextImpl.h.
References llvm::DIType::getAlignInBits(), llvm::DIType::getFlags(), llvm::DIType::getLine(), llvm::DIType::getOffsetInBits(), llvm::DIScope::getRawFile(), llvm::DIType::getRawName(), llvm::DIType::getRawScope(), llvm::DIType::getSizeInBits(), and llvm::DINode::getTag().
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DIDerivedType >::AlignInBits
Definition at line 414 of file LLVMContextImpl.h.
BaseType
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::BaseType
Definition at line 411 of file LLVMContextImpl.h.
DWARFAddressSpace
Optional<unsigned> llvm::MDNodeKeyImpl< DIDerivedType >::DWARFAddressSpace
Definition at line 415 of file LLVMContextImpl.h.
ExtraData
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::ExtraData
Definition at line 417 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::File
Definition at line 408 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Flags
Definition at line 416 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Line
Definition at line 409 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIDerivedType >::Name
Definition at line 407 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual().
OffsetInBits
uint64_t llvm::MDNodeKeyImpl< DIDerivedType >::OffsetInBits
Definition at line 413 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DIDerivedType >::Scope
Definition at line 410 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual().
SizeInBits
uint64_t llvm::MDNodeKeyImpl< DIDerivedType >::SizeInBits
Definition at line 412 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DIDerivedType >::Tag
Definition at line 406 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h