LLVM: llvm::MemoryDepChecker::Dependence Struct Reference
llvm::MemoryDepChecker::Dependence Struct Reference
Dependece between memory access instructions.
#include "llvm/Analysis/LoopAccessAnalysis.h"
Public Types
enum DepType {
NoDep, Unknown, Forward, ForwardButPreventsForwarding,
Backward, BackwardVectorizable, BackwardVectorizableButPreventsForwarding
}
The type of the dependence.
Public Member Functions
Dependence (unsigned Source, unsigned Destination, DepType Type)
Instruction * getSource (const LoopAccessInfo &LAI) const
Return the source instruction of the dependence.
Instruction * getDestination (const LoopAccessInfo &LAI) const
Return the destination instruction of the dependence.
bool isForward () const
Lexically forward dependence.
bool isBackward () const
Lexically backward dependence.
bool isPossiblyBackward () const
May be a lexically backward dependence type (includes Unknown).
void print (raw_ostream &OS, unsigned Depth, const SmallVectorImpl< Instruction *> &Instrs) const
Print the dependence.
Static Public Member Functions
static VectorizationSafetyStatus isSafeForVectorization (DepType Type)
Dependence types that don't prevent vectorization.
Public Attributes
unsigned Source
Index of the source of the dependence in the InstMap vector.
unsigned Destination
Index of the destination of the dependence in the InstMap vector.
DepType Type
The type of the dependence.
Static Public Attributes
static const char * DepName []
String version of the types.
Detailed Description
Dependece between memory access instructions.
Definition at line 113 of file LoopAccessAnalysis.h.
Member Enumeration Documentation
DepType
enum llvm::MemoryDepChecker::Dependence::DepType
The type of the dependence.
Enumerator
NoDep
Unknown
Forward
ForwardButPreventsForwarding
Backward
BackwardVectorizable
BackwardVectorizableButPreventsForwarding
Definition at line 115 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
Dependence()
llvm::MemoryDepChecker::Dependence::Dependence (unsigned Source, unsigned Destination, DepType Type) inline
Definition at line 152 of file LoopAccessAnalysis.h.
References llvm::Depth, and print().
Member Function Documentation
getDestination()
Instruction * llvm::MemoryDepChecker::Dependence::getDestination (const LoopAccessInfo & LAI) const inline
Return the destination instruction of the dependence.
Definition at line 781 of file LoopAccessAnalysis.h.
References llvm::LoopAccessInfo::getDepChecker(), and llvm::MemoryDepChecker::getMemoryInstructions().
getSource()
Instruction * llvm::MemoryDepChecker::Dependence::getSource (const LoopAccessInfo & LAI) const inline
Return the source instruction of the dependence.
Definition at line 776 of file LoopAccessAnalysis.h.
References llvm::LoopAccessInfo::getDepChecker(), llvm::MemoryDepChecker::getMemoryInstructions(), and llvm::Sched::Source.
isBackward()
bool MemoryDepChecker::Dependence::isBackward () const
Lexically backward dependence.
Definition at line 1254 of file LoopAccessAnalysis.cpp.
References llvm_unreachable, and llvm::Unknown.
isForward()
bool MemoryDepChecker::Dependence::isForward () const
Lexically forward dependence.
Definition at line 1274 of file LoopAccessAnalysis.cpp.
References llvm::dbgs(), LLVM_DEBUG, llvm_unreachable, and llvm::Unknown.
isPossiblyBackward()
bool MemoryDepChecker::Dependence::isPossiblyBackward () const
May be a lexically backward dependence type (includes Unknown).
Definition at line 1270 of file LoopAccessAnalysis.cpp.
References llvm::Unknown.
isSafeForVectorization()
MemoryDepChecker::VectorizationSafetyStatus MemoryDepChecker::Dependence::isSafeForVectorization (DepType Type) static
Dependence types that don't prevent vectorization.
Definition at line 1237 of file LoopAccessAnalysis.cpp.
References llvm_unreachable, and llvm::Unknown.
print()
void MemoryDepChecker::Dependence::print (raw_ostream & OS, unsigned Depth, const SmallVectorImpl< Instruction *> & Instrs) const
Print the dependence.
Instr is used to map the instruction indices to instructions.
Definition at line 1728 of file LoopAccessAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::dyn_cast(), llvm::LoopBase< BlockT, LoopT >::empty(), EnableMemAccessVersioning, llvm::MemoryLocation::get(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getModule(), llvm::Value::getName(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::BasicBlock::getParent(), llvm::getPtrStride(), llvm::getVectorIntrinsicIDForCall(), I, llvm::raw_ostream::indent(), llvm::Loop::isAnnotatedParallel(), llvm::TargetLibraryInfo::isFunctionVectorizable(), llvm::ARM_MB::LD, LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), llvm::Sched::Source, llvm::ARM_MB::ST, and llvm::AAMDNodes::TBAA.
Member Data Documentation
DepName
const char * MemoryDepChecker::Dependence::DepName static
Initial value:
= {
    "NoDep", "Unknown", "Forward", "ForwardButPreventsForwarding", "Backward",
    "BackwardVectorizable", "BackwardVectorizableButPreventsForwarding"}
String version of the types.
Definition at line 143 of file LoopAccessAnalysis.h.
Referenced by llvm::MemoryDepChecker::getInstructionsForAccess().
Destination
unsigned llvm::MemoryDepChecker::Dependence::Destination
Index of the destination of the dependence in the InstMap vector.
Definition at line 148 of file LoopAccessAnalysis.h.
Source
unsigned llvm::MemoryDepChecker::Dependence::Source
Index of the source of the dependence in the InstMap vector.
Definition at line 146 of file LoopAccessAnalysis.h.
Type
DepType llvm::MemoryDepChecker::Dependence::Type
The type of the dependence.
Definition at line 150 of file LoopAccessAnalysis.h.
The documentation for this struct was generated from the following files:
include/llvm/Analysis/LoopAccessAnalysis.h
lib/Analysis/LoopAccessAnalysis.cpp