LLVM: llvm::coverage::CounterMappingRegion Struct Reference
llvm::coverage::CounterMappingRegion Struct Reference
A Counter mapping region associates a source range with a specific counter.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Types
enum RegionKind { CodeRegion, ExpansionRegion, SkippedRegion, GapRegion }
Public Member Functions
CounterMappingRegion (Counter Count, unsigned FileID, unsigned ExpandedFileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd, RegionKind Kind)
LineColPair startLoc () const
LineColPair endLoc () const
Static Public Member Functions
static CounterMappingRegion makeRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd)
static CounterMappingRegion makeExpansion (unsigned FileID, unsigned ExpandedFileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd)
static CounterMappingRegion makeSkipped (unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd)
static CounterMappingRegion makeGapRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd)
Public Attributes
Counter Count
unsigned FileID
unsigned ExpandedFileID
unsigned LineStart
unsigned ColumnStart
unsigned LineEnd
unsigned ColumnEnd
RegionKind Kind
Detailed Description
A Counter mapping region associates a source range with a specific counter.
Definition at line 204 of file CoverageMapping.h.
Member Enumeration Documentation
RegionKind
enum llvm::coverage::CounterMappingRegion::RegionKind
Enumerator
CodeRegion
A CodeRegion associates some code with a counter.
ExpansionRegion
An ExpansionRegion represents a file expansion region that associates a source range with the expansion of a virtual source file, such as for a macro instantiation or #include file.
SkippedRegion
A SkippedRegion represents a source range with code that was skipped by a preprocessor or similar means.
GapRegion
A GapRegion is like a CodeRegion, but its count is only set as the line execution count when its the only region in the line.
Definition at line 205 of file CoverageMapping.h.
Constructor & Destructor Documentation
CounterMappingRegion()
llvm::coverage::CounterMappingRegion::CounterMappingRegion (Counter Count, unsigned FileID, unsigned ExpandedFileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd, RegionKind Kind) inline
Definition at line 228 of file CoverageMapping.h.
Member Function Documentation
endLoc()
LineColPair llvm::coverage::CounterMappingRegion::endLoc () const inline
Definition at line 268 of file CoverageMapping.h.
Referenced by llvm::coverage::CoverageMapping::load(), and llvm::coverage::CoverageMappingWriter::write().
makeExpansion()
static CounterMappingRegion llvm::coverage::CounterMappingRegion::makeExpansion (unsigned FileID, unsigned ExpandedFileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd) inline static
Definition at line 243 of file CoverageMapping.h.
makeGapRegion()
static CounterMappingRegion llvm::coverage::CounterMappingRegion::makeGapRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd) inline static
Definition at line 258 of file CoverageMapping.h.
makeRegion()
static CounterMappingRegion llvm::coverage::CounterMappingRegion::makeRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd) inline static
Definition at line 236 of file CoverageMapping.h.
makeSkipped()
static CounterMappingRegion llvm::coverage::CounterMappingRegion::makeSkipped (unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd) inline static
Definition at line 251 of file CoverageMapping.h.
startLoc()
LineColPair llvm::coverage::CounterMappingRegion::startLoc () const inline
Definition at line 264 of file CoverageMapping.h.
Referenced by llvm::coverage::CoverageMapping::load(), and llvm::coverage::CoverageMappingWriter::write().
Member Data Documentation
ColumnEnd
unsigned llvm::coverage::CounterMappingRegion::ColumnEnd
Definition at line 225 of file CoverageMapping.h.
ColumnStart
unsigned llvm::coverage::CounterMappingRegion::ColumnStart
Definition at line 225 of file CoverageMapping.h.
Count
Counter llvm::coverage::CounterMappingRegion::Count
Definition at line 223 of file CoverageMapping.h.
ExpandedFileID
unsigned llvm::coverage::CounterMappingRegion::ExpandedFileID
Definition at line 224 of file CoverageMapping.h.
FileID
unsigned llvm::coverage::CounterMappingRegion::FileID
Definition at line 224 of file CoverageMapping.h.
Referenced by isExpansion(), and llvm::coverage::CoverageMappingWriter::write().
Kind
RegionKind llvm::coverage::CounterMappingRegion::Kind
Definition at line 226 of file CoverageMapping.h.
Referenced by isExpansion(), llvm::coverage::CoverageMapping::load(), and llvm::coverage::CoverageMappingWriter::write().
LineEnd
unsigned llvm::coverage::CounterMappingRegion::LineEnd
Definition at line 225 of file CoverageMapping.h.
LineStart
unsigned llvm::coverage::CounterMappingRegion::LineStart
Definition at line 225 of file CoverageMapping.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h