LLVM: llvm::gvn::AvailableValueInBlock Struct Reference
llvm::gvn::AvailableValueInBlock Struct Reference
Represents an AvailableValue which can be rematerialized at the end of the associated BasicBlock.
Public Member Functions
Value * MaterializeAdjustedValue (LoadInst *LI, GVN &gvn) const
Emit code at the end of this block to adjust the value defined here to the specified type.
Static Public Member Functions
static AvailableValueInBlock get (BasicBlock *BB, AvailableValue &&AV)
static AvailableValueInBlock get (BasicBlock *BB, Value *V, unsigned Offset=0)
static AvailableValueInBlock getUndef (BasicBlock *BB)
Public Attributes
BasicBlock * BB = nullptr
BB - The basic block in question.
AvailableValue AV
AV - The actual available value.
Detailed Description
Represents an AvailableValue which can be rematerialized at the end of the associated BasicBlock.
Definition at line 239 of file GVN.cpp.
Member Function Documentation
get() [1/2]
static AvailableValueInBlock llvm::gvn::AvailableValueInBlock::get (BasicBlock * BB, AvailableValue && AV) inline static
Definition at line 246 of file GVN.cpp.
References AV, and BB.
Referenced by reportMayClobberedLoad().
get() [2/2]
static AvailableValueInBlock llvm::gvn::AvailableValueInBlock::get (BasicBlock * BB, Value * V, unsigned Offset = 0) inline static
Definition at line 253 of file GVN.cpp.
References llvm::gvn::AvailableValue::get().
getUndef()
static AvailableValueInBlock llvm::gvn::AvailableValueInBlock::getUndef (BasicBlock * BB) inline static
Definition at line 258 of file GVN.cpp.
References llvm::gvn::AvailableValue::getUndef().
Referenced by reportMayClobberedLoad().
MaterializeAdjustedValue()
Value* llvm::gvn::AvailableValueInBlock::MaterializeAdjustedValue (LoadInst * LI, GVN & gvn) const inline
Emit code at the end of this block to adjust the value defined here to the specified type.
This handles various coercion cases.
Definition at line 264 of file GVN.cpp.
References Arg, assert(), C, llvm::dyn_cast(), llvm::numbers::e, E, llvm::ExtractValueInst::getAggregateOperand(), llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::BinaryOpIntrinsic::getLHS(), llvm::ExtractValueInst::getNumIndices(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::BinaryOpIntrinsic::getRHS(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), I, llvm::ExtractValueInst::idx_begin(), llvm::ExtractValueInst::idx_end(), llvm::ARM_PROC::IE, llvm::Instruction::isCommutative(), llvm::CmpInst::makeCmpResultType(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::User::op_begin(), llvm::User::op_end(), llvm::GVN::ValueTable::operator=(), std::swap(), llvm::GVN::ValueTable::ValueTable(), and llvm::GVN::ValueTable::~ValueTable().
Member Data Documentation
AV
AvailableValue llvm::gvn::AvailableValueInBlock::AV
AV - The actual available value.
Definition at line 244 of file GVN.cpp.
Referenced by get().
BB
BasicBlock* llvm::gvn::AvailableValueInBlock::BB = nullptr
BB - The basic block in question.
Definition at line 241 of file GVN.cpp.
Referenced by get().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/GVN.cpp