LLVM: llvm::HexagonBlockRanges Struct Reference
llvm::HexagonBlockRanges Struct Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Classes
class IndexRange
class IndexType
class InstrIndexMap
struct PrintRangeMap
class RangeList
struct RegisterRef
Public Types
using RegisterSet = std::set< RegisterRef >
using RegToRangeMap = std::map< RegisterRef, RangeList >
Public Member Functions
HexagonBlockRanges (MachineFunction &MF)
RegToRangeMap computeLiveMap (InstrIndexMap &IndexMap)
RegToRangeMap computeDeadMap (InstrIndexMap &IndexMap, RegToRangeMap &LiveMap)
Static Public Member Functions
static RegisterSet expandToSubRegs (RegisterRef R, const MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI)
Detailed Description
Definition at line 30 of file HexagonBlockRanges.h.
Member Typedef Documentation
RegisterSet
using llvm::HexagonBlockRanges::RegisterSet = std::set<RegisterRef>
Definition at line 40 of file HexagonBlockRanges.h.
RegToRangeMap
using llvm::HexagonBlockRanges::RegToRangeMap = std::map<RegisterRef, RangeList>
Definition at line 142 of file HexagonBlockRanges.h.
Constructor & Destructor Documentation
HexagonBlockRanges()
HexagonBlockRanges::HexagonBlockRanges (MachineFunction & MF)
Definition at line 219 of file HexagonBlockRanges.cpp.
References expandToSubRegs(), llvm::MCSubRegIndexIterator::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), I, llvm::MCSubRegIndexIterator::isValid(), llvm::MachineBasicBlock::liveins(), MRI, llvm::TargetRegisterInfo::regclasses(), SI, TII, and TRI.
Member Function Documentation
computeDeadMap()
HexagonBlockRanges::RegToRangeMap HexagonBlockRanges::computeDeadMap (InstrIndexMap & IndexMap, RegToRangeMap & LiveMap)
Definition at line 431 of file HexagonBlockRanges.cpp.
References llvm::dbgs(), llvm::SIInstrFlags::DS, llvm::HexagonBlockRanges::IndexType::Entry, llvm::HexagonBlockRanges::IndexType::Exit, expandToSubRegs(), F(), llvm::HexagonBlockRanges::InstrIndexMap::getBlock(), llvm::HexagonBlockRanges::InstrIndexMap::getNextIndex(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineBasicBlock::getParent(), llvm::HexagonBlockRanges::InstrIndexMap::getPrevIndex(), llvm::MachineFunction::getRegInfo(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, MRI, llvm::HexagonBlockRanges::IndexType::None, P, and llvm::Z.
computeLiveMap()
HexagonBlockRanges::RegToRangeMap HexagonBlockRanges::computeLiveMap (InstrIndexMap & IndexMap)
Definition at line 421 of file HexagonBlockRanges.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
expandToSubRegs()
HexagonBlockRanges::RegisterSet HexagonBlockRanges::expandToSubRegs (RegisterRef R, const MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI) static
Definition at line 261 of file HexagonBlockRanges.cpp.
References assert(), llvm::TargetRegisterClass::begin(), llvm::HexagonBlockRanges::IndexType::Entry, llvm::HexagonBlockRanges::IndexType::Exit, llvm::HexagonBlockRanges::InstrIndexMap::getBlock(), llvm::HexagonBlockRanges::InstrIndexMap::getIndex(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), I, llvm::tgtok::In, llvm::Register::isPhysicalRegister(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCSubRegIndexIterator::isValid(), llvm::Register::isVirtualRegister(), llvm::ARM_MB::LD, llvm::Left, N, llvm::HexagonBlockRanges::IndexType::None, P, llvm::HexagonBlockRanges::RegisterRef::Reg, and llvm::HexagonBlockRanges::RegisterRef::Sub.
Referenced by computeDeadMap(), llvm::HexagonFrameLowering::determineCalleeSaves(), and HexagonBlockRanges().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonBlockRanges.h
lib/Target/Hexagon/HexagonBlockRanges.cpp