LLVM: llvm::remarks::BitstreamRemarkParser Struct Reference
llvm::remarks::BitstreamRemarkParser Struct Reference
Parses and holds the state of the latest parsed remark.
#include "Remarks/BitstreamRemarkParser.h"
Public Member Functions
BitstreamRemarkParser (StringRef Buf)
Create a parser that expects to find a string table embedded in the stream.
BitstreamRemarkParser (StringRef Buf, ParsedStringTable StrTab)
Create a parser that uses a pre-parsed string table.
Expected< std::unique_ptr< Remark > > next () override
If no error occurs, this returns a valid Remark object.
Error parseMeta ()
Parse and process the metadata of the buffer.
Expected< std::unique_ptr< Remark > > parseRemark ()
Parse a Bitstream remark.
Public Member Functions inherited from llvm::remarks::RemarkParser
RemarkParser (Format ParserFormat)
virtual ~RemarkParser ()=default
Static Public Member Functions
static bool classof (const RemarkParser *P)
Public Attributes
BitstreamParserHelper ParserHelper
The buffer to parse.
Optional< ParsedStringTable > StrTab
The string table used for parsing strings.
std::unique_ptr< MemoryBuffer > TmpRemarkBuffer
Temporary remark buffer used when the remarks are stored separately.
uint64_t ContainerVersion = 0
The common metadata used to decide how to parse the buffer.
uint64_t RemarkVersion = 0
BitstreamRemarkContainerType ContainerType
bool ReadyToParseRemarks = false
Wether the parser is ready to parse remarks.
Public Attributes inherited from llvm::remarks::RemarkParser
Format ParserFormat
The format of the parser.
std::string ExternalFilePrependPath
Path to prepend when opening an external remark file.
Detailed Description
Parses and holds the state of the latest parsed remark.
Definition at line 28 of file BitstreamRemarkParser.h.
Constructor & Destructor Documentation
BitstreamRemarkParser() [1/2]
llvm::remarks::BitstreamRemarkParser::BitstreamRemarkParser (StringRef Buf) inline explicit
Create a parser that expects to find a string table embedded in the stream.
Definition at line 46 of file BitstreamRemarkParser.h.
BitstreamRemarkParser() [2/2]
llvm::remarks::BitstreamRemarkParser::BitstreamRemarkParser (StringRef Buf, ParsedStringTable StrTab) inline
Create a parser that uses a pre-parsed string table.
Definition at line 50 of file BitstreamRemarkParser.h.
References next().
Member Function Documentation
classof()
static bool llvm::remarks::BitstreamRemarkParser::classof (const RemarkParser * P) inline static
Definition at line 56 of file BitstreamRemarkParser.h.
References llvm::remarks::Bitstream, llvm::remarks::createBitstreamParserFromMeta(), llvm::remarks::RemarkParser::ExternalFilePrependPath, llvm::None, parseMeta(), parseRemark(), llvm::remarks::RemarkParser::ParserFormat, and StrTab.
next()
Expected< std::unique_ptr< Remark > > BitstreamRemarkParser::next () override virtual
If no error occurs, this returns a valid Remark object.
If an error of type EndOfFileError occurs, it is safe to recover from it by stopping the parsing. If any other error occurs, it should be propagated to the user. The pointer should never be null.
Implements llvm::remarks::RemarkParser.
Definition at line 331 of file BitstreamRemarkParser.cpp.
References E.
Referenced by BitstreamRemarkParser().
parseMeta()
Error BitstreamRemarkParser::parseMeta ()
Parse and process the metadata of the buffer.
Definition at line 344 of file BitstreamRemarkParser.cpp.
References advanceToMetaBlock(), llvm::remarks::BitstreamMetaParserHelper::ContainerType, llvm::remarks::BitstreamMetaParserHelper::ContainerVersion, llvm::createStringError(), E, llvm::remarks::Last, llvm_unreachable, llvm::make_error_code(), llvm::remarks::BitstreamMetaParserHelper::parse(), llvm::remarks::SeparateRemarksFile, llvm::remarks::SeparateRemarksMeta, llvm::remarks::Standalone, llvm::Error::success(), and llvm::IndexedInstrProf::Version.
Referenced by classof().
parseRemark()
Expected< std::unique_ptr< Remark > > BitstreamRemarkParser::parseRemark ()
Parse a Bitstream remark.
Definition at line 491 of file BitstreamRemarkParser.cpp.
References Arg, llvm::remarks::BitstreamRemarkParserHelper::Args, llvm::createStringError(), E, llvm::remarks::BitstreamRemarkParserHelper::FunctionNameIdx, llvm::remarks::BitstreamRemarkParserHelper::Hotness, llvm::remarks::BitstreamRemarkParserHelper::Argument::KeyIdx, llvm::remarks::Last, llvm::make_error_code(), llvm::None, llvm::remarks::BitstreamRemarkParserHelper::parse(), llvm::remarks::BitstreamRemarkParserHelper::PassNameIdx, llvm::remarks::BitstreamRemarkParserHelper::RemarkNameIdx, llvm::remarks::BitstreamRemarkParserHelper::SourceColumn, llvm::remarks::BitstreamRemarkParserHelper::Argument::SourceColumn, llvm::remarks::BitstreamRemarkParserHelper::SourceFileNameIdx, llvm::remarks::BitstreamRemarkParserHelper::Argument::SourceFileNameIdx, llvm::remarks::BitstreamRemarkParserHelper::SourceLine, llvm::remarks::BitstreamRemarkParserHelper::Argument::SourceLine, llvm::Expected< T >::takeError(), llvm::remarks::BitstreamRemarkParserHelper::Type, and llvm::remarks::BitstreamRemarkParserHelper::Argument::ValueIdx.
Referenced by classof().
Member Data Documentation
ContainerType
BitstreamRemarkContainerType llvm::remarks::BitstreamRemarkParser::ContainerType
Initial value:
=
      BitstreamRemarkContainerType::Standalone
Definition at line 39 of file BitstreamRemarkParser.h.
ContainerVersion
uint64_t llvm::remarks::BitstreamRemarkParser::ContainerVersion = 0
The common metadata used to decide how to parse the buffer.
This is filled when parsing the metadata block.
Definition at line 37 of file BitstreamRemarkParser.h.
ParserHelper
BitstreamParserHelper llvm::remarks::BitstreamRemarkParser::ParserHelper
The buffer to parse.
Definition at line 30 of file BitstreamRemarkParser.h.
ReadyToParseRemarks
bool llvm::remarks::BitstreamRemarkParser::ReadyToParseRemarks = false
Wether the parser is ready to parse remarks.
Definition at line 42 of file BitstreamRemarkParser.h.
RemarkVersion
uint64_t llvm::remarks::BitstreamRemarkParser::RemarkVersion = 0
Definition at line 38 of file BitstreamRemarkParser.h.
Referenced by processRemarkVersion().
StrTab
Optional<ParsedStringTable> llvm::remarks::BitstreamRemarkParser::StrTab
The string table used for parsing strings.
Definition at line 32 of file BitstreamRemarkParser.h.
Referenced by classof(), and processStrTab().
TmpRemarkBuffer
std::unique_ptr<MemoryBuffer> llvm::remarks::BitstreamRemarkParser::TmpRemarkBuffer
Temporary remark buffer used when the remarks are stored separately.
Definition at line 34 of file BitstreamRemarkParser.h.
The documentation for this struct was generated from the following files:
lib/Remarks/BitstreamRemarkParser.h
lib/Remarks/BitstreamRemarkParser.cpp