LLVM: llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > > Struct Template Reference
llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > > Struct Template Reference
#include "llvm/IR/ModuleSummaryIndexYAML.h"
Static Public Member Functions
static void inputOne (IO &io, StringRef Key, std::map< uint64_t, WholeProgramDevirtResolution > &V)
static void output (IO &io, std::map< uint64_t, WholeProgramDevirtResolution > &V)
Detailed Description
template<>
struct llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >
Definition at line 114 of file ModuleSummaryIndexYAML.h.
Member Function Documentation
inputOne()
static void llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::inputOne (IO & io, StringRef Key, std::map< uint64_t, WholeProgramDevirtResolution > & V) inline static
Definition at line 115 of file ModuleSummaryIndexYAML.h.
References llvm::StringRef::getAsInteger(), and llvm::StringRef::str().
output()
static void llvm::yaml::CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >::output (IO & io, std::map< uint64_t, WholeProgramDevirtResolution > & V) inline static
Definition at line 124 of file ModuleSummaryIndexYAML.h.
References P, and llvm::utostr().
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndexYAML.h