LLVM: llvm::DenseMapInfo< LocationSize > Struct Template Reference
llvm::DenseMapInfo< LocationSize > Struct Template Reference
#include "llvm/Analysis/MemoryLocation.h"
Static Public Member Functions
static LocationSize getEmptyKey ()
static LocationSize getTombstoneKey ()
static unsigned getHashValue (const LocationSize &Val)
static bool isEqual (const LocationSize &LHS, const LocationSize &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< LocationSize >
Definition at line 272 of file MemoryLocation.h.
Member Function Documentation
getEmptyKey()
static LocationSize llvm::DenseMapInfo< LocationSize >::getEmptyKey () inline static
Definition at line 273 of file MemoryLocation.h.
References llvm::LocationSize::mapEmpty().
getHashValue()
static unsigned llvm::DenseMapInfo< LocationSize >::getHashValue (const LocationSize & Val) inline static
Definition at line 279 of file MemoryLocation.h.
References llvm::LocationSize::toRaw().
getTombstoneKey()
static LocationSize llvm::DenseMapInfo< LocationSize >::getTombstoneKey () inline static
Definition at line 276 of file MemoryLocation.h.
References llvm::LocationSize::mapTombstone().
isEqual()
static bool llvm::DenseMapInfo< LocationSize >::isEqual (const LocationSize & LHS, const LocationSize & RHS) inline static
Definition at line 282 of file MemoryLocation.h.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/MemoryLocation.h