LLVM: llvm::codeview::GloballyHashedType Struct Reference
llvm::codeview::GloballyHashedType Struct Reference
A globally hashed type represents a hash value that is sufficient to uniquely identify a record across multiple type streams or type sequences.
#include "llvm/DebugInfo/CodeView/TypeHashing.h"
Public Member Functions
GloballyHashedType ()=default
GloballyHashedType (StringRef H)
GloballyHashedType (ArrayRef< uint8_t > H)
bool empty () const
Static Public Member Functions
static GloballyHashedType hashType (ArrayRef< uint8_t > RecordData, ArrayRef< GloballyHashedType > PreviousTypes, ArrayRef< GloballyHashedType > PreviousIds)
Given a sequence of bytes representing a record, compute a global hash for this record.
static GloballyHashedType hashType (CVType Type, ArrayRef< GloballyHashedType > PreviousTypes, ArrayRef< GloballyHashedType > PreviousIds)
Given a sequence of bytes representing a record, compute a global hash for this record.
template<typename Range >
static std::vector< GloballyHashedType > hashTypes (Range &&Records)
Given a sequence of combined type and ID records, compute global hashes for each of them, returning the results in a vector of hashed types.
template<typename Range >
static std::vector< GloballyHashedType > hashIds (Range &&Records, ArrayRef< GloballyHashedType > TypeHashes)
Given a sequence of combined type and ID records, compute global hashes for each of them, returning the results in a vector of hashed types.
static std::vector< GloballyHashedType > hashTypeCollection (TypeCollection &Types)
Public Attributes
std::array< uint8_t, 8 > Hash
Detailed Description
A globally hashed type represents a hash value that is sufficient to uniquely identify a record across multiple type streams or type sequences.
This works by, for any given record A which references B, replacing the TypeIndex that refers to B with a previously-computed global hash for B. As this is a recursive algorithm (e.g. the global hash of B also depends on the global hashes of the types that B refers to), a global hash can uniquely identify identify that A occurs in another stream that has a completely different graph structure. Although the hash itself is slower to compute, probing is much faster with a globally hashed type, because the hash itself is considered "as good as" the original type. Since type records can be quite large, this makes the equality comparison of the hash much faster than equality comparison of a full record.
Definition at line 77 of file TypeHashing.h.
Constructor & Destructor Documentation
GloballyHashedType() [1/3]
llvm::codeview::GloballyHashedType::GloballyHashedType () default
GloballyHashedType() [2/3]
llvm::codeview::GloballyHashedType::GloballyHashedType (StringRef H) inline
Definition at line 79 of file TypeHashing.h.
GloballyHashedType() [3/3]
llvm::codeview::GloballyHashedType::GloballyHashedType (ArrayRef< uint8_t > H) inline
Definition at line 81 of file TypeHashing.h.
References assert(), llvm::ArrayRef< T >::data(), llvm::codeview::LocallyHashedType::Hash, and llvm::ArrayRef< T >::size().
Member Function Documentation
empty()
bool llvm::codeview::GloballyHashedType::empty () const inline
Definition at line 87 of file TypeHashing.h.
References llvm::codeview::LocallyHashedType::hashType(), and llvm::codeview::LocallyHashedType::RecordData.
Referenced by hashTypes().
hashIds()
template<typename Range > static std::vector<GloballyHashedType> llvm::codeview::GloballyHashedType::hashIds (Range && Records, ArrayRef< GloballyHashedType > TypeHashes) inline static
Given a sequence of combined type and ID records, compute global hashes for each of them, returning the results in a vector of hashed types.
Definition at line 147 of file TypeHashing.h.
References llvm::codeview::LocallyHashedType::hashType().
hashType() [1/2]
GloballyHashedType GloballyHashedType::hashType (ArrayRef< uint8_t > RecordData, ArrayRef< GloballyHashedType > PreviousTypes, ArrayRef< GloballyHashedType > PreviousIds) static
Given a sequence of bytes representing a record, compute a global hash for this record.
Due to the nature of global hashes incorporating the hashes of referenced records, this function requires a list of types and ids that RecordData might reference, indexable by TypeIndex.
Definition at line 33 of file TypeHashing.cpp.
References llvm::codeview::discoverTypeIndices(), llvm::ArrayRef< T >::drop_front(), llvm::SHA1::final(), llvm::codeview::IndexRef, llvm::SHA1::init(), llvm::makeArrayRef(), llvm::Ref, llvm::ArrayRef< T >::slice(), llvm::StringRef::take_back(), llvm::ArrayRef< T >::take_front(), and llvm::SHA1::update().
Referenced by llvm::codeview::GlobalTypeTableBuilder::insertRecordBytes().
hashType() [2/2]
static GloballyHashedType llvm::codeview::GloballyHashedType::hashType (CVType Type, ArrayRef< GloballyHashedType > PreviousTypes, ArrayRef< GloballyHashedType > PreviousIds) inline static
Given a sequence of bytes representing a record, compute a global hash for this record.
Due to the nature of global hashes incorporating the hashes of referenced records, this function requires a list of types and ids that RecordData might reference, indexable by TypeIndex.
Definition at line 101 of file TypeHashing.h.
References llvm::codeview::LocallyHashedType::hashType(), and llvm::codeview::CVRecord< Kind >::RecordData.
hashTypeCollection()
static std::vector<GloballyHashedType> llvm::codeview::GloballyHashedType::hashTypeCollection (TypeCollection & Types) inline static
Definition at line 156 of file TypeHashing.h.
References llvm::codeview::TypeCollection::ForEachRecord(), llvm::codeview::LocallyHashedType::hashType(), and llvm::codeview::CVRecord< Kind >::RecordData.
hashTypes()
template<typename Range > static std::vector<GloballyHashedType> llvm::codeview::GloballyHashedType::hashTypes (Range && Records) inline static
Given a sequence of combined type and ID records, compute global hashes for each of them, returning the results in a vector of hashed types.
Definition at line 110 of file TypeHashing.h.
References empty(), H, and llvm::codeview::LocallyHashedType::hashType().
Member Data Documentation
Hash
std::array<uint8_t, 8> llvm::codeview::GloballyHashedType::Hash
Definition at line 85 of file TypeHashing.h.
Referenced by llvm::format_provider< codeview::GloballyHashedType >::format(), llvm::DenseMapInfo< codeview::GloballyHashedType >::getHashValue(), and llvm::DenseMapInfo< codeview::GloballyHashedType >::isEqual().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/CodeView/TypeHashing.h
lib/DebugInfo/CodeView/TypeHashing.cpp