LLVM: llvm::GraphTraits< const CallGraphNode * > Struct Template Reference
llvm::GraphTraits< const CallGraphNode * > Struct Template Reference
#include "llvm/Analysis/CallGraph.h"
Public Types
using NodeRef = const CallGraphNode *
using CGNPairTy = CallGraphNode::CallRecord
using EdgeRef = const CallGraphNode::CallRecord &
using ChildIteratorType = mapped_iterator< CallGraphNode::const_iterator, decltype(&CGNGetValue)>
using ChildEdgeIteratorType = CallGraphNode::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (const CallGraphNode *CGN)
static const CallGraphNode * CGNGetValue (CGNPairTy P)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
static NodeRef edge_dest (EdgeRef E)
Detailed Description
template<>
struct llvm::GraphTraits< const CallGraphNode * >
Definition at line 426 of file CallGraph.h.
Member Typedef Documentation
CGNPairTy
using llvm::GraphTraits< const CallGraphNode * >::CGNPairTy = CallGraphNode::CallRecord
Definition at line 428 of file CallGraph.h.
ChildEdgeIteratorType
using llvm::GraphTraits< const CallGraphNode * >::ChildEdgeIteratorType = CallGraphNode::const_iterator
Definition at line 436 of file CallGraph.h.
ChildIteratorType
using llvm::GraphTraits< const CallGraphNode * >::ChildIteratorType = mapped_iterator<CallGraphNode::const_iterator, decltype(&CGNGetValue)>
Definition at line 435 of file CallGraph.h.
EdgeRef
using llvm::GraphTraits< const CallGraphNode * >::EdgeRef = const CallGraphNode::CallRecord &
Definition at line 429 of file CallGraph.h.
NodeRef
using llvm::GraphTraits< const CallGraphNode * >::NodeRef = const CallGraphNode *
Definition at line 427 of file CallGraph.h.
Member Function Documentation
CGNGetValue()
static const CallGraphNode* llvm::GraphTraits< const CallGraphNode * >::CGNGetValue (CGNPairTy P) inline static
Definition at line 432 of file CallGraph.h.
child_begin()
static ChildIteratorType llvm::GraphTraits< const CallGraphNode * >::child_begin (NodeRef N) inline static
Definition at line 438 of file CallGraph.h.
References llvm::CallGraphNode::begin().
child_edge_begin()
static ChildEdgeIteratorType llvm::GraphTraits< const CallGraphNode * >::child_edge_begin (NodeRef N) inline static
Definition at line 446 of file CallGraph.h.
References llvm::CallGraphNode::begin().
child_edge_end()
static ChildEdgeIteratorType llvm::GraphTraits< const CallGraphNode * >::child_edge_end (NodeRef N) inline static
Definition at line 449 of file CallGraph.h.
References llvm::CallGraphNode::end().
child_end()
static ChildIteratorType llvm::GraphTraits< const CallGraphNode * >::child_end (NodeRef N) inline static
Definition at line 442 of file CallGraph.h.
References llvm::CallGraphNode::end().
edge_dest()
static NodeRef llvm::GraphTraits< const CallGraphNode * >::edge_dest (EdgeRef E) inline static
Definition at line 451 of file CallGraph.h.
getEntryNode()
static NodeRef llvm::GraphTraits< const CallGraphNode * >::getEntryNode (const CallGraphNode * CGN) inline static
Definition at line 431 of file CallGraph.h.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CallGraph.h