LLVM: llvm::pdb::StringTableHashTraits Struct Reference
llvm::pdb::StringTableHashTraits Struct Reference
#include "llvm/DebugInfo/PDB/Native/PDBStringTableBuilder.h"
Public Member Functions
StringTableHashTraits (PDBStringTableBuilder &Table)
uint32_t hashLookupKey (StringRef S) const
StringRef storageKeyToLookupKey (uint32_t Offset) const
uint32_t lookupKeyToStorageKey (StringRef S)
Public Attributes
PDBStringTableBuilder * Table
Detailed Description
Definition at line 35 of file PDBStringTableBuilder.h.
Constructor & Destructor Documentation
StringTableHashTraits()
StringTableHashTraits::StringTableHashTraits (PDBStringTableBuilder & Table) explicit
Definition at line 25 of file PDBStringTableBuilder.cpp.
Member Function Documentation
hashLookupKey()
uint32_t StringTableHashTraits::hashLookupKey (StringRef S) const
Definition at line 28 of file PDBStringTableBuilder.cpp.
References llvm::pdb::PDBStringTableBuilder::getIdForString(), and Table.
lookupKeyToStorageKey()
uint32_t StringTableHashTraits::lookupKeyToStorageKey (StringRef S)
Definition at line 42 of file PDBStringTableBuilder.cpp.
References llvm::pdb::PDBStringTableBuilder::insert(), and Table.
storageKeyToLookupKey()
StringRef StringTableHashTraits::storageKeyToLookupKey (uint32_t Offset) const
Definition at line 38 of file PDBStringTableBuilder.cpp.
References llvm::pdb::PDBStringTableBuilder::getStringForId(), and Table.
Member Data Documentation
Table
PDBStringTableBuilder* llvm::pdb::StringTableHashTraits::Table
Definition at line 36 of file PDBStringTableBuilder.h.
Referenced by hashLookupKey(), lookupKeyToStorageKey(), and storageKeyToLookupKey().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PDBStringTableBuilder.h
lib/DebugInfo/PDB/Native/PDBStringTableBuilder.cpp