LLVM: llvm::ConstantExprKeyType Struct Reference
llvm::ConstantExprKeyType Struct Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = ConstantInfo< ConstantExpr >::TypeClass
Public Member Functions
ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant *> Ops, unsigned short SubclassData=0, unsigned short SubclassOptionalData=0, ArrayRef< unsigned > Indexes=None, Type *ExplicitTy=nullptr)
ConstantExprKeyType (ArrayRef< Constant *> Operands, const ConstantExpr *CE)
ConstantExprKeyType (const ConstantExpr *CE, SmallVectorImpl< Constant *> &Storage)
bool operator== (const ConstantExprKeyType &X) const
bool operator== (const ConstantExpr *CE) const
unsigned getHash () const
ConstantExpr * create (TypeClass *Ty) const
Public Attributes
uint8_t Opcode
uint8_t SubclassOptionalData
uint16_t SubclassData
ArrayRef< Constant * > Ops
ArrayRef< unsigned > Indexes
Type * ExplicitTy
Detailed Description
Definition at line 462 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
using llvm::ConstantExprKeyType::TypeClass = ConstantInfo<ConstantExpr>::TypeClass
Definition at line 528 of file ConstantsContext.h.
Constructor & Destructor Documentation
ConstantExprKeyType() [1/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant *> Ops, unsigned short SubclassData = 0, unsigned short SubclassOptionalData = 0, ArrayRef< unsigned > Indexes = None, Type * ExplicitTy = nullptr) inline
Definition at line 470 of file ConstantsContext.h.
ConstantExprKeyType() [2/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (ArrayRef< Constant *> Operands, const ConstantExpr * CE) inline
Definition at line 479 of file ConstantsContext.h.
ConstantExprKeyType() [3/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (const ConstantExpr * CE, SmallVectorImpl< Constant *> & Storage) inline
Definition at line 486 of file ConstantsContext.h.
References assert(), E, llvm::SmallVectorBase::empty(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, and llvm::SmallVectorTemplateBase< T >::push_back().
Member Function Documentation
create()
ConstantExpr* llvm::ConstantExprKeyType::create (TypeClass * Ty) const inline
Definition at line 530 of file ConstantsContext.h.
References llvm::GetElementPtrConstantExpr::Create(), llvm::Value::getType(), llvm::Instruction::isCast(), llvm_unreachable, llvm::MCID::Select, llvm::ArrayRef< T >::slice(), llvm::Value::SubclassOptionalData, and llvm::UnaryConstantExpr::UnaryConstantExpr().
getHash()
unsigned llvm::ConstantExprKeyType::getHash () const inline
Definition at line 522 of file ConstantsContext.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine(), and llvm::hash_combine_range().
operator==() [1/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExprKeyType & X) const inline
Definition at line 499 of file ConstantsContext.h.
References Indexes, Opcode, Ops, SubclassData, and SubclassOptionalData.
operator==() [2/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExpr * CE) const inline
Definition at line 505 of file ConstantsContext.h.
References E, llvm::ConstantExpr::getIndices(), llvm::User::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getPredicate(), llvm::Value::getRawSubclassOptionalData(), llvm::ConstantExpr::hasIndices(), I, llvm::ConstantExpr::isCompare(), and llvm::ArrayRef< T >::size().
Member Data Documentation
ExplicitTy
Type* llvm::ConstantExprKeyType::ExplicitTy
Definition at line 468 of file ConstantsContext.h.
Indexes
ArrayRef<unsigned> llvm::ConstantExprKeyType::Indexes
Definition at line 467 of file ConstantsContext.h.
Referenced by operator==().
Opcode
uint8_t llvm::ConstantExprKeyType::Opcode
Definition at line 463 of file ConstantsContext.h.
Referenced by operator==().
Ops
ArrayRef<Constant *> llvm::ConstantExprKeyType::Ops
Definition at line 466 of file ConstantsContext.h.
Referenced by operator==().
SubclassData
uint16_t llvm::ConstantExprKeyType::SubclassData
Definition at line 465 of file ConstantsContext.h.
Referenced by operator==().
SubclassOptionalData
uint8_t llvm::ConstantExprKeyType::SubclassOptionalData
Definition at line 464 of file ConstantsContext.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/IR/ConstantsContext.h