LLVM: llvm::GraphTraits< const DDGNode * > Struct Template Reference
llvm::GraphTraits< const DDGNode * > Struct Template Reference
const versions of the grapth trait specializations for DDG
#include "llvm/Analysis/DDG.h"
Public Types
using NodeRef = const DDGNode *
using ChildIteratorType = mapped_iterator< DDGNode::const_iterator, decltype(&DDGGetTargetNode)>
using ChildEdgeIteratorType = DDGNode::const_iterator
Static Public Member Functions
static const DDGNode * DDGGetTargetNode (const DGEdge< DDGNode, DDGEdge > *P)
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
Detailed Description
template<>
struct llvm::GraphTraits< const DDGNode * >
const versions of the grapth trait specializations for DDG
Definition at line 471 of file DDG.h.
Member Typedef Documentation
ChildEdgeIteratorType
using llvm::GraphTraits< const DDGNode * >::ChildEdgeIteratorType = DDGNode::const_iterator
Definition at line 482 of file DDG.h.
ChildIteratorType
using llvm::GraphTraits< const DDGNode * >::ChildIteratorType = mapped_iterator<DDGNode::const_iterator, decltype(&DDGGetTargetNode)>
Definition at line 481 of file DDG.h.
NodeRef
using llvm::GraphTraits< const DDGNode * >::NodeRef = const DDGNode *
Definition at line 472 of file DDG.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< const DDGNode * >::child_begin (NodeRef N) inline static
Definition at line 485 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::begin().
child_edge_begin()
static ChildEdgeIteratorType llvm::GraphTraits< const DDGNode * >::child_edge_begin (NodeRef N) inline static
Definition at line 492 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::begin().
child_edge_end()
static ChildEdgeIteratorType llvm::GraphTraits< const DDGNode * >::child_edge_end (NodeRef N) inline static
Definition at line 495 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::end().
child_end()
static ChildIteratorType llvm::GraphTraits< const DDGNode * >::child_end (NodeRef N) inline static
Definition at line 488 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::end().
DDGGetTargetNode()
static const DDGNode* llvm::GraphTraits< const DDGNode * >::DDGGetTargetNode (const DGEdge< DDGNode, DDGEdge > * P) inline static
Definition at line 474 of file DDG.h.
References llvm::DGEdge< NodeType, EdgeType >::getTargetNode().
getEntryNode()
static NodeRef llvm::GraphTraits< const DDGNode * >::getEntryNode (NodeRef N) inline static
Definition at line 484 of file DDG.h.
References N.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DDG.h