LLVM: llvm::MDNodeKeyImpl< DIMacroFile > Struct Template Reference
llvm::MDNodeKeyImpl< DIMacroFile > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned MIType, unsigned Line, Metadata *File, Metadata *Elements)
MDNodeKeyImpl (const DIMacroFile *N)
bool isKeyOf (const DIMacroFile *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned MIType
unsigned Line
Metadata * File
Metadata * Elements
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIMacroFile >
Definition at line 1114 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIMacroFile >::MDNodeKeyImpl (unsigned MIType, unsigned Line, Metadata * File, Metadata * Elements) inline
Definition at line 1120 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIMacroFile >::MDNodeKeyImpl (const DIMacroFile * N) inline
Definition at line 1123 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIMacroFile >::getHashValue () const inline
Definition at line 1132 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIMacroFile >::isKeyOf (const DIMacroFile * RHS) const inline
Definition at line 1127 of file LLVMContextImpl.h.
References llvm::DIMacroFile::getLine(), llvm::DIMacroNode::getMacinfoType(), llvm::DIMacroFile::getRawElements(), and llvm::DIMacroFile::getRawFile().
Member Data Documentation
Elements
Metadata* llvm::MDNodeKeyImpl< DIMacroFile >::Elements
Definition at line 1118 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIMacroFile >::File
Definition at line 1117 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DIMacroFile >::Line
Definition at line 1116 of file LLVMContextImpl.h.
MIType
unsigned llvm::MDNodeKeyImpl< DIMacroFile >::MIType
Definition at line 1115 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h