LLVM: llvm::ISD::ArgFlagsTy Struct Reference
llvm::ISD::ArgFlagsTy Struct Reference
#include "llvm/CodeGen/TargetCallingConv.h"
Public Member Functions
ArgFlagsTy ()
bool isZExt () const
void setZExt ()
bool isSExt () const
void setSExt ()
bool isInReg () const
void setInReg ()
bool isSRet () const
void setSRet ()
bool isByVal () const
void setByVal ()
bool isInAlloca () const
void setInAlloca ()
bool isSwiftSelf () const
void setSwiftSelf ()
bool isSwiftError () const
void setSwiftError ()
bool isCFGuardTarget () const
void setCFGuardTarget ()
bool isHva () const
void setHva ()
bool isHvaStart () const
void setHvaStart ()
bool isSecArgPass () const
void setSecArgPass ()
bool isNest () const
void setNest ()
bool isReturned () const
void setReturned ()
bool isInConsecutiveRegs () const
void setInConsecutiveRegs ()
bool isInConsecutiveRegsLast () const
void setInConsecutiveRegsLast ()
bool isSplit () const
void setSplit ()
bool isSplitEnd () const
void setSplitEnd ()
bool isCopyElisionCandidate () const
void setCopyElisionCandidate ()
bool isPointer () const
void setPointer ()
unsigned getByValAlign () const
void setByValAlign (Align A)
unsigned getOrigAlign () const
void setOrigAlign (Align A)
unsigned getByValSize () const
void setByValSize (unsigned S)
unsigned getPointerAddrSpace () const
void setPointerAddrSpace (unsigned AS)
Detailed Description
Definition at line 27 of file TargetCallingConv.h.
Constructor & Destructor Documentation
ArgFlagsTy()
llvm::ISD::ArgFlagsTy::ArgFlagsTy () inline
Definition at line 57 of file TargetCallingConv.h.
Member Function Documentation
getByValAlign()
unsigned llvm::ISD::ArgFlagsTy::getByValAlign () const inline
Definition at line 128 of file TargetCallingConv.h.
References llvm::decodeMaybeAlign().
Referenced by AnalyzeReturnValues(), CalculateStackSlotAlignment(), callingConvSupported(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::ARMTargetLowering::CCAssignFnForReturn(), CreateCopyOfByValArgument(), llvm::CCState::HandleByVal(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), mayTailCallThisCC(), and setByValAlign().
getByValSize()
unsigned llvm::ISD::ArgFlagsTy::getByValSize () const inline
Definition at line 146 of file TargetCallingConv.h.
Referenced by AnalyzeReturnValues(), buildCallOperands(), CalculateStackSlotSize(), callingConvSupported(), CC_Lanai32_VarArg(), CC_RISCV_FastCC(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), CreateCopyOfByValArgument(), EnsureStackAlignment(), llvm::CCState::HandleByVal(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::HexagonTargetLowering::LowerFormalArguments(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), shouldGuaranteeTCO(), and UnpackFromArgumentSlot().
getOrigAlign()
unsigned llvm::ISD::ArgFlagsTy::getOrigAlign () const inline
Definition at line 137 of file TargetCallingConv.h.
References llvm::decodeMaybeAlign().
Referenced by callingConvSupported(), CC_ARM_AAPCS_Custom_Aggregate(), CC_MipsO32(), CC_RISCV(), CC_RISCVAssign2XLen(), finishStackBlock(), and setOrigAlign().
getPointerAddrSpace()
unsigned llvm::ISD::ArgFlagsTy::getPointerAddrSpace () const inline
Definition at line 149 of file TargetCallingConv.h.
isByVal()
bool llvm::ISD::ArgFlagsTy::isByVal () const inline
Definition at line 80 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), AnalyzeReturnValues(), areCallingConvEligibleForTCO_64SVR4(), buildCallOperands(), CalculateStackSlotAlignment(), CalculateStackSlotSize(), CalculateStackSlotUsed(), callingConvSupported(), CC_AIX(), CC_Lanai32_VarArg(), CC_MipsO32(), CC_RISCV_FastCC(), llvm::ARMTargetLowering::CCAssignFnForReturn(), computeBytesPoppedByCalleeForSRet(), EnsureStackAlignment(), getComparePred(), getMOVL(), isSortedByValueNo(), llvm::SITargetLowering::isTypeDesirableForOp(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::BPFTargetLowering::LowerOperation(), LowerVASTART(), MatchingStackOffset(), mayTailCallThisCC(), shouldGuaranteeTCO(), tryToElideArgumentCopy(), and UnpackFromArgumentSlot().
isCFGuardTarget()
bool llvm::ISD::ArgFlagsTy::isCFGuardTarget () const inline
Definition at line 92 of file TargetCallingConv.h.
isCopyElisionCandidate()
bool llvm::ISD::ArgFlagsTy::isCopyElisionCandidate () const inline
Definition at line 122 of file TargetCallingConv.h.
Referenced by shouldGuaranteeTCO().
isHva()
bool llvm::ISD::ArgFlagsTy::isHva () const inline
Definition at line 95 of file TargetCallingConv.h.
Referenced by CC_X86_32_VectorCall(), and CC_X86_64_VectorCall().
isHvaStart()
bool llvm::ISD::ArgFlagsTy::isHvaStart () const inline
Definition at line 98 of file TargetCallingConv.h.
Referenced by CC_X86_64_VectorCall().
isInAlloca()
bool llvm::ISD::ArgFlagsTy::isInAlloca () const inline
Definition at line 83 of file TargetCallingConv.h.
Referenced by callingConvSupported(), getMOVL(), and tryToElideArgumentCopy().
isInConsecutiveRegs()
bool llvm::ISD::ArgFlagsTy::isInConsecutiveRegs () const inline
Definition at line 110 of file TargetCallingConv.h.
Referenced by buildCallOperands(), CalculateStackSlotAlignment(), CalculateStackSlotSize(), callingConvSupported(), EnsureStackAlignment(), and mayTailCallThisCC().
isInConsecutiveRegsLast()
bool llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast () const inline
Definition at line 113 of file TargetCallingConv.h.
Referenced by buildCallOperands(), CalculateStackSlotUsed(), callingConvSupported(), CC_AArch64_Custom_Block(), CC_AArch64_Custom_Stack_Block(), CC_ARM_AAPCS_Custom_Aggregate(), and EnsureStackAlignment().
isInReg()
bool llvm::ISD::ArgFlagsTy::isInReg () const inline
Definition at line 74 of file TargetCallingConv.h.
Referenced by argsAreStructReturn(), callIsStructReturn(), CC_MipsO32(), getComparePred(), and processShaderInputArgs().
isNest()
bool llvm::ISD::ArgFlagsTy::isNest () const inline
Definition at line 104 of file TargetCallingConv.h.
Referenced by buildCallOperands(), callingConvSupported(), CC_AIX(), EnsureStackAlignment(), and getComparePred().
isPointer()
bool llvm::ISD::ArgFlagsTy::isPointer () const inline
Definition at line 125 of file TargetCallingConv.h.
isReturned()
bool llvm::ISD::ArgFlagsTy::isReturned () const inline
Definition at line 107 of file TargetCallingConv.h.
Referenced by llvm::ARMTargetLowering::CCAssignFnForReturn(), and mayTailCallThisCC().
isSecArgPass()
bool llvm::ISD::ArgFlagsTy::isSecArgPass () const inline
Definition at line 101 of file TargetCallingConv.h.
Referenced by CC_X86_32_VectorCall(), and CC_X86_64_VectorCall().
isSExt()
bool llvm::ISD::ArgFlagsTy::isSExt () const inline
Definition at line 71 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), buildCallOperands(), CC_AIX(), CC_Lanai32_VarArg(), CC_MipsO32(), computeBytesPoppedByCalleeForSRet(), determineLocInfo(), EnsureStackAlignment(), llvm::SITargetLowering::isTypeDesirableForOp(), MatchingStackOffset(), and truncateScalarIntegerArg().
isSplit()
bool llvm::ISD::ArgFlagsTy::isSplit () const inline
Definition at line 116 of file TargetCallingConv.h.
Referenced by CalculateStackSlotAlignment(), CC_MipsO32(), CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), and processShaderInputArgs().
isSplitEnd()
bool llvm::ISD::ArgFlagsTy::isSplitEnd () const inline
Definition at line 119 of file TargetCallingConv.h.
Referenced by CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), and processShaderInputArgs().
isSRet()
bool llvm::ISD::ArgFlagsTy::isSRet () const inline
Definition at line 77 of file TargetCallingConv.h.
Referenced by argsAreStructReturn(), callIsStructReturn(), CC_Sparc_Assign_SRet(), llvm::ARMTargetLowering::CCAssignFnForReturn(), getComparePred(), llvm::SparcTargetLowering::LowerCall_32(), and llvm::SITargetLowering::LowerFormalArguments().
isSwiftError()
bool llvm::ISD::ArgFlagsTy::isSwiftError () const inline
Definition at line 89 of file TargetCallingConv.h.
isSwiftSelf()
bool llvm::ISD::ArgFlagsTy::isSwiftSelf () const inline
Definition at line 86 of file TargetCallingConv.h.
Referenced by llvm::ARMTargetLowering::CCAssignFnForReturn(), and mayTailCallThisCC().
isZExt()
bool llvm::ISD::ArgFlagsTy::isZExt () const inline
Definition at line 68 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), CC_Lanai32_VarArg(), CC_MipsO32(), determineLocInfo(), EnsureStackAlignment(), llvm::SITargetLowering::isTypeDesirableForOp(), MatchingStackOffset(), and truncateScalarIntegerArg().
setByVal()
void llvm::ISD::ArgFlagsTy::setByVal () inline
Definition at line 81 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setByValAlign()
void llvm::ISD::ArgFlagsTy::setByValAlign (Align A) inline
Definition at line 132 of file TargetCallingConv.h.
References assert(), llvm::encode(), getByValAlign(), and llvm::Align::value().
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setByValSize()
void llvm::ISD::ArgFlagsTy::setByValSize (unsigned S) inline
Definition at line 147 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setCFGuardTarget()
void llvm::ISD::ArgFlagsTy::setCFGuardTarget () inline
Definition at line 93 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo().
setCopyElisionCandidate()
void llvm::ISD::ArgFlagsTy::setCopyElisionCandidate () inline
Definition at line 123 of file TargetCallingConv.h.
Referenced by tryToElideArgumentCopy().
setHva()
void llvm::ISD::ArgFlagsTy::setHva () inline
Definition at line 96 of file TargetCallingConv.h.
Referenced by tryToElideArgumentCopy().
setHvaStart()
void llvm::ISD::ArgFlagsTy::setHvaStart () inline
Definition at line 99 of file TargetCallingConv.h.
Referenced by tryToElideArgumentCopy().
setInAlloca()
void llvm::ISD::ArgFlagsTy::setInAlloca () inline
Definition at line 84 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setInConsecutiveRegs()
void llvm::ISD::ArgFlagsTy::setInConsecutiveRegs () inline
Definition at line 111 of file TargetCallingConv.h.
Referenced by findUnwindDestinations(), llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setInConsecutiveRegsLast()
void llvm::ISD::ArgFlagsTy::setInConsecutiveRegsLast () inline
Definition at line 114 of file TargetCallingConv.h.
Referenced by findUnwindDestinations().
setInReg()
void llvm::ISD::ArgFlagsTy::setInReg () inline
Definition at line 75 of file TargetCallingConv.h.
Referenced by CC_X86_32_VectorCall(), findUnwindDestinations(), llvm::CCState::getRemainingRegParmsForType(), llvm::GetReturnInfo(), llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setNest()
void llvm::ISD::ArgFlagsTy::setNest () inline
Definition at line 105 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setOrigAlign()
void llvm::ISD::ArgFlagsTy::setOrigAlign (Align A) inline
Definition at line 141 of file TargetCallingConv.h.
References assert(), llvm::encode(), getOrigAlign(), and llvm::Align::value().
Referenced by getComparePred(), llvm::CallLowering::handleAssignments(), llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setPointer()
void llvm::ISD::ArgFlagsTy::setPointer () inline
Definition at line 126 of file TargetCallingConv.h.
Referenced by findUnwindDestinations(), and tryToElideArgumentCopy().
setPointerAddrSpace()
void llvm::ISD::ArgFlagsTy::setPointerAddrSpace (unsigned AS) inline
Definition at line 150 of file TargetCallingConv.h.
Referenced by findUnwindDestinations(), and tryToElideArgumentCopy().
setReturned()
void llvm::ISD::ArgFlagsTy::setReturned () inline
Definition at line 108 of file TargetCallingConv.h.
Referenced by tryToElideArgumentCopy().
setSecArgPass()
void llvm::ISD::ArgFlagsTy::setSecArgPass () inline
Definition at line 102 of file TargetCallingConv.h.
setSExt()
void llvm::ISD::ArgFlagsTy::setSExt () inline
Definition at line 72 of file TargetCallingConv.h.
Referenced by findUnwindDestinations(), getComparePred(), llvm::GetReturnInfo(), llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setSplit()
void llvm::ISD::ArgFlagsTy::setSplit () inline
Definition at line 117 of file TargetCallingConv.h.
Referenced by llvm::CallLowering::handleAssignments(), and tryToElideArgumentCopy().
setSplitEnd()
void llvm::ISD::ArgFlagsTy::setSplitEnd () inline
Definition at line 120 of file TargetCallingConv.h.
Referenced by llvm::CallLowering::handleAssignments().
setSRet()
void llvm::ISD::ArgFlagsTy::setSRet () inline
Definition at line 78 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setSwiftError()
void llvm::ISD::ArgFlagsTy::setSwiftError () inline
Definition at line 90 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setSwiftSelf()
void llvm::ISD::ArgFlagsTy::setSwiftSelf () inline
Definition at line 87 of file TargetCallingConv.h.
Referenced by llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
setZExt()
void llvm::ISD::ArgFlagsTy::setZExt () inline
Definition at line 69 of file TargetCallingConv.h.
Referenced by findUnwindDestinations(), getComparePred(), llvm::GetReturnInfo(), llvm::FastISel::lowerCallTo(), and tryToElideArgumentCopy().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetCallingConv.h