LLVM: false::IntervalSorter Struct Reference
false::IntervalSorter Struct Reference
Public Member Functions
bool operator() (LiveInterval *LHS, LiveInterval *RHS) const
Detailed Description
Definition at line 146 of file StackSlotColoring.cpp.
Member Function Documentation
operator()()
bool false::IntervalSorter::operator() (LiveInterval * LHS, LiveInterval * RHS) const inline
Definition at line 147 of file StackSlotColoring.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DCELimit, DisableSharing, llvm::dump(), llvm::LiveInterval::dump(), llvm::numbers::e, E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::exposesReturnsTwice(), llvm::PseudoSourceValueManager::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getIndex(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::LiveStacks::getInterval(), llvm::MachineFunction::getName(), llvm::LiveStacks::getNumIntervals(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOperand(), llvm::MachineMemOperand::getPseudoValue(), llvm::MachineFunction::getPSVManager(), llvm::LiveIntervals::getSpillWeight(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFunction::getSubtarget(), llvm::LiveStacks::hasInterval(), I, llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isFI(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::TargetInstrInfo::isStackSlotCopy(), llvm::TargetInstrInfo::isStoreToStackSlot(), LLVM_DEBUG, llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), MI, llvm::LiveRange::overlaps(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LiveInterval::reg, llvm::MachineFrameInfo::RemoveStackObject(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), llvm::BitVector::set(), llvm::MachineOperand::setIndex(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectSize(), Size, llvm::SmallVectorBase::size(), llvm::sort(), llvm::X86AS::SS, llvm::stable_sort(), llvm::Register::stackSlot2Index(), and llvm::LiveInterval::weight.
The documentation for this struct was generated from the following file:
lib/CodeGen/StackSlotColoring.cpp