LLVM: llvm::codeview::serialize_vector_tail_impl< T > Struct Template Reference
llvm::codeview::serialize_vector_tail_impl< T > Struct Template Reference
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
Public Member Functions
serialize_vector_tail_impl (std::vector< T > &Item)
Error deserialize (BinaryStreamReader &Reader) const
Public Attributes
std::vector< T > & Item
Detailed Description
template<typename T>
struct llvm::codeview::serialize_vector_tail_impl< T >
Definition at line 102 of file RecordSerialization.h.
Constructor & Destructor Documentation
serialize_vector_tail_impl()
template<typename T> llvm::codeview::serialize_vector_tail_impl< T >::serialize_vector_tail_impl (std::vector< T > & Item) inline
Definition at line 103 of file RecordSerialization.h.
Member Function Documentation
deserialize()
template<typename T> Error llvm::codeview::serialize_vector_tail_impl< T >::deserialize (BinaryStreamReader & Reader) const inline
Definition at line 105 of file RecordSerialization.h.
References llvm::codeview::consume(), llvm::codeview::EC, llvm::BinaryStreamReader::empty(), llvm::tgtok::Field, llvm::BinaryStreamReader::peek(), and llvm::Error::success().
Referenced by llvm::codeview::consume().
Member Data Documentation
Item
template<typename T> std::vector<T>& llvm::codeview::serialize_vector_tail_impl< T >::Item
Definition at line 116 of file RecordSerialization.h.
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/RecordSerialization.h