LLVM: llvm::SLPVectorizerPass Struct Reference
llvm::SLPVectorizerPass Struct Reference
#include "llvm/Transforms/Vectorize/SLPVectorizer.h"
Public Types
using StoreList = SmallVector< StoreInst *, 8 >
using StoreListMap = MapVector< Value *, StoreList >
using GEPList = SmallVector< GetElementPtrInst *, 8 >
using GEPListMap = MapVector< Value *, GEPList >
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, ScalarEvolution *SE_, TargetTransformInfo *TTI_, TargetLibraryInfo *TLI_, AliasAnalysis *AA_, LoopInfo *LI_, DominatorTree *DT_, AssumptionCache *AC_, DemandedBits *DB_, OptimizationRemarkEmitter *ORE_)
Public Attributes
ScalarEvolution * SE = nullptr
TargetTransformInfo * TTI = nullptr
TargetLibraryInfo * TLI = nullptr
AliasAnalysis * AA = nullptr
LoopInfo * LI = nullptr
DominatorTree * DT = nullptr
AssumptionCache * AC = nullptr
DemandedBits * DB = nullptr
const DataLayout * DL = nullptr
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SLPVectorizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 60 of file SLPVectorizer.h.
Member Typedef Documentation
GEPList
using llvm::SLPVectorizerPass::GEPList = SmallVector<GetElementPtrInst *, 8>
Definition at line 63 of file SLPVectorizer.h.
GEPListMap
using llvm::SLPVectorizerPass::GEPListMap = MapVector<Value *, GEPList>
Definition at line 64 of file SLPVectorizer.h.
StoreList
using llvm::SLPVectorizerPass::StoreList = SmallVector<StoreInst *, 8>
Definition at line 61 of file SLPVectorizer.h.
StoreListMap
using llvm::SLPVectorizerPass::StoreListMap = MapVector<Value *, StoreList>
Definition at line 62 of file SLPVectorizer.h.
Member Function Documentation
run()
PreservedAnalyses SLPVectorizerPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 5588 of file SLPVectorizer.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool SLPVectorizerPass::runImpl (Function & F, ScalarEvolution * SE_, TargetTransformInfo * TTI_, TargetLibraryInfo * TLI_, AliasAnalysis * AA_, LoopInfo * LI_, DominatorTree * DT_, AssumptionCache * AC_, DemandedBits * DB_, OptimizationRemarkEmitter * ORE_)
Definition at line 5610 of file SLPVectorizer.cpp.
References llvm::any_of(), assert(), B, llvm::ArrayRef< T >::back(), llvm::ArrayRef< T >::begin(), llvm::dbgs(), llvm::dyn_cast(), E, llvm::ArrayRef< T >::end(), F(), llvm::ArrayRef< T >::front(), GEP, llvm::VectorType::get(), llvm::Module::getDataLayout(), llvm::Function::getEntryBlock(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::GlobalValue::getParent(), getSameOpcode(), getType(), llvm::Value::getType(), llvm::GetUnderlyingObject(), llvm::Function::hasFnAttribute(), llvm::Value::hasOneUse(), I, llvm::isConsecutiveAccess(), llvm::isPowerOf2_32(), isValidElementType(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::max(), MaxStoreLookup, llvm::None, Operands, P, llvm::post_order(), llvm::PowerOf2Ceil(), llvm::PowerOf2Floor(), llvm::Type::print(), llvm::ArrayRef< T >::rbegin(), llvm::ArrayRef< T >::rend(), SI, Size, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), SLPCostThreshold, llvm::raw_string_ostream::str(), SV_NAME, llvm::transform(), and llvm::verifyFunction().
Referenced by llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes().
Member Data Documentation
AA
AliasAnalysis* llvm::SLPVectorizerPass::AA = nullptr
Definition at line 69 of file SLPVectorizer.h.
AC
AssumptionCache* llvm::SLPVectorizerPass::AC = nullptr
Definition at line 72 of file SLPVectorizer.h.
DB
DemandedBits* llvm::SLPVectorizerPass::DB = nullptr
Definition at line 73 of file SLPVectorizer.h.
DL
const DataLayout* llvm::SLPVectorizerPass::DL = nullptr
Definition at line 74 of file SLPVectorizer.h.
DT
DominatorTree* llvm::SLPVectorizerPass::DT = nullptr
Definition at line 71 of file SLPVectorizer.h.
LI
LoopInfo* llvm::SLPVectorizerPass::LI = nullptr
Definition at line 70 of file SLPVectorizer.h.
SE
ScalarEvolution* llvm::SLPVectorizerPass::SE = nullptr
Definition at line 66 of file SLPVectorizer.h.
TLI
TargetLibraryInfo* llvm::SLPVectorizerPass::TLI = nullptr
Definition at line 68 of file SLPVectorizer.h.
TTI
TargetTransformInfo* llvm::SLPVectorizerPass::TTI = nullptr
Definition at line 67 of file SLPVectorizer.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Vectorize/SLPVectorizer.h
lib/Transforms/Vectorize/SLPVectorizer.cpp