LLVM: llvm::AnalysisGetter Struct Reference
llvm::AnalysisGetter Struct Reference
Wrapper for FunctoinAnalysisManager.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
template<typename Analysis >
Analysis::Result * getAnalysis (const Function &F)
template<typename Analysis >
Analysis::Result * getAnalysis (const Module &M)
AnalysisGetter (ModuleAnalysisManager &MAM)
AnalysisGetter ()
Detailed Description
Wrapper for FunctoinAnalysisManager.
Definition at line 527 of file Attributor.h.
Constructor & Destructor Documentation
AnalysisGetter() [1/2]
llvm::AnalysisGetter::AnalysisGetter (ModuleAnalysisManager & MAM) inline
Definition at line 544 of file Attributor.h.
AnalysisGetter() [2/2]
llvm::AnalysisGetter::AnalysisGetter () inline
Definition at line 545 of file Attributor.h.
Member Function Documentation
getAnalysis() [1/2]
template<typename Analysis > Analysis::Result* llvm::AnalysisGetter::getAnalysis (const Function & F) inline
Definition at line 529 of file Attributor.h.
References Analysis, F(), and llvm::GlobalValue::getParent().
Referenced by llvm::InformationCache::InformationCache().
getAnalysis() [2/2]
template<typename Analysis > Analysis::Result* llvm::AnalysisGetter::getAnalysis (const Module & M) inline
Definition at line 539 of file Attributor.h.
References Analysis.
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h