LLVM: llvm::ilist_callback_traits< NodeTy > Struct Template Reference
llvm::ilist_callback_traits< NodeTy > Struct Template Reference
Callbacks do nothing by default in iplist and ilist.
#include "llvm/ADT/ilist.h"
Public Member Functions
void addNodeToList (NodeTy *)
When an MBB is added to an MF, we need to update the parent pointer of the MBB, the MBB numbering, and any instructions in the MBB to be on the right operand list for registers.
void removeNodeFromList (NodeTy *)
template<class Iterator >
void transferNodesFromList (ilist_callback_traits &OldList, Iterator, Iterator)
Callback before transferring nodes to this list.
Detailed Description
template<typename NodeTy>
struct llvm::ilist_callback_traits< NodeTy >
Callbacks do nothing by default in iplist and ilist.
Specialize this for to use callbacks for when nodes change their list membership.
Definition at line 64 of file ilist.h.
Member Function Documentation
addNodeToList()
template<typename NodeTy> void ilist_callback_traits::addNodeToList (NodeTy *) inline
When an MBB is added to an MF, we need to update the parent pointer of the MBB, the MBB numbering, and any instructions in the MBB to be on the right operand list for registers.
MBBs start out as #-1. When a MBB is added to a MachineFunction, it gets the next available unique MBB number. If it is removed from a MachineFunction, it goes back to being #-1.
Definition at line 65 of file ilist.h.
Referenced by llvm::printMBBReference().
removeNodeFromList()
template<typename NodeTy> void ilist_callback_traits::removeNodeFromList (NodeTy *) inline
Definition at line 66 of file ilist.h.
Referenced by llvm::printMBBReference().
transferNodesFromList()
template<typename NodeTy> template<class Iterator > void llvm::ilist_callback_traits< NodeTy >::transferNodesFromList (ilist_callback_traits< NodeTy > & OldList, Iterator , Iterator) inline
Callback before transferring nodes to this list.
The nodes may already be in this same list.
Definition at line 71 of file ilist.h.
Referenced by llvm::printMBBReference().
The documentation for this struct was generated from the following files:
include/llvm/ADT/ilist.h
lib/CodeGen/MachineBasicBlock.cpp