LLVM: llvm::MDNodeKeyImpl< DISubroutineType > Struct Template Reference
llvm::MDNodeKeyImpl< DISubroutineType > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Flags, uint8_t CC, Metadata *TypeArray)
MDNodeKeyImpl (const DISubroutineType *N)
bool isKeyOf (const DISubroutineType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Flags
uint8_t CC
Metadata * TypeArray
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DISubroutineType >
Definition at line 561 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DISubroutineType >::MDNodeKeyImpl (unsigned Flags, uint8_t CC, Metadata * TypeArray) inline
Definition at line 566 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DISubroutineType >::MDNodeKeyImpl (const DISubroutineType * N) inline
Definition at line 568 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DISubroutineType >::getHashValue () const inline
Definition at line 576 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DISubroutineType >::isKeyOf (const DISubroutineType * RHS) const inline
Definition at line 571 of file LLVMContextImpl.h.
References llvm::DISubroutineType::getCC(), llvm::DIType::getFlags(), and llvm::DISubroutineType::getRawTypeArray().
Member Data Documentation
CC
uint8_t llvm::MDNodeKeyImpl< DISubroutineType >::CC
Definition at line 563 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DISubroutineType >::Flags
Definition at line 562 of file LLVMContextImpl.h.
TypeArray
Metadata* llvm::MDNodeKeyImpl< DISubroutineType >::TypeArray
Definition at line 564 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h