LLVM: llvm::MCSchedClassDesc Struct Reference
llvm::MCSchedClassDesc Struct Reference
Summarize the scheduling resources required for an instruction of a particular scheduling class.
#include "llvm/MC/MCSchedule.h"
Public Member Functions
bool isValid () const
bool isVariant () const
Public Attributes
const char * Name
uint16_t NumMicroOps: 14
bool BeginGroup: 1
bool EndGroup: 1
uint16_t WriteProcResIdx
uint16_t NumWriteProcResEntries
uint16_t WriteLatencyIdx
uint16_t NumWriteLatencyEntries
uint16_t ReadAdvanceIdx
uint16_t NumReadAdvanceEntries
Static Public Attributes
static const unsigned short InvalidNumMicroOps = (1U << 14) - 1
static const unsigned short VariantNumMicroOps = InvalidNumMicroOps - 1
Detailed Description
Summarize the scheduling resources required for an instruction of a particular scheduling class.
Defined as an aggregate struct for creating tables with initializer lists.
Definition at line 110 of file MCSchedule.h.
Member Function Documentation
isValid()
bool llvm::MCSchedClassDesc::isValid () const inline
Definition at line 127 of file MCSchedule.h.
Referenced by llvm::ResourceManager::canReserveResources(), llvm::TargetSchedModel::computeInstrLatency(), llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeOperandLatency(), llvm::TargetSchedModel::computeOutputLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), llvm::SystemZHazardRecognizer::dumpSU(), getLatency(), llvm::TargetSchedModel::getNumMicroOps(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::MachineTraceMetrics::getResources(), getUnderlyingObjects(), llvm::SystemZHazardRecognizer::groupingCost(), INITIALIZE_PASS(), llvm::TargetSchedModel::mustBeginGroup(), llvm::TargetSchedModel::mustEndGroup(), llvm::SystemZPostRASchedStrategy::releaseTopNode(), llvm::ResourceManager::reserveResources(), llvm::SystemZHazardRecognizer::Reset(), llvm::TargetSchedModel::resolveSchedClass(), and llvm::SystemZHazardRecognizer::resourcesCost().
isVariant()
bool llvm::MCSchedClassDesc::isVariant () const inline
Definition at line 130 of file MCSchedule.h.
Referenced by llvm::MCSchedModel::computeInstrLatency(), llvm::TargetSchedModel::computeReciprocalThroughput(), getLatency(), llvm::MCSchedModel::getReciprocalThroughput(), INITIALIZE_PASS(), llvm::TargetSchedModel::resolveSchedClass(), and llvm::mca::verifyOperands().
Member Data Documentation
BeginGroup
bool llvm::MCSchedClassDesc::BeginGroup
Definition at line 118 of file MCSchedule.h.
Referenced by llvm::SystemZHazardRecognizer::dumpSU(), llvm::SystemZHazardRecognizer::groupingCost(), llvm::TargetSchedModel::mustBeginGroup(), llvm::SystemZPostRASchedStrategy::releaseTopNode(), and llvm::SystemZHazardRecognizer::Reset().
EndGroup
bool llvm::MCSchedClassDesc::EndGroup
Definition at line 119 of file MCSchedule.h.
Referenced by llvm::SystemZHazardRecognizer::dumpSU(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::groupingCost(), llvm::TargetSchedModel::mustEndGroup(), and llvm::SystemZPostRASchedStrategy::releaseTopNode().
InvalidNumMicroOps
const unsigned short llvm::MCSchedClassDesc::InvalidNumMicroOps = (1U << 14) - 1 static
Definition at line 111 of file MCSchedule.h.
Referenced by llvm::mca::verifyOperands().
Name
const char* llvm::MCSchedClassDesc::Name
Definition at line 115 of file MCSchedule.h.
Referenced by llvm::mca::initializeUsedResources().
NumMicroOps
uint16_t llvm::MCSchedClassDesc::NumMicroOps
Definition at line 117 of file MCSchedule.h.
Referenced by llvm::SystemZHazardRecognizer::dumpSU(), llvm::TargetSchedModel::getNumMicroOps(), and llvm::MCSchedModel::getReciprocalThroughput().
NumReadAdvanceEntries
uint16_t llvm::MCSchedClassDesc::NumReadAdvanceEntries
Definition at line 125 of file MCSchedule.h.
Referenced by llvm::TargetSchedModel::computeOperandLatency(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), and llvm::MCSubtargetInfo::getReadAdvanceEntries().
NumWriteLatencyEntries
uint16_t llvm::MCSchedClassDesc::NumWriteLatencyEntries
Definition at line 123 of file MCSchedule.h.
Referenced by llvm::MCSchedModel::computeInstrLatency(), getLatency(), and llvm::mca::verifyOperands().
NumWriteProcResEntries
uint16_t llvm::MCSchedClassDesc::NumWriteProcResEntries
Definition at line 121 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteProcResEnd(), and llvm::mca::initializeUsedResources().
ReadAdvanceIdx
uint16_t llvm::MCSchedClassDesc::ReadAdvanceIdx
Definition at line 124 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getReadAdvanceCycles(), and llvm::MCSubtargetInfo::getReadAdvanceEntries().
VariantNumMicroOps
const unsigned short llvm::MCSchedClassDesc::VariantNumMicroOps = InvalidNumMicroOps - 1 static
Definition at line 112 of file MCSchedule.h.
WriteLatencyIdx
uint16_t llvm::MCSchedClassDesc::WriteLatencyIdx
Definition at line 122 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteLatencyEntry().
WriteProcResIdx
uint16_t llvm::MCSchedClassDesc::WriteProcResIdx
Definition at line 120 of file MCSchedule.h.
Referenced by llvm::MCSubtargetInfo::getWriteProcResBegin().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCSchedule.h