LLVM: llvm::GraphTraits< MachineRegionInfoPass * > Struct Template Reference
llvm::GraphTraits< MachineRegionInfoPass * > Struct Template Reference
#include "llvm/CodeGen/MachineRegionInfo.h"
Public Types
using nodes_iterator = df_iterator< NodeRef, df_iterator_default_set< NodeRef >, false, GraphTraits< FlatIt< NodeRef > >>
Public Types inherited from llvm::GraphTraits< MachineRegionInfo *>
using NodeRef = typename MachineRegionInfo *::UnknownGraphTypeError
Static Public Member Functions
static NodeRef getEntryNode (MachineRegionInfoPass *RI)
static nodes_iterator nodes_begin (MachineRegionInfoPass *RI)
static nodes_iterator nodes_end (MachineRegionInfoPass *RI)
Detailed Description
template<>
struct llvm::GraphTraits< MachineRegionInfoPass * >
Definition at line 157 of file MachineRegionInfo.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< MachineRegionInfoPass * >::nodes_iterator = df_iterator<NodeRef, df_iterator_default_set<NodeRef>, false, GraphTraits<FlatIt<NodeRef> >>
Definition at line 160 of file MachineRegionInfo.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< MachineRegionInfoPass * >::getEntryNode (MachineRegionInfoPass * RI) inline static
Definition at line 162 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_begin()
static nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_begin (MachineRegionInfoPass * RI) inline static
Definition at line 166 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_end()
static nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_end (MachineRegionInfoPass * RI) inline static
Definition at line 170 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineRegionInfo.h