LLVM: llvm::TimeTraceProfiler Struct Reference
llvm::TimeTraceProfiler Struct Reference
Public Member Functions
TimeTraceProfiler (unsigned TimeTraceGranularity=0, StringRef ProcName="")
void begin (std::string Name, llvm::function_ref< std::string()> Detail)
void end ()
void Write (raw_pwrite_stream &OS)
Public Attributes
SmallVector< Entry, 16 > Stack
SmallVector< Entry, 128 > Entries
StringMap< CountAndDurationType > CountAndTotalPerName
const TimePointType StartTime
const std::string ProcName
const unsigned TimeTraceGranularity
Detailed Description
Definition at line 61 of file TimeProfiler.cpp.
Constructor & Destructor Documentation
TimeTraceProfiler()
llvm::TimeTraceProfiler::TimeTraceProfiler (unsigned TimeTraceGranularity = 0, StringRef ProcName = "") inline
Definition at line 62 of file TimeProfiler.cpp.
Member Function Documentation
begin()
void llvm::TimeTraceProfiler::begin (std::string Name, llvm::function_ref< std::string()> Detail) inline
Definition at line 66 of file TimeProfiler.cpp.
References now().
Referenced by llvm::timeTraceProfilerBegin().
end()
void llvm::TimeTraceProfiler::end () inline
Definition at line 71 of file TimeProfiler.cpp.
References assert(), E, llvm::find_if(), and now().
Referenced by llvm::timeTraceProfilerEnd().
Write()
void llvm::TimeTraceProfiler::Write (raw_pwrite_stream & OS) inline
Definition at line 106 of file TimeProfiler.cpp.
References assert(), B, llvm::count(), E, and llvm::sort().
Referenced by llvm::timeTraceProfilerWrite().
Member Data Documentation
CountAndTotalPerName
StringMap<CountAndDurationType> llvm::TimeTraceProfiler::CountAndTotalPerName
Definition at line 183 of file TimeProfiler.cpp.
Entries
SmallVector<Entry, 128> llvm::TimeTraceProfiler::Entries
Definition at line 182 of file TimeProfiler.cpp.
ProcName
const std::string llvm::TimeTraceProfiler::ProcName
Definition at line 185 of file TimeProfiler.cpp.
Stack
SmallVector<Entry, 16> llvm::TimeTraceProfiler::Stack
Definition at line 181 of file TimeProfiler.cpp.
StartTime
const TimePointType llvm::TimeTraceProfiler::StartTime
Definition at line 184 of file TimeProfiler.cpp.
TimeTraceGranularity
const unsigned llvm::TimeTraceProfiler::TimeTraceGranularity
Definition at line 188 of file TimeProfiler.cpp.
The documentation for this struct was generated from the following file:
lib/Support/TimeProfiler.cpp