LLVM: llvm::MD5::MD5Result Struct Reference
llvm::MD5::MD5Result Struct Reference
#include "llvm/Support/MD5.h"
Public Member Functions
operator std::array< uint8_t, 16 > () const
const uint8_t & operator[] (size_t I) const
uint8_t & operator[] (size_t I)
SmallString< 32 > digest () const
uint64_t low () const
uint64_t high () const
std::pair< uint64_t, uint64_t > words () const
Public Attributes
std::array< uint8_t, 16 > Bytes
Detailed Description
Definition at line 55 of file MD5.h.
Member Function Documentation
digest()
SmallString< 32 > MD5::MD5Result::digest () const
Definition at line 264 of file MD5.cpp.
References llvm::format().
Referenced by llvm::DWARFDebugLine::Prologue::dump(), llvm::FileInfo::getCoveragePath(), operator[](), printDwarfFileDirective(), and llvm::MD5::stringifyResult().
high()
uint64_t llvm::MD5::MD5Result::high () const inline
Definition at line 72 of file MD5.h.
Referenced by llvm::DIEHash::computeCUSignature(), llvm::DIEHash::computeTypeSignature(), llvm::DwarfDebug::makeTypeSignature(), and words().
low()
uint64_t llvm::MD5::MD5Result::low () const inline
Definition at line 65 of file MD5.h.
Referenced by llvm::MD5Hash(), and words().
operator std::array< uint8_t, 16 >()
llvm::MD5::MD5Result::operator std::array< uint8_t, 16 > () const inline
Definition at line 58 of file MD5.h.
References Bytes.
operator[]() [1/2]
const uint8_t& llvm::MD5::MD5Result::operator[] (size_t I) const inline
Definition at line 60 of file MD5.h.
References I.
operator[]() [2/2]
uint8_t& llvm::MD5::MD5Result::operator[] (size_t I) inline
Definition at line 61 of file MD5.h.
References digest(), and I.
words()
std::pair<uint64_t, uint64_t> llvm::MD5::MD5Result::words () const inline
Definition at line 76 of file MD5.h.
References llvm::Data, llvm::MD5::hash(), high(), low(), llvm::MD5::MD5(), llvm::MD5::stringifyResult(), and llvm::MD5::update().
Member Data Documentation
Bytes
std::array<uint8_t, 16> llvm::MD5::MD5Result::Bytes
Definition at line 56 of file MD5.h.
Referenced by emitOneV5FileEntry(), llvm::DwarfUnit::getMD5AsBytes(), operator std::array< uint8_t, 16 >(), llvm::operator==(), parseHexOcta(), and parseV5DirFileTables().
The documentation for this struct was generated from the following files:
include/llvm/Support/MD5.h
lib/Support/MD5.cpp