LLVM: llvm::HexagonBlockRanges::RegisterRef Struct Reference
llvm::HexagonBlockRanges::RegisterRef Struct Reference
#include "Target/Hexagon/HexagonBlockRanges.h"
Public Member Functions
bool operator< (RegisterRef R) const
Public Attributes
unsigned Reg
unsigned Sub
Detailed Description
Definition at line 33 of file HexagonBlockRanges.h.
Member Function Documentation
operator<()
bool llvm::HexagonBlockRanges::RegisterRef::operator< (RegisterRef R) const inline
Definition at line 36 of file HexagonBlockRanges.h.
References Reg, and Sub.
Referenced by llvm::HexagonBlockRanges::IndexType::isInstr(), llvm::HexagonBlockRanges::IndexType::operator<(), and llvm::HexagonBlockRanges::IndexType::operator<=().
Member Data Documentation
Reg
unsigned llvm::HexagonBlockRanges::RegisterRef::Reg
Definition at line 34 of file HexagonBlockRanges.h.
Referenced by llvm::HexagonBlockRanges::expandToSubRegs(), and operator<().
Sub
unsigned llvm::HexagonBlockRanges::RegisterRef::Sub
Definition at line 34 of file HexagonBlockRanges.h.
Referenced by llvm::HexagonBlockRanges::expandToSubRegs(), and operator<().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/HexagonBlockRanges.h