LLVM: llvm::MDNodeKeyImpl< DIBasicType > Struct Template Reference
llvm::MDNodeKeyImpl< DIBasicType > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Tag, MDString *Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, unsigned Flags)
MDNodeKeyImpl (const DIBasicType *N)
bool isKeyOf (const DIBasicType *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Tag
MDString * Name
uint64_t SizeInBits
uint32_t AlignInBits
unsigned Encoding
unsigned Flags
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIBasicType >
Definition at line 376 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIBasicType >::MDNodeKeyImpl (unsigned Tag, MDString * Name, uint64_t SizeInBits, uint32_t AlignInBits, unsigned Encoding, unsigned Flags) inline
Definition at line 384 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIBasicType >::MDNodeKeyImpl (const DIBasicType * N) inline
Definition at line 388 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIBasicType >::getHashValue () const inline
Definition at line 400 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIBasicType >::isKeyOf (const DIBasicType * RHS) const inline
Definition at line 392 of file LLVMContextImpl.h.
References llvm::DIType::getAlignInBits(), llvm::DIBasicType::getEncoding(), llvm::DIType::getFlags(), llvm::DIType::getRawName(), llvm::DIType::getSizeInBits(), and llvm::DINode::getTag().
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DIBasicType >::AlignInBits
Definition at line 380 of file LLVMContextImpl.h.
Encoding
unsigned llvm::MDNodeKeyImpl< DIBasicType >::Encoding
Definition at line 381 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DIBasicType >::Flags
Definition at line 382 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIBasicType >::Name
Definition at line 378 of file LLVMContextImpl.h.
SizeInBits
uint64_t llvm::MDNodeKeyImpl< DIBasicType >::SizeInBits
Definition at line 379 of file LLVMContextImpl.h.
Tag
unsigned llvm::MDNodeKeyImpl< DIBasicType >::Tag
Definition at line 377 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h