LLVM: llvm::ms_demangle::Node Struct Reference
llvm::ms_demangle::Node Struct Reference abstract
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
virtual void output (OutputStream &OS, OutputFlags Flags) const =0
std::string toString (OutputFlags Flags=OF_Default) const
Detailed Description
Definition at line 256 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
Node()
llvm::ms_demangle::Node::Node (NodeKind K) inline explicit
Definition at line 257 of file MicrosoftDemangleNodes.h.
~Node()
virtual llvm::ms_demangle::Node::~Node () virtual default
Member Function Documentation
kind()
NodeKind llvm::ms_demangle::Node::kind () const inline
Definition at line 260 of file MicrosoftDemangleNodes.h.
References llvm::ms_demangle::OF_Default, and llvm::toString().
Referenced by llvm::ms_demangle::ArrayTypeNode::outputOneDimension(), llvm::ms_demangle::Demangler::parseTagUniqueName(), and synthesizeVariable().
output()
virtual void llvm::ms_demangle::Node::output (OutputStream & OS, OutputFlags Flags) const pure virtual
Implemented in llvm::ms_demangle::FunctionSymbolNode, llvm::ms_demangle::VariableSymbolNode, llvm::ms_demangle::EncodedStringLiteralNode, llvm::ms_demangle::LocalStaticGuardVariableNode, llvm::ms_demangle::SpecialTableSymbolNode, llvm::ms_demangle::SymbolNode, llvm::ms_demangle::RttiBaseClassDescriptorNode, llvm::ms_demangle::IntegerLiteralNode, llvm::ms_demangle::TemplateParameterReferenceNode, llvm::ms_demangle::QualifiedNameNode, llvm::ms_demangle::NodeArrayNode, llvm::ms_demangle::IntrinsicNode, llvm::ms_demangle::StructorIdentifierNode, llvm::ms_demangle::ConversionOperatorIdentifierNode, llvm::ms_demangle::LocalStaticGuardIdentifierNode, llvm::ms_demangle::LiteralOperatorIdentifierNode, llvm::ms_demangle::IntrinsicFunctionIdentifierNode, llvm::ms_demangle::NamedIdentifierNode, llvm::ms_demangle::DynamicStructorIdentifierNode, llvm::ms_demangle::VcallThunkIdentifierNode, and llvm::ms_demangle::TypeNode.
Referenced by llvm::ms_demangle::NodeArrayNode::output(), llvm::ms_demangle::Demangler::parseTagUniqueName(), and toString().
toString()
std::string Node::toString (OutputFlags Flags = OF_Default) const
Definition at line 115 of file MicrosoftDemangleNodes.cpp.
References initializeOutputStream(), and output().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp