LLVM: llvm::yaml::ScalarTraits< FixedSizeString< N > > Struct Template Reference
llvm::yaml::ScalarTraits< FixedSizeString< N > > Struct Template Reference
Static Public Member Functions
static void output (const FixedSizeString< N > &Fixed, void *, raw_ostream &OS)
static StringRef input (StringRef Scalar, void *, FixedSizeString< N > &Fixed)
static QuotingType mustQuote (StringRef S)
Detailed Description
template<std::size_t N>
struct llvm::yaml::ScalarTraits< FixedSizeString< N > >
Definition at line 216 of file MinidumpYAML.cpp.
Member Function Documentation
input()
template<std::size_t N> static StringRef llvm::yaml::ScalarTraits< FixedSizeString< N > >::input (StringRef Scalar, void * , FixedSizeString< N > & Fixed) inline static
Definition at line 221 of file MinidumpYAML.cpp.
References llvm::copy(), N, and llvm::StringRef::size().
mustQuote()
template<std::size_t N> static QuotingType llvm::yaml::ScalarTraits< FixedSizeString< N > >::mustQuote (StringRef S) inline static
Definition at line 230 of file MinidumpYAML.cpp.
References llvm::minidump::MemoryInfo::AllocationBase, llvm::minidump::MemoryInfo::AllocationProtect, llvm::minidump::CPUInfo::X86Info::AMDExtendedFeatures, llvm::minidump::MemoryInfo::BaseAddress, llvm::minidump::CPUInfo::X86Info::FeatureInfo, llvm::minidump::VSFixedFileInfo::FileDateHigh, llvm::minidump::VSFixedFileInfo::FileDateLow, llvm::minidump::VSFixedFileInfo::FileFlags, llvm::minidump::VSFixedFileInfo::FileFlagsMask, llvm::minidump::VSFixedFileInfo::FileOS, llvm::minidump::VSFixedFileInfo::FileSubtype, llvm::minidump::VSFixedFileInfo::FileType, llvm::minidump::VSFixedFileInfo::FileVersionHigh, llvm::minidump::VSFixedFileInfo::FileVersionLow, mapOptional(), mapOptionalHex(), mapRequiredHex(), llvm::minidump::VSFixedFileInfo::ProductVersionHigh, llvm::minidump::VSFixedFileInfo::ProductVersionLow, llvm::minidump::MemoryInfo::Protect, llvm::minidump::MemoryInfo::RegionSize, llvm::minidump::MemoryInfo::Reserved0, llvm::minidump::MemoryInfo::Reserved1, llvm::minidump::VSFixedFileInfo::Signature, llvm::minidump::MemoryInfo::State, llvm::minidump::VSFixedFileInfo::StructVersion, llvm::minidump::MemoryInfo::Type, llvm::minidump::CPUInfo::X86Info::VendorID, and llvm::minidump::CPUInfo::X86Info::VersionInfo.
output()
template<std::size_t N> static void llvm::yaml::ScalarTraits< FixedSizeString< N > >::output (const FixedSizeString< N > & Fixed, void * , raw_ostream & OS) inline static
Definition at line 217 of file MinidumpYAML.cpp.
References N.
The documentation for this struct was generated from the following file:
lib/ObjectYAML/MinidumpYAML.cpp