LLVM: llvm::HexagonSubtarget::HVXMemLatencyMutation Struct Reference
llvm::HexagonSubtarget::HVXMemLatencyMutation Struct Reference
#include "Target/Hexagon/HexagonSubtarget.h"
Public Member Functions
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Detailed Description
Definition at line 72 of file HexagonSubtarget.h.
Member Function Documentation
apply()
void HexagonSubtarget::HVXMemLatencyMutation::apply (ScheduleDAGInstrs * DAG) override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 141 of file HexagonSubtarget.cpp.
References llvm::SUnit::getInstr(), llvm::SDep::getKind(), llvm::SDep::getLatency(), llvm::MachineInstr::getOpcode(), llvm::SDep::getSUnit(), llvm::HexagonInstrInfo::getType(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::SDep::Order, llvm::SUnit::Preds, llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::SDep::setLatency(), SI, llvm::SUnit::Succs, llvm::ScheduleDAG::SUnits, llvm::ScheduleDAG::TII, llvm::HexagonII::TypeALU64, llvm::HexagonII::TypeM, llvm::HexagonII::TypeS_2op, and llvm::HexagonII::TypeS_3op.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonSubtarget.h
lib/Target/Hexagon/HexagonSubtarget.cpp