LLVM: llvm::bfi_detail::IrreducibleGraph::IrrNode Struct Reference
llvm::bfi_detail::IrreducibleGraph::IrrNode Struct Reference
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
Public Types
using iterator = std::deque< const IrrNode * >::const_iterator
Public Member Functions
IrrNode (const BlockNode &Node)
iterator pred_begin () const
iterator succ_begin () const
iterator pred_end () const
iterator succ_end () const
Public Attributes
BlockNode Node
unsigned NumIn = 0
std::deque< const IrrNode * > Edges
Detailed Description
Definition at line 600 of file BlockFrequencyInfoImpl.h.
Member Typedef Documentation
iterator
using llvm::bfi_detail::IrreducibleGraph::IrrNode::iterator = std::deque<const IrrNode *>::const_iterator
Definition at line 607 of file BlockFrequencyInfoImpl.h.
Constructor & Destructor Documentation
IrrNode()
llvm::bfi_detail::IrreducibleGraph::IrrNode::IrrNode (const BlockNode & Node) inline
Definition at line 605 of file BlockFrequencyInfoImpl.h.
Member Function Documentation
pred_begin()
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::pred_begin () const inline
Definition at line 609 of file BlockFrequencyInfoImpl.h.
pred_end()
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::pred_end () const inline
Definition at line 611 of file BlockFrequencyInfoImpl.h.
References llvm::succ_begin().
succ_begin()
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::succ_begin () const inline
Definition at line 610 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::GraphTraits< IrreducibleGraph >::child_begin().
succ_end()
iterator llvm::bfi_detail::IrreducibleGraph::IrrNode::succ_end () const inline
Definition at line 612 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::GraphTraits< IrreducibleGraph >::child_end().
Member Data Documentation
Edges
std::deque<const IrrNode *> llvm::bfi_detail::IrreducibleGraph::IrrNode::Edges
Definition at line 603 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge().
Node
BlockNode llvm::bfi_detail::IrreducibleGraph::IrrNode::Node
Definition at line 601 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::BlockEdgesAdder< BT >::operator()().
NumIn
unsigned llvm::bfi_detail::IrreducibleGraph::IrrNode::NumIn = 0
Definition at line 602 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/BlockFrequencyInfoImpl.h