LLVM: llvm::MDNodeSubsetEqualImpl< DIDerivedType > Struct Template Reference
llvm::MDNodeSubsetEqualImpl< DIDerivedType > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Types
using KeyTy = MDNodeKeyImpl< DIDerivedType >
Static Public Member Functions
static bool isSubsetEqual (const KeyTy &LHS, const DIDerivedType *RHS)
static bool isSubsetEqual (const DIDerivedType *LHS, const DIDerivedType *RHS)
static bool isODRMember (unsigned Tag, const Metadata *Scope, const MDString *Name, const DIDerivedType *RHS)
Subprograms compare equal if they declare the same function in an ODR type.
Detailed Description
template<>
struct llvm::MDNodeSubsetEqualImpl< DIDerivedType >
Definition at line 465 of file LLVMContextImpl.h.
Member Typedef Documentation
KeyTy
using llvm::MDNodeSubsetEqualImpl< DIDerivedType >::KeyTy = MDNodeKeyImpl<DIDerivedType>
Definition at line 466 of file LLVMContextImpl.h.
Member Function Documentation
isODRMember()
static bool llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isODRMember (unsigned Tag, const Metadata * Scope, const MDString * Name, const DIDerivedType * RHS) inline static
Subprograms compare equal if they declare the same function in an ODR type.
Definition at line 479 of file LLVMContextImpl.h.
References llvm::DIType::getRawName(), llvm::DIType::getRawScope(), and llvm::DINode::getTag().
isSubsetEqual() [1/2]
static bool llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual (const KeyTy & LHS, const DIDerivedType * RHS) inline static
Definition at line 468 of file LLVMContextImpl.h.
References llvm::MDNodeKeyImpl< DIDerivedType >::Name, llvm::MDNodeKeyImpl< DIDerivedType >::Scope, and llvm::MDNodeKeyImpl< DIDerivedType >::Tag.
isSubsetEqual() [2/2]
static bool llvm::MDNodeSubsetEqualImpl< DIDerivedType >::isSubsetEqual (const DIDerivedType * LHS, const DIDerivedType * RHS) inline static
Definition at line 472 of file LLVMContextImpl.h.
References llvm::DIType::getRawName(), llvm::DIType::getRawScope(), and llvm::DINode::getTag().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h