LLVM: llvm::CodeViewYAML::GlobalHash Struct Reference
llvm::CodeViewYAML::GlobalHash Struct Reference
#include "llvm/ObjectYAML/CodeViewYAMLTypeHashing.h"
Public Member Functions
GlobalHash ()=default
GlobalHash (StringRef S)
GlobalHash (ArrayRef< uint8_t > S)
Public Attributes
yaml::BinaryRef Hash
Detailed Description
Definition at line 31 of file CodeViewYAMLTypeHashing.h.
Constructor & Destructor Documentation
GlobalHash() [1/3]
llvm::CodeViewYAML::GlobalHash::GlobalHash () default
GlobalHash() [2/3]
llvm::CodeViewYAML::GlobalHash::GlobalHash (StringRef S) inline explicit
Definition at line 33 of file CodeViewYAMLTypeHashing.h.
References assert(), and llvm::StringRef::size().
GlobalHash() [3/3]
llvm::CodeViewYAML::GlobalHash::GlobalHash (ArrayRef< uint8_t > S) inline explicit
Definition at line 36 of file CodeViewYAMLTypeHashing.h.
References assert(), and llvm::ArrayRef< T >::size().
Member Data Documentation
Hash
yaml::BinaryRef llvm::CodeViewYAML::GlobalHash::Hash
Definition at line 39 of file CodeViewYAMLTypeHashing.h.
The documentation for this struct was generated from the following file:
include/llvm/ObjectYAML/CodeViewYAMLTypeHashing.h