LLVM: llvm::pdb::NamedStreamMapTraits Struct Reference
llvm::pdb::NamedStreamMapTraits Struct Reference
#include "llvm/DebugInfo/PDB/Native/NamedStreamMap.h"
Public Member Functions
NamedStreamMapTraits (NamedStreamMap &NS)
uint16_t hashLookupKey (StringRef S) const
StringRef storageKeyToLookupKey (uint32_t Offset) const
uint32_t lookupKeyToStorageKey (StringRef S)
Public Attributes
NamedStreamMap * NS
Detailed Description
Definition at line 29 of file NamedStreamMap.h.
Constructor & Destructor Documentation
NamedStreamMapTraits()
NamedStreamMapTraits::NamedStreamMapTraits (NamedStreamMap & NS) explicit
Definition at line 29 of file NamedStreamMap.cpp.
Member Function Documentation
hashLookupKey()
uint16_t NamedStreamMapTraits::hashLookupKey (StringRef S) const
Definition at line 31 of file NamedStreamMap.cpp.
References llvm::pdb::hashStringV1().
lookupKeyToStorageKey()
uint32_t NamedStreamMapTraits::lookupKeyToStorageKey (StringRef S)
Definition at line 45 of file NamedStreamMap.cpp.
References llvm::pdb::NamedStreamMap::appendStringData(), and NS.
storageKeyToLookupKey()
StringRef NamedStreamMapTraits::storageKeyToLookupKey (uint32_t Offset) const
Definition at line 41 of file NamedStreamMap.cpp.
References llvm::pdb::NamedStreamMap::getString(), and NS.
Member Data Documentation
NS
NamedStreamMap* llvm::pdb::NamedStreamMapTraits::NS
Definition at line 30 of file NamedStreamMap.h.
Referenced by lookupKeyToStorageKey(), and storageKeyToLookupKey().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NamedStreamMap.h
lib/DebugInfo/PDB/Native/NamedStreamMap.cpp