LLVM: llvm::AnalysisCallGraphWrapperPassTraits Struct Reference
llvm::AnalysisCallGraphWrapperPassTraits Struct Reference
Static Public Member Functions
static CallGraph * getGraph (CallGraphWrapperPass *P)
Detailed Description
Definition at line 38 of file CallPrinter.cpp.
Member Function Documentation
getGraph()
static CallGraph* llvm::AnalysisCallGraphWrapperPassTraits::getGraph (CallGraphWrapperPass * P) inline static
Definition at line 39 of file CallPrinter.cpp.
References llvm::CallGraphWrapperPass::getCallGraph(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS(), llvm::initializeCallGraphDOTPrinterPass(), and llvm::initializeCallGraphViewerPass().
The documentation for this struct was generated from the following file:
lib/Analysis/CallPrinter.cpp