LLVM: llvm::PluginLoader Struct Reference
llvm::PluginLoader Struct Reference
#include "llvm/Support/PluginLoader.h"
Public Member Functions
void operator= (const std::string &Filename)
Static Public Member Functions
static unsigned getNumPlugins ()
static std::string & getPlugin (unsigned num)
Detailed Description
Definition at line 22 of file PluginLoader.h.
Member Function Documentation
getNumPlugins()
unsigned PluginLoader::getNumPlugins () static
Definition at line 36 of file PluginLoader.cpp.
References llvm::ManagedStaticBase::isConstructed(), and llvm::Lock.
getPlugin()
std::string & PluginLoader::getPlugin (unsigned num) static
Definition at line 41 of file PluginLoader.cpp.
References assert(), llvm::ManagedStaticBase::isConstructed(), and llvm::Lock.
operator=()
void PluginLoader::operator= (const std::string & Filename)
Definition at line 25 of file PluginLoader.cpp.
References llvm::Error, llvm::errs(), llvm::sys::DynamicLibrary::LoadLibraryPermanently(), and llvm::Lock.
The documentation for this struct was generated from the following files:
include/llvm/Support/PluginLoader.h
lib/Support/PluginLoader.cpp