LLVM: llvm::GraphTraits< Inverse< VPRegionBlock * > > Struct Template Reference
llvm::GraphTraits< Inverse< VPRegionBlock * > > Struct Template Reference
#include "Transforms/Vectorize/VPlan.h"
Public Types
using GraphRef = VPRegionBlock *
using nodes_iterator = df_iterator< NodeRef >
Public Types inherited from llvm::GraphTraits< Inverse< VPBlockBase *> >
using NodeRef = typename Inverse< VPBlockBase * > ::UnknownGraphTypeError
Static Public Member Functions
static NodeRef getEntryNode (Inverse< GraphRef > N)
static nodes_iterator nodes_begin (GraphRef N)
static nodes_iterator nodes_end (GraphRef N)
Detailed Description
template<>
struct llvm::GraphTraits< Inverse< VPRegionBlock * > >
Definition at line 1323 of file VPlan.h.
Member Typedef Documentation
GraphRef
using llvm::GraphTraits< Inverse< VPRegionBlock * > >::GraphRef = VPRegionBlock *
Definition at line 1325 of file VPlan.h.
nodes_iterator
using llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_iterator = df_iterator<NodeRef>
Definition at line 1326 of file VPlan.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< Inverse< VPRegionBlock * > >::getEntryNode (Inverse< GraphRef > N) inline static
Definition at line 1328 of file VPlan.h.
References llvm::Inverse< GraphType >::Graph.
nodes_begin()
static nodes_iterator llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_begin (GraphRef N) inline static
Definition at line 1332 of file VPlan.h.
References llvm::sys::path::begin(), and llvm::VPRegionBlock::getExit().
nodes_end()
static nodes_iterator llvm::GraphTraits< Inverse< VPRegionBlock * > >::nodes_end (GraphRef N) inline static
Definition at line 1336 of file VPlan.h.
References llvm::sys::path::end().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h