LLVM: llvm::MDNodeKeyImpl< DIGlobalVariable > Struct Template Reference
llvm::MDNodeKeyImpl< DIGlobalVariable > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, MDString *Name, MDString *LinkageName, Metadata *File, unsigned Line, Metadata *Type, bool IsLocalToUnit, bool IsDefinition, Metadata *StaticDataMemberDeclaration, Metadata *TemplateParams, uint32_t AlignInBits)
MDNodeKeyImpl (const DIGlobalVariable *N)
bool isKeyOf (const DIGlobalVariable *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
MDString * Name
MDString * LinkageName
Metadata * File
unsigned Line
Metadata * Type
bool IsLocalToUnit
bool IsDefinition
Metadata * StaticDataMemberDeclaration
Metadata * TemplateParams
uint32_t AlignInBits
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIGlobalVariable >
Definition at line 881 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIGlobalVariable >::MDNodeKeyImpl (Metadata * Scope, MDString * Name, MDString * LinkageName, Metadata * File, unsigned Line, Metadata * Type, bool IsLocalToUnit, bool IsDefinition, Metadata * StaticDataMemberDeclaration, Metadata * TemplateParams, uint32_t AlignInBits) inline
Definition at line 894 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIGlobalVariable >::MDNodeKeyImpl (const DIGlobalVariable * N) inline
Definition at line 904 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIGlobalVariable >::getHashValue () const inline
Definition at line 925 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::isKeyOf (const DIGlobalVariable * RHS) const inline
Definition at line 913 of file LLVMContextImpl.h.
References llvm::DIVariable::getAlignInBits(), llvm::DIVariable::getLine(), llvm::DIVariable::getRawFile(), llvm::DIGlobalVariable::getRawLinkageName(), llvm::DIVariable::getRawName(), llvm::DIVariable::getRawScope(), llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration(), llvm::DIGlobalVariable::getRawTemplateParams(), llvm::DIVariable::getRawType(), llvm::DIGlobalVariable::isDefinition(), and llvm::DIGlobalVariable::isLocalToUnit().
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DIGlobalVariable >::AlignInBits
Definition at line 892 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::File
Definition at line 885 of file LLVMContextImpl.h.
IsDefinition
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::IsDefinition
Definition at line 889 of file LLVMContextImpl.h.
IsLocalToUnit
bool llvm::MDNodeKeyImpl< DIGlobalVariable >::IsLocalToUnit
Definition at line 888 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DIGlobalVariable >::Line
Definition at line 886 of file LLVMContextImpl.h.
LinkageName
MDString* llvm::MDNodeKeyImpl< DIGlobalVariable >::LinkageName
Definition at line 884 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIGlobalVariable >::Name
Definition at line 883 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::Scope
Definition at line 882 of file LLVMContextImpl.h.
StaticDataMemberDeclaration
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::StaticDataMemberDeclaration
Definition at line 890 of file LLVMContextImpl.h.
TemplateParams
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::TemplateParams
Definition at line 891 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariable >::Type
Definition at line 887 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h