LLVM: llvm::R600RegisterInfo Struct Reference
llvm::R600RegisterInfo Struct Reference final
#include "Target/AMDGPU/R600RegisterInfo.h"
Public Member Functions
R600RegisterInfo ()
BitVector getReservedRegs (const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Register getFrameRegister (const MachineFunction &MF) const override
unsigned getHWRegChan (unsigned reg) const
get the HW encoding for a register's channel.
unsigned getHWRegIndex (unsigned Reg) const
const TargetRegisterClass * getCFGStructurizerRegClass (MVT VT) const
get the register class of the specified type to use in the CFGStructurizer
const RegClassWeight & getRegClassWeight (const TargetRegisterClass *RC) const override
bool isPhysRegLiveAcrossClauses (unsigned Reg) const
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
void reserveRegisterTuples (BitVector &Reserved, unsigned Reg) const
Public Attributes
RegClassWeight RCW
Detailed Description
Definition at line 22 of file R600RegisterInfo.h.
Constructor & Destructor Documentation
R600RegisterInfo()
R600RegisterInfo::R600RegisterInfo ()
Definition at line 23 of file R600RegisterInfo.cpp.
References RCW, llvm::RegClassWeight::RegWeight, and llvm::RegClassWeight::WeightLimit.
Member Function Documentation
eliminateFrameIndex()
void R600RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 108 of file R600RegisterInfo.cpp.
References llvm_unreachable.
getCalleeSavedRegs()
const MCPhysReg * R600RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 65 of file R600RegisterInfo.cpp.
References CalleeSavedReg.
getCFGStructurizerRegClass()
const TargetRegisterClass * R600RegisterInfo::getCFGStructurizerRegClass (MVT VT) const
get the register class of the specified type to use in the CFGStructurizer
Definition at line 82 of file R600RegisterInfo.cpp.
References llvm::MVT::i32, and llvm::MVT::SimpleTy.
getFrameRegister()
Register R600RegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 70 of file R600RegisterInfo.cpp.
Referenced by llvm::R600FrameLowering::getFrameIndexReference().
getHWRegChan()
unsigned R600RegisterInfo::getHWRegChan (unsigned reg) const
get the HW encoding for a register's channel.
Definition at line 74 of file R600RegisterInfo.cpp.
References HW_CHAN_SHIFT.
Referenced by llvm::createR600ExpandSpecialInstrsPass(), llvm::R600InstrInfo::expandPostRAPseudo(), llvm::R600InstrInfo::fitsConstReadLimitations(), and llvm::R600InstrInfo::getSrcs().
getHWRegIndex()
unsigned R600RegisterInfo::getHWRegIndex (unsigned Reg) const
Definition at line 78 of file R600RegisterInfo.cpp.
References GET_REG_INDEX.
Referenced by llvm::R600InstrInfo::expandPostRAPseudo().
getRegClassWeight()
const RegClassWeight & R600RegisterInfo::getRegClassWeight (const TargetRegisterClass * RC) const override
Definition at line 90 of file R600RegisterInfo.cpp.
References RCW.
getReservedRegs()
BitVector R600RegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 31 of file R600RegisterInfo.cpp.
References llvm::sys::path::begin(), E, llvm::sys::path::end(), llvm::R600Subtarget::getInstrInfo(), llvm::MachineFunction::getSubtarget(), I, reserveRegisterTuples(), llvm::ARM_MB::ST, and TII.
isPhysRegLiveAcrossClauses()
bool R600RegisterInfo::isPhysRegLiveAcrossClauses (unsigned Reg) const
Definition at line 95 of file R600RegisterInfo.cpp.
References assert(), and llvm::Register::isVirtualRegister().
Referenced by llvm::R600InstrInfo::isLegalToSplitMBBAt().
reserveRegisterTuples()
void R600RegisterInfo::reserveRegisterTuples (BitVector & Reserved, unsigned Reg) const
Definition at line 115 of file R600RegisterInfo.cpp.
References llvm::MCRegAliasIterator::isValid(), and llvm::BitVector::set().
Referenced by getReservedRegs().
Member Data Documentation
RCW
RegClassWeight llvm::R600RegisterInfo::RCW
Definition at line 23 of file R600RegisterInfo.h.
Referenced by getRegClassWeight(), and R600RegisterInfo().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/R600RegisterInfo.h
lib/Target/AMDGPU/R600RegisterInfo.cpp