LLVM: llvm::MDNodeKeyImpl< DISubprogram > Struct Template Reference
llvm::MDNodeKeyImpl< DISubprogram > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, MDString *Name, MDString *LinkageName, Metadata *File, unsigned Line, Metadata *Type, unsigned ScopeLine, Metadata *ContainingType, unsigned VirtualIndex, int ThisAdjustment, unsigned Flags, unsigned SPFlags, Metadata *Unit, Metadata *TemplateParams, Metadata *Declaration, Metadata *RetainedNodes, Metadata *ThrownTypes)
MDNodeKeyImpl (const DISubprogram *N)
bool isKeyOf (const DISubprogram *RHS) const
bool isDefinition () const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
MDString * Name
MDString * LinkageName
Metadata * File
unsigned Line
Metadata * Type
unsigned ScopeLine
Metadata * ContainingType
unsigned VirtualIndex
int ThisAdjustment
unsigned Flags
unsigned SPFlags
Metadata * Unit
Metadata * TemplateParams
Metadata * Declaration
Metadata * RetainedNodes
Metadata * ThrownTypes
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DISubprogram >
Definition at line 608 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DISubprogram >::MDNodeKeyImpl (Metadata * Scope, MDString * Name, MDString * LinkageName, Metadata * File, unsigned Line, Metadata * Type, unsigned ScopeLine, Metadata * ContainingType, unsigned VirtualIndex, int ThisAdjustment, unsigned Flags, unsigned SPFlags, Metadata * Unit, Metadata * TemplateParams, Metadata * Declaration, Metadata * RetainedNodes, Metadata * ThrownTypes) inline
Definition at line 627 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DISubprogram >::MDNodeKeyImpl (const DISubprogram * N) inline
Definition at line 640 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DISubprogram >::getHashValue () const inline
Definition at line 671 of file LLVMContextImpl.h.
References llvm::hash_combine().
isDefinition()
bool llvm::MDNodeKeyImpl< DISubprogram >::isDefinition () const inline
Definition at line 669 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual().
isKeyOf()
bool llvm::MDNodeKeyImpl< DISubprogram >::isKeyOf (const DISubprogram * RHS) const inline
Definition at line 653 of file LLVMContextImpl.h.
References llvm::DIScope::getRawFile().
Member Data Documentation
ContainingType
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::ContainingType
Definition at line 616 of file LLVMContextImpl.h.
Declaration
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::Declaration
Definition at line 623 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::File
Definition at line 612 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DISubprogram >::Flags
Definition at line 619 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DISubprogram >::Line
Definition at line 613 of file LLVMContextImpl.h.
LinkageName
MDString* llvm::MDNodeKeyImpl< DISubprogram >::LinkageName
Definition at line 611 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual().
Name
MDString* llvm::MDNodeKeyImpl< DISubprogram >::Name
Definition at line 610 of file LLVMContextImpl.h.
RetainedNodes
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::RetainedNodes
Definition at line 624 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::Scope
Definition at line 609 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual().
ScopeLine
unsigned llvm::MDNodeKeyImpl< DISubprogram >::ScopeLine
Definition at line 615 of file LLVMContextImpl.h.
SPFlags
unsigned llvm::MDNodeKeyImpl< DISubprogram >::SPFlags
Definition at line 620 of file LLVMContextImpl.h.
TemplateParams
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::TemplateParams
Definition at line 622 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeSubsetEqualImpl< DISubprogram >::isSubsetEqual().
ThisAdjustment
int llvm::MDNodeKeyImpl< DISubprogram >::ThisAdjustment
Definition at line 618 of file LLVMContextImpl.h.
ThrownTypes
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::ThrownTypes
Definition at line 625 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::Type
Definition at line 614 of file LLVMContextImpl.h.
Unit
Metadata* llvm::MDNodeKeyImpl< DISubprogram >::Unit
Definition at line 621 of file LLVMContextImpl.h.
VirtualIndex
unsigned llvm::MDNodeKeyImpl< DISubprogram >::VirtualIndex
Definition at line 617 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h