LLVM: llvm::rdf::RegisterRef Struct Reference
llvm::rdf::RegisterRef Struct Reference
#include "Target/Hexagon/RDFRegisters.h"
Public Member Functions
RegisterRef ()=default
RegisterRef (RegisterId R, LaneBitmask M=LaneBitmask::getAll())
operator bool () const
bool operator== (const RegisterRef &RR) const
bool operator!= (const RegisterRef &RR) const
bool operator< (const RegisterRef &RR) const
Public Attributes
RegisterId Reg = 0
LaneBitmask Mask = LaneBitmask::getNone()
Detailed Description
Definition at line 71 of file RDFRegisters.h.
Constructor & Destructor Documentation
RegisterRef() [1/2]
llvm::rdf::RegisterRef::RegisterRef () default
RegisterRef() [2/2]
llvm::rdf::RegisterRef::RegisterRef (RegisterId R, LaneBitmask M = LaneBitmask::getAll()) inline explicit
Definition at line 76 of file RDFRegisters.h.
Member Function Documentation
operator bool()
llvm::rdf::RegisterRef::operator bool () const inline
Definition at line 79 of file RDFRegisters.h.
References llvm::LaneBitmask::any().
operator!=()
bool llvm::rdf::RegisterRef::operator!= (const RegisterRef & RR) const inline
Definition at line 87 of file RDFRegisters.h.
References llvm::operator==().
operator<()
bool llvm::rdf::RegisterRef::operator< (const RegisterRef & RR) const inline
Definition at line 91 of file RDFRegisters.h.
References Mask, and Reg.
operator==()
bool llvm::rdf::RegisterRef::operator== (const RegisterRef & RR) const inline
Definition at line 83 of file RDFRegisters.h.
References Mask, and Reg.
Member Data Documentation
Mask
LaneBitmask llvm::rdf::RegisterRef::Mask = LaneBitmask::getNone()
Definition at line 73 of file RDFRegisters.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator<(), operator==(), llvm::rdf::DataFlowGraph::pack(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), and llvm::rdf::DataFlowGraph::restrictRef().
Reg
RegisterId llvm::rdf::RegisterRef::Reg = 0
Definition at line 72 of file RDFRegisters.h.
Referenced by llvm::rdf::PhysicalRegisterInfo::alias(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator<(), operator==(), llvm::rdf::DataFlowGraph::pack(), llvm::rdf::DataFlowGraph::pushAllDefs(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), and llvm::rdf::DataFlowGraph::restrictRef().
The documentation for this struct was generated from the following file:
lib/Target/Hexagon/RDFRegisters.h