LLVM: llvm::object::coff_file_header Struct Reference
llvm::object::coff_file_header Struct Reference
#include "llvm/Object/COFF.h"
Public Member Functions
bool isImportLibrary () const
Public Attributes
support::ulittle16_t Machine
support::ulittle16_t NumberOfSections
support::ulittle32_t TimeDateStamp
support::ulittle32_t PointerToSymbolTable
support::ulittle32_t NumberOfSymbols
support::ulittle16_t SizeOfOptionalHeader
support::ulittle16_t Characteristics
Detailed Description
Definition at line 75 of file COFF.h.
Member Function Documentation
isImportLibrary()
bool llvm::object::coff_file_header::isImportLibrary () const inline
Definition at line 84 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), llvm::object::COFFObjectFile::getCharacteristics(), llvm::object::COFFObjectFile::getNumberOfSections(), llvm::object::COFFObjectFile::getPointerToSymbolTable(), llvm::object::COFFObjectFile::getRawNumberOfSymbols(), llvm::object::COFFObjectFile::getSizeOfOptionalHeader(), and llvm::object::COFFObjectFile::section_end().
Member Data Documentation
Characteristics
support::ulittle16_t llvm::object::coff_file_header::Characteristics
Definition at line 82 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getCharacteristics().
Machine
support::ulittle16_t llvm::object::coff_file_header::Machine
Definition at line 76 of file COFF.h.
Referenced by llvm::object::coffnamecpy(), llvm::object::COFFObjectFile::COFFObjectFile(), and llvm::object::COFFObjectFile::getMachine().
NumberOfSections
support::ulittle16_t llvm::object::coff_file_header::NumberOfSections
Definition at line 77 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), and llvm::object::COFFObjectFile::getNumberOfSections().
NumberOfSymbols
support::ulittle32_t llvm::object::coff_file_header::NumberOfSymbols
Definition at line 80 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getRawNumberOfSymbols().
PointerToSymbolTable
support::ulittle32_t llvm::object::coff_file_header::PointerToSymbolTable
Definition at line 79 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getPointerToSymbolTable().
SizeOfOptionalHeader
support::ulittle16_t llvm::object::coff_file_header::SizeOfOptionalHeader
Definition at line 81 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), and llvm::object::COFFObjectFile::getSizeOfOptionalHeader().
TimeDateStamp
support::ulittle32_t llvm::object::coff_file_header::TimeDateStamp
Definition at line 78 of file COFF.h.
Referenced by llvm::object::COFFObjectFile::getTimeDateStamp().
The documentation for this struct was generated from the following file:
include/llvm/Object/COFF.h