LLVM: llvm::GraphTraits< const VPRegionBlock * > Struct Template Reference
llvm::GraphTraits< const VPRegionBlock * > Struct Template Reference
#include "Transforms/Vectorize/VPlan.h"
Public Types
using GraphRef = const VPRegionBlock *
using nodes_iterator = df_iterator< NodeRef >
Public Types inherited from llvm::GraphTraits< const VPBlockBase *>
using NodeRef = typename const VPBlockBase *::UnknownGraphTypeError
Static Public Member Functions
static NodeRef getEntryNode (GraphRef N)
static nodes_iterator nodes_begin (GraphRef N)
static nodes_iterator nodes_end (GraphRef N)
Detailed Description
template<>
struct llvm::GraphTraits< const VPRegionBlock * >
Definition at line 1304 of file VPlan.h.
Member Typedef Documentation
GraphRef
using llvm::GraphTraits< const VPRegionBlock * >::GraphRef = const VPRegionBlock *
Definition at line 1306 of file VPlan.h.
nodes_iterator
using llvm::GraphTraits< const VPRegionBlock * >::nodes_iterator = df_iterator<NodeRef>
Definition at line 1307 of file VPlan.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< const VPRegionBlock * >::getEntryNode (GraphRef N) inline static
Definition at line 1309 of file VPlan.h.
References llvm::VPRegionBlock::getEntry().
nodes_begin()
static nodes_iterator llvm::GraphTraits< const VPRegionBlock * >::nodes_begin (GraphRef N) inline static
Definition at line 1311 of file VPlan.h.
References llvm::sys::path::begin(), and llvm::VPRegionBlock::getEntry().
nodes_end()
static nodes_iterator llvm::GraphTraits< const VPRegionBlock * >::nodes_end (GraphRef N) inline static
Definition at line 1315 of file VPlan.h.
References llvm::sys::path::end().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h