LLVM: llvm::InlineAsmKeyType Struct Reference
llvm::InlineAsmKeyType Struct Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = ConstantInfo< InlineAsm >::TypeClass
Public Member Functions
InlineAsmKeyType (StringRef AsmString, StringRef Constraints, FunctionType *FTy, bool HasSideEffects, bool IsAlignStack, InlineAsm::AsmDialect AsmDialect)
InlineAsmKeyType (const InlineAsm *Asm, SmallVectorImpl< Constant *> &)
bool operator== (const InlineAsmKeyType &X) const
bool operator== (const InlineAsm *Asm) const
unsigned getHash () const
InlineAsm * create (TypeClass *Ty) const
Public Attributes
StringRef AsmString
StringRef Constraints
FunctionType * FTy
bool HasSideEffects
bool IsAlignStack
InlineAsm::AsmDialect AsmDialect
Detailed Description
Definition at line 412 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
using llvm::InlineAsmKeyType::TypeClass = ConstantInfo<InlineAsm>::TypeClass
Definition at line 453 of file ConstantsContext.h.
Constructor & Destructor Documentation
InlineAsmKeyType() [1/2]
llvm::InlineAsmKeyType::InlineAsmKeyType (StringRef AsmString, StringRef Constraints, FunctionType * FTy, bool HasSideEffects, bool IsAlignStack, InlineAsm::AsmDialect AsmDialect) inline
Definition at line 420 of file ConstantsContext.h.
InlineAsmKeyType() [2/2]
llvm::InlineAsmKeyType::InlineAsmKeyType (const InlineAsm * Asm, SmallVectorImpl< Constant *> &) inline
Definition at line 427 of file ConstantsContext.h.
Member Function Documentation
create()
InlineAsm* llvm::InlineAsmKeyType::create (TypeClass * Ty) const inline
Definition at line 455 of file ConstantsContext.h.
References assert(), and llvm::PointerType::getUnqual().
getHash()
unsigned llvm::InlineAsmKeyType::getHash () const inline
Definition at line 448 of file ConstantsContext.h.
References llvm::hash_combine().
operator==() [1/2]
bool llvm::InlineAsmKeyType::operator== (const InlineAsmKeyType & X) const inline
Definition at line 432 of file ConstantsContext.h.
References AsmDialect, AsmString, Constraints, FTy, HasSideEffects, and IsAlignStack.
operator==() [2/2]
bool llvm::InlineAsmKeyType::operator== (const InlineAsm * Asm) const inline
Definition at line 439 of file ConstantsContext.h.
References llvm::InlineAsm::getAsmString(), llvm::InlineAsm::getConstraintString(), llvm::InlineAsm::getDialect(), llvm::InlineAsm::getFunctionType(), llvm::InlineAsm::hasSideEffects(), and llvm::InlineAsm::isAlignStack().
Member Data Documentation
AsmDialect
InlineAsm::AsmDialect llvm::InlineAsmKeyType::AsmDialect
Definition at line 418 of file ConstantsContext.h.
Referenced by operator==().
AsmString
StringRef llvm::InlineAsmKeyType::AsmString
Definition at line 413 of file ConstantsContext.h.
Referenced by operator==().
Constraints
StringRef llvm::InlineAsmKeyType::Constraints
Definition at line 414 of file ConstantsContext.h.
Referenced by operator==().
FTy
FunctionType* llvm::InlineAsmKeyType::FTy
Definition at line 415 of file ConstantsContext.h.
Referenced by operator==().
HasSideEffects
bool llvm::InlineAsmKeyType::HasSideEffects
Definition at line 416 of file ConstantsContext.h.
Referenced by operator==().
IsAlignStack
bool llvm::InlineAsmKeyType::IsAlignStack
Definition at line 417 of file ConstantsContext.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/IR/ConstantsContext.h