LLVM: llvm::LoopBodyTraits Struct Reference
llvm::LoopBodyTraits Struct Reference
#include "llvm/Analysis/LoopIterator.h"
Classes
struct LoopBodyFilter
class WrappedSuccIterator
Public Types
using NodeRef = std::pair< const Loop *, BasicBlock * >
using ChildIteratorType = filter_iterator< WrappedSuccIterator, LoopBodyFilter >
Static Public Member Functions
static NodeRef getEntryNode (const Loop &G)
static ChildIteratorType child_begin (NodeRef Node)
static ChildIteratorType child_end (NodeRef Node)
Detailed Description
Definition at line 40 of file LoopIterator.h.
Member Typedef Documentation
ChildIteratorType
using llvm::LoopBodyTraits::ChildIteratorType = filter_iterator<WrappedSuccIterator, LoopBodyFilter>
Definition at line 72 of file LoopIterator.h.
NodeRef
using llvm::LoopBodyTraits::NodeRef = std::pair<const Loop *, BasicBlock *>
Definition at line 41 of file LoopIterator.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::LoopBodyTraits::child_begin (NodeRef Node) inline static
Definition at line 76 of file LoopIterator.h.
References llvm::sys::path::begin(), llvm::make_filter_range(), llvm::succ_begin(), and llvm::succ_end().
child_end()
static ChildIteratorType llvm::LoopBodyTraits::child_end (NodeRef Node) inline static
Definition at line 84 of file LoopIterator.h.
References llvm::sys::path::end(), llvm::make_filter_range(), llvm::succ_begin(), and llvm::succ_end().
getEntryNode()
static NodeRef llvm::LoopBodyTraits::getEntryNode (const Loop & G) inline static
Definition at line 74 of file LoopIterator.h.
References G, and llvm::LoopBase< BlockT, LoopT >::getHeader().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/LoopIterator.h