LLVM: llvm::MDNodeKeyImpl< DITemplateTypeParameter > Struct Template Reference
llvm::MDNodeKeyImpl< DITemplateTypeParameter > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (MDString *Name, Metadata *Type)
MDNodeKeyImpl (const DITemplateTypeParameter *N)
bool isKeyOf (const DITemplateTypeParameter *RHS) const
unsigned getHashValue () const
Public Attributes
MDString * Name
Metadata * Type
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DITemplateTypeParameter >
Definition at line 846 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DITemplateTypeParameter >::MDNodeKeyImpl (MDString * Name, Metadata * Type) inline
Definition at line 850 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DITemplateTypeParameter >::MDNodeKeyImpl (const DITemplateTypeParameter * N) inline
Definition at line 851 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DITemplateTypeParameter >::getHashValue () const inline
Definition at line 858 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DITemplateTypeParameter >::isKeyOf (const DITemplateTypeParameter * RHS) const inline
Definition at line 854 of file LLVMContextImpl.h.
References llvm::DITemplateParameter::getRawName(), and llvm::DITemplateParameter::getRawType().
Member Data Documentation
Name
MDString* llvm::MDNodeKeyImpl< DITemplateTypeParameter >::Name
Definition at line 847 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DITemplateTypeParameter >::Type
Definition at line 848 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h