LLVM: llvm::KnownBits Struct Reference
llvm::KnownBits Struct Reference
#include "llvm/Support/KnownBits.h"
Public Member Functions
KnownBits ()
KnownBits (unsigned BitWidth)
Create a known bits object of BitWidth bits initialized to unknown.
unsigned getBitWidth () const
Get the bit width of this value.
bool hasConflict () const
Returns true if there is conflicting information.
bool isConstant () const
Returns true if we know the value of all bits.
const APInt & getConstant () const
Returns the value when all bits have a known value.
bool isUnknown () const
Returns true if we don't know any bits.
void resetAll ()
Resets the known state of all bits.
bool isZero () const
Returns true if value is all zero.
bool isAllOnes () const
Returns true if value is all one bits.
void setAllZero ()
Make all bits known to be zero and discard any previous information.
void setAllOnes ()
Make all bits known to be one and discard any previous information.
bool isNegative () const
Returns true if this value is known to be negative.
bool isNonNegative () const
Returns true if this value is known to be non-negative.
bool isStrictlyPositive () const
Returns true if this value is known to be positive.
void makeNegative ()
Make this value negative.
void makeNonNegative ()
Make this value non-negative.
APInt getMinValue () const
Return the minimal value possible given these KnownBits.
APInt getMaxValue () const
Return the maximal value possible given these KnownBits.
KnownBits trunc (unsigned BitWidth) const
Truncate the underlying known Zero and One bits.
KnownBits zext (unsigned BitWidth, bool ExtendedBitsAreKnownZero) const
Extends the underlying known Zero and One bits.
KnownBits sext (unsigned BitWidth) const
Sign extends the underlying known Zero and One bits.
KnownBits zextOrTrunc (unsigned BitWidth, bool ExtendedBitsAreKnownZero) const
Extends or truncates the underlying known Zero and One bits.
unsigned countMinTrailingZeros () const
Returns the minimum number of trailing zero bits.
unsigned countMinTrailingOnes () const
Returns the minimum number of trailing one bits.
unsigned countMinLeadingZeros () const
Returns the minimum number of leading zero bits.
unsigned countMinLeadingOnes () const
Returns the minimum number of leading one bits.
unsigned countMinSignBits () const
Returns the number of times the sign bit is replicated into the other bits.
unsigned countMaxTrailingZeros () const
Returns the maximum number of trailing zero bits possible.
unsigned countMaxTrailingOnes () const
Returns the maximum number of trailing one bits possible.
unsigned countMaxLeadingZeros () const
Returns the maximum number of leading zero bits possible.
unsigned countMaxLeadingOnes () const
Returns the maximum number of leading one bits possible.
unsigned countMinPopulation () const
Returns the number of bits known to be one.
unsigned countMaxPopulation () const
Returns the maximum number of bits that could be one.
Static Public Member Functions
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, const KnownBits &Carry)
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
static KnownBits computeForAddSub (bool Add, bool NSW, const KnownBits &LHS, KnownBits RHS)
Compute known bits resulting from adding LHS and RHS.
Public Attributes
APInt Zero
APInt One
Detailed Description
Definition at line 22 of file KnownBits.h.
Constructor & Destructor Documentation
KnownBits() [1/2]
llvm::KnownBits::KnownBits () inline
Definition at line 33 of file KnownBits.h.
Referenced by sext(), trunc(), zext(), and zextOrTrunc().
KnownBits() [2/2]
llvm::KnownBits::KnownBits (unsigned BitWidth) inline
Create a known bits object of BitWidth bits initialized to unknown.
Definition at line 36 of file KnownBits.h.
Member Function Documentation
computeForAddCarry()
KnownBits KnownBits::computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, const KnownBits & Carry) static
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
Definition at line 47 of file KnownBits.cpp.
References assert(), computeForAddCarry(), getBitWidth(), llvm::APInt::getBoolValue(), One, and Zero.
Referenced by computeForAddSub(), llvm::SelectionDAG::computeKnownBits(), and countMaxPopulation().
computeForAddSub()
KnownBits KnownBits::computeForAddSub (bool Add, bool NSW, const KnownBits & LHS, KnownBits RHS) static
Compute known bits resulting from adding LHS and RHS.
Definition at line 54 of file KnownBits.cpp.
References computeForAddCarry(), isNegative(), isNonNegative(), makeNegative(), makeNonNegative(), One, std::swap(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), computeKnownBitsFromOperator(), countMaxPopulation(), and ShrinkDemandedConstant().
countMaxLeadingOnes()
unsigned llvm::KnownBits::countMaxLeadingOnes () const inline
Returns the maximum number of leading one bits possible.
Definition at line 206 of file KnownBits.h.
References llvm::APInt::countLeadingZeros().
countMaxLeadingZeros()
unsigned llvm::KnownBits::countMaxLeadingZeros () const inline
Returns the maximum number of leading zero bits possible.
Definition at line 201 of file KnownBits.h.
References llvm::APInt::countLeadingZeros().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), foldCttzCtlz(), isAlwaysLive(), and isKnownNonZero().
countMaxPopulation()
unsigned llvm::KnownBits::countMaxPopulation () const inline
Returns the maximum number of bits that could be one.
Definition at line 216 of file KnownBits.h.
References llvm::MCID::Add, computeForAddCarry(), computeForAddSub(), llvm::APInt::countPopulation(), and getBitWidth().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), foldCtpop(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), and processUGT_ADDCST_ADD().
countMaxTrailingOnes()
unsigned llvm::KnownBits::countMaxTrailingOnes () const inline
Returns the maximum number of trailing one bits possible.
Definition at line 196 of file KnownBits.h.
References llvm::APInt::countTrailingZeros().
countMaxTrailingZeros()
unsigned llvm::KnownBits::countMaxTrailingZeros () const inline
Returns the maximum number of trailing zero bits possible.
Definition at line 191 of file KnownBits.h.
References llvm::APInt::countTrailingZeros().
Referenced by llvm::SelectionDAG::computeKnownBits(), foldCttzCtlz(), and isAlwaysLive().
countMinLeadingOnes()
unsigned llvm::KnownBits::countMinLeadingOnes () const inline
Returns the minimum number of leading one bits.
Definition at line 176 of file KnownBits.h.
References llvm::APInt::countLeadingOnes().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and countMinSignBits().
countMinLeadingZeros()
unsigned llvm::KnownBits::countMinLeadingZeros () const inline
Returns the minimum number of leading zero bits.
Definition at line 171 of file KnownBits.h.
References llvm::APInt::countLeadingOnes().
Referenced by combineSubToSubus(), combineVectorSignBitsTruncation(), llvm::SelectionDAG::computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), countMinSignBits(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::RegsForValue::getCopyFromRegs(), LowerAndToBT(), LowerTruncateVecI1(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), promotedOpIsNUW(), ShrinkDemandedConstant(), SimplifyAndInst(), and SimplifyLShrInst().
countMinPopulation()
unsigned llvm::KnownBits::countMinPopulation () const inline
Returns the number of bits known to be one.
Definition at line 211 of file KnownBits.h.
References llvm::APInt::countPopulation().
Referenced by foldCtpop(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), and processUGT_ADDCST_ADD().
countMinSignBits()
unsigned llvm::KnownBits::countMinSignBits () const inline
Returns the number of times the sign bit is replicated into the other bits.
Definition at line 182 of file KnownBits.h.
References countMinLeadingOnes(), countMinLeadingZeros(), isNegative(), and isNonNegative().
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), and ComputeNumSignBitsImpl().
countMinTrailingOnes()
unsigned llvm::KnownBits::countMinTrailingOnes () const inline
Returns the minimum number of trailing one bits.
Definition at line 166 of file KnownBits.h.
References llvm::APInt::countTrailingOnes().
Referenced by computeKnownBitsFromOperator().
countMinTrailingZeros()
unsigned llvm::KnownBits::countMinTrailingZeros () const inline
Returns the minimum number of trailing zero bits.
Definition at line 161 of file KnownBits.h.
References llvm::APInt::countTrailingOnes().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), llvm::SelectionDAG::InferPtrAlignment(), isKnownNonZero(), isWordAligned(), llvm::InstCombiner::replacedSelectWithOperand(), and SimplifyShift().
getBitWidth()
unsigned llvm::KnownBits::getBitWidth () const inline
Get the bit width of this value.
Definition at line 39 of file KnownBits.h.
References assert(), and llvm::APInt::getBitWidth().
Referenced by computeForAddCarry(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), computeKnownBitsMul(), computeSignedMinMaxValuesFromKnownBits(), computeUnsignedMinMaxValuesFromKnownBits(), countMaxPopulation(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::ConstantRange::fromKnownBits(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), GetRangeFromMetadata(), isConstant(), llvm::AMDGPUTargetLowering::performTruncateCombine(), ShrinkDemandedConstant(), SimplifyShift(), tryBitfieldInsertOpFromOr(), zext(), and zextOrTrunc().
getConstant()
const APInt& llvm::KnownBits::getConstant () const inline
Returns the value when all bits have a known value.
This just returns One with a protective assertion.
Definition at line 56 of file KnownBits.h.
References assert(), isConstant(), and One.
Referenced by llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ConstantFoldLoadFromConstPtr(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::InstCombiner::run(), llvm::SimplifyInstruction(), and llvm::InstCombiner::visitReturnInst().
getMaxValue()
APInt llvm::KnownBits::getMaxValue () const inline
Return the maximal value possible given these KnownBits.
Definition at line 120 of file KnownBits.h.
Referenced by computeForAddCarry(), computeKnownBitsFromShiftOperator(), llvm::SelectionDAG::computeOverflowKind(), llvm::ConstantRange::fromKnownBits(), GetRangeFromMetadata(), and isSubBorrowChain().
getMinValue()
APInt llvm::KnownBits::getMinValue () const inline
Return the minimal value possible given these KnownBits.
Definition at line 114 of file KnownBits.h.
References One.
Referenced by computeForAddCarry(), llvm::ConstantRange::fromKnownBits(), and GetRangeFromMetadata().
hasConflict()
bool llvm::KnownBits::hasConflict () const inline
Returns true if there is conflicting information.
Definition at line 46 of file KnownBits.h.
References llvm::APInt::intersects().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), llvm::ConstantRange::fromKnownBits(), isAllOnes(), isConstant(), isZero(), ShrinkDemandedConstant(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
isAllOnes()
bool llvm::KnownBits::isAllOnes () const inline
Returns true if value is all one bits.
Definition at line 77 of file KnownBits.h.
References assert(), hasConflict(), and llvm::APInt::isAllOnesValue().
Referenced by computeKnownBitsFromAssume().
isConstant()
bool llvm::KnownBits::isConstant () const inline
Returns true if we know the value of all bits.
Definition at line 49 of file KnownBits.h.
References assert(), llvm::APInt::countPopulation(), getBitWidth(), and hasConflict().
Referenced by llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ConstantFoldLoadFromConstPtr(), getConstant(), llvm::AMDGPUTargetLowering::performTruncateCombine(), llvm::InstCombiner::run(), llvm::SimplifyInstruction(), and llvm::InstCombiner::visitReturnInst().
isNegative()
bool llvm::KnownBits::isNegative () const inline
Returns true if this value is known to be negative.
Definition at line 95 of file KnownBits.h.
References llvm::APInt::isSignBitSet().
Referenced by aliasSameBasePointerGEPs(), computeForAddSub(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::SelectionDAG::ComputeNumSignBits(), computeRecurrenceType(), countMinSignBits(), EvaluateConstantChrecAtConstant(), llvm::ConstantRange::fromKnownBits(), llvm::isKnownNegative(), isKnownNonZero(), simplifyICmpWithBinOp(), and simplifyICmpWithZero().
isNonNegative()
bool llvm::KnownBits::isNonNegative () const inline
Returns true if this value is known to be non-negative.
Definition at line 98 of file KnownBits.h.
References llvm::APInt::isSignBitSet().
Referenced by aliasSameBasePointerGEPs(), canReplaceGEPIdxWithZero(), computeForAddSub(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), llvm::computeOverflowForSignedMul(), computeRecurrenceType(), countMinSignBits(), EvaluateConstantChrecAtConstant(), llvm::ConstantRange::fromKnownBits(), llvm::isKnownNonNegative(), isKnownNonZero(), ShrinkDemandedConstant(), simplifyICmpWithBinOp(), simplifyICmpWithZero(), llvm::InstCombiner::simplifyRangeCheck(), and llvm::InstCombiner::visitSExt().
isStrictlyPositive()
bool llvm::KnownBits::isStrictlyPositive () const inline
Returns true if this value is known to be positive.
Definition at line 101 of file KnownBits.h.
References llvm::APInt::isNullValue(), and llvm::APInt::isSignBitSet().
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
isUnknown()
bool llvm::KnownBits::isUnknown () const inline
Returns true if we don't know any bits.
Definition at line 62 of file KnownBits.h.
References llvm::APInt::isNullValue().
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::ConstantRange::fromKnownBits().
isZero()
bool llvm::KnownBits::isZero () const inline
Returns true if value is all zero.
Definition at line 71 of file KnownBits.h.
References assert(), hasConflict(), and llvm::APInt::isAllOnesValue().
Referenced by computeKnownBitsFromAssume(), isZero(), and llvm::InstCombiner::replacedSelectWithOperand().
makeNegative()
void llvm::KnownBits::makeNegative () inline
Make this value negative.
Definition at line 104 of file KnownBits.h.
References llvm::APInt::setSignBit().
Referenced by computeForAddSub(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), and computeKnownBitsMul().
makeNonNegative()
void llvm::KnownBits::makeNonNegative () inline
Make this value non-negative.
Definition at line 109 of file KnownBits.h.
References llvm::APInt::setSignBit().
Referenced by computeForAddSub(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsMul(), and ShrinkDemandedConstant().
resetAll()
void llvm::KnownBits::resetAll () inline
Resets the known state of all bits.
Definition at line 65 of file KnownBits.h.
References llvm::APInt::clearAllBits().
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::TargetLowering::computeKnownBitsForTargetInstr(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), and ShrinkDemandedConstant().
setAllOnes()
void llvm::KnownBits::setAllOnes () inline
Make all bits known to be one and discard any previous information.
Definition at line 89 of file KnownBits.h.
References llvm::APInt::clearAllBits(), and llvm::APInt::setAllBits().
Referenced by computeKnownBitsFromAssume().
setAllZero()
void llvm::KnownBits::setAllZero () inline
Make all bits known to be zero and discard any previous information.
Definition at line 83 of file KnownBits.h.
References llvm::APInt::clearAllBits(), and llvm::APInt::setAllBits().
Referenced by computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), and computeKnownBitsFromShiftOperator().
sext()
KnownBits llvm::KnownBits::sext (unsigned BitWidth) const inline
Sign extends the underlying known Zero and One bits.
This is equivalent to sign extending the value we're tracking.
Definition at line 145 of file KnownBits.h.
References KnownBits(), and llvm::APInt::sext().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and ShrinkDemandedConstant().
trunc()
KnownBits llvm::KnownBits::trunc (unsigned BitWidth) const inline
Truncate the underlying known Zero and One bits.
This is equivalent to truncating the value we're tracking.
Definition at line 127 of file KnownBits.h.
References KnownBits(), and llvm::APInt::trunc().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
zext()
KnownBits llvm::KnownBits::zext (unsigned BitWidth, bool ExtendedBitsAreKnownZero) const inline
Extends the underlying known Zero and One bits.
By setting ExtendedBitsAreKnownZero=true this will be equivalent to zero extending the value we're tracking. With ExtendedBitsAreKnownZero=false the extended bits are set to unknown.
Definition at line 135 of file KnownBits.h.
References getBitWidth(), KnownBits(), llvm::APInt::setBitsFrom(), and llvm::APInt::zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and zextOrTrunc().
zextOrTrunc()
KnownBits llvm::KnownBits::zextOrTrunc (unsigned BitWidth, bool ExtendedBitsAreKnownZero) const inline
Extends or truncates the underlying known Zero and One bits.
When extending the extended bits can either be set as known zero (if ExtendedBitsAreKnownZero=true) or as unknown (if ExtendedBitsAreKnownZero=false).
Definition at line 153 of file KnownBits.h.
References getBitWidth(), KnownBits(), zext(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), GetRangeFromMetadata(), ShrinkDemandedConstant(), and llvm::TargetLowering::SimplifyDemandedBits().
Member Data Documentation
One
APInt llvm::KnownBits::One
Definition at line 24 of file KnownBits.h.
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), aliasSameBasePointerGEPs(), llvm::SelectionDAGISel::CheckOrMask(), combineShiftOfShiftedLogic(), computeForAddCarry(), computeForAddCarry(), computeForAddSub(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsBinOp(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computeSignedMinMaxValuesFromKnownBits(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::ConstantFoldLoadFromConstPtr(), foldCttzCtlz(), generateEquivalentSub(), getConstant(), getFauxShuffleMask(), llvm::GISelKnownBits::getKnownOnes(), getMinValue(), isAlwaysLive(), isKnownNonEqual(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), isOpcWithIntImmediate(), maskMatters(), processUGT_ADDCST_ADD(), llvm::InstCombiner::replacedSelectWithOperand(), ShrinkDemandedConstant(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), SimplifyRightShift(), SimplifyShift(), and llvm::InstCombiner::visitTrunc().
Zero
APInt llvm::KnownBits::Zero
Definition at line 23 of file KnownBits.h.
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), adjustForRedundantAnd(), aliasSameBasePointerGEPs(), annotateNonNullAndDereferenceable(), combineShiftOfShiftedLogic(), computeForAddCarry(), computeForAddCarry(), computeForAddSub(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsBinOp(), llvm::GISelKnownBits::computeKnownBitsForAlignment(), llvm::SITargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), llvm::SelectionDAG::computeOverflowKind(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computeSignedMinMaxValuesFromKnownBits(), computeUnsignedMinMaxValuesFromKnownBits(), llvm::ConstantFoldLoadFromConstPtr(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), generateEquivalentSub(), getFauxShuffleMask(), llvm::GISelKnownBits::getKnownZeroes(), getRangeForAffineARHelper(), llvm::SelectionDAG::haveNoCommonBitsSet(), insertDAGNode(), isAlwaysLive(), isBitfieldPositioningOp(), isKnownNonEqual(), isKnownToBeAPowerOfTwo(), isOpcWithIntImmediate(), isSupportedGuardInstruction(), isTruePredicate(), isTruncateOf(), LowerMUL(), MaskedValueIsZero(), maskMatters(), matchRotateSub(), mayUseP9Setb(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), processUGT_ADDCST_ADD(), propagateMetadata(), llvm::InstCombiner::replacedSelectWithOperand(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegReg(), ShrinkDemandedConstant(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitZExt(), and widenCtPop().
The documentation for this struct was generated from the following files:
include/llvm/Support/KnownBits.h
lib/Support/KnownBits.cpp