LLVM: llvm::IntrusiveBackListNode Struct Reference
llvm::IntrusiveBackListNode Struct Reference
#include "llvm/CodeGen/DIE.h"
Public Member Functions
IntrusiveBackListNode ()
IntrusiveBackListNode * getNext () const
Public Attributes
PointerIntPair< IntrusiveBackListNode *, 1 > Next
Detailed Description
Definition at line 497 of file DIE.h.
Constructor & Destructor Documentation
IntrusiveBackListNode()
llvm::IntrusiveBackListNode::IntrusiveBackListNode () inline
Definition at line 500 of file DIE.h.
Member Function Documentation
getNext()
IntrusiveBackListNode* llvm::IntrusiveBackListNode::getNext () const inline
Definition at line 502 of file DIE.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by llvm::IntrusiveBackList< T >::iterator::operator++(), and llvm::IntrusiveBackList< T >::const_iterator::operator++().
Member Data Documentation
Next
PointerIntPair<IntrusiveBackListNode *, 1> llvm::IntrusiveBackListNode::Next
Definition at line 498 of file DIE.h.
Referenced by llvm::IntrusiveBackListBase::push_back(), and llvm::IntrusiveBackListBase::push_front().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/DIE.h