LLVM: llvm::safestack::StackColoring::LiveRange Struct Reference
llvm::safestack::StackColoring::LiveRange Struct Reference
This class represents a set of interesting instructions where an alloca is live.
#include "CodeGen/SafeStackColoring.h"
Public Member Functions
void SetMaximum (int size)
void AddRange (unsigned start, unsigned end)
bool Overlaps (const LiveRange &Other) const
void Join (const LiveRange &Other)
Public Attributes
BitVector bv
Detailed Description
This class represents a set of interesting instructions where an alloca is live.
Definition at line 58 of file SafeStackColoring.h.
Member Function Documentation
AddRange()
void llvm::safestack::StackColoring::LiveRange::AddRange (unsigned start, unsigned end) inline
Definition at line 62 of file SafeStackColoring.h.
References llvm::BitVector::set().
Referenced by llvm::safestack::StackColoring::getFullLiveRange().
Join()
void llvm::safestack::StackColoring::LiveRange::Join (const LiveRange & Other) inline
Definition at line 68 of file SafeStackColoring.h.
References bv, F, and I.
Overlaps()
bool llvm::safestack::StackColoring::LiveRange::Overlaps (const LiveRange & Other) const inline
Definition at line 64 of file SafeStackColoring.h.
References llvm::BitVector::anyCommon(), and bv.
SetMaximum()
void llvm::safestack::StackColoring::LiveRange::SetMaximum (int size) inline
Definition at line 61 of file SafeStackColoring.h.
References llvm::BitVector::resize().
Referenced by llvm::safestack::StackColoring::getFullLiveRange().
Member Data Documentation
bv
BitVector llvm::safestack::StackColoring::LiveRange::bv
Definition at line 59 of file SafeStackColoring.h.
Referenced by Join(), llvm::safestack::operator<<(), and Overlaps().
The documentation for this struct was generated from the following file:
lib/CodeGen/SafeStackColoring.h