LLVM: llvm::DenseMapInfo< DivRemMapKey > Struct Template Reference
llvm::DenseMapInfo< DivRemMapKey > Struct Template Reference
#include "llvm/Transforms/Utils/BypassSlowDivision.h"
Static Public Member Functions
static bool isEqual (const DivRemMapKey &Val1, const DivRemMapKey &Val2)
static DivRemMapKey getEmptyKey ()
static DivRemMapKey getTombstoneKey ()
static unsigned getHashValue (const DivRemMapKey &Val)
Detailed Description
template<>
struct llvm::DenseMapInfo< DivRemMapKey >
Definition at line 41 of file BypassSlowDivision.h.
Member Function Documentation
getEmptyKey()
static DivRemMapKey llvm::DenseMapInfo< DivRemMapKey >::getEmptyKey () inline static
Definition at line 47 of file BypassSlowDivision.h.
References llvm::DivRemMapKey::DivRemMapKey().
getHashValue()
static unsigned llvm::DenseMapInfo< DivRemMapKey >::getHashValue (const DivRemMapKey & Val) inline static
Definition at line 55 of file BypassSlowDivision.h.
References llvm::bypassSlowDivision(), llvm::DivRemMapKey::Dividend, llvm::DivRemMapKey::Divisor, and llvm::DivRemMapKey::SignedOp.
getTombstoneKey()
static DivRemMapKey llvm::DenseMapInfo< DivRemMapKey >::getTombstoneKey () inline static
Definition at line 51 of file BypassSlowDivision.h.
References llvm::DivRemMapKey::DivRemMapKey().
isEqual()
static bool llvm::DenseMapInfo< DivRemMapKey >::isEqual (const DivRemMapKey & Val1, const DivRemMapKey & Val2) inline static
Definition at line 42 of file BypassSlowDivision.h.
References llvm::DivRemMapKey::Dividend, llvm::DivRemMapKey::Divisor, and llvm::DivRemMapKey::SignedOp.
The documentation for this struct was generated from the following file:
include/llvm/Transforms/Utils/BypassSlowDivision.h