LLVM: llvm::SparcRegisterInfo Struct Reference
llvm::SparcRegisterInfo Struct Reference
#include "Target/Sparc/SparcRegisterInfo.h"
Public Member Functions
SparcRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
const uint32_t * getRTCallPreservedMask (CallingConv::ID CC) const
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
bool canRealignStack (const MachineFunction &MF) const override
Detailed Description
Definition at line 22 of file SparcRegisterInfo.h.
Constructor & Destructor Documentation
SparcRegisterInfo()
SparcRegisterInfo::SparcRegisterInfo ()
Definition at line 36 of file SparcRegisterInfo.cpp.
Member Function Documentation
canRealignStack()
bool SparcRegisterInfo::canRealignStack (const MachineFunction & MF) const override
Definition at line 223 of file SparcRegisterInfo.cpp.
References llvm::TargetRegisterInfo::canRealignStack().
eliminateFrameIndex()
void SparcRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 164 of file SparcRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::SparcSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::SparcSubtarget::hasHardQuad(), llvm::SparcSubtarget::isV9(), MI, replaceFI(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), and TII.
getCalleeSavedRegs()
const MCPhysReg * SparcRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 39 of file SparcRegisterInfo.cpp.
getCallPreservedMask()
const uint32_t * SparcRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 44 of file SparcRegisterInfo.cpp.
Referenced by llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::SparcTargetLowering::LowerGlobalTLSAddress().
getFrameRegister()
Register SparcRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 215 of file SparcRegisterInfo.cpp.
Referenced by llvm::SparcFrameLowering::getFrameIndexReference().
getPointerRegClass()
const TargetRegisterClass * SparcRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind) const override
Definition at line 105 of file SparcRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), and llvm::SparcSubtarget::is64Bit().
getReservedRegs()
BitVector SparcRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 54 of file SparcRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::SparcSubtarget::is64Bit(), llvm::SparcSubtarget::isV9(), llvm::MCRegAliasIterator::isValid(), ReserveAppRegisters, and llvm::BitVector::set().
getRTCallPreservedMask()
const uint32_t * SparcRegisterInfo::getRTCallPreservedMask (CallingConv::ID CC) const
Definition at line 50 of file SparcRegisterInfo.cpp.
Referenced by llvm::SparcTargetLowering::LowerCall_32(), and llvm::SparcTargetLowering::LowerCall_64().
The documentation for this struct was generated from the following files:
lib/Target/Sparc/SparcRegisterInfo.h
lib/Target/Sparc/SparcRegisterInfo.cpp