LLVM: lib/Transforms/Scalar/StructurizeCFG.cpp File Reference
StructurizeCFG.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/Analysis/RegionPass.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include <algorithm>
#include <cassert>
#include <utility>
Macros
#define DEBUG_TYPE "structurizecfg"
Functions
INITIALIZE_PASS_BEGIN (StructurizeCFG, "structurizecfg", "Structurize the CFG", false, false) INITIALIZE_PASS_END(StructurizeCFG
static bool hasOnlyUniformBranches (Region *R, unsigned UniformMDKindID, const LegacyDivergenceAnalysis &DA)
Variables
static const char *const FlowBlockName = "Flow"
structurizecfg
Structurize the CFG
Structurize the false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "structurizecfg"
Definition at line 54 of file StructurizeCFG.cpp.
Function Documentation
hasOnlyUniformBranches()
static bool hasOnlyUniformBranches (Region * R, unsigned UniformMDKindID, const LegacyDivergenceAnalysis & DA) static
Definition at line 941 of file StructurizeCFG.cpp.
References llvm::RegionBase< Tr >::blocks(), llvm::dbgs(), llvm::dyn_cast(), E, llvm::RegionBase< Tr >::elements(), llvm::MDNode::get(), llvm::RegionBase< Tr >::getEntry(), llvm::BasicBlock::getTerminator(), llvm::RegionBase< Tr >::isTopLevelRegion(), llvm::LegacyDivergenceAnalysis::isUniform(), LLVM_DEBUG, and llvm::Instruction::setMetadata().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (StructurizeCFG , "structurizecfg" , "Structurize the CFG" , false , false)
Variable Documentation
CFG
Structurize the CFG
Definition at line 299 of file StructurizeCFG.cpp.
false
Structurize the false
Definition at line 299 of file StructurizeCFG.cpp.
FlowBlockName
const char* const FlowBlockName = "Flow" static
Definition at line 57 of file StructurizeCFG.cpp.
structurizecfg
structurizecfg
Definition at line 299 of file StructurizeCFG.cpp.