LLVM: llvm::codeview::LocallyHashedType Struct Reference
llvm::codeview::LocallyHashedType Struct Reference
A locally hashed type represents a straightforward hash code of a serialized record.
#include "llvm/DebugInfo/CodeView/TypeHashing.h"
Static Public Member Functions
static LocallyHashedType hashType (ArrayRef< uint8_t > RecordData)
Given a type, compute its local hash.
template<typename Range >
static std::vector< LocallyHashedType > hashTypes (Range &&Records)
Given a sequence of types, compute all of the local hashes.
static std::vector< LocallyHashedType > hashTypeCollection (TypeCollection &Types)
Public Attributes
hash_code Hash
ArrayRef< uint8_t > RecordData
Detailed Description
A locally hashed type represents a straightforward hash code of a serialized record.
The record is simply serialized, and then the bytes are hashed by a standard algorithm. This is sufficient for the case of de-duplicating records within a single sequence of types, because if two records both have a back-reference to the same type in the same stream, they will both have the same numeric value for the TypeIndex of the back reference.
Definition at line 32 of file TypeHashing.h.
Member Function Documentation
hashType()
LocallyHashedType LocallyHashedType::hashType (ArrayRef< uint8_t > RecordData) static
Given a type, compute its local hash.
Definition at line 28 of file TypeHashing.cpp.
References llvm::hash_value().
Referenced by llvm::codeview::GloballyHashedType::empty(), llvm::codeview::GloballyHashedType::hashIds(), llvm::codeview::GloballyHashedType::hashType(), hashTypeCollection(), llvm::codeview::GloballyHashedType::hashTypeCollection(), hashTypes(), and llvm::codeview::GloballyHashedType::hashTypes().
hashTypeCollection()
static std::vector<LocallyHashedType> llvm::codeview::LocallyHashedType::hashTypeCollection (TypeCollection & Types) inline static
Definition at line 51 of file TypeHashing.h.
References llvm::codeview::TypeCollection::ForEachRecord(), hashType(), and llvm::codeview::CVRecord< Kind >::RecordData.
hashTypes()
template<typename Range > static std::vector<LocallyHashedType> llvm::codeview::LocallyHashedType::hashTypes (Range && Records) inline static
Given a sequence of types, compute all of the local hashes.
Definition at line 41 of file TypeHashing.h.
References llvm::sys::path::begin(), llvm::sys::path::end(), and hashType().
Member Data Documentation
Hash
hash_code llvm::codeview::LocallyHashedType::Hash
Definition at line 33 of file TypeHashing.h.
Referenced by llvm::format_provider< codeview::LocallyHashedType >::format(), llvm::DenseMapInfo< codeview::LocallyHashedType >::getHashValue(), llvm::codeview::GloballyHashedType::GloballyHashedType(), and llvm::DenseMapInfo< codeview::LocallyHashedType >::isEqual().
RecordData
ArrayRef<uint8_t> llvm::codeview::LocallyHashedType::RecordData
Definition at line 34 of file TypeHashing.h.
Referenced by llvm::codeview::GloballyHashedType::empty(), and llvm::DenseMapInfo< codeview::LocallyHashedType >::isEqual().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/CodeView/TypeHashing.h
lib/DebugInfo/CodeView/TypeHashing.cpp