LLVM: llvm::AlignedCharArrayUnion< T, Ts > Struct Template Reference
llvm::AlignedCharArrayUnion< T, Ts > Struct Template Reference
A suitably aligned and sized character array member which can hold elements of any type.
#include "llvm/Support/AlignOf.h"
Public Attributes
char buffer [sizeof(llvm::detail::SizerImpl< T, Ts... >)]
Detailed Description
template<typename T, typename... Ts>
struct llvm::AlignedCharArrayUnion< T, Ts >
A suitably aligned and sized character array member which can hold elements of any type.
These types may be arrays, structs, or any other types. This exposes a buffer member which can be used as suitable storage for a placement new of any of these types.
Definition at line 48 of file AlignOf.h.
Member Data Documentation
buffer
template<typename T, typename... Ts> char llvm::AlignedCharArrayUnion< T, Ts >::buffer[sizeof(llvm::detail::SizerImpl< T, Ts... >)]
Definition at line 50 of file AlignOf.h.
Referenced by llvm::SmallDenseMap< unsigned, unsigned, N >::grow(), llvm::IntervalMap< SlotIndex, unsigned >::IntervalMap(), llvm::ErrorOr< T >::operator*(), and llvm::SmallDenseMap< unsigned, unsigned, N >::shrink_and_clear().
The documentation for this struct was generated from the following file:
include/llvm/Support/AlignOf.h