LLVM: llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata Struct Reference
llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata Struct Reference final
In-memory representation of kernel debug properties metadata.
#include "llvm/Support/AMDGPUMetadata.h"
Public Member Functions
Metadata ()=default
Default constructor.
bool empty () const
bool notEmpty () const
Public Attributes
std::vector< uint32_t > mDebuggerABIVersion = std::vector<uint32_t>()
Debugger ABI version. Optional.
uint16_t mReservedNumVGPRs = 0
Consecutive number of VGPRs reserved for debugger use.
uint16_t mReservedFirstVGPR = uint16_t(-1)
First fixed VGPR reserved.
uint16_t mPrivateSegmentBufferSGPR = uint16_t(-1)
Fixed SGPR of the first of 4 SGPRs used to hold the scratch V# used for the entire kernel execution.
uint16_t mWavefrontPrivateSegmentOffsetSGPR = uint16_t(-1)
Fixed SGPR used to hold the wave scratch offset for the entire kernel execution.
Detailed Description
In-memory representation of kernel debug properties metadata.
Definition at line 331 of file AMDGPUMetadata.h.
Constructor & Destructor Documentation
Metadata()
llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::Metadata () default
Default constructor.
Member Function Documentation
empty()
bool llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::empty () const inline
Returns
True if kernel debug properties metadata is empty, false otherwise.
Definition at line 354 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
notEmpty()
bool llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::notEmpty () const inline
Returns
True if kernel debug properties metadata is not empty, false otherwise.
Definition at line 360 of file AMDGPUMetadata.h.
Member Data Documentation
mDebuggerABIVersion
std::vector<uint32_t> llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::mDebuggerABIVersion = std::vector<uint32_t>()
Debugger ABI version. Optional.
Definition at line 333 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping().
mPrivateSegmentBufferSGPR
uint16_t llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::mPrivateSegmentBufferSGPR = uint16_t(-1)
Fixed SGPR of the first of 4 SGPRs used to hold the scratch V# used for the entire kernel execution.
Must be uint16_t(-1) if mDebuggerABIVersion is not set or SGPR not used or not known. Optional.
Definition at line 343 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping().
mReservedFirstVGPR
uint16_t llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::mReservedFirstVGPR = uint16_t(-1)
First fixed VGPR reserved.
Must be uint16_t(-1) if mDebuggerABIVersion is not set or mReservedFirstVGPR is 0. Optional.
Definition at line 339 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping().
mReservedNumVGPRs
uint16_t llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::mReservedNumVGPRs = 0
Consecutive number of VGPRs reserved for debugger use.
Must be 0 if mDebuggerABIVersion is not set. Optional.
Definition at line 336 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping().
mWavefrontPrivateSegmentOffsetSGPR
uint16_t llvm::AMDGPU::HSAMD::Kernel::DebugProps::Metadata::mWavefrontPrivateSegmentOffsetSGPR = uint16_t(-1)
Fixed SGPR used to hold the wave scratch offset for the entire kernel execution.
Must be uint16_t(-1) if mDebuggerABIVersion is not set or SGPR is not used or not known. Optional.
Definition at line 347 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::DebugProps::Metadata >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/Support/AMDGPUMetadata.h