LLVM: llvm::slpvectorizer::BoUpSLP::BlockScheduling::ReadyList Struct Reference
llvm::slpvectorizer::BoUpSLP::BlockScheduling::ReadyList Struct Reference
Public Member Functions
void insert (ScheduleData *SD)
Public Member Functions inherited from llvm::SmallVector< ScheduleData *, 8 >
SmallVector ()
SmallVector (size_t Size, const ScheduleData * &Value=ScheduleData *())
SmallVector (ItTy S, ItTy E)
SmallVector (const iterator_range< RangeTy > &R)
SmallVector (std::initializer_list< ScheduleData * > IL)
SmallVector (const SmallVector &RHS)
SmallVector (SmallVector &&RHS)
SmallVector (SmallVectorImpl< ScheduleData * > &&RHS)
~SmallVector ()
const SmallVector & operator= (const SmallVector &RHS)
const SmallVector & operator= (SmallVector &&RHS)
const SmallVector & operator= (SmallVectorImpl< ScheduleData * > &&RHS)
const SmallVector & operator= (std::initializer_list< ScheduleData * > IL)
Public Member Functions inherited from llvm::SmallVectorImpl< ScheduleData * >
SmallVectorImpl (const SmallVectorImpl &)=delete
~SmallVectorImpl ()
void clear ()
void resize (size_type N)
void resize (size_type N, const ScheduleData * &NV)
void reserve (size_type N)
LLVM_NODISCARD ScheduleData * pop_back_val ()
void swap (SmallVectorImpl &RHS)
void append (in_iter in_start, in_iter in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, const ScheduleData * &Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< ScheduleData * > IL)
void assign (size_type NumElts, const ScheduleData * &Elt)
void assign (in_iter in_start, in_iter in_end)
void assign (std::initializer_list< ScheduleData * > IL)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, ScheduleData * &&Elt)
iterator insert (iterator I, const ScheduleData * &Elt)
iterator insert (iterator I, size_type NumToInsert, const ScheduleData * &Elt)
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< ScheduleData * > IL)
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase
size_t size () const
size_t capacity () const
LLVM_NODISCARD bool empty () const
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
Additional Inherited Members
Public Types inherited from llvm::SmallVectorImpl< ScheduleData * >
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Member Functions inherited from llvm::SmallVectorImpl< ScheduleData * >
SmallVectorImpl (unsigned N)
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinCapacity, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
Protected Member Functions inherited from llvm::SmallVectorBase
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void grow_pod (void *FirstEl, size_t MinCapacity, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Protected Attributes inherited from llvm::SmallVectorBase
void * BeginX
unsigned Size = 0
unsigned Capacity
Detailed Description
Definition at line 2126 of file SLPVectorizer.cpp.
Member Function Documentation
insert()
void llvm::slpvectorizer::BoUpSLP::BlockScheduling::ReadyList::insert (ScheduleData * SD) inline
Definition at line 2127 of file SLPVectorizer.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), F(), llvm::hash_combine_range(), llvm::isEqual(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and ScheduleRegionSizeBudget.
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp