LLVM: llvm::MCAsmMacro Struct Reference
llvm::MCAsmMacro Struct Reference
#include "llvm/MC/MCAsmMacro.h"
Public Member Functions
MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P)
void dump () const
LLVM_DUMP_METHOD void dump (raw_ostream &OS) const
Public Attributes
StringRef Name
StringRef Body
MCAsmMacroParameters Parameters
Detailed Description
Definition at line 142 of file MCAsmMacro.h.
Constructor & Destructor Documentation
MCAsmMacro()
llvm::MCAsmMacro::MCAsmMacro (StringRef N, StringRef B, MCAsmMacroParameters P) inline
Definition at line 148 of file MCAsmMacro.h.
Member Function Documentation
dump() [1/2]
void llvm::MCAsmMacro::dump () const inline
Definition at line 152 of file MCAsmMacro.h.
References llvm::dbgs(), llvm::AsmToken::dump(), dump(), and LLVM_DUMP_METHOD.
Referenced by dump(), and isValidEncoding().
dump() [2/2]
void MCAsmMacro::dump (raw_ostream & OS) const
Definition at line 34 of file MCAsmMacro.cpp.
References llvm::MCAsmMacroParameter::Name, and P.
Member Data Documentation
Body
StringRef llvm::MCAsmMacro::Body
Definition at line 144 of file MCAsmMacro.h.
Referenced by isOperator().
Name
StringRef llvm::MCAsmMacro::Name
Definition at line 143 of file MCAsmMacro.h.
Referenced by isOperator().
Parameters
MCAsmMacroParameters llvm::MCAsmMacro::Parameters
Definition at line 145 of file MCAsmMacro.h.
Referenced by isOperator().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCAsmMacro.h
lib/MC/MCAsmMacro.cpp