LLVM: llvm::DenseMapInfo< const Expression * > Struct Template Reference
llvm::DenseMapInfo< const Expression * > Struct Template Reference
Static Public Member Functions
static const Expression * getEmptyKey ()
static const Expression * getTombstoneKey ()
static unsigned getHashValue (const Expression *E)
static unsigned getHashValue (const ExactEqualsExpression &E)
static bool isEqual (const ExactEqualsExpression &LHS, const Expression *RHS)
static bool isEqual (const Expression *LHS, const Expression *RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< const Expression * >
Definition at line 444 of file NewGVN.cpp.
Member Function Documentation
getEmptyKey()
static const Expression* llvm::DenseMapInfo< const Expression * >::getEmptyKey () inline static
Definition at line 445 of file NewGVN.cpp.
getHashValue() [1/2]
static unsigned llvm::DenseMapInfo< const Expression * >::getHashValue (const Expression * E) inline static
Definition at line 457 of file NewGVN.cpp.
References llvm::GVNExpression::Expression::getComputedHash().
getHashValue() [2/2]
static unsigned llvm::DenseMapInfo< const Expression * >::getHashValue (const ExactEqualsExpression & E) inline static
Definition at line 461 of file NewGVN.cpp.
References llvm::ExactEqualsExpression::getComputedHash().
getTombstoneKey()
static const Expression* llvm::DenseMapInfo< const Expression * >::getTombstoneKey () inline static
Definition at line 451 of file NewGVN.cpp.
isEqual() [1/2]
static bool llvm::DenseMapInfo< const Expression * >::isEqual (const ExactEqualsExpression & LHS, const Expression * RHS) inline static
Definition at line 465 of file NewGVN.cpp.
isEqual() [2/2]
static bool llvm::DenseMapInfo< const Expression * >::isEqual (const Expression * LHS, const Expression * RHS) inline static
Definition at line 471 of file NewGVN.cpp.
References assert(), E, F(), From, llvm::GVNExpression::Expression::getComputedHash(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/NewGVN.cpp