LLVM: llvm::yaml::MappingTraits< T >::NormalizedTBD_V4 Struct Reference
llvm::yaml::MappingTraits< T >::NormalizedTBD_V4 Struct Reference
Public Member Functions
NormalizedTBD_V4 (IO &IO)
NormalizedTBD_V4 (IO &IO, const InterfaceFile *&File)
const InterfaceFile * denormalize (IO &IO)
Public Attributes
unsigned TBDVersion
std::vector< UUIDv4 > UUIDs
TargetList Targets
StringRef InstallName
PackedVersion CurrentVersion
PackedVersion CompatibilityVersion
SwiftVersion SwiftABIVersion {0}
std::vector< MetadataSection > AllowableClients
std::vector< MetadataSection > ReexportedLibraries
TBDFlags Flags {TBDFlags::None}
std::vector< UmbrellaSection > ParentUmbrellas
SectionList Exports
SectionList Reexports
SectionList Undefineds
Detailed Description
template<typename T>
struct llvm::yaml::MappingTraits< T >::NormalizedTBD_V4
Definition at line 802 of file TextStub.cpp.
Constructor & Destructor Documentation
NormalizedTBD_V4() [1/2]
template<typename T > llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::NormalizedTBD_V4 (IO & IO) inline explicit
Definition at line 803 of file TextStub.cpp.
NormalizedTBD_V4() [2/2]
template<typename T > llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::NormalizedTBD_V4 (IO & IO, const InterfaceFile *& File) inline
Definition at line 804 of file TextStub.cpp.
References llvm::MachO::InterfaceFile::allowableClients(), assert(), llvm::iterator_range< IteratorT >::begin(), llvm::coverage::CurrentVersion, llvm::iterator_range< IteratorT >::end(), llvm::MachO::InterfaceFile::exports(), llvm::MachO::InterfaceFile::getCompatibilityVersion(), llvm::MachO::InterfaceFile::getCurrentVersion(), llvm::MachO::InterfaceFile::getInstallName(), llvm::MachO::Symbol::getKind(), llvm::MachO::Symbol::getName(), llvm::MachO::InterfaceFile::getSwiftABIVersion(), llvm::MachO::InterfaceFile::isApplicationExtensionSafe(), llvm::MachO::InterfaceFile::isInstallAPI(), llvm::MachO::Symbol::isReexported(), llvm::MachO::Symbol::isThreadLocalValue(), llvm::MachO::InterfaceFile::isTwoLevelNamespace(), llvm::MachO::Symbol::isWeakDefined(), IT, llvm::None, llvm::MachO::InterfaceFile::reexportedLibraries(), llvm::sort(), llvm::ARMBuildAttrs::Symbol, llvm::MachO::Symbol::targets(), llvm::MachO::InterfaceFile::targets(), llvm::MachO::InterfaceFile::umbrellas(), llvm::MachO::InterfaceFile::undefineds(), and llvm::MachO::InterfaceFile::uuids().
Member Function Documentation
denormalize()
template<typename T > const InterfaceFile* llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::denormalize (IO & IO) inline
Definition at line 907 of file TextStub.cpp.
References assert(), llvm::coverage::CurrentVersion, File, and llvm::None.
Member Data Documentation
AllowableClients
template<typename T > std::vector<MetadataSection> llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::AllowableClients
Definition at line 984 of file TextStub.cpp.
CompatibilityVersion
template<typename T > PackedVersion llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::CompatibilityVersion
Definition at line 982 of file TextStub.cpp.
CurrentVersion
template<typename T > PackedVersion llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::CurrentVersion
Definition at line 981 of file TextStub.cpp.
Exports
template<typename T > SectionList llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::Exports
Definition at line 988 of file TextStub.cpp.
Flags
template<typename T > TBDFlags llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::Flags {TBDFlags::None}
Definition at line 986 of file TextStub.cpp.
InstallName
template<typename T > StringRef llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::InstallName
Definition at line 980 of file TextStub.cpp.
ParentUmbrellas
template<typename T > std::vector<UmbrellaSection> llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::ParentUmbrellas
Definition at line 987 of file TextStub.cpp.
ReexportedLibraries
template<typename T > std::vector<MetadataSection> llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::ReexportedLibraries
Definition at line 985 of file TextStub.cpp.
Reexports
template<typename T > SectionList llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::Reexports
Definition at line 989 of file TextStub.cpp.
SwiftABIVersion
template<typename T > SwiftVersion llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::SwiftABIVersion {0}
Definition at line 983 of file TextStub.cpp.
Targets
template<typename T > TargetList llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::Targets
Definition at line 979 of file TextStub.cpp.
TBDVersion
template<typename T > unsigned llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::TBDVersion
Definition at line 977 of file TextStub.cpp.
Undefineds
template<typename T > SectionList llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::Undefineds
Definition at line 990 of file TextStub.cpp.
UUIDs
template<typename T > std::vector<UUIDv4> llvm::yaml::MappingTraits< T >::NormalizedTBD_V4::UUIDs
Definition at line 978 of file TextStub.cpp.
The documentation for this struct was generated from the following file:
lib/TextAPI/MachO/TextStub.cpp