LLVM: llvm::yaml::MappingTraits< T >::NormalizedTBD Struct Reference
llvm::yaml::MappingTraits< T >::NormalizedTBD Struct Reference
Public Member Functions
NormalizedTBD (IO &IO)
NormalizedTBD (IO &IO, const InterfaceFile *&File)
TargetList synthesizeTargets (ArchitectureSet Architectures, const PlatformSet &Platforms)
const InterfaceFile * denormalize (IO &IO)
StringRef copyString (StringRef String)
Public Attributes
llvm::BumpPtrAllocator Allocator
std::vector< Architecture > Architectures
std::vector< UUID > UUIDs
PlatformSet Platforms
StringRef InstallName
PackedVersion CurrentVersion
PackedVersion CompatibilityVersion
SwiftVersion SwiftABIVersion {0}
ObjCConstraintType ObjCConstraint {ObjCConstraintType::None}
TBDFlags Flags {TBDFlags::None}
StringRef ParentUmbrella
std::vector< ExportSection > Exports
std::vector< UndefinedSection > Undefineds
Detailed Description
template<typename T>
struct llvm::yaml::MappingTraits< T >::NormalizedTBD
Definition at line 431 of file TextStub.cpp.
Constructor & Destructor Documentation
NormalizedTBD() [1/2]
template<typename T > llvm::yaml::MappingTraits< T >::NormalizedTBD::NormalizedTBD (IO & IO) inline explicit
Definition at line 432 of file TextStub.cpp.
NormalizedTBD() [2/2]
template<typename T > llvm::yaml::MappingTraits< T >::NormalizedTBD::NormalizedTBD (IO & IO, const InterfaceFile *& File) inline
Definition at line 433 of file TextStub.cpp.
References llvm::coverage::CurrentVersion, llvm::MachO::InterfaceFile::getArchitectures(), llvm::MachO::InterfaceFile::getCompatibilityVersion(), llvm::MachO::InterfaceFile::getCurrentVersion(), llvm::MachO::InterfaceFile::getInstallName(), llvm::MachO::InterfaceFile::getObjCConstraint(), llvm::MachO::InterfaceFile::getPlatforms(), llvm::MachO::InterfaceFile::getSwiftABIVersion(), llvm::MachO::InterfaceFile::isApplicationExtensionSafe(), llvm::MachO::InterfaceFile::isInstallAPI(), llvm::MachO::InterfaceFile::isTwoLevelNamespace(), llvm::None, llvm::MachO::InterfaceFile::umbrellas(), and llvm::MachO::InterfaceFile::uuids().
Member Function Documentation
copyString()
template<typename T > StringRef llvm::yaml::MappingTraits< T >::NormalizedTBD::copyString (StringRef String) inline
Definition at line 722 of file TextStub.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold >::Allocate(), llvm::StringRef::data(), llvm::StringRef::empty(), and llvm::StringRef::size().
denormalize()
template<typename T > const InterfaceFile* llvm::yaml::MappingTraits< T >::NormalizedTBD::denormalize (IO & IO) inline
Definition at line 612 of file TextStub.cpp.
References assert(), llvm::coverage::CurrentVersion, File, Name, llvm::ARMBuildAttrs::Section, llvm::MachO::TBD_V1, and llvm::MachO::TBD_V3.
synthesizeTargets()
template<typename T > TargetList llvm::yaml::MappingTraits< T >::NormalizedTBD::synthesizeTargets (ArchitectureSet Architectures, const PlatformSet & Platforms) inline
Definition at line 594 of file TextStub.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachO::ArchitectureSet::hasX86(), and llvm::MachO::mapToPlatformKind().
Member Data Documentation
Allocator
template<typename T > llvm::BumpPtrAllocator llvm::yaml::MappingTraits< T >::NormalizedTBD::Allocator
Definition at line 721 of file TextStub.cpp.
Architectures
template<typename T > std::vector<Architecture> llvm::yaml::MappingTraits< T >::NormalizedTBD::Architectures
Definition at line 731 of file TextStub.cpp.
CompatibilityVersion
template<typename T > PackedVersion llvm::yaml::MappingTraits< T >::NormalizedTBD::CompatibilityVersion
Definition at line 736 of file TextStub.cpp.
CurrentVersion
template<typename T > PackedVersion llvm::yaml::MappingTraits< T >::NormalizedTBD::CurrentVersion
Definition at line 735 of file TextStub.cpp.
Exports
template<typename T > std::vector<ExportSection> llvm::yaml::MappingTraits< T >::NormalizedTBD::Exports
Definition at line 741 of file TextStub.cpp.
Flags
template<typename T > TBDFlags llvm::yaml::MappingTraits< T >::NormalizedTBD::Flags {TBDFlags::None}
Definition at line 739 of file TextStub.cpp.
InstallName
template<typename T > StringRef llvm::yaml::MappingTraits< T >::NormalizedTBD::InstallName
Definition at line 734 of file TextStub.cpp.
ObjCConstraint
template<typename T > ObjCConstraintType llvm::yaml::MappingTraits< T >::NormalizedTBD::ObjCConstraint {ObjCConstraintType::None}
Definition at line 738 of file TextStub.cpp.
ParentUmbrella
template<typename T > StringRef llvm::yaml::MappingTraits< T >::NormalizedTBD::ParentUmbrella
Definition at line 740 of file TextStub.cpp.
Platforms
template<typename T > PlatformSet llvm::yaml::MappingTraits< T >::NormalizedTBD::Platforms
Definition at line 733 of file TextStub.cpp.
SwiftABIVersion
template<typename T > SwiftVersion llvm::yaml::MappingTraits< T >::NormalizedTBD::SwiftABIVersion {0}
Definition at line 737 of file TextStub.cpp.
Undefineds
template<typename T > std::vector<UndefinedSection> llvm::yaml::MappingTraits< T >::NormalizedTBD::Undefineds
Definition at line 742 of file TextStub.cpp.
UUIDs
template<typename T > std::vector<UUID> llvm::yaml::MappingTraits< T >::NormalizedTBD::UUIDs
Definition at line 732 of file TextStub.cpp.
The documentation for this struct was generated from the following file:
lib/TextAPI/MachO/TextStub.cpp