LLVM: llvm::MIToken Struct Reference
llvm::MIToken Struct Reference
A token produced by the machine instruction lexer.
#include "CodeGen/MIRParser/MILexer.h"
Public Types
enum TokenKind {
Eof, Error, Newline, comma,
equal, underscore, colon, coloncolon,
dot, exclaim, lparen, rparen,
lbrace, rbrace, plus, minus,
less, greater, kw_implicit, kw_implicit_define,
kw_def, kw_dead, kw_dereferenceable, kw_killed,
kw_undef, kw_internal, kw_early_clobber, kw_debug_use,
kw_renamable, kw_tied_def, kw_frame_setup, kw_frame_destroy,
kw_nnan, kw_ninf, kw_nsz, kw_arcp,
kw_contract, kw_afn, kw_reassoc, kw_nuw,
kw_nsw, kw_exact, kw_nofpexcept, kw_debug_location,
kw_cfi_same_value, kw_cfi_offset, kw_cfi_rel_offset, kw_cfi_def_cfa_register,
kw_cfi_def_cfa_offset, kw_cfi_adjust_cfa_offset, kw_cfi_escape, kw_cfi_def_cfa,
kw_cfi_register, kw_cfi_remember_state, kw_cfi_restore, kw_cfi_restore_state,
kw_cfi_undefined, kw_cfi_window_save, kw_cfi_aarch64_negate_ra_sign_state, kw_blockaddress,
kw_intrinsic, kw_target_index, kw_half, kw_float,
kw_double, kw_x86_fp80, kw_fp128, kw_ppc_fp128,
kw_target_flags, kw_volatile, kw_non_temporal, kw_invariant,
kw_align, kw_addrspace, kw_stack, kw_got,
kw_jump_table, kw_constant_pool, kw_call_entry, kw_custom,
kw_liveout, kw_address_taken, kw_landing_pad, kw_liveins,
kw_successors, kw_floatpred, kw_intpred, kw_shufflemask,
kw_pre_instr_symbol, kw_post_instr_symbol, kw_heap_alloc_marker, kw_unknown_size,
md_tbaa, md_alias_scope, md_noalias, md_range,
md_diexpr, md_dilocation, Identifier, NamedRegister,
NamedVirtualRegister, MachineBasicBlockLabel, MachineBasicBlock, StackObject,
FixedStackObject, NamedGlobalValue, GlobalValue, ExternalSymbol,
MCSymbol, IntegerLiteral, FloatingPointLiteral, HexLiteral,
VectorLiteral, VirtualRegister, ConstantPoolItem, JumpTableIndex,
NamedIRBlock, IRBlock, NamedIRValue, IRValue,
QuotedIRValue, SubRegisterIndex, StringConstant
}
Public Member Functions
MIToken ()=default
MIToken & reset (TokenKind Kind, StringRef Range)
MIToken & setStringValue (StringRef StrVal)
MIToken & setOwnedStringValue (std::string StrVal)
MIToken & setIntegerValue (APSInt IntVal)
TokenKind kind () const
bool isError () const
bool isNewlineOrEOF () const
bool isErrorOrEOF () const
bool isRegister () const
bool isRegisterFlag () const
bool isMemoryOperandFlag () const
bool is (TokenKind K) const
bool isNot (TokenKind K) const
StringRef::iterator location () const
StringRef range () const
StringRef stringValue () const
Return the token's string value.
const APSInt & integerValue () const
bool hasIntegerValue () const
Detailed Description
A token produced by the machine instruction lexer.
Definition at line 27 of file MILexer.h.
Member Enumeration Documentation
TokenKind
enum llvm::MIToken::TokenKind
Enumerator
Eof
Error
Newline
comma
equal
underscore
colon
coloncolon
dot
exclaim
lparen
rparen
lbrace
rbrace
plus
minus
less
greater
kw_implicit
kw_implicit_define
kw_def
kw_dead
kw_dereferenceable
kw_killed
kw_undef
kw_internal
kw_early_clobber
kw_debug_use
kw_renamable
kw_tied_def
kw_frame_setup
kw_frame_destroy
kw_nnan
kw_ninf
kw_nsz
kw_arcp
kw_contract
kw_afn
kw_reassoc
kw_nuw
kw_nsw
kw_exact
kw_nofpexcept
kw_debug_location
kw_cfi_same_value
kw_cfi_offset
kw_cfi_rel_offset
kw_cfi_def_cfa_register
kw_cfi_def_cfa_offset
kw_cfi_adjust_cfa_offset
kw_cfi_escape
kw_cfi_def_cfa
kw_cfi_register
kw_cfi_remember_state
kw_cfi_restore
kw_cfi_restore_state
kw_cfi_undefined
kw_cfi_window_save
kw_cfi_aarch64_negate_ra_sign_state
kw_blockaddress
kw_intrinsic
kw_target_index
kw_half
kw_float
kw_double
kw_x86_fp80
kw_fp128
kw_ppc_fp128
kw_target_flags
kw_volatile
kw_non_temporal
kw_invariant
kw_align
kw_addrspace
kw_stack
kw_got
kw_jump_table
kw_constant_pool
kw_call_entry
kw_custom
kw_liveout
kw_address_taken
kw_landing_pad
kw_liveins
kw_successors
kw_floatpred
kw_intpred
kw_shufflemask
kw_pre_instr_symbol
kw_post_instr_symbol
kw_heap_alloc_marker
kw_unknown_size
md_tbaa
md_alias_scope
md_noalias
md_range
md_diexpr
md_dilocation
Identifier
NamedRegister
NamedVirtualRegister
MachineBasicBlockLabel
MachineBasicBlock
StackObject
FixedStackObject
NamedGlobalValue
GlobalValue
ExternalSymbol
MCSymbol
IntegerLiteral
FloatingPointLiteral
HexLiteral
VectorLiteral
VirtualRegister
ConstantPoolItem
JumpTableIndex
NamedIRBlock
IRBlock
NamedIRValue
IRValue
QuotedIRValue
SubRegisterIndex
StringConstant
Definition at line 28 of file MILexer.h.
Constructor & Destructor Documentation
MIToken()
llvm::MIToken::MIToken () default
Member Function Documentation
hasIntegerValue()
bool llvm::MIToken::hasIntegerValue () const inline
Definition at line 221 of file MILexer.h.
References ConstantPoolItem, FixedStackObject, IRBlock, IRValue, JumpTableIndex, llvm::lexMIToken(), MachineBasicBlockLabel, llvm::Sched::Source, StackObject, and VirtualRegister.
Referenced by getUnsigned().
integerValue()
const APSInt& llvm::MIToken::integerValue () const inline
Definition at line 219 of file MILexer.h.
Referenced by getUnsigned().
is()
bool llvm::MIToken::is (TokenKind K) const inline
Definition at line 208 of file MILexer.h.
Referenced by getHexUint(), and getUnsigned().
isError()
bool llvm::MIToken::isError () const inline
Definition at line 183 of file MILexer.h.
References Error.
Referenced by maybeLexExclaim().
isErrorOrEOF()
bool llvm::MIToken::isErrorOrEOF () const inline
Definition at line 187 of file MILexer.h.
References Eof.
isMemoryOperandFlag()
bool llvm::MIToken::isMemoryOperandFlag () const inline
Definition at line 202 of file MILexer.h.
References kw_dereferenceable, kw_invariant, kw_non_temporal, kw_volatile, and StringConstant.
isNewlineOrEOF()
bool llvm::MIToken::isNewlineOrEOF () const inline
Definition at line 185 of file MILexer.h.
References Eof, and Newline.
isNot()
bool llvm::MIToken::isNot (TokenKind K) const inline
Definition at line 210 of file MILexer.h.
isRegister()
bool llvm::MIToken::isRegister () const inline
Definition at line 189 of file MILexer.h.
References NamedRegister, NamedVirtualRegister, underscore, and VirtualRegister.
isRegisterFlag()
bool llvm::MIToken::isRegisterFlag () const inline
Definition at line 194 of file MILexer.h.
References kw_dead, kw_debug_use, kw_def, kw_early_clobber, kw_implicit, kw_implicit_define, kw_internal, kw_killed, kw_renamable, and kw_undef.
kind()
TokenKind llvm::MIToken::kind () const inline
Definition at line 181 of file MILexer.h.
Referenced by parseGlobalValue(), and parseIRValue().
location()
StringRef::iterator llvm::MIToken::location () const inline
Definition at line 212 of file MILexer.h.
References llvm::StringRef::begin().
Referenced by getUnsigned(), maybeLexExclaim(), parseGlobalValue(), and parseIRValue().
range()
StringRef llvm::MIToken::range () const inline
Definition at line 214 of file MILexer.h.
Referenced by getHexUint(), parseGlobalValue(), and parseIRValue().
reset()
MIToken & MIToken::reset (TokenKind Kind, StringRef Range)
Definition at line 67 of file MILexer.cpp.
Referenced by lexFloatingPointLiteral(), lexName(), lexNamedVirtualRegister(), lexVirtualRegister(), maybeLexEscapedIRValue(), maybeLexExclaim(), maybeLexGlobalValue(), maybeLexHexadecimalLiteral(), maybeLexIdentifier(), maybeLexIndex(), maybeLexIndexAndName(), maybeLexMachineBasicBlock(), maybeLexNewline(), maybeLexNumericalLiteral(), maybeLexRegister(), and maybeLexSymbol().
setIntegerValue()
MIToken & MIToken::setIntegerValue (APSInt IntVal)
Definition at line 84 of file MILexer.cpp.
Referenced by maybeLexNumericalLiteral().
setOwnedStringValue()
MIToken & MIToken::setOwnedStringValue (std::string StrVal)
Definition at line 78 of file MILexer.cpp.
Referenced by lexName().
setStringValue()
MIToken & MIToken::setStringValue (StringRef StrVal)
Definition at line 73 of file MILexer.cpp.
References llvm::tgtok::StrVal.
Referenced by maybeLexIdentifier().
stringValue()
StringRef llvm::MIToken::stringValue () const inline
Return the token's string value.
Definition at line 217 of file MILexer.h.
Referenced by parseGlobalValue(), and parseIRValue().
The documentation for this struct was generated from the following files:
lib/CodeGen/MIRParser/MILexer.h
lib/CodeGen/MIRParser/MILexer.cpp