LLVM: llvm::rdf::CopyPropagation Struct Reference
llvm::rdf::CopyPropagation Struct Reference
#include "Target/Hexagon/RDFCopy.h"
Public Types
using EqualityMap = std::map< RegisterRef, RegisterRef >
Public Member Functions
CopyPropagation (DataFlowGraph &dfg)
virtual ~CopyPropagation ()=default
bool run ()
void trace (bool On)
bool trace () const
DataFlowGraph & getDFG ()
virtual bool interpretAsCopy (const MachineInstr *MI, EqualityMap &EM)
Detailed Description
Definition at line 27 of file RDFCopy.h.
Member Typedef Documentation
EqualityMap
using llvm::rdf::CopyPropagation::EqualityMap = std::map<RegisterRef, RegisterRef>
Definition at line 38 of file RDFCopy.h.
Constructor & Destructor Documentation
CopyPropagation()
llvm::rdf::CopyPropagation::CopyPropagation (DataFlowGraph & dfg) inline
Definition at line 28 of file RDFCopy.h.
References run(), and ~CopyPropagation().
~CopyPropagation()
virtual llvm::rdf::CopyPropagation::~CopyPropagation () virtual default
Referenced by CopyPropagation().
Member Function Documentation
getDFG()
DataFlowGraph& llvm::rdf::CopyPropagation::getDFG () inline
Definition at line 36 of file RDFCopy.h.
interpretAsCopy()
bool CopyPropagation::interpretAsCopy (const MachineInstr * MI, EqualityMap & EM) virtual
Definition at line 40 of file RDFCopy.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), B, llvm::rdf::NodeAttrs::Def, llvm::rdf::DataFlowGraph::findBlock(), llvm::rdf::StmtNode::getCode(), llvm::rdf::NodeBase::getKind(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::rdf::Liveness::getNearestAliasedRef(), llvm::MachineDominatorTree::getNode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::rdf::RefNode::getReachingDef(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::rdf::DataFlowGraph::getTRI(), I, llvm::rdf::NodeAddr< T >::Id, llvm::rdf::DataFlowGraph::IsCode(), llvm::Register::isPhysicalRegister(), llvm_unreachable, llvm::rdf::DataFlowGraph::makeRegRef(), llvm::rdf::CodeNode::members(), N, RA, llvm::rdf::RegisterRef::Reg, llvm::rdf::NodeAttrs::Stmt, TRI, and llvm::rdf::NodeAttrs::Use.
run()
bool CopyPropagation::run ()
Definition at line 101 of file RDFCopy.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), assert(), C, CpLimit, llvm::dbgs(), F(), R600_InstFlag::FC, llvm::rdf::NodeAttrs::Fixed, llvm::MachineFunction::front(), llvm::X86AS::FS, llvm::rdf::StmtNode::getCode(), llvm::rdf::DataFlowGraph::getMF(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::rdf::InstrNode::getOwner(), llvm::rdf::RefNode::getSibling(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::rdf::DataFlowGraph::getTRI(), I, llvm::rdf::NodeAddr< T >::Id, llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::DataFlowGraph::IsDef(), llvm::MachineOperand::isTied(), llvm::MCSubRegIndexIterator::isValid(), llvm::TargetRegisterClass::LaneMask, llvm_unreachable, llvm::rdf::CodeNode::members_if(), N, llvm::rdf::NodeAttrs::PhiRef, llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), llvm::rdf::NodeAttrs::Stmt, trace(), TRI, and llvm::rdf::DataFlowGraph::unlinkUse().
Referenced by CopyPropagation().
trace() [1/2]
void llvm::rdf::CopyPropagation::trace (bool On) inline
Definition at line 34 of file RDFCopy.h.
trace() [2/2]
bool llvm::rdf::CopyPropagation::trace () const inline
Definition at line 35 of file RDFCopy.h.
Referenced by run().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFCopy.h
lib/Target/Hexagon/RDFCopy.cpp