LLVM: llvm::DOTGraphTraits< RegionInfo * > Struct Template Reference
llvm::DOTGraphTraits< RegionInfo * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (RegionNode *Node, RegionInfo *G)
std::string getEdgeAttributes (RegionNode *srcNode, GraphTraits< RegionInfo *>::ChildIteratorType CI, RegionInfo *G)
Public Member Functions inherited from llvm::DOTGraphTraits< RegionNode *>
DOTGraphTraits (bool simple=false)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Static Public Member Functions
static std::string getGraphName (const RegionInfo *)
static void printRegionCluster (const Region &R, GraphWriter< RegionInfo *> &GW, unsigned depth=0)
static void addCustomGraphFeatures (const RegionInfo *G, GraphWriter< RegionInfo *> &GW)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
static bool isNodeHidden (const void *)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
template<>
struct llvm::DOTGraphTraits< RegionInfo * >
Definition at line 62 of file RegionPrinter.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< RegionInfo * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 64 of file RegionPrinter.cpp.
Member Function Documentation
addCustomGraphFeatures()
static void llvm::DOTGraphTraits< RegionInfo * >::addCustomGraphFeatures (const RegionInfo * G, GraphWriter< RegionInfo *> & GW) inline static
Definition at line 134 of file RegionPrinter.cpp.
References llvm::GraphWriter< GraphType >::getOStream(), llvm::PassRegistry::getPassRegistry(), llvm::RegionInfoPass::getRegionInfo(), llvm::RegionInfoBase< Tr >::getTopLevelRegion(), INITIALIZE_PASS(), llvm::initializeRegionOnlyPrinterPass(), llvm::initializeRegionOnlyViewerPass(), llvm::initializeRegionPrinterPass(), llvm::initializeRegionViewerPass(), and llvm::RISCVFenceField::O.
getEdgeAttributes()
std::string llvm::DOTGraphTraits< RegionInfo * >::getEdgeAttributes (RegionNode * srcNode, GraphTraits< RegionInfo *>::ChildIteratorType CI, RegionInfo * G) inline
Definition at line 74 of file RegionPrinter.cpp.
References llvm::RegionNodeBase< Tr >::getNodeAs(), llvm::RegionInfoBase< Tr >::getRegionFor(), llvm::RegionNodeBase< Tr >::isSubRegion(), and llvm::RISCVFenceField::R.
getGraphName()
static std::string llvm::DOTGraphTraits< RegionInfo * >::getGraphName (const RegionInfo *) inline static
Definition at line 67 of file RegionPrinter.cpp.
getNodeLabel()
std::string llvm::DOTGraphTraits< RegionInfo * >::getNodeLabel (RegionNode * Node, RegionInfo * G) inline
Definition at line 69 of file RegionPrinter.cpp.
printRegionCluster()
static void llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster (const Region & R, GraphWriter< RegionInfo *> & GW, unsigned depth = 0) inline static
Definition at line 102 of file RegionPrinter.cpp.
References llvm::RegionBase< Tr >::getDepth(), llvm::GraphWriter< GraphType >::getOStream(), llvm::RegionInfoBase< Tr >::getRegionFor(), llvm::RegionInfoBase< Tr >::getTopLevelRegion(), llvm::raw_ostream::indent(), llvm::RegionBase< Tr >::isSimple(), llvm::RISCVFenceField::O, onlySimpleRegions, and llvm::RISCVFenceField::R.
The documentation for this struct was generated from the following file:
lib/Analysis/RegionPrinter.cpp