LLVM: llvm::remarks::YAMLStrTabRemarkSerializer Struct Reference
llvm::remarks::YAMLStrTabRemarkSerializer Struct Reference
Serialize the remarks to YAML using a string table.
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLStrTabRemarkSerializer (raw_ostream &OS, SerializerMode Mode)
YAMLStrTabRemarkSerializer (raw_ostream &OS, SerializerMode Mode, StringTable StrTab)
void emit (const Remark &Remark) override
Override to emit the metadata if necessary.
std::unique_ptr< MetaSerializer > metaSerializer (raw_ostream &OS, Optional< StringRef > ExternalFilename=None) override
Return the corresponding metadata serializer.
Public Member Functions inherited from llvm::remarks::YAMLRemarkSerializer
YAMLRemarkSerializer (raw_ostream &OS, SerializerMode Mode, Optional< StringTable > StrTab=None)
Public Member Functions inherited from llvm::remarks::RemarkSerializer
RemarkSerializer (Format SerializerFormat, raw_ostream &OS, SerializerMode Mode)
virtual ~RemarkSerializer ()=default
This is just an interface.
Static Public Member Functions
static bool classof (const RemarkSerializer *S)
Static Public Member Functions inherited from llvm::remarks::YAMLRemarkSerializer
static bool classof (const RemarkSerializer *S)
Public Attributes
bool DidEmitMeta = false
Wether we already emitted the metadata in standalone mode.
Public Attributes inherited from llvm::remarks::YAMLRemarkSerializer
yaml::Output YAMLOutput
The YAML streamer.
Public Attributes inherited from llvm::remarks::RemarkSerializer
Format SerializerFormat
The format of the serializer.
raw_ostream & OS
The open raw_ostream that the remark diagnostics are emitted to.
SerializerMode Mode
The serialization mode.
Optional< StringTable > StrTab
The string table containing all the unique strings used in the output.
Additional Inherited Members
Protected Member Functions inherited from llvm::remarks::YAMLRemarkSerializer
YAMLRemarkSerializer (Format SerializerFormat, raw_ostream &OS, SerializerMode Mode, Optional< StringTable > StrTab=None)
Detailed Description
Serialize the remarks to YAML using a string table.
An remark entry looks like the regular YAML remark but instead of string entries it's using numbers that map to an index in the string table.
Definition at line 67 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLStrTabRemarkSerializer() [1/2]
llvm::remarks::YAMLStrTabRemarkSerializer::YAMLStrTabRemarkSerializer (raw_ostream & OS, SerializerMode Mode) inline
Definition at line 72 of file YAMLRemarkSerializer.h.
References llvm::remarks::RemarkSerializer::StrTab.
YAMLStrTabRemarkSerializer() [2/2]
llvm::remarks::YAMLStrTabRemarkSerializer::YAMLStrTabRemarkSerializer (raw_ostream & OS, SerializerMode Mode, StringTable StrTab) inline
Definition at line 77 of file YAMLRemarkSerializer.h.
References llvm::remarks::YAMLRemarkSerializer::emit(), llvm::remarks::YAMLRemarkSerializer::metaSerializer(), llvm::None, and llvm::remarks::RemarkSerializer::OS.
Member Function Documentation
classof()
static bool llvm::remarks::YAMLStrTabRemarkSerializer::classof (const RemarkSerializer * S) inline static
Definition at line 88 of file YAMLRemarkSerializer.h.
References llvm::remarks::RemarkSerializer::SerializerFormat, and llvm::remarks::YAMLStrTab.
emit()
void YAMLStrTabRemarkSerializer::emit (const Remark & Remark) override virtual
Override to emit the metadata if necessary.
Reimplemented from llvm::remarks::YAMLRemarkSerializer.
Definition at line 186 of file YAMLRemarkSerializer.cpp.
References llvm::remarks::YAMLRemarkSerializer::emit(), llvm::remarks::YAMLRemarkSerializer::metaSerializer(), llvm::remarks::RemarkSerializer::Mode, llvm::None, llvm::remarks::RemarkSerializer::OS, and llvm::remarks::Standalone.
metaSerializer()
std::unique_ptr< MetaSerializer > YAMLStrTabRemarkSerializer::metaSerializer (raw_ostream & OS, Optional< StringRef > ExternalFilename = None) override virtual
Return the corresponding metadata serializer.
Reimplemented from llvm::remarks::YAMLRemarkSerializer.
Definition at line 200 of file YAMLRemarkSerializer.cpp.
References assert(), llvm::remarks::RemarkSerializer::OS, and llvm::remarks::RemarkSerializer::StrTab.
Member Data Documentation
DidEmitMeta
bool llvm::remarks::YAMLStrTabRemarkSerializer::DidEmitMeta = false
Wether we already emitted the metadata in standalone mode.
This should be set to true after the first invocation of emit.
Definition at line 70 of file YAMLRemarkSerializer.h.
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp