LLVM: llvm::GraphTraits< MachineFunction * > Struct Template Reference
llvm::GraphTraits< MachineFunction * > Struct Template Reference
#include "llvm/CodeGen/MachineFunction.h"
Public Types
using nodes_iterator = pointer_iterator< MachineFunction::iterator >
Public Types inherited from llvm::GraphTraits< MachineBasicBlock *>
using NodeRef = typename MachineBasicBlock *::UnknownGraphTypeError
Static Public Member Functions
static NodeRef getEntryNode (MachineFunction *F)
static nodes_iterator nodes_begin (MachineFunction *F)
static nodes_iterator nodes_end (MachineFunction *F)
static unsigned size (MachineFunction *F)
Detailed Description
template<>
struct llvm::GraphTraits< MachineFunction * >
Definition at line 1025 of file MachineFunction.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< MachineFunction * >::nodes_iterator = pointer_iterator<MachineFunction::iterator>
Definition at line 1030 of file MachineFunction.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< MachineFunction * >::getEntryNode (MachineFunction * F) inline static
Definition at line 1027 of file MachineFunction.h.
References llvm::MachineFunction::front().
nodes_begin()
static nodes_iterator llvm::GraphTraits< MachineFunction * >::nodes_begin (MachineFunction * F) inline static
Definition at line 1032 of file MachineFunction.h.
References llvm::MachineFunction::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< MachineFunction * >::nodes_end (MachineFunction * F) inline static
Definition at line 1036 of file MachineFunction.h.
References llvm::MachineFunction::end().
size()
static unsigned llvm::GraphTraits< MachineFunction * >::size (MachineFunction * F) inline static
Definition at line 1040 of file MachineFunction.h.
References llvm::MachineFunction::size().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineFunction.h