LLVM: llvm::yaml::CustomMappingTraits< MapDocNode > Struct Template Reference
llvm::yaml::CustomMappingTraits< MapDocNode > Struct Template Reference
YAMLIO for MapDocNode.
Static Public Member Functions
static void inputOne (IO &IO, StringRef Key, MapDocNode &M)
static void output (IO &IO, MapDocNode &M)
Detailed Description
template<>
struct llvm::yaml::CustomMappingTraits< MapDocNode >
YAMLIO for MapDocNode.
Definition at line 208 of file MsgPackDocumentYAML.cpp.
Member Function Documentation
inputOne()
static void llvm::yaml::CustomMappingTraits< MapDocNode >::inputOne (IO & IO, StringRef Key, MapDocNode & M) inline static
Definition at line 210 of file MsgPackDocumentYAML.cpp.
References llvm::msgpack::DocNode::getDocument(), llvm::msgpack::DocNode::getMap(), llvm::msgpack::Document::getNode(), and llvm::StringRef::str().
output()
static void llvm::yaml::CustomMappingTraits< MapDocNode >::output (IO & IO, MapDocNode & M) inline static
Definition at line 216 of file MsgPackDocumentYAML.cpp.
References llvm::msgpack::DocNode::getMap(), and I.
The documentation for this struct was generated from the following file:
lib/BinaryFormat/MsgPackDocumentYAML.cpp