LLVM: llvm::TargetLowering::MakeLibCallOptions Struct Reference
llvm::TargetLowering::MakeLibCallOptions Struct Reference
This structure is used to pass arguments to makeLibCall function.
#include "llvm/CodeGen/TargetLowering.h"
Public Member Functions
MakeLibCallOptions ()
MakeLibCallOptions & setSExt (bool Value=true)
MakeLibCallOptions & setNoReturn (bool Value=true)
MakeLibCallOptions & setDiscardResult (bool Value=true)
MakeLibCallOptions & setIsPostTypeLegalization (bool Value=true)
MakeLibCallOptions & setTypeListBeforeSoften (ArrayRef< EVT > OpsVT, EVT RetVT, bool Value=true)
Public Attributes
ArrayRef< EVT > OpsVTBeforeSoften
EVT RetVTBeforeSoften
bool IsSExt: 1
bool DoesNotReturn: 1
bool IsReturnValueUsed: 1
bool IsPostTypeLegalization: 1
bool IsSoften: 1
Detailed Description
This structure is used to pass arguments to makeLibCall function.
Definition at line 3600 of file TargetLowering.h.
Constructor & Destructor Documentation
MakeLibCallOptions()
llvm::TargetLowering::MakeLibCallOptions::MakeLibCallOptions () inline
Definition at line 3611 of file TargetLowering.h.
Member Function Documentation
setDiscardResult()
MakeLibCallOptions& llvm::TargetLowering::MakeLibCallOptions::setDiscardResult (bool Value = true) inline
Definition at line 3625 of file TargetLowering.h.
Referenced by llvm::SelectionDAGBuilder::visitSPDescriptorFailure().
setIsPostTypeLegalization()
MakeLibCallOptions& llvm::TargetLowering::MakeLibCallOptions::setIsPostTypeLegalization (bool Value = true) inline
Definition at line 3630 of file TargetLowering.h.
setNoReturn()
MakeLibCallOptions& llvm::TargetLowering::MakeLibCallOptions::setNoReturn (bool Value = true) inline
Definition at line 3620 of file TargetLowering.h.
setSExt()
MakeLibCallOptions& llvm::TargetLowering::MakeLibCallOptions::setSExt (bool Value = true) inline
Definition at line 3615 of file TargetLowering.h.
Referenced by GetFPLibCall(), and LowerUMULO_SMULO().
setTypeListBeforeSoften()
MakeLibCallOptions& llvm::TargetLowering::MakeLibCallOptions::setTypeListBeforeSoften (ArrayRef< EVT > OpsVT, EVT RetVT, bool Value = true) inline
Definition at line 3635 of file TargetLowering.h.
Referenced by GetFPLibCall(), and llvm::TargetLowering::softenSetCCOperands().
Member Data Documentation
DoesNotReturn
bool llvm::TargetLowering::MakeLibCallOptions::DoesNotReturn
Definition at line 3606 of file TargetLowering.h.
IsPostTypeLegalization
bool llvm::TargetLowering::MakeLibCallOptions::IsPostTypeLegalization
Definition at line 3608 of file TargetLowering.h.
IsReturnValueUsed
bool llvm::TargetLowering::MakeLibCallOptions::IsReturnValueUsed
Definition at line 3607 of file TargetLowering.h.
IsSExt
bool llvm::TargetLowering::MakeLibCallOptions::IsSExt
Definition at line 3605 of file TargetLowering.h.
IsSoften
bool llvm::TargetLowering::MakeLibCallOptions::IsSoften
Definition at line 3609 of file TargetLowering.h.
OpsVTBeforeSoften
ArrayRef<EVT> llvm::TargetLowering::MakeLibCallOptions::OpsVTBeforeSoften
Definition at line 3603 of file TargetLowering.h.
RetVTBeforeSoften
EVT llvm::TargetLowering::MakeLibCallOptions::RetVTBeforeSoften
Definition at line 3604 of file TargetLowering.h.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetLowering.h