LLVM: llvm::MDNodeKeyImpl< DIMacro > Struct Template Reference
llvm::MDNodeKeyImpl< DIMacro > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned MIType, unsigned Line, MDString *Name, MDString *Value)
MDNodeKeyImpl (const DIMacro *N)
bool isKeyOf (const DIMacro *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned MIType
unsigned Line
MDString * Name
MDString * Value
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIMacro >
Definition at line 1092 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIMacro >::MDNodeKeyImpl (unsigned MIType, unsigned Line, MDString * Name, MDString * Value) inline
Definition at line 1098 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIMacro >::MDNodeKeyImpl (const DIMacro * N) inline
Definition at line 1100 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIMacro >::getHashValue () const inline
Definition at line 1109 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIMacro >::isKeyOf (const DIMacro * RHS) const inline
Definition at line 1104 of file LLVMContextImpl.h.
References llvm::DIMacro::getLine(), llvm::DIMacroNode::getMacinfoType(), llvm::DIMacro::getRawName(), and llvm::DIMacro::getRawValue().
Member Data Documentation
Line
unsigned llvm::MDNodeKeyImpl< DIMacro >::Line
Definition at line 1094 of file LLVMContextImpl.h.
MIType
unsigned llvm::MDNodeKeyImpl< DIMacro >::MIType
Definition at line 1093 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIMacro >::Name
Definition at line 1095 of file LLVMContextImpl.h.
Value
MDString* llvm::MDNodeKeyImpl< DIMacro >::Value
Definition at line 1096 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h