LLVM: llvm::RegisterBankInfo::PartialMapping Struct Reference
llvm::RegisterBankInfo::PartialMapping Struct Reference
Helper struct that represents how a value is partially mapped into a register.
#include "llvm/CodeGen/GlobalISel/RegisterBankInfo.h"
Public Member Functions
PartialMapping ()=default
PartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank &RegBank)
Provide a shortcut for quickly building PartialMapping.
unsigned getHighBitIdx () const
void dump () const
Print this partial mapping on dbgs() stream.
void print (raw_ostream &OS) const
Print this partial mapping on OS;.
bool verify () const
Check that the Mask is compatible with the RegBank.
Public Attributes
unsigned StartIdx
Number of bits at which this partial mapping starts in the original value.
unsigned Length
Length of this mapping in bits.
const RegisterBank * RegBank
Register bank where the partial value lives.
Detailed Description
Helper struct that represents how a value is partially mapped into a register.
The StartIdx and Length represent what region of the orginal value this partial mapping covers. This can be represented as a Mask of contiguous bit starting at StartIdx bit and spanning Length bits. StartIdx is the number of bits from the less significant bits.
Definition at line 48 of file RegisterBankInfo.h.
Constructor & Destructor Documentation
PartialMapping() [1/2]
llvm::RegisterBankInfo::PartialMapping::PartialMapping () default
PartialMapping() [2/2]
llvm::RegisterBankInfo::PartialMapping::PartialMapping (unsigned StartIdx, unsigned Length, const RegisterBank & RegBank) inline
Provide a shortcut for quickly building PartialMapping.
Definition at line 65 of file RegisterBankInfo.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void RegisterBankInfo::PartialMapping::dump () const
Print this partial mapping on dbgs() stream.
Definition at line 513 of file RegisterBankInfo.cpp.
References llvm::dbgs(), and print().
Referenced by getHighBitIdx(), llvm::RegisterBankInfo::OperandsMapper::getMRI(), llvm::RegisterBankInfo::ValueMapping::isValid(), and llvm::RegisterBankInfo::InstructionMapping::isValid().
getHighBitIdx()
unsigned llvm::RegisterBankInfo::PartialMapping::getHighBitIdx () const inline
Returns
the index of in the original value of the most significant bit that this partial mapping covers.
Definition at line 71 of file RegisterBankInfo.h.
References dump(), print(), and verify().
Referenced by llvm::RegisterBankInfo::ValueMapping::verify().
print()
void RegisterBankInfo::PartialMapping::print (raw_ostream & OS) const
Print this partial mapping on OS;.
Definition at line 528 of file RegisterBankInfo.cpp.
Referenced by getHighBitIdx(), llvm::RegisterBankInfo::OperandsMapper::getMRI(), llvm::RegisterBankInfo::ValueMapping::isValid(), and llvm::RegisterBankInfo::InstructionMapping::isValid().
verify()
bool RegisterBankInfo::PartialMapping::verify () const
Check that the Mask is compatible with the RegBank.
Indeed, if the RegBank cannot accomadate the "active bits" of the mask, there is no way this mapping is valid.
Note
This method does not check anything when assertions are disabled.
Returns
True is the check was successful.
Definition at line 519 of file RegisterBankInfo.cpp.
References assert().
Referenced by llvm::applyMapping(), getHighBitIdx(), llvm::RegisterBankInfo::ValueMapping::isValid(), llvm::RegisterBankInfo::InstructionMapping::isValid(), and llvm::RegisterBankInfo::ValueMapping::verify().
Member Data Documentation
Length
unsigned llvm::RegisterBankInfo::PartialMapping::Length
Length of this mapping in bits.
This is how many bits this partial mapping covers in the original value: from StartIdx to StartIdx + Length -1.
Definition at line 57 of file RegisterBankInfo.h.
Referenced by llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::RegBankSelect::getAnalysisUsage(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::RegisterBankInfo::getRegBank(), hashPartialMapping(), and llvm::RegisterBankInfo::ValueMapping::partsAllUniform().
RegBank
const RegisterBank* llvm::RegisterBankInfo::PartialMapping::RegBank
Register bank where the partial value lives.
Definition at line 60 of file RegisterBankInfo.h.
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingWideLoad(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::RegBankSelect::getAnalysisUsage(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::RegisterBankInfo::getRegBank(), hashPartialMapping(), and llvm::RegisterBankInfo::ValueMapping::partsAllUniform().
StartIdx
unsigned llvm::RegisterBankInfo::PartialMapping::StartIdx
Number of bits at which this partial mapping starts in the original value.
The bits are counted from less significant bits to most significant bits.
Definition at line 52 of file RegisterBankInfo.h.
Referenced by llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::RegisterBankInfo::getRegBank(), hashPartialMapping(), and llvm::RegisterBankInfo::ValueMapping::verify().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegisterBankInfo.h
lib/CodeGen/GlobalISel/RegisterBankInfo.cpp