LLVM: llvm::DenseMapInfo< ValueInfo > Struct Template Reference
llvm::DenseMapInfo< ValueInfo > Struct Template Reference
#include "llvm/IR/ModuleSummaryIndex.h"
Static Public Member Functions
static ValueInfo getEmptyKey ()
static ValueInfo getTombstoneKey ()
static bool isSpecialKey (ValueInfo V)
static bool isEqual (ValueInfo L, ValueInfo R)
static unsigned getHashValue (ValueInfo I)
Detailed Description
template<>
struct llvm::DenseMapInfo< ValueInfo >
Definition at line 256 of file ModuleSummaryIndex.h.
Member Function Documentation
getEmptyKey()
static ValueInfo llvm::DenseMapInfo< ValueInfo >::getEmptyKey () inline static
Definition at line 257 of file ModuleSummaryIndex.h.
getHashValue()
static unsigned llvm::DenseMapInfo< ValueInfo >::getHashValue (ValueInfo I) inline static
Definition at line 275 of file ModuleSummaryIndex.h.
References llvm::ValueInfo::getRef().
getTombstoneKey()
static ValueInfo llvm::DenseMapInfo< ValueInfo >::getTombstoneKey () inline static
Definition at line 261 of file ModuleSummaryIndex.h.
isEqual()
static bool llvm::DenseMapInfo< ValueInfo >::isEqual (ValueInfo L, ValueInfo R) inline static
Definition at line 269 of file ModuleSummaryIndex.h.
References assert(), llvm::ValueInfo::getRef(), and llvm::ValueInfo::haveGVs().
isSpecialKey()
static bool llvm::DenseMapInfo< ValueInfo >::isSpecialKey (ValueInfo V) inline static
Definition at line 265 of file ModuleSummaryIndex.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h