LLVM: llvm::BinarySubstreamRef Struct Reference
llvm::BinarySubstreamRef Struct Reference
#include "llvm/Support/BinaryStreamRef.h"
Public Member Functions
BinarySubstreamRef slice (uint32_t Off, uint32_t Size) const
BinarySubstreamRef drop_front (uint32_t N) const
BinarySubstreamRef keep_front (uint32_t N) const
std::pair< BinarySubstreamRef, BinarySubstreamRef > split (uint32_t Off) const
uint32_t size () const
bool empty () const
Public Attributes
uint32_t Offset = 0
BinaryStreamRef StreamData
Detailed Description
Definition at line 200 of file BinaryStreamRef.h.
Member Function Documentation
drop_front()
BinarySubstreamRef llvm::BinarySubstreamRef::drop_front (uint32_t N) const inline
Definition at line 208 of file BinaryStreamRef.h.
References llvm::size(), and llvm::BinaryStreamRefBase< RefType, StreamType >::slice().
empty()
bool llvm::BinarySubstreamRef::empty () const inline
Definition at line 219 of file BinaryStreamRef.h.
References llvm::size().
Referenced by llvm::pdb::DbiStream::getECName(), llvm::pdb::DbiStream::getECSubstreamData(), and llvm::pdb::DbiStream::reload().
keep_front()
BinarySubstreamRef llvm::BinarySubstreamRef::keep_front (uint32_t N) const inline
Definition at line 211 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::slice().
size()
uint32_t llvm::BinarySubstreamRef::size () const inline
Definition at line 218 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
Referenced by llvm::pdb::TpiStream::reload().
slice()
BinarySubstreamRef llvm::BinarySubstreamRef::slice (uint32_t Off, uint32_t Size) const inline
Definition at line 204 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::slice().
split()
std::pair<BinarySubstreamRef, BinarySubstreamRef> llvm::BinarySubstreamRef::split (uint32_t Off) const inline
Definition at line 214 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), and llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front().
Member Data Documentation
Offset
uint32_t llvm::BinarySubstreamRef::Offset = 0
Definition at line 201 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamReader::readSubstream().
StreamData
BinaryStreamRef llvm::BinarySubstreamRef::StreamData
Definition at line 202 of file BinaryStreamRef.h.
Referenced by llvm::pdb::DbiStream::getECName(), llvm::pdb::DbiStream::getECSubstreamData(), llvm::BinaryStreamReader::readSubstream(), llvm::pdb::TpiStream::reload(), and llvm::pdb::DbiStream::reload().
The documentation for this struct was generated from the following file:
include/llvm/Support/BinaryStreamRef.h