LLVM: llvm::MDBuilder::TBAAStructField Struct Reference
llvm::MDBuilder::TBAAStructField Struct Reference
#include "llvm/IR/MDBuilder.h"
Public Member Functions
TBAAStructField (uint64_t Offset, uint64_t Size, MDNode *Type)
Public Attributes
uint64_t Offset
uint64_t Size
MDNode * Type
Detailed Description
Definition at line 166 of file MDBuilder.h.
Constructor & Destructor Documentation
TBAAStructField()
llvm::MDBuilder::TBAAStructField::TBAAStructField (uint64_t Offset, uint64_t Size, MDNode * Type) inline
Definition at line 170 of file MDBuilder.h.
References llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::MDBuilder::createMutableTBAAAccessTag(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), Offset, Size, and llvm::Tag.
Member Data Documentation
Offset
uint64_t llvm::MDBuilder::TBAAStructField::Offset
Definition at line 167 of file MDBuilder.h.
Referenced by TBAAStructField().
Size
uint64_t llvm::MDBuilder::TBAAStructField::Size
Definition at line 168 of file MDBuilder.h.
Referenced by TBAAStructField().
Type
MDNode* llvm::MDBuilder::TBAAStructField::Type
Definition at line 169 of file MDBuilder.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/MDBuilder.h