LLVM: llvm::GraphTraits< MachineBlockFrequencyInfo * > Struct Template Reference
llvm::GraphTraits< MachineBlockFrequencyInfo * > Struct Template Reference
Public Types
using NodeRef = const MachineBasicBlock *
using ChildIteratorType = MachineBasicBlock::const_succ_iterator
using nodes_iterator = pointer_iterator< MachineFunction::const_iterator >
Static Public Member Functions
static NodeRef getEntryNode (const MachineBlockFrequencyInfo *G)
static ChildIteratorType child_begin (const NodeRef N)
static ChildIteratorType child_end (const NodeRef N)
static nodes_iterator nodes_begin (const MachineBlockFrequencyInfo *G)
static nodes_iterator nodes_end (const MachineBlockFrequencyInfo *G)
Detailed Description
template<>
struct llvm::GraphTraits< MachineBlockFrequencyInfo * >
Definition at line 88 of file MachineBlockFrequencyInfo.cpp.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< MachineBlockFrequencyInfo * >::ChildIteratorType = MachineBasicBlock::const_succ_iterator
Definition at line 90 of file MachineBlockFrequencyInfo.cpp.
NodeRef
using llvm::GraphTraits< MachineBlockFrequencyInfo * >::NodeRef = const MachineBasicBlock *
Definition at line 89 of file MachineBlockFrequencyInfo.cpp.
nodes_iterator
using llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_iterator = pointer_iterator<MachineFunction::const_iterator>
Definition at line 91 of file MachineBlockFrequencyInfo.cpp.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< MachineBlockFrequencyInfo * >::child_begin (const NodeRef N) inline static
Definition at line 97 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineBasicBlock::succ_begin().
child_end()
static ChildIteratorType llvm::GraphTraits< MachineBlockFrequencyInfo * >::child_end (const NodeRef N) inline static
Definition at line 101 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineBasicBlock::succ_end().
getEntryNode()
static NodeRef llvm::GraphTraits< MachineBlockFrequencyInfo * >::getEntryNode (const MachineBlockFrequencyInfo * G) inline static
Definition at line 93 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::front(), and llvm::MachineBlockFrequencyInfo::getFunction().
nodes_begin()
static nodes_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_begin (const MachineBlockFrequencyInfo * G) inline static
Definition at line 103 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::begin(), and llvm::MachineBlockFrequencyInfo::getFunction().
nodes_end()
static nodes_iterator llvm::GraphTraits< MachineBlockFrequencyInfo * >::nodes_end (const MachineBlockFrequencyInfo * G) inline static
Definition at line 107 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineFunction::end(), and llvm::MachineBlockFrequencyInfo::getFunction().
The documentation for this struct was generated from the following file:
lib/CodeGen/MachineBlockFrequencyInfo.cpp