LLVM: llvm::rdf::InstrNode Struct Reference
llvm::rdf::InstrNode Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Public Member Functions
NodeAddr< NodeBase * > getOwner (const DataFlowGraph &G)
Public Member Functions inherited from llvm::rdf::CodeNode
template<typename T >
T getCode () const
void setCode (void *C)
NodeAddr< NodeBase * > getFirstMember (const DataFlowGraph &G) const
NodeAddr< NodeBase * > getLastMember (const DataFlowGraph &G) const
void addMember (NodeAddr< NodeBase *> NA, const DataFlowGraph &G)
void addMemberAfter (NodeAddr< NodeBase *> MA, NodeAddr< NodeBase *> NA, const DataFlowGraph &G)
void removeMember (NodeAddr< NodeBase *> NA, const DataFlowGraph &G)
NodeList members (const DataFlowGraph &G) const
template<typename Predicate >
NodeList members_if (Predicate P, const DataFlowGraph &G) const
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (NodeAddr< NodeBase *> NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct Ref
Code_struct Code
};
Detailed Description
Definition at line 610 of file RDFGraph.h.
Member Function Documentation
getOwner()
NodeAddr< NodeBase * > InstrNode::getOwner (const DataFlowGraph & G)
Definition at line 533 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), assert(), llvm::rdf::NodeAttrs::Block, llvm::rdf::NodeAttrs::Code, llvm::rdf::NodeBase::getKind(), llvm::rdf::NodeBase::getNext(), llvm::rdf::NodeBase::getType(), and llvm_unreachable.
Referenced by llvm::rdf::DeadCodeElimination::erase(), llvm::rdf::Liveness::getNearestAliasedRef(), llvm::rdf::Liveness::resetKills(), and llvm::rdf::CopyPropagation::run().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFGraph.h
lib/Target/Hexagon/RDFGraph.cpp