LLVM: llvm::AMDGPURegisterInfo Struct Reference
llvm::AMDGPURegisterInfo Struct Reference
#include "Target/AMDGPU/AMDGPURegisterInfo.h"
Public Member Functions
AMDGPURegisterInfo ()
void reserveRegisterTuples (BitVector &, unsigned Reg) const
Static Public Member Functions
static unsigned getSubRegFromChannel (unsigned Channel, unsigned NumRegs=1)
Detailed Description
Definition at line 26 of file AMDGPURegisterInfo.h.
Constructor & Destructor Documentation
AMDGPURegisterInfo()
AMDGPURegisterInfo::AMDGPURegisterInfo ()
Definition at line 22 of file AMDGPURegisterInfo.cpp.
Member Function Documentation
getSubRegFromChannel()
unsigned AMDGPURegisterInfo::getSubRegFromChannel (unsigned Channel, unsigned NumRegs = 1) static
Returns
the sub reg enum value for the given Channel (e.g. getSubRegFromChannel(0) -> AMDGPU::sub0)
Definition at line 75 of file AMDGPURegisterInfo.cpp.
References llvm::array_lengthof(), and assert().
Referenced by buildMUBUFOffsetLoadStore(), llvm::R600InstrInfo::copyPhysReg(), llvm::createR600ExpandSpecialInstrsPass(), getLogicalBitOpcode(), getSubRegForIndex(), and selectSGPRVectorRegClassID().
reserveRegisterTuples()
void AMDGPURegisterInfo::reserveRegisterTuples (BitVector & Reserved, unsigned Reg) const
Definition at line 84 of file AMDGPURegisterInfo.cpp.
References llvm::MCRegAliasIterator::isValid(), and llvm::BitVector::set().
Referenced by llvm::SIRegisterInfo::getReservedRegs().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPURegisterInfo.h
lib/Target/AMDGPU/AMDGPURegisterInfo.cpp