LLVM: llvm::ScopedFatalErrorHandler Struct Reference
llvm::ScopedFatalErrorHandler Struct Reference
ScopedFatalErrorHandler - This is a simple helper class which just calls install_fatal_error_handler in its constructor and remove_fatal_error_handler in its destructor.
#include "llvm/Support/ErrorHandling.h"
Public Member Functions
ScopedFatalErrorHandler (fatal_error_handler_t handler, void *user_data=nullptr)
~ScopedFatalErrorHandler ()
Detailed Description
ScopedFatalErrorHandler - This is a simple helper class which just calls install_fatal_error_handler in its constructor and remove_fatal_error_handler in its destructor.
Definition at line 54 of file ErrorHandling.h.
Constructor & Destructor Documentation
ScopedFatalErrorHandler()
llvm::ScopedFatalErrorHandler::ScopedFatalErrorHandler (fatal_error_handler_t handler, void * user_data = nullptr) inline explicit
Definition at line 55 of file ErrorHandling.h.
References llvm::install_fatal_error_handler().
~ScopedFatalErrorHandler()
llvm::ScopedFatalErrorHandler::~ScopedFatalErrorHandler () inline
Definition at line 60 of file ErrorHandling.h.
References file, llvm::install_bad_alloc_error_handler(), llvm::install_out_of_memory_new_handler(), LLVM_ATTRIBUTE_NORETURN, llvm::llvm_unreachable_internal(), llvm::remove_bad_alloc_error_handler(), llvm::remove_fatal_error_handler(), llvm::report_bad_alloc_error(), and llvm::report_fatal_error().
The documentation for this struct was generated from the following file:
include/llvm/Support/ErrorHandling.h