LLVM: llvm::yaml::ScalarTraits< FlowStringRef > Struct Template Reference
llvm::yaml::ScalarTraits< FlowStringRef > Struct Template Reference
#include "TextAPI/MachO/TextStubCommon.h"
Static Public Member Functions
static void output (const FlowStringRef &, void *, raw_ostream &)
static StringRef input (StringRef, void *, FlowStringRef &)
static QuotingType mustQuote (StringRef)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< FlowStringRef >
Definition at line 34 of file TextStubCommon.h.
Member Function Documentation
input()
StringRef llvm::yaml::ScalarTraits< FlowStringRef >::input (StringRef Value, void * Ctx, FlowStringRef & Out) static
Definition at line 25 of file TextStubCommon.cpp.
mustQuote()
QuotingType llvm::yaml::ScalarTraits< FlowStringRef >::mustQuote (StringRef Name) static
Definition at line 29 of file TextStubCommon.cpp.
References assert(), llvm::SmallSet< T, N, C >::begin(), llvm::MachO::bridgeOS, llvm::StringSwitch< T, R >::Case(), llvm::SmallSet< T, N, C >::count(), llvm::StringSwitch< T, R >::Default(), llvm::MachO::GC, llvm::MachO::getArchitectureFromName(), llvm::SmallSet< T, N, C >::insert(), llvm::Invalid, llvm::MachO::iOS, llvm_unreachable, llvm::MachO::macCatalyst, llvm::MachO::macOS, llvm::MachO::None, llvm::MachO::PackedVersion::parse32(), llvm::MachO::Retain_Release, llvm::MachO::Retain_Release_For_Simulator, llvm::MachO::Retain_Release_Or_GC, llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::SmallSet< T, N, C >::size(), llvm::MachO::TBD_V3, llvm::MachO::tvOS, llvm::MachO::unknown, and llvm::MachO::watchOS.
output()
void llvm::yaml::ScalarTraits< FlowStringRef >::output (const FlowStringRef & Value, void * Ctx, raw_ostream & OS) static
Definition at line 21 of file TextStubCommon.cpp.
The documentation for this struct was generated from the following files:
lib/TextAPI/MachO/TextStubCommon.h
lib/TextAPI/MachO/TextStubCommon.cpp