LLVM: llvm::ItaniumPartialDemangler Struct Reference
llvm::ItaniumPartialDemangler Struct Reference
"Partial" demangler.
#include "llvm/Demangle/Demangle.h"
Public Member Functions
ItaniumPartialDemangler ()
ItaniumPartialDemangler (ItaniumPartialDemangler &&Other)
ItaniumPartialDemangler & operator= (ItaniumPartialDemangler &&Other)
bool partialDemangle (const char *MangledName)
Demangle into an AST.
char * finishDemangle (char *Buf, size_t *N) const
Just print the entire mangled name into Buf.
char * getFunctionBaseName (char *Buf, size_t *N) const
Get the base name of a function.
char * getFunctionDeclContextName (char *Buf, size_t *N) const
Get the context name for a function.
char * getFunctionName (char *Buf, size_t *N) const
Get the entire name of this function.
char * getFunctionParameters (char *Buf, size_t *N) const
Get the parameters for this function.
char * getFunctionReturnType (char *Buf, size_t *N) const
bool hasFunctionQualifiers () const
If this function has any any cv or reference qualifiers.
bool isCtorOrDtor () const
If this symbol describes a constructor or destructor.
bool isFunction () const
If this symbol describes a function.
bool isData () const
If this symbol describes a variable.
bool isSpecialName () const
If this symbol is a <special-name>.
~ItaniumPartialDemangler ()
Detailed Description
"Partial" demangler.
This supports demangling a string into an AST (typically an intermediate stage in itaniumDemangle) and querying certain properties or partially printing the demangled name.
Definition at line 56 of file Demangle.h.
Constructor & Destructor Documentation
ItaniumPartialDemangler() [1/2]
ItaniumPartialDemangler::ItaniumPartialDemangler ()
Definition at line 360 of file ItaniumDemangle.cpp.
ItaniumPartialDemangler() [2/2]
ItaniumPartialDemangler::ItaniumPartialDemangler (ItaniumPartialDemangler && Other)
Definition at line 367 of file ItaniumDemangle.cpp.
References operator=(), and llvm::Other.
~ItaniumPartialDemangler()
ItaniumPartialDemangler::~ItaniumPartialDemangler ()
Definition at line 363 of file ItaniumDemangle.cpp.
Member Function Documentation
finishDemangle()
char * ItaniumPartialDemangler::finishDemangle (char * Buf, size_t * N) const
Just print the entire mangled name into Buf.
Buf and N behave like the second and third parameters to itaniumDemangle.
Definition at line 520 of file ItaniumDemangle.cpp.
References assert(), and printNode().
getFunctionBaseName()
char * ItaniumPartialDemangler::getFunctionBaseName (char * Buf, size_t * N) const
Get the base name of a function.
This doesn't include trailing template arguments, ie for "a::b<int>" this function returns "b".
Definition at line 400 of file ItaniumDemangle.cpp.
References getName(), isFunction(), Name, and printNode().
getFunctionDeclContextName()
char * ItaniumPartialDemangler::getFunctionDeclContextName (char * Buf, size_t * N) const
Get the context name for a function.
For "a::b::c", this function returns "a::b".
Definition at line 429 of file ItaniumDemangle.cpp.
References LocalName::Encoding, getName(), initializeOutputStream(), isFunction(), Name, and Node::print().
getFunctionName()
char * ItaniumPartialDemangler::getFunctionName (char * Buf, size_t * N) const
Get the entire name of this function.
Definition at line 475 of file ItaniumDemangle.cpp.
References getName(), isFunction(), Name, and printNode().
getFunctionParameters()
char * ItaniumPartialDemangler::getFunctionParameters (char * Buf, size_t * N) const
Get the parameters for this function.
Definition at line 482 of file ItaniumDemangle.cpp.
References initializeOutputStream(), isFunction(), and NodeArray::printWithComma().
getFunctionReturnType()
char * ItaniumPartialDemangler::getFunctionReturnType (char * Buf, size_t * N) const
Definition at line 501 of file ItaniumDemangle.cpp.
References initializeOutputStream(), isFunction(), and llvm::MipsISD::Ret.
hasFunctionQualifiers()
bool ItaniumPartialDemangler::hasFunctionQualifiers () const
If this function has any any cv or reference qualifiers.
These imply that the function is a non-static member function.
Definition at line 525 of file ItaniumDemangle.cpp.
References assert(), E, FrefQualNone, isFunction(), and QualNone.
isCtorOrDtor()
bool ItaniumPartialDemangler::isCtorOrDtor () const
If this symbol describes a constructor or destructor.
Definition at line 533 of file ItaniumDemangle.cpp.
References getName(), N, and Name.
isData()
bool ItaniumPartialDemangler::isData () const
If this symbol describes a variable.
Definition at line 577 of file ItaniumDemangle.cpp.
References isFunction(), and isSpecialName().
isFunction()
bool ItaniumPartialDemangler::isFunction () const
If this symbol describes a function.
Definition at line 565 of file ItaniumDemangle.cpp.
References assert().
Referenced by getFunctionBaseName(), getFunctionDeclContextName(), getFunctionName(), getFunctionParameters(), getFunctionReturnType(), hasFunctionQualifiers(), and isData().
isSpecialName()
bool ItaniumPartialDemangler::isSpecialName () const
If this symbol is a <special-name>.
These are generally implicitly generated by the implementation, such as vtables and typeinfo names.
Definition at line 571 of file ItaniumDemangle.cpp.
References assert().
Referenced by isData().
operator=()
ItaniumPartialDemangler & ItaniumPartialDemangler::operator= (ItaniumPartialDemangler && Other)
Definition at line 374 of file ItaniumDemangle.cpp.
References llvm::Other, and std::swap().
Referenced by ItaniumPartialDemangler().
partialDemangle()
bool ItaniumPartialDemangler::partialDemangle (const char * MangledName)
Demangle into an AST.
Subsequent calls to the rest of the member functions implicitly operate on the AST this produces.
Returns
true on error, false otherwise
Definition at line 381 of file ItaniumDemangle.cpp.
The documentation for this struct was generated from the following files:
include/llvm/Demangle/Demangle.h
lib/Demangle/ItaniumDemangle.cpp