LLVM: llvm::SystemZRegisterInfo Struct Reference
llvm::SystemZRegisterInfo Struct Reference
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
SystemZRegisterInfo ()
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
getPointerRegClass - Return the register class to use to hold pointers.
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
bool getRegAllocationHints (unsigned VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM, const LiveRegMatrix *Matrix) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const override
SrcRC and DstRC will be morphed into NewRC if this returns true.
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 42 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
SystemZRegisterInfo()
SystemZRegisterInfo::SystemZRegisterInfo ()
Definition at line 24 of file SystemZRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void SystemZRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 256 of file SystemZRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ISD::FrameIndex, llvm::SystemZFrameLowering::getFrameIndexReference(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZII::HasIndex, llvm::SystemZSubtarget::hasVector(), llvm::RegState::Kill, llvm::AArch64CC::LE, llvm::BitmaskEnumDetail::Mask(), and TII.
getCalleeSavedRegs()
const MCPhysReg * SystemZRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 196 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), llvm::SystemZSubtarget::hasVector(), and llvm::TargetLowering::supportSwiftError().
getCallPreservedMask()
const uint32_t * SystemZRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 211 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), llvm::SystemZSubtarget::hasVector(), and llvm::TargetLowering::supportSwiftError().
getCrossCopyRegClass()
const TargetRegisterClass * SystemZRegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
Returns NULL if it is possible to copy between a two registers of the specified class.
Definition at line 418 of file SystemZRegisterInfo.cpp.
getFrameRegister()
Register SystemZRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 412 of file SystemZRegisterInfo.cpp.
References llvm::SystemZFrameLowering::hasFP().
getPointerRegClass()
const TargetRegisterClass* llvm::SystemZRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline override
getPointerRegClass - Return the register class to use to hold pointers.
This is currently only used by LOAD_STACK_GUARD, which requires a non-r0 register, hence ADDR64.
Definition at line 50 of file SystemZRegisterInfo.h.
References Matrix.
getRegAllocationHints()
bool SystemZRegisterInfo::getRegAllocationHints (unsigned VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const MachineFunction & MF, const VirtRegMap * VRM, const LiveRegMatrix * Matrix) const override
Definition at line 77 of file SystemZRegisterInfo.cpp.
References addHints(), llvm::SmallSet< T, N, C >::count(), llvm::MachineRegisterInfo::def_instructions(), DefMI, llvm::VirtRegMap::getPhys(), getRC32(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SystemZSubtarget::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::SystemZ::getTwoOperandOpcode(), llvm::SmallSet< T, N, C >::insert(), llvm::is_contained(), llvm::Register::isPhysicalRegister(), llvm::MachineRegisterInfo::isReserved(), MRI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, llvm::MachineRegisterInfo::reg_instructions(), llvm::MachineRegisterInfo::reg_nodbg_instructions(), llvm::SmallVectorBase::size(), and TRI.
getReservedRegs()
BitVector SystemZRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 227 of file SystemZRegisterInfo.cpp.
References llvm::SystemZFrameLowering::hasFP(), and llvm::BitVector::set().
requiresFrameIndexScavenging()
bool llvm::SystemZRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 72 of file SystemZRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::SystemZRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 69 of file SystemZRegisterInfo.h.
shouldCoalesce()
bool SystemZRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const override
SrcRC and DstRC will be morphed into NewRC if this returns true.
Definition at line 340 of file SystemZRegisterInfo.cpp.
References assert(), llvm::LiveRange::beginIndex(), llvm::TargetRegisterClass::contains(), llvm::BitVector::count(), llvm::LiveRange::endIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInterval(), llvm::TargetRegisterClass::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetRegisterClass::hasSuperClassEq(), llvm::MachineInstr::isCopy(), llvm::Register::isPhysicalRegister(), llvm::BitVector::set(), and SI.
trackLivenessAfterRegAlloc()
bool llvm::SystemZRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline override
Definition at line 75 of file SystemZRegisterInfo.h.
References MI, and SubReg.
The documentation for this struct was generated from the following files:
lib/Target/SystemZ/SystemZRegisterInfo.h
lib/Target/SystemZ/SystemZRegisterInfo.cpp