LLVM: llvm::MDNodeKeyImpl< DIEnumerator > Struct Template Reference
llvm::MDNodeKeyImpl< DIEnumerator > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (int64_t Value, bool IsUnsigned, MDString *Name)
MDNodeKeyImpl (const DIEnumerator *N)
bool isKeyOf (const DIEnumerator *RHS) const
unsigned getHashValue () const
Public Attributes
int64_t Value
MDString * Name
bool IsUnsigned
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIEnumerator >
Definition at line 357 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIEnumerator >::MDNodeKeyImpl (int64_t Value, bool IsUnsigned, MDString * Name) inline
Definition at line 362 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIEnumerator >::MDNodeKeyImpl (const DIEnumerator * N) inline
Definition at line 364 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIEnumerator >::getHashValue () const inline
Definition at line 373 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIEnumerator >::isKeyOf (const DIEnumerator * RHS) const inline
Definition at line 368 of file LLVMContextImpl.h.
References llvm::DIEnumerator::getRawName(), llvm::DIEnumerator::getValue(), and llvm::DIEnumerator::isUnsigned().
Member Data Documentation
IsUnsigned
bool llvm::MDNodeKeyImpl< DIEnumerator >::IsUnsigned
Definition at line 360 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIEnumerator >::Name
Definition at line 359 of file LLVMContextImpl.h.
Value
int64_t llvm::MDNodeKeyImpl< DIEnumerator >::Value
Definition at line 358 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h