LLVM: llvm::DWARFDebugNames::Header Struct Reference
llvm::DWARFDebugNames::Header Struct Reference
DWARF v5 Name Index header.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
Error extract (const DWARFDataExtractor &AS, uint64_t *Offset)
void dump (ScopedPrinter &W) const
Public Attributes
SmallString< 8 > AugmentationString
Detailed Description
DWARF v5 Name Index header.
Definition at line 245 of file DWARFAcceleratorTable.h.
Member Function Documentation
dump()
void DWARFDebugNames::Header::dump (ScopedPrinter & W) const
Definition at line 365 of file DWARFAcceleratorTable.cpp.
References llvm::ScopedPrinter::printHex(), llvm::ScopedPrinter::printNumber(), llvm::ScopedPrinter::startLine(), and llvm::IndexedInstrProf::Version.
extract()
Error DWARFDebugNames::Header::extract (const DWARFDataExtractor & AS, uint64_t * Offset)
Definition at line 379 of file DWARFAcceleratorTable.cpp.
References llvm::alignTo(), llvm::createStringError(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::illegal_byte_sequence, llvm::DataExtractor::isValidOffset(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::Error::success(), and llvm::IndexedInstrProf::Version.
Member Data Documentation
AugmentationString
SmallString<8> llvm::DWARFDebugNames::Header::AugmentationString
Definition at line 246 of file DWARFAcceleratorTable.h.
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp