LLVM: llvm::DenseMapInfo< StringRef > Struct Template Reference
llvm::DenseMapInfo< StringRef > Struct Template Reference
#include "llvm/ADT/DenseMapInfo.h"
Static Public Member Functions
static StringRef getEmptyKey ()
static StringRef getTombstoneKey ()
static unsigned getHashValue (StringRef Val)
static bool isEqual (StringRef LHS, StringRef RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< StringRef >
Definition at line 221 of file DenseMapInfo.h.
Member Function Documentation
getEmptyKey()
static StringRef llvm::DenseMapInfo< StringRef >::getEmptyKey () inline static
Definition at line 222 of file DenseMapInfo.h.
getHashValue()
static unsigned llvm::DenseMapInfo< StringRef >::getHashValue (StringRef Val) inline static
Definition at line 232 of file DenseMapInfo.h.
References assert(), llvm::StringRef::data(), and llvm::hash_value().
getTombstoneKey()
static StringRef llvm::DenseMapInfo< StringRef >::getTombstoneKey () inline static
Definition at line 227 of file DenseMapInfo.h.
isEqual()
static bool llvm::DenseMapInfo< StringRef >::isEqual (StringRef LHS, StringRef RHS) inline static
Definition at line 239 of file DenseMapInfo.h.
References llvm::StringRef::data().
The documentation for this struct was generated from the following file:
include/llvm/ADT/DenseMapInfo.h