LLVM: llvm::WasmEHFuncInfo Struct Reference
llvm::WasmEHFuncInfo Struct Reference
#include "llvm/CodeGen/WasmEHFuncInfo.h"
Public Member Functions
const BasicBlock * getEHPadUnwindDest (const BasicBlock *BB) const
void setEHPadUnwindDest (const BasicBlock *BB, const BasicBlock *Dest)
bool hasEHPadUnwindDest (const BasicBlock *BB) const
MachineBasicBlock * getEHPadUnwindDest (MachineBasicBlock *MBB) const
void setEHPadUnwindDest (MachineBasicBlock *MBB, MachineBasicBlock *Dest)
bool hasEHPadUnwindDest (MachineBasicBlock *MBB) const
Public Attributes
DenseMap< BBOrMBB, BBOrMBB > EHPadUnwindMap
Detailed Description
Definition at line 27 of file WasmEHFuncInfo.h.
Member Function Documentation
getEHPadUnwindDest() [1/2]
const BasicBlock* llvm::WasmEHFuncInfo::getEHPadUnwindDest (const BasicBlock * BB) const inline
Definition at line 33 of file WasmEHFuncInfo.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
getEHPadUnwindDest() [2/2]
MachineBasicBlock* llvm::WasmEHFuncInfo::getEHPadUnwindDest (MachineBasicBlock * MBB) const inline
Definition at line 43 of file WasmEHFuncInfo.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
hasEHPadUnwindDest() [1/2]
bool llvm::WasmEHFuncInfo::hasEHPadUnwindDest (const BasicBlock * BB) const inline
Definition at line 39 of file WasmEHFuncInfo.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count().
hasEHPadUnwindDest() [2/2]
bool llvm::WasmEHFuncInfo::hasEHPadUnwindDest (MachineBasicBlock * MBB) const inline
Definition at line 49 of file WasmEHFuncInfo.h.
References llvm::calculateWasmEHInfo(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), and F().
setEHPadUnwindDest() [1/2]
void llvm::WasmEHFuncInfo::setEHPadUnwindDest (const BasicBlock * BB, const BasicBlock * Dest) inline
Definition at line 36 of file WasmEHFuncInfo.h.
Referenced by llvm::calculateWasmEHInfo().
setEHPadUnwindDest() [2/2]
void llvm::WasmEHFuncInfo::setEHPadUnwindDest (MachineBasicBlock * MBB, MachineBasicBlock * Dest) inline
Definition at line 46 of file WasmEHFuncInfo.h.
Member Data Documentation
EHPadUnwindMap
DenseMap<BBOrMBB, BBOrMBB> llvm::WasmEHFuncInfo::EHPadUnwindMap
Definition at line 30 of file WasmEHFuncInfo.h.
Referenced by llvm::FunctionLoweringInfo::set().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/WasmEHFuncInfo.h