LLVM: llvm::GCNRegPressure Struct Reference
llvm::GCNRegPressure Struct Reference
#include "Target/AMDGPU/GCNRegPressure.h"
Public Types
enum RegKind {
SGPR32, SGPR_TUPLE, VGPR32, VGPR_TUPLE,
AGPR32, AGPR_TUPLE, TOTAL_KINDS
}
Public Member Functions
GCNRegPressure ()
bool empty () const
void clear ()
unsigned getSGPRNum () const
unsigned getVGPRNum () const
unsigned getVGPRTuplesWeight () const
unsigned getSGPRTuplesWeight () const
unsigned getOccupancy (const GCNSubtarget &ST) const
void inc (unsigned Reg, LaneBitmask PrevMask, LaneBitmask NewMask, const MachineRegisterInfo &MRI)
bool higherOccupancy (const GCNSubtarget &ST, const GCNRegPressure &O) const
bool less (const GCNSubtarget &ST, const GCNRegPressure &O, unsigned MaxOccupancy=std::numeric_limits< unsigned >::max()) const
bool operator== (const GCNRegPressure &O) const
bool operator!= (const GCNRegPressure &O) const
void print (raw_ostream &OS, const GCNSubtarget *ST=nullptr) const
void dump () const
Friends
GCNRegPressure max (const GCNRegPressure &P1, const GCNRegPressure &P2)
Detailed Description
Definition at line 28 of file GCNRegPressure.h.
Member Enumeration Documentation
RegKind
enum llvm::GCNRegPressure::RegKind
Enumerator
SGPR32
SGPR_TUPLE
VGPR32
VGPR_TUPLE
AGPR32
AGPR_TUPLE
TOTAL_KINDS
Definition at line 29 of file GCNRegPressure.h.
Constructor & Destructor Documentation
GCNRegPressure()
llvm::GCNRegPressure::GCNRegPressure () inline
Definition at line 39 of file GCNRegPressure.h.
References clear().
Member Function Documentation
clear()
void llvm::GCNRegPressure::clear () inline
Definition at line 45 of file GCNRegPressure.h.
References TOTAL_KINDS.
Referenced by llvm::GCNRPTracker::clearMaxPressure(), GCNRegPressure(), llvm::GCNRPTracker::moveMaxPressure(), and llvm::GCNIterativeScheduler::OverrideLegacyStrategy::schedule().
dump()
void llvm::GCNRegPressure::dump () const inline
Definition at line 80 of file GCNRegPressure.h.
References llvm::dbgs(), max, print(), and TOTAL_KINDS.
empty()
bool llvm::GCNRegPressure::empty () const inline
Definition at line 43 of file GCNRegPressure.h.
References getSGPRNum(), and getVGPRNum().
Referenced by llvm::GCNIterativeScheduler::scheduleRegion().
getOccupancy()
unsigned llvm::GCNRegPressure::getOccupancy (const GCNSubtarget & ST) const inline
Definition at line 54 of file GCNRegPressure.h.
References llvm::GCNSubtarget::getOccupancyWithNumSGPRs(), llvm::GCNSubtarget::getOccupancyWithNumVGPRs(), getSGPRNum(), getVGPRNum(), inc(), MRI, and Reg.
Referenced by getMopState(), higherOccupancy(), print(), and llvm::GCNScheduleDAGMILive::schedule().
getSGPRNum()
unsigned llvm::GCNRegPressure::getSGPRNum () const inline
Definition at line 47 of file GCNRegPressure.h.
References SGPR32.
Referenced by empty(), getMopState(), getOccupancy(), less(), and print().
getSGPRTuplesWeight()
unsigned llvm::GCNRegPressure::getSGPRTuplesWeight () const inline
Definition at line 52 of file GCNRegPressure.h.
References SGPR_TUPLE.
Referenced by less(), and print().
getVGPRNum()
unsigned llvm::GCNRegPressure::getVGPRNum () const inline
Definition at line 48 of file GCNRegPressure.h.
References AGPR32, llvm::max(), and VGPR32.
Referenced by empty(), getMopState(), getOccupancy(), less(), and print().
getVGPRTuplesWeight()
unsigned llvm::GCNRegPressure::getVGPRTuplesWeight () const inline
Definition at line 50 of file GCNRegPressure.h.
References AGPR_TUPLE, llvm::max(), and VGPR_TUPLE.
Referenced by less(), and print().
higherOccupancy()
bool llvm::GCNRegPressure::higherOccupancy (const GCNSubtarget & ST, const GCNRegPressure & O) const inline
Definition at line 64 of file GCNRegPressure.h.
References getOccupancy(), less(), llvm::max(), llvm::RISCVFenceField::O, and llvm::ARM_MB::ST.
inc()
void GCNRegPressure::inc (unsigned Reg, LaneBitmask PrevMask, LaneBitmask NewMask, const MachineRegisterInfo & MRI)
Definition at line 97 of file GCNRegPressure.cpp.
References AGPR32, AGPR_TUPLE, llvm::LaneBitmask::any(), assert(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::MachineRegisterInfo::getPressureSets(), llvm::PSetIterator::getWeight(), llvm_unreachable, llvm::LaneBitmask::none(), SGPR32, SGPR_TUPLE, std::swap(), VGPR32, and VGPR_TUPLE.
Referenced by getOccupancy(), and llvm::getRegPressure().
less()
bool GCNRegPressure::less (const GCNSubtarget & ST, const GCNRegPressure & O, unsigned MaxOccupancy = std::numeric_limits<unsigned>::max()) const
Definition at line 139 of file GCNRegPressure.cpp.
References llvm::GCNSubtarget::getOccupancyWithNumSGPRs(), llvm::GCNSubtarget::getOccupancyWithNumVGPRs(), getSGPRNum(), getSGPRTuplesWeight(), getVGPRNum(), getVGPRTuplesWeight(), I, and LLVM_DUMP_METHOD.
Referenced by higherOccupancy(), and llvm::GCNIterativeScheduler::sortRegionsByPressure().
operator!=()
bool llvm::GCNRegPressure::operator!= (const GCNRegPressure & O) const inline
Definition at line 75 of file GCNRegPressure.h.
References llvm::RISCVFenceField::O, and print().
operator==()
bool llvm::GCNRegPressure::operator== (const GCNRegPressure & O) const inline
Definition at line 71 of file GCNRegPressure.h.
References llvm::lltok::equal, and TOTAL_KINDS.
print()
LLVM_DUMP_METHOD void GCNRegPressure::print (raw_ostream & OS, const GCNSubtarget * ST = nullptr) const
Definition at line 185 of file GCNRegPressure.cpp.
References AGPR32, getOccupancy(), llvm::GCNSubtarget::getOccupancyWithNumSGPRs(), llvm::GCNSubtarget::getOccupancyWithNumVGPRs(), getSGPRNum(), getSGPRTuplesWeight(), getVGPRNum(), getVGPRTuplesWeight(), and VGPR32.
Referenced by dump(), operator!=(), printLivenessInfo(), llvm::GCNIterativeScheduler::printSchedRP(), llvm::GCNScheduleDAGMILive::schedule(), and llvm::GCNIterativeScheduler::scheduleRegion().
Friends And Related Function Documentation
max
GCNRegPressure max (const GCNRegPressure & P1, const GCNRegPressure & P2) friend
Definition at line 91 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNDownwardRPTracker::advanceToNext(), dump(), and llvm::GCNUpwardRPTracker::recede().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/GCNRegPressure.h
lib/Target/AMDGPU/GCNRegPressure.cpp