LLVM: llvm::codeview::BinaryAnnotationIterator Struct Reference
llvm::codeview::BinaryAnnotationIterator Struct Reference
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
Public Member Functions
BinaryAnnotationIterator ()=default
BinaryAnnotationIterator (ArrayRef< uint8_t > Annotations)
BinaryAnnotationIterator (const BinaryAnnotationIterator &Other)
bool operator== (BinaryAnnotationIterator Other) const
BinaryAnnotationIterator & operator= (const BinaryAnnotationIterator Other)
BinaryAnnotationIterator & operator++ ()
const DecodedAnnotation & operator* ()
Public Member Functions inherited from llvm::iterator_facade_base< BinaryAnnotationIterator, std::forward_iterator_tag, DecodedAnnotation >
BinaryAnnotationIterator operator+ (std::ptrdiff_t n) const
BinaryAnnotationIterator operator- (std::ptrdiff_t n) const
BinaryAnnotationIterator & operator++ ()
BinaryAnnotationIterator operator++ (int)
BinaryAnnotationIterator & operator-- ()
BinaryAnnotationIterator operator-- (int)
bool operator!= (const BinaryAnnotationIterator &RHS) const
bool operator> (const BinaryAnnotationIterator &RHS) const
bool operator<= (const BinaryAnnotationIterator &RHS) const
bool operator>= (const BinaryAnnotationIterator &RHS) const
DecodedAnnotation * operator-> ()
DecodedAnnotation * operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n)
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< BinaryAnnotationIterator, std::forward_iterator_tag, DecodedAnnotation >
enum
Detailed Description
Definition at line 168 of file SymbolRecord.h.
Constructor & Destructor Documentation
BinaryAnnotationIterator() [1/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator () default
BinaryAnnotationIterator() [2/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator (ArrayRef< uint8_t > Annotations) inline
Definition at line 173 of file SymbolRecord.h.
References llvm::Data.
BinaryAnnotationIterator() [3/3]
llvm::codeview::BinaryAnnotationIterator::BinaryAnnotationIterator (const BinaryAnnotationIterator & Other) inline
Definition at line 174 of file SymbolRecord.h.
References llvm::Data.
Member Function Documentation
operator*()
const DecodedAnnotation& llvm::codeview::BinaryAnnotationIterator::operator* () inline
Definition at line 197 of file SymbolRecord.h.
References llvm::codeview::DecodedAnnotation::Bytes, llvm::codeview::ChangeCodeLength, llvm::codeview::ChangeCodeLengthAndCodeOffset, llvm::codeview::ChangeCodeOffset, llvm::codeview::ChangeCodeOffsetAndLineOffset, llvm::codeview::ChangeCodeOffsetBase, llvm::codeview::ChangeColumnEnd, llvm::codeview::ChangeColumnEndDelta, llvm::codeview::ChangeColumnStart, llvm::codeview::ChangeFile, llvm::codeview::ChangeLineEndDelta, llvm::codeview::ChangeLineOffset, llvm::codeview::ChangeRangeKind, llvm::codeview::CodeOffset, llvm::Data, DecodeSignedOperand(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::codeview::Invalid, llvm::codeview::DecodedAnnotation::Name, llvm::codeview::DecodedAnnotation::OpCode, llvm::codeview::DecodedAnnotation::S1, llvm::codeview::DecodedAnnotation::U1, and llvm::codeview::DecodedAnnotation::U2.
operator++()
BinaryAnnotationIterator& llvm::codeview::BinaryAnnotationIterator::operator++ () inline
Definition at line 186 of file SymbolRecord.h.
References llvm::Data.
operator=()
BinaryAnnotationIterator& llvm::codeview::BinaryAnnotationIterator::operator= (const BinaryAnnotationIterator Other) inline
Definition at line 181 of file SymbolRecord.h.
References llvm::Data.
operator==()
bool llvm::codeview::BinaryAnnotationIterator::operator== (BinaryAnnotationIterator Other) const inline
Definition at line 177 of file SymbolRecord.h.
References llvm::Data.
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/SymbolRecord.h