LLVM: llvm::object::Elf_Sym_Impl< ELFT > Struct Template Reference
llvm::object::Elf_Sym_Impl< ELFT > Struct Template Reference
#include "llvm/Object/ELFTypes.h"
Public Member Functions
unsigned char getBinding () const
unsigned char getType () const
uint64_t getValue () const
void setBinding (unsigned char b)
void setType (unsigned char t)
void setBindingAndType (unsigned char b, unsigned char t)
unsigned char getVisibility () const
Access to the STV_xxx flag stored in the first two bits of st_other.
void setVisibility (unsigned char v)
bool isAbsolute () const
bool isCommon () const
bool isDefined () const
bool isProcessorSpecific () const
bool isOSSpecific () const
bool isReserved () const
bool isUndefined () const
bool isExternal () const
Expected< StringRef > getName (StringRef StrTab) const
Detailed Description
template<class ELFT>
struct llvm::object::Elf_Sym_Impl< ELFT >
Definition at line 30 of file ELFTypes.h.
Member Function Documentation
getBinding()
template<class ELFT > unsigned char llvm::object::Elf_Sym_Impl< ELFT >::getBinding () const inline
Definition at line 195 of file ELFTypes.h.
getName()
template<class ELFT > Expected< StringRef > llvm::object::Elf_Sym_Impl< ELFT >::getName (StringRef StrTab) const
Definition at line 248 of file ELFTypes.h.
References llvm::createStringError(), llvm::StringRef::data(), LLVM_ELF_IMPORT_TYPES_ELFT, llvm::object::parse_failed, and llvm::StringRef::size().
getType()
template<class ELFT > unsigned char llvm::object::Elf_Sym_Impl< ELFT >::getType () const inline
Definition at line 196 of file ELFTypes.h.
getValue()
template<class ELFT > uint64_t llvm::object::Elf_Sym_Impl< ELFT >::getValue () const inline
Definition at line 197 of file ELFTypes.h.
getVisibility()
template<class ELFT > unsigned char llvm::object::Elf_Sym_Impl< ELFT >::getVisibility () const inline
Access to the STV_xxx flag stored in the first two bits of st_other.
STV_DEFAULT: 0 STV_INTERNAL: 1 STV_HIDDEN: 2 STV_PROTECTED: 3
Definition at line 210 of file ELFTypes.h.
isAbsolute()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isAbsolute () const inline
Definition at line 216 of file ELFTypes.h.
References llvm::ELF::SHN_ABS.
isCommon()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isCommon () const inline
Definition at line 218 of file ELFTypes.h.
References getType(), llvm::ELF::SHN_COMMON, and llvm::ELF::STT_COMMON.
isDefined()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isDefined () const inline
Definition at line 222 of file ELFTypes.h.
isExternal()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isExternal () const inline
Definition at line 240 of file ELFTypes.h.
References getName(), and llvm::ELF::STB_LOCAL.
isOSSpecific()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isOSSpecific () const inline
Definition at line 228 of file ELFTypes.h.
References llvm::ELF::SHN_HIOS, and llvm::ELF::SHN_LOOS.
isProcessorSpecific()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isProcessorSpecific () const inline
Definition at line 224 of file ELFTypes.h.
References llvm::ELF::SHN_HIPROC, and llvm::ELF::SHN_LOPROC.
isReserved()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isReserved () const inline
Definition at line 232 of file ELFTypes.h.
References llvm::ELF::SHN_LORESERVE.
isUndefined()
template<class ELFT > bool llvm::object::Elf_Sym_Impl< ELFT >::isUndefined () const inline
Definition at line 238 of file ELFTypes.h.
References llvm::ELF::SHN_UNDEF.
setBinding()
template<class ELFT > void llvm::object::Elf_Sym_Impl< ELFT >::setBinding (unsigned char b) inline
Definition at line 198 of file ELFTypes.h.
References getType().
setBindingAndType()
template<class ELFT > void llvm::object::Elf_Sym_Impl< ELFT >::setBindingAndType (unsigned char b, unsigned char t) inline
Definition at line 201 of file ELFTypes.h.
setType()
template<class ELFT > void llvm::object::Elf_Sym_Impl< ELFT >::setType (unsigned char t) inline
Definition at line 199 of file ELFTypes.h.
setVisibility()
template<class ELFT > void llvm::object::Elf_Sym_Impl< ELFT >::setVisibility (unsigned char v) inline
Definition at line 211 of file ELFTypes.h.
References assert().
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h