LLVM: llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse > Struct Template Reference
llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse > Struct Template Reference
#include "llvm/Support/GenericDomTreeConstruction.h"
Public Types
using ResultTy = SmallVector< NodePtr, 8 >
using Tag = std::integral_constant< bool, Inverse >
Static Public Member Functions
static ResultTy Get (NodePtr N, std::integral_constant< bool, false >)
static ResultTy Get (NodePtr N, std::integral_constant< bool, true >)
static ResultTy Get (NodePtr N, BatchUpdatePtr BUI)
Detailed Description
template<typename DomTreeT>
template<bool Inverse>
struct llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >
Definition at line 109 of file GenericDomTreeConstruction.h.
Member Typedef Documentation
ResultTy
template<typename DomTreeT > template<bool Inverse> using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::ResultTy = SmallVector<NodePtr, 8>
Definition at line 110 of file GenericDomTreeConstruction.h.
Tag
template<typename DomTreeT > template<bool Inverse> using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Tag = std::integral_constant<bool, Inverse>
Definition at line 122 of file GenericDomTreeConstruction.h.
Member Function Documentation
Get() [1/3]
template<typename DomTreeT > template<bool Inverse> static ResultTy llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get (NodePtr N, std::integral_constant< bool, false >) inline static
Definition at line 112 of file GenericDomTreeConstruction.h.
References llvm::reverse().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors().
Get() [2/3]
template<typename DomTreeT > template<bool Inverse> static ResultTy llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get (NodePtr N, std::integral_constant< bool, true >) inline static
Definition at line 117 of file GenericDomTreeConstruction.h.
References N.
Get() [3/3]
template<typename DomTreeT > template<bool Inverse> static ResultTy llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ChildrenGetter< Inverse >::Get (NodePtr N, BatchUpdatePtr BUI) inline static
Definition at line 128 of file GenericDomTreeConstruction.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::find(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::FuturePredecessors, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::FutureSuccessors, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sys::fs::remove().
The documentation for this struct was generated from the following file:
include/llvm/Support/GenericDomTreeConstruction.h