LLVM: llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > > Struct Template Reference
llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > > Struct Template Reference
#include "llvm/ObjectYAML/ELFYAML.h"
Static Public Member Functions
static void mapping (IO &IO, std::unique_ptr< ELFYAML::Chunk > &C)
static StringRef validate (IO &io, std::unique_ptr< ELFYAML::Chunk > &C)
Detailed Description
template<>
struct llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >
Definition at line 692 of file ELFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping (IO & IO, std::unique_ptr< ELFYAML::Chunk > & C) static
Definition at line 1177 of file ELFYAML.cpp.
References llvm::ELFYAML::dropUniqueSuffix(), llvm::yaml::fillMapping(), llvm::yaml::groupSectionMapping(), Name, llvm::ELFYAML::StackSizesSection::nameMatches(), llvm::yaml::sectionMapping(), llvm::ELF::SHT_DYNAMIC, llvm::ELF::SHT_GNU_HASH, llvm::ELF::SHT_GNU_verdef, llvm::ELF::SHT_GNU_verneed, llvm::ELF::SHT_GNU_versym, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_HASH, llvm::ELF::SHT_LLVM_ADDRSIG, llvm::ELF::SHT_LLVM_DEPENDENT_LIBRARIES, llvm::ELF::SHT_LLVM_LINKER_OPTIONS, llvm::ELF::SHT_MIPS_ABIFLAGS, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_RELR, and llvm::ELF::SHT_SYMTAB_SHNDX.
validate()
StringRef llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate (IO & io, std::unique_ptr< ELFYAML::Chunk > & C) static
Definition at line 1299 of file ELFYAML.cpp.
References F(), llvm::AArch64CC::HS, llvm::ELFYAML::AddrsigSymbol::Index, llvm::ELFYAML::AddrsigSymbol::Name, llvm::ELF::RSS_UNDEF, SpecSym, llvm::X86AS::SS, Type2, and Type3.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/ELFYAML.h
lib/ObjectYAML/ELFYAML.cpp