LLVM: llvm::GraphTraits< BlockFrequencyInfo * > Struct Template Reference
llvm::GraphTraits< BlockFrequencyInfo * > Struct Template Reference
Public Types
using NodeRef = const BasicBlock *
using ChildIteratorType = succ_const_iterator
using nodes_iterator = pointer_iterator< Function::const_iterator >
Static Public Member Functions
static NodeRef getEntryNode (const BlockFrequencyInfo *G)
static ChildIteratorType child_begin (const NodeRef N)
static ChildIteratorType child_end (const NodeRef N)
static nodes_iterator nodes_begin (const BlockFrequencyInfo *G)
static nodes_iterator nodes_end (const BlockFrequencyInfo *G)
Detailed Description
template<>
struct llvm::GraphTraits< BlockFrequencyInfo * >
Definition at line 99 of file BlockFrequencyInfo.cpp.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< BlockFrequencyInfo * >::ChildIteratorType = succ_const_iterator
Definition at line 101 of file BlockFrequencyInfo.cpp.
NodeRef
using llvm::GraphTraits< BlockFrequencyInfo * >::NodeRef = const BasicBlock *
Definition at line 100 of file BlockFrequencyInfo.cpp.
nodes_iterator
using llvm::GraphTraits< BlockFrequencyInfo * >::nodes_iterator = pointer_iterator<Function::const_iterator>
Definition at line 102 of file BlockFrequencyInfo.cpp.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< BlockFrequencyInfo * >::child_begin (const NodeRef N) inline static
Definition at line 108 of file BlockFrequencyInfo.cpp.
References llvm::succ_begin().
child_end()
static ChildIteratorType llvm::GraphTraits< BlockFrequencyInfo * >::child_end (const NodeRef N) inline static
Definition at line 112 of file BlockFrequencyInfo.cpp.
References llvm::succ_end().
getEntryNode()
static NodeRef llvm::GraphTraits< BlockFrequencyInfo * >::getEntryNode (const BlockFrequencyInfo * G) inline static
Definition at line 104 of file BlockFrequencyInfo.cpp.
References llvm::Function::front(), and llvm::BlockFrequencyInfo::getFunction().
nodes_begin()
static nodes_iterator llvm::GraphTraits< BlockFrequencyInfo * >::nodes_begin (const BlockFrequencyInfo * G) inline static
Definition at line 114 of file BlockFrequencyInfo.cpp.
References llvm::Function::begin(), and llvm::BlockFrequencyInfo::getFunction().
nodes_end()
static nodes_iterator llvm::GraphTraits< BlockFrequencyInfo * >::nodes_end (const BlockFrequencyInfo * G) inline static
Definition at line 118 of file BlockFrequencyInfo.cpp.
References llvm::Function::end(), and llvm::BlockFrequencyInfo::getFunction().
The documentation for this struct was generated from the following file:
lib/Analysis/BlockFrequencyInfo.cpp