LLVM: llvm::MDNodeKeyImpl< DILabel > Struct Template Reference
llvm::MDNodeKeyImpl< DILabel > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, MDString *Name, Metadata *File, unsigned Line)
MDNodeKeyImpl (const DILabel *N)
bool isKeyOf (const DILabel *RHS) const
unsigned getHashValue () const
Using name and line to get hash value. It should already be mostly unique.
Public Attributes
Metadata * Scope
MDString * Name
Metadata * File
unsigned Line
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILabel >
Definition at line 978 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DILabel >::MDNodeKeyImpl (Metadata * Scope, MDString * Name, Metadata * File, unsigned Line) inline
Definition at line 984 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DILabel >::MDNodeKeyImpl (const DILabel * N) inline
Definition at line 986 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DILabel >::getHashValue () const inline
Using name and line to get hash value. It should already be mostly unique.
Definition at line 996 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DILabel >::isKeyOf (const DILabel * RHS) const inline
Definition at line 990 of file LLVMContextImpl.h.
References llvm::DILabel::getLine(), llvm::DILabel::getRawFile(), llvm::DILabel::getRawName(), and llvm::DILabel::getRawScope().
Member Data Documentation
File
Metadata* llvm::MDNodeKeyImpl< DILabel >::File
Definition at line 981 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DILabel >::Line
Definition at line 982 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DILabel >::Name
Definition at line 980 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DILabel >::Scope
Definition at line 979 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h