LLVM: llvm::latency_sort Struct Reference
llvm::latency_sort Struct Reference
Sorting functions for the Available queue.
#include "llvm/CodeGen/LatencyPriorityQueue.h"
Public Member Functions
latency_sort (LatencyPriorityQueue *pq)
bool operator() (const SUnit *LHS, const SUnit *RHS) const
Public Attributes
LatencyPriorityQueue * PQ
Detailed Description
Sorting functions for the Available queue.
Definition at line 25 of file LatencyPriorityQueue.h.
Constructor & Destructor Documentation
latency_sort()
llvm::latency_sort::latency_sort (LatencyPriorityQueue * pq) inline explicit
Definition at line 27 of file LatencyPriorityQueue.h.
References operator()().
Member Function Documentation
operator()()
bool latency_sort::operator() (const SUnit * LHS, const SUnit * RHS) const
Definition at line 23 of file LatencyPriorityQueue.cpp.
References E, llvm::LatencyPriorityQueue::getLatency(), llvm::LatencyPriorityQueue::getNumSolelyBlockNodes(), I, llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, llvm::SUnit::NodeNum, PQ, and llvm::SUnit::Preds.
Referenced by latency_sort().
Member Data Documentation
PQ
LatencyPriorityQueue* llvm::latency_sort::PQ
Definition at line 26 of file LatencyPriorityQueue.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/LatencyPriorityQueue.h
lib/CodeGen/LatencyPriorityQueue.cpp