LLVM: llvm::MDNodeKeyImpl< DICommonBlock > Struct Template Reference
llvm::MDNodeKeyImpl< DICommonBlock > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *Decl, MDString *Name, Metadata *File, unsigned LineNo)
MDNodeKeyImpl (const DICommonBlock *N)
bool isKeyOf (const DICommonBlock *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * Decl
MDString * Name
Metadata * File
unsigned LineNo
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DICommonBlock >
Definition at line 792 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DICommonBlock >::MDNodeKeyImpl (Metadata * Scope, Metadata * Decl, MDString * Name, Metadata * File, unsigned LineNo) inline
Definition at line 799 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DICommonBlock >::MDNodeKeyImpl (const DICommonBlock * N) inline
Definition at line 802 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DICommonBlock >::getHashValue () const inline
Definition at line 812 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DICommonBlock >::isKeyOf (const DICommonBlock * RHS) const inline
Definition at line 806 of file LLVMContextImpl.h.
References llvm::DICommonBlock::getLineNo(), llvm::DICommonBlock::getRawDecl(), llvm::DICommonBlock::getRawFile(), llvm::DICommonBlock::getRawName(), and llvm::DICommonBlock::getRawScope().
Member Data Documentation
Decl
Metadata* llvm::MDNodeKeyImpl< DICommonBlock >::Decl
Definition at line 794 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DICommonBlock >::File
Definition at line 796 of file LLVMContextImpl.h.
LineNo
unsigned llvm::MDNodeKeyImpl< DICommonBlock >::LineNo
Definition at line 797 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DICommonBlock >::Name
Definition at line 795 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DICommonBlock >::Scope
Definition at line 793 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h