LLVM: llvm::OverlapStats Struct Reference
llvm::OverlapStats Struct Reference
#include "llvm/ProfileData/InstrProf.h"
Public Types
enum OverlapStatsLevel { ProgramLevel, FunctionLevel }
Public Member Functions
OverlapStats (OverlapStatsLevel L=ProgramLevel)
void dump (raw_fd_ostream &OS) const
void setFuncInfo (StringRef Name, uint64_t Hash)
Error accumulateCounts (const std::string &BaseFilename, const std::string &TestFilename, bool IsCS)
void addOneMismatch (const CountSumOrPercent &MismatchFunc)
void addOneUnique (const CountSumOrPercent &UniqueFunc)
Static Public Member Functions
static double score (uint64_t Val1, uint64_t Val2, double Sum1, double Sum2)
Public Attributes
CountSumOrPercent Base
CountSumOrPercent Test
CountSumOrPercent Overlap
CountSumOrPercent Mismatch
CountSumOrPercent Unique
OverlapStatsLevel Level
const std::string * BaseFilename
const std::string * TestFilename
StringRef FuncName
uint64_t FuncHash
bool Valid
Detailed Description
Definition at line 605 of file InstrProf.h.
Member Enumeration Documentation
OverlapStatsLevel
enum llvm::OverlapStats::OverlapStatsLevel
Enumerator
ProgramLevel
FunctionLevel
Definition at line 606 of file InstrProf.h.
Constructor & Destructor Documentation
OverlapStats()
llvm::OverlapStats::OverlapStats (OverlapStatsLevel L = ProgramLevel) inline
Definition at line 622 of file InstrProf.h.
References llvm::dump().
Member Function Documentation
accumulateCounts()
Error llvm::OverlapStats::accumulateCounts (const std::string & BaseFilename, const std::string & TestFilename, bool IsCS)
Definition at line 1167 of file InstrProf.cpp.
References llvm::InstrProfReader::create(), E, llvm::MipsISD::Ret, llvm::Error::success(), and llvm::Test.
addOneMismatch()
void llvm::OverlapStats::addOneMismatch (const CountSumOrPercent & MismatchFunc)
Definition at line 1192 of file InstrProf.cpp.
References llvm::CountSumOrPercent::CountSum, I, llvm::Test, and llvm::CountSumOrPercent::ValueCounts.
Referenced by llvm::InstrProfRecord::overlap(), and llvm::InstrProfWriter::overlapRecord().
addOneUnique()
void llvm::OverlapStats::addOneUnique (const CountSumOrPercent & UniqueFunc)
Definition at line 1202 of file InstrProf.cpp.
References llvm::CountSumOrPercent::CountSum, I, llvm::Test, and llvm::CountSumOrPercent::ValueCounts.
Referenced by llvm::InstrProfWriter::overlapRecord().
dump()
void llvm::OverlapStats::dump (raw_fd_ostream & OS) const
Definition at line 1211 of file InstrProf.cpp.
References llvm::format(), I, and llvm::Test.
score()
static double llvm::OverlapStats::score (uint64_t Val1, uint64_t Val2, double Sum1, double Sum2) inline static
Definition at line 638 of file InstrProf.h.
Referenced by llvm::InstrProfValueSiteRecord::overlap(), and llvm::InstrProfRecord::overlap().
setFuncInfo()
void llvm::OverlapStats::setFuncInfo (StringRef Name, uint64_t Hash) inline
Definition at line 628 of file InstrProf.h.
References Name.
Member Data Documentation
Base
CountSumOrPercent llvm::OverlapStats::Base
Definition at line 608 of file InstrProf.h.
Referenced by llvm::InstrProfValueSiteRecord::overlap(), and llvm::InstrProfRecord::overlap().
BaseFilename
const std::string* llvm::OverlapStats::BaseFilename
Definition at line 616 of file InstrProf.h.
FuncHash
uint64_t llvm::OverlapStats::FuncHash
Definition at line 619 of file InstrProf.h.
FuncName
StringRef llvm::OverlapStats::FuncName
Definition at line 618 of file InstrProf.h.
Level
OverlapStatsLevel llvm::OverlapStats::Level
Definition at line 615 of file InstrProf.h.
Mismatch
CountSumOrPercent llvm::OverlapStats::Mismatch
Definition at line 613 of file InstrProf.h.
Overlap
CountSumOrPercent llvm::OverlapStats::Overlap
Definition at line 612 of file InstrProf.h.
Referenced by llvm::InstrProfValueSiteRecord::overlap(), llvm::InstrProfRecord::overlap(), and llvm::InstrProfWriter::overlapRecord().
Test
CountSumOrPercent llvm::OverlapStats::Test
Definition at line 610 of file InstrProf.h.
Referenced by llvm::InstrProfValueSiteRecord::overlap(), llvm::InstrProfRecord::overlap(), and llvm::InstrProfWriter::overlapRecord().
TestFilename
const std::string* llvm::OverlapStats::TestFilename
Definition at line 617 of file InstrProf.h.
Unique
CountSumOrPercent llvm::OverlapStats::Unique
Definition at line 614 of file InstrProf.h.
Valid
bool llvm::OverlapStats::Valid
Definition at line 620 of file InstrProf.h.
Referenced by llvm::InstrProfRecord::overlap().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp