LLVM: llvm::DenseMapAPIntKeyInfo Struct Reference
llvm::DenseMapAPIntKeyInfo Struct Reference
#include "IR/LLVMContextImpl.h"
Static Public Member Functions
static APInt getEmptyKey ()
static APInt getTombstoneKey ()
static unsigned getHashValue (const APInt &Key)
static bool isEqual (const APInt &LHS, const APInt &RHS)
Detailed Description
Definition at line 62 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
static APInt llvm::DenseMapAPIntKeyInfo::getEmptyKey () inline static
Definition at line 63 of file LLVMContextImpl.h.
References llvm::APInt::VAL.
Referenced by llvm::AnonStructTypeKeyInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), and llvm::MDNodeInfo< NodeTy >::isEqual().
getHashValue()
static unsigned llvm::DenseMapAPIntKeyInfo::getHashValue (const APInt & Key) inline static
Definition at line 75 of file LLVMContextImpl.h.
References llvm::hash_value().
Referenced by llvm::AnonStructTypeKeyInfo::getHashValue(), and llvm::FunctionTypeKeyInfo::getHashValue().
getTombstoneKey()
static APInt llvm::DenseMapAPIntKeyInfo::getTombstoneKey () inline static
Definition at line 69 of file LLVMContextImpl.h.
References llvm::APInt::VAL.
Referenced by llvm::AnonStructTypeKeyInfo::isEqual(), llvm::FunctionTypeKeyInfo::isEqual(), and llvm::MDNodeInfo< NodeTy >::isEqual().
isEqual()
static bool llvm::DenseMapAPIntKeyInfo::isEqual (const APInt & LHS, const APInt & RHS) inline static
Definition at line 79 of file LLVMContextImpl.h.
References llvm::APInt::getBitWidth().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h