LLVM: llvm::MDNodeKeyImpl< DIGlobalVariableExpression > Struct Template Reference
llvm::MDNodeKeyImpl< DIGlobalVariableExpression > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Variable, Metadata *Expression)
MDNodeKeyImpl (const DIGlobalVariableExpression *N)
bool isKeyOf (const DIGlobalVariableExpression *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Variable
Metadata * Expression
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIGlobalVariableExpression >
Definition at line 1016 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::MDNodeKeyImpl (Metadata * Variable, Metadata * Expression) inline
Definition at line 1020 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::MDNodeKeyImpl (const DIGlobalVariableExpression * N) inline
Definition at line 1022 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::getHashValue () const inline
Definition at line 1030 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::isKeyOf (const DIGlobalVariableExpression * RHS) const inline
Definition at line 1025 of file LLVMContextImpl.h.
References llvm::DIGlobalVariableExpression::getRawExpression(), and llvm::DIGlobalVariableExpression::getRawVariable().
Member Data Documentation
Expression
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::Expression
Definition at line 1018 of file LLVMContextImpl.h.
Variable
Metadata* llvm::MDNodeKeyImpl< DIGlobalVariableExpression >::Variable
Definition at line 1017 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h