LLVM: llvm::RISCVRegisterInfo Struct Reference
llvm::RISCVRegisterInfo Struct Reference
#include "Target/RISCV/RISCVRegisterInfo.h"
Public Member Functions
RISCVRegisterInfo (unsigned HwMode)
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool isAsmClobberable (const MachineFunction &MF, unsigned PhysReg) const override
bool isConstantPhysReg (unsigned PhysReg) const override
const uint32_t * getNoPreservedMask () const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
Detailed Description
Definition at line 23 of file RISCVRegisterInfo.h.
Constructor & Destructor Documentation
RISCVRegisterInfo()
RISCVRegisterInfo::RISCVRegisterInfo (unsigned HwMode)
Definition at line 38 of file RISCVRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void RISCVRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 106 of file RISCVRegisterInfo.cpp.
References llvm::ISD::ADD, llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::isInt< 32 >(), llvm::RegState::Kill, MI, llvm::RISCVInstrInfo::movImm(), MRI, llvm::report_fatal_error(), and TII.
getCalleeSavedRegs()
const MCPhysReg * RISCVRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 43 of file RISCVRegisterInfo.cpp.
References llvm::RISCVABI::ABI_ILP32, llvm::RISCVABI::ABI_ILP32D, llvm::RISCVABI::ABI_ILP32F, llvm::RISCVABI::ABI_LP64, llvm::RISCVABI::ABI_LP64D, llvm::RISCVABI::ABI_LP64F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), and llvm_unreachable.
getCallPreservedMask()
const uint32_t * RISCVRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const override
Definition at line 156 of file RISCVRegisterInfo.cpp.
References llvm::RISCVABI::ABI_ILP32, llvm::RISCVABI::ABI_ILP32D, llvm::RISCVABI::ABI_ILP32F, llvm::RISCVABI::ABI_LP64, llvm::RISCVABI::ABI_LP64D, llvm::RISCVABI::ABI_LP64F, llvm::MachineFunction::getSubtarget(), and llvm_unreachable.
Referenced by CC_RISCV_FastCC().
getFrameRegister()
Register RISCVRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 150 of file RISCVRegisterInfo.cpp.
References llvm::TargetFrameLowering::hasFP().
getNoPreservedMask()
const uint32_t * RISCVRegisterInfo::getNoPreservedMask () const override
Definition at line 102 of file RISCVRegisterInfo.cpp.
getPointerRegClass()
const TargetRegisterClass* llvm::RISCVRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline override
Definition at line 59 of file RISCVRegisterInfo.h.
getReservedRegs()
BitVector RISCVRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 68 of file RISCVRegisterInfo.cpp.
References assert(), llvm::RISCVABI::getBPReg(), llvm::MachineFunction::getSubtarget(), llvm::RISCVFrameLowering::hasBP(), llvm::RISCVFrameLowering::hasFP(), llvm::RISCVSubtarget::isRegisterReservedByUser(), and Reg.
Referenced by llvm::RISCVTargetLowering::getRegisterByName().
isAsmClobberable()
bool RISCVRegisterInfo::isAsmClobberable (const MachineFunction & MF, unsigned PhysReg) const override
Definition at line 93 of file RISCVRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget().
isConstantPhysReg()
bool RISCVRegisterInfo::isConstantPhysReg (unsigned PhysReg) const override
Definition at line 98 of file RISCVRegisterInfo.cpp.
requiresFrameIndexScavenging()
bool llvm::RISCVRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 50 of file RISCVRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::RISCVRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 46 of file RISCVRegisterInfo.h.
trackLivenessAfterRegAlloc()
bool llvm::RISCVRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction &) const inline override
Definition at line 54 of file RISCVRegisterInfo.h.
The documentation for this struct was generated from the following files:
lib/Target/RISCV/RISCVRegisterInfo.h
lib/Target/RISCV/RISCVRegisterInfo.cpp