LLVM: llvm::DWARFDebugNames::Abbrev Struct Reference
llvm::DWARFDebugNames::Abbrev Struct Reference
Abbreviation describing the encoding of Name Index entries.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
Abbrev (uint32_t Code, dwarf::Tag Tag, std::vector< AttributeEncoding > Attributes)
void dump (ScopedPrinter &W) const
Public Attributes
uint32_t Code
Abbreviation code.
dwarf::Tag Tag
Dwarf Tag of the described entity.
std::vector< AttributeEncoding > Attributes
List of index attributes.
Detailed Description
Abbreviation describing the encoding of Name Index entries.
Definition at line 267 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
Abbrev()
llvm::DWARFDebugNames::Abbrev::Abbrev (uint32_t Code, dwarf::Tag Tag, std::vector< AttributeEncoding > Attributes) inline
Definition at line 272 of file DWARFAcceleratorTable.h.
References llvm::DWARFAcceleratorTable::dump(), and llvm::RISCVFenceField::W.
Member Function Documentation
dump()
void DWARFDebugNames::Abbrev::dump (ScopedPrinter & W) const
Definition at line 407 of file DWARFAcceleratorTable.cpp.
References llvm::formatv(), llvm::ScopedPrinter::startLine(), llvm::Tag, and llvm::Twine::utohexstr().
Referenced by llvm::DWARFDebugNames::NameIndex::getHashArrayEntry().
Member Data Documentation
Attributes
std::vector<AttributeEncoding> llvm::DWARFDebugNames::Abbrev::Attributes
List of index attributes.
Definition at line 270 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::Entry::dump(), llvm::DWARFDebugNames::NameIndex::extract(), and llvm::DWARFDebugNames::Entry::lookup().
Code
uint32_t llvm::DWARFDebugNames::Abbrev::Code
Abbreviation code.
Definition at line 268 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::Entry::dump(), isSentinel(), and llvm::DWARFDebugNames::SentinelError::log().
Tag
dwarf::Tag llvm::DWARFDebugNames::Abbrev::Tag
Dwarf Tag of the described entity.
Definition at line 269 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::Entry::dump(), and llvm::DWARFDebugNames::Entry::tag().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp