LLVM: llvm::VerifierSupport Struct Reference
llvm::VerifierSupport Struct Reference
Public Member Functions
VerifierSupport (raw_ostream *OS, const Module &M)
void CheckFailed (const Twine &Message)
A check failed, so printout out the condition and the message.
template<typename T1 , typename... Ts>
void CheckFailed (const Twine &Message, const T1 &V1, const Ts &... Vs)
A check failed (with values to print).
void DebugInfoCheckFailed (const Twine &Message)
A debug info check failed.
template<typename T1 , typename... Ts>
void DebugInfoCheckFailed (const Twine &Message, const T1 &V1, const Ts &... Vs)
A debug info check failed (with values to print).
Public Attributes
raw_ostream * OS
const Module & M
ModuleSlotTracker MST
Triple TT
const DataLayout & DL
LLVMContext & Context
bool Broken = false
Track the brokenness of the module while recursively visiting.
bool BrokenDebugInfo = false
Broken debug info can be "recovered" from by stripping the debug info.
bool TreatBrokenDebugInfoAsError = true
Whether to treat broken debug info as an error.
Detailed Description
Definition at line 120 of file Verifier.cpp.
Constructor & Destructor Documentation
VerifierSupport()
llvm::VerifierSupport::VerifierSupport (raw_ostream * OS, const Module & M) inline explicit
Definition at line 135 of file Verifier.cpp.
References C, llvm::MDTupleTypedArrayWrapper< T >::get(), llvm::Module::getModuleIdentifier(), llvm::Metadata::print(), llvm::Value::print(), llvm::NamedMDNode::print(), llvm::Value::printAsOperand(), llvm::T, and T1.
Referenced by DebugInfoCheckFailed().
Member Function Documentation
CheckFailed() [1/2]
void llvm::VerifierSupport::CheckFailed (const Twine & Message) inline
A check failed, so printout out the condition and the message.
This provides a nice place to put a breakpoint if you want to see why something is not correct.
Definition at line 215 of file Verifier.cpp.
References T1.
Referenced by CheckFailed(), forEachUser(), getParentPad(), isFuncOrArgAttr(), IsScalarTBAANodeImpl(), and llvm::TBAAVerifier::visitTBAAMetadata().
CheckFailed() [2/2]
template<typename T1 , typename... Ts> void llvm::VerifierSupport::CheckFailed (const Twine & Message, const T1 & V1, const Ts &... Vs) inline
A check failed (with values to print).
This calls the Message-only version so that the above is easier to set a breakpoint on.
Definition at line 226 of file Verifier.cpp.
References CheckFailed().
DebugInfoCheckFailed() [1/2]
void llvm::VerifierSupport::DebugInfoCheckFailed (const Twine & Message) inline
A debug info check failed.
Definition at line 233 of file Verifier.cpp.
References T1, and TreatBrokenDebugInfoAsError.
Referenced by DebugInfoCheckFailed().
DebugInfoCheckFailed() [2/2]
template<typename T1 , typename... Ts> void llvm::VerifierSupport::DebugInfoCheckFailed (const Twine & Message, const T1 & V1, const Ts &... Vs) inline
A debug info check failed (with values to print).
Definition at line 242 of file Verifier.cpp.
References A, assert(), Broken, BrokenDebugInfo, C, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), llvm::SmallPtrSetImplBase::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), DebugInfoCheckFailed(), llvm::Function::empty(), F(), llvm::Function::getIntrinsicID(), llvm::GlobalValue::getParent(), I, M, MST, N, OS, llvm::SmallVectorTemplateBase< T >::push_back(), TreatBrokenDebugInfoAsError, Verifier, VerifierSupport(), and llvm::verify().
Member Data Documentation
Broken
bool llvm::VerifierSupport::Broken = false
Track the brokenness of the module while recursively visiting.
Definition at line 129 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed(), and llvm::verifyModule().
BrokenDebugInfo
bool llvm::VerifierSupport::BrokenDebugInfo = false
Broken debug info can be "recovered" from by stripping the debug info.
Definition at line 131 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed().
Context
LLVMContext& llvm::VerifierSupport::Context
Definition at line 126 of file Verifier.cpp.
Referenced by forEachUser(), getSuccPad(), and isFuncOrArgAttr().
DL
const DataLayout& llvm::VerifierSupport::DL
Definition at line 125 of file Verifier.cpp.
Referenced by forEachUser(), getParentPad(), isContiguous(), and isFuncOrArgAttr().
M
const Module& llvm::VerifierSupport::M
Definition at line 122 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed(), forEachUser(), getParentPad(), isFuncOrArgAttr(), llvm::VerifierPass::run(), and llvm::verifyModule().
MST
ModuleSlotTracker llvm::VerifierSupport::MST
Definition at line 123 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed().
OS
raw_ostream* llvm::VerifierSupport::OS
Definition at line 121 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed().
TreatBrokenDebugInfoAsError
bool llvm::VerifierSupport::TreatBrokenDebugInfoAsError = true
Whether to treat broken debug info as an error.
Definition at line 133 of file Verifier.cpp.
Referenced by DebugInfoCheckFailed().
TT
Triple llvm::VerifierSupport::TT
Definition at line 124 of file Verifier.cpp.
The documentation for this struct was generated from the following file:
lib/IR/Verifier.cpp