LLVM: llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > > Struct Template Reference
llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > > Struct Template Reference
#include "llvm/ADT/PointerIntPair.h"
Public Types
enum { NumLowBitsAvailable = PtrTraits::NumLowBitsAvailable - IntBits }
Static Public Member Functions
static void * getAsVoidPointer (const PointerIntPair< PointerTy, IntBits, IntType > &P)
static PointerIntPair< PointerTy, IntBits, IntType > getFromVoidPointer (void *P)
static PointerIntPair< PointerTy, IntBits, IntType > getFromVoidPointer (const void *P)
Detailed Description
template<typename PointerTy, unsigned IntBits, typename IntType, typename PtrTraits>
struct llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >
Definition at line 221 of file PointerIntPair.h.
Member Enumeration Documentation
anonymous enum
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > anonymous enum
Enumerator
NumLowBitsAvailable
Definition at line 238 of file PointerIntPair.h.
Member Function Documentation
getAsVoidPointer()
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static void* llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getAsVoidPointer (const PointerIntPair< PointerTy, IntBits, IntType > & P) inline static
Definition at line 224 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getOpaqueValue().
getFromVoidPointer() [1/2]
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static PointerIntPair<PointerTy, IntBits, IntType> llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getFromVoidPointer (void * P) inline static
Definition at line 229 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getFromOpaqueValue().
getFromVoidPointer() [2/2]
template<typename PointerTy , unsigned IntBits, typename IntType , typename PtrTraits > static PointerIntPair<PointerTy, IntBits, IntType> llvm::PointerLikeTypeTraits< PointerIntPair< PointerTy, IntBits, IntType, PtrTraits > >::getFromVoidPointer (const void * P) inline static
Definition at line 234 of file PointerIntPair.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getFromOpaqueValue().
The documentation for this struct was generated from the following file:
include/llvm/ADT/PointerIntPair.h