LLVM: llvm::RegsForValue Struct Reference
llvm::RegsForValue Struct Reference
This struct represents the registers (physical or virtual) that a particular set of values is assigned, and the type information about the value.
#include "CodeGen/SelectionDAG/SelectionDAGBuilder.h"
Public Member Functions
RegsForValue ()=default
RegsForValue (const SmallVector< unsigned, 4 > &regs, MVT regvt, EVT valuevt, Optional< CallingConv::ID > CC=None)
RegsForValue (LLVMContext &Context, const TargetLowering &TLI, const DataLayout &DL, unsigned Reg, Type *Ty, Optional< CallingConv::ID > CC)
bool isABIMangled () const
void append (const RegsForValue &RHS)
Add the specified values to this one.
SDValue getCopyFromRegs (SelectionDAG &DAG, FunctionLoweringInfo &FuncInfo, const SDLoc &dl, SDValue &Chain, SDValue *Flag, const Value *V=nullptr) const
Emit a series of CopyFromReg nodes that copies from this value and returns the result as a ValueVTs value.
void getCopyToRegs (SDValue Val, SelectionDAG &DAG, const SDLoc &dl, SDValue &Chain, SDValue *Flag, const Value *V=nullptr, ISD::NodeType PreferredExtendType=ISD::ANY_EXTEND) const
Emit a series of CopyToReg nodes that copies the specified value into the registers specified by this object.
void AddInlineAsmOperands (unsigned Code, bool HasMatching, unsigned MatchingIdx, const SDLoc &dl, SelectionDAG &DAG, std::vector< SDValue > &Ops) const
Add this value to the specified inlineasm node operand list.
bool occupiesMultipleRegs () const
Check if the total RegCount is greater than one.
SmallVector< std::pair< unsigned, unsigned >, 4 > getRegsAndSizes () const
Return a list of registers and their sizes.
Public Attributes
SmallVector< EVT, 4 > ValueVTs
The value types of the values, which may not be legal, and may need be promoted or synthesized from one or more registers.
SmallVector< MVT, 4 > RegVTs
The value types of the registers.
SmallVector< unsigned, 4 > Regs
This list holds the registers assigned to the values.
SmallVector< unsigned, 4 > RegCount
This list holds the number of registers for each value.
Optional< CallingConv::ID > CallConv
Records if this value needs to be treated in an ABI dependant manner, different to normal type legalization.
Detailed Description
This struct represents the registers (physical or virtual) that a particular set of values is assigned, and the type information about the value.
The most common situation is to represent one value at a time, but struct or array values are handled element-wise as multiple values. The splitting of aggregates is performed recursively, so that we never have aggregate-typed registers. The values at this point do not necessarily have legal types, so each value may require one or more registers of some legal type.
Definition at line 832 of file SelectionDAGBuilder.h.
Constructor & Destructor Documentation
RegsForValue() [1/3]
llvm::RegsForValue::RegsForValue () default
Referenced by GetRegistersForValue().
RegsForValue() [2/3]
RegsForValue::RegsForValue (const SmallVector< unsigned, 4 > & regs, MVT regvt, EVT valuevt, Optional< CallingConv::ID > CC = None)
Definition at line 774 of file SelectionDAGBuilder.cpp.
RegsForValue() [3/3]
RegsForValue::RegsForValue (LLVMContext & Context, const TargetLowering & TLI, const DataLayout & DL, unsigned Reg, Type * Ty, Optional< CallingConv::ID > CC)
Definition at line 779 of file SelectionDAGBuilder.cpp.
References llvm::ComputeValueVTs(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getNumRegistersForCallingConv(), llvm::TargetLoweringBase::getRegisterType(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::Optional< T >::getValue(), isABIMangled(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), RegCount, Regs, RegVTs, and ValueVTs.
Member Function Documentation
AddInlineAsmOperands()
void RegsForValue::AddInlineAsmOperands (unsigned Code, bool HasMatching, unsigned MatchingIdx, const SDLoc & dl, SelectionDAG & DAG, std::vector< SDValue > & Ops) const
Add this value to the specified inlineasm node operand list.
This adds the code marker, matching input operand index (if applicable), and includes the number of values added into it.
Definition at line 946 of file SelectionDAGBuilder.cpp.
References assert(), llvm::numbers::e, E, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SelectionDAG::getContext(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterClass::getID(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getNumRegisters(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MachineFrameInfo::hasOpaqueSPAdjustment(), I, llvm::MVT::i32, llvm::Register::isVirtualRegister(), llvm::InlineAsm::Kind_Clobber, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, Regs, RegVTs, llvm::SmallVectorBase::size(), and ValueVTs.
append()
void llvm::RegsForValue::append (const RegsForValue & RHS) inline
Add the specified values to this one.
Definition at line 871 of file SelectionDAGBuilder.h.
References llvm::ISD::ANY_EXTEND, llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SelectionDAGBuilder::FuncInfo, llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Regs, RegVTs, llvm::SmallVectorBase::size(), and ValueVTs.
getCopyFromRegs()
SDValue RegsForValue::getCopyFromRegs (SelectionDAG & DAG, FunctionLoweringInfo & FuncInfo, const SDLoc & dl, SDValue & Chain, SDValue * Flag, const Value * V = nullptr) const
Emit a series of CopyFromReg nodes that copies from this value and returns the result as a ValueVTs value.
This uses Chain/Flag as the input and updates them for the output Chain/Flag. If the Flag pointer is NULL, no flag is used.
Definition at line 803 of file SelectionDAGBuilder.cpp.
References assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorTemplateCommon< T >::begin(), CallConv, llvm::SmallVectorImpl< T >::clear(), llvm::KnownBits::countMinLeadingZeros(), llvm::numbers::e, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getCopyFromParts(), llvm::SelectionDAG::getCopyFromReg(), llvm::EVT::getIntegerVT(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::Optional< T >::getValue(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getVTList(), isABIMangled(), llvm::MVT::isInteger(), llvm::Register::isVirtualRegister(), llvm::FunctionLoweringInfo::LiveOutInfo::Known, llvm::ISD::MERGE_VALUES, llvm::FunctionLoweringInfo::LiveOutInfo::NumSignBits, llvm::MVT::Other, P, RegCount, Regs, RegVTs, llvm::SmallVectorImpl< T >::resize(), and ValueVTs.
Referenced by llvm::SelectionDAGBuilder::getValue().
getCopyToRegs()
void RegsForValue::getCopyToRegs (SDValue Val, SelectionDAG & DAG, const SDLoc & dl, SDValue & Chain, SDValue * Flag, const Value * V = nullptr, ISD::NodeType PreferredExtendType = ISD::ANY_EXTEND) const
Emit a series of CopyToReg nodes that copies the specified value into the registers specified by this object.
This uses Chain/Flag as the input and updates them for the output Chain/Flag. If the Flag pointer is nullptr, no flag is used. If V is not nullptr, then it is used in printing better diagnostic messages on error.
Definition at line 890 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ANY_EXTEND, llvm::numbers::e, llvm::SelectionDAG::getContext(), getCopyToParts(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::SDValue::getResNo(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::Optional< T >::getValue(), isABIMangled(), llvm::TargetLoweringBase::isZExtFree(), llvm::MVT::Other, RegCount, Regs, RegVTs, llvm::SmallVectorBase::size(), llvm::ISD::TokenFactor, ValueVTs, and llvm::ISD::ZERO_EXTEND.
getRegsAndSizes()
SmallVector< std::pair< unsigned, unsigned >, 4 > RegsForValue::getRegsAndSizes () const
Return a list of registers and their sizes.
Definition at line 999 of file SelectionDAGBuilder.cpp.
References E, llvm::MVT::getSizeInBits(), I, llvm::SmallVectorTemplateBase< T >::push_back(), RegCount, Regs, RegVTs, and llvm::zip_first().
isABIMangled()
bool llvm::RegsForValue::isABIMangled () const inline
Definition at line 866 of file SelectionDAGBuilder.h.
References llvm::Optional< T >::hasValue().
Referenced by getCopyFromRegs(), getCopyToRegs(), and RegsForValue().
occupiesMultipleRegs()
bool llvm::RegsForValue::occupiesMultipleRegs () const inline
Check if the total RegCount is greater than one.
Definition at line 903 of file SelectionDAGBuilder.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Member Data Documentation
CallConv
Optional<CallingConv::ID> llvm::RegsForValue::CallConv
Records if this value needs to be treated in an ABI dependant manner, different to normal type legalization.
Definition at line 857 of file SelectionDAGBuilder.h.
Referenced by getCopyFromRegs().
RegCount
SmallVector<unsigned, 4> llvm::RegsForValue::RegCount
This list holds the number of registers for each value.
Definition at line 853 of file SelectionDAGBuilder.h.
Referenced by getCopyFromRegs(), getCopyToRegs(), getRegsAndSizes(), and RegsForValue().
Regs
SmallVector<unsigned, 4> llvm::RegsForValue::Regs
This list holds the registers assigned to the values.
Each legal or promoted value requires one register, and each expanded value requires multiple registers.
Definition at line 850 of file SelectionDAGBuilder.h.
Referenced by AddInlineAsmOperands(), append(), findMatchingInlineAsmOperand(), getCopyFromRegs(), getCopyToRegs(), GetRegistersForValue(), getRegsAndSizes(), getUnderlyingArgRegs(), and RegsForValue().
RegVTs
SmallVector<MVT, 4> llvm::RegsForValue::RegVTs
The value types of the registers.
This is the same size as ValueVTs and it records, for each value, what the type of the assigned register or registers are. (Individual values are never synthesized from more than one type of register.)
With virtual registers, the contents of RegVTs is redundant with TLI's getRegisterType member function, however when with physical registers it is necessary to have a separate record of the types.
Definition at line 845 of file SelectionDAGBuilder.h.
Referenced by AddInlineAsmOperands(), append(), getCopyFromRegs(), getCopyToRegs(), getRegsAndSizes(), and RegsForValue().
ValueVTs
SmallVector<EVT, 4> llvm::RegsForValue::ValueVTs
The value types of the values, which may not be legal, and may need be promoted or synthesized from one or more registers.
Definition at line 835 of file SelectionDAGBuilder.h.
Referenced by AddInlineAsmOperands(), addStackMapLiveVars(), append(), findMatchingInlineAsmOperand(), findUnwindDestinations(), FixedPointIntrinsicToOpcode(), getCopyFromRegs(), getCopyToRegs(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), RegsForValue(), tryToElideArgumentCopy(), and llvm::SelectionDAGBuilder::visitBitTestCase().
The documentation for this struct was generated from the following files:
lib/CodeGen/SelectionDAG/SelectionDAGBuilder.h
lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp