LLVM: llvm::CodeMetrics Struct Reference
llvm::CodeMetrics Struct Reference
Utility to calculate the size and a few similar metrics for a set of basic blocks.
#include "llvm/Analysis/CodeMetrics.h"
Public Member Functions
void analyzeBasicBlock (const BasicBlock *BB, const TargetTransformInfo &TTI, const SmallPtrSetImpl< const Value *> &EphValues)
Add information about a block to the current state.
Static Public Member Functions
static void collectEphemeralValues (const Loop *L, AssumptionCache *AC, SmallPtrSetImpl< const Value *> &EphValues)
Collect a loop's ephemeral values (those used only by an assume or similar intrinsics in the loop).
static void collectEphemeralValues (const Function *L, AssumptionCache *AC, SmallPtrSetImpl< const Value *> &EphValues)
Collect a functions's ephemeral values (those used only by an assume or similar intrinsics in the function).
Public Attributes
bool exposesReturnsTwice = false
True if this function contains a call to setjmp or other functions with attribute "returns twice" without having the attribute itself.
bool isRecursive = false
True if this function calls itself.
bool notDuplicatable = false
True if this function cannot be duplicated.
bool convergent = false
True if this function contains a call to a convergent function.
bool usesDynamicAlloca = false
True if this function calls alloca (in the C sense).
unsigned NumInsts = false
Number of instructions in the analyzed blocks.
unsigned NumBlocks = false
Number of analyzed blocks.
DenseMap< const BasicBlock *, unsigned > NumBBInsts
Keeps track of basic block code size estimates.
unsigned NumCalls = false
Keep track of the number of calls to 'big' functions.
unsigned NumInlineCandidates = 0
The number of calls to internal functions with a single caller.
unsigned NumVectorInsts = 0
How many instructions produce vector values.
unsigned NumRets = 0
How many 'ret' instructions the blocks contain.
Detailed Description
Utility to calculate the size and a few similar metrics for a set of basic blocks.
Definition at line 32 of file CodeMetrics.h.
Member Function Documentation
analyzeBasicBlock()
void CodeMetrics::analyzeBasicBlock (const BasicBlock * BB, const TargetTransformInfo & TTI, const SmallPtrSetImpl< const Value *> & EphValues)
Add information about a block to the current state.
Fill in the current structure with information gleaned from the specified block.
Definition at line 116 of file CodeMetrics.cpp.
References convergent, llvm::SmallPtrSetImpl< PtrType >::count(), F(), llvm::TargetTransformInfo::getUserCost(), I, llvm::TargetTransformInfo::isLoweredToCall(), isRecursive, notDuplicatable, NumBBInsts, NumBlocks, NumCalls, NumInlineCandidates, NumInsts, NumRets, NumVectorInsts, and usesDynamicAlloca.
Referenced by llvm::ApproximateLoopSize(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::LoopDataPrefetchPass::run(), and shouldRotateLoopExitingLatch().
collectEphemeralValues() [1/2]
void CodeMetrics::collectEphemeralValues (const Loop * L, AssumptionCache * AC, SmallPtrSetImpl< const Value *> & EphValues) static
Collect a loop's ephemeral values (those used only by an assume or similar intrinsics in the loop).
Definition at line 70 of file CodeMetrics.cpp.
References appendSpeculatableOperands(), llvm::AssumptionCache::assumptions(), completeEphemeralValues(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::Instruction::getParent(), I, and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::slpvectorizer::BoUpSLP::BoUpSLP(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::IVUsers::IVUsers(), llvm::LoopDataPrefetchPass::run(), shouldRotateLoopExitingLatch(), tryToUnrollAndJamLoop(), and tryToUnrollLoop().
collectEphemeralValues() [2/2]
void CodeMetrics::collectEphemeralValues (const Function * L, AssumptionCache * AC, SmallPtrSetImpl< const Value *> & EphValues) static
Collect a functions's ephemeral values (those used only by an assume or similar intrinsics in the function).
Definition at line 94 of file CodeMetrics.cpp.
References appendSpeculatableOperands(), assert(), llvm::AssumptionCache::assumptions(), completeEphemeralValues(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), I, and llvm::SmallPtrSetImpl< PtrType >::insert().
Member Data Documentation
convergent
bool llvm::CodeMetrics::convergent = false
True if this function contains a call to a convergent function.
Definition at line 47 of file CodeMetrics.h.
Referenced by analyzeBasicBlock(), llvm::ApproximateLoopSize(), and shouldRotateLoopExitingLatch().
exposesReturnsTwice
bool llvm::CodeMetrics::exposesReturnsTwice = false
True if this function contains a call to setjmp or other functions with attribute "returns twice" without having the attribute itself.
Definition at line 35 of file CodeMetrics.h.
isRecursive
bool llvm::CodeMetrics::isRecursive = false
True if this function calls itself.
Definition at line 38 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
notDuplicatable
bool llvm::CodeMetrics::notDuplicatable = false
True if this function cannot be duplicated.
True if this function contains one or more indirect branches, or it contains one or more 'noduplicate' instructions.
Definition at line 44 of file CodeMetrics.h.
Referenced by analyzeBasicBlock(), llvm::ApproximateLoopSize(), and shouldRotateLoopExitingLatch().
NumBBInsts
DenseMap<const BasicBlock *, unsigned> llvm::CodeMetrics::NumBBInsts
Keeps track of basic block code size estimates.
Definition at line 59 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
NumBlocks
unsigned llvm::CodeMetrics::NumBlocks = false
Number of analyzed blocks.
Definition at line 56 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
NumCalls
unsigned llvm::CodeMetrics::NumCalls = false
Keep track of the number of calls to 'big' functions.
Definition at line 62 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
NumInlineCandidates
unsigned llvm::CodeMetrics::NumInlineCandidates = 0
The number of calls to internal functions with a single caller.
These are likely targets for future inlining, likely exposed by interleaved devirtualization.
Definition at line 68 of file CodeMetrics.h.
Referenced by analyzeBasicBlock(), and llvm::ApproximateLoopSize().
NumInsts
unsigned llvm::CodeMetrics::NumInsts = false
Number of instructions in the analyzed blocks.
Definition at line 53 of file CodeMetrics.h.
Referenced by analyzeBasicBlock(), llvm::ApproximateLoopSize(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::LoopDataPrefetchPass::run(), and shouldRotateLoopExitingLatch().
NumRets
unsigned llvm::CodeMetrics::NumRets = 0
How many 'ret' instructions the blocks contain.
Definition at line 76 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
NumVectorInsts
unsigned llvm::CodeMetrics::NumVectorInsts = 0
How many instructions produce vector values.
The inliner is more aggressive with inlining vector kernels.
Definition at line 73 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
usesDynamicAlloca
bool llvm::CodeMetrics::usesDynamicAlloca = false
True if this function calls alloca (in the C sense).
Definition at line 50 of file CodeMetrics.h.
Referenced by analyzeBasicBlock().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/CodeMetrics.h
lib/Analysis/CodeMetrics.cpp