LLVM: llvm::format_provider< llvm::json::Value > Struct Template Reference
llvm::format_provider< llvm::json::Value > Struct Template Reference
Allow printing json::Value with formatv().
#include "llvm/Support/JSON.h"
Static Public Member Functions
static void format (const llvm::json::Value &, raw_ostream &, StringRef)
Detailed Description
template<>
struct llvm::format_provider< llvm::json::Value >
Allow printing json::Value with formatv().
The default style is basic/compact formatting, like operator<<. A format string like formatv("{0:2}", Value) pretty-prints with indent 2.
Definition at line 855 of file JSON.h.
Member Function Documentation
format()
void llvm::format_provider< llvm::json::Value >::format (const llvm::json::Value & E, raw_ostream & OS, StringRef Options) static
Definition at line 711 of file JSON.cpp.
References llvm::StringRef::empty(), llvm::StringRef::getAsInteger(), llvm_unreachable, and llvm::json::OStream::value().
The documentation for this struct was generated from the following files:
include/llvm/Support/JSON.h
lib/Support/JSON.cpp