LLVM: llvm::AMDGPU::HSAMD::Metadata Struct Reference
llvm::AMDGPU::HSAMD::Metadata Struct Reference final
In-memory representation of HSA metadata.
#include "llvm/Support/AMDGPUMetadata.h"
Public Member Functions
Metadata ()=default
Default constructor.
Public Attributes
std::vector< uint32_t > mVersion = std::vector<uint32_t>()
HSA metadata version. Required.
std::vector< std::string > mPrintf = std::vector<std::string>()
Printf metadata. Optional.
std::vector< Kernel::Metadata > mKernels = std::vector<Kernel::Metadata>()
Kernels metadata. Required.
Detailed Description
In-memory representation of HSA metadata.
Definition at line 421 of file AMDGPUMetadata.h.
Constructor & Destructor Documentation
Metadata()
llvm::AMDGPU::HSAMD::Metadata::Metadata () default
Default constructor.
Member Data Documentation
mKernels
std::vector<Kernel::Metadata> llvm::AMDGPU::HSAMD::Metadata::mKernels = std::vector<Kernel::Metadata>()
Kernels metadata. Required.
Definition at line 427 of file AMDGPUMetadata.h.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), and llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping().
mPrintf
std::vector<std::string> llvm::AMDGPU::HSAMD::Metadata::mPrintf = std::vector<std::string>()
Printf metadata. Optional.
Definition at line 425 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping().
mVersion
std::vector<uint32_t> llvm::AMDGPU::HSAMD::Metadata::mVersion = std::vector<uint32_t>()
HSA metadata version. Required.
Definition at line 423 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< HSAMD::Metadata >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/Support/AMDGPUMetadata.h