LLVM: llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord > Struct Template Reference
llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord > Struct Template Reference
#include "llvm/DebugInfo/CodeView/DebugSubsectionRecord.h"
Public Member Functions
Error operator() (BinaryStreamRef Stream, uint32_t &Length, codeview::DebugSubsectionRecord &Info)
Detailed Description
template<>
struct llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >
Definition at line 80 of file DebugSubsectionRecord.h.
Member Function Documentation
operator()()
Error llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator() (BinaryStreamRef Stream, uint32_t & Length, codeview::DebugSubsectionRecord & Info) inline
Definition at line 81 of file DebugSubsectionRecord.h.
References llvm::alignTo(), llvm::codeview::EC, llvm::codeview::DebugSubsectionRecord::getRecordLength(), llvm::codeview::DebugSubsectionRecord::initialize(), llvm::codeview::Pdb, and llvm::Error::success().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/CodeView/DebugSubsectionRecord.h