LLVM: llvm::TimeTraceScope Struct Reference
llvm::TimeTraceScope Struct Reference
The TimeTraceScope is a helper class to call the begin and end functions of the time trace profiler.
#include "llvm/Support/TimeProfiler.h"
Public Member Functions
TimeTraceScope ()=delete
TimeTraceScope (const TimeTraceScope &)=delete
TimeTraceScope & operator= (const TimeTraceScope &)=delete
TimeTraceScope (TimeTraceScope &&)=delete
TimeTraceScope & operator= (TimeTraceScope &&)=delete
TimeTraceScope (StringRef Name)
TimeTraceScope (StringRef Name, StringRef Detail)
TimeTraceScope (StringRef Name, llvm::function_ref< std::string()> Detail)
~TimeTraceScope ()
Detailed Description
The TimeTraceScope is a helper class to call the begin and end functions of the time trace profiler.
When the object is constructed, it begins the section; and when it is destroyed, it stops it. If the time profiler is not initialized, the overhead is a single branch.
Definition at line 53 of file TimeProfiler.h.
Constructor & Destructor Documentation
TimeTraceScope() [1/6]
llvm::TimeTraceScope::TimeTraceScope () delete
TimeTraceScope() [2/6]
llvm::TimeTraceScope::TimeTraceScope (const TimeTraceScope &) delete
TimeTraceScope() [3/6]
llvm::TimeTraceScope::TimeTraceScope (TimeTraceScope &&) delete
TimeTraceScope() [4/6]
llvm::TimeTraceScope::TimeTraceScope (StringRef Name) inline
Definition at line 61 of file TimeProfiler.h.
References llvm::timeTraceProfilerBegin().
TimeTraceScope() [5/6]
llvm::TimeTraceScope::TimeTraceScope (StringRef Name, StringRef Detail) inline
Definition at line 65 of file TimeProfiler.h.
References llvm::timeTraceProfilerBegin().
TimeTraceScope() [6/6]
llvm::TimeTraceScope::TimeTraceScope (StringRef Name, llvm::function_ref< std::string()> Detail) inline
Definition at line 69 of file TimeProfiler.h.
References llvm::timeTraceProfilerBegin().
~TimeTraceScope()
llvm::TimeTraceScope::~TimeTraceScope () inline
Definition at line 73 of file TimeProfiler.h.
References llvm::timeTraceProfilerEnd().
Member Function Documentation
operator=() [1/2]
TimeTraceScope& llvm::TimeTraceScope::operator= (const TimeTraceScope &) delete
operator=() [2/2]
TimeTraceScope& llvm::TimeTraceScope::operator= (TimeTraceScope &&) delete
The documentation for this struct was generated from the following file:
include/llvm/Support/TimeProfiler.h