LLVM: llvm::BitTracker::MachineEvaluator Struct Reference
llvm::BitTracker::MachineEvaluator Struct Reference abstract
#include "Target/Hexagon/BitTracker.h"
Public Member Functions
MachineEvaluator (const TargetRegisterInfo &T, MachineRegisterInfo &M)
virtual ~MachineEvaluator ()=default
uint16_t getRegBitWidth (const RegisterRef &RR) const
RegisterCell getCell (const RegisterRef &RR, const CellMapType &M) const
void putCell (const RegisterRef &RR, RegisterCell RC, CellMapType &M) const
RegisterCell getRef (const RegisterRef &RR, const CellMapType &M) const
bool isInt (const RegisterCell &A) const
uint64_t toInt (const RegisterCell &A) const
RegisterCell eIMM (int64_t V, uint16_t W) const
RegisterCell eIMM (const ConstantInt *CI) const
RegisterCell eADD (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eSUB (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eMLS (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eMLU (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eASL (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eLSR (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eASR (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eAND (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eORL (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eXOR (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eNOT (const RegisterCell &A1) const
RegisterCell eSET (const RegisterCell &A1, uint16_t BitN) const
RegisterCell eCLR (const RegisterCell &A1, uint16_t BitN) const
RegisterCell eCLB (const RegisterCell &A1, bool B, uint16_t W) const
RegisterCell eCTB (const RegisterCell &A1, bool B, uint16_t W) const
RegisterCell eSXT (const RegisterCell &A1, uint16_t FromN) const
RegisterCell eZXT (const RegisterCell &A1, uint16_t FromN) const
RegisterCell eXTR (const RegisterCell &A1, uint16_t B, uint16_t E) const
RegisterCell eINS (const RegisterCell &A1, const RegisterCell &A2, uint16_t AtN) const
virtual BitMask mask (unsigned Reg, unsigned Sub) const
virtual bool track (const TargetRegisterClass *RC) const
virtual bool evaluate (const MachineInstr &MI, const CellMapType &Inputs, CellMapType &Outputs) const
virtual bool evaluate (const MachineInstr &BI, const CellMapType &Inputs, BranchTargetList &Targets, bool &FallsThru) const =0
virtual const TargetRegisterClass & composeWithSubRegIndex (const TargetRegisterClass &RC, unsigned Idx) const
virtual uint16_t getPhysRegBitWidth (unsigned Reg) const
Public Attributes
const TargetRegisterInfo & TRI
MachineRegisterInfo & MRI
Detailed Description
Definition at line 391 of file BitTracker.h.
Constructor & Destructor Documentation
MachineEvaluator()
llvm::BitTracker::MachineEvaluator::MachineEvaluator (const TargetRegisterInfo & T, MachineRegisterInfo & M) inline
Definition at line 392 of file BitTracker.h.
References llvm::AMDGPU::getRegBitWidth(), and MRI.
~MachineEvaluator()
virtual llvm::BitTracker::MachineEvaluator::~MachineEvaluator () virtual default
Member Function Documentation
composeWithSubRegIndex()
virtual const TargetRegisterClass& llvm::BitTracker::MachineEvaluator::composeWithSubRegIndex (const TargetRegisterClass & RC, unsigned Idx) const inline virtual
Reimplemented in llvm::HexagonEvaluator.
Definition at line 481 of file BitTracker.h.
References llvm_unreachable.
Referenced by getRegBitWidth().
eADD()
BT::RegisterCell BT::MachineEvaluator::eADD (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 432 of file BitTracker.cpp.
References assert(), I, llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::num(), llvm::BitTracker::BitValue::ref(), llvm::BitTracker::BitValue::self(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eAND()
BT::RegisterCell BT::MachineEvaluator::eAND (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 548 of file BitTracker.cpp.
References assert(), llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::ref(), llvm::BitTracker::BitValue::self(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eASL()
BT::RegisterCell BT::MachineEvaluator::eASL (const RegisterCell & A1, uint16_t Sh) const
Definition at line 518 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::ref(), llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eASR()
BT::RegisterCell BT::MachineEvaluator::eASR (const RegisterCell & A1, uint16_t Sh) const
Definition at line 537 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::RegisterCell::ref(), llvm::BitTracker::RegisterCell::rol(), llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eCLB()
BT::RegisterCell BT::MachineEvaluator::eCLB (const RegisterCell & A1, bool B, uint16_t W) const
Definition at line 643 of file BitTracker.cpp.
References C, llvm::BitTracker::RegisterCell::cl(), eIMM(), llvm::BitTracker::RegisterCell::self(), and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eCLR()
BT::RegisterCell BT::MachineEvaluator::eCLR (const RegisterCell & A1, uint16_t BitN) const
Definition at line 635 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::ref(), llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
eCTB()
BT::RegisterCell BT::MachineEvaluator::eCTB (const RegisterCell & A1, bool B, uint16_t W) const
Definition at line 653 of file BitTracker.cpp.
References C, llvm::BitTracker::RegisterCell::ct(), eIMM(), llvm::BitTracker::RegisterCell::self(), and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eIMM() [1/2]
BT::RegisterCell BT::MachineEvaluator::eIMM (int64_t V, uint16_t W) const
Definition at line 412 of file BitTracker.cpp.
References llvm::RISCVFenceField::W.
Referenced by eCLB(), eCTB(), and llvm::HexagonEvaluator::evaluate().
eIMM() [2/2]
BT::RegisterCell BT::MachineEvaluator::eIMM (const ConstantInt * CI) const
Definition at line 422 of file BitTracker.cpp.
References assert(), llvm::APInt::getBitWidth(), and llvm::ConstantInt::getValue().
eINS()
BT::RegisterCell BT::MachineEvaluator::eINS (const RegisterCell & A1, const RegisterCell & A2, uint16_t AtN) const
Definition at line 695 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::insert(), llvm::BitTracker::RegisterCell::ref(), and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eLSR()
BT::RegisterCell BT::MachineEvaluator::eLSR (const RegisterCell & A1, uint16_t Sh) const
Definition at line 527 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::RegisterCell::ref(), llvm::BitTracker::RegisterCell::rol(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eMLS()
BT::RegisterCell BT::MachineEvaluator::eMLS (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 498 of file BitTracker.cpp.
References llvm::BitTracker::RegisterCell::ct(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::BitValue::self(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), llvm::Z, and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eMLU()
BT::RegisterCell BT::MachineEvaluator::eMLU (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 508 of file BitTracker.cpp.
References llvm::BitTracker::RegisterCell::ct(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::BitValue::self(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), llvm::Z, and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eNOT()
BT::RegisterCell BT::MachineEvaluator::eNOT (const RegisterCell & A1) const
Definition at line 612 of file BitTracker.cpp.
References llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::One, llvm::BitTracker::BitValue::self(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eORL()
BT::RegisterCell BT::MachineEvaluator::eORL (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 570 of file BitTracker.cpp.
References assert(), llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::One, llvm::BitTracker::BitValue::ref(), llvm::BitTracker::BitValue::self(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eSET()
BT::RegisterCell BT::MachineEvaluator::eSET (const RegisterCell & A1, uint16_t BitN) const
Definition at line 627 of file BitTracker.cpp.
References assert(), llvm::BitTracker::BitValue::One, llvm::BitTracker::RegisterCell::ref(), and llvm::BitTracker::RegisterCell::width().
eSUB()
BT::RegisterCell BT::MachineEvaluator::eSUB (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 465 of file BitTracker.cpp.
References assert(), I, llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::num(), llvm::BitTracker::BitValue::ref(), llvm::BitTracker::BitValue::self(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eSXT()
BT::RegisterCell BT::MachineEvaluator::eSXT (const RegisterCell & A1, uint16_t FromN) const
Definition at line 663 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::RegisterCell::ref(), llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
evaluate() [1/2]
bool BT::MachineEvaluator::evaluate (const MachineInstr & MI, const CellMapType & Inputs, CellMapType & Outputs) const virtual
Reimplemented in llvm::HexagonEvaluator.
Definition at line 720 of file BitTracker.cpp.
References assert(), B, D, llvm::dbgs(), E, F(), llvm::BitTracker::RegisterCell::fill(), getCell(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), getRegBitWidth(), I, llvm::BitTracker::RegisterCell::insert(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isDebugInstr(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::Register::isVirtualRegister(), mask(), llvm::BitTracker::RegisterCell::meet(), MI, llvm::MachineInstr::operands(), P, llvm::printMBBReference(), llvm::printReg(), putCell(), llvm::BitTracker::BitValue::Ref, llvm::BitTracker::RegisterCell::ref(), llvm::BitTracker::BitValue::RefI, llvm::BitTracker::BitRef::Reg, llvm::BitTracker::RegisterRef::Reg, llvm::BitTracker::RegisterCell::self(), llvm::X86AS::SS, llvm::ARM_MB::ST, llvm::BitTracker::RegisterRef::Sub, llvm::BitTracker::BitValue::Type, llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
evaluate() [2/2]
virtual bool llvm::BitTracker::MachineEvaluator::evaluate (const MachineInstr & BI, const CellMapType & Inputs, BranchTargetList & Targets, bool & FallsThru) const pure virtual
Implemented in llvm::HexagonEvaluator.
eXOR()
BT::RegisterCell BT::MachineEvaluator::eXOR (const RegisterCell & A1, const RegisterCell & A2) const
Definition at line 592 of file BitTracker.cpp.
References assert(), llvm::BitTracker::BitValue::is(), llvm::BitTracker::BitValue::ref(), llvm::BitTracker::BitValue::self(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
eXTR()
BT::RegisterCell BT::MachineEvaluator::eXTR (const RegisterCell & A1, uint16_t B, uint16_t E) const
Definition at line 683 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::extract(), llvm::BitTracker::RegisterCell::ref(), llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by llvm::HexagonEvaluator::evaluate().
eZXT()
BT::RegisterCell BT::MachineEvaluator::eZXT (const RegisterCell & A1, uint16_t FromN) const
Definition at line 674 of file BitTracker.cpp.
References assert(), llvm::BitTracker::RegisterCell::fill(), llvm::BitTracker::RegisterCell::ref(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), and llvm::BitTracker::BitValue::Zero.
Referenced by llvm::HexagonEvaluator::evaluate().
getCell()
BT::RegisterCell BT::MachineEvaluator::getCell (const RegisterRef & RR, const CellMapType & M) const
Definition at line 348 of file BitTracker.cpp.
References assert(), C, F(), getRegBitWidth(), llvm::MachineRegisterInfo::getRegClass(), llvm::Register::isPhysicalRegister(), llvm::Register::isVirtualRegister(), mask(), MRI, llvm::BitTracker::RegisterRef::Reg, llvm::BitTracker::RegisterCell::self(), llvm::BitTracker::RegisterRef::Sub, llvm::BitTracker::RegisterCell::top(), and track().
Referenced by llvm::HexagonEvaluator::evaluate(), and evaluate().
getPhysRegBitWidth()
uint16_t BT::MachineEvaluator::getPhysRegBitWidth (unsigned Reg) const virtual
Reimplemented in llvm::HexagonEvaluator.
Definition at line 714 of file BitTracker.cpp.
References assert(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::Register::isPhysicalRegister(), and TRI.
Referenced by getRegBitWidth().
getRef()
RegisterCell llvm::BitTracker::MachineEvaluator::getRef (const RegisterRef & RR, const CellMapType & M) const inline
Definition at line 404 of file BitTracker.h.
References B, E, llvm::isInt(), llvm::BitTracker::RegisterCell::ref(), Reg, and llvm::RISCVFenceField::W.
getRegBitWidth()
uint16_t BT::MachineEvaluator::getRegBitWidth (const RegisterRef & RR) const
Definition at line 329 of file BitTracker.cpp.
References assert(), composeWithSubRegIndex(), getPhysRegBitWidth(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::TargetRegisterInfo::getSubReg(), llvm::Register::isPhysicalRegister(), llvm::Register::isVirtualRegister(), MRI, llvm::BitTracker::RegisterRef::Reg, Register, llvm::BitTracker::RegisterRef::Sub, TRI, and llvm::AArch64CC::VC.
Referenced by llvm::HexagonEvaluator::evaluate(), evaluate(), getCell(), llvm::HexagonEvaluator::mask(), and mask().
isInt()
bool BT::MachineEvaluator::isInt (const RegisterCell & A) const
Definition at line 388 of file BitTracker.cpp.
References llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
Referenced by toInt().
mask()
BT::BitMask BT::MachineEvaluator::mask (unsigned Reg, unsigned Sub) const virtual
Reimplemented in llvm::HexagonEvaluator.
Definition at line 707 of file BitTracker.cpp.
References assert(), getRegBitWidth(), and llvm::RISCVFenceField::W.
Referenced by evaluate(), and getCell().
putCell()
void BT::MachineEvaluator::putCell (const RegisterRef & RR, RegisterCell RC, CellMapType & M) const
Definition at line 375 of file BitTracker.cpp.
References assert(), llvm::Register::isVirtualRegister(), llvm::BitTracker::RegisterRef::Reg, llvm::BitTracker::RegisterCell::regify(), and llvm::BitTracker::RegisterRef::Sub.
Referenced by llvm::HexagonEvaluator::evaluate(), and evaluate().
toInt()
uint64_t BT::MachineEvaluator::toInt (const RegisterCell & A) const
Definition at line 397 of file BitTracker.cpp.
References assert(), isInt(), llvm::RISCVFenceField::W, and llvm::BitTracker::RegisterCell::width().
track()
virtual bool llvm::BitTracker::MachineEvaluator::track (const TargetRegisterClass * RC) const inline virtual
Definition at line 466 of file BitTracker.h.
References MI.
Referenced by getCell().
Member Data Documentation
MRI
MachineRegisterInfo& llvm::BitTracker::MachineEvaluator::MRI
Definition at line 490 of file BitTracker.h.
Referenced by llvm::HexagonEvaluator::evaluate(), getCell(), getRegBitWidth(), and llvm::HexagonEvaluator::mask().
TRI
const TargetRegisterInfo& llvm::BitTracker::MachineEvaluator::TRI
Definition at line 489 of file BitTracker.h.
Referenced by llvm::HexagonEvaluator::composeWithSubRegIndex(), llvm::HexagonEvaluator::getPhysRegBitWidth(), getPhysRegBitWidth(), getRegBitWidth(), and llvm::HexagonEvaluator::mask().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/BitTracker.h
lib/Target/Hexagon/BitTracker.cpp