LLVM: llvm::yaml::ScalarTraits< FixedSizeHex< N > > Struct Template Reference
llvm::yaml::ScalarTraits< FixedSizeHex< N > > Struct Template Reference
Static Public Member Functions
static void output (const FixedSizeHex< N > &Fixed, void *, raw_ostream &OS)
static StringRef input (StringRef Scalar, void *, FixedSizeHex< N > &Fixed)
static QuotingType mustQuote (StringRef S)
Detailed Description
template<std::size_t N>
struct llvm::yaml::ScalarTraits< FixedSizeHex< N > >
Definition at line 179 of file MinidumpYAML.cpp.
Member Function Documentation
input()
template<std::size_t N> static StringRef llvm::yaml::ScalarTraits< FixedSizeHex< N > >::input (StringRef Scalar, void * , FixedSizeHex< N > & Fixed) inline static
Definition at line 184 of file MinidumpYAML.cpp.
References llvm::all_of(), llvm::copy(), llvm::fromHex(), llvm::isHexDigit(), N, and llvm::StringRef::size().
mustQuote()
template<std::size_t N> static QuotingType llvm::yaml::ScalarTraits< FixedSizeHex< N > >::mustQuote (StringRef S) inline static
Definition at line 195 of file MinidumpYAML.cpp.
References N, llvm::None, and llvm::minidump::CPUInfo::OtherInfo::ProcessorFeatures.
output()
template<std::size_t N> static void llvm::yaml::ScalarTraits< FixedSizeHex< N > >::output (const FixedSizeHex< N > & Fixed, void * , raw_ostream & OS) inline static
Definition at line 180 of file MinidumpYAML.cpp.
References llvm::makeArrayRef(), and llvm::toHex().
The documentation for this struct was generated from the following file:
lib/ObjectYAML/MinidumpYAML.cpp