LLVM: llvm::GraphTraits< const VPBlockBase * > Struct Template Reference
llvm::GraphTraits< const VPBlockBase * > Struct Template Reference
#include "Transforms/Vectorize/VPlan.h"
Public Types
using NodeRef = const VPBlockBase *
using ChildIteratorType = SmallVectorImpl< VPBlockBase * >::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<>
struct llvm::GraphTraits< const VPBlockBase * >
Definition at line 1246 of file VPlan.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< const VPBlockBase * >::ChildIteratorType = SmallVectorImpl<VPBlockBase *>::const_iterator
Definition at line 1248 of file VPlan.h.
NodeRef
using llvm::GraphTraits< const VPBlockBase * >::NodeRef = const VPBlockBase *
Definition at line 1247 of file VPlan.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< const VPBlockBase * >::child_begin (NodeRef N) inline static
Definition at line 1252 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::VPBlockBase::getSuccessors().
child_end()
static ChildIteratorType llvm::GraphTraits< const VPBlockBase * >::child_end (NodeRef N) inline static
Definition at line 1256 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::VPBlockBase::getSuccessors().
getEntryNode()
static NodeRef llvm::GraphTraits< const VPBlockBase * >::getEntryNode (NodeRef N) inline static
Definition at line 1250 of file VPlan.h.
References N.
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h