LLVM: llvm::object::XCOFFRelocation32 Struct Reference
llvm::object::XCOFFRelocation32 Struct Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
bool isRelocationSigned () const
bool isFixupIndicated () const
uint8_t getRelocatedLength () const
Public Attributes
support::ubig32_t VirtualAddress
support::ubig32_t SymbolIndex
uint8_t Info
XCOFF::RelocationType Type
Static Public Attributes
static constexpr uint8_t XR_SIGN_INDICATOR_MASK = 0x80
static constexpr uint8_t XR_FIXUP_INDICATOR_MASK = 0x40
static constexpr uint8_t XR_BIASED_LENGTH_MASK = 0x3f
Detailed Description
Definition at line 167 of file XCOFFObjectFile.h.
Member Function Documentation
getRelocatedLength()
uint8_t llvm::object::XCOFFRelocation32::getRelocatedLength () const
Definition at line 72 of file XCOFFObjectFile.cpp.
References assert(), Info, is64Bit(), llvm::object::DataRefImpl::p, llvm::Ref, llvm::report_fatal_error(), and XR_BIASED_LENGTH_MASK.
isFixupIndicated()
bool llvm::object::XCOFFRelocation32::isFixupIndicated () const
Definition at line 68 of file XCOFFObjectFile.cpp.
References Info, and XR_FIXUP_INDICATOR_MASK.
isRelocationSigned()
bool llvm::object::XCOFFRelocation32::isRelocationSigned () const
Definition at line 64 of file XCOFFObjectFile.cpp.
References Info, and XR_SIGN_INDICATOR_MASK.
Member Data Documentation
Info
uint8_t llvm::object::XCOFFRelocation32::Info
Definition at line 187 of file XCOFFObjectFile.h.
Referenced by getRelocatedLength(), isFixupIndicated(), and isRelocationSigned().
SymbolIndex
support::ubig32_t llvm::object::XCOFFRelocation32::SymbolIndex
Definition at line 184 of file XCOFFObjectFile.h.
Type
XCOFF::RelocationType llvm::object::XCOFFRelocation32::Type
Definition at line 189 of file XCOFFObjectFile.h.
VirtualAddress
support::ubig32_t llvm::object::XCOFFRelocation32::VirtualAddress
Definition at line 183 of file XCOFFObjectFile.h.
XR_BIASED_LENGTH_MASK
constexpr uint8_t llvm::object::XCOFFRelocation32::XR_BIASED_LENGTH_MASK = 0x3f static
Definition at line 180 of file XCOFFObjectFile.h.
Referenced by getRelocatedLength().
XR_FIXUP_INDICATOR_MASK
constexpr uint8_t llvm::object::XCOFFRelocation32::XR_FIXUP_INDICATOR_MASK = 0x40 static
Definition at line 176 of file XCOFFObjectFile.h.
Referenced by isFixupIndicated().
XR_SIGN_INDICATOR_MASK
constexpr uint8_t llvm::object::XCOFFRelocation32::XR_SIGN_INDICATOR_MASK = 0x80 static
Definition at line 172 of file XCOFFObjectFile.h.
Referenced by isRelocationSigned().
The documentation for this struct was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp