LLVM: llvm::HexagonEvaluator Struct Reference
llvm::HexagonEvaluator Struct Reference
#include "Target/Hexagon/HexagonBitTracker.h"
Public Types
using CellMapType = BitTracker::CellMapType
using RegisterRef = BitTracker::RegisterRef
using RegisterCell = BitTracker::RegisterCell
using BranchTargetList = BitTracker::BranchTargetList
Public Member Functions
HexagonEvaluator (const HexagonRegisterInfo &tri, MachineRegisterInfo &mri, const HexagonInstrInfo &tii, MachineFunction &mf)
bool evaluate (const MachineInstr &MI, const CellMapType &Inputs, CellMapType &Outputs) const override
bool evaluate (const MachineInstr &BI, const CellMapType &Inputs, BranchTargetList &Targets, bool &FallsThru) const override
BitTracker::BitMask mask (unsigned Reg, unsigned Sub) const override
uint16_t getPhysRegBitWidth (unsigned Reg) const override
const TargetRegisterClass & composeWithSubRegIndex (const TargetRegisterClass &RC, unsigned Idx) const override
Public Member Functions inherited from llvm::BitTracker::MachineEvaluator
MachineEvaluator (const TargetRegisterInfo &T, MachineRegisterInfo &M)
virtual ~MachineEvaluator ()=default
uint16_t getRegBitWidth (const RegisterRef &RR) const
RegisterCell getCell (const RegisterRef &RR, const CellMapType &M) const
void putCell (const RegisterRef &RR, RegisterCell RC, CellMapType &M) const
RegisterCell getRef (const RegisterRef &RR, const CellMapType &M) const
bool isInt (const RegisterCell &A) const
uint64_t toInt (const RegisterCell &A) const
RegisterCell eIMM (int64_t V, uint16_t W) const
RegisterCell eIMM (const ConstantInt *CI) const
RegisterCell eADD (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eSUB (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eMLS (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eMLU (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eASL (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eLSR (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eASR (const RegisterCell &A1, uint16_t Sh) const
RegisterCell eAND (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eORL (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eXOR (const RegisterCell &A1, const RegisterCell &A2) const
RegisterCell eNOT (const RegisterCell &A1) const
RegisterCell eSET (const RegisterCell &A1, uint16_t BitN) const
RegisterCell eCLR (const RegisterCell &A1, uint16_t BitN) const
RegisterCell eCLB (const RegisterCell &A1, bool B, uint16_t W) const
RegisterCell eCTB (const RegisterCell &A1, bool B, uint16_t W) const
RegisterCell eSXT (const RegisterCell &A1, uint16_t FromN) const
RegisterCell eZXT (const RegisterCell &A1, uint16_t FromN) const
RegisterCell eXTR (const RegisterCell &A1, uint16_t B, uint16_t E) const
RegisterCell eINS (const RegisterCell &A1, const RegisterCell &A2, uint16_t AtN) const
virtual bool track (const TargetRegisterClass *RC) const
Public Attributes
MachineFunction & MF
MachineFrameInfo & MFI
const HexagonInstrInfo & TII
Public Attributes inherited from llvm::BitTracker::MachineEvaluator
const TargetRegisterInfo & TRI
MachineRegisterInfo & MRI
Detailed Description
Definition at line 25 of file HexagonBitTracker.h.
Member Typedef Documentation
BranchTargetList
using llvm::HexagonEvaluator::BranchTargetList = BitTracker::BranchTargetList
Definition at line 29 of file HexagonBitTracker.h.
CellMapType
using llvm::HexagonEvaluator::CellMapType = BitTracker::CellMapType
Definition at line 26 of file HexagonBitTracker.h.
RegisterCell
using llvm::HexagonEvaluator::RegisterCell = BitTracker::RegisterCell
Definition at line 28 of file HexagonBitTracker.h.
RegisterRef
using llvm::HexagonEvaluator::RegisterRef = BitTracker::RegisterRef
Definition at line 27 of file HexagonBitTracker.h.
Constructor & Destructor Documentation
HexagonEvaluator()
HexagonEvaluator::HexagonEvaluator (const HexagonRegisterInfo & tri, MachineRegisterInfo & mri, const HexagonInstrInfo & tii, MachineFunction & mf)
Definition at line 40 of file HexagonBitTracker.cpp.
References Arg, llvm::Function::args(), llvm::MachineFunction::getFunction(), llvm::Type::getIntegerBitWidth(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), and MF.
Member Function Documentation
composeWithSubRegIndex()
const TargetRegisterClass & HexagonEvaluator::composeWithSubRegIndex (const TargetRegisterClass & RC, unsigned Idx) const override virtual
Reimplemented from llvm::BitTracker::MachineEvaluator.
Definition at line 132 of file HexagonBitTracker.cpp.
References assert(), llvm::dbgs(), llvm::TargetRegisterClass::getID(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isReg(), llvm_unreachable, MI, llvm::Hexagon::ps_sub_hi, llvm::Hexagon::ps_sub_lo, llvm::size(), llvm::BitTracker::MachineEvaluator::TRI, and llvm::Vector.
evaluate() [1/2]
bool HexagonEvaluator::evaluate (const MachineInstr & MI, const CellMapType & Inputs, CellMapType & Outputs) const override virtual
Reimplemented from llvm::BitTracker::MachineEvaluator.
Definition at line 187 of file HexagonBitTracker.cpp.
References llvm::abs(), assert(), llvm::BitTracker::RegisterCell::cat(), llvm::HexagonISD::CONST32, llvm::countTrailingZeros(), llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), llvm::BitTracker::MachineEvaluator::eASL(), llvm::BitTracker::MachineEvaluator::eASR(), llvm::BitTracker::MachineEvaluator::eCLB(), llvm::BitTracker::MachineEvaluator::eCTB(), llvm::BitTracker::MachineEvaluator::eIMM(), llvm::BitTracker::MachineEvaluator::eINS(), llvm::BitTracker::MachineEvaluator::eLSR(), llvm::BitTracker::MachineEvaluator::eMLS(), llvm::BitTracker::MachineEvaluator::eMLU(), llvm::BitTracker::MachineEvaluator::eNOT(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::BitTracker::MachineEvaluator::eSXT(), llvm::BitTracker::MachineEvaluator::eXOR(), llvm::MipsISD::Ext, llvm::BitTracker::MachineEvaluator::eXTR(), llvm::BitTracker::MachineEvaluator::eZXT(), F(), llvm::BitTracker::RegisterCell::fill(), llvm::MachineOperand::getImm(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineInstr::getOpcode(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::MachineRegisterInfo::getRegClass(), I, im, llvm::BitTracker::RegisterCell::insert(), llvm::BitTracker::BitValue::is(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoad(), llvm::BitTracker::RegisterCell::meet(), MFI, MI, llvm::BitTracker::MachineEvaluator::MRI, N, llvm::BitTracker::BitValue::One, op, llvm::MachineInstr::operands(), llvm::X86II::PD, llvm::BitTracker::MachineEvaluator::putCell(), R2, rc, llvm::BitTracker::RegisterCell::ref(), Reg, llvm::NVPTX::PTXCvtMode::RZ, llvm::BitTracker::BitValue::self(), llvm::BitTracker::RegisterCell::self(), llvm::RISCVFenceField::W, llvm::BitTracker::RegisterCell::width(), llvm::SystemZISD::XC, and llvm::BitTracker::BitValue::Zero.
evaluate() [2/2]
bool HexagonEvaluator::evaluate (const MachineInstr & BI, const CellMapType & Inputs, BranchTargetList & Targets, bool & FallsThru) const override virtual
Implements llvm::BitTracker::MachineEvaluator.
Definition at line 982 of file HexagonBitTracker.cpp.
References assert(), llvm::BitTracker::MachineEvaluator::eSXT(), llvm::BitTracker::MachineEvaluator::eZXT(), F(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::SetVector< T, Vector, Set >::insert(), llvm::BitTracker::BitValue::is(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDef(), llvm::Register::isPhysicalRegister(), llvm::HexagonInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::Register::isVirtualRegister(), llvm::MachineRegisterInfo::liveins(), LLVM_FALLTHROUGH, llvm::MachineInstr::mayLoad(), MI, llvm::BitTracker::MachineEvaluator::MRI, llvm::MachineInstr::operands(), P, llvm::BitTracker::MachineEvaluator::putCell(), R2, R4, llvm::BitTracker::BitValue::ref(), llvm::BitTracker::RegisterRef::Reg, llvm::BitTracker::BitValue::self(), llvm::Test, TII, llvm::RISCVFenceField::W, and llvm::BitTracker::BitValue::Zero.
getPhysRegBitWidth()
uint16_t HexagonEvaluator::getPhysRegBitWidth (unsigned Reg) const override virtual
Reimplemented from llvm::BitTracker::MachineEvaluator.
Definition at line 113 of file HexagonBitTracker.cpp.
References assert(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MCRegisterInfo::getName(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::Register::isPhysicalRegister(), llvm_unreachable, MF, and llvm::BitTracker::MachineEvaluator::TRI.
mask()
BT::BitMask HexagonEvaluator::mask (unsigned Reg, unsigned Sub) const override virtual
Reimplemented from llvm::BitTracker::MachineEvaluator.
Definition at line 89 of file HexagonBitTracker.cpp.
References llvm::dbgs(), llvm::TargetRegisterClass::getID(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm_unreachable, llvm::BitTracker::MachineEvaluator::MRI, llvm::printReg(), llvm::Hexagon::ps_sub_lo, and llvm::BitTracker::MachineEvaluator::TRI.
Member Data Documentation
MF
MachineFunction& llvm::HexagonEvaluator::MF
Definition at line 46 of file HexagonBitTracker.h.
Referenced by getPhysRegBitWidth(), and HexagonEvaluator().
MFI
MachineFrameInfo& llvm::HexagonEvaluator::MFI
Definition at line 47 of file HexagonBitTracker.h.
Referenced by evaluate().
TII
const HexagonInstrInfo& llvm::HexagonEvaluator::TII
Definition at line 48 of file HexagonBitTracker.h.
Referenced by evaluate().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonBitTracker.h
lib/Target/Hexagon/HexagonBitTracker.cpp