LLVM: llvm::IRAttributeManifest Struct Reference
llvm::IRAttributeManifest Struct Reference
Helper struct necessary as the modular build fails if the virtual method IRAttribute::manifest is defined in the Attributor.cpp.
#include "llvm/Transforms/IPO/Attributor.h"
Static Public Member Functions
static ChangeStatus manifestAttrs (Attributor &A, const IRPosition &IRP, const ArrayRef< Attribute > &DeducedAttrs)
Detailed Description
Helper struct necessary as the modular build fails if the virtual method IRAttribute::manifest is defined in the Attributor.cpp.
Definition at line 1619 of file Attributor.h.
Member Function Documentation
manifestAttrs()
ChangeStatus IRAttributeManifest::manifestAttrs (Attributor & A, const IRPosition & IRP, const ArrayRef< Attribute > & DeducedAttrs) static
Definition at line 423 of file Attributor.cpp.
References addIfNotExistent(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::CHANGED, llvm::IRPosition::EmptyKey, llvm::IRPosition::getAnchorValue(), llvm::IRPosition::getAssociatedFunction(), llvm::Intrinsic::getAttributes(), llvm::Function::getAttributes(), llvm::IRPosition::getAttrIdx(), llvm::Value::getContext(), llvm::IRPosition::getPositionKind(), llvm::IRPosition::IRP_ARGUMENT, llvm::IRPosition::IRP_CALL_SITE, llvm::IRPosition::IRP_CALL_SITE_ARGUMENT, llvm::IRPosition::IRP_CALL_SITE_RETURNED, llvm::IRPosition::IRP_FLOAT, llvm::IRPosition::IRP_FUNCTION, llvm::IRPosition::IRP_INVALID, llvm::IRPosition::IRP_RETURNED, llvm::Function::setAttributes(), llvm::IRPosition::TombstoneKey, and llvm::UNCHANGED.
Referenced by llvm::IRAttribute< Attribute::Returned, AbstractAttribute >::manifest().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp