LLVM: llvm::resource_sort Struct Reference
llvm::resource_sort Struct Reference
Sorting functions for the Available queue.
#include "llvm/CodeGen/ResourcePriorityQueue.h"
Public Member Functions
resource_sort (ResourcePriorityQueue *pq)
bool operator() (const SUnit *LHS, const SUnit *RHS) const
This heuristic is used if DFA scheduling is not desired for some VLIW platform.
Public Attributes
ResourcePriorityQueue * PQ
Detailed Description
Sorting functions for the Available queue.
Definition at line 30 of file ResourcePriorityQueue.h.
Constructor & Destructor Documentation
resource_sort()
llvm::resource_sort::resource_sort (ResourcePriorityQueue * pq) inline explicit
Definition at line 32 of file ResourcePriorityQueue.h.
References operator()().
Member Function Documentation
operator()()
bool resource_sort::operator() (const SUnit * LHS, const SUnit * RHS) const
This heuristic is used if DFA scheduling is not desired for some VLIW platform.
Definition at line 176 of file ResourcePriorityQueue.cpp.
References llvm::SDep::getSUnit(), llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, llvm::SUnit::NodeNum, and llvm::SUnit::Preds.
Referenced by resource_sort().
Member Data Documentation
PQ
ResourcePriorityQueue* llvm::resource_sort::PQ
Definition at line 31 of file ResourcePriorityQueue.h.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/ResourcePriorityQueue.h
lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp