LLVM: llvm::MipsABIFlagsSection Struct Reference
llvm::MipsABIFlagsSection Struct Reference
#include "Target/Mips/MCTargetDesc/MipsABIFlagsSection.h"
Public Types
enum FpABIKind {
FpABIKind::ANY, FpABIKind::XX, FpABIKind::S32, FpABIKind::S64,
FpABIKind::SOFT
}
Public Member Functions
MipsABIFlagsSection ()=default
uint16_t getVersionValue ()
uint8_t getISALevelValue ()
uint8_t getISARevisionValue ()
uint8_t getGPRSizeValue ()
uint8_t getCPR1SizeValue ()
uint8_t getCPR2SizeValue ()
uint8_t getFpABIValue ()
uint32_t getISAExtensionValue ()
uint32_t getASESetValue ()
uint32_t getFlags1Value ()
uint32_t getFlags2Value ()
FpABIKind getFpABI ()
void setFpABI (FpABIKind Value, bool IsABI32Bit)
StringRef getFpABIString (FpABIKind Value)
template<class PredicateLibrary >
void setISALevelAndRevisionFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setGPRSizeFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setCPR1SizeFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setISAExtensionFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setASESetFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setFpAbiFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary >
void setAllFromPredicates (const PredicateLibrary &P)
Public Attributes
uint16_t Version = 0
uint8_t ISALevel = 0
uint8_t ISARevision = 0
Mips::AFL_REG GPRSize = Mips::AFL_REG_NONE
Mips::AFL_REG CPR1Size = Mips::AFL_REG_NONE
Mips::AFL_REG CPR2Size = Mips::AFL_REG_NONE
Mips::AFL_EXT ISAExtension = Mips::AFL_EXT_NONE
uint32_t ASESet = 0
bool OddSPReg = false
bool Is32BitABI = false
Protected Attributes
FpABIKind FpABI = FpABIKind::ANY
Detailed Description
Definition at line 21 of file MipsABIFlagsSection.h.
Member Enumeration Documentation
FpABIKind
enum llvm::MipsABIFlagsSection::FpABIKind strong
Enumerator
ANY
XX
S32
S64
SOFT
Definition at line 23 of file MipsABIFlagsSection.h.
Constructor & Destructor Documentation
MipsABIFlagsSection()
llvm::MipsABIFlagsSection::MipsABIFlagsSection () default
Member Function Documentation
getASESetValue()
uint32_t llvm::MipsABIFlagsSection::getASESetValue () inline
Definition at line 61 of file MipsABIFlagsSection.h.
References ASESet.
Referenced by llvm::operator<<().
getCPR1SizeValue()
uint8_t MipsABIFlagsSection::getCPR1SizeValue ()
Definition at line 50 of file MipsABIFlagsSection.cpp.
References llvm::Mips::AFL_REG_32, CPR1Size, FpABI, and XX.
Referenced by getGPRSizeValue(), and llvm::operator<<().
getCPR2SizeValue()
uint8_t llvm::MipsABIFlagsSection::getCPR2SizeValue () inline
Definition at line 58 of file MipsABIFlagsSection.h.
References CPR2Size, and getFpABIValue().
Referenced by llvm::operator<<().
getFlags1Value()
uint32_t llvm::MipsABIFlagsSection::getFlags1Value () inline
Definition at line 63 of file MipsABIFlagsSection.h.
References llvm::Mips::AFL_FLAGS1_ODDSPREG.
Referenced by llvm::operator<<().
getFlags2Value()
uint32_t llvm::MipsABIFlagsSection::getFlags2Value () inline
Definition at line 72 of file MipsABIFlagsSection.h.
Referenced by llvm::operator<<().
getFpABI()
FpABIKind llvm::MipsABIFlagsSection::getFpABI () inline
Definition at line 74 of file MipsABIFlagsSection.h.
References FpABI.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleFP().
getFpABIString()
StringRef MipsABIFlagsSection::getFpABIString (FpABIKind Value)
Definition at line 37 of file MipsABIFlagsSection.cpp.
References llvm_unreachable, S32, S64, and XX.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleFP(), llvm::MipsTargetAsmStreamer::emitDirectiveSetFp(), and setFpABI().
getFpABIValue()
uint8_t MipsABIFlagsSection::getFpABIValue ()
Definition at line 17 of file MipsABIFlagsSection.cpp.
References ANY, FpABI, Is32BitABI, llvm_unreachable, OddSPReg, S32, S64, SOFT, llvm::Mips::Val_GNU_MIPS_ABI_FP_64, llvm::Mips::Val_GNU_MIPS_ABI_FP_64A, llvm::Mips::Val_GNU_MIPS_ABI_FP_ANY, llvm::Mips::Val_GNU_MIPS_ABI_FP_DOUBLE, llvm::Mips::Val_GNU_MIPS_ABI_FP_SOFT, llvm::Mips::Val_GNU_MIPS_ABI_FP_XX, and XX.
Referenced by getCPR2SizeValue(), and llvm::operator<<().
getGPRSizeValue()
uint8_t llvm::MipsABIFlagsSection::getGPRSizeValue () inline
Definition at line 56 of file MipsABIFlagsSection.h.
References getCPR1SizeValue(), and GPRSize.
Referenced by llvm::operator<<().
getISAExtensionValue()
uint32_t llvm::MipsABIFlagsSection::getISAExtensionValue () inline
Definition at line 60 of file MipsABIFlagsSection.h.
References ISAExtension.
Referenced by llvm::operator<<().
getISALevelValue()
uint8_t llvm::MipsABIFlagsSection::getISALevelValue () inline
Definition at line 54 of file MipsABIFlagsSection.h.
References ISALevel.
Referenced by llvm::operator<<().
getISARevisionValue()
uint8_t llvm::MipsABIFlagsSection::getISARevisionValue () inline
Definition at line 55 of file MipsABIFlagsSection.h.
References ISARevision.
Referenced by llvm::operator<<().
getVersionValue()
uint16_t llvm::MipsABIFlagsSection::getVersionValue () inline
Definition at line 53 of file MipsABIFlagsSection.h.
References Version.
Referenced by llvm::operator<<().
setAllFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setAllFromPredicates (const PredicateLibrary & P) inline
Definition at line 193 of file MipsABIFlagsSection.h.
References llvm::operator<<(), setASESetFromPredicates(), setCPR1SizeFromPredicates(), setFpAbiFromPredicates(), setGPRSizeFromPredicates(), setISAExtensionFromPredicates(), and setISALevelAndRevisionFromPredicates().
Referenced by llvm::MipsTargetStreamer::updateABIInfo().
setASESetFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setASESetFromPredicates (const PredicateLibrary & P) inline
Definition at line 151 of file MipsABIFlagsSection.h.
References llvm::Mips::AFL_ASE_CRC, llvm::Mips::AFL_ASE_DSP, llvm::Mips::AFL_ASE_DSPR2, llvm::Mips::AFL_ASE_GINV, llvm::Mips::AFL_ASE_MICROMIPS, llvm::Mips::AFL_ASE_MIPS16, llvm::Mips::AFL_ASE_MSA, llvm::Mips::AFL_ASE_MT, and llvm::Mips::AFL_ASE_VIRT.
Referenced by setAllFromPredicates().
setCPR1SizeFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setCPR1SizeFromPredicates (const PredicateLibrary & P) inline
Definition at line 131 of file MipsABIFlagsSection.h.
References llvm::Mips::AFL_REG_128, llvm::Mips::AFL_REG_32, llvm::Mips::AFL_REG_64, and llvm::Mips::AFL_REG_NONE.
Referenced by setAllFromPredicates().
setFpABI()
void llvm::MipsABIFlagsSection::setFpABI (FpABIKind Value, bool IsABI32Bit) inline
Definition at line 75 of file MipsABIFlagsSection.h.
References getFpABIString().
setFpAbiFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setFpAbiFromPredicates (const PredicateLibrary & P) inline
Definition at line 174 of file MipsABIFlagsSection.h.
References ANY, S32, S64, SOFT, and XX.
Referenced by setAllFromPredicates().
setGPRSizeFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setGPRSizeFromPredicates (const PredicateLibrary & P) inline
Definition at line 126 of file MipsABIFlagsSection.h.
References llvm::Mips::AFL_REG_32, and llvm::Mips::AFL_REG_64.
Referenced by setAllFromPredicates().
setISAExtensionFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setISAExtensionFromPredicates (const PredicateLibrary & P) inline
Definition at line 141 of file MipsABIFlagsSection.h.
References llvm::Mips::AFL_EXT_NONE, llvm::Mips::AFL_EXT_OCTEON, and llvm::Mips::AFL_EXT_OCTEONP.
Referenced by setAllFromPredicates().
setISALevelAndRevisionFromPredicates()
template<class PredicateLibrary > void llvm::MipsABIFlagsSection::setISALevelAndRevisionFromPredicates (const PredicateLibrary & P) inline
Definition at line 83 of file MipsABIFlagsSection.h.
References llvm_unreachable.
Referenced by setAllFromPredicates().
Member Data Documentation
ASESet
uint32_t llvm::MipsABIFlagsSection::ASESet = 0
Definition at line 40 of file MipsABIFlagsSection.h.
Referenced by getASESetValue().
CPR1Size
Mips::AFL_REG llvm::MipsABIFlagsSection::CPR1Size = Mips::AFL_REG_NONE
Definition at line 34 of file MipsABIFlagsSection.h.
Referenced by getCPR1SizeValue().
CPR2Size
Mips::AFL_REG llvm::MipsABIFlagsSection::CPR2Size = Mips::AFL_REG_NONE
Definition at line 36 of file MipsABIFlagsSection.h.
Referenced by getCPR2SizeValue().
FpABI
FpABIKind llvm::MipsABIFlagsSection::FpABI = FpABIKind::ANY protected
Definition at line 48 of file MipsABIFlagsSection.h.
Referenced by getCPR1SizeValue(), getFpABI(), and getFpABIValue().
GPRSize
Mips::AFL_REG llvm::MipsABIFlagsSection::GPRSize = Mips::AFL_REG_NONE
Definition at line 32 of file MipsABIFlagsSection.h.
Referenced by getGPRSizeValue().
Is32BitABI
bool llvm::MipsABIFlagsSection::Is32BitABI = false
Definition at line 44 of file MipsABIFlagsSection.h.
Referenced by llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), and getFpABIValue().
ISAExtension
Mips::AFL_EXT llvm::MipsABIFlagsSection::ISAExtension = Mips::AFL_EXT_NONE
Definition at line 38 of file MipsABIFlagsSection.h.
Referenced by getISAExtensionValue().
ISALevel
uint8_t llvm::MipsABIFlagsSection::ISALevel = 0
Definition at line 28 of file MipsABIFlagsSection.h.
Referenced by getISALevelValue().
ISARevision
uint8_t llvm::MipsABIFlagsSection::ISARevision = 0
Definition at line 30 of file MipsABIFlagsSection.h.
Referenced by getISARevisionValue().
OddSPReg
bool llvm::MipsABIFlagsSection::OddSPReg = false
Definition at line 42 of file MipsABIFlagsSection.h.
Referenced by llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg(), and getFpABIValue().
Version
uint16_t llvm::MipsABIFlagsSection::Version = 0
Definition at line 26 of file MipsABIFlagsSection.h.
Referenced by getVersionValue().
The documentation for this struct was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsABIFlagsSection.h
lib/Target/Mips/MCTargetDesc/MipsABIFlagsSection.cpp