LLVM: llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable > Struct Template Reference
llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
BinaryOp_match (const LHS_P &LHS, const RHS_P &RHS)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
LHS_P L
RHS_P R
Detailed Description
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false>
struct llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >
Definition at line 173 of file MIPatternMatch.h.
Constructor & Destructor Documentation
BinaryOp_match()
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false> llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::BinaryOp_match (const LHS_P & LHS, const RHS_P & RHS) inline
Definition at line 177 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false> template<typename OpTy > bool llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 179 of file MIPatternMatch.h.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MIPatternMatch::m_MInstr(), and llvm::MIPatternMatch::mi_match().
Member Data Documentation
L
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false> LHS_P llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::L
Definition at line 174 of file MIPatternMatch.h.
R
template<typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false> RHS_P llvm::MIPatternMatch::BinaryOp_match< LHS_P, RHS_P, Opcode, Commutable >::R
Definition at line 175 of file MIPatternMatch.h.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h