LLVM: llvm::PerTargetMIParsingState Struct Reference
llvm::PerTargetMIParsingState Struct Reference
#include "llvm/CodeGen/MIRParser/MIParser.h"
Public Member Functions
bool parseInstrName (StringRef InstrName, unsigned &OpCode)
Try to convert an instruction name to an opcode.
bool getRegisterByName (StringRef RegName, unsigned &Reg)
Try to convert a register name to a register number.
const uint32_t * getRegMask (StringRef Identifier)
Check if the given identifier is a name of a register mask.
unsigned getSubRegIndex (StringRef Name)
Check if the given identifier is a name of a subregister index.
bool getTargetIndex (StringRef Name, int &Index)
Try to convert a name of target index to the corresponding target index.
bool getDirectTargetFlag (StringRef Name, unsigned &Flag)
Try to convert a name of a direct target flag to the corresponding target flag.
bool getBitmaskTargetFlag (StringRef Name, unsigned &Flag)
Try to convert a name of a bitmask target flag to the corresponding target flag.
bool getMMOTargetFlag (StringRef Name, MachineMemOperand::Flags &Flag)
Try to convert a name of a MachineMemOperand target flag to the corresponding target flag.
const TargetRegisterClass * getRegClass (StringRef Name)
Check if the given identifier is a name of a register class.
const RegisterBank * getRegBank (StringRef Name)
Check if the given identifier is a name of a register bank.
PerTargetMIParsingState (const TargetSubtargetInfo &STI)
~PerTargetMIParsingState ()=default
void setTarget (const TargetSubtargetInfo &NewSubtarget)
Detailed Description
Definition at line 50 of file MIParser.h.
Constructor & Destructor Documentation
PerTargetMIParsingState()
llvm::PerTargetMIParsingState::PerTargetMIParsingState (const TargetSubtargetInfo & STI) inline
Definition at line 148 of file MIParser.h.
~PerTargetMIParsingState()
llvm::PerTargetMIParsingState::~PerTargetMIParsingState () default
Member Function Documentation
getBitmaskTargetFlag()
bool PerTargetMIParsingState::getBitmaskTargetFlag (StringRef Name, unsigned & Flag)
Try to convert a name of a bitmask target flag to the corresponding target flag.
Return true if the name isn't a name of a bitmask target flag.
Definition at line 244 of file MIParser.cpp.
References assert(), llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getInstrInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TII.
Referenced by parseGlobalValue().
getDirectTargetFlag()
bool PerTargetMIParsingState::getDirectTargetFlag (StringRef Name, unsigned & Flag)
Try to convert a name of a direct target flag to the corresponding target flag.
Return true if the name isn't a name of a direct flag.
Definition at line 222 of file MIParser.cpp.
References assert(), llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::HexagonInstrInfo::getSerializableBitmaskMachineOperandTargetFlags(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TII.
Referenced by parseGlobalValue().
getMMOTargetFlag()
bool PerTargetMIParsingState::getMMOTargetFlag (StringRef Name, MachineMemOperand::Flags & Flag)
Try to convert a name of a MachineMemOperand target flag to the corresponding target flag.
Return true if the name isn't a name of a target MMO flag.
Definition at line 265 of file MIParser.cpp.
References E, llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::RegisterBankInfo::getNumRegBanks(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::RegisterBankInfo::getRegBank(), llvm::TargetSubtargetInfo::getRegBankInfo(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::TargetSubtargetInfo::getRegisterInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TRI.
Referenced by parseIRValue().
getRegBank()
const RegisterBank * PerTargetMIParsingState::getRegBank (StringRef Name)
Check if the given identifier is a name of a register bank.
Return null if the name isn't a register bank.
Definition at line 312 of file MIParser.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), and llvm::StringMap< ValueTy, AllocatorTy >::find().
Referenced by isImplicitOperandIn().
getRegClass()
const TargetRegisterClass * PerTargetMIParsingState::getRegClass (StringRef Name)
Check if the given identifier is a name of a register class.
Return null if the name isn't a register class.
Definition at line 305 of file MIParser.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), and llvm::StringMap< ValueTy, AllocatorTy >::find().
Referenced by isImplicitOperandIn().
getRegisterByName()
bool PerTargetMIParsingState::getRegisterByName (StringRef RegName, unsigned & Reg)
Try to convert a register name to a register number.
Return true if the register name is invalid.
Definition at line 124 of file MIParser.cpp.
References assert(), E, llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getInstrInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TII.
Referenced by isImplicitOperandIn().
getRegMask()
const uint32_t * PerTargetMIParsingState::getRegMask (StringRef Identifier)
Check if the given identifier is a name of a register mask.
Return null if the identifier isn't a register mask.
Definition at line 166 of file MIParser.cpp.
References E, llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::MCRegisterInfo::getNumSubRegIndices(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getSubRegIndexName(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TRI.
Referenced by parseGlobalValue().
getSubRegIndex()
unsigned PerTargetMIParsingState::getSubRegIndex (StringRef Name)
Check if the given identifier is a name of a subregister index.
Return 0 if the name isn't a subregister index class.
Definition at line 183 of file MIParser.cpp.
References assert(), llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getInstrInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TII.
Referenced by isImplicitOperandIn(), and parseGlobalValue().
getTargetIndex()
bool PerTargetMIParsingState::getTargetIndex (StringRef Name, int & Index)
Try to convert a name of target index to the corresponding target index.
Return true if the name isn't a name of a target index.
Definition at line 201 of file MIParser.cpp.
References assert(), llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::HexagonInstrInfo::getSerializableDirectMachineOperandTargetFlags(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TII.
Referenced by parseGlobalValue().
parseInstrName()
bool PerTargetMIParsingState::parseInstrName (StringRef InstrName, unsigned & OpCode)
Try to convert an instruction name to an opcode.
Return true if the instruction name is invalid.
Definition at line 143 of file MIParser.cpp.
References assert(), E, llvm::StringMapImpl::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::TargetSubtargetInfo::getRegisterInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::ArrayRef< T >::size(), and TRI.
Referenced by isImplicitOperandIn().
setTarget()
void PerTargetMIParsingState::setTarget (const TargetSubtargetInfo & NewSubtarget)
Definition at line 86 of file MIParser.cpp.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), E, llvm::StringMapImpl::empty(), llvm::TargetSubtargetInfo::getRegisterInfo(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), and TRI.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MIRParser/MIParser.h
lib/CodeGen/MIRParser/MIParser.cpp