LLVM: llvm::rdf::DataFlowGraph::DefStack Struct Reference
llvm::rdf::DataFlowGraph::DefStack Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Public Types
using iterator = Iterator
Public Member Functions
DefStack ()=default
bool empty () const
iterator top () const
iterator bottom () const
unsigned size () const
void push (NodeAddr< DefNode *> DA)
void pop ()
void start_block (NodeId N)
void clear_block (NodeId N)
Friends
struct Iterator
Detailed Description
Definition at line 669 of file RDFGraph.h.
Member Typedef Documentation
iterator
using llvm::rdf::DataFlowGraph::DefStack::iterator = Iterator
Definition at line 705 of file RDFGraph.h.
Constructor & Destructor Documentation
DefStack()
llvm::rdf::DataFlowGraph::DefStack::DefStack () default
Member Function Documentation
bottom()
iterator llvm::rdf::DataFlowGraph::DefStack::bottom () const inline
Definition at line 708 of file RDFGraph.h.
References llvm::size().
Referenced by llvm::rdf::DataFlowGraph::getNextShadow(), and llvm::rdf::operator<<().
clear_block()
void DataFlowGraph::DefStack::clear_block (NodeId N)
Definition at line 703 of file RDFGraph.cpp.
References assert(), F(), llvm::TargetLoweringBase::getExceptionPointerRegister(), llvm::TargetLoweringBase::getExceptionSelectorRegister(), llvm::MachineFunction::getFunction(), llvm::Function::getPersonalityFn(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::Function::hasPersonalityFn(), P, and llvm::X86AS::SS.
empty()
bool llvm::rdf::DataFlowGraph::DefStack::empty () const inline
Definition at line 672 of file RDFGraph.h.
References assert(), llvm::SIInstrFlags::DS, llvm::operator!=(), llvm::operator*(), and llvm::operator==().
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
pop()
void DataFlowGraph::DefStack::pop ()
Definition at line 688 of file RDFGraph.cpp.
References assert(), llvm::empty(), and P.
push()
void llvm::rdf::DataFlowGraph::DefStack::push (NodeAddr< DefNode *> DA) inline
Definition at line 711 of file RDFGraph.h.
size()
unsigned DataFlowGraph::DefStack::size () const
Definition at line 678 of file RDFGraph.cpp.
References E, and I.
start_block()
void DataFlowGraph::DefStack::start_block (NodeId N)
Definition at line 695 of file RDFGraph.cpp.
References assert().
top()
iterator llvm::rdf::DataFlowGraph::DefStack::top () const inline
Definition at line 707 of file RDFGraph.h.
Referenced by llvm::rdf::DataFlowGraph::getNextShadow(), and llvm::rdf::operator<<().
Friends And Related Function Documentation
Iterator
friend struct Iterator friend
Definition at line 717 of file RDFGraph.h.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFGraph.h
lib/Target/Hexagon/RDFGraph.cpp