LLVM: llvm::MDNodeKeyImpl< DILocalVariable > Struct Template Reference
llvm::MDNodeKeyImpl< DILocalVariable > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, MDString *Name, Metadata *File, unsigned Line, Metadata *Type, unsigned Arg, unsigned Flags, uint32_t AlignInBits)
MDNodeKeyImpl (const DILocalVariable *N)
bool isKeyOf (const DILocalVariable *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
MDString * Name
Metadata * File
unsigned Line
Metadata * Type
unsigned Arg
unsigned Flags
uint32_t AlignInBits
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILocalVariable >
Definition at line 939 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DILocalVariable >::MDNodeKeyImpl (Metadata * Scope, MDString * Name, Metadata * File, unsigned Line, Metadata * Type, unsigned Arg, unsigned Flags, uint32_t AlignInBits) inline
Definition at line 949 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DILocalVariable >::MDNodeKeyImpl (const DILocalVariable * N) inline
Definition at line 954 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::getHashValue () const inline
Definition at line 966 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DILocalVariable >::isKeyOf (const DILocalVariable * RHS) const inline
Definition at line 959 of file LLVMContextImpl.h.
References llvm::DIVariable::getAlignInBits(), llvm::DILocalVariable::getArg(), llvm::DILocalVariable::getFlags(), llvm::DIVariable::getLine(), llvm::DIVariable::getRawFile(), llvm::DIVariable::getRawName(), llvm::DIVariable::getRawScope(), and llvm::DIVariable::getRawType().
Member Data Documentation
AlignInBits
uint32_t llvm::MDNodeKeyImpl< DILocalVariable >::AlignInBits
Definition at line 947 of file LLVMContextImpl.h.
Arg
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Arg
Definition at line 945 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::File
Definition at line 942 of file LLVMContextImpl.h.
Flags
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Flags
Definition at line 946 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DILocalVariable >::Line
Definition at line 943 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DILocalVariable >::Name
Definition at line 941 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::Scope
Definition at line 940 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DILocalVariable >::Type
Definition at line 944 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h