LLVM: llvm::yaml::ScalarTraits< VersionTuple > Struct Template Reference
llvm::yaml::ScalarTraits< VersionTuple > Struct Template Reference
YAML traits for TbeVersion.
Static Public Member Functions
static void output (const VersionTuple &Value, void *, llvm::raw_ostream &Out)
static StringRef input (StringRef Scalar, void *, VersionTuple &Value)
static QuotingType mustQuote (StringRef)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< VersionTuple >
YAML traits for TbeVersion.
Definition at line 73 of file TBEHandler.cpp.
Member Function Documentation
input()
static StringRef llvm::yaml::ScalarTraits< VersionTuple >::input (StringRef Scalar, void * , VersionTuple & Value) inline static
Definition at line 79 of file TBEHandler.cpp.
References llvm::elfabi::TBEVersionCurrent(), and llvm::VersionTuple::tryParse().
mustQuote()
static QuotingType llvm::yaml::ScalarTraits< VersionTuple >::mustQuote (StringRef) inline static
Definition at line 91 of file TBEHandler.cpp.
References llvm::None.
output()
static void llvm::yaml::ScalarTraits< VersionTuple >::output (const VersionTuple & Value, void * , llvm::raw_ostream & Out) inline static
Definition at line 74 of file TBEHandler.cpp.
References llvm::VersionTuple::getAsString().
The documentation for this struct was generated from the following file:
lib/TextAPI/ELF/TBEHandler.cpp