LLVM: llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata Struct Reference
llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata Struct Reference final
In-memory representation of kernel attributes metadata.
#include "llvm/Support/AMDGPUMetadata.h"
Public Member Functions
Metadata ()=default
Default constructor.
bool empty () const
bool notEmpty () const
Public Attributes
std::vector< uint32_t > mReqdWorkGroupSize = std::vector<uint32_t>()
'reqd_work_group_size' attribute. Optional.
std::vector< uint32_t > mWorkGroupSizeHint = std::vector<uint32_t>()
'work_group_size_hint' attribute. Optional.
std::string mVecTypeHint = std::string()
'vec_type_hint' attribute. Optional.
std::string mRuntimeHandle = std::string()
External symbol created by runtime to store the kernel address for enqueued blocks.
Detailed Description
In-memory representation of kernel attributes metadata.
Definition at line 121 of file AMDGPUMetadata.h.
Constructor & Destructor Documentation
Metadata()
llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::Metadata () default
Default constructor.
Member Function Documentation
empty()
bool llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::empty () const inline
Returns
True if kernel attributes metadata is empty, false otherwise.
Definition at line 136 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Metadata >::mapping().
notEmpty()
bool llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::notEmpty () const inline
Returns
True if kernel attributes metadata is not empty, false otherwise.
Definition at line 141 of file AMDGPUMetadata.h.
Member Data Documentation
mReqdWorkGroupSize
std::vector<uint32_t> llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::mReqdWorkGroupSize = std::vector<uint32_t>()
'reqd_work_group_size' attribute. Optional.
Definition at line 123 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Attrs::Metadata >::mapping().
mRuntimeHandle
std::string llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::mRuntimeHandle = std::string()
External symbol created by runtime to store the kernel address for enqueued blocks.
Definition at line 130 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Attrs::Metadata >::mapping().
mVecTypeHint
std::string llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::mVecTypeHint = std::string()
'vec_type_hint' attribute. Optional.
Definition at line 127 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Attrs::Metadata >::mapping().
mWorkGroupSizeHint
std::vector<uint32_t> llvm::AMDGPU::HSAMD::Kernel::Attrs::Metadata::mWorkGroupSizeHint = std::vector<uint32_t>()
'work_group_size_hint' attribute. Optional.
Definition at line 125 of file AMDGPUMetadata.h.
Referenced by llvm::yaml::MappingTraits< Kernel::Attrs::Metadata >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/Support/AMDGPUMetadata.h