LLVM: llvm::detail::ErrorHolder Struct Reference
llvm::detail::ErrorHolder Struct Reference
#include "llvm/Testing/Support/SupportHelpers.h"
Public Member Functions
bool Success () const
Public Attributes
std::vector< std::shared_ptr< ErrorInfoBase > > Infos
Detailed Description
Definition at line 23 of file SupportHelpers.h.
Member Function Documentation
Success()
bool llvm::detail::ErrorHolder::Success () const inline
Definition at line 26 of file SupportHelpers.h.
Referenced by llvm::detail::ValueMatchesMono< T >::MatchAndExplain(), llvm::detail::ErrorMatchesMono< InfoT >::MatchAndExplain(), and llvm::detail::PrintTo().
Member Data Documentation
Infos
std::vector<std::shared_ptr<ErrorInfoBase> > llvm::detail::ErrorHolder::Infos
Definition at line 24 of file SupportHelpers.h.
Referenced by llvm::detail::ErrorMatchesMono< InfoT >::MatchAndExplain().
The documentation for this struct was generated from the following file:
include/llvm/Testing/Support/SupportHelpers.h