LLVM: llvm::DenseMapAPFloatKeyInfo Struct Reference
llvm::DenseMapAPFloatKeyInfo Struct Reference
#include "IR/LLVMContextImpl.h"
Static Public Member Functions
static APFloat getEmptyKey ()
static APFloat getTombstoneKey ()
static unsigned getHashValue (const APFloat &Key)
static bool isEqual (const APFloat &LHS, const APFloat &RHS)
Detailed Description
Definition at line 84 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
static APFloat llvm::DenseMapAPFloatKeyInfo::getEmptyKey () inline static
Definition at line 85 of file LLVMContextImpl.h.
References llvm::lltok::APFloat, and llvm::APFloatBase::Bogus().
getHashValue()
static unsigned llvm::DenseMapAPFloatKeyInfo::getHashValue (const APFloat & Key) inline static
Definition at line 88 of file LLVMContextImpl.h.
References llvm::hash_value().
getTombstoneKey()
static APFloat llvm::DenseMapAPFloatKeyInfo::getTombstoneKey () inline static
Definition at line 86 of file LLVMContextImpl.h.
References llvm::lltok::APFloat, and llvm::APFloatBase::Bogus().
isEqual()
static bool llvm::DenseMapAPFloatKeyInfo::isEqual (const APFloat & LHS, const APFloat & RHS) inline static
Definition at line 92 of file LLVMContextImpl.h.
References llvm::APFloat::bitwiseIsEqual().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h