LLVM: llvm::PatternMatch::icmp_pred_with_threshold Struct Reference
llvm::PatternMatch::icmp_pred_with_threshold Struct Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
bool isValue (const APInt &C)
Public Attributes
ICmpInst::Predicate Pred
const APInt * Thr
Detailed Description
Definition at line 484 of file PatternMatch.h.
Member Function Documentation
isValue()
bool llvm::PatternMatch::icmp_pred_with_threshold::isValue (const APInt & C) inline
Definition at line 487 of file PatternMatch.h.
References llvm::APInt::eq(), llvm_unreachable, llvm::APInt::ne(), llvm::APInt::sge(), llvm::APInt::sgt(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), and llvm::APInt::ult().
Member Data Documentation
Pred
ICmpInst::Predicate llvm::PatternMatch::icmp_pred_with_threshold::Pred
Definition at line 485 of file PatternMatch.h.
Thr
const APInt* llvm::PatternMatch::icmp_pred_with_threshold::Thr
Definition at line 486 of file PatternMatch.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h