LLVM: llvm::rdf::DeadCodeElimination Struct Reference
llvm::rdf::DeadCodeElimination Struct Reference
#include "Target/Hexagon/RDFDeadCode.h"
Public Member Functions
DeadCodeElimination (DataFlowGraph &dfg, MachineRegisterInfo &mri)
bool collect ()
bool erase (const SetVector< NodeId > &Nodes)
void trace (bool On)
bool trace () const
SetVector< NodeId > getDeadNodes ()
SetVector< NodeId > getDeadInstrs ()
DataFlowGraph & getDFG ()
Detailed Description
Definition at line 34 of file RDFDeadCode.h.
Constructor & Destructor Documentation
DeadCodeElimination()
llvm::rdf::DeadCodeElimination::DeadCodeElimination (DataFlowGraph & dfg, MachineRegisterInfo & mri) inline
Definition at line 35 of file RDFDeadCode.h.
References collect(), and erase().
Member Function Documentation
collect()
bool DeadCodeElimination::collect ()
Definition at line 116 of file RDFDeadCode.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::dbgs(), llvm::rdf::NodeAddr< T >::Id, IsDead, llvm::rdf::CodeNode::members(), llvm::rdf::CodeNode::members_if(), N, RA, llvm::rdf::NodeAttrs::Stmt, and trace().
Referenced by DeadCodeElimination().
erase()
bool DeadCodeElimination::erase (const SetVector< NodeId > & Nodes)
Definition at line 179 of file RDFDeadCode.cpp.
References llvm::rdf::NodeAddr< T >::Addr, B, llvm::dbgs(), llvm::rdf::NodeAttrs::Def, llvm::SetVector< T, Vector, Set >::empty(), llvm::MachineInstr::eraseFromParent(), llvm::rdf::NodeBase::getKind(), llvm::rdf::InstrNode::getOwner(), I, llvm::rdf::NodeAddr< T >::Id, llvm_unreachable, MI, N, llvm::rdf::NodeAttrs::Phi, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::rdf::NodeAttrs::Ref, llvm::rdf::CodeNode::removeMember(), llvm::sort(), llvm::rdf::NodeAttrs::Stmt, trace(), and llvm::rdf::NodeAttrs::Use.
Referenced by DeadCodeElimination().
getDeadInstrs()
SetVector<NodeId> llvm::rdf::DeadCodeElimination::getDeadInstrs () inline
Definition at line 44 of file RDFDeadCode.h.
getDeadNodes()
SetVector<NodeId> llvm::rdf::DeadCodeElimination::getDeadNodes () inline
Definition at line 43 of file RDFDeadCode.h.
getDFG()
DataFlowGraph& llvm::rdf::DeadCodeElimination::getDFG () inline
Definition at line 45 of file RDFDeadCode.h.
References MI.
trace() [1/2]
void llvm::rdf::DeadCodeElimination::trace (bool On) inline
Definition at line 40 of file RDFDeadCode.h.
trace() [2/2]
bool llvm::rdf::DeadCodeElimination::trace () const inline
Definition at line 41 of file RDFDeadCode.h.
Referenced by collect(), and erase().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFDeadCode.h
lib/Target/Hexagon/RDFDeadCode.cpp