LLVM: llvm::FmtAlign Struct Reference
llvm::FmtAlign Struct Reference
#include "llvm/Support/FormatCommon.h"
Public Member Functions
FmtAlign (detail::format_adapter &Adapter, AlignStyle Where, size_t Amount, char Fill=' ')
void format (raw_ostream &S, StringRef Options)
Public Attributes
detail::format_adapter & Adapter
AlignStyle Where
size_t Amount
char Fill
Detailed Description
Definition at line 19 of file FormatCommon.h.
Constructor & Destructor Documentation
FmtAlign()
llvm::FmtAlign::FmtAlign (detail::format_adapter & Adapter, AlignStyle Where, size_t Amount, char Fill = ' ') inline
Definition at line 25 of file FormatCommon.h.
Member Function Documentation
format()
void llvm::FmtAlign::format (raw_ostream & S, StringRef Options) inline
Definition at line 29 of file FormatCommon.h.
References llvm::Center, llvm::detail::format_adapter::format(), I, llvm::Left, llvm::SmallVectorBase::size(), and X.
Referenced by llvm::detail::AlignAdapter< T >::format(), and llvm::formatv_object_base::format().
Member Data Documentation
Adapter
detail::format_adapter& llvm::FmtAlign::Adapter
Definition at line 20 of file FormatCommon.h.
Amount
size_t llvm::FmtAlign::Amount
Definition at line 22 of file FormatCommon.h.
Fill
char llvm::FmtAlign::Fill
Definition at line 23 of file FormatCommon.h.
Where
AlignStyle llvm::FmtAlign::Where
Definition at line 21 of file FormatCommon.h.
The documentation for this struct was generated from the following file:
include/llvm/Support/FormatCommon.h