LLVM: llvm::yaml::ScalarTraits< uuid_t > Struct Template Reference
llvm::yaml::ScalarTraits< uuid_t > Struct Template Reference
#include "llvm/ObjectYAML/MachOYAML.h"
Static Public Member Functions
static void output (const uuid_t &Val, void *, raw_ostream &Out)
static StringRef input (StringRef Scalar, void *, uuid_t &Val)
static QuotingType mustQuote (StringRef S)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< uuid_t >
Definition at line 273 of file MachOYAML.h.
Member Function Documentation
input()
StringRef llvm::yaml::ScalarTraits< uuid_t >::input (StringRef Scalar, void * , uuid_t & Val) static
Definition at line 62 of file MachOYAML.cpp.
References llvm::getAsUnsignedInteger(), llvm::StringRef::size(), and llvm::StringRef::slice().
mustQuote()
QuotingType llvm::yaml::ScalarTraits< uuid_t >::mustQuote (StringRef S) static
Definition at line 79 of file MachOYAML.cpp.
output()
void llvm::yaml::ScalarTraits< uuid_t >::output (const uuid_t & Val, void * , raw_ostream & Out) static
Definition at line 58 of file MachOYAML.cpp.
References llvm::raw_ostream::write_uuid().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/MachOYAML.h
lib/ObjectYAML/MachOYAML.cpp