LLVM: llvm::HexagonSubtarget::CallMutation Struct Reference
llvm::HexagonSubtarget::CallMutation Struct Reference
#include "Target/Hexagon/HexagonSubtarget.h"
Public Member Functions
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Detailed Description
Definition at line 75 of file HexagonSubtarget.h.
Member Function Documentation
apply()
void HexagonSubtarget::CallMutation::apply (ScheduleDAGInstrs * DAG) override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 192 of file HexagonSubtarget.cpp.
References llvm::ScheduleDAGInstrs::addEdge(), llvm::SDep::Barrier, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::numbers::e, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::HexagonSubtarget::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), if(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDef(), llvm::Register::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::ScheduleDAG::MF, MI, SchedPredsCloser, SchedRetvalOptimization, llvm::ScheduleDAG::SUnits, and TRI.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonSubtarget.h
lib/Target/Hexagon/HexagonSubtarget.cpp