LLVM: llvm::GraphTraits< Inverse< VPBlockBase * > > Struct Template Reference
llvm::GraphTraits< Inverse< VPBlockBase * > > Struct Template Reference
#include "Transforms/Vectorize/VPlan.h"
Public Types
using NodeRef = VPBlockBase *
using ChildIteratorType = SmallVectorImpl< VPBlockBase * >::iterator
Static Public Member Functions
static NodeRef getEntryNode (Inverse< NodeRef > B)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<>
struct llvm::GraphTraits< Inverse< VPBlockBase * > >
Definition at line 1263 of file VPlan.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< Inverse< VPBlockBase * > >::ChildIteratorType = SmallVectorImpl<VPBlockBase *>::iterator
Definition at line 1265 of file VPlan.h.
NodeRef
using llvm::GraphTraits< Inverse< VPBlockBase * > >::NodeRef = VPBlockBase *
Definition at line 1264 of file VPlan.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< Inverse< VPBlockBase * > >::child_begin (NodeRef N) inline static
Definition at line 1269 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::VPBlockBase::getPredecessors().
child_end()
static ChildIteratorType llvm::GraphTraits< Inverse< VPBlockBase * > >::child_end (NodeRef N) inline static
Definition at line 1273 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::VPBlockBase::getPredecessors().
getEntryNode()
static NodeRef llvm::GraphTraits< Inverse< VPBlockBase * > >::getEntryNode (Inverse< NodeRef > B) inline static
Definition at line 1267 of file VPlan.h.
References llvm::Inverse< GraphType >::Graph.
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h