LLVM: llvm::DWARFVerifier::DieRangeInfo Struct Reference
llvm::DWARFVerifier::DieRangeInfo Struct Reference
A class that keeps the address range information for a single DIE.
#include "llvm/DebugInfo/DWARF/DWARFVerifier.h"
Public Types
typedef std::vector< DWARFAddressRange >::const_iterator address_range_iterator
typedef std::set< DieRangeInfo >::const_iterator die_range_info_iterator
Public Member Functions
DieRangeInfo ()=default
DieRangeInfo (DWARFDie Die)
DieRangeInfo (std::vector< DWARFAddressRange > Ranges)
Used for unit testing.
address_range_iterator insert (const DWARFAddressRange &R)
Inserts the address range.
address_range_iterator findRange (const DWARFAddressRange &R) const
Finds an address range in the sorted vector of ranges.
die_range_info_iterator insert (const DieRangeInfo &RI)
Inserts the address range info.
bool contains (const DieRangeInfo &RHS) const
Return true if ranges in this object contains all ranges within RHS.
bool intersects (const DieRangeInfo &RHS) const
Return true if any range in this object intersects with any range in RHS.
Public Attributes
DWARFDie Die
std::vector< DWARFAddressRange > Ranges
Sorted DWARFAddressRanges.
std::set< DieRangeInfo > Children
Sorted DWARFAddressRangeInfo.
Detailed Description
A class that keeps the address range information for a single DIE.
Definition at line 38 of file DWARFVerifier.h.
Member Typedef Documentation
address_range_iterator
typedef std::vector<DWARFAddressRange>::const_iterator llvm::DWARFVerifier::DieRangeInfo::address_range_iterator
Definition at line 55 of file DWARFVerifier.h.
die_range_info_iterator
typedef std::set<DieRangeInfo>::const_iterator llvm::DWARFVerifier::DieRangeInfo::die_range_info_iterator
Definition at line 56 of file DWARFVerifier.h.
Constructor & Destructor Documentation
DieRangeInfo() [1/3]
llvm::DWARFVerifier::DieRangeInfo::DieRangeInfo () default
DieRangeInfo() [2/3]
llvm::DWARFVerifier::DieRangeInfo::DieRangeInfo (DWARFDie Die) inline
Definition at line 48 of file DWARFVerifier.h.
DieRangeInfo() [3/3]
llvm::DWARFVerifier::DieRangeInfo::DieRangeInfo (std::vector< DWARFAddressRange > Ranges) inline
Used for unit testing.
Definition at line 51 of file DWARFVerifier.h.
Member Function Documentation
contains()
bool DWARFVerifier::DieRangeInfo::contains (const DieRangeInfo & RHS) const
Return true if ranges in this object contains all ranges within RHS.
Definition at line 62 of file DWARFVerifier.cpp.
References llvm::DWARFAddressRange::HighPC, llvm::DWARFAddressRange::LowPC, and Ranges.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
findRange()
address_range_iterator llvm::DWARFVerifier::DieRangeInfo::findRange (const DWARFAddressRange & R) const inline
Finds an address range in the sorted vector of ranges.
Definition at line 66 of file DWARFVerifier.h.
insert() [1/2]
DWARFVerifier::DieRangeInfo::address_range_iterator DWARFVerifier::DieRangeInfo::insert (const DWARFAddressRange & R)
Inserts the address range.
If the range overlaps with an existing range, the range is not added and an iterator to the overlapping range is returned.
This is used for finding overlapping ranges within the same DIE.
Definition at line 30 of file DWARFVerifier.cpp.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
insert() [2/2]
DWARFVerifier::DieRangeInfo::die_range_info_iterator DWARFVerifier::DieRangeInfo::insert (const DieRangeInfo & RI)
Inserts the address range info.
If any of its ranges overlaps with a range in an existing range info, the range info is not added and an iterator to the overlapping range info.
This is used for finding overlapping children of the same DIE.
Definition at line 50 of file DWARFVerifier.cpp.
intersects()
bool DWARFVerifier::DieRangeInfo::intersects (const DieRangeInfo & RHS) const
Return true if any range in this object intersects with any range in RHS.
Definition at line 86 of file DWARFVerifier.cpp.
References llvm::dwarf::AttributeString(), llvm::DWARFDie::dump(), llvm::dwarf::DW_LENGTH_DWARF64, error, llvm::DWARFDie::find(), llvm::format(), llvm::DWARFDebugAbbrev::getAbbreviationDeclarationSet(), llvm::DWARFUnit::getDIEAtIndex(), llvm::DWARFUnit::getNumDIEs(), llvm::DWARFDie::getParent(), llvm::DWARFDie::getTag(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DWARFUnit::getUnitDIE(), llvm::DWARFUnit::getUnitType(), llvm::DWARFDie::hasChildren(), I, llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, InlineBuckets, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::DWARFUnit::isMatchingUnitTypeAndTag(), llvm::DWARFDie::isSubprogramDIE(), llvm::DWARFContext::isSupportedVersion(), llvm::dwarf::isUnitType(), llvm::DWARFDie::isValid(), llvm::DataExtractor::isValidOffset(), Ranges, Success, llvm::dwarf::TagString(), llvm::dwarf::UnitTypeString(), and llvm::IndexedInstrProf::Version.
Member Data Documentation
Children
std::set<DieRangeInfo> llvm::DWARFVerifier::DieRangeInfo::Children
Sorted DWARFAddressRangeInfo.
Definition at line 45 of file DWARFVerifier.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
Die
DWARFDie llvm::DWARFVerifier::DieRangeInfo::Die
Definition at line 39 of file DWARFVerifier.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo(), and llvm::operator<().
Ranges
std::vector<DWARFAddressRange> llvm::DWARFVerifier::DieRangeInfo::Ranges
Sorted DWARFAddressRanges.
Definition at line 42 of file DWARFVerifier.h.
Referenced by contains(), llvm::DWARFVerifier::handleDebugInfo(), intersects(), and llvm::operator<().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFVerifier.h
lib/DebugInfo/DWARF/DWARFVerifier.cpp