LLVM: llvm::MDNodeKeyImpl< DILocation > Struct Template Reference
llvm::MDNodeKeyImpl< DILocation > Struct Template Reference
DenseMapInfo for DILocation.
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (unsigned Line, unsigned Column, Metadata *Scope, Metadata *InlinedAt, bool ImplicitCode)
MDNodeKeyImpl (const DILocation *L)
bool isKeyOf (const DILocation *RHS) const
unsigned getHashValue () const
Public Attributes
unsigned Line
unsigned Column
Metadata * Scope
Metadata * InlinedAt
bool ImplicitCode
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILocation >
DenseMapInfo for DILocation.
Definition at line 278 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DILocation >::MDNodeKeyImpl (unsigned Line, unsigned Column, Metadata * Scope, Metadata * InlinedAt, bool ImplicitCode) inline
Definition at line 285 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DILocation >::MDNodeKeyImpl (const DILocation * L) inline
Definition at line 289 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DILocation >::getHashValue () const inline
Definition at line 299 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DILocation >::isKeyOf (const DILocation * RHS) const inline
Definition at line 293 of file LLVMContextImpl.h.
References llvm::DILocation::getRawInlinedAt(), and llvm::DILocation::getRawScope().
Member Data Documentation
Column
unsigned llvm::MDNodeKeyImpl< DILocation >::Column
Definition at line 280 of file LLVMContextImpl.h.
ImplicitCode
bool llvm::MDNodeKeyImpl< DILocation >::ImplicitCode
Definition at line 283 of file LLVMContextImpl.h.
InlinedAt
Metadata* llvm::MDNodeKeyImpl< DILocation >::InlinedAt
Definition at line 282 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DILocation >::Line
Definition at line 279 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DILocation >::Scope
Definition at line 281 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h