LLVM: llvm::GraphTraits< VPBlockBase * > Struct Template Reference
llvm::GraphTraits< VPBlockBase * > Struct Template Reference
#include "Transforms/Vectorize/VPlan.h"
Public Types
using NodeRef = VPBlockBase *
using ChildIteratorType = SmallVectorImpl< VPBlockBase * >::iterator
Static Public Member Functions
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
template<>
struct llvm::GraphTraits< VPBlockBase * >
Definition at line 1231 of file VPlan.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< VPBlockBase * >::ChildIteratorType = SmallVectorImpl<VPBlockBase *>::iterator
Definition at line 1233 of file VPlan.h.
NodeRef
using llvm::GraphTraits< VPBlockBase * >::NodeRef = VPBlockBase *
Definition at line 1232 of file VPlan.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< VPBlockBase * >::child_begin (NodeRef N) inline static
Definition at line 1237 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::VPBlockBase::getSuccessors().
child_end()
static ChildIteratorType llvm::GraphTraits< VPBlockBase * >::child_end (NodeRef N) inline static
Definition at line 1241 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::VPBlockBase::getSuccessors().
getEntryNode()
static NodeRef llvm::GraphTraits< VPBlockBase * >::getEntryNode (NodeRef N) inline static
Definition at line 1235 of file VPlan.h.
References N.
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h