LLVM: llvm::AppleAccelTableData::Atom Struct Reference
llvm::AppleAccelTableData::Atom Struct Reference
An Atom defines the form of the data in an Apple accelerator table.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
constexpr Atom (uint16_t Type, uint16_t Form)
void print (raw_ostream &OS) const
void dump () const
Public Attributes
const uint16_t Type
Atom Type.
const uint16_t Form
DWARF Form.
Detailed Description
An Atom defines the form of the data in an Apple accelerator table.
Conceptually it is a column in the accelerator consisting of a type and a specification of the form of its data.
Definition at line 225 of file AccelTable.h.
Constructor & Destructor Documentation
Atom()
constexpr llvm::AppleAccelTableData::Atom::Atom (uint16_t Type, uint16_t Form) inline
Definition at line 231 of file AccelTable.h.
References llvm::AccelTableData::print().
Member Function Documentation
dump()
void llvm::AppleAccelTableData::Atom::dump () const inline
Definition at line 235 of file AccelTable.h.
References llvm::HexStyle::Asm, llvm::dbgs(), and llvm::AccelTableData::print().
print()
void AppleAccelTableData::Atom::print (raw_ostream & OS) const
Definition at line 631 of file AccelTable.cpp.
References llvm::dwarf::AtomTypeString(), llvm::dwarf::FormEncodingString(), print(), llvm::AccelTableBase::print(), and print().
Referenced by print().
Member Data Documentation
Form
const uint16_t llvm::AppleAccelTableData::Atom::Form
DWARF Form.
Definition at line 229 of file AccelTable.h.
Type
const uint16_t llvm::AppleAccelTableData::Atom::Type
Atom Type.
Definition at line 227 of file AccelTable.h.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp