LLVM: llvm::SparseBitVectorElement< ElementSize > Struct Template Reference
llvm::SparseBitVectorElement< ElementSize > Struct Template Reference
SparseBitVector is an implementation of a bitvector that is sparse by only storing the elements that have non-zero bits set.
#include "llvm/ADT/SparseBitVector.h"
Public Types
enum { BITWORD_SIZE = sizeof(BitWord) * CHAR_BIT, BITWORDS_PER_ELEMENT = (ElementSize + BITWORD_SIZE - 1) / BITWORD_SIZE, BITS_PER_ELEMENT = ElementSize }
using BitWord = unsigned long
using size_type = unsigned
Public Member Functions
SparseBitVectorElement (unsigned Idx)
bool operator== (const SparseBitVectorElement &RHS) const
bool operator!= (const SparseBitVectorElement &RHS) const
BitWord word (unsigned Idx) const
unsigned index () const
bool empty () const
void set (unsigned Idx)
bool test_and_set (unsigned Idx)
void reset (unsigned Idx)
bool test (unsigned Idx) const
size_type count () const
int find_first () const
find_first - Returns the index of the first set bit.
int find_last () const
find_last - Returns the index of the last set bit.
int find_next (unsigned Curr) const
find_next - Returns the index of the next set bit starting from the "Curr" bit.
bool unionWith (const SparseBitVectorElement &RHS)
bool intersects (const SparseBitVectorElement &RHS) const
bool intersectWith (const SparseBitVectorElement &RHS, bool &BecameZero)
bool intersectWithComplement (const SparseBitVectorElement &RHS, bool &BecameZero)
void intersectWithComplement (const SparseBitVectorElement &RHS1, const SparseBitVectorElement &RHS2, bool &BecameZero)
Detailed Description
template<unsigned ElementSize = 128>
struct llvm::SparseBitVectorElement< ElementSize >
SparseBitVector is an implementation of a bitvector that is sparse by only storing the elements that have non-zero bits set.
In order to make this fast for the most common cases, SparseBitVector is implemented as a linked list of SparseBitVectorElements. We maintain a pointer to the last SparseBitVectorElement accessed (in the form of a list iterator), in order to make multiple in-order test/set constant time after the first one is executed. Note that using vectors to store SparseBitVectorElement's does not work out very well because it causes insertion in the middle to take enormous amounts of time with a large amount of bits. Other structures that have better worst cases for insertion in the middle (various balanced trees, etc) do not perform as well in practice as a linked list with this iterator kept up to date. They are also significantly more memory intensive.
Definition at line 41 of file SparseBitVector.h.
Member Typedef Documentation
BitWord
template<unsigned ElementSize = 128> using llvm::SparseBitVectorElement< ElementSize >::BitWord = unsigned long
Definition at line 43 of file SparseBitVector.h.
size_type
template<unsigned ElementSize = 128> using llvm::SparseBitVectorElement< ElementSize >::size_type = unsigned
Definition at line 44 of file SparseBitVector.h.
Member Enumeration Documentation
anonymous enum
template<unsigned ElementSize = 128> anonymous enum
Enumerator
BITWORD_SIZE
BITWORDS_PER_ELEMENT
BITS_PER_ELEMENT
Definition at line 45 of file SparseBitVector.h.
Constructor & Destructor Documentation
SparseBitVectorElement()
template<unsigned ElementSize = 128> llvm::SparseBitVectorElement< ElementSize >::SparseBitVectorElement (unsigned Idx) inline explicit
Definition at line 62 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
Member Function Documentation
count()
template<unsigned ElementSize = 128> size_type llvm::SparseBitVectorElement< ElementSize >::count () const inline
Definition at line 119 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT, and llvm::countPopulation().
empty()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::empty () const inline
Definition at line 91 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
Referenced by llvm::SparseBitVector< ElementSize >::intersectWithComplement().
find_first()
template<unsigned ElementSize = 128> int llvm::SparseBitVectorElement< ElementSize >::find_first () const inline
find_first - Returns the index of the first set bit.
Definition at line 127 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE, llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT, llvm::countTrailingZeros(), and llvm_unreachable.
Referenced by llvm::SparseBitVector< ElementSize >::find_first().
find_last()
template<unsigned ElementSize = 128> int llvm::SparseBitVectorElement< ElementSize >::find_last () const inline
find_last - Returns the index of the last set bit.
Definition at line 135 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE, llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT, llvm::countLeadingZeros(), I, and llvm_unreachable.
Referenced by llvm::SparseBitVector< ElementSize >::find_last().
find_next()
template<unsigned ElementSize = 128> int llvm::SparseBitVectorElement< ElementSize >::find_next (unsigned Curr) const inline
find_next - Returns the index of the next set bit starting from the "Curr" bit.
Returns -1 if the next set bit is not found.
Definition at line 147 of file SparseBitVector.h.
References assert(), llvm::SparseBitVectorElement< ElementSize >::BITS_PER_ELEMENT, llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE, llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT, and llvm::countTrailingZeros().
index()
template<unsigned ElementSize = 128> unsigned llvm::SparseBitVectorElement< ElementSize >::index () const inline
Definition at line 87 of file SparseBitVector.h.
Referenced by llvm::SparseBitVector< ElementSize >::find_first(), and llvm::SparseBitVector< ElementSize >::find_last().
intersects()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::intersects (const SparseBitVectorElement< ElementSize > & RHS) const inline
Definition at line 184 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
Referenced by llvm::SparseBitVector< ElementSize >::intersects().
intersectWith()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::intersectWith (const SparseBitVectorElement< ElementSize > & RHS, bool & BecameZero) inline
Definition at line 194 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
intersectWithComplement() [1/2]
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::intersectWithComplement (const SparseBitVectorElement< ElementSize > & RHS, bool & BecameZero) inline
Definition at line 217 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
Referenced by llvm::SparseBitVector< ElementSize >::intersectWithComplement().
intersectWithComplement() [2/2]
template<unsigned ElementSize = 128> void llvm::SparseBitVectorElement< ElementSize >::intersectWithComplement (const SparseBitVectorElement< ElementSize > & RHS1, const SparseBitVectorElement< ElementSize > & RHS2, bool & BecameZero) inline
Definition at line 239 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
operator!=()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::operator!= (const SparseBitVectorElement< ElementSize > & RHS) const inline
Definition at line 77 of file SparseBitVector.h.
operator==()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::operator== (const SparseBitVectorElement< ElementSize > & RHS) const inline
Definition at line 68 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
reset()
template<unsigned ElementSize = 128> void llvm::SparseBitVectorElement< ElementSize >::reset (unsigned Idx) inline
Definition at line 111 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE.
set()
template<unsigned ElementSize = 128> void llvm::SparseBitVectorElement< ElementSize >::set (unsigned Idx) inline
Definition at line 98 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE.
test()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::test (unsigned Idx) const inline
Definition at line 115 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORD_SIZE.
Referenced by llvm::SparseBitVectorElement< ElementSize >::test_and_set(), and llvm::SparseBitVector< ElementSize >::test_and_set().
test_and_set()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::test_and_set (unsigned Idx) inline
Definition at line 102 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::test().
unionWith()
template<unsigned ElementSize = 128> bool llvm::SparseBitVectorElement< ElementSize >::unionWith (const SparseBitVectorElement< ElementSize > & RHS) inline
Definition at line 171 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
word()
template<unsigned ElementSize = 128> BitWord llvm::SparseBitVectorElement< ElementSize >::word (unsigned Idx) const inline
Definition at line 82 of file SparseBitVector.h.
References assert(), and llvm::SparseBitVectorElement< ElementSize >::BITWORDS_PER_ELEMENT.
The documentation for this struct was generated from the following file:
include/llvm/ADT/SparseBitVector.h