LLVM: llvm::MDNodeKeyImpl< DIExpression > Struct Template Reference
llvm::MDNodeKeyImpl< DIExpression > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (ArrayRef< uint64_t > Elements)
MDNodeKeyImpl (const DIExpression *N)
bool isKeyOf (const DIExpression *RHS) const
unsigned getHashValue () const
Public Attributes
ArrayRef< uint64_t > Elements
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIExpression >
Definition at line 1001 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIExpression >::MDNodeKeyImpl (ArrayRef< uint64_t > Elements) inline
Definition at line 1004 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIExpression >::MDNodeKeyImpl (const DIExpression * N) inline
Definition at line 1005 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIExpression >::getHashValue () const inline
Definition at line 1011 of file LLVMContextImpl.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), and llvm::hash_combine_range().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIExpression >::isKeyOf (const DIExpression * RHS) const inline
Definition at line 1007 of file LLVMContextImpl.h.
References llvm::DIExpression::getElements().
Member Data Documentation
Elements
ArrayRef<uint64_t> llvm::MDNodeKeyImpl< DIExpression >::Elements
Definition at line 1002 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h