LLVM: llvm::DWARFYAML::InitialLength Struct Reference
llvm::DWARFYAML::InitialLength Struct Reference
#include "llvm/ObjectYAML/DWARFYAML.h"
Public Member Functions
bool isDWARF64 () const
uint64_t getLength () const
void setLength (uint64_t Len)
Public Attributes
uint32_t TotalLength
uint64_t TotalLength64
Detailed Description
Definition at line 27 of file DWARFYAML.h.
Member Function Documentation
getLength()
uint64_t llvm::DWARFYAML::InitialLength::getLength () const inline
Definition at line 33 of file DWARFYAML.h.
References isDWARF64(), TotalLength, and TotalLength64.
isDWARF64()
bool llvm::DWARFYAML::InitialLength::isDWARF64 () const inline
Definition at line 31 of file DWARFYAML.h.
Referenced by llvm::DWARFYAML::EmitDebugLine(), getLength(), getOffsetSize(), llvm::yaml::MappingTraits< DWARFYAML::InitialLength >::mapping(), and writeInitialLength().
setLength()
void llvm::DWARFYAML::InitialLength::setLength (uint64_t Len) inline
Definition at line 37 of file DWARFYAML.h.
Referenced by EmitDebugSectionImpl().
Member Data Documentation
TotalLength
uint32_t llvm::DWARFYAML::InitialLength::TotalLength
Definition at line 28 of file DWARFYAML.h.
Referenced by getLength(), llvm::yaml::MappingTraits< DWARFYAML::InitialLength >::mapping(), and writeInitialLength().
TotalLength64
uint64_t llvm::DWARFYAML::InitialLength::TotalLength64
Definition at line 29 of file DWARFYAML.h.
Referenced by getLength(), llvm::yaml::MappingTraits< DWARFYAML::InitialLength >::mapping(), and writeInitialLength().
The documentation for this struct was generated from the following file:
include/llvm/ObjectYAML/DWARFYAML.h