LLVM: llvm::DenseMapInfo< DebugVariable > Struct Template Reference
llvm::DenseMapInfo< DebugVariable > Struct Template Reference
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
using FragmentInfo = DIExpression::FragmentInfo
Static Public Member Functions
static DebugVariable getEmptyKey ()
Empty key: no key should be generated that has no DILocalVariable.
static DebugVariable getTombstoneKey ()
Difference in tombstone is that the Optional is meaningful.
static unsigned getHashValue (const DebugVariable &D)
static bool isEqual (const DebugVariable &A, const DebugVariable &B)
Detailed Description
template<>
struct llvm::DenseMapInfo< DebugVariable >
Definition at line 3318 of file DebugInfoMetadata.h.
Member Typedef Documentation
FragmentInfo
using llvm::DenseMapInfo< DebugVariable >::FragmentInfo = DIExpression::FragmentInfo
Definition at line 3319 of file DebugInfoMetadata.h.
Member Function Documentation
getEmptyKey()
static DebugVariable llvm::DenseMapInfo< DebugVariable >::getEmptyKey () inline static
Empty key: no key should be generated that has no DILocalVariable.
Definition at line 3322 of file DebugInfoMetadata.h.
getHashValue()
static unsigned llvm::DenseMapInfo< DebugVariable >::getHashValue (const DebugVariable & D) inline static
Definition at line 3331 of file DebugInfoMetadata.h.
References llvm::DebugVariable::getFragment(), llvm::DebugVariable::getInlinedAt(), llvm::DebugVariable::getVariable(), and llvm::hash_combine().
getTombstoneKey()
static DebugVariable llvm::DenseMapInfo< DebugVariable >::getTombstoneKey () inline static
Difference in tombstone is that the Optional is meaningful.
Definition at line 3327 of file DebugInfoMetadata.h.
isEqual()
static bool llvm::DenseMapInfo< DebugVariable >::isEqual (const DebugVariable & A, const DebugVariable & B) inline static
Definition at line 3340 of file DebugInfoMetadata.h.
References B.
The documentation for this struct was generated from the following file:
include/llvm/IR/DebugInfoMetadata.h