LLVM: llvm::yaml::PolymorphicTraits< DocNode > Struct Template Reference
llvm::yaml::PolymorphicTraits< DocNode > Struct Template Reference
YAMLIO for DocNode.
Static Public Member Functions
static NodeKind getKind (const DocNode &N)
static MapDocNode & getAsMap (DocNode &N)
static ArrayDocNode & getAsSequence (DocNode &N)
static ScalarDocNode & getAsScalar (DocNode &N)
Detailed Description
template<>
struct llvm::yaml::PolymorphicTraits< DocNode >
YAMLIO for DocNode.
Definition at line 147 of file MsgPackDocumentYAML.cpp.
Member Function Documentation
getAsMap()
static MapDocNode& llvm::yaml::PolymorphicTraits< DocNode >::getAsMap (DocNode & N) inline static
Definition at line 160 of file MsgPackDocumentYAML.cpp.
References llvm::msgpack::DocNode::getMap().
getAsScalar()
static ScalarDocNode& llvm::yaml::PolymorphicTraits< DocNode >::getAsScalar (DocNode & N) inline static
Definition at line 167 of file MsgPackDocumentYAML.cpp.
References N.
getAsSequence()
static ArrayDocNode& llvm::yaml::PolymorphicTraits< DocNode >::getAsSequence (DocNode & N) inline static
Definition at line 162 of file MsgPackDocumentYAML.cpp.
References llvm::msgpack::DocNode::getArray(), and N.
getKind()
static NodeKind llvm::yaml::PolymorphicTraits< DocNode >::getKind (const DocNode & N) inline static
Definition at line 149 of file MsgPackDocumentYAML.cpp.
References llvm::msgpack::Array, llvm::msgpack::DocNode::getKind(), llvm::msgpack::Map, and llvm::NVPTX::PTXLdStInstCode::Scalar.
The documentation for this struct was generated from the following file:
lib/BinaryFormat/MsgPackDocumentYAML.cpp