LLVM: llvm::SDNodeFlags Struct Reference
llvm::SDNodeFlags Struct Reference
These are IR-level optimization flags that may be propagated to SDNodes.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Member Functions
SDNodeFlags ()
Default constructor turns off all optimization flags.
void copyFMF (const FPMathOperator &FPMO)
Propagate the fast-math-flags from an IR FPMathOperator.
void setDefined ()
Sets the state of the flags to the defined state.
bool isDefined () const
Returns true if the flags are in a defined state.
void setNoUnsignedWrap (bool b)
void setNoSignedWrap (bool b)
void setExact (bool b)
void setNoNaNs (bool b)
void setNoInfs (bool b)
void setNoSignedZeros (bool b)
void setAllowReciprocal (bool b)
void setVectorReduction (bool b)
void setAllowContract (bool b)
void setApproximateFuncs (bool b)
void setAllowReassociation (bool b)
void setNoFPExcept (bool b)
bool hasNoUnsignedWrap () const
bool hasNoSignedWrap () const
bool hasExact () const
bool hasNoNaNs () const
bool hasNoInfs () const
bool hasNoSignedZeros () const
bool hasAllowReciprocal () const
bool hasVectorReduction () const
bool hasAllowContract () const
bool hasApproximateFuncs () const
bool hasAllowReassociation () const
bool hasNoFPExcept () const
bool isFast () const
void intersectWith (const SDNodeFlags Flags)
Clear any flags in this flag set that aren't also set in Flags.
Detailed Description
These are IR-level optimization flags that may be propagated to SDNodes.
TODO: This data structure should be shared by the IR optimizer and the the backend.
Definition at line 357 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDNodeFlags()
llvm::SDNodeFlags::SDNodeFlags () inline
Default constructor turns off all optimization flags.
Definition at line 385 of file SelectionDAGNodes.h.
Member Function Documentation
copyFMF()
void llvm::SDNodeFlags::copyFMF (const FPMathOperator & FPMO) inline
Propagate the fast-math-flags from an IR FPMathOperator.
Definition at line 393 of file SelectionDAGNodes.h.
References llvm::FPMathOperator::hasAllowContract(), llvm::FPMathOperator::hasAllowReassoc(), llvm::FPMathOperator::hasAllowReciprocal(), llvm::FPMathOperator::hasApproxFunc(), llvm::FPMathOperator::hasNoInfs(), llvm::FPMathOperator::hasNoNaNs(), and llvm::FPMathOperator::hasNoSignedZeros().
Referenced by isVectorReductionOp().
hasAllowContract()
bool llvm::SDNodeFlags::hasAllowContract () const inline
Definition at line 467 of file SelectionDAGNodes.h.
References llvm::bitc::AllowContract.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), isClampZeroToOne(), and isContractable().
hasAllowReassociation()
bool llvm::SDNodeFlags::hasAllowReassociation () const inline
Definition at line 469 of file SelectionDAGNodes.h.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), isContractable(), and llvm::SelectionDAG::matchBinOpReduction().
hasAllowReciprocal()
bool llvm::SDNodeFlags::hasAllowReciprocal () const inline
Definition at line 465 of file SelectionDAGNodes.h.
References llvm::bitc::AllowReciprocal.
Referenced by llvm::InstrEmitter::EmitDbgLabel().
hasApproximateFuncs()
bool llvm::SDNodeFlags::hasApproximateFuncs () const inline
Definition at line 468 of file SelectionDAGNodes.h.
Referenced by CanCombineFCOPYSIGN_EXTEND_ROUND(), and llvm::InstrEmitter::EmitDbgLabel().
hasExact()
bool llvm::SDNodeFlags::hasExact () const inline
Definition at line 461 of file SelectionDAGNodes.h.
Referenced by llvm::TargetLowering::BuildSDIV(), combineShiftOfShiftedLogic(), llvm::InstrEmitter::EmitDbgLabel(), llvm::TargetLowering::SimplifyDemandedBits(), and simplifyDivRem().
hasNoFPExcept()
bool llvm::SDNodeFlags::hasNoFPExcept () const inline
Definition at line 470 of file SelectionDAGNodes.h.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), and isCalleeLoad().
hasNoInfs()
bool llvm::SDNodeFlags::hasNoInfs () const inline
Definition at line 463 of file SelectionDAGNodes.h.
References llvm::bitc::NoInfs.
Referenced by CanCombineFCOPYSIGN_EXTEND_ROUND(), and llvm::InstrEmitter::EmitDbgLabel().
hasNoNaNs()
bool llvm::SDNodeFlags::hasNoNaNs () const inline
Definition at line 462 of file SelectionDAGNodes.h.
References llvm::bitc::NoNaNs.
Referenced by CanCombineFCOPYSIGN_EXTEND_ROUND(), combineFMinNumFMaxNum(), llvm::createR600ISelDag(), llvm::InstrEmitter::EmitDbgLabel(), getReductionSDNode(), isContractable(), and llvm::SelectionDAG::isKnownNeverNaN().
hasNoSignedWrap()
bool llvm::SDNodeFlags::hasNoSignedWrap () const inline
Definition at line 460 of file SelectionDAGNodes.h.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), EmitTest(), promoteExtBeforeAdd(), llvm::TargetLowering::SimplifyDemandedBits(), and tryFoldToZero().
hasNoSignedZeros()
bool llvm::SDNodeFlags::hasNoSignedZeros () const inline
Definition at line 464 of file SelectionDAGNodes.h.
References llvm::bitc::NoSignedZeros.
Referenced by CanCombineFCOPYSIGN_EXTEND_ROUND(), combineFneg(), llvm::InstrEmitter::EmitDbgLabel(), FoldIntToFPToInt(), llvm::TargetLowering::getNegatedExpression(), isContractable(), llvm::TargetLowering::isNegatibleForFree(), llvm::SelectionDAG::matchBinOpReduction(), and llvm::AMDGPUTargetLowering::mayIgnoreSignedZero().
hasNoUnsignedWrap()
bool llvm::SDNodeFlags::hasNoUnsignedWrap () const inline
Definition at line 459 of file SelectionDAGNodes.h.
Referenced by llvm::InstrEmitter::EmitDbgLabel(), findMemSDNode(), getSPDenormModeValue(), promoteExtBeforeAdd(), llvm::TargetLowering::SimplifyDemandedBits(), and tryFoldToZero().
hasVectorReduction()
bool llvm::SDNodeFlags::hasVectorReduction () const inline
Definition at line 466 of file SelectionDAGNodes.h.
Referenced by combineAdd().
intersectWith()
void llvm::SDNodeFlags::intersectWith (const SDNodeFlags Flags) inline
Clear any flags in this flag set that aren't also set in Flags.
If the given Flags are undefined then don't do anything.
Definition at line 479 of file SelectionDAGNodes.h.
References llvm::bitc::AllowContract, llvm::bitc::AllowReciprocal, isDefined(), llvm::bitc::NoInfs, llvm::bitc::NoNaNs, and llvm::bitc::NoSignedZeros.
Referenced by llvm::SDNode::intersectFlagsWith().
isDefined()
bool llvm::SDNodeFlags::isDefined () const inline
Returns true if the flags are in a defined state.
Definition at line 406 of file SelectionDAGNodes.h.
Referenced by llvm::createR600ISelDag(), and intersectWith().
isFast()
bool llvm::SDNodeFlags::isFast () const inline
Definition at line 472 of file SelectionDAGNodes.h.
References llvm::bitc::AllowContract, llvm::bitc::AllowReciprocal, llvm::bitc::NoInfs, llvm::bitc::NoNaNs, and llvm::bitc::NoSignedZeros.
Referenced by llvm::SDNode::isFast().
setAllowContract()
void llvm::SDNodeFlags::setAllowContract (bool b) inline
Definition at line 441 of file SelectionDAGNodes.h.
References llvm::bitc::AllowContract.
setAllowReassociation()
void llvm::SDNodeFlags::setAllowReassociation (bool b) inline
Definition at line 449 of file SelectionDAGNodes.h.
Referenced by getEstimate().
setAllowReciprocal()
void llvm::SDNodeFlags::setAllowReciprocal (bool b) inline
Definition at line 433 of file SelectionDAGNodes.h.
References llvm::bitc::AllowReciprocal.
setApproximateFuncs()
void llvm::SDNodeFlags::setApproximateFuncs (bool b) inline
Definition at line 445 of file SelectionDAGNodes.h.
setDefined()
void llvm::SDNodeFlags::setDefined () inline
Sets the state of the flags to the defined state.
Definition at line 404 of file SelectionDAGNodes.h.
setExact()
void llvm::SDNodeFlags::setExact (bool b) inline
Definition at line 417 of file SelectionDAGNodes.h.
Referenced by BuildExactSDIV(), isVectorReductionOp(), and llvm::TargetLowering::SimplifyDemandedBits().
setNoFPExcept()
void llvm::SDNodeFlags::setNoFPExcept (bool b) inline
Definition at line 453 of file SelectionDAGNodes.h.
Referenced by isCalleeLoad(), and llvm::SelectionDAGISel::SelectCodeCommon().
setNoInfs()
void llvm::SDNodeFlags::setNoInfs (bool b) inline
Definition at line 425 of file SelectionDAGNodes.h.
References llvm::bitc::NoInfs.
Referenced by truncateScalarIntegerArg().
setNoNaNs()
void llvm::SDNodeFlags::setNoNaNs (bool b) inline
Definition at line 421 of file SelectionDAGNodes.h.
References llvm::bitc::NoNaNs.
Referenced by truncateScalarIntegerArg().
setNoSignedWrap()
void llvm::SDNodeFlags::setNoSignedWrap (bool b) inline
Definition at line 413 of file SelectionDAGNodes.h.
Referenced by isVectorReductionOp(), promoteExtBeforeAdd(), and llvm::TargetLowering::SimplifyDemandedBits().
setNoSignedZeros()
void llvm::SDNodeFlags::setNoSignedZeros (bool b) inline
Definition at line 429 of file SelectionDAGNodes.h.
References llvm::bitc::NoSignedZeros.
setNoUnsignedWrap()
void llvm::SDNodeFlags::setNoUnsignedWrap (bool b) inline
Definition at line 409 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getObjectPtrOffset(), getSPDenormModeValue(), isVectorReductionOp(), promoteExtBeforeAdd(), llvm::TargetLowering::SimplifyDemandedBits(), and widenCtPop().
setVectorReduction()
void llvm::SDNodeFlags::setVectorReduction (bool b) inline
Definition at line 437 of file SelectionDAGNodes.h.
Referenced by combineLoopMAddPattern(), combineLoopSADPattern(), and isVectorReductionOp().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h