LLVM: llvm::MDNodeKeyImpl< DILexicalBlockFile > Struct Template Reference
llvm::MDNodeKeyImpl< DILexicalBlockFile > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *Scope, Metadata *File, unsigned Discriminator)
MDNodeKeyImpl (const DILexicalBlockFile *N)
bool isKeyOf (const DILexicalBlockFile *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * Scope
Metadata * File
unsigned Discriminator
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DILexicalBlockFile >
Definition at line 750 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DILexicalBlockFile >::MDNodeKeyImpl (Metadata * Scope, Metadata * File, unsigned Discriminator) inline
Definition at line 755 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DILexicalBlockFile >::MDNodeKeyImpl (const DILexicalBlockFile * N) inline
Definition at line 757 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DILexicalBlockFile >::getHashValue () const inline
Definition at line 766 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DILexicalBlockFile >::isKeyOf (const DILexicalBlockFile * RHS) const inline
Definition at line 761 of file LLVMContextImpl.h.
References llvm::DILexicalBlockFile::getDiscriminator(), llvm::DIScope::getRawFile(), and llvm::DILexicalBlockBase::getRawScope().
Member Data Documentation
Discriminator
unsigned llvm::MDNodeKeyImpl< DILexicalBlockFile >::Discriminator
Definition at line 753 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DILexicalBlockFile >::File
Definition at line 752 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DILexicalBlockFile >::Scope
Definition at line 751 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h