LLVM: llvm::rdf::RefNode Struct Reference
llvm::rdf::RefNode Struct Reference
#include "Target/Hexagon/RDFGraph.h"
Public Member Functions
RefNode ()=default
RegisterRef getRegRef (const DataFlowGraph &G) const
MachineOperand & getOp ()
void setRegRef (RegisterRef RR, DataFlowGraph &G)
void setRegRef (MachineOperand *Op, DataFlowGraph &G)
NodeId getReachingDef () const
void setReachingDef (NodeId RD)
NodeId getSibling () const
void setSibling (NodeId Sib)
bool isUse () const
bool isDef () const
template<typename Predicate >
NodeAddr< RefNode * > getNextRef (RegisterRef RR, Predicate P, bool NextOnly, const DataFlowGraph &G)
NodeAddr< NodeBase * > getOwner (const DataFlowGraph &G)
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (NodeAddr< NodeBase *> NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct Ref
Code_struct Code
};
Detailed Description
Definition at line 515 of file RDFGraph.h.
Constructor & Destructor Documentation
RefNode()
llvm::rdf::RefNode::RefNode () default
Member Function Documentation
getNextRef()
template<typename Predicate > NodeAddr< RefNode * > llvm::rdf::RefNode::getNextRef (RegisterRef RR, Predicate P, bool NextOnly, const DataFlowGraph & G)
Definition at line 887 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), assert(), llvm::rdf::NodeAttrs::Code, P, RA, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DataFlowGraph::getNextRelated().
getOp()
MachineOperand& llvm::rdf::RefNode::getOp () inline
Definition at line 520 of file RDFGraph.h.
References assert(), getFlags(), llvm::rdf::NodeAttrs::PhiRef, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DataFlowGraph::getNextRelated().
getOwner()
NodeAddr< NodeBase * > RefNode::getOwner (const DataFlowGraph & G)
Definition at line 434 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::rdf::NodeAttrs::Code, llvm::rdf::NodeBase::getNext(), llvm::rdf::NodeBase::getType(), and llvm_unreachable.
Referenced by llvm::rdf::Liveness::computePhiInfo(), and DeadCodeElimination::SetQueue< T >::push_back().
getReachingDef()
NodeId llvm::rdf::RefNode::getReachingDef () const inline
Definition at line 528 of file RDFGraph.h.
References llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::DataFlowGraph::getNextShadow(), and llvm::rdf::CopyPropagation::interpretAsCopy().
getRegRef()
RegisterRef RefNode::getRegRef (const DataFlowGraph & G) const
Definition at line 408 of file RDFGraph.cpp.
References assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::rdf::NodeAttrs::flags(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::rdf::NodeAttrs::PhiRef, llvm::Ref, llvm::rdf::NodeAttrs::Ref, llvm::rdf::NodeAttrs::type(), and llvm::rdf::DataFlowGraph::unpack().
Referenced by llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::DataFlowGraph::getNextRelated(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::rdf::printRefHeader(), and llvm::rdf::DataFlowGraph::pushAllDefs().
getSibling()
NodeId llvm::rdf::RefNode::getSibling () const inline
Definition at line 535 of file RDFGraph.h.
References llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), llvm::rdf::DataFlowGraph::getNextShadow(), and llvm::rdf::CopyPropagation::run().
isDef()
bool llvm::rdf::RefNode::isDef () const inline
Definition at line 547 of file RDFGraph.h.
References assert(), llvm::rdf::NodeAttrs::Def, getType(), P, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DataFlowGraph::getNextShadow().
isUse()
bool llvm::rdf::RefNode::isUse () const inline
Definition at line 542 of file RDFGraph.h.
References assert(), getType(), llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::Use.
setReachingDef()
void llvm::rdf::RefNode::setReachingDef (NodeId RD) inline
Definition at line 531 of file RDFGraph.h.
References llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DataFlowGraph::id().
setRegRef() [1/2]
void RefNode::setRegRef (RegisterRef RR, DataFlowGraph & G)
Definition at line 418 of file RDFGraph.cpp.
References assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::rdf::NodeAttrs::flags(), llvm::rdf::DataFlowGraph::pack(), llvm::rdf::NodeAttrs::PhiRef, llvm::Ref, llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::type().
Referenced by llvm::rdf::DataFlowGraph::id().
setRegRef() [2/2]
void RefNode::setRegRef (MachineOperand * Op, DataFlowGraph & G)
Definition at line 426 of file RDFGraph.cpp.
References assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::rdf::NodeAttrs::flags(), llvm::rdf::NodeAttrs::PhiRef, llvm::Ref, llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::type().
setSibling()
void llvm::rdf::RefNode::setSibling (NodeId Sib) inline
Definition at line 538 of file RDFGraph.h.
References llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DataFlowGraph::id().
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/RDFGraph.h
lib/Target/Hexagon/RDFGraph.cpp