LLVM: llvm::MDNodeKeyImpl< DIObjCProperty > Struct Template Reference
llvm::MDNodeKeyImpl< DIObjCProperty > Struct Template Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (MDString *Name, Metadata *File, unsigned Line, MDString *GetterName, MDString *SetterName, unsigned Attributes, Metadata *Type)
MDNodeKeyImpl (const DIObjCProperty *N)
bool isKeyOf (const DIObjCProperty *RHS) const
unsigned getHashValue () const
Public Attributes
MDString * Name
Metadata * File
unsigned Line
MDString * GetterName
MDString * SetterName
unsigned Attributes
Metadata * Type
Detailed Description
template<>
struct llvm::MDNodeKeyImpl< DIObjCProperty >
Definition at line 1033 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIObjCProperty >::MDNodeKeyImpl (MDString * Name, Metadata * File, unsigned Line, MDString * GetterName, MDString * SetterName, unsigned Attributes, Metadata * Type) inline
Definition at line 1042 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIObjCProperty >::MDNodeKeyImpl (const DIObjCProperty * N) inline
Definition at line 1047 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::getHashValue () const inline
Definition at line 1059 of file LLVMContextImpl.h.
References llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf (const DIObjCProperty * RHS) const inline
Definition at line 1052 of file LLVMContextImpl.h.
References llvm::DIObjCProperty::getAttributes(), llvm::DIObjCProperty::getLine(), llvm::DIObjCProperty::getRawFile(), llvm::DIObjCProperty::getRawGetterName(), llvm::DIObjCProperty::getRawName(), llvm::DIObjCProperty::getRawSetterName(), and llvm::DIObjCProperty::getRawType().
Member Data Documentation
Attributes
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::Attributes
Definition at line 1039 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIObjCProperty >::File
Definition at line 1035 of file LLVMContextImpl.h.
GetterName
MDString* llvm::MDNodeKeyImpl< DIObjCProperty >::GetterName
Definition at line 1037 of file LLVMContextImpl.h.
Line
unsigned llvm::MDNodeKeyImpl< DIObjCProperty >::Line
Definition at line 1036 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIObjCProperty >::Name
Definition at line 1034 of file LLVMContextImpl.h.
SetterName
MDString* llvm::MDNodeKeyImpl< DIObjCProperty >::SetterName
Definition at line 1038 of file LLVMContextImpl.h.
Type
Metadata* llvm::MDNodeKeyImpl< DIObjCProperty >::Type
Definition at line 1040 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h