LLVM: llvm::DenseMapInfo< Register > Struct Template Reference
llvm::DenseMapInfo< Register > Struct Template Reference
#include "llvm/CodeGen/Register.h"
Static Public Member Functions
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
static unsigned getHashValue (const Register &Val)
static bool isEqual (const Register &LHS, const Register &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< Register >
Definition at line 139 of file Register.h.
Member Function Documentation
getEmptyKey()
static unsigned llvm::DenseMapInfo< Register >::getEmptyKey () inline static
Definition at line 140 of file Register.h.
getHashValue()
static unsigned llvm::DenseMapInfo< Register >::getHashValue (const Register & Val) inline static
Definition at line 146 of file Register.h.
References llvm::Register::id().
getTombstoneKey()
static unsigned llvm::DenseMapInfo< Register >::getTombstoneKey () inline static
Definition at line 143 of file Register.h.
isEqual()
static bool llvm::DenseMapInfo< Register >::isEqual (const Register & LHS, const Register & RHS) inline static
Definition at line 149 of file Register.h.
References llvm::Register::id(), and isEqual().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/Register.h