LLVM: llvm::LowerExpectIntrinsicPass Struct Reference
llvm::LowerExpectIntrinsicPass Struct Reference
#include "llvm/Transforms/Scalar/LowerExpectIntrinsic.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &)
Run the pass over the function.
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LowerExpectIntrinsicPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file LowerExpectIntrinsic.h.
Member Function Documentation
run()
PreservedAnalyses LowerExpectIntrinsicPass::run (Function & F, FunctionAnalysisManager &)
Run the pass over the function.
This will lower all of the expect intrinsic calls in this function into branch weight metadata. That metadata will subsequently feed the analysis of the probabilities and frequencies of the CFG. After running this pass, no more expect intrinsics remain, allowing the rest of the optimizer to ignore them.
Definition at line 366 of file LowerExpectIntrinsic.cpp.
References llvm::PreservedAnalyses::all(), F(), llvm::PassRegistry::getPassRegistry(), llvm::initializeLowerExpectIntrinsicPass(), lowerExpectIntrinsic(), llvm::PreservedAnalyses::none(), and runOnFunction().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/LowerExpectIntrinsic.h
lib/Transforms/Scalar/LowerExpectIntrinsic.cpp