LLVM: llvm::HexagonSubtarget::BankConflictMutation Struct Reference
llvm::HexagonSubtarget::BankConflictMutation Struct Reference
#include "Target/Hexagon/HexagonSubtarget.h"
Public Member Functions
void apply (ScheduleDAGInstrs *DAG) override
Public Member Functions inherited from llvm::ScheduleDAGMutation
virtual ~ScheduleDAGMutation ()=default
Detailed Description
Definition at line 81 of file HexagonSubtarget.h.
Member Function Documentation
apply()
void HexagonSubtarget::BankConflictMutation::apply (ScheduleDAGInstrs * DAG) override virtual
Implements llvm::ScheduleDAGMutation.
Definition at line 262 of file HexagonSubtarget.cpp.
References llvm::SUnit::addPred(), llvm::SDep::Artificial, llvm::HexagonII::BaseImmOffset, llvm::numbers::e, EnableCheckBankConflict, llvm::HexagonInstrInfo::getAddrMode(), llvm::HexagonInstrInfo::getBaseAndOffset(), llvm::SUnit::getInstr(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::SDep::setLatency(), llvm::ScheduleDAG::SUnits, and llvm::ScheduleDAG::TII.
The documentation for this struct was generated from the following files:
lib/Target/Hexagon/HexagonSubtarget.h
lib/Target/Hexagon/HexagonSubtarget.cpp