LLVM: NewGVN::ValueDFS Struct Reference
NewGVN::ValueDFS Struct Reference
Public Member Functions
bool operator< (const ValueDFS &Other) const
Public Attributes
int DFSIn = 0
int DFSOut = 0
int LocalNum = 0
PointerIntPair< Value *, 1, bool > Def
Use * U = nullptr
Detailed Description
Definition at line 3499 of file NewGVN.cpp.
Member Function Documentation
operator<()
bool NewGVN::ValueDFS::operator< (const ValueDFS & Other) const inline
Definition at line 3510 of file NewGVN.cpp.
References alwaysAvailable(), assert(), D, llvm::tgtok::Def, Def, DFSIn, DFSOut, llvm::SmallVectorImpl< T >::emplace_back(), llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), llvm::DomTreeNodeBase< NodeT >::getDFSNumOut(), llvm::StoreInst::getValueOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm_unreachable, LocalNum, P, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setPointer(), U, and llvm::Value::uses().
Member Data Documentation
Def
PointerIntPair<Value *, 1, bool> NewGVN::ValueDFS::Def
Definition at line 3507 of file NewGVN.cpp.
Referenced by operator<().
DFSIn
int NewGVN::ValueDFS::DFSIn = 0
Definition at line 3500 of file NewGVN.cpp.
Referenced by operator<().
DFSOut
int NewGVN::ValueDFS::DFSOut = 0
Definition at line 3501 of file NewGVN.cpp.
Referenced by operator<().
LocalNum
int NewGVN::ValueDFS::LocalNum = 0
Definition at line 3502 of file NewGVN.cpp.
Referenced by operator<().
U
Use* NewGVN::ValueDFS::U = nullptr
Definition at line 3508 of file NewGVN.cpp.
Referenced by operator<().
The documentation for this struct was generated from the following file:
lib/Transforms/Scalar/NewGVN.cpp