LLVM: llvm::GraphTraits< DDGNode * > Struct Template Reference
llvm::GraphTraits< DDGNode * > Struct Template Reference
non-const versions of the grapth trait specializations for DDG
#include "llvm/Analysis/DDG.h"
Public Types
using NodeRef = DDGNode *
using ChildIteratorType = mapped_iterator< DDGNode::iterator, decltype(&DDGGetTargetNode)>
using ChildEdgeIteratorType = DDGNode::iterator
Static Public Member Functions
static DDGNode * DDGGetTargetNode (DGEdge< DDGNode, DDGEdge > *P)
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
Detailed Description
template<>
struct llvm::GraphTraits< DDGNode * >
non-const versions of the grapth trait specializations for DDG
Definition at line 431 of file DDG.h.
Member Typedef Documentation
ChildEdgeIteratorType
using llvm::GraphTraits< DDGNode * >::ChildEdgeIteratorType = DDGNode::iterator
Definition at line 442 of file DDG.h.
ChildIteratorType
using llvm::GraphTraits< DDGNode * >::ChildIteratorType = mapped_iterator<DDGNode::iterator, decltype(&DDGGetTargetNode)>
Definition at line 441 of file DDG.h.
NodeRef
using llvm::GraphTraits< DDGNode * >::NodeRef = DDGNode *
Definition at line 432 of file DDG.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< DDGNode * >::child_begin (NodeRef N) inline static
Definition at line 445 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::begin().
child_edge_begin()
static ChildEdgeIteratorType llvm::GraphTraits< DDGNode * >::child_edge_begin (NodeRef N) inline static
Definition at line 452 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::begin().
child_edge_end()
static ChildEdgeIteratorType llvm::GraphTraits< DDGNode * >::child_edge_end (NodeRef N) inline static
Definition at line 455 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::end().
child_end()
static ChildIteratorType llvm::GraphTraits< DDGNode * >::child_end (NodeRef N) inline static
Definition at line 448 of file DDG.h.
References llvm::DGNode< NodeType, EdgeType >::end().
DDGGetTargetNode()
static DDGNode* llvm::GraphTraits< DDGNode * >::DDGGetTargetNode (DGEdge< DDGNode, DDGEdge > * P) inline static
Definition at line 434 of file DDG.h.
References llvm::DGEdge< NodeType, EdgeType >::getTargetNode().
getEntryNode()
static NodeRef llvm::GraphTraits< DDGNode * >::getEntryNode (NodeRef N) inline static
Definition at line 444 of file DDG.h.
References N.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DDG.h