LLVM: llvm::BPFRegisterInfo Struct Reference
llvm::BPFRegisterInfo Struct Reference
#include "Target/BPF/BPFRegisterInfo.h"
Public Member Functions
BPFRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 23 of file BPFRegisterInfo.h.
Constructor & Destructor Documentation
BPFRegisterInfo()
BPFRegisterInfo::BPFRegisterInfo ()
Definition at line 29 of file BPFRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void BPFRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 56 of file BPFRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineInstr::eraseFromParent(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineOperand::isFI(), llvm::isInt< 32 >(), llvm_unreachable, MI, TII, and WarnSize().
getCalleeSavedRegs()
const MCPhysReg * BPFRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 33 of file BPFRegisterInfo.cpp.
getFrameRegister()
Register BPFRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 124 of file BPFRegisterInfo.cpp.
Referenced by eliminateFrameIndex().
getReservedRegs()
BitVector BPFRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 37 of file BPFRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/BPF/BPFRegisterInfo.h
lib/Target/BPF/BPFRegisterInfo.cpp