LLVM: llvm::ARCRegisterInfo Struct Reference
llvm::ARCRegisterInfo Struct Reference
#include "Target/ARC/ARCRegisterInfo.h"
Public Member Functions
ARCRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
Register getFrameRegister (const MachineFunction &MF) const override
Static Public Member Functions
static bool needsFrameMoves (const MachineFunction &MF)
Return whether to emit frame moves.
Detailed Description
Definition at line 25 of file ARCRegisterInfo.h.
Constructor & Destructor Documentation
ARCRegisterInfo()
ARCRegisterInfo::ARCRegisterInfo ()
Definition at line 128 of file ARCRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void ARCRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 165 of file ARCRegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), contains(), llvm::dbgs(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::ARCFrameLowering::hasFP(), llvm::MachineInstr::isDebugValue(), LLVM_DEBUG, MI, Reg, ReplaceFrameIndex(), and TII.
getCalleeSavedRegs()
const MCPhysReg * ARCRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 135 of file ARCRegisterInfo.cpp.
getCallPreservedMask()
const uint32_t * ARCRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 232 of file ARCRegisterInfo.cpp.
getFrameRegister()
Register ARCRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 226 of file ARCRegisterInfo.cpp.
References llvm::ARCFrameLowering::hasFP().
Referenced by eliminateFrameIndex(), and llvm::ARCTargetLowering::isLegalAddressingMode().
getReservedRegs()
BitVector ARCRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 139 of file ARCRegisterInfo.cpp.
References llvm::BitVector::set().
needsFrameMoves()
bool ARCRegisterInfo::needsFrameMoves (const MachineFunction & MF) static
Return whether to emit frame moves.
Definition at line 130 of file ARCRegisterInfo.cpp.
References llvm::MachineFunction::needsFrameMoves().
requiresRegisterScavenging()
bool ARCRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const override
Definition at line 151 of file ARCRegisterInfo.cpp.
trackLivenessAfterRegAlloc()
bool ARCRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const override
Definition at line 156 of file ARCRegisterInfo.cpp.
useFPForScavengingIndex()
bool ARCRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const override
Definition at line 161 of file ARCRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/ARC/ARCRegisterInfo.h
lib/Target/ARC/ARCRegisterInfo.cpp