LLVM: llvm::MinidumpYAML::Object Struct Reference
llvm::MinidumpYAML::Object Struct Reference
The top level structure representing a minidump object, consisting of a minidump header, and zero or more streams.
#include "llvm/ObjectYAML/MinidumpYAML.h"
Public Member Functions
Object ()=default
Object (const Object &)=delete
Object & operator= (const Object &)=delete
Object (Object &&)=default
Object & operator= (Object &&)=default
Object (const minidump::Header &Header, std::vector< std::unique_ptr< Stream >> Streams)
Static Public Member Functions
static Expected< Object > create (const object::MinidumpFile &File)
Public Attributes
minidump::Header Header
The minidump header.
std::vector< std::unique_ptr< Stream > > Streams
The list of streams in this minidump object.
Detailed Description
The top level structure representing a minidump object, consisting of a minidump header, and zero or more streams.
To construct an Object from a minidump file, use the static create function. To serialize to/from yaml, use the appropriate streaming operator on a yaml stream.
Definition at line 201 of file MinidumpYAML.h.
Constructor & Destructor Documentation
Object() [1/4]
llvm::MinidumpYAML::Object::Object () default
Object() [2/4]
llvm::MinidumpYAML::Object::Object (const Object &) delete
Object() [3/4]
llvm::MinidumpYAML::Object::Object (Object &&) default
Object() [4/4]
llvm::MinidumpYAML::Object::Object (const minidump::Header & Header, std::vector< std::unique_ptr< Stream >> Streams) inline
Definition at line 208 of file MinidumpYAML.h.
Member Function Documentation
create()
Expected< Object > Object::create (const object::MinidumpFile & File) static
Definition at line 553 of file MinidumpYAML.cpp.
References llvm::MinidumpYAML::Stream::create(), llvm::object::MinidumpFile::header(), and llvm::object::MinidumpFile::streams().
operator=() [1/2]
Object& llvm::MinidumpYAML::Object::operator= (const Object &) delete
operator=() [2/2]
Object& llvm::MinidumpYAML::Object::operator= (Object &&) default
Member Data Documentation
Header
minidump::Header llvm::MinidumpYAML::Object::Header
The minidump header.
Definition at line 213 of file MinidumpYAML.h.
Referenced by streamMapping(), and llvm::yaml::yaml2minidump().
Streams
std::vector<std::unique_ptr<Stream> > llvm::MinidumpYAML::Object::Streams
The list of streams in this minidump object.
Definition at line 216 of file MinidumpYAML.h.
Referenced by streamMapping(), and llvm::yaml::yaml2minidump().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/MinidumpYAML.h
lib/ObjectYAML/MinidumpYAML.cpp