LLVM: llvm::PredicateInfoClasses::ValueDFS_Compare Struct Reference
llvm::PredicateInfoClasses::ValueDFS_Compare Struct Reference
Public Member Functions
ValueDFS_Compare (DominatorTree &DT, OrderedInstructions &OI)
bool operator() (const ValueDFS &A, const ValueDFS &B) const
const std::pair< BasicBlock *, BasicBlock * > getBlockEdge (const ValueDFS &VD) const
bool comparePHIRelated (const ValueDFS &A, const ValueDFS &B) const
Value * getMiddleDef (const ValueDFS &VD) const
const Instruction * getDefOrUser (const Value *Def, const Use *U) const
bool localComesBefore (const ValueDFS &A, const ValueDFS &B) const
Public Attributes
DominatorTree & DT
OrderedInstructions & OI
Detailed Description
Definition at line 128 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
ValueDFS_Compare()
llvm::PredicateInfoClasses::ValueDFS_Compare::ValueDFS_Compare (DominatorTree & DT, OrderedInstructions & OI) inline
Definition at line 131 of file PredicateInfo.cpp.
Member Function Documentation
comparePHIRelated()
bool llvm::PredicateInfoClasses::ValueDFS_Compare::comparePHIRelated (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 173 of file PredicateInfo.cpp.
References assert(), llvm::PredicateInfoClasses::ValueDFS::Def, llvm::PredicateInfoClasses::ValueDFS::DFSIn, llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), and llvm::PredicateInfoClasses::ValueDFS::U.
getBlockEdge()
const std::pair<BasicBlock *, BasicBlock *> llvm::PredicateInfoClasses::ValueDFS_Compare::getBlockEdge (const ValueDFS & VD) const inline
Definition at line 163 of file PredicateInfo.cpp.
References llvm::PredicateInfoClasses::ValueDFS::Def, llvm::PredicateInfoClasses::ValueDFS::PInfo, and llvm::PredicateInfoClasses::ValueDFS::U.
getDefOrUser()
const Instruction* llvm::PredicateInfoClasses::ValueDFS_Compare::getDefOrUser (const Value * Def, const Use * U) const inline
Definition at line 227 of file PredicateInfo.cpp.
References llvm::tgtok::Def.
getMiddleDef()
Value* llvm::PredicateInfoClasses::ValueDFS_Compare::getMiddleDef (const ValueDFS & VD) const inline
Definition at line 206 of file PredicateInfo.cpp.
References assert(), llvm::PredicateInfoClasses::ValueDFS::Def, llvm::PredicateInfoClasses::ValueDFS::PInfo, and llvm::PredicateInfoClasses::ValueDFS::U.
localComesBefore()
bool llvm::PredicateInfoClasses::ValueDFS_Compare::localComesBefore (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 235 of file PredicateInfo.cpp.
References llvm::PredicateInfoClasses::ValueDFS::DFSIn, llvm::PredicateInfoClasses::ValueDFS::DFSOut, llvm::dyn_cast(), llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), llvm::DomTreeNodeBase< NodeT >::getDFSNumOut(), I, llvm::PredicateInfoClasses::LN_Last, llvm::PredicateInfoClasses::LN_Middle, llvm::PredicateInfoClasses::ValueDFS::LocalNum, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::PredicateInfoClasses::ValueDFS::U, llvm::Value::uses(), and llvm::PredicateInfoClasses::valueComesBefore().
operator()()
bool llvm::PredicateInfoClasses::ValueDFS_Compare::operator() (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 134 of file PredicateInfo.cpp.
References assert(), llvm::PredicateInfoClasses::ValueDFS::Def, llvm::PredicateInfoClasses::ValueDFS::DFSIn, llvm::PredicateInfoClasses::ValueDFS::DFSOut, llvm::PredicateInfoClasses::LN_Last, llvm::PredicateInfoClasses::LN_Middle, and llvm::PredicateInfoClasses::ValueDFS::LocalNum.
Member Data Documentation
DT
DominatorTree& llvm::PredicateInfoClasses::ValueDFS_Compare::DT
Definition at line 129 of file PredicateInfo.cpp.
OI
OrderedInstructions& llvm::PredicateInfoClasses::ValueDFS_Compare::OI
Definition at line 130 of file PredicateInfo.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp