LLVM: llvm::VERegisterInfo Struct Reference
llvm::VERegisterInfo Struct Reference
#include "Target/VE/VERegisterInfo.h"
Public Member Functions
VERegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
const uint32_t * getNoPreservedMask () const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool isConstantPhysReg (unsigned PhysReg) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
bool canRealignStack (const MachineFunction &MF) const override
Detailed Description
Definition at line 22 of file VERegisterInfo.h.
Constructor & Destructor Documentation
VERegisterInfo()
VERegisterInfo::VERegisterInfo ()
Definition at line 33 of file VERegisterInfo.cpp.
Member Function Documentation
canRealignStack()
bool VERegisterInfo::canRealignStack (const MachineFunction & MF) const override
Definition at line 116 of file VERegisterInfo.cpp.
References llvm::TargetRegisterInfo::canRealignStack().
eliminateFrameIndex()
void VERegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 88 of file VERegisterInfo.cpp.
References assert(), llvm::ISD::FrameIndex, llvm::MachineInstr::getDebugLoc(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), MI, and replaceFI().
getCalleeSavedRegs()
const MCPhysReg * VERegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 36 of file VERegisterInfo.cpp.
getCallPreservedMask()
const uint32_t * VERegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 40 of file VERegisterInfo.cpp.
getFrameRegister()
Register VERegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 108 of file VERegisterInfo.cpp.
getNoPreservedMask()
const uint32_t * VERegisterInfo::getNoPreservedMask () const override
Definition at line 45 of file VERegisterInfo.cpp.
getPointerRegClass()
const TargetRegisterClass * VERegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind) const override
Definition at line 73 of file VERegisterInfo.cpp.
getReservedRegs()
BitVector VERegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 49 of file VERegisterInfo.cpp.
References llvm::BitVector::set().
isConstantPhysReg()
bool VERegisterInfo::isConstantPhysReg (unsigned PhysReg) const override
Definition at line 70 of file VERegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/VE/VERegisterInfo.h
lib/Target/VE/VERegisterInfo.cpp