LLVM: NoAutoPaddingScope Struct Reference
NoAutoPaddingScope Struct Reference
A RAII helper which defines a region of instructions which can't have padding added between them for correctness.
Public Member Functions
NoAutoPaddingScope (MCStreamer &OS)
~NoAutoPaddingScope ()
void changeAndComment (bool b)
Public Attributes
MCStreamer & OS
const bool OldAllowAutoPadding
Detailed Description
A RAII helper which defines a region of instructions which can't have padding added between them for correctness.
Definition at line 1166 of file X86MCInstLower.cpp.
Constructor & Destructor Documentation
NoAutoPaddingScope()
NoAutoPaddingScope::NoAutoPaddingScope (MCStreamer & OS) inline
Definition at line 1169 of file X86MCInstLower.cpp.
~NoAutoPaddingScope()
NoAutoPaddingScope::~NoAutoPaddingScope () inline
Definition at line 1173 of file X86MCInstLower.cpp.
Member Function Documentation
changeAndComment()
void NoAutoPaddingScope::changeAndComment (bool b) inline
Definition at line 1176 of file X86MCInstLower.cpp.
References llvm::MCStreamer::AddComment(), addOperand(), llvm::MCInst::addOperand(), assert(), convertTailJumpOpcode(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createImm(), llvm::MachineOperand::CreateMCSymbol(), llvm::MCOperand::createReg(), llvm::MCContext::createTempSymbol(), llvm::AsmPrinter::CUSTOM_EVENT, E, llvm::MCStreamer::EmitBinaryData(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitCodeAlignment(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), EmitNop(), EmitNops(), llvm::MCStreamer::emitRawComment(), llvm::MCCodeEmitter::encodeInstruction(), F(), llvm::FaultMaps::FaultKindMax, llvm::AsmPrinter::FUNCTION_ENTER, llvm::AsmPrinter::FUNCTION_EXIT, llvm::MCStreamer::getAllowAutoPadding(), llvm::StringRef::getAsInteger(), llvm::PatchPointOpers::getCallTarget(), llvm::StatepointOpers::getCallTarget(), llvm::MCStreamer::getContext(), llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MCSymbol::getName(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::MachineInstr::getNumOperands(), llvm::PatchPointOpers::getNumPatchBytes(), llvm::StatepointOpers::getNumPatchBytes(), llvm::MachineInstr::getOperand(), llvm::MCContext::getOrCreateSymbol(), llvm::MachineOperand::getReg(), llvm::AsmPrinter::getSubtargetInfo(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getType(), llvm::Attribute::getValueAsString(), llvm::getX86SubSuperRegister(), llvm::Function::hasFnAttribute(), I, llvm::MachineOperand::isImm(), llvm::AsmPrinter::isPositionIndependent(), llvm::X86II::isX86_64ExtendedReg(), llvm_unreachable, llvm::make_range(), llvm::AsmPrinter::MF, MI, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::X86II::MO_PLT, llvm::MachineOperand::MO_Register, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::recordSled(), llvm::report_fatal_error(), llvm::MipsISD::Ret, llvm::MCStreamer::setAllowAutoPadding(), llvm::MCInst::setOpcode(), llvm::MachineOperand::setTargetFlags(), llvm::SmallVectorBase::size(), llvm::AsmPrinter::TAIL_CALL, llvm::AsmPrinter::TYPED_EVENT, and llvm::MCSymbolRefExpr::VK_None.
Member Data Documentation
OldAllowAutoPadding
const bool NoAutoPaddingScope::OldAllowAutoPadding
Definition at line 1168 of file X86MCInstLower.cpp.
OS
MCStreamer& NoAutoPaddingScope::OS
Definition at line 1167 of file X86MCInstLower.cpp.
The documentation for this struct was generated from the following file:
lib/Target/X86/X86MCInstLower.cpp