LLVM: llvm::DenseMapInfo< coverage::CounterExpression > Struct Template Reference
llvm::DenseMapInfo< coverage::CounterExpression > Struct Template Reference
Provide DenseMapInfo for CounterExpression.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Static Public Member Functions
static coverage::CounterExpression getEmptyKey ()
static coverage::CounterExpression getTombstoneKey ()
static unsigned getHashValue (const coverage::CounterExpression &V)
static bool isEqual (const coverage::CounterExpression &LHS, const coverage::CounterExpression &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< coverage::CounterExpression >
Provide DenseMapInfo for CounterExpression.
Definition at line 801 of file CoverageMapping.h.
Member Function Documentation
getEmptyKey()
static coverage::CounterExpression llvm::DenseMapInfo< coverage::CounterExpression >::getEmptyKey () inline static
Definition at line 802 of file CoverageMapping.h.
References llvm::coverage::Counter::getCounter().
getHashValue()
static unsigned llvm::DenseMapInfo< coverage::CounterExpression >::getHashValue (const coverage::CounterExpression & V) inline static
Definition at line 818 of file CoverageMapping.h.
References llvm::coverage::Counter::getCounterID(), llvm::coverage::Counter::getKind(), llvm::hash_combine(), llvm::coverage::CounterExpression::Kind, llvm::coverage::CounterExpression::LHS, and llvm::coverage::CounterExpression::RHS.
getTombstoneKey()
static coverage::CounterExpression llvm::DenseMapInfo< coverage::CounterExpression >::getTombstoneKey () inline static
Definition at line 810 of file CoverageMapping.h.
References llvm::MCID::Add, and llvm::coverage::Counter::getCounter().
isEqual()
static bool llvm::DenseMapInfo< coverage::CounterExpression >::isEqual (const coverage::CounterExpression & LHS, const coverage::CounterExpression & RHS) inline static
Definition at line 824 of file CoverageMapping.h.
References llvm::coverage::CounterExpression::Kind, llvm::coverage::CounterExpression::LHS, and llvm::coverage::CounterExpression::RHS.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h