LLVM: llvm::yaml::ScalarTraits< SwiftVersion > Struct Template Reference
llvm::yaml::ScalarTraits< SwiftVersion > Struct Template Reference
#include "TextAPI/MachO/TextStubCommon.h"
Static Public Member Functions
static void output (const SwiftVersion &, void *, raw_ostream &)
static StringRef input (StringRef, void *, SwiftVersion &)
static QuotingType mustQuote (StringRef)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< SwiftVersion >
Definition at line 66 of file TextStubCommon.h.
Member Function Documentation
input()
StringRef llvm::yaml::ScalarTraits< SwiftVersion >::input (StringRef Scalar, void * IO, SwiftVersion & Value) static
Definition at line 175 of file TextStubCommon.cpp.
References assert(), llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::StringRef::getAsInteger(), llvm::Invalid, llvm::NVPTX::PTXLdStInstCode::Scalar, and llvm::MachO::TBD_V4.
mustQuote()
QuotingType llvm::yaml::ScalarTraits< SwiftVersion >::mustQuote (StringRef) static
Definition at line 202 of file TextStubCommon.cpp.
References llvm::MachO::None.
output()
void llvm::yaml::ScalarTraits< SwiftVersion >::output (const SwiftVersion & Value, void * , raw_ostream & OS) static
Definition at line 155 of file TextStubCommon.cpp.
The documentation for this struct was generated from the following files:
lib/TextAPI/MachO/TextStubCommon.h
lib/TextAPI/MachO/TextStubCommon.cpp