LLVM: lib/LTO/SummaryBasedOptimizations.cpp File Reference
SummaryBasedOptimizations.cpp File Reference
#include "llvm/LTO/SummaryBasedOptimizations.h"
#include "llvm/Analysis/SyntheticCountsUtils.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/Support/CommandLine.h"
Functions
static void initializeCounts (ModuleSummaryIndex &Index)
Variables
static cl::opt< bool > ThinLTOSynthesizeEntryCounts ("thinlto-synthesize-entry-counts", cl::init(false), cl::Hidden, cl::desc("Synthesize entry counts based on the summary"))
cl::opt< int > InitialSyntheticCount
Initial synthetic count assigned to functions.
Function Documentation
initializeCounts()
static void initializeCounts (ModuleSummaryIndex & Index) static
Definition at line 28 of file SummaryBasedOptimizations.cpp.
References C, llvm::ModuleSummaryIndex::calculateCallGraphRoot(), and F().
Referenced by llvm::computeSyntheticCounts().
Variable Documentation
InitialSyntheticCount
cl::opt<int> InitialSyntheticCount
Initial synthetic count assigned to functions.
Referenced by initializeCounts().
ThinLTOSynthesizeEntryCounts
cl::opt<bool> ThinLTOSynthesizeEntryCounts("thinlto-synthesize-entry-counts", cl::init(false), cl::Hidden, cl::desc("Synthesize entry counts based on the summary")) static
Referenced by llvm::computeSyntheticCounts().