LLVM: lib/DebugInfo/CodeView/SymbolDumper.cpp File Reference
SymbolDumper.cpp File Reference
#include "llvm/DebugInfo/CodeView/SymbolDumper.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/DebugInfo/CodeView/CVSymbolVisitor.h"
#include "llvm/DebugInfo/CodeView/DebugStringTableSubsection.h"
#include "llvm/DebugInfo/CodeView/EnumTables.h"
#include "llvm/DebugInfo/CodeView/SymbolDeserializer.h"
#include "llvm/DebugInfo/CodeView/SymbolDumpDelegate.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/SymbolVisitorCallbackPipeline.h"
#include "llvm/DebugInfo/CodeView/SymbolVisitorCallbacks.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ScopedPrinter.h"
#include <system_error>
#include "llvm/DebugInfo/CodeView/CodeViewSymbols.def"
Macros
#define SYMBOL_RECORD(EnumName, EnumVal, Name) Error visitKnownRecord(CVSymbol &CVR, Name &Record) override;
CVSymbolVisitor overrides.
#define SYMBOL_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
#define SYMBOL_RECORD(EnumName, EnumVal, Name)
CVSymbolVisitor overrides.
Functions
static StringRef getSymbolKindName (SymbolKind Kind)
Macro Definition Documentation
SYMBOL_RECORD [1/2]
#define SYMBOL_RECORD (EnumName, EnumVal, Name) Error visitKnownRecord(CVSymbol &CVR, Name &Record) override;
CVSymbolVisitor overrides.
Definition at line 39 of file SymbolDumper.cpp.
SYMBOL_RECORD [2/2]
#define SYMBOL_RECORD (EnumName, EnumVal, Name)
Value:
case EnumName:                                                               \
    return #Name;
CVSymbolVisitor overrides.
Definition at line 39 of file SymbolDumper.cpp.
SYMBOL_RECORD_ALIAS
#define SYMBOL_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
Definition at line 41 of file SymbolDumper.cpp.
Function Documentation
getSymbolKindName()
static StringRef getSymbolKindName (SymbolKind Kind) static
Definition at line 68 of file SymbolDumper.cpp.
References llvm::codeview::SectionSym::Alignment, llvm::codeview::DefRangeRegisterRelHeader::BasePointerOffset, llvm::codeview::BuildInfoSym::BuildId, llvm::codeview::SectionSym::Characteristics, llvm::codeview::CoffGroupSym::Characteristics, llvm::codeview::BlockSym::CodeOffset, llvm::codeview::CallSiteInfoSym::CodeOffset, llvm::codeview::BlockSym::CodeSize, llvm::codeview::CVRecord< Kind >::content(), llvm::Data, llvm::codeview::DataSym::DataOffset, llvm::StringRef::empty(), llvm::codeview::Thunk32Sym::End, llvm::codeview::BlockSym::End, llvm::codeview::EnvBlockSym::Fields, llvm::codeview::ExportSym::Flags, llvm::codeview::FileStaticSym::Flags, llvm::codeview::DefRangeRegisterSym::Gaps, llvm::codeview::DefRangeSubfieldRegisterSym::Gaps, llvm::codeview::DefRangeFramePointerRelSym::Gaps, llvm::codeview::DefRangeRegisterRelSym::Gaps, llvm::codeview::getCompileSym2FlagNames(), llvm::codeview::getCompileSym3FlagNames(), llvm::codeview::getCPUTypeNames(), llvm::codeview::getExportSymFlagNames(), llvm::codeview::Compile2Sym::getFlags(), llvm::codeview::Compile3Sym::getFlags(), llvm::codeview::getImageSectionCharacteristicNames(), llvm::codeview::Compile2Sym::getLanguage(), llvm::codeview::Compile3Sym::getLanguage(), llvm::codeview::getLocalFlagNames(), llvm::codeview::getRegisterNames(), llvm::codeview::DefRangeRegisterSym::getRelocationOffset(), llvm::codeview::DefRangeSubfieldRegisterSym::getRelocationOffset(), llvm::codeview::DefRangeFramePointerRelSym::getRelocationOffset(), llvm::codeview::DefRangeRegisterRelSym::getRelocationOffset(), llvm::codeview::BlockSym::getRelocationOffset(), llvm::codeview::CallSiteInfoSym::getRelocationOffset(), llvm::codeview::DataSym::getRelocationOffset(), llvm::codeview::getSourceLanguageNames(), llvm::codeview::getSymbolTypeNames(), llvm::codeview::getThunkOrdinalNames(), llvm::codeview::getTrampolineNames(), llvm::codeview::DefRangeRegisterRelSym::hasSpilledUDTMember(), llvm::codeview::DefRangeRegisterSym::Hdr, llvm::codeview::DefRangeSubfieldRegisterSym::Hdr, llvm::codeview::DefRangeFramePointerRelSym::Hdr, llvm::codeview::DefRangeRegisterRelSym::Hdr, llvm::codeview::FileStaticSym::Index, llvm::codeview::LocalVariableAddrRange::ISectStart, llvm::codeview::CVRecord< Kind >::kind(), llvm::codeview::Thunk32Sym::Length, llvm::codeview::SectionSym::Length, llvm::LinkageName, llvm::codeview::Compile2Sym::Machine, llvm::codeview::Compile3Sym::Machine, llvm::codeview::DefRangeRegisterHeader::MayHaveNoName, llvm::codeview::DefRangeSubfieldRegisterHeader::MayHaveNoName, llvm::codeview::FileStaticSym::ModFilenameOffset, llvm::codeview::Thunk32Sym::Name, llvm::codeview::SectionSym::Name, llvm::codeview::CoffGroupSym::Name, llvm::codeview::BlockSym::Name, llvm::codeview::ExportSym::Name, llvm::codeview::FileStaticSym::Name, llvm::codeview::BPRelativeSym::Name, llvm::codeview::ConstantSym::Name, llvm::codeview::DataSym::Name, llvm::codeview::Thunk32Sym::Next, llvm::codeview::Thunk32Sym::Offset, llvm::codeview::CoffGroupSym::Offset, llvm::codeview::DefRangeFramePointerRelHeader::Offset, llvm::codeview::DefRangeFramePointerRelFullScopeSym::Offset, llvm::codeview::BPRelativeSym::Offset, llvm::codeview::DefRangeSubfieldRegisterHeader::OffsetInParent, llvm::codeview::DefRangeRegisterRelSym::offsetInParent(), llvm::codeview::LocalVariableAddrRange::OffsetStart, llvm::codeview::ExportSym::Ordinal, llvm::codeview::Thunk32Sym::Parent, llvm::codeview::BlockSym::Parent, llvm::codeview::printTypeIndex(), llvm::codeview::LocalVariableAddrRange::Range, llvm::codeview::DefRangeRegisterSym::Range, llvm::codeview::DefRangeSubfieldRegisterSym::Range, llvm::codeview::DefRangeFramePointerRelSym::Range, llvm::codeview::DefRangeRegisterRelSym::Range, llvm::codeview::DefRangeRegisterHeader::Register, llvm::codeview::DefRangeSubfieldRegisterHeader::Register, llvm::codeview::DefRangeRegisterRelHeader::Register, llvm::codeview::SectionSym::Rva, llvm::ARMBuildAttrs::Section, llvm::codeview::SectionSym::SectionNumber, llvm::codeview::Thunk32Sym::Segment, llvm::codeview::CoffGroupSym::Segment, llvm::codeview::BlockSym::Segment, llvm::codeview::CallSiteInfoSym::Segment, llvm::codeview::TrampolineSym::Size, llvm::codeview::CoffGroupSym::Size, llvm::Error::success(), llvm::codeview::TrampolineSym::TargetOffset, llvm::codeview::TrampolineSym::TargetSection, llvm::codeview::Thunk32Sym::Thunk, llvm::codeview::TrampolineSym::ThunkOffset, llvm::codeview::TrampolineSym::ThunkSection, llvm::codeview::TrampolineSym::Type, llvm::codeview::CallSiteInfoSym::Type, llvm::codeview::BPRelativeSym::Type, llvm::codeview::ConstantSym::Type, llvm::codeview::DataSym::Type, llvm::codeview::ConstantSym::Value, llvm::codeview::Compile2Sym::Version, llvm::codeview::Compile3Sym::Version, llvm::codeview::Compile2Sym::VersionBackendBuild, llvm::codeview::Compile3Sym::VersionBackendBuild, llvm::codeview::Compile2Sym::VersionBackendMajor, llvm::codeview::Compile3Sym::VersionBackendMajor, llvm::codeview::Compile2Sym::VersionBackendMinor, llvm::codeview::Compile3Sym::VersionBackendMinor, llvm::codeview::Compile3Sym::VersionBackendQFE, llvm::codeview::Compile2Sym::VersionFrontendBuild, llvm::codeview::Compile3Sym::VersionFrontendBuild, llvm::codeview::Compile2Sym::VersionFrontendMajor, llvm::codeview::Compile3Sym::VersionFrontendMajor, llvm::codeview::Compile2Sym::VersionFrontendMinor, llvm::codeview::Compile3Sym::VersionFrontendMinor, llvm::codeview::Compile3Sym::VersionFrontendQFE, visitKnownRecord(), and llvm::RISCVFenceField::W.