LLVM: lib/Transforms/Utils/SymbolRewriter.cpp File Reference
SymbolRewriter.cpp File Reference
#include "llvm/Transforms/Utils/SymbolRewriter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/ilist.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLParser.h"
#include <memory>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "symbol-rewriter"
Functions
static void rewriteComdat (Module &M, GlobalObject *GO, const std::string &Source, const std::string &Target)
INITIALIZE_PASS (RewriteSymbolsLegacyPass, "rewrite-symbols", "Rewrite Symbols", false, false) ModulePass *llvm
Variables
static cl::list< std::string > RewriteMapFiles ("rewrite-map-file", cl::desc("Symbol Rewrite Map"), cl::value_desc("filename"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "symbol-rewriter"
Definition at line 89 of file SymbolRewriter.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RewriteSymbolsLegacyPass , "rewrite-symbols" , "Rewrite Symbols" , false , false)
Definition at line 575 of file SymbolRewriter.cpp.
rewriteComdat()
static void rewriteComdat (Module & M, GlobalObject * GO, const std::string & Source, const std::string & Target) static
Definition at line 96 of file SymbolRewriter.cpp.
References llvm::Module::aliases(), C, llvm::SymbolRewriter::RewriteDescriptor::Function, llvm::Module::functions(), llvm::GlobalObject::getComdat(), llvm::Module::getComdatSymbolTable(), llvm::Module::getFunction(), llvm::Module::getGlobalVariable(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::Module::getNamedAlias(), llvm::Module::getOrInsertComdat(), llvm::SymbolRewriter::RewriteDescriptor::getType(), llvm::Module::globals(), llvm::SymbolRewriter::RewriteDescriptor::GlobalVariable, Name, llvm::SymbolRewriter::RewriteDescriptor::NamedAlias, P, llvm::report_fatal_error(), llvm::GlobalObject::setComdat(), llvm::Value::setName(), llvm::Comdat::setSelectionKind(), llvm::Value::setValueName(), llvm::Sched::Source, llvm::StringRef::str(), and llvm::Regex::sub().
Variable Documentation
RewriteMapFiles
cl::list<std::string> RewriteMapFiles("rewrite-map-file", cl::desc("Symbol Rewrite Map"), cl::value_desc("filename"), cl::Hidden) static
Referenced by llvm::RewriteSymbolPass::runImpl().