LLVM: lib/Object/SymbolSize.cpp File Reference
SymbolSize.cpp File Reference
#include "llvm/Object/SymbolSize.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/MachO.h"
Functions
static unsigned getSectionID (const ObjectFile &O, SectionRef Sec)
static unsigned getSymbolSectionID (const ObjectFile &O, SymbolRef Sym)
Function Documentation
getSectionID()
static unsigned getSectionID (const ObjectFile & O, SectionRef Sec) static
Definition at line 27 of file SymbolSize.cpp.
References llvm::RISCVFenceField::O.
Referenced by llvm::object::computeSymbolSizes(), and llvm::object::COFFObjectFile::getLoadConfig64().
getSymbolSectionID()
static unsigned getSymbolSectionID (const ObjectFile & O, SymbolRef Sym) static
Definition at line 33 of file SymbolSize.cpp.
References llvm::RISCVFenceField::O.
Referenced by llvm::object::computeSymbolSizes(), llvm::object::COFFObjectFile::getLoadConfig64(), and llvm::RuntimeDyld::MemoryManager::notifyObjectLoaded().