LLVM: lib/Target/SystemZ/SystemZElimCompare.cpp File Reference
SystemZElimCompare.cpp File Reference
#include "SystemZ.h"
#include "SystemZInstrInfo.h"
#include "SystemZTargetMachine.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include <cassert>
#include <cstdint>
Macros
#define DEBUG_TYPE "systemz-elim-compare"
Functions
STATISTIC (BranchOnCounts, "Number of branch-on-count instructions")
STATISTIC (LoadAndTraps, "Number of load-and-trap instructions")
STATISTIC (EliminatedComparisons, "Number of eliminated comparisons")
STATISTIC (FusedComparisons, "Number of fused compare-and-branch instructions")
static bool preservesValueOf (MachineInstr &MI, unsigned Reg)
static bool resultTests (MachineInstr &MI, unsigned Reg)
static bool isLoadAndTestAsCmp (MachineInstr &MI)
static unsigned getCompareSourceReg (MachineInstr &Compare)
static bool isAddWithImmediate (unsigned Opcode)
static bool isCompareZero (MachineInstr &Compare)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-elim-compare"
Definition at line 36 of file SystemZElimCompare.cpp.
Function Documentation
getCompareSourceReg()
static unsigned getCompareSourceReg (MachineInstr & Compare) static
Definition at line 176 of file SystemZElimCompare.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::AArch64CC::AL, assert(), llvm::MCID::Branch, llvm::BuildMI(), llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_ICMP, llvm::MachineInstr::clearRegisterDeads(), llvm::MCID::Compare, llvm::RegState::Dead, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegState::ImplicitDefine, llvm::MachineInstr::isCompare(), isLoadAndTestAsCmp(), llvm::MachineInstr::mayRaiseFPException(), llvm::MachineInstr::memoperands(), MI, llvm::MachineInstr::operands(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineInstrBuilder::setMemRefs(), llvm::SmallVectorBase::size(), and TII.
Referenced by isCompareZero().
isAddWithImmediate()
static bool isAddWithImmediate (unsigned Opcode) static
Definition at line 338 of file SystemZElimCompare.cpp.
References assert(), llvm::SystemZII::CCIfNoSignedWrap, llvm::SystemZ::CCMASK_ARITH_OVERFLOW, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_LOGICAL_NONZERO, llvm::SystemZ::CCMASK_LOGICAL_ZERO, llvm::SystemZII::CCMaskFirst, llvm::SystemZII::CCMaskLast, llvm::MachineInstr::clearRegisterDeads(), llvm::MCID::Compare, contains(), E, llvm::MachineBasicBlock::end(), llvm::SystemZII::getCCValues(), llvm::SystemZII::getCompareZeroCCMask(), llvm::MachineInstr::getDesc(), llvm::MachineInstr::getFlag(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), I, llvm::MachineOperand::isImm(), llvm::SystemZII::IsLogical, llvm::MachineInstr::mayLoadOrStore(), llvm::MCInstrDesc::mayRaiseFPException(), llvm::MachineInstr::mayRaiseFPException(), MI, llvm::MachineInstr::NoSWrap, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), TII, TRI, and llvm::MCInstrDesc::TSFlags.
isCompareZero()
static bool isCompareZero (MachineInstr & Compare) static
Definition at line 501 of file SystemZElimCompare.cpp.
References llvm::MachineInstrBuilder::add(), llvm::LivePhysRegs::addLiveOuts(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), assert(), llvm::MachineBasicBlock::begin(), llvm::MCID::Branch, llvm::SystemZ::CCMASK_ICMP, llvm::SmallVectorImpl< T >::clear(), llvm::MCID::Compare, llvm::SystemZII::CompareAndBranch, llvm::SystemZII::CompareAndReturn, llvm::SystemZII::CompareAndSibcall, llvm::SystemZII::CompareAndTrap, llvm::LivePhysRegs::contains(), llvm::RegState::Dead, llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), F(), getCompareSourceReg(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::hasUnmodeledSideEffects(), I, llvm::RegState::ImplicitDefine, llvm::MachineInstr::isCall(), llvm::MachineInstr::isCompare(), llvm::MachineOperand::isImm(), isLoadAndTestAsCmp(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayRaiseFPException(), preservesValueOf(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineInstr::readsRegister(), Register, llvm::MachineInstr::RemoveOperand(), llvm::MachineBasicBlock::rend(), resultTests(), llvm::MachineInstr::setDesc(), llvm::SmallVectorBase::size(), TII, and TRI.
isLoadAndTestAsCmp()
static bool isLoadAndTestAsCmp (MachineInstr & MI) static
Definition at line 165 of file SystemZElimCompare.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::isDead().
Referenced by getCompareSourceReg(), and isCompareZero().
preservesValueOf()
static bool preservesValueOf (MachineInstr & MI, unsigned Reg) static
Definition at line 110 of file SystemZElimCompare.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MipsISD::LDR, and Reg.
Referenced by isCompareZero(), and resultTests().
resultTests()
static bool resultTests (MachineInstr & MI, unsigned Reg) static
Definition at line 133 of file SystemZElimCompare.cpp.
References E, llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, if(), llvm::MachineInstr::isDebugInstr(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), MI, preservesValueOf(), llvm::Ref, Reg, and TRI.
Referenced by isCompareZero().
STATISTIC() [1/4]
STATISTIC (BranchOnCounts , "Number of branch-on-count instructions")
STATISTIC() [2/4]
STATISTIC (LoadAndTraps , "Number of load-and-trap instructions")
STATISTIC() [3/4]
STATISTIC (EliminatedComparisons , "Number of eliminated comparisons")
STATISTIC() [4/4]
STATISTIC (FusedComparisons , "Number of fused compare-and-branch instructions")