LLVM: lib/Target/SystemZ/SystemZFrameLowering.cpp File Reference
SystemZFrameLowering.cpp File Reference
#include "SystemZFrameLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZInstrBuilder.h"
#include "SystemZInstrInfo.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZRegisterInfo.h"
#include "SystemZSubtarget.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
Functions
static bool usePackedStack (MachineFunction &MF)
static void addSavedGPR (MachineBasicBlock &MBB, MachineInstrBuilder &MIB, unsigned GPR64, bool IsImplicit)
static void emitIncrement (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, const DebugLoc &DL, unsigned Reg, int64_t NumBytes, const TargetInstrInfo *TII)
Function Documentation
addSavedGPR()
static void addSavedGPR (MachineBasicBlock & MBB, MachineInstrBuilder & MIB, unsigned GPR64, bool IsImplicit) static
Definition at line 224 of file SystemZFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::getImplRegState(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::isLiveIn(), and llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
Referenced by llvm::SystemZFrameLowering::spillCalleeSavedRegisters().
emitIncrement()
static void emitIncrement (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, const DebugLoc & DL, unsigned Reg, int64_t NumBytes, const TargetInstrInfo * TII) static
Definition at line 391 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getOperand(), llvm::isInt< 16 >(), MI, Reg, and llvm::MachineOperand::setIsDead().
Referenced by llvm::SystemZFrameLowering::emitEpilogue(), and llvm::SystemZFrameLowering::emitPrologue().
usePackedStack()
static bool usePackedStack (MachineFunction & MF) static
Definition at line 65 of file SystemZFrameLowering.cpp.
References llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::CallingConv::GHC, llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::Function::isVarArg(), and llvm::report_fatal_error().
Referenced by llvm::SystemZFrameLowering::assignCalleeSavedSpillSlots(), and llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized().