LLVM: lib/Target/SystemZ/SystemZRegisterInfo.cpp File Reference
SystemZRegisterInfo.cpp File Reference
#include "SystemZRegisterInfo.h"
#include "SystemZInstrInfo.h"
#include "SystemZSubtarget.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "SystemZGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static const TargetRegisterClass * getRC32 (MachineOperand &MO, const VirtRegMap *VRM, const MachineRegisterInfo *MRI)
static void addHints (ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const TargetRegisterClass *RC, const MachineRegisterInfo *MRI)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 21 of file SystemZRegisterInfo.cpp.
Function Documentation
addHints()
static void addHints (ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const TargetRegisterClass * RC, const MachineRegisterInfo * MRI) static
Definition at line 59 of file SystemZRegisterInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetRegisterClass::contains(), llvm::SmallSet< T, N, C >::count(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineRegisterInfo::isReserved(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Reg.
Referenced by llvm::SystemZRegisterInfo::getRegAllocationHints().
getRC32()
static const TargetRegisterClass* getRC32 (MachineOperand & MO, const VirtRegMap * VRM, const MachineRegisterInfo * MRI) static
Definition at line 29 of file SystemZRegisterInfo.cpp.
References assert(), contains(), llvm::VirtRegMap::getPhys(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), and llvm::VirtRegMap::hasPhys().
Referenced by llvm::SystemZRegisterInfo::getRegAllocationHints().