LLVM: lib/Target/SystemZ/SystemZTDC.cpp File Reference
SystemZTDC.cpp File Reference
#include "SystemZ.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include <deque>
#include <set>
Namespaces
llvm
This class represents lattice values for constants.
Functions
void llvm::initializeSystemZTDCPassPass (PassRegistry &)
INITIALIZE_PASS (SystemZTDCPass, "systemz-tdc", "SystemZ Test Data Class optimization", false, false) FunctionPass *llvm
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SystemZTDCPass , "systemz-tdc" , "SystemZ Test Data Class optimization" , false , false)
Definition at line 115 of file SystemZTDC.cpp.
References llvm::APFloat::changeSign(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), llvm::dyn_cast(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty(), llvm::Instruction::eraseFromParent(), F(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_UNO, llvm::ConstantInt::get(), llvm::Module::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFltSemantics(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Function::getIntrinsicID(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::CmpInst::getPredicate(), llvm::APFloat::getSmallestNormalized(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::instructions(), llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), llvm::Value::replaceAllUsesWith(), llvm::reverse(), runOnFunction(), llvm::SystemZISD::TDC, llvm::SystemZ::TDCMASK_ALL, llvm::SystemZ::TDCMASK_INFINITY_MINUS, llvm::SystemZ::TDCMASK_INFINITY_PLUS, llvm::SystemZ::TDCMASK_MINUS, llvm::SystemZ::TDCMASK_NAN, llvm::SystemZ::TDCMASK_NEGATIVE, llvm::SystemZ::TDCMASK_NORMAL_MINUS, llvm::SystemZ::TDCMASK_NORMAL_PLUS, llvm::SystemZ::TDCMASK_PLUS, llvm::SystemZ::TDCMASK_POSITIVE, llvm::SystemZ::TDCMASK_SUBNORMAL_MINUS, llvm::SystemZ::TDCMASK_SUBNORMAL_PLUS, llvm::SystemZ::TDCMASK_ZERO, and llvm::Value::user_empty().