LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZMCAsmBackend.cpp File Reference
SystemZMCAsmBackend.cpp File Reference
#include "MCTargetDesc/SystemZMCFixups.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
Functions
static uint64_t extractBitsForFixup (MCFixupKind Kind, uint64_t Value)
Function Documentation
extractBitsForFixup()
static uint64_t extractBitsForFixup (MCFixupKind Kind, uint64_t Value) static
Definition at line 23 of file SystemZMCAsmBackend.cpp.
References llvm::HexStyle::Asm, assert(), llvm::support::big, llvm::createSystemZObjectWriter(), llvm::Data, llvm::FirstTargetFixupKind, Fixup, llvm::SystemZ::FK_390_PC12DBL, llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC24DBL, llvm::SystemZ::FK_390_PC32DBL, llvm::SystemZ::FK_390_TLS_CALL, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), I, llvm_unreachable, llvm::SystemZ::NumTargetFixupKinds, Size, and llvm::ArrayRef< T >::size().