LLVM: lib/Target/SystemZ/SystemZInstrInfo.cpp File Reference
SystemZInstrInfo.cpp File Reference
#include "SystemZInstrInfo.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "SystemZ.h"
#include "SystemZInstrBuilder.h"
#include "SystemZSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include "SystemZGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRMAP_INFO
#define DEBUG_TYPE "systemz-II"
Functions
static uint64_t allOnes (unsigned int Count)
static int isSimpleMove (const MachineInstr &MI, int &FrameIndex, unsigned Flag)
static bool isSimpleBD12Move (const MachineInstr *MI, unsigned Flag)
static LogicOp interpretAndImmediate (unsigned Opcode)
static void transferDeadCC (MachineInstr *OldMI, MachineInstr *NewMI)
static void transferMIFlag (MachineInstr *OldMI, MachineInstr *NewMI, MachineInstr::MIFlag Flag)
static bool isStringOfOnes (uint64_t Mask, unsigned &LSB, unsigned &Length)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-II"
Definition at line 48 of file SystemZInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 44 of file SystemZInstrInfo.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 45 of file SystemZInstrInfo.cpp.
Function Documentation
allOnes()
static uint64_t allOnes (unsigned int Count) static
Definition at line 51 of file SystemZInstrInfo.cpp.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress(), insertDAGNode(), llvm::APInt::magicu(), and maskMatters().
interpretAndImmediate()
static LogicOp interpretAndImmediate (unsigned Opcode) static
Definition at line 925 of file SystemZInstrInfo.cpp.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress().
isSimpleBD12Move()
static bool isSimpleBD12Move (const MachineInstr * MI, unsigned Flag) static
Definition at line 902 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl().
isSimpleMove()
static int isSimpleMove (const MachineInstr & MI, int & FrameIndex, unsigned Flag) static
Definition at line 309 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::SystemZInstrInfo::isLoadFromStackSlot(), and llvm::SystemZInstrInfo::isStoreToStackSlot().
isStringOfOnes()
static bool isStringOfOnes (uint64_t Mask, unsigned & LSB, unsigned & Length) static
Definition at line 1566 of file SystemZInstrInfo.cpp.
References llvm::findFirstSet().
transferDeadCC()
static void transferDeadCC (MachineInstr * OldMI, MachineInstr * NewMI) static
Definition at line 940 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::findRegisterDefOperand(), llvm::MachineInstr::registerDefIsDead(), and llvm::MachineOperand::setIsDead().
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl().
transferMIFlag()
static void transferMIFlag (MachineInstr * OldMI, MachineInstr * NewMI, MachineInstr::MIFlag Flag) static
Definition at line 948 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::getFlag(), and llvm::MachineInstr::setFlag().
Referenced by llvm::SystemZInstrInfo::foldMemoryOperandImpl().