LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZMCObjectWriter.cpp File Reference
SystemZMCObjectWriter.cpp File Reference
#include "MCTargetDesc/SystemZMCFixups.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <cstdint>
Functions
static unsigned getAbsoluteReloc (unsigned Kind)
static unsigned getPCRelReloc (unsigned Kind)
static unsigned getTLSLEReloc (unsigned Kind)
static unsigned getTLSLDOReloc (unsigned Kind)
static unsigned getTLSLDMReloc (unsigned Kind)
static unsigned getTLSGDReloc (unsigned Kind)
static unsigned getPLTReloc (unsigned Kind)
Function Documentation
getAbsoluteReloc()
static unsigned getAbsoluteReloc (unsigned Kind) static
Definition at line 43 of file SystemZMCObjectWriter.cpp.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().
getPCRelReloc()
static unsigned getPCRelReloc (unsigned Kind) static
Definition at line 54 of file SystemZMCObjectWriter.cpp.
References llvm::SystemZ::FK_390_PC12DBL, llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC24DBL, llvm::SystemZ::FK_390_PC32DBL, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().
getPLTReloc()
static unsigned getPLTReloc (unsigned Kind) static
Definition at line 106 of file SystemZMCObjectWriter.cpp.
References assert(), Fixup, llvm::SystemZ::FK_390_PC12DBL, llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC24DBL, llvm::SystemZ::FK_390_PC32DBL, getAbsoluteReloc(), llvm::MCValue::getAccessVariant(), llvm::MCFixup::getKind(), getPCRelReloc(), getRelocType(), getTLSGDReloc(), getTLSLDMReloc(), getTLSLDOReloc(), getTLSLEReloc(), llvm_unreachable, llvm::MCSymbolRefExpr::VK_DTPOFF, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_INDNTPOFF, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_NTPOFF, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_TLSGD, and llvm::MCSymbolRefExpr::VK_TLSLDM.
getTLSGDReloc()
static unsigned getTLSGDReloc (unsigned Kind) static
Definition at line 96 of file SystemZMCObjectWriter.cpp.
References llvm::SystemZ::FK_390_TLS_CALL, llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().
getTLSLDMReloc()
static unsigned getTLSLDMReloc (unsigned Kind) static
Definition at line 86 of file SystemZMCObjectWriter.cpp.
References llvm::SystemZ::FK_390_TLS_CALL, llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().
getTLSLDOReloc()
static unsigned getTLSLDOReloc (unsigned Kind) static
Definition at line 77 of file SystemZMCObjectWriter.cpp.
References llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().
getTLSLEReloc()
static unsigned getTLSLEReloc (unsigned Kind) static
Definition at line 68 of file SystemZMCObjectWriter.cpp.
References llvm::FK_Data_4, llvm::FK_Data_8, and llvm_unreachable.
Referenced by getPLTReloc().