LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZInstPrinter.cpp File Reference
SystemZInstPrinter.cpp File Reference
#include "SystemZInstPrinter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include "SystemZGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
template<unsigned N>
static void printUImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
template<unsigned N>
static void printSImmOperand (const MCInst *MI, int OpNum, raw_ostream &O)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 22 of file SystemZInstPrinter.cpp.
Function Documentation
printSImmOperand()
template<unsigned N> static void printSImmOperand (const MCInst * MI, int OpNum, raw_ostream & O) static
Definition at line 77 of file SystemZInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbol::getName(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::SystemZInstPrinter::getRegisterName(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCOperand::isImm(), llvm_unreachable, llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, llvm::MCExpr::print(), llvm::SystemZInstPrinter::printAddress(), llvm::SystemZInstPrinter::printOperand(), llvm::MCSymbolRefExpr::VK_TLSGD, llvm::MCSymbolRefExpr::VK_TLSLDM, and llvm::raw_ostream::write_hex().
printUImmOperand()
template<unsigned N> static void printUImmOperand (const MCInst * MI, int OpNum, raw_ostream & O) static
Definition at line 70 of file SystemZInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().