LLVM: lib/Target/SystemZ/SystemZISelDAGToDAG.cpp File Reference
SystemZISelDAGToDAG.cpp File Reference
#include "SystemZTargetMachine.h"
#include "SystemZISelLowering.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include "SystemZGenDAGISel.inc"
Macros
#define DEBUG_TYPE "systemz-isel"
Functions
static bool selectDisp (SystemZAddressingMode::DispRange DR, int64_t Val)
static void changeComponent (SystemZAddressingMode &AM, bool IsBase, SDValue Value)
static bool expandAdjDynAlloc (SystemZAddressingMode &AM, bool IsBase, SDValue Value)
static bool expandIndex (SystemZAddressingMode &AM, SDValue Base, SDValue Index)
static bool expandDisp (SystemZAddressingMode &AM, bool IsBase, SDValue Op0, uint64_t Op1)
static bool isValidDisp (SystemZAddressingMode::DispRange DR, int64_t Val)
static bool shouldUseLA (SDNode *Base, int64_t Disp, SDNode *Index)
static void insertDAGNode (SelectionDAG *DAG, SDNode *Pos, SDValue N)
static bool maskMatters (RxSBGOperands &RxSBG, uint64_t Mask)
static bool isFusableLoadOpStorePattern (StoreSDNode *StoreNode, SDValue StoredVal, SelectionDAG *CurDAG, LoadSDNode *&LoadNode, SDValue &InputChain)
static IPMConversion getIPMConversion (unsigned CCValid, unsigned CCMask)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-isel"
Definition at line 23 of file SystemZISelDAGToDAG.cpp.
Function Documentation
changeComponent()
static void changeComponent (SystemZAddressingMode & AM, bool IsBase, SDValue Value) static
Definition at line 404 of file SystemZISelDAGToDAG.cpp.
Referenced by expandAdjDynAlloc(), and expandDisp().
expandAdjDynAlloc()
static bool expandAdjDynAlloc (SystemZAddressingMode & AM, bool IsBase, SDValue Value) static
Definition at line 415 of file SystemZISelDAGToDAG.cpp.
References changeComponent().
Referenced by expandDisp(), and shouldUseLA().
expandDisp()
static bool expandDisp (SystemZAddressingMode & AM, bool IsBase, SDValue Op0, uint64_t Op1) static
Definition at line 439 of file SystemZISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::SystemZISD::ADJDYNALLOC, changeComponent(), llvm::ISD::Constant, expandAdjDynAlloc(), expandIndex(), llvm::Full, llvm::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), N, llvm::SystemZISD::PCREL_OFFSET, selectDisp(), and llvm::ISD::TRUNCATE.
Referenced by shouldUseLA().
expandIndex()
static bool expandIndex (SystemZAddressingMode & AM, SDValue Base, SDValue Index) static
Definition at line 427 of file SystemZISelDAGToDAG.cpp.
Referenced by expandDisp().
getIPMConversion()
static IPMConversion getIPMConversion (unsigned CCValid, unsigned CCMask) static
Definition at line 1763 of file SystemZISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::SystemZ::CCMASK_0, llvm::SystemZ::CCMASK_1, llvm::SystemZ::CCMASK_2, llvm::SystemZ::CCMASK_3, llvm::dbgs(), llvm::SDNode::dump(), llvm::dyn_cast(), E, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, LLVM_DEBUG, llvm_unreachable, llvm::SystemZISD::SELECT_CCMASK, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::SDNode::use_empty(), and llvm::ISD::XOR.
insertDAGNode()
static void insertDAGNode (SelectionDAG * DAG, SDNode * Pos, SDValue N) static
Definition at line 612 of file SystemZISelDAGToDAG.cpp.
References allOnes(), llvm::ISD::AND, assert(), llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FrameIndex, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::SDValue::getNode(), llvm::SDNode::getNodeId(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAGISel::getUninvalidatedNodeId(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::SelectionDAGISel::InvalidateNodeId(), llvm::SystemZInstrInfo::isRxSBGMask(), llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::RepositionNode(), llvm::SDNode::setNodeId(), TII, llvm::ISD::TRUNCATE, llvm::KnownBits::Zero, and llvm::ISD::ZERO_EXTEND.
Referenced by maskMatters().
isFusableLoadOpStorePattern()
static bool isFusableLoadOpStorePattern (StoreSDNode * StoreNode, SDValue StoredVal, SelectionDAG * CurDAG, LoadSDNode *& LoadNode, SDValue & InputChain) static
Definition at line 1243 of file SystemZISelDAGToDAG.cpp.
References llvm::numbers::e, llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValue(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasPredecessorHelper(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::SPII::Load, llvm::SDNode::ops(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::TokenFactor.
isValidDisp()
static bool isValidDisp (SystemZAddressingMode::DispRange DR, int64_t Val) static
Definition at line 497 of file SystemZISelDAGToDAG.cpp.
References assert(), llvm_unreachable, and selectDisp().
Referenced by shouldUseLA().
maskMatters()
static bool maskMatters (RxSBGOperands & RxSBG, uint64_t Mask) static
Definition at line 765 of file SystemZISelDAGToDAG.cpp.
References allOnes(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::dyn_cast(), llvm::ISD::EXTLOAD, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, insertDAGNode(), llvm::SystemZ::isImmHF(), llvm::SystemZ::isImmLF(), llvm::EVT::isInteger(), llvm::SDNode::isMachineOpcode(), LLVM_FALLTHROUGH, llvm::SPII::Load, llvm::BitmaskEnumDetail::Mask(), N, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::ROTL, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZEXTLOAD.
selectDisp()
static bool selectDisp (SystemZAddressingMode::DispRange DR, int64_t Val) static
Definition at line 386 of file SystemZISelDAGToDAG.cpp.
References llvm_unreachable.
Referenced by expandDisp(), and isValidDisp().
shouldUseLA()
static bool shouldUseLA (SDNode * Base, int64_t Disp, SDNode * Index) static
Definition at line 517 of file SystemZISelDAGToDAG.cpp.
References llvm::SystemZISD::ADJDYNALLOC, llvm::ISD::Constant, expandAdjDynAlloc(), expandDisp(), llvm::ISD::FrameIndex, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::hasOneUse(), llvm::isInt< 16 >(), isValidDisp(), LLVM_DEBUG, llvm::ISD::SIGN_EXTEND, and llvm::ISD::SIGN_EXTEND_INREG.