LLVM: lib/Target/SystemZ/SystemZPostRewrite.cpp File Reference
SystemZPostRewrite.cpp File Reference
#include "SystemZ.h"
#include "SystemZInstrInfo.h"
#include "SystemZSubtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define SYSTEMZ_POSTREWRITE_NAME "SystemZ Post Rewrite pass"
#define DEBUG_TYPE "systemz-postrewrite"
Functions
STATISTIC (MemFoldCopies, "Number of copies inserted before folded mem ops.")
STATISTIC (LOCRMuxJumps, "Number of LOCRMux jump-sequences (lower is better)")
void llvm::initializeSystemZPostRewritePass (PassRegistry &)
INITIALIZE_PASS (SystemZPostRewrite, "systemz-post-rewrite", SYSTEMZ_POSTREWRITE_NAME, false, false) FunctionPass *llvm
Returns an instance of the Post Rewrite pass.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-postrewrite"
Definition at line 26 of file SystemZPostRewrite.cpp.
SYSTEMZ_POSTREWRITE_NAME
#define SYSTEMZ_POSTREWRITE_NAME "SystemZ Post Rewrite pass"
Definition at line 24 of file SystemZPostRewrite.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SystemZPostRewrite , "systemz-post-rewrite" , SYSTEMZ_POSTREWRITE_NAME , false , false)
Returns an instance of the Post Rewrite pass.
Definition at line 72 of file SystemZPostRewrite.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::LivePhysRegs::addLiveOuts(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), E, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::getRegState(), llvm::MachineFunction::getSubtarget(), llvm::SystemZ::getTargetMemOpcode(), I, llvm::MachineFunction::insert(), llvm::SystemZ::isHighReg(), MI, Modified, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), llvm::MachineBasicBlock::splice(), std::swap(), llvm::MachineInstr::tieOperands(), TII, and llvm::MachineBasicBlock::transferSuccessors().
STATISTIC() [1/2]
STATISTIC (MemFoldCopies , "Number of copies inserted before folded mem ops.")
STATISTIC() [2/2]
STATISTIC (LOCRMuxJumps , "Number of LOCRMux jump-sequences (lower is better)")