LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp File Reference
SystemZMCTargetDesc.cpp File Reference
#include "SystemZMCTargetDesc.h"
#include "SystemZInstPrinter.h"
#include "SystemZMCAsmInfo.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
#include "SystemZGenInstrInfo.inc"
#include "SystemZGenSubtargetInfo.inc"
#include "SystemZGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createSystemZMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createSystemZMCInstrInfo ()
static MCRegisterInfo * createSystemZMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createSystemZMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createSystemZMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 22 of file SystemZMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 28 of file SystemZMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 25 of file SystemZMCTargetDesc.cpp.
Function Documentation
createSystemZMCAsmInfo()
static MCAsmInfo* createSystemZMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 149 of file SystemZMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::SystemZMC::CFAOffsetFromInitialSP, llvm::MCCFIInstruction::createDefCfa(), and llvm::MCRegisterInfo::getDwarfRegNum().
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstPrinter()
static MCInstPrinter* createSystemZMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 178 of file SystemZMCTargetDesc.cpp.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstrInfo()
static MCInstrInfo* createSystemZMCInstrInfo () static
Definition at line 161 of file SystemZMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCRegisterInfo()
static MCRegisterInfo* createSystemZMCRegisterInfo (const Triple & TT) static
Definition at line 167 of file SystemZMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCSubtargetInfo()
static MCSubtargetInfo* createSystemZMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 174 of file SystemZMCTargetDesc.cpp.
Referenced by LLVMInitializeSystemZTargetMC().
LLVMInitializeSystemZTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTargetMC ()
Definition at line 186 of file SystemZMCTargetDesc.cpp.
References llvm::createSystemZMCAsmBackend(), createSystemZMCAsmInfo(), llvm::createSystemZMCCodeEmitter(), createSystemZMCInstPrinter(), createSystemZMCInstrInfo(), createSystemZMCRegisterInfo(), createSystemZMCSubtargetInfo(), llvm::getTheSystemZTarget(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), and llvm::TargetRegistry::RegisterMCSubtargetInfo().