LLVM: lib/Target/SystemZ/SystemZSelectionDAGInfo.cpp File Reference
SystemZSelectionDAGInfo.cpp File Reference
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/SelectionDAG.h"
Macros
#define DEBUG_TYPE "systemz-selectiondag-info"
Functions
static SDValue emitMemMem (SelectionDAG &DAG, const SDLoc &DL, unsigned Sequence, unsigned Loop, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size)
static SDValue memsetStore (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, unsigned Align, MachinePointerInfo DstPtrInfo)
static SDValue emitCLC (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src1, SDValue Src2, uint64_t Size)
static SDValue addIPMSequence (const SDLoc &DL, SDValue CCReg, SelectionDAG &DAG)
static std::pair< SDValue, SDValue > getBoundedStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue Limit)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-selectiondag-info"
Definition at line 18 of file SystemZSelectionDAGInfo.cpp.
Function Documentation
addIPMSequence()
static SDValue addIPMSequence (const SDLoc & DL, SDValue CCReg, SelectionDAG & DAG) static
Definition at line 169 of file SystemZSelectionDAGInfo.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, llvm::ISD::SHL, and llvm::ISD::SRA.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp().
emitCLC()
static SDValue emitCLC (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src1, SDValue Src2, uint64_t Size) static
Definition at line 145 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZISD::CLC, llvm::SystemZISD::CLC_LOOP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, and llvm::MVT::Other.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp().
emitMemMem()
static SDValue emitMemMem (SelectionDAG & DAG, const SDLoc & DL, unsigned Sequence, unsigned Loop, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size) static
Definition at line 25 of file SystemZSelectionDAGInfo.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::MVT::Other.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().
getBoundedStrlen()
static std::pair<SDValue, SDValue> getBoundedStrlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, SDValue Limit) static
Definition at line 248 of file SystemZSelectionDAGInfo.cpp.
References llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, and llvm::MVT::Other.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen().
memsetStore()
static SDValue memsetStore (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, unsigned Align, MachinePointerInfo DstPtrInfo) static
Definition at line 64 of file SystemZSelectionDAGInfo.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::Align, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getStore(), I, and Size.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().