LLVM: lib/Target/SystemZ/SystemZShortenInst.cpp File Reference
SystemZShortenInst.cpp File Reference
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "systemz-shorten-inst"
Functions
static void tieOpsIfNeeded (MachineInstr &MI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-shorten-inst"
Definition at line 23 of file SystemZShortenInst.cpp.
Function Documentation
tieOpsIfNeeded()
static void tieOpsIfNeeded (MachineInstr & MI) static
Definition at line 66 of file SystemZShortenInst.cpp.
References add(), llvm::RegState::Dead, F(), llvm::MachineInstr::getDesc(), llvm::SystemZMC::getFirstReg(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::SystemZSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::SystemZMC::getRegAsGR64(), llvm::SystemZSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZ::getTwoOperandOpcode(), llvm::RegState::ImplicitDefine, llvm::MachineInstr::isCommutable(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), llvm::MachineOperand::isTied(), llvm::ARM_MB::LD, MI, Mode, llvm::MachineBasicBlock::rbegin(), Reg, llvm::MachineInstr::RemoveOperand(), llvm::MachineBasicBlock::rend(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setReg(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ARM_MB::ST, llvm::MCOI::TIED_TO, llvm::MachineInstr::tieOperands(), TII, and TRI.