LLVM: lib/Target/SystemZ/SystemZISelLowering.cpp File Reference
SystemZISelLowering.cpp File Reference
#include "SystemZISelLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZConstantPoolValue.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsS390.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/KnownBits.h"
#include <cctype>
#include "SystemZGenCallingConv.inc"
Classes
struct AddressingMode
Macros
#define DEBUG_TYPE "systemz-lower"
#define CONV(X)
#define OPCODE(NAME) case SystemZISD::NAME: return "SystemZISD::" #NAME
Enumerations
enum CmpMode { CmpMode::Int, CmpMode::FP, CmpMode::StrictFP, CmpMode::SignalingFP }
Functions
static bool is32Bit (EVT VT)
static MachineOperand earlyUseOperand (MachineOperand Op)
static AddressingMode getLoadStoreAddrMode (bool HasVector, Type *Ty)
static AddressingMode supportedAddressingMode (Instruction *I, bool HasVector)
static std::pair< unsigned, const TargetRegisterClass * > parseRegisterNumber (StringRef Constraint, const TargetRegisterClass *RC, const unsigned *Map, unsigned Size)
static void VerifyVectorType (MVT VT, EVT ArgVT)
static void VerifyVectorTypes (const SmallVectorImpl< ISD::InputArg > &Ins)
static void VerifyVectorTypes (const SmallVectorImpl< ISD::OutputArg > &Outs)
static SDValue convertLocVTToValVT (SelectionDAG &DAG, const SDLoc &DL, CCValAssign &VA, SDValue Chain, SDValue Value)
static SDValue convertValVTToLocVT (SelectionDAG &DAG, const SDLoc &DL, CCValAssign &VA, SDValue Value)
static bool canUseSiblingCall (const CCState &ArgCCInfo, SmallVectorImpl< CCValAssign > &ArgLocs, SmallVectorImpl< ISD::OutputArg > &Outs)
static bool isIntrinsicWithCCAndChain (SDValue Op, unsigned &Opcode, unsigned &CCValid)
static bool isIntrinsicWithCC (SDValue Op, unsigned &Opcode, unsigned &CCValid)
static SDNode * emitIntrinsicWithCCAndChain (SelectionDAG &DAG, SDValue Op, unsigned Opcode)
static SDNode * emitIntrinsicWithCC (SelectionDAG &DAG, SDValue Op, unsigned Opcode)
static unsigned CCMaskForCondCode (ISD::CondCode CC)
static void adjustZeroCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustSubwordCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType)
static bool shouldSwapCmpOperands (const Comparison &C)
static unsigned reverseCCMask (unsigned CCMask)
static void adjustForSubtraction (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustForFNeg (Comparison &C)
static void adjustForLTGFR (Comparison &C)
static void adjustICmpTruncate (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static bool isSimpleShift (SDValue N, unsigned &ShiftVal)
static unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType)
static void adjustForTestUnderMask (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void adjustForRedundantAnd (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static Comparison getIntrinsicCmp (SelectionDAG &DAG, unsigned Opcode, SDValue Call, unsigned CCValid, uint64_t CC, ISD::CondCode Cond)
static Comparison getCmp (SelectionDAG &DAG, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, const SDLoc &DL, SDValue Chain=SDValue(), bool IsSignaling=false)
static SDValue emitCmp (SelectionDAG &DAG, const SDLoc &DL, Comparison &C)
static void lowerMUL_LOHI32 (SelectionDAG &DAG, const SDLoc &DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue &Hi, SDValue &Lo)
static void lowerGR128Binary (SelectionDAG &DAG, const SDLoc &DL, EVT VT, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue &Even, SDValue &Odd)
static SDValue emitSETCC (SelectionDAG &DAG, const SDLoc &DL, SDValue CCReg, unsigned CCValid, unsigned CCMask)
static unsigned getVectorComparison (ISD::CondCode CC, CmpMode Mode)
static unsigned getVectorComparisonOrInvert (ISD::CondCode CC, CmpMode Mode, bool &Invert)
static SDValue expandV4F32ToV2F64 (SelectionDAG &DAG, int Start, const SDLoc &DL, SDValue Op, SDValue Chain)
static bool isAbsolute (SDValue CmpOp, SDValue Pos, SDValue Neg)
static SDValue getAbsolute (SelectionDAG &DAG, const SDLoc &DL, SDValue Op, bool IsNegative)
static bool isAddCarryChain (SDValue Carry)
static bool isSubBorrowChain (SDValue Carry)
static SDValue getCCResult (SelectionDAG &DAG, SDValue CCReg)
static bool chooseShuffleOpNos (int *OpNos, unsigned &OpNo0, unsigned &OpNo1)
static bool matchPermute (const SmallVectorImpl< int > &Bytes, const Permute &P, unsigned &OpNo0, unsigned &OpNo1)
static const Permute * matchPermute (const SmallVectorImpl< int > &Bytes, unsigned &OpNo0, unsigned &OpNo1)
static bool matchDoublePermute (const SmallVectorImpl< int > &Bytes, const Permute &P, SmallVectorImpl< int > &Transform)
static const Permute * matchDoublePermute (const SmallVectorImpl< int > &Bytes, SmallVectorImpl< int > &Transform)
static bool getVPermMask (SDValue ShuffleOp, SmallVectorImpl< int > &Bytes)
static bool getShuffleInput (const SmallVectorImpl< int > &Bytes, unsigned Start, unsigned BytesPerElement, int &Base)
static bool isShlDoublePermute (const SmallVectorImpl< int > &Bytes, unsigned &StartIndex, unsigned &OpNo0, unsigned &OpNo1)
static SDValue getPermuteNode (SelectionDAG &DAG, const SDLoc &DL, const Permute &P, SDValue Op0, SDValue Op1)
static SDValue getGeneralPermuteNode (SelectionDAG &DAG, const SDLoc &DL, SDValue *Ops, const SmallVectorImpl< int > &Bytes)
static bool isScalarToVector (SDValue Op)
static SDValue buildScalarToVector (SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Value)
static SDValue buildMergeScalars (SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Op0, SDValue Op1)
static SDValue joinDwords (SelectionDAG &DAG, const SDLoc &DL, SDValue Op0, SDValue Op1)
static SDValue tryBuildVectorShuffle (SelectionDAG &DAG, BuildVectorSDNode *BVN)
static SDValue lowerI128ToGR128 (SelectionDAG &DAG, SDValue In)
static SDValue lowerGR128ToI128 (SelectionDAG &DAG, SDValue In)
static bool isVectorElementSwap (ArrayRef< int > M, EVT VT)
static SDValue MergeInputChains (SDNode *N1, SDNode *N2)
static bool combineCCMask (SDValue &CCReg, int &CCValid, int &CCMask)
static APInt getDemandedSrcElements (SDValue Op, const APInt &DemandedElts, unsigned OpNo)
static void computeKnownBitsBinOp (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth, unsigned OpNo)
static unsigned computeNumSignBitsBinOp (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth, unsigned OpNo)
static MachineBasicBlock * emitBlockAfter (MachineBasicBlock *MBB)
static MachineBasicBlock * splitBlockAfter (MachineBasicBlock::iterator MI, MachineBasicBlock *MBB)
static MachineBasicBlock * splitBlockBefore (MachineBasicBlock::iterator MI, MachineBasicBlock *MBB)
static Register forceReg (MachineInstr &MI, MachineOperand &Base, const SystemZInstrInfo *TII)
static bool checkCCKill (MachineInstr &MI, MachineBasicBlock *MBB)
static bool isSelectPseudo (MachineInstr &MI)
static void createPHIsForSelects (SmallVector< MachineInstr *, 8 > &Selects, MachineBasicBlock *TrueMBB, MachineBasicBlock *FalseMBB, MachineBasicBlock *SinkMBB)
Variables
static const Permute PermuteForms []
Macro Definition Documentation
CONV
#define CONV (X)
Value:
case ISD::SET##X: return SystemZ::CCMASK_CMP_##X; \
  case ISD::SETO##X: return SystemZ::CCMASK_CMP_##X; \
  case ISD::SETU##X: return SystemZ::CCMASK_CMP_UO | SystemZ::CCMASK_CMP_##X
Referenced by CCMaskForCondCode().
DEBUG_TYPE
#define DEBUG_TYPE "systemz-lower"
Definition at line 31 of file SystemZISelLowering.cpp.
OPCODE
#define OPCODE (NAME) case SystemZISD::NAME: return "SystemZISD::" #NAME
Referenced by llvm::SystemZTargetLowering::getTargetNodeName().
Enumeration Type Documentation
CmpMode
enum CmpMode strong
Enumerator
Int
FP
StrictFP
SignalingFP
Definition at line 2658 of file SystemZISelLowering.cpp.
Function Documentation
adjustForFNeg()
static void adjustForFNeg (Comparison & C) static
Definition at line 2197 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), E, llvm::ISD::FNEG, llvm::SDNode::getOpcode(), I, N, and reverseCCMask().
adjustForLTGFR()
static void adjustForLTGFR (Comparison & C) static
Definition at line 2221 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::dyn_cast(), E, llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), I, llvm::MVT::i32, llvm::MVT::i64, N, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
adjustForRedundantAnd()
static void adjustForRedundantAnd (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2468 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::computeKnownBits(), llvm::dyn_cast(), llvm::BitmaskEnumDetail::Mask(), and llvm::KnownBits::Zero.
adjustForSubtraction()
static void adjustForSubtraction (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2176 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_NE, E, llvm::SelectionDAG::getConstant(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), I, N, and llvm::ISD::SUB.
adjustForTestUnderMask()
static void adjustForTestUnderMask (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2377 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::SystemZICMP::Any, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_TM, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), getTestUnderMaskCond(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i64, isSimpleShift(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::SHL, llvm::SystemZICMP::SignedOnly, llvm::ISD::SRL, llvm::SystemZISD::TM, and llvm::SystemZICMP::UnsignedOnly.
adjustICmpTruncate()
static void adjustICmpTruncate (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2246 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::SelectionDAG::getConstant(), llvm::ISD::LOAD, llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::ISD::TRUNCATE, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
adjustSubwordCmp()
static void adjustSubwordCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2012 of file SystemZISelLowering.cpp.
References llvm::SystemZICMP::Any, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::ISD::Constant, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getExtLoad(), llvm::MVT::i32, llvm::SPII::Load, llvm::ISD::LOAD, llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
adjustZeroCmp()
static void adjustZeroCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 1992 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), and llvm::SystemZICMP::UnsignedOnly.
buildMergeScalars()
static SDValue buildMergeScalars (SelectionDAG & DAG, const SDLoc & DL, EVT VT, SDValue Op0, SDValue Op1) static
Definition at line 4648 of file SystemZISelLowering.cpp.
References buildScalarToVector(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::isUndef(), llvm::SystemZISD::MERGE_HIGH, and llvm::SystemZISD::REPLICATE.
Referenced by tryBuildVectorShuffle().
buildScalarToVector()
static SDValue buildScalarToVector (SelectionDAG & DAG, const SDLoc & DL, EVT VT, SDValue Value) static
Definition at line 4632 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SelectionDAG::getUNDEF(), llvm::EVT::getVectorNumElements(), llvm::SDValue::isUndef(), and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by buildMergeScalars(), and tryBuildVectorShuffle().
canUseSiblingCall()
static bool canUseSiblingCall (const CCState & ArgCCInfo, SmallVectorImpl< CCValAssign > & ArgLocs, SmallVectorImpl< ISD::OutputArg > & Outs) static
Definition at line 1468 of file SystemZISelLowering.cpp.
References E, llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), I, llvm::CCValAssign::Indirect, llvm::CCValAssign::isRegLoc(), Reg, and llvm::SmallVectorBase::size().
Referenced by llvm::SystemZTargetLowering::LowerCall().
CCMaskForCondCode()
static unsigned CCMaskForCondCode (ISD::CondCode CC) static
Definition at line 1967 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_O, llvm::SystemZ::CCMASK_CMP_UO, CONV, EQ, llvm::AArch64CC::GE, llvm::AArch64CC::GT, llvm::AArch64CC::LE, llvm_unreachable, llvm::AArch64CC::LT, llvm::AArch64CC::NE, llvm::ISD::SETO, and llvm::ISD::SETUO.
checkCCKill()
static bool checkCCKill (MachineInstr & MI, MachineBasicBlock * MBB) static
Definition at line 6746 of file SystemZISelLowering.cpp.
References llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::readsRegister(), SI, llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by createPHIsForSelects().
chooseShuffleOpNos()
static bool chooseShuffleOpNos (int * OpNos, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 4222 of file SystemZISelLowering.cpp.
Referenced by isShlDoublePermute(), and matchPermute().
combineCCMask()
static bool combineCCMask (SDValue & CCReg, int & CCValid, int & CCMask) static
Definition at line 6169 of file SystemZISelLowering.cpp.
References llvm::BeforeLegalizeTypes, llvm::SystemZISD::BR_CCMASK, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_ICMP, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i32, llvm::SystemZISD::ICMP, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, llvm::SelectionDAG::isConstantIntBuildVectorOrConstantInt(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), N, llvm::SystemZISD::PCREL_WRAPPER, llvm::MCID::Select, llvm::SystemZISD::SELECT_CCMASK, llvm::ISD::SHL, llvm::ISD::SRA, and llvm::SelectionDAG::UnrollVectorOp().
computeKnownBitsBinOp()
static void computeKnownBitsBinOp (const SDValue Op, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth, unsigned OpNo) static
Definition at line 6506 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits(), getDemandedSrcElements(), llvm::SDValue::getOperand(), llvm::KnownBits::One, and llvm::KnownBits::Zero.
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode().
computeNumSignBitsBinOp()
static unsigned computeNumSignBitsBinOp (SDValue Op, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth, unsigned OpNo) static
Definition at line 6615 of file SystemZISelLowering.cpp.
References assert(), llvm::SelectionDAG::ComputeNumSignBits(), getDemandedSrcElements(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), and llvm::SDValue::getValueType().
Referenced by llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode().
convertLocVTToValVT()
static SDValue convertLocVTToValVT (SelectionDAG & DAG, const SDLoc & DL, CCValAssign & VA, SDValue Chain, SDValue Value) static
Definition at line 1271 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::CCValAssign::Full, llvm::SelectionDAG::getBuildVector(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::MVT::i64, llvm::CCValAssign::isExtInLoc(), llvm::MVT::isVector(), llvm::CCValAssign::SExt, llvm::ISD::TRUNCATE, llvm::MVT::v2i64, and llvm::CCValAssign::ZExt.
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerFormalArguments().
convertValVTToLocVT()
static SDValue convertValVTToLocVT (SelectionDAG & DAG, const SDLoc & DL, CCValAssign & VA, SDValue Value) static
Definition at line 1300 of file SystemZISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, assert(), llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::CCValAssign::Full, llvm::SelectionDAG::getConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::CCValAssign::getValVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::isVector(), llvm_unreachable, llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::MVT::v2i64, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerReturn().
createPHIsForSelects()
static void createPHIsForSelects (SmallVector< MachineInstr *, 8 > & Selects, MachineBasicBlock * TrueMBB, MachineBasicBlock * FalseMBB, MachineBasicBlock * SinkMBB) static
Definition at line 6791 of file SystemZISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::SystemZ::CCMASK_3, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_CS, llvm::SystemZ::CCMASK_CS_NE, llvm::SystemZ::CCMASK_ICMP, checkCCKill(), llvm::SystemZISD::CLC, llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, earlyUseOperand(), emitBlockAfter(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), first, forceReg(), llvm::SystemZMC::FP64Regs, llvm::SmallVectorTemplateCommon< T >::front(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineInstr::getFlags(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getNumExplicitOperands(), llvm::SystemZInstrInfo::getOpcodeForOffset(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getProperties(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMC::GR64Regs, llvm::TargetFrameLowering::hasFP(), llvm::MipsISD::Hi, I, llvm::MachineOperand::isIdenticalTo(), isSelectPseudo(), llvm::MachineInstr::killsRegister(), llvm::MipsISD::Lo, llvm::MachineInstr::memoperands(), MI, MRI, llvm::SystemZISD::MVC, llvm::MachineFunctionProperties::NoPHIs, llvm::SystemZ::PFD_WRITE, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, Register, llvm::MachineInstr::registerDefIsDead(), llvm::MachineFunctionProperties::reset(), second, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineBasicBlock::splice(), splitBlockAfter(), splitBlockBefore(), std::swap(), TII, and llvm::SystemZMC::VR128Regs.
earlyUseOperand()
static MachineOperand earlyUseOperand (MachineOperand Op) static
Definition at line 74 of file SystemZISelLowering.cpp.
References llvm::MachineOperand::isReg(), and llvm::MachineOperand::setIsKill().
Referenced by createPHIsForSelects().
emitBlockAfter()
static MachineBasicBlock* emitBlockAfter (MachineBasicBlock * MBB) static
Definition at line 6698 of file SystemZISelLowering.cpp.
References llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineBasicBlock::getParent(), and llvm::MachineFunction::insert().
Referenced by createPHIsForSelects(), splitBlockAfter(), and splitBlockBefore().
emitCmp()
static SDValue emitCmp (SelectionDAG & DAG, const SDLoc & DL, Comparison & C) static
Definition at line 2583 of file SystemZISelLowering.cpp.
Referenced by CC_MipsO32_FP64(), getAbsolute(), getCompareCC(), and isMulPowOf2().
emitIntrinsicWithCC()
static SDNode* emitIntrinsicWithCC (SelectionDAG & DAG, SDValue Op, unsigned Opcode) static
Definition at line 1949 of file SystemZISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDNode::getVTList(), I, Intr, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by getCCResult().
emitIntrinsicWithCCAndChain()
static SDNode* emitIntrinsicWithCCAndChain (SelectionDAG & DAG, SDValue Op, unsigned Opcode) static
Definition at line 1929 of file SystemZISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getVTList(), I, llvm::MVT::i32, Intr, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by getCCResult().
emitSETCC()
static SDValue emitSETCC (SelectionDAG & DAG, const SDLoc & DL, SDValue CCReg, unsigned CCValid, unsigned CCMask) static
Definition at line 2644 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, and llvm::SystemZISD::SELECT_CCMASK.
Referenced by isSubBorrowChain(), and llvm::SystemZTargetLowering::LowerOperationWrapper().
expandV4F32ToV2F64()
static SDValue expandV4F32ToV2F64 (SelectionDAG & DAG, int Start, const SDLoc & DL, SDValue Op, SDValue Chain) static
Definition at line 2726 of file SystemZISelLowering.cpp.
forceReg()
static Register forceReg (MachineInstr & MI, MachineOperand & Base, const SystemZInstrInfo * TII) static
Definition at line 6726 of file SystemZISelLowering.cpp.
References add(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::isReg(), MRI, and Reg.
Referenced by createPHIsForSelects().
getAbsolute()
static SDValue getAbsolute (SelectionDAG & DAG, const SDLoc & DL, SDValue Op, bool IsNegative) static
Definition at line 2924 of file SystemZISelLowering.cpp.
References C, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::ISD::Constant, emitCmp(), getCmp(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::SystemZISD::IABS, llvm::SystemZISD::ICMP, isAbsolute(), llvm::SystemZISD::SELECT_CCMASK, and llvm::ISD::SUB.
getCCResult()
static SDValue getCCResult (SelectionDAG & DAG, SDValue CCReg) static
Definition at line 4076 of file SystemZISelLowering.cpp.
References assert(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getVTList(), llvm::MVT::i32, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, isIntrinsicWithCC(), isIntrinsicWithCCAndChain(), llvm::ISD::MERGE_VALUES, llvm::SystemZISD::PERMUTE, llvm::SystemZISD::PERMUTE_DWORDS, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SRL, llvm::SystemZISD::UNPACK_HIGH, llvm::SystemZISD::UNPACK_LOW, llvm::SystemZISD::UNPACKL_HIGH, llvm::SystemZISD::UNPACKL_LOW, llvm::SystemZ::VectorBytes, and llvm::SystemZISD::VSUM.
getCmp()
static Comparison getCmp (SelectionDAG & DAG, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, const SDLoc & DL, SDValue Chain = SDValue(), bool IsSignaling = false) static
Definition at line 2519 of file SystemZISelLowering.cpp.
Referenced by getAbsolute(), and INITIALIZE_PASS().
getDemandedSrcElements()
static APInt getDemandedSrcElements (SDValue Op, const APInt & DemandedElts, unsigned OpNo) static
Definition at line 6409 of file SystemZISelLowering.cpp.
References assert(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isVector(), llvm::SystemZISD::JOIN_DWORDS, llvm_unreachable, llvm::APInt::lshr(), llvm::APInt::lshrInPlace(), llvm::BitmaskEnumDetail::Mask(), llvm::SystemZISD::SELECT_CCMASK, llvm::APInt::setBit(), llvm::APInt::trunc(), and llvm::MVT::v16i8.
Referenced by computeKnownBitsBinOp(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), computeNumSignBitsBinOp(), and llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode().
getGeneralPermuteNode()
static SDValue getGeneralPermuteNode (SelectionDAG & DAG, const SDLoc & DL, SDValue * Ops, const SmallVectorImpl< int > & Bytes) static
Definition at line 4426 of file SystemZISelLowering.cpp.
References add(), assert(), llvm::ISD::BITCAST, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPermuteNode(), getShuffleInput(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), getVPermMask(), llvm::SDValue::hasOneUse(), I, llvm::MVT::i32, isShlDoublePermute(), llvm::SDValue::isUndef(), matchDoublePermute(), matchPermute(), P, llvm::SystemZISD::PERMUTE, llvm::SystemZISD::SHL_DOUBLE, llvm::MVT::v16i8, llvm::ISD::VECTOR_SHUFFLE, and llvm::SystemZ::VectorBytes.
getIntrinsicCmp()
static Comparison getIntrinsicCmp (SelectionDAG & DAG, unsigned Opcode, SDValue Call, unsigned CCValid, uint64_t CC, ISD::CondCode Cond) static
Definition at line 2486 of file SystemZISelLowering.cpp.
getLoadStoreAddrMode()
static AddressingMode getLoadStoreAddrMode (bool HasVector, Type * Ty) static
Definition at line 853 of file SystemZISelLowering.cpp.
References llvm::Type::isIntegerTy(), and llvm::SystemZISD::MVC.
Referenced by supportedAddressingMode().
getPermuteNode()
static SDValue getPermuteNode (SelectionDAG & DAG, const SDLoc & DL, const Permute & P, SDValue Op0, SDValue Op1) static
Definition at line 4397 of file SystemZISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::SystemZISD::PACK, llvm::SystemZISD::PERMUTE_DWORDS, and llvm::SystemZ::VectorBytes.
Referenced by getGeneralPermuteNode().
getShuffleInput()
static bool getShuffleInput (const SmallVectorImpl< int > & Bytes, unsigned Start, unsigned BytesPerElement, int & Base) static
Definition at line 4346 of file SystemZISelLowering.cpp.
Referenced by getGeneralPermuteNode(), and llvm::SystemZTargetLowering::getTargetNodeName().
getTestUnderMaskCond()
static unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType) static
Definition at line 2285 of file SystemZISelLowering.cpp.
References assert(), llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_TM_ALL_0, llvm::SystemZ::CCMASK_TM_ALL_1, llvm::SystemZ::CCMASK_TM_MIXED_MSB_0, llvm::SystemZ::CCMASK_TM_MIXED_MSB_1, llvm::SystemZ::CCMASK_TM_MSB_0, llvm::SystemZ::CCMASK_TM_MSB_1, llvm::SystemZ::CCMASK_TM_SOME_0, llvm::SystemZ::CCMASK_TM_SOME_1, llvm::countLeadingZeros(), llvm::countTrailingZeros(), High, llvm::SystemZ::isImmHH(), llvm::SystemZ::isImmHL(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), and llvm::SystemZICMP::SignedOnly.
Referenced by adjustForTestUnderMask().
getVectorComparison()
static unsigned getVectorComparison (ISD::CondCode CC, CmpMode Mode) static
Definition at line 2659 of file SystemZISelLowering.cpp.
References FP, Int, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETUGT, SignalingFP, llvm::SystemZISD::STRICT_VFCMPE, llvm::SystemZISD::STRICT_VFCMPES, llvm::SystemZISD::STRICT_VFCMPH, llvm::SystemZISD::STRICT_VFCMPHE, llvm::SystemZISD::STRICT_VFCMPHES, llvm::SystemZISD::STRICT_VFCMPHS, StrictFP, llvm::SystemZISD::VFCMPE, llvm::SystemZISD::VFCMPH, llvm::SystemZISD::VFCMPHE, llvm::SystemZISD::VICMPE, llvm::SystemZISD::VICMPH, and llvm::SystemZISD::VICMPHL.
Referenced by getVectorComparisonOrInvert().
getVectorComparisonOrInvert()
static unsigned getVectorComparisonOrInvert (ISD::CondCode CC, CmpMode Mode, bool & Invert) static
Definition at line 2708 of file SystemZISelLowering.cpp.
References llvm::MVT::f32, llvm::ISD::getSetCCInverse(), getVectorComparison(), llvm::MVT::i32, and Int.
getVPermMask()
static bool getVPermMask (SDValue ShuffleOp, SmallVectorImpl< int > & Bytes) static
Definition at line 4314 of file SystemZISelLowering.cpp.
References llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), I, llvm::SmallVectorImpl< T >::resize(), and llvm::SystemZISD::SPLAT.
Referenced by getGeneralPermuteNode(), and llvm::SystemZTargetLowering::getTargetNodeName().
is32Bit()
static bool is32Bit (EVT VT) static
Definition at line 61 of file SystemZISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, and llvm::MVT::SimpleTy.
Referenced by lowerGR128Binary().
isAbsolute()
static bool isAbsolute (SDValue CmpOp, SDValue Pos, SDValue Neg) static
Definition at line 2913 of file SystemZISelLowering.cpp.
References llvm::ISD::Constant, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::SUB.
Referenced by getAbsolute().
isAddCarryChain()
static bool isAddCarryChain (SDValue Carry) static
Definition at line 3638 of file SystemZISelLowering.cpp.
References llvm::ISD::ADDCARRY, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), and llvm::ISD::UADDO.
Referenced by isSubBorrowChain().
isIntrinsicWithCC()
static bool isIntrinsicWithCC (SDValue Op, unsigned & Opcode, unsigned & CCValid) static
Definition at line 1771 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_0, llvm::SystemZ::CCMASK_3, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_TDC, llvm::SystemZ::CCMASK_VCMP, llvm::SDValue::getOperand(), llvm::SystemZISD::PACKLS_CC, llvm::SystemZISD::PACKS_CC, llvm::SystemZISD::TDC, llvm::SystemZISD::VFAE_CC, llvm::SystemZISD::VFAEZ_CC, llvm::SystemZISD::VFCMPES, llvm::SystemZISD::VFCMPHES, llvm::SystemZISD::VFCMPHS, llvm::SystemZISD::VFEE_CC, llvm::SystemZISD::VFEEZ_CC, llvm::SystemZISD::VFENE_CC, llvm::SystemZISD::VFENEZ_CC, llvm::SystemZISD::VFTCI, llvm::SystemZISD::VICMPES, llvm::SystemZISD::VICMPHLS, llvm::SystemZISD::VICMPHS, llvm::SystemZISD::VISTR_CC, llvm::SystemZISD::VSTRC_CC, llvm::SystemZISD::VSTRCZ_CC, llvm::SystemZISD::VSTRS_CC, llvm::SystemZISD::VSTRSZ_CC, and llvm::SystemZISD::VTM.
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), and getCCResult().
isIntrinsicWithCCAndChain()
static bool isIntrinsicWithCCAndChain (SDValue Op, unsigned & Opcode, unsigned & CCValid) static
Definition at line 1744 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_TBEGIN, llvm::SystemZ::CCMASK_TEND, llvm::SDValue::getOperand(), llvm::SystemZISD::TBEGIN, llvm::SystemZISD::TBEGIN_NOFLOAT, and llvm::SystemZISD::TEND.
Referenced by getCCResult().
isNaturalMemoryOperand()
static bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType) static
Definition at line 2085 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::MVT::i8, llvm::SPII::Load, llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
Referenced by shouldSwapCmpOperands().
isScalarToVector()
static bool isScalarToVector (SDValue Op) static
Definition at line 4623 of file SystemZISelLowering.cpp.
References E, llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), I, and llvm::SDValue::isUndef().
Referenced by tryBuildVectorShuffle().
isSelectPseudo()
static bool isSelectPseudo (MachineInstr & MI) static
Definition at line 6771 of file SystemZISelLowering.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by createPHIsForSelects().
isShlDoublePermute()
static bool isShlDoublePermute (const SmallVectorImpl< int > & Bytes, unsigned & StartIndex, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 4369 of file SystemZISelLowering.cpp.
References chooseShuffleOpNos(), I, and llvm::SystemZ::VectorBytes.
Referenced by getGeneralPermuteNode().
isSimpleShift()
static bool isSimpleShift (SDValue N, unsigned & ShiftVal) static
Definition at line 2266 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getOperand(), llvm::SDValue::getValueSizeInBits(), and llvm::ConstantSDNode::getZExtValue().
Referenced by adjustForTestUnderMask().
isSubBorrowChain()
static bool isSubBorrowChain (SDValue Carry) static
Definition at line 3644 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::SystemZISD::ADDCARRY, llvm::ISD::ADDCARRY, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::SystemZISD::ATOMIC_CMP_SWAP, llvm::SystemZISD::ATOMIC_CMP_SWAPW, llvm::ISD::ATOMIC_LOAD_ADD, llvm::SystemZISD::ATOMIC_LOADW_ADD, llvm::SystemZISD::ATOMIC_LOADW_AND, llvm::SystemZISD::ATOMIC_LOADW_NAND, llvm::SystemZISD::ATOMIC_LOADW_SUB, llvm::SystemZISD::ATOMIC_SWAPW, llvm::ISD::BITCAST, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CS, llvm::SystemZ::CCMASK_CS_EQ, llvm::SystemZ::CCMASK_ICMP, llvm::SystemZ::CCMASK_LOGICAL, llvm::SystemZ::CCMASK_LOGICAL_BORROW, llvm::SystemZ::CCMASK_LOGICAL_CARRY, llvm::SelectionDAG::computeKnownBits(), emitSETCC(), llvm::ISD::EXTLOAD, llvm::SystemZISD::GET_CCMASK, llvm::APInt::getActiveBits(), llvm::SelectionDAG::getAtomic(), llvm::Function::getCallingConv(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getExtLoad(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::KnownBits::getMaxValue(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getSplatBuildVector(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::CallingConv::GHC, llvm::Function::hasFnAttribute(), I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, isAddCarryChain(), llvm::isInt< 32 >(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm_unreachable, llvm::Log2_32_Ceil(), llvm::SystemZISD::MEMBARRIER, llvm::ISD::MERGE_VALUES, llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, N, llvm::ISD::OR, llvm::MVT::Other, llvm::SystemZ::PFD_READ, llvm::SystemZ::PFD_WRITE, llvm::SystemZISD::POPCNT, llvm::SystemZISD::PREFETCH, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::report_fatal_error(), llvm::ISD::ROTL, llvm::SequentiallyConsistent, llvm::ISD::SHL, SI, llvm::ISD::SRL, llvm::ISD::SUB, llvm::SystemZISD::SUBCARRY, llvm::ISD::SUBCARRY, Success, llvm::SyncScope::System, llvm::ISD::TRUNCATE, llvm::ISD::USUBO, llvm::MVT::v16i8, llvm::MVT::v4i32, llvm::SystemZISD::VSHL_BY_SCALAR, llvm::SystemZISD::VSRL_BY_SCALAR, and llvm::SystemZISD::VSUM.
isVectorElementSwap()
static bool isVectorElementSwap (ArrayRef< int > M, EVT VT) static
Definition at line 5747 of file SystemZISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::ISD::BSWAP, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::EVT::isInteger(), llvm::ISD::isNON_EXTLoad(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::ARM_MB::LD, llvm::SPII::Load, N, llvm::MVT::Other, llvm::SystemZISD::REPLICATE, llvm::SystemZISD::STRV, llvm::ISD::VECTOR_SHUFFLE, llvm::SystemZISD::VLER, and llvm::SystemZISD::VSTER.
joinDwords()
static SDValue joinDwords (SelectionDAG & DAG, const SDLoc & DL, SDValue Op0, SDValue Op1) static
Definition at line 4664 of file SystemZISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::i64, llvm::SDValue::isUndef(), llvm::SystemZISD::JOIN_DWORDS, and llvm::MVT::v2i64.
Referenced by tryBuildVectorShuffle().
lowerGR128Binary()
static void lowerGR128Binary (SelectionDAG & DAG, const SDLoc & DL, EVT VT, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue & Even, SDValue & Odd) static
Definition at line 2632 of file SystemZISelLowering.cpp.
References llvm::SystemZ::even128(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), is32Bit(), llvm::SystemZ::odd128(), and llvm::MVT::Untyped.
lowerGR128ToI128()
static SDValue lowerGR128ToI128 (SelectionDAG & DAG, SDValue In) static
Definition at line 5226 of file SystemZISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::MipsISD::Hi, llvm::MVT::i128, llvm::MVT::i64, and llvm::MipsISD::Lo.
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
lowerI128ToGR128()
static SDValue lowerI128ToGR128 (SelectionDAG & DAG, SDValue In) static
Definition at line 5215 of file SystemZISelLowering.cpp.
References llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, llvm::MVT::i64, llvm::MipsISD::Lo, and llvm::MVT::Untyped.
Referenced by llvm::SystemZTargetLowering::LowerOperationWrapper().
lowerMUL_LOHI32()
static void lowerMUL_LOHI32 (SelectionDAG & DAG, const SDLoc & DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue & Hi, SDValue & Lo) static
Definition at line 2616 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::MUL, llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
matchDoublePermute() [1/2]
static bool matchDoublePermute (const SmallVectorImpl< int > & Bytes, const Permute & P, SmallVectorImpl< int > & Transform) static
Definition at line 4282 of file SystemZISelLowering.cpp.
References From, and llvm::SystemZ::VectorBytes.
Referenced by getGeneralPermuteNode(), and matchDoublePermute().
matchDoublePermute() [2/2]
static const Permute* matchDoublePermute (const SmallVectorImpl< int > & Bytes, SmallVectorImpl< int > & Transform) static
Definition at line 4304 of file SystemZISelLowering.cpp.
References matchDoublePermute(), and P.
matchPermute() [1/2]
static bool matchPermute (const SmallVectorImpl< int > & Bytes, const Permute & P, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 4245 of file SystemZISelLowering.cpp.
References chooseShuffleOpNos(), I, and llvm::SystemZ::VectorBytes.
Referenced by getGeneralPermuteNode(), and matchPermute().
matchPermute() [2/2]
static const Permute* matchPermute (const SmallVectorImpl< int > & Bytes, unsigned & OpNo0, unsigned & OpNo1) static
Definition at line 4269 of file SystemZISelLowering.cpp.
References matchPermute(), and P.
MergeInputChains()
static SDValue MergeInputChains (SDNode * N1, SDNode * N2) static
Definition at line 5914 of file SystemZISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BSWAP, llvm::ISD::Constant, llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::SelectionDAG::isConstantIntBuildVectorOrConstantInt(), llvm::ISD::isNON_EXTLoad(), llvm::SDNode::isStrictFPOpcode(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::ARM_MB::LD, llvm::SPII::Load, llvm::SystemZISD::LRV, llvm::ISD::MERGE_VALUES, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SystemZISD::STRICT_VEXTEND, llvm::SystemZISD::STRICT_VROUND, llvm::ISD::TRUNCATE, llvm::SDNode::uses(), llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::SystemZISD::VEXTEND, and llvm::SystemZISD::VROUND.
parseRegisterNumber()
static std::pair<unsigned, const TargetRegisterClass *> parseRegisterNumber (StringRef Constraint, const TargetRegisterClass * RC, const unsigned * Map, unsigned Size) static
Definition at line 1087 of file SystemZISelLowering.cpp.
References assert(), llvm::StringRef::end(), llvm::Failed(), llvm::StringRef::size(), and llvm::StringRef::slice().
Referenced by llvm::SystemZTargetLowering::getRegForInlineAsmConstraint().
reverseCCMask()
static unsigned reverseCCMask (unsigned CCMask) static
Definition at line 2166 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, and llvm::SystemZ::CCMASK_CMP_UO.
Referenced by adjustForFNeg().
shouldSwapCmpOperands()
static bool shouldSwapCmpOperands (const Comparison & C) static
Definition at line 2107 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::Constant, llvm::dyn_cast(), llvm::MVT::f128, llvm::isInt< 16 >(), isNaturalMemoryOperand(), llvm::isUInt< 16 >(), llvm::ISD::SIGN_EXTEND, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZERO_EXTEND.
splitBlockAfter()
static MachineBasicBlock* splitBlockAfter (MachineBasicBlock::iterator MI, MachineBasicBlock * MBB) static
Definition at line 6707 of file SystemZISelLowering.cpp.
References llvm::MachineBasicBlock::begin(), emitBlockAfter(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by createPHIsForSelects().
splitBlockBefore()
static MachineBasicBlock* splitBlockBefore (MachineBasicBlock::iterator MI, MachineBasicBlock * MBB) static
Definition at line 6717 of file SystemZISelLowering.cpp.
References llvm::MachineBasicBlock::begin(), emitBlockAfter(), llvm::MachineBasicBlock::end(), MI, llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by createPHIsForSelects().
supportedAddressingMode()
static AddressingMode supportedAddressingMode (Instruction * I, bool HasVector) static
Definition at line 869 of file SystemZISelLowering.cpp.
References C, getLoadStoreAddrMode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::Type::isFloatingPointTy(), llvm::isInt< 16 >(), llvm::isUInt< 16 >(), llvm::Type::isVectorTy(), and llvm::Value::user_begin().
Referenced by llvm::SystemZTargetLowering::isLegalAddressingMode().
tryBuildVectorShuffle()
static SDValue tryBuildVectorShuffle (SelectionDAG & DAG, BuildVectorSDNode * BVN) static
Definition at line 4685 of file SystemZISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, buildMergeScalars(), buildScalarToVector(), llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::SmallVectorBase::empty(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::X86AS::GS, I, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::isOperationLegal(), isScalarToVector(), llvm::SDValue::isUndef(), isUndef(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), joinDwords(), llvm::ISD::LOAD, llvm::SystemZISD::LRV, llvm::BitmaskEnumDetail::Mask(), llvm::SystemZISD::MERGE_HIGH, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SystemZISD::REPLICATE, llvm::ISD::SCALAR_TO_VECTOR, llvm::pdb::Single, llvm::SmallVectorBase::size(), llvm::SystemZISD::SPLAT, llvm::ISD::TRUNCATE, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::SystemZ::VectorBits.
VerifyVectorType()
static void VerifyVectorType (MVT VT, EVT ArgVT) static
Definition at line 1253 of file SystemZISelLowering.cpp.
References llvm::EVT::isVector(), llvm::MVT::isVector(), and llvm::report_fatal_error().
Referenced by VerifyVectorTypes().
VerifyVectorTypes() [1/2]
static void VerifyVectorTypes (const SmallVectorImpl< ISD::InputArg > & Ins) static
Definition at line 1258 of file SystemZISelLowering.cpp.
References llvm::SmallVectorBase::size(), and VerifyVectorType().
Referenced by llvm::SystemZTargetLowering::CanLowerReturn(), llvm::SystemZTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerFormalArguments(), and llvm::SystemZTargetLowering::LowerReturn().
VerifyVectorTypes() [2/2]
static void VerifyVectorTypes (const SmallVectorImpl< ISD::OutputArg > & Outs) static
Definition at line 1263 of file SystemZISelLowering.cpp.
References llvm::SmallVectorBase::size(), and VerifyVectorType().
Variable Documentation
PermuteForms
const Permute PermuteForms[] static
Definition at line 4173 of file SystemZISelLowering.cpp.