LLVM: lib/Object/TapiFile.cpp File Reference
TapiFile.cpp File Reference
#include "llvm/Object/TapiFile.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
static uint32_t getFlags (const Symbol *Sym)
Variables
static constexpr StringLiteral ObjC1ClassNamePrefix = ".objc_class_name_"
static constexpr StringLiteral ObjC2ClassNamePrefix = "_OBJC_CLASS_$_"
static constexpr StringLiteral ObjC2MetaClassNamePrefix = "_OBJC_METACLASS_$_"
static constexpr StringLiteral ObjC2EHTypePrefix = "_OBJC_EHTYPE_$_"
static constexpr StringLiteral ObjC2IVarPrefix = "_OBJC_IVAR_$_"
Function Documentation
getFlags()
static uint32_t getFlags (const Symbol * Sym) static
Definition at line 28 of file TapiFile.cpp.
References llvm::MachO::Symbol::isUndefined(), llvm::MachO::Symbol::isWeakDefined(), and llvm::MachO::Symbol::isWeakReferenced().
Referenced by createRdxShuffleMask(), llvm::orc::JITDylib::getExecutionSession(), llvm::DIType::getExportSymbols(), llvm::rdf::RefNode::getOp(), llvm::object::XCOFFObjectFile::getPointerToSymbolTable(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::codeview::Compile3Sym::hasOptimizations(), llvm::DIType::isAppleBlockExtension(), llvm::DIType::isArtificial(), llvm::DILocalVariable::isArtificial(), llvm::DIType::isBigEndian(), llvm::DIType::isBitField(), llvm::DIType::isForwardDecl(), llvm::DIType::isLittleEndian(), llvm::DIType::isLValueReference(), llvm::DIType::isObjcClassComplete(), llvm::DIType::isObjectPointer(), llvm::DILocalVariable::isObjectPointer(), llvm::DIType::isPrivate(), llvm::DIType::isProtected(), llvm::DIType::isPublic(), llvm::DIType::isRValueReference(), llvm::DIType::isStaticMember(), llvm::DIType::isTypePassByReference(), llvm::DIType::isTypePassByValue(), llvm::DIType::isVector(), llvm::DIType::isVirtual(), LLVMDITypeGetFlags(), llvm::orc::JITDylib::removeGenerator(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::object::TapiFile::TapiFile(), and llvm::DISubprogram::toSPFlags().
Variable Documentation
ObjC1ClassNamePrefix
constexpr StringLiteral ObjC1ClassNamePrefix = ".objc_class_name_" static
Definition at line 22 of file TapiFile.cpp.
Referenced by llvm::object::TapiFile::TapiFile().
ObjC2ClassNamePrefix
constexpr StringLiteral ObjC2ClassNamePrefix = "_OBJC_CLASS_$_" static
Definition at line 23 of file TapiFile.cpp.
Referenced by llvm::object::TapiFile::TapiFile().
ObjC2EHTypePrefix
constexpr StringLiteral ObjC2EHTypePrefix = "_OBJC_EHTYPE_$_" static
Definition at line 25 of file TapiFile.cpp.
Referenced by llvm::object::TapiFile::TapiFile().
ObjC2IVarPrefix
constexpr StringLiteral ObjC2IVarPrefix = "_OBJC_IVAR_$_" static
Definition at line 26 of file TapiFile.cpp.
Referenced by llvm::object::TapiFile::TapiFile().
ObjC2MetaClassNamePrefix
constexpr StringLiteral ObjC2MetaClassNamePrefix = "_OBJC_METACLASS_$_" static
Definition at line 24 of file TapiFile.cpp.
Referenced by llvm::object::TapiFile::TapiFile().