LLVM: lib/CodeGen/TargetLoweringObjectFileImpl.cpp File Reference
TargetLoweringObjectFileImpl.cpp File Reference
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSectionXCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <string>
Functions
static void GetObjCImageInfo (Module &M, unsigned &Version, unsigned &Flags, StringRef &Section)
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K)
static unsigned getELFSectionType (StringRef Name, SectionKind K)
static unsigned getELFSectionFlags (SectionKind K)
static const Comdat * getELFComdat (const GlobalValue *GV)
static const MCSymbolELF * getAssociatedSymbol (const GlobalObject *GO, const TargetMachine &TM)
static unsigned getEntrySizeForKind (SectionKind Kind)
static StringRef getSectionPrefixForGlobal (SectionKind Kind)
Return the section prefix name used by options FunctionsSections and DataSections.
static MCSectionELF * selectELFSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned Flags, unsigned *NextUniqueID, const MCSymbolELF *AssociatedSymbol)
static MCSectionELF * getStaticStructorSection (MCContext &Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol *KeySym)
static void checkMachOComdat (const GlobalValue *GV)
static bool canUsePrivateLabel (const MCAsmInfo &AsmInfo, const MCSection &Section)
static unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine &TM)
static const GlobalValue * getComdatGVForCOFF (const GlobalValue *GV)
static int getSelectionForCOFF (const GlobalValue *GV)
static StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind)
static MCSectionCOFF * getCOFFStaticStructorSection (MCContext &Ctx, const Triple &T, bool IsCtor, unsigned Priority, const MCSymbol *KeySym, MCSectionCOFF *Default)
static std::string APIntToHexString (const APInt &AI)
static std::string scalarConstantToHexString (const Constant *C)
static const Comdat * getWasmComdat (const GlobalValue *GV)
static SectionKind getWasmKindForNamedSection (StringRef Name, SectionKind K)
static MCSectionWasm * selectWasmSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned *NextUniqueID)
Function Documentation
APIntToHexString()
static std::string APIntToHexString (const APInt & AI) static
Definition at line 1599 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::APInt::getBitWidth(), Size, llvm::APInt::toString(), and llvm::transform().
Referenced by scalarConstantToHexString().
canUsePrivateLabel()
static bool canUsePrivateLabel (const MCAsmInfo & AsmInfo, const MCSection & Section) static
Definition at line 1190 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCSectionMachO::hasAttribute(), llvm::MCAsmInfo::isSectionAtomizableBySymbols(), llvm::MachO::S_ATTR_NO_DEAD_STRIP, and llvm::ARMBuildAttrs::Section.
Referenced by llvm::TargetLoweringObjectFileMachO::getNameWithPrefix().
checkMachOComdat()
static void checkMachOComdat (const GlobalValue * GV) static
Definition at line 928 of file TargetLoweringObjectFileImpl.cpp.
References C, llvm::GlobalValue::getComdat(), llvm::Comdat::getName(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
getAssociatedSymbol()
static const MCSymbolELF* getAssociatedSymbol (const GlobalObject * GO, const TargetMachine & TM) static
Definition at line 515 of file TargetLoweringObjectFileImpl.cpp.
References llvm::dyn_cast(), llvm::MDOperand::get(), llvm::GlobalObject::getMetadata(), llvm::MDNode::getOperand(), llvm::TargetMachine::getSymbol(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getCOFFSectionFlags()
static unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine & TM) static
Definition at line 1221 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Triple::getArch(), llvm::TargetMachine::getTargetTriple(), llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_16BIT, llvm::COFF::IMAGE_SCN_MEM_DISCARDABLE, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, llvm::SectionKind::isBSS(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), isThumb(), llvm::SectionKind::isWriteable(), and llvm::Triple::thumb.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFSectionNameForUniqueGlobal()
static StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind) static
Definition at line 1326 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isBSS(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), and llvm::SectionKind::isThreadLocal().
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFStaticStructorSection()
static MCSectionCOFF* getCOFFStaticStructorSection (MCContext & Ctx, const Triple & T, bool IsCtor, unsigned Priority, const MCSymbol * KeySym, MCSectionCOFF * Default) static
Definition at line 1506 of file TargetLoweringObjectFileImpl.cpp.
References llvm::format(), llvm::MCContext::getAssociativeCOFFSection(), llvm::MCContext::getCOFFSection(), llvm::SectionKind::getData(), llvm::SectionKind::getReadOnly(), llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, llvm::Triple::isWindowsItaniumEnvironment(), llvm::Triple::isWindowsMSVCEnvironment(), and Name.
Referenced by llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection().
getComdatGVForCOFF()
static const GlobalValue* getComdatGVForCOFF (const GlobalValue * GV) static
Definition at line 1257 of file TargetLoweringObjectFileImpl.cpp.
References assert(), C, llvm::GlobalValue::getComdat(), llvm::Comdat::getName(), llvm::Module::getNamedValue(), llvm::GlobalValue::getParent(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), getSelectionForCOFF(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getELFComdat()
static const Comdat* getELFComdat (const GlobalValue * GV) static
Definition at line 503 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, C, llvm::GlobalValue::getComdat(), llvm::Comdat::getName(), llvm::Comdat::getSelectionKind(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and selectELFSectionForGlobal().
getELFKindForNamedSection()
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K) static
Definition at line 414 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Triple::ELF, llvm::StringRef::empty(), llvm::SectionKind::getBSS(), llvm::getInstrProfSectionName(), llvm::SectionKind::getMetadata(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), and llvm::StringRef::startswith().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal().
getELFSectionFlags()
static unsigned getELFSectionFlags (SectionKind K) static
Definition at line 476 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isExecuteOnly(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableCString(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), llvm::SectionKind::isWriteable(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_ARM_PURECODE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, and llvm::ELF::SHF_WRITE.
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getELFSectionType()
static unsigned getELFSectionType (StringRef Name, SectionKind K) static
Definition at line 454 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isBSS(), llvm::SectionKind::isThreadBSS(), llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PREINIT_ARRAY, llvm::ELF::SHT_PROGBITS, and llvm::StringRef::startswith().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and selectELFSectionForGlobal().
getEntrySizeForKind()
static unsigned getEntrySizeForKind (SectionKind Kind) static
Definition at line 533 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::SectionKind::isMergeable1ByteCString(), llvm::SectionKind::isMergeable2ByteCString(), llvm::SectionKind::isMergeable4ByteCString(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst32(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), and llvm::SectionKind::isMergeableCString().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), selectELFSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
GetObjCImageInfo()
static void GetObjCImageInfo (Module & M, unsigned & Version, unsigned & Flags, StringRef & Section) static
Definition at line 65 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Module::getModuleFlagsMetadata(), and llvm::Module::Require.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), and llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata().
getSectionPrefixForGlobal()
static StringRef getSectionPrefixForGlobal (SectionKind Kind) static
Return the section prefix name used by options FunctionsSections and DataSections.
Definition at line 613 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::SectionKind::isBSS(), llvm::SectionKind::isData(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadBSS(), and llvm::SectionKind::isThreadData().
Referenced by selectELFSectionForGlobal(), and selectWasmSectionForGlobal().
getSelectionForCOFF()
static int getSelectionForCOFF (const GlobalValue * GV) static
Definition at line 1274 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, C, llvm::Comdat::ExactMatch, llvm::GlobalValue::getBaseObject(), llvm::GlobalValue::getComdat(), getComdatGVForCOFF(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, llvm::Comdat::Largest, llvm::Comdat::NoDuplicates, and llvm::Comdat::SameSize.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getStaticStructorSection()
static MCSectionELF* getStaticStructorSection (MCContext & Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol * KeySym) static
Definition at line 754 of file TargetLoweringObjectFileImpl.cpp.
References llvm::format(), llvm::MCContext::getELFSection(), llvm::MCSymbol::getName(), Name, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_PROGBITS, and llvm::utostr().
Referenced by llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileELF::getStaticDtorSection().
getWasmComdat()
static const Comdat* getWasmComdat (const GlobalValue * GV) static
Definition at line 1681 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, C, llvm::GlobalValue::getComdat(), llvm::Comdat::getName(), llvm::Comdat::getSelectionKind(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), and selectWasmSectionForGlobal().
getWasmKindForNamedSection()
static SectionKind getWasmKindForNamedSection (StringRef Name, SectionKind K) static
Definition at line 1694 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::getData(), llvm::SectionKind::getText(), and llvm::SectionKind::isText().
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal().
scalarConstantToHexString()
static std::string scalarConstantToHexString (const Constant * C) static
Definition at line 1610 of file TargetLoweringObjectFileImpl.cpp.
References APIntToHexString(), E, llvm::Constant::getAggregateElement(), llvm::Type::getArrayNumElements(), llvm::APInt::getNullValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), and I.
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForConstant().
selectELFSectionForGlobal()
static MCSectionELF* selectELFSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned Flags, unsigned * NextUniqueID, const MCSymbolELF * AssociatedSymbol) static
Definition at line 630 of file TargetLoweringObjectFileImpl.cpp.
References C, F(), llvm::MCContext::GenericSectionID, llvm::Module::getDataLayout(), getELFComdat(), llvm::MCContext::getELFSection(), getELFSectionType(), getEntrySizeForKind(), llvm::Value::getName(), llvm::TargetMachine::getNameWithPrefix(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPreferredAlignment(), getSectionPrefixForGlobal(), llvm::TargetMachine::getUniqueSectionNames(), llvm::SectionKind::isExecuteOnly(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableCString(), Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ELF::SHF_GROUP, and llvm::utostr().
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
selectWasmSectionForGlobal()
static MCSectionWasm* selectWasmSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned * NextUniqueID) static
Definition at line 1728 of file TargetLoweringObjectFileImpl.cpp.
References C, F(), llvm::MCContext::GenericSectionID, llvm::Value::getName(), llvm::TargetMachine::getNameWithPrefix(), getSectionPrefixForGlobal(), llvm::TargetMachine::getUniqueSectionNames(), getWasmComdat(), llvm::MCContext::getWasmSection(), Name, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal().