LLVM: lib/Support/Timer.cpp File Reference
Timer.cpp File Reference
#include "llvm/Support/Timer.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Signposts.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include <limits>
Functions
static std::string & getLibSupportInfoOutputFilename ()
static TimerGroup * getDefaultTimerGroup ()
static size_t getMemUsage ()
static void printVal (double Val, double Total, raw_ostream &OS)
Variables
static ManagedStatic< std::string > LibSupportInfoOutputFilename
static ManagedStatic< sys::SmartMutex< true > > TimerLock
static ManagedStatic< SignpostEmitter > Signposts
Allows llvm::Timer to emit signposts when supported.
static ManagedStatic< TimerGroup, CreateDefaultTimerGroup > DefaultTimerGroup
static ManagedStatic< Name2PairMap > NamedGroupedTimers
static TimerGroup * TimerGroupList = nullptr
This is the global list of TimerGroups, maintained by the TimerGroup ctor/dtor and is protected by the TimerLock lock.
Function Documentation
getDefaultTimerGroup()
static TimerGroup* getDefaultTimerGroup () static
Definition at line 88 of file Timer.cpp.
References DefaultTimerGroup.
Referenced by llvm::Timer::init(), and llvm::TimerGroup::~TimerGroup().
getLibSupportInfoOutputFilename()
static std::string& getLibSupportInfoOutputFilename () static
Definition at line 37 of file Timer.cpp.
References LibSupportInfoOutputFilename.
Referenced by llvm::CreateInfoOutputFile().
getMemUsage()
static size_t getMemUsage () inline static
Definition at line 113 of file Timer.cpp.
References llvm::sys::Process::GetMallocUsage().
printVal()
static void printVal (double Val, double Total, raw_ostream & OS) static
Definition at line 158 of file Timer.cpp.
References llvm::numbers::e, and llvm::format().
Referenced by llvm::TimeRecord::print().
Variable Documentation
DefaultTimerGroup
ManagedStatic<TimerGroup, CreateDefaultTimerGroup> DefaultTimerGroup static
Definition at line 87 of file Timer.cpp.
Referenced by getDefaultTimerGroup().
LibSupportInfoOutputFilename
ManagedStatic<std::string> LibSupportInfoOutputFilename static
Definition at line 36 of file Timer.cpp.
Referenced by getLibSupportInfoOutputFilename().
NamedGroupedTimers
ManagedStatic<Name2PairMap> NamedGroupedTimers static
Definition at line 216 of file Timer.cpp.
Signposts
ManagedStatic<SignpostEmitter> Signposts static
Allows llvm::Timer to emit signposts when supported.
Definition at line 44 of file Timer.cpp.
TimerGroupList
TimerGroup* TimerGroupList = nullptr static
This is the global list of TimerGroups, maintained by the TimerGroup ctor/dtor and is protected by the TimerLock lock.
Definition at line 231 of file Timer.cpp.
Referenced by llvm::TimerGroup::TimerGroup().
TimerLock
ManagedStatic<sys::SmartMutex<true> > TimerLock static
Definition at line 41 of file Timer.cpp.