LLVM: lib/DebugInfo/CodeView/TypeStreamMerger.cpp File Reference
TypeStreamMerger.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeStreamMerger.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/DebugInfo/CodeView/GlobalTypeTableBuilder.h"
#include "llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/DebugInfo/CodeView/TypeIndexDiscovery.h"
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
#include "llvm/DebugInfo/CodeView/TypeRecordHelpers.h"
#include "llvm/Support/Error.h"
Functions
static size_t slotForIndex (TypeIndex Idx)
Function Documentation
slotForIndex()
static size_t slotForIndex (TypeIndex Idx) inline static
Definition at line 24 of file TypeStreamMerger.cpp.
References assert(), llvm::codeview::corrupt_record, llvm::codeview::TypeIndex::FirstNonSimpleIndex, llvm::codeview::TypeIndex::getIndex(), llvm::codeview::TypeIndex::isSimple(), llvm::joinErrors(), LLVM_LIKELY, LLVM_UNLIKELY, llvm::codeview::mergeIdRecords(), llvm::codeview::mergeTypeRecords(), llvm::codeview::NotTranslated, llvm::SmallVectorBase::size(), and llvm::ArrayRef< T >::size().