LLVM: lib/CodeGen/TypePromotion.cpp File Reference
TypePromotion.cpp File Reference
This is an opcode based type promotion pass for small types that would otherwise be promoted during legalisation.
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "type-promotion"
#define PASS_NAME "Type Promotion"
Functions
static bool GenerateSignBits (Value *V)
static bool isPromotedResultSafe (Value *V)
Return whether we can safely mutate V's type to ExtTy without having to be concerned with zero extending or truncation.
Variables
static cl::opt< bool > DisablePromotion ("disable-type-promotion", cl::Hidden, cl::init(false), cl::desc("Disable type promotion pass"))
Detailed Description
This is an opcode based type promotion pass for small types that would otherwise be promoted during legalisation.
This works around the limitations of selection dag for cyclic regions. The search begins from icmp instructions operands where a tree, consisting of non-wrapping or safe wrapping instructions, is built, checked and promoted if possible.
Definition in file TypePromotion.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "type-promotion"
Definition at line 44 of file TypePromotion.cpp.
Referenced by isPromotedResultSafe().
PASS_NAME
#define PASS_NAME "Type Promotion"
Definition at line 45 of file TypePromotion.cpp.
Referenced by isPromotedResultSafe().
Function Documentation
GenerateSignBits()
static bool GenerateSignBits (Value * V) static
Definition at line 196 of file TypePromotion.cpp.
References llvm::APInt::abs(), llvm::MCID::Add, llvm::dbgs(), llvm::dyn_cast(), llvm::APInt::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::Instruction::getOpcode(), getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::ConstantInt::isNegative(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MCID::Return, llvm::SPII::Store, llvm::APInt::ugt(), llvm::Value::user_begin(), and llvm::APInt::zext().
Referenced by isPromotedResultSafe().
isPromotedResultSafe()
static bool isPromotedResultSafe (Value * V) static
Return whether we can safely mutate V's type to ExtTy without having to be concerned with zero extending or truncation.
Definition at line 407 of file TypePromotion.cpp.
References llvm::MCID::Add, Arg, assert(), llvm::MCID::Call, Cleanup(), llvm::SmallVectorImpl< T >::clear(), llvm::SetVector< T, Vector, Set >::count(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), DEBUG_TYPE, DisablePromotion, llvm::User::dropAllReferences(), llvm::Value::dump(), llvm::dyn_cast(), llvm::numbers::e, llvm::SetVector< T, Vector, Set >::empty(), llvm::Instruction::eraseFromParent(), F(), From, GenerateSignBits(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::IntegerType::getBitWidth(), getBitWidth(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::Instruction::getDebugLoc(), llvm::BasicBlock::getFirstInsertionPt(), llvm::APInt::getMaxValue(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::GlobalValue::getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::TargetTransformInfo::getRegisterBitWidth(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::TargetMachine::getSubtargetImpl(), llvm::Value::getType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::TargetLoweringBase::getValueType(), llvm::ConstantExpr::getZExt(), hasNoUnsignedWrap(), I, INITIALIZE_PASS_BEGIN, INITIALIZE_PASS_END(), llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isLegalToPromote(), llvm::Type::isPointerTy(), llvm::EVT::isSimple(), isSupportedType(), llvm::TargetLoweringBase::isTypeLegal(), llvm::Type::isVoidTy(), LLVM_DEBUG, llvm_unreachable, llvm::SPII::Load, llvm::BitmaskEnumDetail::Mask(), llvm::Instruction::moveAfter(), llvm::Instruction::moveBefore(), llvm::Value::mutateType(), llvm::User::operands(), PASS_NAME, llvm::SetVector< T, Vector, Set >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::report_fatal_error(), llvm::MipsISD::Ret, runOnFunction(), llvm::MCID::Select, llvm::User::setOperand(), llvm::SmallVectorBase::size(), llvm::SmallPtrSetImplBase::size(), llvm::SPII::Store, TII, llvm::SystemZISD::TM, llvm::TargetLoweringBase::TypePromoteInteger, Users, llvm::Value::uses(), and llvm::verifyFunction().
Variable Documentation
DisablePromotion
cl::opt<bool> DisablePromotion("disable-type-promotion", cl::Hidden, cl::init(false), cl::desc("Disable type promotion pass")) static
Referenced by isPromotedResultSafe().