LLVM: lib/DebugInfo/CodeView/TypeIndexDiscovery.cpp File Reference
TypeIndexDiscovery.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeIndexDiscovery.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/Endian.h"
Functions
static MethodKind getMethodKind (uint16_t Attrs)
static bool isIntroVirtual (uint16_t Attrs)
static PointerMode getPointerMode (uint32_t Attrs)
static bool isMemberPointer (uint32_t Attrs)
static uint32_t getEncodedIntegerLength (ArrayRef< uint8_t > Data)
static uint32_t getCStringLength (ArrayRef< uint8_t > Data)
static void handleMethodOverloadList (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleBaseClass (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleEnumerator (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleDataMember (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleOverloadedMethod (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleOneMethod (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleNestedType (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleStaticDataMember (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleVirtualBaseClass (ArrayRef< uint8_t > Data, uint32_t Offset, bool IsIndirect, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleVFPtr (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static uint32_t handleListContinuation (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > &Refs)
static void handleFieldList (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > &Refs)
static void handlePointer (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > &Refs)
static void discoverTypeIndices (ArrayRef< uint8_t > Content, TypeLeafKind Kind, SmallVectorImpl< TiReference > &Refs)
static bool discoverTypeIndices (ArrayRef< uint8_t > Content, SymbolKind Kind, SmallVectorImpl< TiReference > &Refs)
static void resolveTypeIndexReferences (ArrayRef< uint8_t > RecordData, ArrayRef< TiReference > Refs, SmallVectorImpl< TypeIndex > &Indices)
Function Documentation
discoverTypeIndices() [1/2]
static void discoverTypeIndices (ArrayRef< uint8_t > Content, TypeLeafKind Kind, SmallVectorImpl< TiReference > & Refs) static
Definition at line 273 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::data(), handleFieldList(), handleMethodOverloadList(), handlePointer(), llvm::codeview::IndexRef, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::support::endian::read16le(), llvm::support::endian::read32le(), and llvm::codeview::TypeRef.
Referenced by llvm::codeview::discoverTypeIndicesInSymbol().
discoverTypeIndices() [2/2]
static bool discoverTypeIndices (ArrayRef< uint8_t > Content, SymbolKind Kind, SmallVectorImpl< TiReference > & Refs) static
Definition at line 359 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::data(), llvm::codeview::IndexRef, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
getCStringLength()
static uint32_t getCStringLength (ArrayRef< uint8_t > Data) inline static
Definition at line 63 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::data().
Referenced by handleDataMember(), handleEnumerator(), handleNestedType(), handleOneMethod(), handleOverloadedMethod(), and handleStaticDataMember().
getEncodedIntegerLength()
static uint32_t getEncodedIntegerLength (ArrayRef< uint8_t > Data) inline static
Definition at line 39 of file TypeIndexDiscovery.cpp.
References assert(), llvm::ArrayRef< T >::data(), N, and llvm::support::endian::read16le().
Referenced by handleBaseClass(), handleDataMember(), handleEnumerator(), and handleVirtualBaseClass().
getMethodKind()
static MethodKind getMethodKind (uint16_t Attrs) inline static
Definition at line 16 of file TypeIndexDiscovery.cpp.
References llvm::codeview::MethodKindMask.
Referenced by llvm::codeview::MemberAttributes::isIntroducedVirtual(), llvm::codeview::OneMethodRecord::isIntroducingVirtual(), isIntroVirtual(), llvm::codeview::MemberAttributes::isStatic(), and llvm::codeview::MemberAttributes::isVirtual().
getPointerMode()
static PointerMode getPointerMode (uint32_t Attrs) inline static
Definition at line 28 of file TypeIndexDiscovery.cpp.
References llvm::codeview::PointerRecord::PointerModeMask, and llvm::codeview::PointerRecord::PointerModeShift.
Referenced by isMemberPointer().
handleBaseClass()
static uint32_t handleBaseClass (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 94 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getEncodedIntegerLength(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleDataMember()
static uint32_t handleDataMember (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 114 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getCStringLength(), getEncodedIntegerLength(), llvm::SmallVectorTemplateBase< T >::push_back(), Size, and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleEnumerator()
static uint32_t handleEnumerator (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 104 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getCStringLength(), getEncodedIntegerLength(), and Size.
Referenced by handleFieldList().
handleFieldList()
static void handleFieldList (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > & Refs) static
Definition at line 208 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), handleBaseClass(), handleDataMember(), handleEnumerator(), handleListContinuation(), handleNestedType(), handleOneMethod(), handleOverloadedMethod(), handleStaticDataMember(), handleVFPtr(), handleVirtualBaseClass(), and llvm::support::endian::read16le().
Referenced by discoverTypeIndices().
handleListContinuation()
static uint32_t handleListContinuation (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 199 of file TypeIndexDiscovery.cpp.
References llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleMethodOverloadList()
static void handleMethodOverloadList (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > & Refs) static
Definition at line 68 of file TypeIndexDiscovery.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), isIntroVirtual(), LLVM_UNLIKELY, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::support::endian::read16le(), and llvm::codeview::TypeRef.
Referenced by discoverTypeIndices().
handleNestedType()
static uint32_t handleNestedType (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 154 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getCStringLength(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleOneMethod()
static uint32_t handleOneMethod (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 136 of file TypeIndexDiscovery.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), getCStringLength(), isIntroVirtual(), LLVM_UNLIKELY, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::support::endian::read16le(), Size, and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleOverloadedMethod()
static uint32_t handleOverloadedMethod (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 126 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getCStringLength(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handlePointer()
static void handlePointer (ArrayRef< uint8_t > Content, SmallVectorImpl< TiReference > & Refs) static
Definition at line 264 of file TypeIndexDiscovery.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), isMemberPointer(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::support::endian::read32le(), and llvm::codeview::TypeRef.
Referenced by discoverTypeIndices().
handleStaticDataMember()
static uint32_t handleStaticDataMember (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 164 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getCStringLength(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleVFPtr()
static uint32_t handleVFPtr (ArrayRef< uint8_t > Data, uint32_t Offset, SmallVectorImpl< TiReference > & Refs) static
Definition at line 190 of file TypeIndexDiscovery.cpp.
References llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::codeview::TypeRef.
Referenced by handleFieldList().
handleVirtualBaseClass()
static uint32_t handleVirtualBaseClass (ArrayRef< uint8_t > Data, uint32_t Offset, bool IsIndirect, SmallVectorImpl< TiReference > & Refs) static
Definition at line 174 of file TypeIndexDiscovery.cpp.
References llvm::ArrayRef< T >::drop_front(), getEncodedIntegerLength(), llvm::SmallVectorTemplateBase< T >::push_back(), Size, and llvm::codeview::TypeRef.
Referenced by handleFieldList().
isIntroVirtual()
static bool isIntroVirtual (uint16_t Attrs) inline static
Definition at line 22 of file TypeIndexDiscovery.cpp.
References getMethodKind(), llvm::codeview::IntroducingVirtual, and llvm::codeview::PureIntroducingVirtual.
Referenced by handleMethodOverloadList(), and handleOneMethod().
isMemberPointer()
static bool isMemberPointer (uint32_t Attrs) inline static
Definition at line 33 of file TypeIndexDiscovery.cpp.
References getPointerMode(), Mode, llvm::codeview::PointerToDataMember, and llvm::codeview::PointerToMemberFunction.
Referenced by handlePointer().
resolveTypeIndexReferences()
static void resolveTypeIndexReferences (ArrayRef< uint8_t > RecordData, ArrayRef< TiReference > Refs, SmallVectorImpl< TypeIndex > & Indices) static
Definition at line 461 of file TypeIndexDiscovery.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::FixedStreamArray< T >::begin(), llvm::cantFail(), llvm::SmallVectorImpl< T >::clear(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::FixedStreamArray< T >::end(), llvm::support::little, llvm::BinaryStreamReader::readArray(), llvm::Ref, and llvm::BinaryStreamReader::setOffset().
Referenced by llvm::codeview::discoverTypeIndices(), and llvm::codeview::discoverTypeIndicesInSymbol().