LLVM: lib/DebugInfo/CodeView/TypeRecordMapping.cpp File Reference
TypeRecordMapping.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeRecordMapping.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/DebugInfo/CodeView/EnumTables.h"
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define error(X)
#define CV_TYPE(enum, val) {#enum, enum},
#define TYPE_RECORD(ename, value, name)
Functions
static Error mapNameAndUniqueName (CodeViewRecordIO &IO, StringRef &Name, StringRef &UniqueName, bool HasUniqueName)
Macro Definition Documentation
CV_TYPE
#define CV_TYPE (enum, val) {#enum, enum},
error
#define error (X)
Value:
if (auto EC = X)                                                             \
    return EC;
Definition at line 18 of file TypeRecordMapping.cpp.
Referenced by mapNameAndUniqueName(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), and llvm::codeview::TypeRecordMapping::visitTypeEnd().
TYPE_RECORD
#define TYPE_RECORD (ename, value, name)
Value:
case ename:                                                                  \
    return #name;
Function Documentation
mapNameAndUniqueName()
static Error mapNameAndUniqueName (CodeViewRecordIO & IO, StringRef & Name, StringRef & UniqueName, bool HasUniqueName) static
Definition at line 147 of file TypeRecordMapping.cpp.
References llvm::StringRef::drop_back(), error, llvm::codeview::CodeViewRecordIO::isWriting(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), N, Name, llvm::StringRef::size(), llvm::Error::success(), and llvm::StringRef::take_front().
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().