LLVM: include/llvm/Demangle/Utility.h File Reference
Utility.h File Reference
#include "StringView.h"
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iterator>
#include <limits>
Classes
class OutputStream
class SwapAndRestore< T >
Functions
bool initializeOutputStream (char *Buf, size_t *N, OutputStream &S, size_t InitSize)
Function Documentation
initializeOutputStream()
bool initializeOutputStream (char * Buf, size_t * N, OutputStream & S, size_t InitSize) inline
Definition at line 174 of file Utility.h.
References DEMANGLE_NAMESPACE_END, N, and OutputStream::reset().
Referenced by decodeMultiByteChar(), llvm::ms_demangle::Demangler::dumpBackReferences(), llvm::ItaniumPartialDemangler::getFunctionDeclContextName(), llvm::ItaniumPartialDemangler::getFunctionParameters(), llvm::ItaniumPartialDemangler::getFunctionReturnType(), llvm::itaniumDemangle(), llvm::microsoftDemangle(), llvm::ms_demangle::Demangler::parseTagUniqueName(), printNode(), and llvm::ms_demangle::Node::toString().