LLVM: lib/Transforms/Utils/ValueMapper.cpp File Reference
ValueMapper.cpp File Reference
#include "llvm/Transforms/Utils/ValueMapper.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalIndirectSymbol.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <limits>
#include <memory>
#include <utility>
Functions
static Metadata * cloneOrBuildODR (const MDNode &N)
static ConstantAsMetadata * wrapConstantAsMetadata (const ConstantAsMetadata &CMD, Value *MappedV)
static Mapper * getAsMapper (void *pImpl)
Function Documentation
cloneOrBuildODR()
static Metadata* cloneOrBuildODR (const MDNode & N) static
Definition at line 539 of file ValueMapper.cpp.
References assert(), llvm::MDNode::clone(), llvm::dyn_cast(), llvm::MDNode::isDistinct(), N, llvm::MDNode::replaceWithDistinct(), and llvm::RF_MoveDistinctMDs.
getAsMapper()
static Mapper* getAsMapper (void * pImpl) static
Definition at line 1056 of file ValueMapper.cpp.
References assert().
Referenced by llvm::ValueMapper::registerAlternateMappingContext(), llvm::ValueMapper::scheduleMapAppendingVariable(), llvm::ValueMapper::scheduleMapGlobalIndirectSymbol(), llvm::ValueMapper::scheduleMapGlobalInitializer(), llvm::ValueMapper::scheduleRemapFunction(), and llvm::ValueMapper::~ValueMapper().
wrapConstantAsMetadata()
static ConstantAsMetadata* wrapConstantAsMetadata (const ConstantAsMetadata & CMD, Value * MappedV) static
Definition at line 559 of file ValueMapper.cpp.
References llvm::AttributeList::addAttribute(), llvm::GlobalObject::addMetadata(), llvm::SmallVectorImpl< T >::append(), llvm::Function::args(), assert(), llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::SmallVectorTemplateCommon< T >::back(), llvm::ArrayRef< T >::begin(), llvm::GlobalObject::clearMetadata(), llvm::MDNode::clone(), D, llvm::Data, llvm::numbers::e, E, llvm::SmallVectorBase::empty(), llvm::ArrayRef< T >::end(), F(), llvm::ArrayRef< T >::front(), G, GEP, llvm::FunctionType::get(), llvm::StructType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::Constant::getAggregateElement(), llvm::GlobalObject::getAllMetadata(), llvm::Instruction::getAllMetadata(), llvm::AttributeList::getAttribute(), llvm::ValueAsMetadata::getConstant(), llvm::Value::getContext(), llvm::PointerType::getElementType(), llvm::Type::getInt8Ty(), getMappedOp(), llvm::Constant::getNullValue(), llvm::AttributeList::getNumAttrSets(), llvm::MDNode::getNumOperands(), llvm::FunctionType::getNumParams(), llvm::MDNode::getOperand(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::ConstantAsMetadata::getValue(), llvm::Attribute::getValueAsType(), llvm::Attribute::getWithByValType(), llvm::GlobalIndirectSymbol::GlobalIndirectSymbol(), llvm::AttributeList::hasAttribute(), I, Info, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair< ValueT > >, ValueInfoT >::insert(), llvm::MDNode::isResolved(), llvm::MDNode::isUniqued(), llvm::FunctionType::isVarArg(), llvm::makeArrayRef(), MI, llvm::Value::mutateType(), N, llvm::None, llvm::none_of(), llvm::MDNode::op_begin(), llvm::User::operands(), llvm::MDNode::operands(), llvm::FunctionType::params(), llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::RemapFunction(), llvm::remapInstruction(), llvm::ValueMapTypeRemapper::remapType(), llvm::AttributeList::removeAttribute(), llvm::MDNode::replaceOperandWith(), llvm::MDNode::replaceWithUniqued(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), llvm::MDNode::resolveCycles(), llvm::GlobalVariable::setInitializer(), llvm::Instruction::setMetadata(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), and llvm::ARM_MB::ST.