LLVM: lib/Target/VE/VERegisterInfo.cpp File Reference
VERegisterInfo.cpp File Reference
#include "VERegisterInfo.h"
#include "VE.h"
#include "VESubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "VEGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static void replaceFI (MachineFunction &MF, MachineBasicBlock::iterator II, MachineInstr &MI, const DebugLoc &dl, unsigned FIOperandNum, int Offset, unsigned FramePtr)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 29 of file VERegisterInfo.cpp.
Function Documentation
replaceFI()
static void replaceFI (MachineFunction & MF, MachineBasicBlock::iterator II, MachineInstr & MI, const DebugLoc & dl, unsigned FIOperandNum, int Offset, unsigned FramePtr) static
Definition at line 78 of file VERegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), and llvm::MachineInstr::getOperand().
Referenced by llvm::VERegisterInfo::eliminateFrameIndex().