LLVM: lib/IR/Verifier.cpp File Reference
Verifier.cpp File Reference
#include "llvm/IR/Verifier.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/ilist.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Use.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include "llvm/IR/Metadata.def"
#include "llvm/IR/ConstrainedOps.def"
Classes
struct llvm::VerifierSupport
Namespaces
llvm
This class represents lattice values for constants.
Macros
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS) void visit##CLASS(const CLASS &N);
#define Assert(C, ...) do { if (!(C)) { CheckFailed(__VA_ARGS__); return; } } while (false)
We know that cond should be true, if not print an error message.
#define AssertDI(C, ...) do { if (!(C)) { DebugInfoCheckFailed(__VA_ARGS__); return; } } while (false)
We know that a debug info condition should be true, if not print an error message.
#define HANDLE_SPECIALIZED_MDNODE_LEAF(CLASS)
#define INSTRUCTION(NAME, NARGS, ROUND_MODE, INTRINSIC, DAGN) case Intrinsic::INTRINSIC:
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN)
#define AssertTBAA(C, ...)
Functions
static void forEachUser (const Value *User, SmallPtrSet< const Value *, 32 > &Visited, llvm::function_ref< bool(const Value *)> Callback)
static bool isType (const Metadata *MD)
static bool isScope (const Metadata *MD)
static bool isDINode (const Metadata *MD)
static bool hasConflictingReferenceFlags (unsigned Flags)
Detect mutually exclusive flags.
static bool isFuncOnlyAttr (Attribute::AttrKind Kind)
Return true if this attribute kind only applies to functions.
static bool isFuncOrArgAttr (Attribute::AttrKind Kind)
Return true if this is a function attribute that can also appear on arguments.
static Instruction * getSuccPad (Instruction *Terminator)
static bool isTypeCongruent (Type *L, Type *R)
Two types are "congruent" if they are identical, or if they are both pointer types with different pointee types and the same address space.
static AttrBuilder getParameterABIAttributes (int I, AttributeList Attrs)
static bool isContiguous (const ConstantRange &A, const ConstantRange &B)
static Value * getParentPad (Value *EHPad)
static DISubprogram * getSubprogram (Metadata *LocalScope)
Carefully grab the subprogram from a local scope.
static bool IsRootTBAANode (const MDNode *MD)
static bool IsScalarTBAANodeImpl (const MDNode *MD, SmallPtrSetImpl< const MDNode *> &Visited)
static bool isNewFormatTBAATypeNode (llvm::MDNode *Type)
Macro Definition Documentation
Assert
#define Assert (C, ...) do { if (!(C)) { CheckFailed(__VA_ARGS__); return; } } while (false)
We know that cond should be true, if not print an error message.
Definition at line 539 of file Verifier.cpp.
Referenced by forEachUser(), getParameterABIAttributes(), getParentPad(), getSubprogram(), getSuccPad(), isContiguous(), and isFuncOrArgAttr().
AssertDI
#define AssertDI (C, ...) do { if (!(C)) { DebugInfoCheckFailed(__VA_ARGS__); return; } } while (false)
We know that a debug info condition should be true, if not print an error message.
Definition at line 544 of file Verifier.cpp.
Referenced by forEachUser(), getParentPad(), getSubprogram(), getSuccPad(), hasConflictingReferenceFlags(), and isDINode().
AssertTBAA
#define AssertTBAA (C, ...)
Value:
do {                                                                         \
    if (!(C)) {                                                                \
      CheckFailed(__VA_ARGS__);                                                \
      return false;                                                            \
    }                                                                          \
  } while (false)
Definition at line 5179 of file Verifier.cpp.
Referenced by llvm::TBAAVerifier::visitTBAAMetadata().
HANDLE_SPECIALIZED_MDNODE_LEAF [1/2]
#define HANDLE_SPECIALIZED_MDNODE_LEAF (CLASS) void visit##CLASS(const CLASS &N);
Definition at line 426 of file Verifier.cpp.
HANDLE_SPECIALIZED_MDNODE_LEAF [2/2]
#define HANDLE_SPECIALIZED_MDNODE_LEAF (CLASS)
Value:
case Metadata::CLASS##Kind:                                                  \
    visit##CLASS(cast<CLASS>(MD));                                             \
    break;
Definition at line 426 of file Verifier.cpp.
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARGS, ROUND_MODE, INTRINSIC, DAGN) case Intrinsic::INTRINSIC:
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN)
Value:
case Intrinsic::INTRINSIC:                                                   \
    NumOperands = NARG;                                                        \
    HasRoundingMD = ROUND_MODE;                                                \
    break;
Function Documentation
forEachUser()
static void forEachUser (const Value * User, SmallPtrSet< const Value *, 32 > & Visited, llvm::function_ref< bool(const Value *)> Callback) static
Definition at line 556 of file Verifier.cpp.
References A, assert(), Assert, AssertDI, C, llvm::VerifierSupport::CheckFailed(), llvm::VerifierSupport::Context, llvm::VerifierSupport::DL, llvm::dyn_cast(), F(), llvm::FunctionType::get(), llvm::GlobalAlias::getAliasee(), llvm::GlobalValue::getAlignment(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getLinkage(), llvm::GlobalObject::getMetadata(), llvm::MetadataAsValue::getMetadata(), llvm::Metadata::getMetadataID(), llvm::Value::getName(), llvm::NamedMDNode::getName(), llvm::StructType::getNumElements(), llvm::GlobalValue::getParent(), llvm::DataLayout::getProgramAddressSpace(), llvm::Value::getType(), llvm::GlobalValue::getType(), llvm::CompositeType::getTypeAtIndex(), llvm::ValueAsMetadata::getValue(), llvm::GlobalValue::getValueType(), llvm::Type::getVoidTy(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalObject::hasComdat(), llvm::GlobalValue::hasComdat(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::GlobalValue::hasValidDeclarationLinkage(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Type::isArrayTy(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isDeclarationForLinker(), llvm::GlobalValue::isDSOLocal(), llvm::Type::isIntegerTy(), llvm::Type::isMetadataTy(), llvm::Constant::isNullValue(), llvm::MDNode::isResolved(), llvm::MDNode::isTemporary(), llvm::GlobalAlias::isValidLinkage(), llvm_unreachable, llvm::VerifierSupport::M, llvm::Value::materialized_users(), llvm::Value::MaximumAlignment, N, llvm::User::operands(), llvm::MDNode::operands(), llvm::NamedMDNode::operands(), and llvm::StringRef::startswith().
getParameterABIAttributes()
static AttrBuilder getParameterABIAttributes (int I, AttributeList Attrs) static
Definition at line 3064 of file Verifier.cpp.
References llvm::MCID::Add, llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), llvm::all_of(), Assert, B, E, R600_InstFlag::FC, GEP, llvm::AttributeList::getAttributes(), llvm::CallBase::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCallingConv(), llvm::CallBase::getFunctionType(), llvm::GetElementPtrInst::getIndexedType(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::FunctionType::getNumParams(), llvm::UnaryOperator::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::AttributeList::getParamAlignment(), llvm::FunctionType::getParamType(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GetElementPtrInst::getPointerOperandType(), llvm::GetElementPtrInst::getResultElementType(), llvm::FunctionType::getReturnType(), llvm::ReturnInst::getReturnValue(), llvm::Type::getScalarType(), llvm::GetElementPtrInst::getSourceElementType(), llvm::Value::getType(), llvm::InvokeInst::getUnwindDest(), llvm::Type::getVectorNumElements(), llvm::AttributeList::hasParamAttribute(), I, llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_end(), llvm::ARM_PROC::IE, llvm::BasicBlock::isEHPad(), llvm::Type::isFPOrFPVectorTy(), llvm::CmpInst::isFPPredicate(), llvm::CallBase::isInlineAsm(), llvm::Type::isIntOrIntVectorTy(), llvm::CmpInst::isIntPredicate(), llvm::Function::isIntrinsic(), llvm::CallInst::isMustTailCall(), llvm::Type::isPtrOrPtrVectorTy(), llvm::Type::isSized(), isTypeCongruent(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), llvm::FunctionType::isVarArg(), llvm::Type::isVectorTy(), llvm_unreachable, and llvm::MipsISD::Ret.
getParentPad()
static Value* getParentPad (Value * EHPad) static
Definition at line 3609 of file Verifier.cpp.
References Arg, llvm::CallBase::arg_size(), llvm::CallBase::args(), assert(), Assert, AssertDI, llvm::MCID::Call, llvm::VerifierSupport::CheckFailed(), llvm::CallBase::countOperandBundlesOfType(), llvm::VerifierSupport::DL, llvm::dyn_cast(), llvm::numbers::e, llvm::ArrayRef< T >::empty(), F(), llvm::Function::front(), llvm::ConstantTokenNone::get(), llvm::AllocaInst::getAllocatedType(), llvm::CallBase::getArgOperand(), llvm::DebugLoc::getAsMDNode(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCalledOperandUse(), llvm::CallBase::getCaller(), llvm::LandingPadInst::getClause(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::GCRelocateInst::getDerivedPtr(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::Instruction::getFunction(), llvm::Function::getFunctionType(), llvm::GlobalVariable::getInitializer(), llvm::Function::getIntrinsicID(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::BasicBlock::getLandingPadInst(), llvm::Instruction::getMetadata(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::DataLayout::getNonIntegralAddressSpaces(), llvm::InvokeInst::getNormalDest(), llvm::CallBase::getNumArgOperands(), llvm::LandingPadInst::getNumClauses(), llvm::CatchSwitchInst::getNumHandlers(), llvm::User::getNumOperands(), llvm::MDNode::getNumOperands(), llvm::Instruction::getNumSuccessors(), llvm::IndirectBrInst::getNumSuccessors(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::CallBase::getOperandBundle(), llvm::User::getOperandUse(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::FuncletPadInst::getParentPad(), llvm::CatchSwitchInst::getParentPad(), llvm::Function::getReturnType(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::APFloat::getSemantics(), llvm::MDString::getString(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::InvokeInst::getUnwindDest(), llvm::CatchSwitchInst::getUnwindDest(), llvm::CleanupReturnInst::getUnwindDest(), llvm::ConstantInt::getValue(), llvm::ResumeInst::getValue(), llvm::CatchSwitchInst::handlers(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::Function::hasGC(), llvm::Value::hasName(), llvm::Function::hasPersonalityFn(), I, llvm::APFloatBase::IEEEsingle(), llvm::AMDGPUISD::IF, llvm::SmallSet< T, N, C >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isCleanup(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), llvm::Instruction::isEHPad(), llvm::LandingPadInst::isFilter(), llvm::APFloat::isFiniteNonZero(), llvm::Type::isFirstClassType(), llvm::Type::isFPOrFPVectorTy(), llvm::CallBase::isInlineAsm(), llvm::Type::isIntOrIntVectorTy(), llvm::Function::isIntrinsic(), llvm::Type::isMetadataTy(), llvm::APFloat::isNegative(), llvm::Type::isPointerTy(), llvm::APInt::isPowerOf2(), llvm::isPowerOf2_32(), llvm::isPowerOf2_64(), llvm::Type::isPtrOrPtrVectorTy(), llvm::isStatepoint(), llvm::AllocaInst::isStaticAlloca(), llvm::FunctionType::isVarArg(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::VerifierSupport::M, llvm::BitmaskEnumDetail::Mask(), llvm::Intrinsic::matchIntrinsicSignature(), llvm::Intrinsic::MatchIntrinsicTypes_NoMatchArg, llvm::Intrinsic::MatchIntrinsicTypes_NoMatchRet, llvm::Intrinsic::matchIntrinsicVarArg(), llvm::max(), llvm::Value::MaximumAlignment, MI, llvm::LLVMContext::OB_deopt, llvm::LLVMContext::OB_funclet, llvm::pred_empty(), llvm::predecessors(), prefetch, llvm::Value::stripPointerCasts(), llvm::Value::users(), and llvm::Value::uses().
getSubprogram()
static DISubprogram* getSubprogram (Metadata * LocalScope) static
Carefully grab the subprogram from a local scope.
This carefully grabs the subprogram from a local scope, avoiding the built-in assertions that would typically fire.
Definition at line 4747 of file Verifier.cpp.
References assert(), Assert, AssertDI, llvm::SmallPtrSetImpl< PtrType >::count(), E, F(), llvm::DILocalVariable::getArg(), llvm::CallBase::getArgOperand(), llvm::DebugLoc::getAsMDNode(), llvm::Function::getCallingConv(), llvm::Module::getContext(), llvm::Instruction::getDebugLoc(), llvm::ConstrainedFPIntrinsic::getExceptionBehavior(), llvm::IntrinsicInst::getIntrinsicID(), llvm::DbgLabelInst::getLabel(), llvm::Module::getNamedMetadata(), llvm::CallBase::getNumArgOperands(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::PPC::getPredicate(), llvm::DbgVariableIntrinsic::getRawExpression(), llvm::DbgLabelInst::getRawLabel(), llvm::DILocation::getRawScope(), llvm::DIVariable::getRawScope(), llvm::DILabel::getRawScope(), llvm::DIVariable::getRawType(), llvm::DbgVariableIntrinsic::getRawVariable(), llvm::ConstrainedFPIntrinsic::getRoundingMode(), llvm::Type::getScalarSizeInBits(), llvm::DILocalVariable::getScope(), llvm::DILabel::getScope(), llvm::DIVariable::getSizeInBits(), llvm::DIScope::getSource(), llvm::DILocalScope::getSubprogram(), llvm::Value::getType(), llvm::DbgVariableIntrinsic::getVariable(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::DILocalVariable::isArtificial(), llvm::DIExpression::isEntryValue(), llvm::Type::isFPOrFPVectorTy(), llvm::CmpInst::isFPPredicate(), llvm::Type::isIntOrIntVectorTy(), llvm::LLVMContext::isODRUniquingDebugTypes(), isType(), llvm::DIExpression::isValid(), llvm::Type::isVectorTy(), llvm_unreachable, llvm::makeArrayRef(), llvm::DIExpression::FragmentInfo::OffsetInBits, and llvm::DIExpression::FragmentInfo::SizeInBits.
getSuccPad()
static Instruction* getSuccPad (Instruction * Terminator) static
Definition at line 2109 of file Verifier.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, Arg, llvm::Function::arg_size(), assert(), Assert, AssertDI, llvm::CallingConv::C, llvm::SmallPtrSetImplBase::clear(), llvm::CallingConv::Cold, llvm::VerifierSupport::Context, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dyn_cast(), F(), llvm::CallingConv::Fast, llvm::AttributeList::getAttributes(), llvm::Function::getContext(), llvm::BasicBlock::getFirstNonPHI(), llvm::Function::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::BasicBlock::hasAddressTaken(), llvm::GlobalValue::hasCommonLinkage(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::CallingConv::Intel_OCL_BI, LLVM_FALLTHROUGH, llvm::BlockAddress::lookup(), llvm::pred_empty(), llvm::CallingConv::PTX_Device, llvm::CallingConv::PTX_Kernel, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::CallingConv::SPIR_KERNEL, and llvm::MCID::Terminator.
hasConflictingReferenceFlags()
static bool hasConflictingReferenceFlags (unsigned Flags) static
Detect mutually exclusive flags.
Definition at line 950 of file Verifier.cpp.
References AssertDI, llvm::DIFile::CSK_MD5, llvm::DIFile::CSK_SHA1, D, llvm::dyn_cast(), llvm::StringRef::empty(), F(), llvm::DICompositeType::getElements(), llvm::DICompileUnit::getEmissionKind(), llvm::DICompileUnit::getEnumTypes(), llvm::DIScope::getFile(), llvm::DIScope::getFilename(), llvm::DIType::getFlags(), llvm::DICompileUnit::getGlobalVariables(), llvm::DICompileUnit::getImportedEntities(), llvm::DICompileUnit::getMacros(), llvm::DICompositeType::getRawBaseType(), llvm::DICompositeType::getRawDiscriminator(), llvm::DICompositeType::getRawElements(), llvm::DICompileUnit::getRawEnumTypes(), llvm::DIScope::getRawFile(), llvm::DICompileUnit::getRawGlobalVariables(), llvm::DICompileUnit::getRawImportedEntities(), llvm::DICompileUnit::getRawMacros(), llvm::DICompileUnit::getRawRetainedTypes(), llvm::DIType::getRawScope(), llvm::DICompositeType::getRawTemplateParams(), llvm::DISubroutineType::getRawTypeArray(), llvm::DICompositeType::getRawVTableHolder(), llvm::DICompileUnit::getRetainedTypes(), llvm::DINode::getTag(), llvm::DISubroutineType::getTypeArray(), llvm::MDNode::isDistinct(), llvm::isHexDigit(), isScope(), isType(), llvm::DIType::isVector(), llvm::DICompileUnit::LastEmissionKind, N, llvm::StringRef::npos, llvm::MDNode::operands(), Size, and llvm::T.
isContiguous()
static bool isContiguous (const ConstantRange & A, const ConstantRange & B) static
Definition at line 3347 of file Verifier.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), assert(), Assert, llvm::MCID::Call, llvm::VerifierSupport::DL, llvm::dyn_cast(), E, llvm::AtomicRMWInst::FIRST_BINOP, llvm::PointerType::getAddressSpace(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::DataLayout::getAllocaAddrSpace(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::PointerType::getElementType(), llvm::AtomicCmpXchgInst::getFailureOrdering(), llvm::ExtractValueInst::getIndexedType(), llvm::ExtractValueInst::getIndices(), llvm::InsertValueInst::getIndices(), llvm::ConstantRange::getLower(), llvm::Instruction::getMetadata(), llvm::MDNode::getNumOperands(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getOperationName(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::FenceInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::AtomicCmpXchgInst::getSuccessOrdering(), llvm::LoadInst::getSyncScopeID(), llvm::StoreInst::getSyncScopeID(), llvm::AllocaInst::getType(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::ConstantRange::getUpper(), llvm::ConstantInt::getValue(), High, I, llvm::ConstantRange::intersectWith(), llvm::Instruction::isAtomic(), llvm::ConstantRange::isEmptySet(), llvm::Type::isFloatingPointTy(), llvm::AtomicRMWInst::isFPOperation(), llvm::ConstantRange::isFullSet(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrPtrTy(), llvm::Type::isSized(), llvm::isStrongerThan(), llvm::AllocaInst::isSwiftError(), llvm::AtomicRMWInst::LAST_BINOP, llvm::Value::MaximumAlignment, llvm::NotAtomic, llvm::CallBase::paramHasAttr(), llvm::Release, llvm::SequentiallyConsistent, llvm::APInt::sgt(), SI, Size, llvm::SyncScope::System, llvm::Unordered, llvm::Value::users(), and llvm::AtomicRMWInst::Xchg.
isDINode()
static bool isDINode (const Metadata * MD) static
Definition at line 872 of file Verifier.cpp.
References AssertDI, F(), llvm::ConstantInt::get(), llvm::DISubrange::getCount(), llvm::DIScope::getRawFile(), llvm::DILocation::getRawInlinedAt(), llvm::DIType::getRawScope(), llvm::DILocation::getRawScope(), llvm::ConstantInt::getSExtValue(), llvm::DINode::getTag(), llvm::GenericDINode::getTag(), llvm::DIType::isBigEndian(), llvm::DIType::isLittleEndian(), isScope(), isType(), and N.
isFuncOnlyAttr()
static bool isFuncOnlyAttr (Attribute::AttrKind Kind) static
Return true if this attribute kind only applies to functions.
Definition at line 1503 of file Verifier.cpp.
References llvm::CallingConv::Cold, llvm::MCID::Convergent, and llvm::ISD::JumpTable.
Referenced by isFuncOrArgAttr().
isFuncOrArgAttr()
static bool isFuncOrArgAttr (Attribute::AttrKind Kind) static
Return true if this is a function attribute that can also appear on arguments.
Definition at line 1557 of file Verifier.cpp.
References A, llvm::CallBase::arg_size(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Assert, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::MCID::Call, llvm::Type::canLosslesslyBitCastTo(), llvm::CastInst::castIsValid(), llvm::VerifierSupport::CheckFailed(), llvm::VerifierSupport::Context, llvm::VerifierSupport::DL, llvm::CallBase::doesNotAccessMemory(), llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorBase::empty(), FP, llvm::AttributeList::FunctionIndex, llvm::AttributeSet::get(), llvm::AttributeList::getAllocSizeArgs(), llvm::CallBase::getArgOperand(), llvm::StringRef::getAsInteger(), llvm::AttributeSet::getAsString(), llvm::AttributeList::getAttribute(), llvm::CallBase::getAttributes(), llvm::AttributeSet::getByValType(), llvm::CallBase::getCalledFunction(), llvm::AttributeList::getFnAttributes(), llvm::Function::getIntrinsicID(), llvm::AttributeSet::getNumAttributes(), llvm::AttributeList::getNumAttrSets(), llvm::MDNode::getNumOperands(), llvm::FunctionType::getNumParams(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::AttributeList::getParamAttributes(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), llvm::AttributeList::getRetAttributes(), llvm::FunctionType::getReturnType(), llvm::MDString::getString(), llvm::Value::getType(), llvm::Attribute::getValueAsString(), llvm::AttributeSet::hasAttribute(), llvm::AttributeSet::hasAttributes(), llvm::AttributeList::hasAttributes(), llvm::AttributeList::hasFnAttribute(), llvm::GlobalValue::hasGlobalUnnamedAddr(), llvm::AttributeList::isEmpty(), isFuncOnlyAttr(), llvm::isInt< 32 >(), llvm::Type::isIntegerTy(), llvm::DataLayout::isNonIntegralPointerType(), llvm::ISD::JumpTable, llvm::VerifierSupport::M, llvm::MaskAll, N, Name, llvm::CallBase::onlyAccessesArgMemory(), llvm::CallBase::onlyReadsMemory(), llvm::User::operands(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::AttributeFuncs::typeIncompatible(), and llvm::Value::users().
isNewFormatTBAATypeNode()
static bool isNewFormatTBAATypeNode (llvm::MDNode * Type) static
Definition at line 5401 of file Verifier.cpp.
References llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by llvm::TBAAVerifier::visitTBAAMetadata().
IsRootTBAANode()
static bool IsRootTBAANode (const MDNode * MD) static
Definition at line 5320 of file Verifier.cpp.
References llvm::MDNode::getNumOperands().
Referenced by IsScalarTBAANodeImpl(), and llvm::TBAAVerifier::visitTBAAMetadata().
IsScalarTBAANodeImpl()
static bool IsScalarTBAANodeImpl (const MDNode * MD, SmallPtrSetImpl< const MDNode *> & Visited) static
Definition at line 5324 of file Verifier.cpp.
References assert(), llvm::VerifierSupport::CheckFailed(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), and IsRootTBAANode().
isScope()
static bool isScope (const Metadata * MD) static
Definition at line 871 of file Verifier.cpp.
Referenced by hasConflictingReferenceFlags(), and isDINode().
isType()
static bool isType (const Metadata * MD) static
Definition at line 870 of file Verifier.cpp.
Referenced by getSubprogram(), hasConflictingReferenceFlags(), and isDINode().
isTypeCongruent()
static bool isTypeCongruent (Type * L, Type * R) static
Two types are "congruent" if they are identical, or if they are both pointer types with different pointee types and the same address space.
Definition at line 3054 of file Verifier.cpp.
References llvm::dyn_cast(), llvm::PointerType::getAddressSpace(), llvm::AArch64CC::PL, and llvm::RISCVFenceField::R.
Referenced by getParameterABIAttributes().