LLVM: lib/Support/VirtualFileSystem.cpp File Reference
VirtualFileSystem.cpp File Reference
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/IntrusiveRefCntPtr.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLParser.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <atomic>
#include <cassert>
#include <cstdint>
#include <iterator>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <system_error>
#include <utility>
#include <vector>
Classes
class llvm::vfs::detail::InMemoryNode
The in memory file system is a tree of Nodes.
class llvm::vfs::detail::InMemoryFile
class llvm::vfs::detail::InMemoryDirectory
class llvm::vfs::VFSFromYamlDirIterImpl
class llvm::vfs::RedirectingFileSystemParser
A helper class to hold the common YAML parsing state.
Namespaces
llvm
This class represents lattice values for constants.
llvm::vfs
llvm::vfs::detail
Enumerations
enum llvm::vfs::detail::InMemoryNodeKind { llvm::vfs::detail::IME_File, llvm::vfs::detail::IME_Directory, llvm::vfs::detail::IME_HardLink }
Functions
static bool isTraversalComponent (StringRef Component)
static bool pathHasTraversal (StringRef Path)
static ErrorOr< const detail::InMemoryNode * > llvm::vfs::lookupInMemoryNode (const InMemoryFileSystem &FS, detail::InMemoryDirectory *Dir, const Twine &P)
static Status getRedirectedFileStatus (const Twine &Path, bool UseExternalNames, Status ExternalStatus)
static void getVFSEntries (RedirectingFileSystem::Entry *SrcE, SmallVectorImpl< StringRef > &Path, SmallVectorImpl< YAMLVFSEntry > &Entries)
Function Documentation
getRedirectedFileStatus()
static Status getRedirectedFileStatus (const Twine & Path, bool UseExternalNames, Status ExternalStatus) static
Definition at line 1723 of file VirtualFileSystem.cpp.
References assert(), llvm::vfs::Status::copyWithNewName(), E, F(), and llvm::vfs::Status::IsVFSMapped.
Referenced by llvm::vfs::RedirectingFileSystem::openFileForRead().
getVFSEntries()
static void getVFSEntries (RedirectingFileSystem::Entry * SrcE, SmallVectorImpl< StringRef > & Path, SmallVectorImpl< YAMLVFSEntry > & Entries) static
Definition at line 1847 of file VirtualFileSystem.cpp.
References llvm::sys::path::append(), assert(), llvm::SmallString< InternalLen >::c_str(), llvm::vfs::collectVFSFromYAML(), llvm::vfs::RedirectingFileSystem::create(), llvm::dyn_cast(), llvm::vfs::RedirectingFileSystem::EK_Directory, llvm::vfs::RedirectingFileSystem::EK_File, llvm::vfs::RedirectingFileSystem::Entry::getKind(), llvm::make_range(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateBase< T >::push_back().
isTraversalComponent()
static bool isTraversalComponent (StringRef Component) static
Definition at line 151 of file VirtualFileSystem.cpp.
References llvm::StringRef::equals().
Referenced by pathHasTraversal().
pathHasTraversal()
static bool pathHasTraversal (StringRef Path) static
Definition at line 155 of file VirtualFileSystem.cpp.
References llvm::HexagonII::Absolute, assert(), llvm::sys::path::begin(), llvm::sys::fs::closeFile(), llvm::vfs::Status::copyWithNewName(), llvm::sys::fs::current_path(), llvm::StringRef::empty(), llvm::sys::path::end(), llvm::errorToErrorCode(), getName(), llvm::vfs::Status::getName(), llvm::MemoryBuffer::getOpenFile(), isTraversalComponent(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::IsVolatile, llvm::sys::fs::kInvalidFile, llvm::sys::fs::make_absolute(), llvm::make_range(), llvm::sys::fs::OF_None, llvm::sys::fs::openFileForRead(), llvm::sys::fs::openNativeFileForRead(), llvm::sys::fs::real_path(), llvm::sys::fs::set_current_path(), llvm::sys::fs::status(), llvm::sys::fs::status_error, llvm::StringRef::str(), llvm::SmallString< InternalLen >::str(), llvm::Twine::str(), llvm::Expected< T >::takeError(), and llvm::Twine::toVector().
Referenced by llvm::vfs::YAMLVFSWriter::addFileMapping().