LLVM: lib/Transforms/Vectorize/VPlanSLP.cpp File Reference
VPlanSLP.cpp File Reference
#include "VPlan.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <cassert>
#include <iterator>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "vplan-slp"
Functions
static SmallVector< VPValue *, 4 > getOperands (ArrayRef< VPValue *> Values, unsigned OperandIndex)
static bool areCommutative (ArrayRef< VPValue *> Values)
static SmallVector< SmallVector< VPValue *, 4 >, 4 > getOperands (ArrayRef< VPValue *> Values)
static Optional< unsigned > getOpcode (ArrayRef< VPValue *> Values)
Returns the opcode of Values or ~0 if they do not all agree.
static bool areConsecutiveOrMatch (VPInstruction *A, VPInstruction *B, VPInterleavedAccessInfo &IAI)
Returns true if A and B access sequential memory if they are loads or stores or if they have identical opcodes otherwise.
static unsigned getLAScore (VPValue *V1, VPValue *V2, unsigned MaxLevel, VPInterleavedAccessInfo &IAI)
Implements getLAScore from Listing 7 in the paper.
Variables
static unsigned LookaheadMaxDepth = 5
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vplan-slp"
Definition at line 45 of file VPlanSLP.cpp.
Function Documentation
areCommutative()
static bool areCommutative (ArrayRef< VPValue *> Values) static
Definition at line 170 of file VPlanSLP.cpp.
References getOpcode(), and llvm::Instruction::isCommutative().
Referenced by llvm::VPlanSlp::buildGraph().
areConsecutiveOrMatch()
static bool areConsecutiveOrMatch (VPInstruction * A, VPInstruction * B, VPInterleavedAccessInfo & IAI) static
Returns true if A and B access sequential memory if they are loads or stores or if they have identical opcodes otherwise.
Definition at line 207 of file VPlanSLP.cpp.
References llvm::VPInterleavedAccessInfo::getInterleaveGroup(), llvm::VPInstruction::getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by getLAScore().
getLAScore()
static unsigned getLAScore (VPValue * V1, VPValue * V2, unsigned MaxLevel, VPInterleavedAccessInfo & IAI) static
Implements getLAScore from Listing 7 in the paper.
Traverses and compares operands of V1 and V2 to MaxLevel.
Definition at line 223 of file VPlanSLP.cpp.
References areConsecutiveOrMatch(), assert(), llvm::dbgs(), llvm::Depth, E, llvm::SmallVectorBase::empty(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, llvm::SPII::Load, LookaheadMaxDepth, Mode, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::reserve(), second, and llvm::SmallVectorBase::size().
getOpcode()
static Optional<unsigned> getOpcode (ArrayRef< VPValue *> Values) static
Returns the opcode of Values or ~0 if they do not all agree.
Definition at line 196 of file VPlanSLP.cpp.
References llvm::any_of(), and llvm::None.
Referenced by areCommutative(), llvm::VPlanSlp::buildGraph(), buildNew(), canNarrowShiftAmt(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::ConstantFoldBinaryInstruction(), createRdxShuffleMask(), detectAVGPattern(), llvm::MCInst::dump_pretty(), llvm::Instruction::extractProfMetadata(), llvm::Instruction::extractProfTotalWeight(), llvm::R600InstrInfo::fitsReadPortLimitations(), llvm::UnOpInit::Fold(), llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), FoldBUILD_VECTOR(), foldShiftOfShiftedLogic(), foldVecTruncToExtElt(), GenerateSignBits(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::ConstantExpr::getAsInstruction(), llvm::UnOpInit::getAsString(), llvm::BinOpInit::getAsString(), llvm::TernOpInit::getAsString(), getNegatibleInsts(), llvm::CallBase::getNumSubclassExtraOperands(), llvm::Instruction::getOpcodeName(), llvm::ConstantExpr::getOpcodeName(), getSameOpcode(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getTargetMemSDNode(), getVariantKind(), llvm::ConstantExpr::getWithOperands(), llvm::ConstantExpr::hasIndices(), hasZeroSignBit(), llvm::Instruction::isArithmeticShift(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isBitwiseLogicOp(), llvm::Instruction::isCast(), llvm::ConstantExpr::isCast(), llvm::Instruction::isCommutative(), llvm::ConstantExpr::isCompare(), llvm::slpvectorizer::BoUpSLP::isDeleted(), llvm::Instruction::isEHPad(), llvm::Instruction::isExceptionalTerminator(), llvm::Instruction::isFenceLike(), llvm::Instruction::isFuncletPad(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), llvm::Instruction::isIdempotent(), llvm::Instruction::isIndirectTerminator(), llvm::Instruction::isIntDivRem(), llvm::Instruction::isLogicalShift(), llvm::Instruction::isNilpotent(), llvm::Instruction::isShift(), isShuffle(), isSignedMinMaxClamp(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::Instruction::isTerminator(), llvm::Instruction::isUnaryOp(), LinearizeExprTree(), LLVMGetConstOpcode(), llvm::VPRecipeBase::moveAfter(), llvm::MCInst::print(), llvm::VPInstruction::print(), llvm::UnOpInit::Profile(), llvm::BinOpInit::Profile(), llvm::TernOpInit::Profile(), ReorganizeVector(), llvm::UnOpInit::resolveReferences(), llvm::BinOpInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), shouldMergeGEPs(), llvm::HexagonShuffler::shuffle(), SRAGlobal(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitShl().
getOperands() [1/2]
static SmallVector<VPValue *, 4> getOperands (ArrayRef< VPValue *> Values, unsigned OperandIndex) static
Definition at line 160 of file VPlanSLP.cpp.
References Operands, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by llvm::VPlanSlp::buildGraph(), and getOperands().
getOperands() [2/2]
static SmallVector<SmallVector<VPValue *, 4>, 4> getOperands (ArrayRef< VPValue *> Values) static
Definition at line 176 of file VPlanSLP.cpp.
References getOperands(), I, llvm_unreachable, llvm::SPII::Load, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SPII::Store.
Variable Documentation
LookaheadMaxDepth
unsigned LookaheadMaxDepth = 5 static
Definition at line 48 of file VPlanSLP.cpp.
Referenced by getLAScore().