LLVM: lib/Transforms/Scalar/WarnMissedTransforms.cpp File Reference
WarnMissedTransforms.cpp File Reference
#include "llvm/Transforms/Scalar/WarnMissedTransforms.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "transform-warning"
Functions
static void warnAboutLeftoverTransformations (Loop *L, OptimizationRemarkEmitter *ORE)
Emit warnings for forced (i.e.
static void warnAboutLeftoverTransformations (Function *F, LoopInfo *LI, OptimizationRemarkEmitter *ORE)
INITIALIZE_PASS_BEGIN (WarnMissedTransformationsLegacy, "transform-warning", "Warn about non-applied transformations", false, false) INITIALIZE_PASS_END(WarnMissedTransformationsLegacy
Variables
transform warning
transform Warn about non applied transformations
transform Warn about non applied false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "transform-warning"
Definition at line 20 of file WarnMissedTransforms.cpp.
Referenced by warnAboutLeftoverTransformations().
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (WarnMissedTransformationsLegacy , "transform-warning" , "Warn about non-applied transformations" , false , false)
Referenced by llvm::WarnMissedTransformationsPass::run().
warnAboutLeftoverTransformations() [1/2]
static void warnAboutLeftoverTransformations (Loop * L, OptimizationRemarkEmitter * ORE) static
Emit warnings for forced (i.e.
user-defined) loop transformations which have still not been performed.
Definition at line 24 of file WarnMissedTransforms.cpp.
References llvm::dbgs(), DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getOptionalIntLoopAttribute(), llvm::Loop::getStartLoc(), llvm::Optional< T >::getValueOr(), llvm::hasDistributeTransformation(), llvm::hasUnrollAndJamTransformation(), llvm::hasUnrollTransformation(), llvm::hasVectorizeTransformation(), LLVM_DEBUG, and llvm::TM_ForcedByUser.
Referenced by llvm::WarnMissedTransformationsPass::run(), and warnAboutLeftoverTransformations().
warnAboutLeftoverTransformations() [2/2]
static void warnAboutLeftoverTransformations (Function * F, LoopInfo * LI, OptimizationRemarkEmitter * ORE) static
Definition at line 85 of file WarnMissedTransforms.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), and warnAboutLeftoverTransformations().
Variable Documentation
false
transform Warn about non applied false
Definition at line 144 of file WarnMissedTransforms.cpp.
transformations
transform Warn about non applied transformations
Definition at line 144 of file WarnMissedTransforms.cpp.
warning
transform warning
Definition at line 144 of file WarnMissedTransforms.cpp.
Referenced by llvm::WithColor::operator<<().