LLVM: lib/CodeGen/WasmEHPrepare.cpp File Reference
WasmEHPrepare.cpp File Reference
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Triple.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "wasmehprepare"
Functions
INITIALIZE_PASS (WasmEHPrepare, DEBUG_TYPE, "Prepare WebAssembly exceptions", false, false) FunctionPass *llvm
template<typename Container >
static void eraseDeadBBsAndChildren (const Container &BBs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasmehprepare"
Definition at line 97 of file WasmEHPrepare.cpp.
Function Documentation
eraseDeadBBsAndChildren()
template<typename Container > static void eraseDeadBBsAndChildren (const Container & BBs) static
Definition at line 156 of file WasmEHPrepare.cpp.
References assert(), llvm::DeleteDeadBlock(), llvm::SmallVectorBase::empty(), F(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHI(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), llvm::GlobalValue::getParent(), llvm::BasicBlock::isEHPad(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::Value::replaceAllUsesWith(), runOnFunction(), llvm::CallBase::setDoesNotThrow(), llvm::IRBuilderBase::SetInsertPoint(), llvm::succ_begin(), llvm::succ_end(), and llvm::Value::users().
INITIALIZE_PASS()
INITIALIZE_PASS (WasmEHPrepare , DEBUG_TYPE , "Prepare WebAssembly exceptions" , false , false)
Definition at line 139 of file WasmEHPrepare.cpp.
References llvm::StructType::get(), and llvm::Module::getContext().