LLVM: lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp File Reference
WebAssemblyLowerEmscriptenEHSjLj.cpp File Reference
This file lowers exception-related instructions and setjmp/longjmp function calls in order to use Emscripten's JavaScript try and catch mechanism.
#include "WebAssembly.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
Macros
#define DEBUG_TYPE "wasm-lower-em-ehsjlj"
Functions
INITIALIZE_PASS (WebAssemblyLowerEmscriptenEHSjLj, DEBUG_TYPE, "WebAssembly Lower Emscripten Exceptions / Setjmp / Longjmp", false, false) ModulePass *llvm
static bool canThrow (const Value *V)
static GlobalVariable * getGlobalVariableI32 (Module &M, IRBuilder<> &IRB, const char *Name)
static std::string getSignature (FunctionType *FTy)
Variables
static cl::list< std::string > EHWhitelist ("emscripten-cxx-exceptions-whitelist", cl::desc("The list of function names in which Emscripten-style " "exception handling is enabled (see emscripten " "EMSCRIPTEN_CATCHING_WHITELIST options)"), cl::CommaSeparated)
Detailed Description
This file lowers exception-related instructions and setjmp/longjmp function calls in order to use Emscripten's JavaScript try and catch mechanism.
To handle exceptions and setjmp/longjmps, this scheme relies on JavaScript's try and catch syntax and relevant exception-related libraries implemented in JavaScript glue code that will be produced by Emscripten. This is similar to the current Emscripten asm.js exception handling in fastcomp. For fastcomp's EH / SjLj scheme, see these files in fastcomp LLVM branch: (Location: https://github.com/kripken/emscripten-fastcomp) lib/Target/JSBackend/NaCl/LowerEmExceptionsPass.cpp lib/Target/JSBackend/NaCl/LowerEmSetjmp.cpp lib/Target/JSBackend/JSBackend.cpp lib/Target/JSBackend/CallHandlers.h
Exception handling This pass lowers invokes and landingpads into library functions in JS glue code. Invokes are lowered into function wrappers called invoke wrappers that exist in JS side, which wraps the original function call with JS try-catch. If an exception occurred, cxa_throw() function in JS side sets some variables (see below) so we can check whether an exception occurred from wasm code and handle it appropriately.
Setjmp-longjmp handling This pass lowers setjmp to a reasonably-performant approach for emscripten. The idea is that each block with a setjmp is broken up into two parts: the part containing setjmp and the part right after the setjmp. The latter part is either reached from the setjmp, or later from a longjmp. To handle the longjmp, all calls that might longjmp are also called using invoke wrappers and thus JS / try-catch. JS longjmp() function also sets some variables so we can check / whether a longjmp occurred from wasm code. Each block with a function call that might longjmp is also split up after the longjmp call. After the longjmp call, we check whether a longjmp occurred, and if it did, which setjmp it corresponds to, and jump to the right post-setjmp block. We assume setjmp-longjmp handling always run after EH handling, which means we don't expect any exception-related instructions when SjLj runs. FIXME Currently this scheme does not support indirect call of setjmp, because of the limitation of the scheme itself. fastcomp does not support it either.
In detail, this pass does following things:
1) Assumes the existence of global variables: THREW, threwValue __THREW and threwValue will be set in invoke wrappers in JS glue code. For what invoke wrappers are, refer to 3). These variables are used for both exceptions and setjmp/longjmps. __THREW indicates whether an exception or a longjmp occurred or not. 0 means nothing occurred, 1 means an exception occurred, and other numbers mean a longjmp occurred. In the case of longjmp, __threwValue variable indicates the corresponding setjmp buffer the longjmp corresponds to.
Exception handling
2) We assume the existence of setThrew and setTempRet0/getTempRet0 functions at link time. The global variables in 1) will exist in wasm address space, but their values should be set in JS code, so these functions as interfaces to JS glue code. These functions are equivalent to the following JS functions, which actually exist in asm.js version of JS library.
function setThrew(threw, value) { if (THREW == 0) { THREW = threw; __threwValue = value; } }
Definition in file WebAssemblyLowerEmscriptenEHSjLj.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-lower-em-ehsjlj"
Definition at line 220 of file WebAssemblyLowerEmscriptenEHSjLj.cpp.
Function Documentation
canThrow()
static bool canThrow (const Value * V) static
Definition at line 298 of file WebAssemblyLowerEmscriptenEHSjLj.cpp.
References F(), and Name.
Referenced by getSignature().
getGlobalVariableI32()
static GlobalVariable* getGlobalVariableI32 (Module & M, IRBuilder<> & IRB, const char * Name) static
Definition at line 315 of file WebAssemblyLowerEmscriptenEHSjLj.cpp.
References llvm::dyn_cast(), llvm::IRBuilderBase::getInt32Ty(), llvm::Module::getOrInsertGlobal(), and llvm::report_fatal_error().
Referenced by getSignature().
getSignature()
static std::string getSignature (FunctionType * FTy) static
Definition at line 331 of file WebAssemblyLowerEmscriptenEHSjLj.cpp.
References llvm::MCID::Add, llvm::SSAUpdater::AddAvailableValue(), llvm::SwitchInst::addCase(), llvm::PHINode::addIncoming(), llvm::SmallVectorImpl< T >::append(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), C, Callee, canThrow(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::BinaryOperator::Create(), llvm::IRBuilder< T, Inserter >::CreateAnd(), llvm::IRBuilder< T, Inserter >::CreateBr(), llvm::IRBuilder< T, Inserter >::CreateCall(), llvm::IRBuilder< T, Inserter >::CreateCondBr(), llvm::IRBuilder< T, Inserter >::CreateExtractValue(), llvm::CallInst::CreateFree(), llvm::IRBuilder< T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< T, Inserter >::CreateICmpNE(), llvm::IRBuilder< T, Inserter >::CreateInsertValue(), llvm::IRBuilder< T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< T, Inserter >::CreateLoad(), llvm::CallInst::CreateMalloc(), llvm::IRBuilder< T, Inserter >::CreatePHI(), llvm::IRBuilder< T, Inserter >::CreateStore(), llvm::IRBuilder< T, Inserter >::CreateSwitch(), llvm::IRBuilder< T, Inserter >::CreateUnreachable(), llvm::dbgs(), llvm::DominatorTree::dominates(), llvm::dyn_cast(), E, llvm::SmallPtrSetImplBase::empty(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::Function::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, F(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::AttributeList::FunctionIndex, llvm::FunctionType::get(), llvm::AttributeSet::get(), llvm::AttributeList::get(), llvm::UndefValue::get(), llvm::AttributeList::getAttributes(), llvm::Function::getContext(), llvm::Module::getContext(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHI(), llvm::AttributeList::getFnAttributes(), llvm::Module::getFunction(), llvm::Function::getFunctionType(), getGlobalVariableI32(), llvm::IRBuilderBase::getInt32(), llvm::Type::getInt32PtrTy(), llvm::IRBuilderBase::getInt32Ty(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Type::getInt8PtrTy(), llvm::Function::getIntrinsicID(), llvm::Instruction::getModule(), llvm::BasicBlock::getModule(), llvm::Value::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::AttributeList::getParamAttributes(), llvm::FunctionType::getParamType(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::AttributeList::getRetAttributes(), llvm::FunctionType::getReturnType(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Use::getUser(), llvm::Optional< T >::getValue(), llvm::IRBuilderBase::getVoidTy(), llvm::Optional< T >::hasValue(), I, llvm::ARM_PROC::IE, llvm::SSAUpdater::Initialize(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::GlobalValue::isDeclaration(), llvm::FunctionType::isVarArg(), LLVM_DEBUG, llvm::makeArrayRef(), llvm::None, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::FunctionType::params(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::remove_if(), replace(), llvm::Value::replaceAllUsesWith(), llvm::report_fatal_error(), llvm::SSAUpdater::RewriteUse(), llvm::SSAUpdater::RewriteUseAfterInsertions(), llvm::CallBase::setAttributes(), llvm::CallBase::setCallingConv(), llvm::Instruction::setDebugLoc(), llvm::Function::setDoesNotThrow(), llvm::IRBuilderBase::SetInsertPoint(), SI, llvm::SmallVectorBase::size(), llvm::BasicBlock::size(), llvm::SplitBlock(), SSA, llvm::StringRef::startswith(), llvm::raw_string_ostream::str(), llvm::CallingConv::Tail, llvm::Value::takeName(), llvm::RegState::Undef, llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), llvm::Value::users(), and llvm::CallingConv::WASM_EmscriptenInvoke.
Referenced by llvm::DWARFUnitIndex::getFromHash().
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblyLowerEmscriptenEHSjLj , DEBUG_TYPE , "WebAssembly Lower Emscripten Exceptions / Setjmp / Longjmp" , false , false)
Definition at line 289 of file WebAssemblyLowerEmscriptenEHSjLj.cpp.
Variable Documentation
EHWhitelist
cl::list<std::string> EHWhitelist("emscripten-cxx-exceptions-whitelist", cl::desc("The list of function names in which Emscripten-style " "exception handling is enabled (see emscripten " "EMSCRIPTEN_CATCHING_WHITELIST options)"), cl::CommaSeparated) static