LLVM: lib/Target/WebAssembly/WebAssemblyMCInstLower.cpp File Reference
WebAssemblyMCInstLower.cpp File Reference
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
#include "WebAssemblyMCInstLower.h"
#include "WebAssemblyAsmPrinter.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyRuntimeLibcallSignatures.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Constants.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "WebAssemblyGenInstrInfo.inc"
Macros
#define GET_INSTRMAP_INFO 1
Functions
static void removeRegisterOperands (const MachineInstr *MI, MCInst &OutMI)
static wasm::ValType getType (const TargetRegisterClass *RC)
static void getFunctionReturns (const MachineInstr *MI, SmallVectorImpl< wasm::ValType > &Returns)
Variables
cl::opt< bool > WasmKeepRegisters ("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false))
Detailed Description
This file contains code to lower WebAssembly MachineInstrs to their corresponding MCInst records.
Definition in file WebAssemblyMCInstLower.cpp.
Macro Definition Documentation
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO 1
Definition at line 34 of file WebAssemblyMCInstLower.cpp.
Function Documentation
getFunctionReturns()
static void getFunctionReturns (const MachineInstr * MI, SmallVectorImpl< wasm::ValType > & Returns) static
Definition at line 196 of file WebAssemblyMCInstLower.cpp.
References llvm::computeLegalValueVTs(), F(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getMF(), llvm::Function::getReturnType(), llvm::MachineFunction::getTarget(), and llvm::valTypesFromMVTs().
Referenced by llvm::WebAssemblyMCInstLower::lower().
getType()
static wasm::ValType getType (const TargetRegisterClass * RC) static
Definition at line 182 of file WebAssemblyMCInstLower.cpp.
References llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::I32, llvm::wasm::I64, llvm_unreachable, and llvm::wasm::V128.
Referenced by allSameType(), llvm::Record::appendLoc(), llvm::object::BaseRelocRef::BaseRelocRef(), branchMaxOffsets(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBoolExt(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::MachineIRBuilder::buildInsert(), llvm::MachineIRBuilder::buildSequence(), llvm::canConstantFoldCallTo(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), cloneConstantExprWithNewAddressSpace(), ComputeNumSignBitsImpl(), concatSubVector(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), llvm::Constant::containsConstantExpression(), llvm::Constant::containsUndefElement(), llvm::TypedInit::convertInitializerBitRange(), llvm::TypedInit::convertInitializerTo(), llvm::ListInit::convertInitializerTo(), llvm::DefInit::convertInitializerTo(), llvm::TypedInit::convertInitListSlice(), createCallInst(), llvm::createSeparateConstOffsetFromGEPPass(), DoInitialMatch(), llvm::GVNExpression::Expression::dump(), llvm::AMDGPU::HSAMD::MetadataStreamerV2::emitKernel(), llvm::GVNExpression::BasicExpression::equals(), llvm::UnOpInit::Fold(), llvm::TernOpInit::Fold(), foldIdentityExtractShuffle(), FunctionNumber(), llvm::InlineAsm::get(), GetAEABIUnwindPersonalityName(), llvm::UnOpInit::getAsString(), llvm::AAValueConstantRange::getAssumedConstantInt(), llvm::IRPosition::getAttrs(), llvm::object::COFFSymbolRef::getBaseType(), llvm::OpInit::getBit(), llvm::VarInit::getBit(), llvm::VarListElementInit::getBit(), llvm::FieldInit::getBit(), llvm::TypedInit::getCastTo(), getChainID(), llvm::object::COFFSymbolRef::getComplexType(), llvm::getCopyDeclaration(), llvm::ListInit::getElementType(), llvm::ConstantAggregateZero::getElementValue(), llvm::UndefValue::getElementValue(), llvm::TypedInit::getFieldType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), getMemSetPatternValue(), llvm::ConstantAggregateZero::getNumElements(), llvm::UndefValue::getNumElements(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::ConstantAggregateZero::getSequentialElement(), llvm::UndefValue::getSequentialElement(), llvm::DIVariable::getSignedness(), llvm::ConstantAggregateZero::getStructElement(), llvm::UndefValue::getStructElement(), llvm::ConstantPoolSDNode::getTargetFlags(), group2Shuffle(), llvm::DbgVariable::hasComplexAddress(), llvm::Constant::hasExactInverseFP(), insertLifetimeMarkersSurroundingCall(), instrumentMaskedLoadOrStore(), llvm::object::XCOFFObjectFile::is64Bit(), llvm::object::MachOObjectFile::is64Bit(), llvm::DbgVariable::isArtificial(), llvm::object::Elf_Sym_Impl< ELFT >::isCommon(), llvm::HexagonMCInstrInfo::isCompound(), llvm::rdf::RefNode::isDef(), llvm::Constant::isElementWiseEqual(), llvm::Constant::isFiniteNonZeroFP(), llvm::object::XCOFFSymbolRef::isFunction(), llvm::HexagonMCInstrInfo::isHVX(), isIFunc(), llvm::Constant::isNaN(), llvm::Constant::isNegativeZeroValue(), llvm::Constant::isNormalFP(), llvm::Constant::isNotMinSignedValue(), llvm::Constant::isNotOneValue(), llvm::DbgVariable::isObjectPointer(), llvm::MachineInstr::isOperandSubregIdx(), isReInterleaveMask(), llvm::rdf::RefNode::isUse(), llvm::HexagonMCInstrInfo::isVector(), LLVMBinaryGetType(), LLVMTypeOf(), llvm::WebAssemblyMCInstLower::lower(), llvm::fuzzerop::matchFirstType(), matchScalarInAggregate(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::MachineIRBuilder::materializePtrAdd(), llvm::ListInit::Profile(), llvm::UnOpInit::Profile(), llvm::BinOpInit::Profile(), llvm::TernOpInit::Profile(), llvm::UnOpInit::resolveReferences(), llvm::BinOpInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), llvm::SLPVectorizerPass::runImpl(), llvm::object::Elf_Sym_Impl< ELFT >::setBinding(), llvm::ELF::Elf32_Sym::setBinding(), llvm::ELF::Elf64_Sym::setBinding(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::setSymbol(), llvm::ELF::Elf32_Rel::setSymbol(), llvm::ELF::Elf32_Rela::setSymbol(), llvm::ELF::Elf64_Rel::setSymbol(), llvm::ELF::Elf64_Rela::setSymbol(), llvm::ARMAsmBackend::shouldForceRelocation(), simplifyFPOp(), SimplifyGEPInst(), speculatePHIs(), splitGlobal(), llvm::DISubprogram::toSPFlags(), tryUnmergingGEPsAcrossIndirectBr(), llvm::pdb::TpiStream::typeCollection(), validExtractValueIndex(), validInsertValueIndex(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLShr(), llvm::object::XCOFFSymbolRef::XCOFFSymbolRef(), and llvm::MetadataAsValue::~MetadataAsValue().
removeRegisterOperands()
static void removeRegisterOperands (const MachineInstr * MI, MCInst & OutMI) static
Definition at line 311 of file WebAssemblyMCInstLower.cpp.
References assert(), llvm::MCInst::erase(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), I, llvm::MachineInstr::isDebugInstr(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isLabel(), llvm::MachineOperand::isReg(), and llvm::MCInst::setOpcode().
Referenced by llvm::WebAssemblyMCInstLower::lower().
Variable Documentation
WasmKeepRegisters
cl::opt<bool> WasmKeepRegisters("wasm-keep-registers", cl::Hidden, cl::desc("WebAssembly: output stack registers in" " instruction output for test purposes only."), cl::init(false))
Referenced by llvm::WebAssemblyMCInstLower::lower().