LLVM: lib/Target/WebAssembly/MCTargetDesc/WebAssemblyInstPrinter.cpp File Reference
WebAssemblyInstPrinter.cpp File Reference
Print MCInst instructions to wasm format.
#include "MCTargetDesc/WebAssemblyInstPrinter.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyUtilities.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "WebAssemblyGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static std::string toString (const APFloat &FP)
Detailed Description
Print MCInst instructions to wasm format.
Definition in file WebAssemblyInstPrinter.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 31 of file WebAssemblyInstPrinter.cpp.
Function Documentation
toString()
static std::string toString (const APFloat & FP) static
Definition at line 185 of file WebAssemblyInstPrinter.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::bitwiseIsEqual(), llvm::APFloat::convertToHexString(), llvm::APInt::getBitWidth(), llvm::APFloat::getQNaN(), llvm::APFloat::getSemantics(), llvm::APInt::getZExtValue(), llvm::APFloat::isNaN(), llvm::APInt::isNegative(), llvm::APFloatBase::rmNearestTiesToEven, and llvm::utohexstr().