LLVM: lib/Target/WebAssembly/WebAssemblyRegNumbering.cpp File Reference
WebAssemblyRegNumbering.cpp File Reference
This file implements a pass which assigns WebAssembly register numbers for CodeGen virtual registers.
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblySubtarget.h"
#include "WebAssemblyUtilities.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "wasm-reg-numbering"
Functions
INITIALIZE_PASS (WebAssemblyRegNumbering, DEBUG_TYPE, "Assigns WebAssembly register numbers for virtual registers", false, false) FunctionPass *llvm
Detailed Description
This file implements a pass which assigns WebAssembly register numbers for CodeGen virtual registers.
Definition in file WebAssemblyRegNumbering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-reg-numbering"
Definition at line 31 of file WebAssemblyRegNumbering.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblyRegNumbering , DEBUG_TYPE , "Assigns WebAssembly register numbers for virtual registers" , false , false)
Definition at line 53 of file WebAssemblyRegNumbering.cpp.
References llvm::dbgs(), llvm::MachineFunction::front(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getName(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineFunction::getRegInfo(), llvm::Register::index2VirtReg(), llvm::WebAssembly::isArgument(), LLVM_DEBUG, MI, MRI, and llvm::WebAssemblyFunctionInfo::UnusedReg.