LLVM: lib/Target/WebAssembly/Disassembler/WebAssemblyDisassembler.cpp File Reference
WebAssemblyDisassembler.cpp File Reference
This file is part of the WebAssembly Disassembler.
#include "MCTargetDesc/WebAssemblyInstPrinter.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/TargetRegistry.h"
#include "WebAssemblyGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "wasm-disassembler"
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
static MCDisassembler * createWebAssemblyDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyDisassembler ()
static int nextByte (ArrayRef< uint8_t > Bytes, uint64_t &Size)
static bool nextLEB (int64_t &Val, ArrayRef< uint8_t > Bytes, uint64_t &Size, bool Signed)
static bool parseLEBImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes, bool Signed)
template<typename T >
bool parseImmediate (MCInst &MI, uint64_t &Size, ArrayRef< uint8_t > Bytes)
Detailed Description
This file is part of the WebAssembly Disassembler.
It contains code to translate the data produced by the decoder into MCInsts.
Definition in file WebAssemblyDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-disassembler"
Definition at line 34 of file WebAssemblyDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 36 of file WebAssemblyDisassembler.cpp.
Function Documentation
createWebAssemblyDisassembler()
static MCDisassembler* createWebAssemblyDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 60 of file WebAssemblyDisassembler.cpp.
References llvm::Target::createMCInstrInfo(), and LLVM_EXTERNAL_VISIBILITY.
Referenced by LLVMInitializeWebAssemblyDisassembler().
LLVMInitializeWebAssemblyDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyDisassembler ()
Definition at line 68 of file WebAssemblyDisassembler.cpp.
References createWebAssemblyDisassembler(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), and llvm::TargetRegistry::RegisterMCDisassembler().
nextByte()
static int nextByte (ArrayRef< uint8_t > Bytes, uint64_t & Size) static
Definition at line 76 of file WebAssemblyDisassembler.cpp.
References Size, and llvm::ArrayRef< T >::size().
Referenced by parseImmediate(), and readPrefixes().
nextLEB()
static bool nextLEB (int64_t & Val, ArrayRef< uint8_t > Bytes, uint64_t & Size, bool Signed) static
Definition at line 84 of file WebAssemblyDisassembler.cpp.
References llvm::ArrayRef< T >::data(), llvm::decodeSLEB128(), llvm::decodeULEB128(), llvm::Error, N, Size, and llvm::ArrayRef< T >::size().
Referenced by parseImmediate(), and parseLEBImmediate().
parseImmediate()
template<typename T > bool parseImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes)
Definition at line 109 of file WebAssemblyDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::Address, llvm::WebAssembly::anyTypeToString(), assert(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createFPImm(), llvm::MCOperand::createImm(), llvm::ArrayRef< T >::data(), llvm::MCDisassembler::Fail, I, llvm::WebAssembly::Invalid, llvm_unreachable, MI, Name, nextByte(), nextLEB(), llvm::WebAssembly::OPERAND_BASIC_BLOCK, llvm::WebAssembly::OPERAND_BRLIST, llvm::WebAssembly::OPERAND_EVENT, llvm::WebAssembly::OPERAND_F32IMM, llvm::WebAssembly::OPERAND_F64IMM, llvm::WebAssembly::OPERAND_FUNCTION32, llvm::WebAssembly::OPERAND_GLOBAL, llvm::WebAssembly::OPERAND_I32IMM, llvm::WebAssembly::OPERAND_I64IMM, llvm::MCOI::OPERAND_IMMEDIATE, llvm::WebAssembly::OPERAND_LOCAL, llvm::WebAssembly::OPERAND_OFFSET32, llvm::WebAssembly::OPERAND_P2ALIGN, llvm::MCOI::OPERAND_REGISTER, llvm::WebAssembly::OPERAND_SIGNATURE, llvm::WebAssembly::OPERAND_TYPEINDEX, llvm::WebAssembly::OPERAND_VEC_I16IMM, llvm::WebAssembly::OPERAND_VEC_I32IMM, llvm::WebAssembly::OPERAND_VEC_I64IMM, llvm::WebAssembly::OPERAND_VEC_I8IMM, llvm::outs(), parseLEBImmediate(), llvm::MCInst::setOpcode(), Size, llvm::ArrayRef< T >::size(), llvm::MCDisassembler::Success, llvm::T, llvm::MCSymbolRefExpr::VK_WASM_TYPEINDEX, and llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION.
Referenced by matchRegisterNameHelper(), and shouldBeSls().
parseLEBImmediate()
static bool parseLEBImmediate (MCInst & MI, uint64_t & Size, ArrayRef< uint8_t > Bytes, bool Signed) static
Definition at line 99 of file WebAssemblyDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and nextLEB().
Referenced by parseImmediate().