LLVM: lib/Target/WebAssembly/WebAssemblyLowerGlobalDtors.cpp File Reference
WebAssemblyLowerGlobalDtors.cpp File Reference
Lower .global_dtors.
#include "WebAssembly.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Macros
#define DEBUG_TYPE "wasm-lower-global-dtors"
Functions
INITIALIZE_PASS (LowerGlobalDtors, DEBUG_TYPE, "Lower @llvm.global_dtors for WebAssembly", false, false) ModulePass *llvm
Detailed Description
Lower .global_dtors.
WebAssembly doesn't have a builtin way to invoke static destructors. Implement .global_dtors by creating wrapper functions that are registered in .global_ctors and which contain a call to __cxa_atexit to register their destructor functions.
Definition in file WebAssemblyLowerGlobalDtors.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-lower-global-dtors"
Definition at line 31 of file WebAssemblyLowerGlobalDtors.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LowerGlobalDtors , DEBUG_TYPE , "Lower @llvm.global_dtors for WebAssembly" , false , false)
Definition at line 53 of file WebAssemblyLowerGlobalDtors.cpp.
References llvm::appendToGlobalCtors(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, C, llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::CallInst::Create(), llvm::ReturnInst::Create(), llvm::BranchInst::Create(), llvm::dbgs(), llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalValue::ExternalWeakLinkage, llvm::FunctionType::get(), llvm::ConstantPointerNull::get(), llvm::PointerType::get(), llvm::Module::getContext(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Module::getOrInsertFunction(), llvm::Value::getType(), llvm::ConstantArray::getType(), llvm::Type::getVoidTy(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::HiddenVisibility, llvm::CmpInst::ICMP_NE, llvm::Constant::isNullValue(), LLVM_DEBUG, llvm::RISCVFenceField::O, llvm::User::operands(), llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::setVisibility(), and llvm::Constant::stripPointerCasts().