LLVM: lib/Target/WebAssembly/WebAssemblyOptimizeReturned.cpp File Reference
WebAssemblyOptimizeReturned.cpp File Reference
Optimize calls with "returned" attributes for WebAssembly.
#include "WebAssembly.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "wasm-optimize-returned"
Functions
INITIALIZE_PASS (OptimizeReturned, DEBUG_TYPE, "Optimize calls with \eturned\attributes for WebAssembly", false, false) FunctionPass *llvm
Detailed Description
Optimize calls with "returned" attributes for WebAssembly.
Definition in file WebAssemblyOptimizeReturned.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-optimize-returned"
Definition at line 21 of file WebAssemblyOptimizeReturned.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (OptimizeReturned , DEBUG_TYPE , "Optimize calls with \eturned\attributes for WebAssembly" , false , false)
Definition at line 50 of file WebAssemblyOptimizeReturned.cpp.
References Arg, llvm::dbgs(), E, F(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getArgOperand(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::Value::getName(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getNumArgOperands(), I, LLVM_DEBUG, llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::paramHasAttr(), llvm::Value::replaceUsesWithIf(), and runOnFunction().