LLVM: lib/Target/WebAssembly/WebAssemblySetP2AlignOperands.cpp File Reference
WebAssemblySetP2AlignOperands.cpp File Reference
This file sets the p2align operands on load and store instructions.
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyInstrInfo.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "wasm-set-p2align-operands"
Functions
INITIALIZE_PASS (WebAssemblySetP2AlignOperands, DEBUG_TYPE, "Set the p2align operands for WebAssembly loads and stores", false, false) FunctionPass *llvm
static void rewriteP2Align (MachineInstr &MI, unsigned OperandNo)
Detailed Description
This file sets the p2align operands on load and store instructions.
Definition in file WebAssemblySetP2AlignOperands.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-set-p2align-operands"
Definition at line 25 of file WebAssemblySetP2AlignOperands.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblySetP2AlignOperands , DEBUG_TYPE , "Set the p2align operands for WebAssembly loads and stores" , false , false)
Definition at line 49 of file WebAssemblySetP2AlignOperands.cpp.
rewriteP2Align()
static void rewriteP2Align (MachineInstr & MI, unsigned OperandNo) static
Definition at line 57 of file WebAssemblySetP2AlignOperands.cpp.
References assert(), llvm::dbgs(), getAlignment(), llvm::WebAssembly::GetDefaultP2Align(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getName(), llvm::WebAssembly::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::hasOneMemOperand(), LLVM_DEBUG, llvm::Log2_64(), llvm::MachineInstr::memoperands_begin(), MI, llvm::WebAssembly::OPERAND_P2ALIGN, llvm::MCOperandInfo::OperandType, llvm::MCInstrDesc::OpInfo, and llvm::MachineOperand::setImm().