LLVM: lib/Target/WebAssembly/MCTargetDesc/WebAssemblyWasmObjectWriter.cpp File Reference
WebAssemblyWasmObjectWriter.cpp File Reference
This file handles Wasm-specific object emission, converting LLVM's internal fixups into the appropriate relocations.
#include "MCTargetDesc/WebAssemblyFixupKinds.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWasmObjectWriter.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static const MCSection * getFixupSection (const MCExpr *Expr)
Detailed Description
This file handles Wasm-specific object emission, converting LLVM's internal fixups into the appropriate relocations.
Definition in file WebAssemblyWasmObjectWriter.cpp.
Function Documentation
getFixupSection()
static const MCSection* getFixupSection (const MCExpr * Expr) static
Definition at line 46 of file WebAssemblyWasmObjectWriter.cpp.
References assert(), Fixup, llvm::WebAssembly::fixup_sleb128_i32, llvm::WebAssembly::fixup_sleb128_i64, llvm::WebAssembly::fixup_uleb128_i32, llvm::FK_Data_4, llvm::MCValue::getAccessVariant(), llvm::MCFixup::getKind(), getRelocType(), llvm::MCValue::getSymA(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCFixup::getValue(), llvm_unreachable, llvm::ARMBuildAttrs::Section, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_WASM_MBREL, llvm::MCSymbolRefExpr::VK_WASM_TBREL, and llvm::MCSymbolRefExpr::VK_WASM_TYPEINDEX.