LLVM: lib/Target/WebAssembly/WebAssemblyExplicitLocals.cpp File Reference
WebAssemblyExplicitLocals.cpp File Reference
This file converts any remaining registers into WebAssembly locals.
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyDebugValueManager.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblySubtarget.h"
#include "WebAssemblyUtilities.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "wasm-explicit-locals"
Functions
INITIALIZE_PASS (WebAssemblyExplicitLocals, DEBUG_TYPE, "Convert registers to WebAssembly locals", false, false) FunctionPass *llvm
static unsigned getLocalId (DenseMap< unsigned, unsigned > &Reg2Local, unsigned &CurLocal, unsigned Reg)
Return a local id number for the given register, assigning it a new one if it doesn't yet have one.
static unsigned getDropOpcode (const TargetRegisterClass *RC)
Get the appropriate drop opcode for the given register class.
static unsigned getLocalGetOpcode (const TargetRegisterClass *RC)
Get the appropriate local.get opcode for the given register class.
static unsigned getLocalSetOpcode (const TargetRegisterClass *RC)
Get the appropriate local.set opcode for the given register class.
static unsigned getLocalTeeOpcode (const TargetRegisterClass *RC)
Get the appropriate local.tee opcode for the given register class.
static MVT typeForRegClass (const TargetRegisterClass *RC)
Get the type associated with the given register class.
static MachineInstr * findStartOfTree (MachineOperand &MO, MachineRegisterInfo &MRI, WebAssemblyFunctionInfo &MFI)
Given a MachineOperand of a stackified vreg, return the instruction at the start of the expression tree.
Variables
static cl::opt< bool > WasmDisableExplicitLocals ("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false))
Detailed Description
This file converts any remaining registers into WebAssembly locals.
After register stackification and register coloring, convert non-stackified registers into locals, inserting explicit local.get and local.set instructions.
Definition in file WebAssemblyExplicitLocals.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-explicit-locals"
Definition at line 32 of file WebAssemblyExplicitLocals.cpp.
Function Documentation
findStartOfTree()
static MachineInstr* findStartOfTree (MachineOperand & MO, MachineRegisterInfo & MRI, WebAssemblyFunctionInfo & MFI) static
Given a MachineOperand of a stackified vreg, return the instruction at the start of the expression tree.
Definition at line 169 of file WebAssemblyExplicitLocals.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::tgtok::Def, E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::explicit_uses(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), getDropOpcode(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), getLocalGetOpcode(), getLocalId(), getLocalSetOpcode(), getLocalTeeOpcode(), llvm::MachineFunction::getName(), llvm::MCInstrDesc::getNumDefs(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getOperandNo(), llvm::WebAssemblyFunctionInfo::getParams(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::Register::index2VirtReg(), llvm::WebAssembly::isArgument(), llvm::WebAssembly::isCopy(), llvm::MachineInstr::isDebugInstr(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isLabel(), llvm::WebAssembly::isTee(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), LLVM_DEBUG, MI, MRI, Reg, llvm::MachineRegisterInfo::replaceRegWith(), llvm::WebAssemblyDebugValueManager::replaceWithLocal(), llvm::reverse(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::WebAssemblyFunctionInfo::setLocal(), llvm::WebAssemblyFunctionInfo::setNumLocals(), llvm::MachineOperand::setReg(), llvm::WebAssemblyFunctionInfo::stackifyVReg(), TII, typeForRegClass(), llvm::MachineInstr::untieRegOperand(), llvm::MachineRegisterInfo::use_empty(), llvm::Register::virtReg2Index(), and WasmDisableExplicitLocals.
getDropOpcode()
static unsigned getDropOpcode (const TargetRegisterClass * RC) static
Get the appropriate drop opcode for the given register class.
Definition at line 83 of file WebAssemblyExplicitLocals.cpp.
References llvm_unreachable.
Referenced by findStartOfTree().
getLocalGetOpcode()
static unsigned getLocalGetOpcode (const TargetRegisterClass * RC) static
Get the appropriate local.get opcode for the given register class.
Definition at line 100 of file WebAssemblyExplicitLocals.cpp.
References llvm_unreachable.
Referenced by findStartOfTree().
getLocalId()
static unsigned getLocalId (DenseMap< unsigned, unsigned > & Reg2Local, unsigned & CurLocal, unsigned Reg) static
Return a local id number for the given register, assigning it a new one if it doesn't yet have one.
Definition at line 74 of file WebAssemblyExplicitLocals.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and P.
Referenced by findStartOfTree().
getLocalSetOpcode()
static unsigned getLocalSetOpcode (const TargetRegisterClass * RC) static
Get the appropriate local.set opcode for the given register class.
Definition at line 117 of file WebAssemblyExplicitLocals.cpp.
References llvm_unreachable.
Referenced by findStartOfTree().
getLocalTeeOpcode()
static unsigned getLocalTeeOpcode (const TargetRegisterClass * RC) static
Get the appropriate local.tee opcode for the given register class.
Definition at line 134 of file WebAssemblyExplicitLocals.cpp.
References llvm_unreachable.
Referenced by findStartOfTree().
INITIALIZE_PASS()
INITIALIZE_PASS (WebAssemblyExplicitLocals , DEBUG_TYPE , "Convert registers to WebAssembly locals" , false , false)
Definition at line 65 of file WebAssemblyExplicitLocals.cpp.
typeForRegClass()
static MVT typeForRegClass (const TargetRegisterClass * RC) static
Get the type associated with the given register class.
Definition at line 151 of file WebAssemblyExplicitLocals.cpp.
References llvm::MVT::exnref, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, and llvm::MVT::v16i8.
Referenced by findStartOfTree().
Variable Documentation
WasmDisableExplicitLocals
cl::opt<bool> WasmDisableExplicitLocals("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false)) static
Referenced by findStartOfTree().