LLVM: lib/WindowsManifest/WindowsManifestMerger.cpp File Reference
WindowsManifestMerger.cpp File Reference
#include "llvm/WindowsManifest/WindowsManifestMerger.h"
#include "llvm/Config/config.h"
#include "llvm/Support/MemoryBuffer.h"
#include <map>
#include <libxml/xmlreader.h>
Classes
class llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl
Macros
#define TO_XML_CHAR(X) reinterpret_cast<const unsigned char *>(X)
#define FROM_XML_CHAR(X) reinterpret_cast<const char *>(X)
Functions
static bool xmlStringsEqual (const unsigned char *A, const unsigned char *B)
static bool isMergeableElement (const unsigned char *ElementName)
static xmlNodePtr getChildWithName (xmlNodePtr Parent, const unsigned char *ElementName)
static xmlAttrPtr getAttribute (xmlNodePtr Node, const unsigned char *AttributeName)
static bool namespaceOverrides (const unsigned char *HRef1, const unsigned char *HRef2)
static xmlNsPtr search (const unsigned char *HRef, xmlNodePtr Node)
static const unsigned char * getPrefixForHref (const unsigned char *HRef)
static Expected< xmlNsPtr > searchOrDefine (const unsigned char *HRef, xmlNodePtr Node)
static Error copyAttributeNamespace (xmlAttrPtr OriginalAttribute, xmlNodePtr OriginalNode, xmlAttrPtr AdditionalAttribute)
static xmlNsPtr getNamespaceWithPrefix (const unsigned char *Prefix, xmlNodePtr Node)
static xmlNsPtr getClosestDefault (xmlNodePtr Node)
static Error mergeAttributes (xmlNodePtr OriginalNode, xmlNodePtr AdditionalNode)
static xmlNodePtr getDominantNode (xmlNodePtr Node1, xmlNodePtr Node2)
static bool hasInheritedNs (xmlNodePtr Node)
static bool hasInheritedDefaultNs (xmlNodePtr Node)
static bool hasDefinedDefaultNamespace (xmlNodePtr Node)
static void explicateNamespace (xmlNsPtr PrefixDef, xmlNodePtr Node)
static Error mergeNamespaces (xmlNodePtr OriginalNode, xmlNodePtr AdditionalNode)
static bool isRecognizedNamespace (const unsigned char *NsHref)
static bool hasRecognizedNamespace (xmlNodePtr Node)
static Error reconcileNamespaces (xmlNodePtr Node)
static Error treeMerge (xmlNodePtr OriginalRoot, xmlNodePtr AdditionalRoot)
static void stripComments (xmlNodePtr Root)
static void setAttributeNamespaces (xmlNodePtr Node)
static void checkAndStripPrefixes (xmlNodePtr Node, std::vector< xmlNsPtr > &RequiredPrefixes)
Variables
static constexpr std::pair< StringLiteral, StringLiteral > MtNsHrefsPrefixes []
Macro Definition Documentation
FROM_XML_CHAR
#define FROM_XML_CHAR (X) reinterpret_cast<const char *>(X)
Definition at line 24 of file WindowsManifestMerger.cpp.
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest(), isMergeableElement(), mergeAttributes(), mergeNamespaces(), treeMerge(), and xmlStringsEqual().
TO_XML_CHAR
#define TO_XML_CHAR (X) reinterpret_cast<const unsigned char *>(X)
Definition at line 23 of file WindowsManifestMerger.cpp.
Referenced by getPrefixForHref(), isRecognizedNamespace(), mergeNamespaces(), namespaceOverrides(), and stripComments().
Function Documentation
checkAndStripPrefixes()
static void checkAndStripPrefixes (xmlNodePtr Node, std::vector< xmlNsPtr > & RequiredPrefixes) static
Definition at line 573 of file WindowsManifestMerger.cpp.
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::getMergedManifest().
copyAttributeNamespace()
static Error copyAttributeNamespace (xmlAttrPtr OriginalAttribute, xmlNodePtr OriginalNode, xmlAttrPtr AdditionalAttribute) static
Definition at line 164 of file WindowsManifestMerger.cpp.
References llvm::Expected< T >::get(), searchOrDefine(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by mergeAttributes().
explicateNamespace()
static void explicateNamespace (xmlNsPtr PrefixDef, xmlNodePtr Node) static
Definition at line 310 of file WindowsManifestMerger.cpp.
Referenced by mergeNamespaces().
getAttribute()
static xmlAttrPtr getAttribute (xmlNodePtr Node, const unsigned char * AttributeName) static
Definition at line 98 of file WindowsManifestMerger.cpp.
Referenced by llvm::CallSiteBase< Function, BasicBlock, Value, User, Use, Instruction, CallInst, InvokeInst, CallBrInst, User::op_iterator >::getAttribute(), llvm::Function::getFnAttribute(), llvm::AttributeList::getParamAttr(), llvm::AttributeSetNode::hasAttributes(), llvm::AttributeSet::hasAttributes(), llvm::AttributeList::hasParamAttrs(), LLVMGetCallSiteEnumAttribute(), LLVMGetCallSiteStringAttribute(), LLVMGetEnumAttributeAtIndex(), LLVMGetStringAttributeAtIndex(), and mergeAttributes().
getChildWithName()
static xmlNodePtr getChildWithName (xmlNodePtr Parent, const unsigned char * ElementName) static
Definition at line 88 of file WindowsManifestMerger.cpp.
References xmlStringsEqual().
Referenced by treeMerge().
getClosestDefault()
static xmlNsPtr getClosestDefault (xmlNodePtr Node) static
Definition at line 193 of file WindowsManifestMerger.cpp.
Referenced by mergeAttributes(), and mergeNamespaces().
getDominantNode()
static xmlNodePtr getDominantNode (xmlNodePtr Node1, xmlNodePtr Node2) static
Definition at line 278 of file WindowsManifestMerger.cpp.
References namespaceOverrides().
Referenced by mergeNamespaces().
getNamespaceWithPrefix()
static xmlNsPtr getNamespaceWithPrefix (const unsigned char * Prefix, xmlNodePtr Node) static
Definition at line 178 of file WindowsManifestMerger.cpp.
Referenced by mergeNamespaces().
getPrefixForHref()
static const unsigned char* getPrefixForHref (const unsigned char * HRef) static
Definition at line 140 of file WindowsManifestMerger.cpp.
References MtNsHrefsPrefixes, TO_XML_CHAR, and xmlStringsEqual().
hasDefinedDefaultNamespace()
static bool hasDefinedDefaultNamespace (xmlNodePtr Node) static
Definition at line 301 of file WindowsManifestMerger.cpp.
Referenced by mergeNamespaces().
hasInheritedDefaultNs()
static bool hasInheritedDefaultNs (xmlNodePtr Node) static
Definition at line 296 of file WindowsManifestMerger.cpp.
hasInheritedNs()
static bool hasInheritedNs (xmlNodePtr Node) static
Definition at line 290 of file WindowsManifestMerger.cpp.
hasRecognizedNamespace()
static bool hasRecognizedNamespace (xmlNodePtr Node) static
Definition at line 482 of file WindowsManifestMerger.cpp.
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(), and treeMerge().
isMergeableElement()
static bool isMergeableElement (const unsigned char * ElementName) static
Definition at line 77 of file WindowsManifestMerger.cpp.
References FROM_XML_CHAR.
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(), and treeMerge().
isRecognizedNamespace()
static bool isRecognizedNamespace (const unsigned char * NsHref) static
Definition at line 473 of file WindowsManifestMerger.cpp.
References MtNsHrefsPrefixes, TO_XML_CHAR, and xmlStringsEqual().
mergeAttributes()
static Error mergeAttributes (xmlNodePtr OriginalNode, xmlNodePtr AdditionalNode) static
Definition at line 207 of file WindowsManifestMerger.cpp.
References copyAttributeNamespace(), E, FROM_XML_CHAR, llvm::Expected< T >::get(), getAttribute(), getClosestDefault(), namespaceOverrides(), searchOrDefine(), llvm::Error::success(), llvm::Expected< T >::takeError(), and xmlStringsEqual().
Referenced by treeMerge().
mergeNamespaces()
static Error mergeNamespaces (xmlNodePtr OriginalNode, xmlNodePtr AdditionalNode) static
Definition at line 332 of file WindowsManifestMerger.cpp.
References llvm::tgtok::Def, llvm::ECError::EC, explicateNamespace(), FROM_XML_CHAR, llvm::Expected< T >::get(), getClosestDefault(), getDominantNode(), getNamespaceWithPrefix(), hasDefinedDefaultNamespace(), namespaceOverrides(), searchOrDefine(), llvm::Error::success(), llvm::Expected< T >::takeError(), TO_XML_CHAR, and xmlStringsEqual().
Referenced by treeMerge().
namespaceOverrides()
static bool namespaceOverrides (const unsigned char * HRef1, const unsigned char * HRef2) static
Definition at line 110 of file WindowsManifestMerger.cpp.
References llvm::find_if(), MtNsHrefsPrefixes, TO_XML_CHAR, and xmlStringsEqual().
Referenced by getDominantNode(), mergeAttributes(), and mergeNamespaces().
reconcileNamespaces()
static Error reconcileNamespaces (xmlNodePtr Node) static
Definition at line 488 of file WindowsManifestMerger.cpp.
Referenced by treeMerge().
search()
static xmlNsPtr search (const unsigned char * HRef, xmlNodePtr Node) static
Definition at line 126 of file WindowsManifestMerger.cpp.
searchOrDefine()
static Expected<xmlNsPtr> searchOrDefine (const unsigned char * HRef, xmlNodePtr Node) static
Definition at line 153 of file WindowsManifestMerger.cpp.
Referenced by copyAttributeNamespace(), mergeAttributes(), and mergeNamespaces().
setAttributeNamespaces()
static void setAttributeNamespaces (xmlNodePtr Node) static
Definition at line 559 of file WindowsManifestMerger.cpp.
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge().
stripComments()
static void stripComments (xmlNodePtr Root) static
Definition at line 541 of file WindowsManifestMerger.cpp.
References TO_XML_CHAR, and xmlStringsEqual().
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge().
treeMerge()
static Error treeMerge (xmlNodePtr OriginalRoot, xmlNodePtr AdditionalRoot) static
Definition at line 511 of file WindowsManifestMerger.cpp.
References E, FROM_XML_CHAR, getChildWithName(), hasRecognizedNamespace(), isMergeableElement(), mergeAttributes(), mergeNamespaces(), reconcileNamespaces(), and llvm::Error::success().
Referenced by llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge().
xmlStringsEqual()
static bool xmlStringsEqual (const unsigned char * A, const unsigned char * B) static
Definition at line 69 of file WindowsManifestMerger.cpp.
References B, and FROM_XML_CHAR.
Referenced by getChildWithName(), getPrefixForHref(), isRecognizedNamespace(), llvm::windows_manifest::WindowsManifestMerger::WindowsManifestMergerImpl::merge(), mergeAttributes(), mergeNamespaces(), namespaceOverrides(), and stripComments().
Variable Documentation
MtNsHrefsPrefixes
constexpr std::pair<StringLiteral, StringLiteral> MtNsHrefsPrefixes[] static
Initial value:
= {
    {"urn:schemas-microsoft-com:asm.v1", "ms_asmv1"},
    {"urn:schemas-microsoft-com:asm.v2", "ms_asmv2"},
    {"urn:schemas-microsoft-com:asm.v3", "ms_asmv3"},
    {"http://schemas.microsoft.com/SMI/2005/WindowsSettings",
     "ms_windowsSettings"},
    {"urn:schemas-microsoft-com:compatibility.v1", "ms_compatibilityv1"}}
Definition at line 61 of file WindowsManifestMerger.cpp.
Referenced by getPrefixForHref(), isRecognizedNamespace(), and namespaceOverrides().