LLVM: lib/CodeGen/AsmPrinter/WinException.cpp File Reference
WinException.cpp File Reference
#include "WinException.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetOptions.h"
Functions
static MCSymbol * getMCSymbolForMBB (AsmPrinter *Asm, const MachineBasicBlock *MBB)
Retrieve the MCSymbol for a GlobalValue or MachineBasicBlock.
static int getTryRank (const WinEHFuncInfo &FuncInfo, int State)
static int getTryAncestor (const WinEHFuncInfo &FuncInfo, int Left, int Right)
Function Documentation
getMCSymbolForMBB()
static MCSymbol* getMCSymbolForMBB (AsmPrinter * Asm, const MachineBasicBlock * MBB) static
Retrieve the MCSymbol for a GlobalValue or MachineBasicBlock.
Definition at line 169 of file WinException.cpp.
References assert(), llvm::GlobalValue::dropLLVMManglingEscape(), F(), llvm::Value::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), llvm::MachineBasicBlock::isCleanupFuncletEntry(), and llvm::MachineBasicBlock::isEHFuncletEntry().
Referenced by llvm::WinException::beginFunclet().
getTryAncestor()
static int getTryAncestor (const WinEHFuncInfo & FuncInfo, int Left, int Right) static
Definition at line 1067 of file WinException.cpp.
References llvm::EHStreamer::Asm, assert(), llvm::MachineFunction::begin(), llvm::WinEHFuncInfo::ClrEHUnwindMap, llvm::MCStreamer::EmitIntValue(), llvm::MachineFunction::front(), llvm::AsmPrinter::getFunctionBegin(), llvm::AsmPrinter::getFunctionEnd(), getTryRank(), llvm::MachineFunction::getWinEHFuncInfo(), llvm::Left, llvm::AsmPrinter::OutStreamer, and llvm::Right.
getTryRank()
static int getTryRank (const WinEHFuncInfo & FuncInfo, int State) static
Definition at line 1058 of file WinException.cpp.
References llvm::WinEHFuncInfo::ClrEHUnwindMap.
Referenced by getTryAncestor().