LLVM: lib/CodeGen/WinEHPrepare.cpp File Reference
WinEHPrepare.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
Macros
#define DEBUG_TYPE "winehprepare"
Functions
INITIALIZE_PASS (WinEHPrepare, DEBUG_TYPE, "Prepare Windows exceptions", false, false) FunctionPass *llvm
static int addUnwindMapEntry (WinEHFuncInfo &FuncInfo, int ToState, const BasicBlock *BB)
static void addTryBlockMapEntry (WinEHFuncInfo &FuncInfo, int TryLow, int TryHigh, int CatchHigh, ArrayRef< const CatchPadInst *> Handlers)
static BasicBlock * getCleanupRetUnwindDest (const CleanupPadInst *CleanupPad)
static void calculateStateNumbersForInvokes (const Function *Fn, WinEHFuncInfo &FuncInfo)
static const BasicBlock * getEHPadFromPredecessor (const BasicBlock *BB, Value *ParentPad)
static void calculateCXXStateNumbers (WinEHFuncInfo &FuncInfo, const Instruction *FirstNonPHI, int ParentState)
static int addSEHExcept (WinEHFuncInfo &FuncInfo, int ParentState, const Function *Filter, const BasicBlock *Handler)
static int addSEHFinally (WinEHFuncInfo &FuncInfo, int ParentState, const BasicBlock *Handler)
static void calculateSEHStateNumbers (WinEHFuncInfo &FuncInfo, const Instruction *FirstNonPHI, int ParentState)
static bool isTopLevelPadForMSVC (const Instruction *EHPad)
static int addClrEHHandler (WinEHFuncInfo &FuncInfo, int HandlerParentState, int TryParentState, ClrHandlerType HandlerType, uint32_t TypeToken, const BasicBlock *Handler)
Variables
static cl::opt< bool > DisableDemotion ("disable-demotion", cl::Hidden, cl::desc("Clone multicolor basic blocks but do not demote cross scopes"), cl::init(false))
static cl::opt< bool > DisableCleanups ("disable-cleanups", cl::Hidden, cl::desc("Do not remove implausible terminators or other similar cleanups"), cl::init(false))
static cl::opt< bool > DemoteCatchSwitchPHIOnlyOpt ("demote-catchswitch-only", cl::Hidden, cl::desc("Demote catchswitch BBs only (for wasm EH)"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "winehprepare"
Definition at line 40 of file WinEHPrepare.cpp.
Function Documentation
addClrEHHandler()
static int addClrEHHandler (WinEHFuncInfo & FuncInfo, int HandlerParentState, int TryParentState, ClrHandlerType HandlerType, uint32_t TypeToken, const BasicBlock * Handler) static
Definition at line 465 of file WinEHPrepare.cpp.
Referenced by llvm::calculateClrEHStateNumbers().
addSEHExcept()
static int addSEHExcept (WinEHFuncInfo & FuncInfo, int ParentState, const Function * Filter, const BasicBlock * Handler) static
Definition at line 317 of file WinEHPrepare.cpp.
Referenced by calculateSEHStateNumbers().
addSEHFinally()
static int addSEHFinally (WinEHFuncInfo & FuncInfo, int ParentState, const BasicBlock * Handler) static
Definition at line 328 of file WinEHPrepare.cpp.
Referenced by calculateSEHStateNumbers().
addTryBlockMapEntry()
static void addTryBlockMapEntry (WinEHFuncInfo & FuncInfo, int TryLow, int TryHigh, int CatchHigh, ArrayRef< const CatchPadInst *> Handlers) static
Definition at line 140 of file WinEHPrepare.cpp.
References llvm::WinEHHandlerType::Adjectives, llvm::WinEHHandlerType::Alloca, assert(), llvm::WinEHTryBlockMapEntry::CatchHigh, llvm::WinEHHandlerType::CatchObj, llvm::WinEHHandlerType::Handler, llvm::WinEHTryBlockMapEntry::HandlerArray, llvm::Constant::isNullValue(), llvm::Constant::stripPointerCasts(), llvm::WinEHFuncInfo::TryBlockMap, llvm::WinEHTryBlockMapEntry::TryHigh, llvm::WinEHTryBlockMapEntry::TryLow, and llvm::WinEHHandlerType::TypeDescriptor.
Referenced by calculateCXXStateNumbers().
addUnwindMapEntry()
static int addUnwindMapEntry (WinEHFuncInfo & FuncInfo, int ToState, const BasicBlock * BB) static
Definition at line 131 of file WinEHPrepare.cpp.
References llvm::CxxUnwindMapEntry::Cleanup, llvm::WinEHFuncInfo::CxxUnwindMap, llvm::WinEHFuncInfo::getLastStateNumber(), and llvm::CxxUnwindMapEntry::ToState.
Referenced by calculateCXXStateNumbers().
calculateCXXStateNumbers()
static void calculateCXXStateNumbers (WinEHFuncInfo & FuncInfo, const Instruction * FirstNonPHI, int ParentState) static
Definition at line 237 of file WinEHPrepare.cpp.
References addTryBlockMapEntry(), addUnwindMapEntry(), assert(), llvm::dbgs(), llvm::WinEHFuncInfo::EHPadStateMap, llvm::WinEHFuncInfo::FuncletBaseStateMap, getCleanupRetUnwindDest(), getEHPadFromPredecessor(), llvm::WinEHFuncInfo::getLastStateNumber(), llvm::Value::getName(), llvm::Instruction::getParent(), llvm::BasicBlock::isEHPad(), LLVM_DEBUG, llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), and llvm::Value::users().
Referenced by llvm::calculateWinCXXEHStateNumbers().
calculateSEHStateNumbers()
static void calculateSEHStateNumbers (WinEHFuncInfo & FuncInfo, const Instruction * FirstNonPHI, int ParentState) static
Definition at line 339 of file WinEHPrepare.cpp.
References addSEHExcept(), addSEHFinally(), assert(), llvm::calculateSEHStateNumbers(), llvm::dbgs(), llvm::dyn_cast(), llvm::WinEHFuncInfo::EHPadStateMap, llvm::Filter, getCleanupRetUnwindDest(), getEHPadFromPredecessor(), llvm::Value::getName(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::BasicBlock::isEHPad(), llvm::Constant::isNullValue(), LLVM_DEBUG, llvm::predecessors(), llvm::report_fatal_error(), and llvm::Value::users().
calculateStateNumbersForInvokes()
static void calculateStateNumbersForInvokes (const Function * Fn, WinEHFuncInfo & FuncInfo) static
Definition at line 174 of file WinEHPrepare.cpp.
References assert(), llvm::colorEHFunclets(), llvm::dyn_cast(), llvm::WinEHFuncInfo::EHPadStateMap, F(), llvm::BasicBlock::front(), llvm::WinEHFuncInfo::FuncletBaseStateMap, getCleanupRetUnwindDest(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::WinEHFuncInfo::InvokeStateMap, and llvm_unreachable.
Referenced by llvm::calculateSEHStateNumbers(), and llvm::calculateWinCXXEHStateNumbers().
getCleanupRetUnwindDest()
static BasicBlock* getCleanupRetUnwindDest (const CleanupPadInst * CleanupPad) static
Definition at line 167 of file WinEHPrepare.cpp.
References llvm::Value::users().
Referenced by calculateCXXStateNumbers(), calculateSEHStateNumbers(), calculateStateNumbersForInvokes(), and isTopLevelPadForMSVC().
getEHPadFromPredecessor()
static const BasicBlock* getEHPadFromPredecessor (const BasicBlock * BB, Value * ParentPad) static
Definition at line 220 of file WinEHPrepare.cpp.
References assert(), llvm::BasicBlock::getTerminator(), and llvm::Instruction::isEHPad().
Referenced by calculateCXXStateNumbers(), and calculateSEHStateNumbers().
INITIALIZE_PASS()
INITIALIZE_PASS (WinEHPrepare , DEBUG_TYPE , "Prepare Windows exceptions" , false , false)
Definition at line 105 of file WinEHPrepare.cpp.
References llvm::classifyEHPersonality(), llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), llvm::Function::getPersonalityFn(), llvm::Function::hasPersonalityFn(), llvm::isScopedEHPersonality(), and runOnFunction().
isTopLevelPadForMSVC()
static bool isTopLevelPadForMSVC (const Instruction * EHPad) static
Definition at line 417 of file WinEHPrepare.cpp.
References getCleanupRetUnwindDest(), and llvm_unreachable.
Referenced by llvm::calculateSEHStateNumbers(), and llvm::calculateWinCXXEHStateNumbers().
Variable Documentation
DemoteCatchSwitchPHIOnlyOpt
cl::opt<bool> DemoteCatchSwitchPHIOnlyOpt("demote-catchswitch-only", cl::Hidden, cl::desc("Demote catchswitch BBs only (for wasm EH)"), cl::init(false)) static
DisableCleanups
cl::opt<bool> DisableCleanups("disable-cleanups", cl::Hidden, cl::desc("Do not remove implausible terminators or other similar cleanups"), cl::init(false)) static
DisableDemotion
cl::opt<bool> DisableDemotion("disable-demotion", cl::Hidden, cl::desc("Clone multicolor basic blocks but do not demote cross scopes"), cl::init(false)) static