LLVM: lib/Target/X86/X86AvoidStoreForwardingBlocks.cpp File Reference
X86AvoidStoreForwardingBlocks.cpp File Reference
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCInstrDesc.h"
Macros
#define DEBUG_TYPE "x86-avoid-SFB"
Functions
INITIALIZE_PASS_BEGIN (X86AvoidSFBPass, DEBUG_TYPE, "Machine code sinking", false, false) INITIALIZE_PASS_END(X86AvoidSFBPass
static bool isXMMLoadOpcode (unsigned Opcode)
static bool isYMMLoadOpcode (unsigned Opcode)
static bool isPotentialBlockedMemCpyLd (unsigned Opcode)
static bool isPotentialBlockedMemCpyPair (int LdOpcode, int StOpcode)
static bool isPotentialBlockingStoreInst (int Opcode, int LoadOpcode)
static unsigned getYMMtoXMMLoadOpcode (unsigned LoadOpcode)
static unsigned getYMMtoXMMStoreOpcode (unsigned StoreOpcode)
static int getAddrOffset (MachineInstr *MI)
static MachineOperand & getBaseOperand (MachineInstr *MI)
static MachineOperand & getDispOperand (MachineInstr *MI)
static bool isRelevantAddressingMode (MachineInstr *MI)
static SmallVector< MachineInstr *, 2 > findPotentialBlockers (MachineInstr *LoadInst)
static void updateKillStatus (MachineInstr *LoadInst, MachineInstr *StoreInst)
static bool hasSameBaseOpValue (MachineInstr *LoadInst, MachineInstr *StoreInst)
static bool isBlockingStore (int64_t LoadDispImm, unsigned LoadSize, int64_t StoreDispImm, unsigned StoreSize)
static void updateBlockingStoresDispSizeMap (DisplacementSizeMap &BlockingStoresDispSizeMap, int64_t DispImm, unsigned Size)
static void removeRedundantBlockingStores (DisplacementSizeMap &BlockingStoresDispSizeMap)
Variables
static cl::opt< bool > DisableX86AvoidStoreForwardBlocks ("x86-disable-avoid-SFB", cl::Hidden, cl::desc("X86: Disable Store Forwarding Blocks fixup."), cl::init(false))
static cl::opt< unsigned > X86AvoidSFBInspectionLimit ("x86-sfb-inspection-limit", cl::desc("X86: Number of instructions backward to " "inspect for store forwarding blocks."), cl::init(20), cl::Hidden)
DEBUG_TYPE
Machine code sinking
Machine code false
static const int MOV128SZ = 16
static const int MOV64SZ = 8
static const int MOV32SZ = 4
static const int MOV16SZ = 2
static const int MOV8SZ = 1
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-avoid-SFB"
Definition at line 54 of file X86AvoidStoreForwardingBlocks.cpp.
Function Documentation
findPotentialBlockers()
static SmallVector<MachineInstr *, 2> findPotentialBlockers (MachineInstr * LoadInst) static
Definition at line 338 of file X86AvoidStoreForwardingBlocks.cpp.
References add(), llvm::X86::AddrNumOperands, assert(), llvm::BuildMI(), llvm::MachineInstr::dump(), E, getBaseOperand(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), getYMMtoXMMLoadOpcode(), getYMMtoXMMStoreOpcode(), llvm::MachineBasicBlock::instr_begin(), llvm::MCInstrDesc::isCall(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), isYMMLoadOpcode(), LLVM_DEBUG, llvm::MachineInstr::memoperands_begin(), MI, MOV128SZ, MOV16SZ, MOV32SZ, MOV64SZ, MOV8SZ, MRI, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), llvm::MachineOperand::setIsKill(), Size, llvm::skipDebugInstructionsBackward(), TII, TRI, and X86AvoidSFBInspectionLimit.
Referenced by removeRedundantBlockingStores().
getAddrOffset()
static int getAddrOffset (MachineInstr * MI) static
Definition at line 290 of file X86AvoidStoreForwardingBlocks.cpp.
References assert(), llvm::MachineInstr::getDesc(), llvm::X86II::getMemoryOperandNo(), llvm::X86II::getOperandBias(), and llvm::MCInstrDesc::TSFlags.
Referenced by getBaseOperand(), getDispOperand(), and isRelevantAddressingMode().
getBaseOperand()
static MachineOperand& getBaseOperand (MachineInstr * MI) static
Definition at line 298 of file X86AvoidStoreForwardingBlocks.cpp.
References llvm::X86::AddrBaseReg, getAddrOffset(), and llvm::MachineInstr::getOperand().
Referenced by findPotentialBlockers(), hasSameBaseOpValue(), isRelevantAddressingMode(), and updateKillStatus().
getDispOperand()
static MachineOperand& getDispOperand (MachineInstr * MI) static
Definition at line 303 of file X86AvoidStoreForwardingBlocks.cpp.
References llvm::X86::AddrDisp, getAddrOffset(), and llvm::MachineInstr::getOperand().
Referenced by isRelevantAddressingMode(), removeRedundantBlockingStores(), and updateKillStatus().
getYMMtoXMMLoadOpcode()
static unsigned getYMMtoXMMLoadOpcode (unsigned LoadOpcode) static
Definition at line 232 of file X86AvoidStoreForwardingBlocks.cpp.
References llvm_unreachable.
Referenced by findPotentialBlockers().
getYMMtoXMMStoreOpcode()
static unsigned getYMMtoXMMStoreOpcode (unsigned StoreOpcode) static
Definition at line 261 of file X86AvoidStoreForwardingBlocks.cpp.
References llvm_unreachable.
Referenced by findPotentialBlockers().
hasSameBaseOpValue()
static bool hasSameBaseOpValue (MachineInstr * LoadInst, MachineInstr * StoreInst) static
Definition at line 617 of file X86AvoidStoreForwardingBlocks.cpp.
References getBaseOperand(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getReg(), and llvm::MachineOperand::isReg().
Referenced by removeRedundantBlockingStores().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86AvoidSFBPass , DEBUG_TYPE , "Machine code sinking" , false , false)
isBlockingStore()
static bool isBlockingStore (int64_t LoadDispImm, unsigned LoadSize, int64_t StoreDispImm, unsigned StoreSize) static
Definition at line 628 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by removeRedundantBlockingStores().
isPotentialBlockedMemCpyLd()
static bool isPotentialBlockedMemCpyLd (unsigned Opcode) static
Definition at line 152 of file X86AvoidStoreForwardingBlocks.cpp.
References isXMMLoadOpcode(), and isYMMLoadOpcode().
Referenced by updateKillStatus().
isPotentialBlockedMemCpyPair()
static bool isPotentialBlockedMemCpyPair (int LdOpcode, int StOpcode) static
Definition at line 156 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by updateKillStatus().
isPotentialBlockingStoreInst()
static bool isPotentialBlockingStoreInst (int Opcode, int LoadOpcode) static
Definition at line 208 of file X86AvoidStoreForwardingBlocks.cpp.
References isYMMLoadOpcode().
Referenced by removeRedundantBlockingStores().
isRelevantAddressingMode()
static bool isRelevantAddressingMode (MachineInstr * MI) static
Definition at line 311 of file X86AvoidStoreForwardingBlocks.cpp.
References llvm::X86::AddrIndexReg, llvm::X86::AddrScaleAmt, llvm::X86::AddrSegmentReg, getAddrOffset(), getBaseOperand(), getDispOperand(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by removeRedundantBlockingStores(), and updateKillStatus().
isXMMLoadOpcode()
static bool isXMMLoadOpcode (unsigned Opcode) static
Definition at line 132 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by isPotentialBlockedMemCpyLd().
isYMMLoadOpcode()
static bool isYMMLoadOpcode (unsigned Opcode) static
Definition at line 142 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers(), isPotentialBlockedMemCpyLd(), and isPotentialBlockingStoreInst().
removeRedundantBlockingStores()
static void removeRedundantBlockingStores (DisplacementSizeMap & BlockingStoresDispSizeMap) static
Definition at line 649 of file X86AvoidStoreForwardingBlocks.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::dbgs(), DisableX86AvoidStoreForwardBlocks, llvm::MachineInstr::dump(), findPotentialBlockers(), getDispOperand(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), hasSameBaseOpValue(), llvm::X86Subtarget::is64Bit(), isBlockingStore(), isPotentialBlockingStoreInst(), isRelevantAddressingMode(), LLVM_DEBUG, MRI, llvm::SmallVectorTemplateBase< T >::pop_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), TII, TRI, updateBlockingStoresDispSizeMap(), and updateKillStatus().
updateBlockingStoresDispSizeMap()
static void updateBlockingStoresDispSizeMap (DisplacementSizeMap & BlockingStoresDispSizeMap, int64_t DispImm, unsigned Size) static
Definition at line 636 of file X86AvoidStoreForwardingBlocks.cpp.
References Size.
Referenced by removeRedundantBlockingStores().
updateKillStatus()
static void updateKillStatus (MachineInstr * LoadInst, MachineInstr * StoreInst) static
Definition at line 498 of file X86AvoidStoreForwardingBlocks.cpp.
References assert(), llvm::MachineMemOperand::getAAInfo(), getBaseOperand(), getDispOperand(), llvm::MachineOperand::getImm(), llvm::MachineMemOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::MachineInstr::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::MachineMemOperand::getSize(), llvm::MachineMemOperand::getValue(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineOperand::isKill(), isPotentialBlockedMemCpyLd(), isPotentialBlockedMemCpyPair(), llvm::MachineOperand::isReg(), isRelevantAddressingMode(), llvm::MachineInstr::memoperands_begin(), MI, MRI, llvm::NoAlias, llvm::MachineOperand::setIsKill(), llvm::skipDebugInstructionsBackward(), TII, and TRI.
Referenced by removeRedundantBlockingStores().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 125 of file X86AvoidStoreForwardingBlocks.cpp.
DisableX86AvoidStoreForwardBlocks
cl::opt<bool> DisableX86AvoidStoreForwardBlocks("x86-disable-avoid-SFB", cl::Hidden, cl::desc("X86: Disable Store Forwarding Blocks fixup."), cl::init(false)) static
Referenced by removeRedundantBlockingStores().
false
Machine code false
Definition at line 125 of file X86AvoidStoreForwardingBlocks.cpp.
MOV128SZ
const int MOV128SZ = 16 static
Definition at line 226 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers().
MOV16SZ
const int MOV16SZ = 2 static
Definition at line 229 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers().
MOV32SZ
const int MOV32SZ = 4 static
Definition at line 228 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers().
MOV64SZ
const int MOV64SZ = 8 static
Definition at line 227 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers().
MOV8SZ
const int MOV8SZ = 1 static
Definition at line 230 of file X86AvoidStoreForwardingBlocks.cpp.
Referenced by findPotentialBlockers().
sinking
Machine code sinking
Definition at line 125 of file X86AvoidStoreForwardingBlocks.cpp.
X86AvoidSFBInspectionLimit
cl::opt<unsigned> X86AvoidSFBInspectionLimit("x86-sfb-inspection-limit", cl::desc("X86: Number of instructions backward to " "inspect for store forwarding blocks."), cl::init(20), cl::Hidden) static
Referenced by findPotentialBlockers().