LLVM: lib/Target/X86/X86AvoidTrailingCall.cpp File Reference
X86AvoidTrailingCall.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
Macros
#define DEBUG_TYPE "x86-avoid-trailing-call"
Functions
static bool isRealInstruction (MachineInstr &MI)
static bool isCallInstruction (const MachineInstr &MI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-avoid-trailing-call"
Definition at line 21 of file X86AvoidTrailingCall.cpp.
Function Documentation
isCallInstruction()
static bool isCallInstruction (const MachineInstr & MI) static
Definition at line 56 of file X86AvoidTrailingCall.cpp.
References assert(), llvm::BuildMI(), llvm::dbgs(), llvm::find_if(), llvm::X86Subtarget::getInstrInfo(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MachineInstrBundleIterator< Ty, IsReverse >::getReverse(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isCall(), llvm::MachineBasicBlock::isEHFuncletEntry(), isRealInstruction(), llvm::MachineInstr::isReturn(), llvm::X86Subtarget::isTargetWin64(), LLVM_DEBUG, llvm::make_range(), llvm::reverse(), and TII.
isRealInstruction()
static bool isRealInstruction (MachineInstr & MI) static
Definition at line 51 of file X86AvoidTrailingCall.cpp.
References llvm::MachineInstr::isMetaInstruction(), and llvm::MachineInstr::isPseudo().
Referenced by isCallInstruction().