LLVM: lib/Target/X86/X86DomainReassignment.cpp File Reference
X86DomainReassignment.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Printable.h"
#include <bitset>
Macros
#define DEBUG_TYPE "x86-domain-reassignment"
Enumerations
enum RegDomain
Functions
STATISTIC (NumClosuresConverted, "Number of closures converted by the pass")
static bool usedAsAddr (const MachineInstr &MI, unsigned Reg, const TargetInstrInfo *TII)
INITIALIZE_PASS (X86DomainReassignment, "x86-domain-reassignment", "X86 Domain Reassignment Pass", false, false) FunctionPass *llvm
Returns an instance of the Domain Reassignment pass.
Variables
static cl::opt< bool > DisableX86DomainReassignment ("disable-x86-domain-reassignment", cl::Hidden, cl::desc("X86: Disable Virtual Register Reassignment."), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-domain-reassignment"
Definition at line 33 of file X86DomainReassignment.cpp.
Enumeration Type Documentation
RegDomain
enum RegDomain
Definition at line 42 of file X86DomainReassignment.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (X86DomainReassignment , "x86-domain-reassignment" , "X86 Domain Reassignment Pass" , false , false)
Returns an instance of the Domain Reassignment pass.
Definition at line 791 of file X86DomainReassignment.cpp.
STATISTIC()
STATISTIC (NumClosuresConverted , "Number of closures converted by the pass")
usedAsAddr()
static bool usedAsAddr (const MachineInstr & MI, unsigned Reg, const TargetInstrInfo * TII) static
Returns
true when Reg is used as part of an address calculation in MI.
Definition at line 526 of file X86DomainReassignment.cpp.
References llvm::X86::AddrNumOperands, assert(), C, llvm::dbgs(), DefMI, llvm::DeleteContainerSeconds(), DisableX86DomainReassignment, llvm::SmallVectorBase::empty(), From, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getFunction(), llvm::X86II::getMemoryOperandNo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::X86II::getOperandBias(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::Register::index2VirtReg(), llvm::Register::isVirtualRegister(), LLVM_DEBUG, llvm::MachineInstr::mayLoadOrStore(), MRI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineFunction::print(), Reg, TII, llvm::MCInstrDesc::TSFlags, and UseMI.
Variable Documentation
DisableX86DomainReassignment
cl::opt<bool> DisableX86DomainReassignment("disable-x86-domain-reassignment", cl::Hidden, cl::desc("X86: Disable Virtual Register Reassignment."), cl::init(false)) static
Referenced by usedAsAddr().