LLVM: lib/Target/X86/MCTargetDesc/X86ELFObjectWriter.cpp File Reference
X86ELFObjectWriter.cpp File Reference
#include "MCTargetDesc/X86FixupKinds.h"
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <cstdint>
Enumerations
enum X86_64RelType {
RT64_NONE, RT64_64, RT64_32, RT64_32S,
RT64_16, RT64_8
}
enum X86_32RelType { RT32_NONE, RT32_32, RT32_16, RT32_8 }
Functions
static X86_64RelType getType64 (MCFixupKind Kind, MCSymbolRefExpr::VariantKind &Modifier, bool &IsPCRel)
static void checkIs32 (MCContext &Ctx, SMLoc Loc, X86_64RelType Type)
static unsigned getRelocType64 (MCContext &Ctx, SMLoc Loc, MCSymbolRefExpr::VariantKind Modifier, X86_64RelType Type, bool IsPCRel, MCFixupKind Kind)
static X86_32RelType getType32 (X86_64RelType T)
static unsigned getRelocType32 (MCContext &Ctx, MCSymbolRefExpr::VariantKind Modifier, X86_32RelType Type, bool IsPCRel, MCFixupKind Kind)
Enumeration Type Documentation
X86_32RelType
enum X86_32RelType
Enumerator
RT32_NONE
RT32_32
RT32_16
RT32_8
Definition at line 218 of file X86ELFObjectWriter.cpp.
X86_64RelType
enum X86_64RelType
Enumerator
RT64_NONE
RT64_64
RT64_32
RT64_32S
RT64_16
RT64_8
Definition at line 47 of file X86ELFObjectWriter.cpp.
Function Documentation
checkIs32()
static void checkIs32 (MCContext & Ctx, SMLoc Loc, X86_64RelType Type) static
Definition at line 91 of file X86ELFObjectWriter.cpp.
References llvm::MCContext::reportError(), and RT64_32.
Referenced by getRelocType64().
getRelocType32()
static unsigned getRelocType32 (MCContext & Ctx, MCSymbolRefExpr::VariantKind Modifier, X86_32RelType Type, bool IsPCRel, MCFixupKind Kind) static
Definition at line 237 of file X86ELFObjectWriter.cpp.
References assert(), llvm::MCAsmInfo::canRelaxRelocations(), llvm::ELF::EM_386, llvm::ELF::EM_IAMCU, llvm::ELF::EM_X86_64, Fixup, llvm::MCValue::getAccessVariant(), llvm::MCContext::getAsmInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getLoc(), getRelocType(), getRelocType64(), getType32(), getType64(), llvm_unreachable, llvm::X86::reloc_signed_4byte_relax, RT32_16, RT32_32, RT32_8, RT32_NONE, llvm::MCSymbolRefExpr::VK_DTPOFF, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_GOTNTPOFF, llvm::MCSymbolRefExpr::VK_GOTOFF, llvm::MCSymbolRefExpr::VK_GOTTPOFF, llvm::MCSymbolRefExpr::VK_INDNTPOFF, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_NTPOFF, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_TLSCALL, llvm::MCSymbolRefExpr::VK_TLSDESC, llvm::MCSymbolRefExpr::VK_TLSGD, llvm::MCSymbolRefExpr::VK_TLSLDM, llvm::MCSymbolRefExpr::VK_TPOFF, and llvm::MCSymbolRefExpr::VK_X86_ABS8.
getRelocType64()
static unsigned getRelocType64 (MCContext & Ctx, SMLoc Loc, MCSymbolRefExpr::VariantKind Modifier, X86_64RelType Type, bool IsPCRel, MCFixupKind Kind) static
Definition at line 97 of file X86ELFObjectWriter.cpp.
References assert(), llvm::MCAsmInfo::canRelaxRelocations(), checkIs32(), llvm::MCContext::getAsmInfo(), llvm_unreachable, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_riprel_4byte_relax, llvm::X86::reloc_riprel_4byte_relax_rex, RT64_16, RT64_32, RT64_32S, RT64_64, RT64_8, RT64_NONE, llvm::MCSymbolRefExpr::VK_DTPOFF, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_GOTOFF, llvm::MCSymbolRefExpr::VK_GOTPCREL, llvm::MCSymbolRefExpr::VK_GOTTPOFF, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_SIZE, llvm::MCSymbolRefExpr::VK_TLSCALL, llvm::MCSymbolRefExpr::VK_TLSDESC, llvm::MCSymbolRefExpr::VK_TLSGD, llvm::MCSymbolRefExpr::VK_TLSLD, llvm::MCSymbolRefExpr::VK_TPOFF, and llvm::MCSymbolRefExpr::VK_X86_ABS8.
Referenced by getRelocType32().
getType32()
static X86_32RelType getType32 (X86_64RelType T) static
Definition at line 220 of file X86ELFObjectWriter.cpp.
References llvm_unreachable, RT32_16, RT32_32, RT32_8, RT32_NONE, RT64_16, RT64_32, RT64_32S, RT64_64, RT64_8, and RT64_NONE.
Referenced by getRelocType32().
getType64()
static X86_64RelType getType64 (MCFixupKind Kind, MCSymbolRefExpr::VariantKind & Modifier, bool & IsPCRel) static
Definition at line 49 of file X86ELFObjectWriter.cpp.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_NONE, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm_unreachable, llvm::X86::reloc_branch_4byte_pcrel, llvm::X86::reloc_global_offset_table, llvm::X86::reloc_global_offset_table8, llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_riprel_4byte_relax, llvm::X86::reloc_riprel_4byte_relax_rex, llvm::X86::reloc_signed_4byte, llvm::X86::reloc_signed_4byte_relax, RT64_16, RT64_32, RT64_32S, RT64_64, RT64_8, RT64_NONE, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_None, and llvm::MCSymbolRefExpr::VK_PLT.
Referenced by getRelocType32().