LLVM: lib/Target/X86/X86ExpandPseudo.cpp File Reference
X86ExpandPseudo.cpp File Reference
#include "X86.h"
#include "X86FrameLowering.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/GlobalValue.h"
Macros
#define DEBUG_TYPE "x86-pseudo"
#define X86_EXPAND_PSEUDO_NAME "X86 pseudo instruction expansion pass"
Functions
INITIALIZE_PASS (X86ExpandPseudo, DEBUG_TYPE, X86_EXPAND_PSEUDO_NAME, false, false) void X86ExpandPseudo
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-pseudo"
Definition at line 28 of file X86ExpandPseudo.cpp.
X86_EXPAND_PSEUDO_NAME
#define X86_EXPAND_PSEUDO_NAME "X86 pseudo instruction expansion pass"
Definition at line 29 of file X86ExpandPseudo.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (X86ExpandPseudo , DEBUG_TYPE , X86_EXPAND_PSEUDO_NAME , false , false)
Definition at line 72 of file X86ExpandPseudo.cpp.
References add(), llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::X86::AddrNumOperands, llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::classifyEHPersonality(), llvm::X86::COND_B, llvm::X86::COND_E, llvm::MachineInstr::copyImplicitOps(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::RegState::Define, E, llvm::N86::EBX, llvm::N86::ECX, llvm::ISD::EH_RETURN, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), FirstTarget, llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::Function::getPersonalityFn(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineFunction::hasWinCFI(), I, llvm::MachineFunction::insert(), llvm::X86ISD::IRET, llvm::isAsynchronousEHPersonality(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::isMem(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::isUInt< 16 >(), llvm_unreachable, MI, Modified, llvm::MachineFunction::moveCallSiteInfo(), P, llvm::ARCISD::RET, llvm::MachineOperand::setIsKill(), TII, and TRI.