LLVM: lib/Target/X86/X86FlagsCopyLowering.cpp File Reference
X86FlagsCopyLowering.cpp File Reference
Lowers COPY nodes of EFLAGS by directly extracting and preserving individual flag bits.
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/SparseBitVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineSSAUpdater.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCSchedule.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <iterator>
#include <utility>
Macros
#define PASS_KEY "x86-flags-copy-lowering"
#define DEBUG_TYPE PASS_KEY
#define LLVM_EXPAND_INSTR_SIZES(MNEMONIC, SUFFIX)
#define LLVM_EXPAND_ADC_SBB_INSTR(MNEMONIC)
Enumerations
enum FlagArithMnemonic
An enumeration of the arithmetic instruction mnemonics which have interesting flag semantics.
Functions
STATISTIC (NumCopiesEliminated, "Number of copies of EFLAGS eliminated")
STATISTIC (NumSetCCsInserted, "Number of setCC instructions inserted")
STATISTIC (NumTestsInserted, "Number of test instructions inserted")
STATISTIC (NumAddsInserted, "Number of adds instructions inserted")
INITIALIZE_PASS_BEGIN (X86FlagsCopyLoweringPass, DEBUG_TYPE, "X86 EFLAGS copy lowering", false, false) INITIALIZE_PASS_END(X86FlagsCopyLoweringPass
static FlagArithMnemonic getMnemonicFromOpcode (unsigned Opcode)
static MachineBasicBlock & splitBlock (MachineBasicBlock &MBB, MachineInstr &SplitI, const X86InstrInfo &TII)
static X86::CondCode getCondFromFCMOV (unsigned Opcode)
Variables
DEBUG_TYPE
X86 EFLAGS copy lowering
X86 EFLAGS copy false
Detailed Description
Lowers COPY nodes of EFLAGS by directly extracting and preserving individual flag bits.
We have to do this by carefully analyzing and rewriting the usage of the copied EFLAGS register because there is no general way to rematerialize the entire EFLAGS register safely and efficiently. Using popf both forces dynamic stack adjustment and can create correctness issues due to IF, TF, and other non-status flags being overwritten. Using sequences involving SAHF don't work on all x86 processors and are often quite slow compared to directly testing a single status preserved in its own GPR.
Definition in file X86FlagsCopyLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE PASS_KEY
Definition at line 66 of file X86FlagsCopyLowering.cpp.
LLVM_EXPAND_ADC_SBB_INSTR
#define LLVM_EXPAND_ADC_SBB_INSTR (MNEMONIC)
Value:
LLVM_EXPAND_INSTR_SIZES(MNEMONIC, rr)                                        \
  LLVM_EXPAND_INSTR_SIZES(MNEMONIC, rr_REV)                                    \
  LLVM_EXPAND_INSTR_SIZES(MNEMONIC, rm)                                        \
  LLVM_EXPAND_INSTR_SIZES(MNEMONIC, mr)                                        \
  case X86::MNEMONIC##8ri:                                                     \
  case X86::MNEMONIC##16ri8:                                                   \
  case X86::MNEMONIC##32ri8:                                                   \
  case X86::MNEMONIC##64ri8:                                                   \
  case X86::MNEMONIC##16ri:                                                    \
  case X86::MNEMONIC##32ri:                                                    \
  case X86::MNEMONIC##64ri32:                                                  \
  case X86::MNEMONIC##8mi:                                                     \
  case X86::MNEMONIC##16mi8:                                                   \
  case X86::MNEMONIC##32mi8:                                                   \
  case X86::MNEMONIC##64mi8:                                                   \
  case X86::MNEMONIC##16mi:                                                    \
  case X86::MNEMONIC##32mi:                                                    \
  case X86::MNEMONIC##64mi32:                                                  \
  case X86::MNEMONIC##8i8:                                                     \
  case X86::MNEMONIC##16i16:                                                   \
  case X86::MNEMONIC##32i32:                                                   \
  case X86::MNEMONIC##64i32:
Referenced by getMnemonicFromOpcode().
LLVM_EXPAND_INSTR_SIZES
#define LLVM_EXPAND_INSTR_SIZES (MNEMONIC, SUFFIX)
Value:
case X86::MNEMONIC##8##SUFFIX:                                               \
  case X86::MNEMONIC##16##SUFFIX:                                              \
  case X86::MNEMONIC##32##SUFFIX:                                              \
  case X86::MNEMONIC##64##SUFFIX:
Referenced by getMnemonicFromOpcode().
PASS_KEY
#define PASS_KEY "x86-flags-copy-lowering"
Definition at line 65 of file X86FlagsCopyLowering.cpp.
Enumeration Type Documentation
FlagArithMnemonic
enum FlagArithMnemonic strong
An enumeration of the arithmetic instruction mnemonics which have interesting flag semantics.
We can map instruction opcodes into these mnemonics to make it easy to dispatch with specific functionality.
Definition at line 161 of file X86FlagsCopyLowering.cpp.
Function Documentation
getCondFromFCMOV()
static X86::CondCode getCondFromFCMOV (unsigned Opcode) static
Definition at line 341 of file X86FlagsCopyLowering.cpp.
References assert(), llvm::MachineFunction::begin(), Cleanup(), llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_INVALID, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_P, Copies, llvm::dbgs(), llvm::MachineFunction::end(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), LLVM_DEBUG, llvm::make_scope_exit(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), TII, and TRI.
getMnemonicFromOpcode()
static FlagArithMnemonic getMnemonicFromOpcode (unsigned Opcode) static
Definition at line 171 of file X86FlagsCopyLowering.cpp.
References llvm::AArch64ISD::ADC, LLVM_EXPAND_ADC_SBB_INSTR, LLVM_EXPAND_INSTR_SIZES, r1(), llvm::report_fatal_error(), and llvm::X86ISD::SBB.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86FlagsCopyLoweringPass , DEBUG_TYPE , "X86 EFLAGS copy lowering" , false , false)
splitBlock()
static MachineBasicBlock& splitBlock (MachineBasicBlock & MBB, MachineInstr & SplitI, const X86InstrInfo & TII) static
Definition at line 241 of file X86FlagsCopyLowering.cpp.
References llvm::any_of(), assert(), llvm::X86::COND_INVALID, llvm::MachineBasicBlock::copySuccessor(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineOperand::CreateMBB(), llvm::MachineBasicBlock::end(), llvm::X86::getCondFromBranch(), llvm::MachineBasicBlock::getFallThrough(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::insert(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBranch(), llvm::MachineOperand::isMBB(), llvm::MachineBasicBlock::isSuccessor(), MI, llvm::MachineBasicBlock::normalizeSuccProbs(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::MachineOperand::setMBB(), SI, llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and llvm::MachineBasicBlock::successors().
STATISTIC() [1/4]
STATISTIC (NumCopiesEliminated , "Number of copies of EFLAGS eliminated")
STATISTIC() [2/4]
STATISTIC (NumSetCCsInserted , "Number of setCC instructions inserted")
STATISTIC() [3/4]
STATISTIC (NumTestsInserted , "Number of test instructions inserted")
STATISTIC() [4/4]
STATISTIC (NumAddsInserted , "Number of adds instructions inserted")
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 141 of file X86FlagsCopyLowering.cpp.
false
X86 EFLAGS copy false
Definition at line 141 of file X86FlagsCopyLowering.cpp.
lowering
X86 EFLAGS copy lowering
Definition at line 141 of file X86FlagsCopyLowering.cpp.