LLVM: lib/Target/X86/X86ISelLowering.cpp File Reference
X86ISelLowering.cpp File Reference
#include "X86ISelLowering.h"
#include "Utils/X86ShuffleDecode.h"
#include "X86CallingConv.h"
#include "X86FrameLowering.h"
#include "X86InstrBuilder.h"
#include "X86IntrinsicsInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86TargetMachine.h"
#include "X86TargetObjectFile.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/EHPersonalities.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <bitset>
#include <cctype>
#include <numeric>
Namespaces
llvm
This class represents lattice values for constants.
llvm::X86
Define some predicates that are used for node matching.
Macros
#define DEBUG_TYPE "x86-isel"
Enumerations
enum StructReturnType { NotStructReturn, RegStructReturn, StackStructReturn }
CallIsStructReturn - Determines whether a call uses struct return semantics.
enum ShrinkMode { ShrinkMode::MULS8, ShrinkMode::MULU8, ShrinkMode::MULS16, ShrinkMode::MULU16 }
Different mul shrinking modes.
Functions
STATISTIC (NumTailCalls, "Number of tail calls")
static void errorUnsupported (SelectionDAG &DAG, const SDLoc &dl, const char *Msg)
Call this when the user attempts to do something unsupported, like returning a double without SSE2 enabled on x86_64.
static void getMaxByValAlign (Type *Ty, unsigned &MaxAlign)
Helper for getByValTypeAlignment to determine the desired ByVal argument alignment.
static bool hasStackGuardSlotTLS (const Triple &TargetTriple)
static Constant * SegmentOffset (IRBuilder<> &IRB, unsigned Offset, unsigned AddressSpace)
static SDValue lowerMasksToReg (const SDValue &ValArg, const EVT &ValLoc, const SDLoc &Dl, SelectionDAG &DAG)
Lowers masks values (v*i1) to the local register values.
static void Passv64i1ArgInRegs (const SDLoc &Dl, SelectionDAG &DAG, SDValue &Arg, SmallVectorImpl< std::pair< unsigned, SDValue >> &RegsToPass, CCValAssign &VA, CCValAssign &NextVA, const X86Subtarget &Subtarget)
Breaks v64i1 value into two registers and adds the new node to the DAG.
static SDValue getv64i1Argument (CCValAssign &VA, CCValAssign &NextVA, SDValue &Root, SelectionDAG &DAG, const SDLoc &Dl, const X86Subtarget &Subtarget, SDValue *InFlag=nullptr)
Reads two 32 bit registers and creates a 64 bit mask value.
static SDValue lowerRegToMasks (const SDValue &ValArg, const EVT &ValVT, const EVT &ValLoc, const SDLoc &Dl, SelectionDAG &DAG)
The function will lower a register of various sizes (8/16/32/64) to a mask value of the expected size (v8i1/v16i1/v32i1/v64i1)
static StructReturnType callIsStructReturn (ArrayRef< ISD::OutputArg > Outs, bool IsMCU)
static StructReturnType argsAreStructReturn (ArrayRef< ISD::InputArg > Ins, bool IsMCU)
Determines whether a function uses struct return semantics.
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG &DAG, const SDLoc &dl)
Make a copy of an aggregate at address specified by "Src" to address "Dst" with size and alignment information specified by the specific parameter attribute.
static bool canGuaranteeTCO (CallingConv::ID CC)
Return true if the calling convention is one that we can guarantee TCO for.
static bool mayTailCallThisCC (CallingConv::ID CC)
Return true if we might ever do TCO for calls with this calling convention.
static bool shouldGuaranteeTCO (CallingConv::ID CC, bool GuaranteedTailCallOpt)
Return true if the function is being made into a tailcall target by changing its ABI.
static ArrayRef< MCPhysReg > get64BitArgumentGPRs (CallingConv::ID CallConv, const X86Subtarget &Subtarget)
static ArrayRef< MCPhysReg > get64BitArgumentXMMs (MachineFunction &MF, CallingConv::ID CallConv, const X86Subtarget &Subtarget)
static bool isSortedByValueNo (ArrayRef< CCValAssign > ArgLocs)
static SDValue EmitTailCallStoreRetAddr (SelectionDAG &DAG, MachineFunction &MF, SDValue Chain, SDValue RetAddrFrIdx, EVT PtrVT, unsigned SlotSize, int FPDiff, const SDLoc &dl)
Emit a store of the return address if tail call optimization is performed and it is required (FPDiff!=0).
static SDValue getMOVL (SelectionDAG &DAG, const SDLoc &dl, MVT VT, SDValue V1, SDValue V2)
Returns a vector_shuffle mask for an movs{s|d}, movd operation of specified width.
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo &MFI, const MachineRegisterInfo *MRI, const X86InstrInfo *TII, const CCValAssign &VA)
Return true if the given stack call argument is already available in the same position (relatively) of the caller's incoming argument stack.
static bool MayFoldLoad (SDValue Op)
static bool MayFoldIntoStore (SDValue Op)
static bool MayFoldIntoZeroExtend (SDValue Op)
static bool isTargetShuffle (unsigned Opcode)
static bool isTargetShuffleVariableMask (unsigned Opcode)
static bool isX86CCSigned (unsigned X86CC)
Return true if the condition is an signed comparison operation.
static X86::CondCode TranslateIntegerX86CC (ISD::CondCode SetCCOpcode)
static X86::CondCode TranslateX86CC (ISD::CondCode SetCCOpcode, const SDLoc &DL, bool isFP, SDValue &LHS, SDValue &RHS, SelectionDAG &DAG)
Do a one-to-one translation of a ISD::CondCode to the X86-specific condition code, returning the condition code and the LHS/RHS of the comparison to make.
static bool hasFPCMov (unsigned X86CC)
Is there a floating point cmov for the specific X86 condition code? Current x86 isa includes the following FP cmov instructions: fcmovb, fcomvbe, fcomve, fcmovu, fcmovae, fcmova, fcmovne, fcmovnu.
static bool isUndefOrEqual (int Val, int CmpVal)
Val is the undef sentinel value or equal to the specified value.
static bool isUndefOrZero (int Val)
Val is either the undef or zero sentinel value.
static bool isUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size)
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size is the undef sentinel value.
static bool isUndefLowerHalf (ArrayRef< int > Mask)
Return true if the mask creates a vector whose lower half is undefined.
static bool isUndefUpperHalf (ArrayRef< int > Mask)
Return true if the mask creates a vector whose upper half is undefined.
static bool isInRange (int Val, int Low, int Hi)
Return true if Val falls within the specified range (L, H].
static bool isAnyInRange (ArrayRef< int > Mask, int Low, int Hi)
Return true if the value of any element in Mask falls within the specified range (L, H].
static bool isUndefOrInRange (int Val, int Low, int Hi)
Return true if Val is undef or if its value falls within the specified range (L, H].
static bool isUndefOrInRange (ArrayRef< int > Mask, int Low, int Hi)
Return true if every element in Mask is undef or if its value falls within the specified range (L, H].
static bool isUndefOrZeroOrInRange (int Val, int Low, int Hi)
Return true if Val is undef, zero or if its value falls within the specified range (L, H].
static bool isUndefOrZeroOrInRange (ArrayRef< int > Mask, int Low, int Hi)
Return true if every element in Mask is undef, zero or if its value falls within the specified range (L, H].
static bool isSequentialOrUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low, int Step=1)
Return true if every element in Mask, beginning from position Pos and ending in Pos + Size, falls within the specified sequence (Low, Low + Step, ..., Low + (Size - 1) * Step) or is undef.
static bool isSequentialOrUndefOrZeroInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low, int Step=1)
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size, falls within the specified sequential range (Low, Low+Size], or is undef or is zero.
static bool isUndefOrZeroInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size)
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size is undef or is zero.
static bool canWidenShuffleElements (ArrayRef< int > Mask, SmallVectorImpl< int > &WidenedMask)
Helper function to test whether a shuffle mask could be simplified by widening the elements being shuffled.
static bool canWidenShuffleElements (ArrayRef< int > Mask, const APInt &Zeroable, bool V2IsZero, SmallVectorImpl< int > &WidenedMask)
static bool canWidenShuffleElements (ArrayRef< int > Mask)
static SDValue getConstVector (ArrayRef< int > Values, MVT VT, SelectionDAG &DAG, const SDLoc &dl, bool IsMask=false)
static SDValue getConstVector (ArrayRef< APInt > Bits, APInt &Undefs, MVT VT, SelectionDAG &DAG, const SDLoc &dl)
static SDValue getZeroVector (MVT VT, const X86Subtarget &Subtarget, SelectionDAG &DAG, const SDLoc &dl)
Returns a vector of specified type with all zero elements.
static SDValue extractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &dl, unsigned vectorWidth)
static SDValue extract128BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &dl)
Generate a DAG to grab 128-bits from a vector > 128 bits.
static SDValue extract256BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &dl)
Generate a DAG to grab 256-bits from a 512-bit vector.
static SDValue insertSubVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &dl, unsigned vectorWidth)
static SDValue insert128BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &dl)
Generate a DAG to put 128-bits into a vector > 128 bits.
static SDValue widenSubVector (MVT VT, SDValue Vec, bool ZeroNewElements, const X86Subtarget &Subtarget, SelectionDAG &DAG, const SDLoc &dl)
Widen a vector to a larger size with the same scalar type, with the new elements either zero or undef.
static SDValue widenSubVector (SDValue Vec, bool ZeroNewElements, const X86Subtarget &Subtarget, SelectionDAG &DAG, const SDLoc &dl, unsigned WideSizeInBits)
Widen a vector to a larger size with the same scalar type, with the new elements either zero or undef.
static bool collectConcatOps (SDNode *N, SmallVectorImpl< SDValue > &Ops)
template<typename F >
SDValue SplitOpsAndApply (SelectionDAG &DAG, const X86Subtarget &Subtarget, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, F Builder, bool CheckBWI=true)
static SDValue insert1BitVector (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Insert i1-subvector to i1-vector.
static SDValue concatSubVectors (SDValue V1, SDValue V2, SelectionDAG &DAG, const SDLoc &dl)
static SDValue getOnesVector (EVT VT, SelectionDAG &DAG, const SDLoc &dl)
Returns a vector of specified type with all bits set.
static unsigned getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode)
static SDValue getExtendInVec (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue In, SelectionDAG &DAG)
static SDValue IsNOT (SDValue V, SelectionDAG &DAG)
static SDValue getUnpackl (SelectionDAG &DAG, const SDLoc &dl, MVT VT, SDValue V1, SDValue V2)
Returns a vector_shuffle node for an unpackl operation.
static SDValue getUnpackh (SelectionDAG &DAG, const SDLoc &dl, MVT VT, SDValue V1, SDValue V2)
Returns a vector_shuffle node for an unpackh operation.
static SDValue getShuffleVectorZeroOrUndef (SDValue V2, int Idx, bool IsZero, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Return a vector_shuffle of the specified vector of zero or undef vector.
static const Constant * getTargetConstantFromNode (LoadSDNode *Load)
static const Constant * getTargetConstantFromNode (SDValue Op)
static bool getTargetConstantBitsFromNode (SDValue Op, unsigned EltSizeInBits, APInt &UndefElts, SmallVectorImpl< APInt > &EltBits, bool AllowWholeUndefs=true, bool AllowPartialUndefs=true)
bool llvm::X86::isConstantSplat (SDValue Op, APInt &SplatVal)
If Op is a constant whose elements are all the same constant or undefined, return true and return the constant value in SplatVal.
static bool getTargetShuffleMaskIndices (SDValue MaskNode, unsigned MaskEltSizeInBits, SmallVectorImpl< uint64_t > &RawMask, APInt &UndefElts)
static void createPackShuffleMask (MVT VT, SmallVectorImpl< int > &Mask, bool Unary)
Create a shuffle mask that matches the PACKSS/PACKUS truncation.
static void getPackDemandedElts (EVT VT, const APInt &DemandedElts, APInt &DemandedLHS, APInt &DemandedRHS)
static void getHorizDemandedElts (EVT VT, const APInt &DemandedElts, APInt &DemandedLHS, APInt &DemandedRHS)
static bool getTargetShuffleMask (SDNode *N, MVT VT, bool AllowSentinelZero, SmallVectorImpl< SDValue > &Ops, SmallVectorImpl< int > &Mask, bool &IsUnary)
Calculates the shuffle mask corresponding to the target-specific opcode.
static void computeZeroableShuffleElements (ArrayRef< int > Mask, SDValue V1, SDValue V2, APInt &KnownUndef, APInt &KnownZero)
Compute whether each element of a shuffle is zeroable.
static bool getTargetShuffleAndZeroables (SDValue N, SmallVectorImpl< int > &Mask, SmallVectorImpl< SDValue > &Ops, APInt &KnownUndef, APInt &KnownZero)
Decode a target shuffle mask and inputs and see if any values are known to be undef or zero from their inputs.
static void resolveTargetShuffleFromZeroables (SmallVectorImpl< int > &Mask, const APInt &KnownUndef, const APInt &KnownZero, bool ResolveKnownZeros=true)
static void resolveZeroablesFromTargetShuffle (const SmallVectorImpl< int > &Mask, APInt &KnownUndef, APInt &KnownZero)
static bool getTargetShuffleInputs (SDValue Op, SmallVectorImpl< SDValue > &Inputs, SmallVectorImpl< int > &Mask, SelectionDAG &DAG, unsigned Depth, bool ResolveKnownElts)
static bool getFauxShuffleMask (SDValue N, const APInt &DemandedElts, SmallVectorImpl< int > &Mask, SmallVectorImpl< SDValue > &Ops, SelectionDAG &DAG, unsigned Depth, bool ResolveKnownElts)
static void resolveTargetShuffleInputsAndMask (SmallVectorImpl< SDValue > &Inputs, SmallVectorImpl< int > &Mask)
Removes unused/repeated shuffle source inputs and adjusts the shuffle mask.
static bool getTargetShuffleInputs (SDValue Op, const APInt &DemandedElts, SmallVectorImpl< SDValue > &Inputs, SmallVectorImpl< int > &Mask, APInt &KnownUndef, APInt &KnownZero, SelectionDAG &DAG, unsigned Depth, bool ResolveKnownElts)
Calls getTargetShuffleAndZeroables to resolve a target shuffle mask's inputs and then sets the SM_SentinelUndef and SM_SentinelZero values.
static SDValue getShuffleScalarElt (SDNode *N, unsigned Index, SelectionDAG &DAG, unsigned Depth)
Returns the scalar element that will make up the ith element of the result of the vector shuffle.
static SDValue LowerBuildVectorAsInsert (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerBuildVectorv16i8 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Custom lower build_vector of v16i8.
static SDValue LowerBuildVectorv8i16 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Custom lower build_vector of v8i16.
static SDValue LowerBuildVectorv4x32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Custom lower build_vector of v4i32 or v4f32.
static SDValue getVShift (bool isLeft, EVT VT, SDValue SrcOp, unsigned NumBits, SelectionDAG &DAG, const TargetLowering &TLI, const SDLoc &dl)
Return a vector logical shift node.
static SDValue LowerAsSplatVectorLoad (SDValue SrcOp, MVT VT, const SDLoc &dl, SelectionDAG &DAG)
static bool findEltLoadSrc (SDValue Elt, LoadSDNode *&Ld, int64_t &ByteOffset)
static SDValue EltsFromConsecutiveLoads (EVT VT, ArrayRef< SDValue > Elts, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget, bool isAfterLegalize)
Given the initializing elements 'Elts' of a vector of type 'VT', see if the elements can be replaced by a single large load which has the same value as a build_vector or insert_subvector whose loaded operands are 'Elts'.
static SDValue combineToConsecutiveLoads (EVT VT, SDNode *N, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget, bool isAfterLegalize)
static Constant * getConstantVector (MVT VT, const APInt &SplatValue, unsigned SplatBitSize, LLVMContext &C)
static bool isFoldableUseOfShuffle (SDNode *N)
static SDValue isSplatZeroExtended (const BuildVectorSDNode *Op, unsigned &NumElt, MVT &EltType)
static SDValue lowerBuildVectorAsBroadcast (BuildVectorSDNode *BVOp, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Attempt to use the vbroadcast instruction to generate a splat value from a splat BUILD_VECTOR which uses: a.
static int getUnderlyingExtractedFromVec (SDValue &ExtractedFromVec, SDValue ExtIdx)
For an EXTRACT_VECTOR_ELT with a constant index return the real underlying vector and index.
static SDValue buildFromShuffleMostly (SDValue Op, SelectionDAG &DAG)
static SDValue ConvertI1VectorToInteger (SDValue Op, SelectionDAG &DAG)
static SDValue LowerBUILD_VECTORvXi1 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool isHorizontalBinOpPart (const BuildVectorSDNode *N, unsigned Opcode, SelectionDAG &DAG, unsigned BaseIdx, unsigned LastIdx, SDValue &V0, SDValue &V1)
This is a helper function of LowerToHorizontalOp().
static SDValue ExpandHorizontalBinOp (const SDValue &V0, const SDValue &V1, const SDLoc &DL, SelectionDAG &DAG, unsigned X86Opcode, bool Mode, bool isUndefLO, bool isUndefHI)
Emit a sequence of two 128-bit horizontal add/sub followed by a concat_vector.
static bool isAddSubOrSubAdd (const BuildVectorSDNode *BV, const X86Subtarget &Subtarget, SelectionDAG &DAG, SDValue &Opnd0, SDValue &Opnd1, unsigned &NumExtracts, bool &IsSubAdd)
Returns true iff BV builds a vector with the result equivalent to the result of ADDSUB/SUBADD operation.
static bool isFMAddSubOrFMSubAdd (const X86Subtarget &Subtarget, SelectionDAG &DAG, SDValue &Opnd0, SDValue &Opnd1, SDValue &Opnd2, unsigned ExpectedUses)
Returns true if is possible to fold MUL and an idiom that has already been recognized as ADDSUB/SUBADD(Opnd0, Opnd1) into FMADDSUB/FMSUBADD(x, y, Opnd1).
static SDValue lowerToAddSubOrFMAddSub (const BuildVectorSDNode *BV, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to fold a build_vector that performs an 'addsub' or 'fmaddsub' or 'fsubadd' operation accordingly to X86ISD::ADDSUB or X86ISD::FMADDSUB or X86ISD::FMSUBADD node.
static bool isHopBuildVector (const BuildVectorSDNode *BV, SelectionDAG &DAG, unsigned &HOpcode, SDValue &V0, SDValue &V1)
static SDValue getHopForBuildVector (const BuildVectorSDNode *BV, SelectionDAG &DAG, unsigned HOpcode, SDValue V0, SDValue V1)
static SDValue LowerToHorizontalOp (const BuildVectorSDNode *BV, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower BUILD_VECTOR to a horizontal add/sub operation if possible.
static SDValue lowerBuildVectorToBitOp (BuildVectorSDNode *Op, SelectionDAG &DAG)
If a BUILD_VECTOR's source elements all apply the same bit operation and one of their operands is constant, lower to a pair of BUILD_VECTOR and just apply the bit to the vectors.
static SDValue materializeVectorConstant (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Create a vector constant without a load.
static SDValue createVariablePermute (MVT VT, SDValue SrcVec, SDValue IndicesVec, SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Look for opportunities to create a VPERMV/VPERMILPV/PSHUFB variable permute from a vector of source values and a vector of extraction indices.
static SDValue LowerBUILD_VECTORAsVariablePermute (SDValue V, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerAVXCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerCONCAT_VECTORSvXi1 (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerCONCAT_VECTORS (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static bool isNoopShuffleMask (ArrayRef< int > Mask)
Tiny helper function to identify a no-op mask.
static bool isLaneCrossingShuffleMask (unsigned LaneSizeInBits, unsigned ScalarSizeInBits, ArrayRef< int > Mask)
Test whether there are elements crossing LaneSizeInBits lanes in this shuffle mask.
static bool is128BitLaneCrossingShuffleMask (MVT VT, ArrayRef< int > Mask)
Test whether there are elements crossing 128-bit lanes in this shuffle mask.
static bool isRepeatedShuffleMask (unsigned LaneSizeInBits, MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > &RepeatedMask)
Test whether a shuffle mask is equivalent within each sub-lane.
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > &RepeatedMask)
Test whether a shuffle mask is equivalent within each 128-bit lane.
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask)
static bool is256BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > &RepeatedMask)
Test whether a shuffle mask is equivalent within each 256-bit lane.
static bool isRepeatedTargetShuffleMask (unsigned LaneSizeInBits, MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > &RepeatedMask)
Test whether a target shuffle mask is equivalent within each sub-lane.
static bool isShuffleEquivalent (SDValue V1, SDValue V2, ArrayRef< int > Mask, ArrayRef< int > ExpectedMask)
Checks whether a shuffle mask is equivalent to an explicit list of arguments.
static bool isTargetShuffleEquivalent (ArrayRef< int > Mask, ArrayRef< int > ExpectedMask, SDValue V1=SDValue(), SDValue V2=SDValue())
Checks whether a target shuffle mask is equivalent to an explicit pattern.
static bool createShuffleMaskFromVSELECT (SmallVectorImpl< int > &Mask, SDValue Cond)
static bool isUnpackWdShuffleMask (ArrayRef< int > Mask, MVT VT)
static bool is128BitUnpackShuffleMask (ArrayRef< int > Mask)
static bool hasIdenticalHalvesShuffleMask (ArrayRef< int > Mask)
Return true if a shuffle mask chooses elements identically in its top and bottom halves.
static unsigned getV4X86ShuffleImm (ArrayRef< int > Mask)
Get a 4-lane 8-bit shuffle immediate for a mask.
static SDValue getV4X86ShuffleImm8ForMask (ArrayRef< int > Mask, const SDLoc &DL, SelectionDAG &DAG)
static bool isNonZeroElementsInOrder (const APInt &Zeroable, ArrayRef< int > Mask, const EVT &VectorType, bool &IsZeroSideLeft)
static SDValue lowerShuffleWithPSHUFB (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a shuffle with a single PSHUFB of V1 or V2.
static SDValue getMaskNode (SDValue Mask, MVT MaskVT, const X86Subtarget &Subtarget, SelectionDAG &DAG, const SDLoc &dl)
Return Mask with the necessary casting or extending for Mask according to MaskVT when lowering masking intrinsics.
static SDValue lowerShuffleToEXPAND (const SDLoc &DL, MVT VT, const APInt &Zeroable, ArrayRef< int > Mask, SDValue &V1, SDValue &V2, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool matchShuffleWithUNPCK (MVT VT, SDValue &V1, SDValue &V2, unsigned &UnpackOpcode, bool IsUnary, ArrayRef< int > TargetMask, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerShuffleWithUNPCK (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG &DAG)
static bool matchShuffleAsVPMOV (ArrayRef< int > Mask, bool SwappedOps, int Delta)
static SDValue lowerShuffleWithVPMOV (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool matchShuffleWithPACK (MVT VT, MVT &SrcVT, SDValue &V1, SDValue &V2, unsigned &PackOpcode, ArrayRef< int > TargetMask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerShuffleWithPACK (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerShuffleAsBitMask (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to emit a bitmask instruction for a shuffle.
static SDValue lowerShuffleAsBitBlend (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Try to emit a blend instruction for a shuffle using bit math.
static SDValue getVectorMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Return (and Op, Mask) for compare instructions or (vselect Mask, Op, PreservedSrc) for others along with the necessary casting or extending for Mask when lowering masking intrinsics.
static bool matchShuffleAsBlend (SDValue V1, SDValue V2, MutableArrayRef< int > Mask, const APInt &Zeroable, bool &ForceV1Zero, bool &ForceV2Zero, uint64_t &BlendMask)
static uint64_t scaleVectorShuffleBlendMask (uint64_t BlendMask, int Size, int Scale)
static SDValue lowerShuffleAsBlend (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Original, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to emit a blend instruction for a shuffle.
static SDValue lowerShuffleAsBlendAndPermute (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG, bool ImmBlends=false)
Try to lower as a blend of elements from two inputs followed by a single-input permutation.
static SDValue lowerShuffleAsUNPCKAndPermute (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Try to lower as an unpack of elements from two inputs followed by a single-input permutation.
static SDValue lowerShuffleAsByteRotateAndPermute (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Helper to form a PALIGNR-based rotate+permute, merging 2 inputs and then permuting the elements of the result in place.
static SDValue lowerShuffleAsDecomposedShuffleBlend (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Generic routine to decompose a shuffle and blend into independent blends and permutes.
static int matchShuffleAsRotate (SDValue &V1, SDValue &V2, ArrayRef< int > Mask)
Try to lower a vector shuffle as a rotation.
static int matchShuffleAsByteRotate (MVT VT, SDValue &V1, SDValue &V2, ArrayRef< int > Mask)
Try to lower a vector shuffle as a byte rotation.
static SDValue lowerShuffleAsByteRotate (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue lowerShuffleAsRotate (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a dword/qword rotation.
static SDValue lowerShuffleAsByteShiftMask (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a byte shift sequence.
static int matchShuffleAsShift (MVT &ShiftVT, unsigned &Opcode, unsigned ScalarSizeInBits, ArrayRef< int > Mask, int MaskOffset, const APInt &Zeroable, const X86Subtarget &Subtarget)
Try to lower a vector shuffle as a bit shift (shifts in zeros).
static SDValue lowerShuffleAsShift (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static bool matchShuffleAsEXTRQ (MVT VT, SDValue &V1, SDValue &V2, ArrayRef< int > Mask, uint64_t &BitLen, uint64_t &BitIdx, const APInt &Zeroable)
static bool matchShuffleAsINSERTQ (MVT VT, SDValue &V1, SDValue &V2, ArrayRef< int > Mask, uint64_t &BitLen, uint64_t &BitIdx)
static SDValue lowerShuffleWithSSE4A (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, SelectionDAG &DAG)
Try to lower a vector shuffle using SSE4a EXTRQ/INSERTQ.
static SDValue lowerShuffleAsSpecificZeroOrAnyExtend (const SDLoc &DL, MVT VT, int Scale, int Offset, bool AnyExt, SDValue InputV, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower a vector shuffle as a zero or any extension.
static SDValue lowerShuffleAsZeroOrAnyExtend (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a zero extension on any microarch.
static SDValue getScalarValueForVectorElement (SDValue V, int Idx, SelectionDAG &DAG)
Try to get a scalar value for a specific element of a vector.
static bool isShuffleFoldableLoad (SDValue V)
Helper to test for a load that can be folded with x86 shuffles.
static SDValue lowerShuffleAsElementInsertion (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower insertion of a single element into a zero vector.
static SDValue lowerShuffleAsTruncBroadcast (const SDLoc &DL, MVT VT, SDValue V0, int BroadcastIdx, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower broadcast of a single - truncated - integer element, coming from a scalar_to_vector/build_vector node V0 with larger elements.
static bool isSingleSHUFPSMask (ArrayRef< int > Mask)
Test whether this can be lowered with a single SHUFPS instruction.
static SDValue lowerShuffleOfExtractsAsVperm (const SDLoc &DL, SDValue N0, SDValue N1, ArrayRef< int > Mask, SelectionDAG &DAG)
If we are extracting two 128-bit halves of a vector and shuffling the result, match that to a 256-bit AVX2 vperm* instruction to avoid a multi-shuffle lowering.
static SDValue lowerShuffleAsBroadcast (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower broadcast of a single element.
static bool matchShuffleAsInsertPS (SDValue &V1, SDValue &V2, unsigned &InsertPSMask, const APInt &Zeroable, ArrayRef< int > Mask, SelectionDAG &DAG)
static SDValue lowerShuffleAsInsertPS (const SDLoc &DL, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, SelectionDAG &DAG)
static SDValue lowerShuffleAsPermuteAndUnpack (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a shuffle as a permute of the inputs followed by an UNPCK instruction.
static SDValue lowerV2F64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 2-lane 64-bit floating point shuffles.
static SDValue lowerV2I64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 2-lane 64-bit integer shuffles.
static SDValue lowerShuffleWithSHUFPS (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG &DAG)
Lower a vector shuffle using the SHUFPS instruction.
static SDValue lowerV4F32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower 4-lane 32-bit floating point shuffles.
static SDValue lowerV4I32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower 4-lane i32 vector shuffles.
static SDValue lowerV8I16GeneralSingleInputShuffle (const SDLoc &DL, MVT VT, SDValue V, MutableArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lowering of single-input v8i16 shuffles is the cornerstone of SSE2 shuffle lowering, and the most complex part.
static SDValue lowerShuffleAsBlendOfPSHUFBs (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, SelectionDAG &DAG, bool &V1InUse, bool &V2InUse)
Helper to form a PSHUFB-based shuffle+blend, opportunistically avoiding the blend if only one input is used.
static SDValue lowerV8I16Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Generic lowering of 8-lane i16 shuffles.
static int canLowerByDroppingEvenElements (ArrayRef< int > Mask, bool IsSingleInput)
Check whether a compaction lowering can be done by dropping even elements and compute how many times even elements must be dropped.
static SDValue lowerShuffleWithPERMV (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG &DAG)
static SDValue lowerV16I8Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Generic lowering of v16i8 shuffles.
static SDValue lower128BitShuffle (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Dispatching routine to lower various 128-bit x86 vector shuffles.
static SDValue splitAndLowerShuffle (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
Generic routine to split vector shuffle into half-sized shuffles.
static SDValue lowerShuffleAsSplitOrBlend (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Either split a vector in halves or decompose the shuffles and the blend.
static SDValue lowerShuffleAsLanePermuteAndSHUFP (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG)
static SDValue lowerShuffleAsLanePermuteAndPermute (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Lower a vector shuffle crossing multiple 128-bit lanes as a lane permutation followed by a per-lane permutation.
static SDValue lowerShuffleAsLanePermuteAndShuffle (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Lower a vector shuffle crossing multiple 128-bit lanes by shuffling one source with a lane permutation.
static SDValue lowerV2X128Shuffle (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering 2-lane 128-bit shuffles.
static SDValue lowerShuffleAsLanePermuteAndRepeatedMask (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower a vector shuffle by first fixing the 128-bit lanes and then shuffling each lane.
static bool getHalfShuffleMask (ArrayRef< int > Mask, MutableArrayRef< int > HalfMask, int &HalfIdx1, int &HalfIdx2)
If the input shuffle mask results in a vector that is undefined in all upper or lower half elements and that mask accesses only 2 halves of the shuffle's operands, return true.
static SDValue getShuffleHalfVectors (const SDLoc &DL, SDValue V1, SDValue V2, ArrayRef< int > HalfMask, int HalfIdx1, int HalfIdx2, bool UndefLower, SelectionDAG &DAG, bool UseConcat=false)
Given the output values from getHalfShuffleMask(), create a half width shuffle of extracted vectors followed by an insert back to full width.
static SDValue lowerShuffleWithUndefHalf (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Lower shuffles where an entire half of a 256 or 512-bit vector is UNDEF.
static bool isShuffleMaskInputInPlace (int Input, ArrayRef< int > Mask)
Test whether the specified input (0 or 1) is in-place blended by the given mask.
static SDValue lowerShuffleAsRepeatedMaskAndLanePermute (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle case where shuffle sources are coming from the same 128-bit lane and every lane can be represented as the same repeating mask - allowing us to shuffle the sources with the repeating shuffle and then permute the result to the destination lanes.
static bool matchShuffleWithSHUFPD (MVT VT, SDValue &V1, SDValue &V2, bool &ForceV1Zero, bool &ForceV2Zero, unsigned &ShuffleImm, ArrayRef< int > Mask, const APInt &Zeroable)
static SDValue lowerShuffleWithSHUFPD (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue lowerShuffleAsVTRUNCAndUnpack (const SDLoc &DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt &Zeroable, SelectionDAG &DAG)
static SDValue lowerV4F64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 4-lane 64-bit floating point shuffles.
static SDValue lowerV4I64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 4-lane 64-bit integer shuffles.
static SDValue lowerV8F32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 32-bit floating point shuffles.
static SDValue lowerV8I32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 32-bit integer shuffles.
static SDValue lowerV16I16Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 16-bit integer shuffles.
static SDValue lowerV32I8Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 32-lane 8-bit integer shuffles.
static SDValue lower256BitShuffle (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
High-level routine to lower various 256-bit x86 vector shuffles.
static SDValue lowerV4X128Shuffle (const SDLoc &DL, MVT VT, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a vector shuffle as a 128-bit shuffles.
static SDValue lowerV8F64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 64-bit floating point shuffles.
static SDValue lowerV16F32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 32-bit floating point shuffles.
static SDValue lowerV8I64Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 8-lane 64-bit integer shuffles.
static SDValue lowerV16I32Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 16-lane 32-bit integer shuffles.
static SDValue lowerV32I16Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 32-lane 16-bit integer shuffles.
static SDValue lowerV64I8Shuffle (const SDLoc &DL, ArrayRef< int > Mask, const APInt &Zeroable, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle lowering of 64-lane 8-bit integer shuffles.
static SDValue lower512BitShuffle (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
High-level routine to lower various 512-bit x86 vector shuffles.
static SDValue lower1BitShuffleAsKSHIFTR (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static int match1BitShuffleAsKSHIFT (unsigned &Opcode, ArrayRef< int > Mask, int MaskOffset, const APInt &Zeroable)
static SDValue lower1BitShuffle (const SDLoc &DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt &Zeroable, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static bool canonicalizeShuffleMaskWithCommute (ArrayRef< int > Mask)
Helper function that returns true if the shuffle mask should be commuted to improve canonicalization.
static SDValue lowerVECTOR_SHUFFLE (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Top-level lowering for x86 vector shuffles.
static SDValue lowerVSELECTtoVectorShuffle (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to lower a VSELECT instruction to a vector shuffle.
static SDValue LowerEXTRACT_VECTOR_ELT_SSE4 (SDValue Op, SelectionDAG &DAG)
static SDValue ExtractBitFromMaskVector (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Extract one bit from mask vector, like v16i1 or v8i1.
static SDValue InsertBitToMaskVector (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Insert one bit to mask vector, like v16i1 or v8i1.
static SDValue LowerSCALAR_TO_VECTOR (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerINSERT_SUBVECTOR (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue GetTLSADDR (SelectionDAG &DAG, SDValue Chain, GlobalAddressSDNode *GA, SDValue *InFlag, const EVT PtrVT, unsigned ReturnReg, unsigned char OperandFlags, bool LocalDynamic=false)
static SDValue LowerToTLSGeneralDynamicModel32 (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT)
static SDValue LowerToTLSGeneralDynamicModel64 (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT)
static SDValue LowerToTLSLocalDynamicModel (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT, bool is64Bit)
static SDValue LowerToTLSExecModel (GlobalAddressSDNode *GA, SelectionDAG &DAG, const EVT PtrVT, TLSModel::Model model, bool is64Bit, bool isPIC)
static SDValue LowerShiftParts (SDValue Op, SelectionDAG &DAG)
Lower SRA_PARTS and friends, which return two i32 values and take a 2 x i32 value to shift plus a shift amount.
static SDValue LowerFunnelShift (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerI64IntToFP_AVX512DQ (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool useVectorCast (unsigned Opcode, MVT FromVT, MVT ToVT, const X86Subtarget &Subtarget)
static SDValue vectorizeExtractedCast (SDValue Cast, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Given a scalar cast operation that is extracted from a vector, try to vectorize the cast op followed by extraction.
static SDValue lowerINT_TO_FP_vXi64 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool shouldUseHorizontalOp (bool IsSingleSource, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Horizontal vector math instructions may be slower than normal math with shuffles.
static SDValue LowerUINT_TO_FP_i64 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
64-bit unsigned integer to double expansion.
static SDValue LowerUINT_TO_FP_i32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
32-bit unsigned integer to float expansion.
static SDValue lowerUINT_TO_FP_v2i32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget, const SDLoc &DL)
static SDValue lowerUINT_TO_FP_vXi32 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerUINT_TO_FP_vec (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerAVXExtend (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue SplitAndExtendv16i1 (unsigned ExtOpc, MVT VT, SDValue In, const SDLoc &dl, SelectionDAG &DAG)
static SDValue LowerZERO_EXTEND_Mask (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerZERO_EXTEND (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue truncateVectorWithPACK (unsigned Opcode, EVT DstVT, SDValue In, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Helper to recursively truncate vector elements in half with PACKSS/PACKUS.
static SDValue LowerTruncateVecI1 (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerAddSubToHorizontalOp (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Depending on uarch and/or optimizing for size, we might prefer to use a vector operation in place of the typical scalar operation.
static SDValue LowerFABSorFNEG (SDValue Op, SelectionDAG &DAG)
The only differences between FABS and FNEG are the mask and the logic op.
static SDValue LowerFCOPYSIGN (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFGETSIGN (SDValue Op, SelectionDAG &DAG)
static SDValue getSETCC (X86::CondCode Cond, SDValue EFLAGS, const SDLoc &dl, SelectionDAG &DAG)
Helper for creating a X86ISD::SETCC node.
static bool matchScalarReduction (SDValue Op, ISD::NodeType BinOp, SmallVectorImpl< SDValue > &SrcOps)
Helper for matching OR(EXTRACTELT(X,0),OR(EXTRACTELT(X,1),...)) style scalarized (associative) reduction patterns.
static SDValue LowerVectorAllZeroTest (SDValue Op, ISD::CondCode CC, const X86Subtarget &Subtarget, SelectionDAG &DAG, SDValue &X86CC)
static bool hasNonFlagsUse (SDValue Op)
return true if Op has a use that doesn't just read flags.
static bool isProfitableToUseFlagOp (SDValue Op)
static SDValue EmitTest (SDValue Op, unsigned X86CC, const SDLoc &dl, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Emit nodes that will be selected as "test Op0,Op0", or something equivalent.
static std::pair< SDValue, SDValue > EmitCmp (SDValue Op0, SDValue Op1, unsigned X86CC, const SDLoc &dl, SelectionDAG &DAG, const X86Subtarget &Subtarget, SDValue Chain, bool IsSignaling)
Emit nodes that will be selected as "cmp Op0,Op1", or something equivalent.
static SDValue LowerAndToBT (SDValue And, ISD::CondCode CC, const SDLoc &dl, SelectionDAG &DAG, SDValue &X86CC)
Result of 'and' is compared against zero.
static unsigned translateX86FSETCC (ISD::CondCode SetCCOpcode, SDValue &Op0, SDValue &Op1, bool &IsAlwaysSignaling)
Turns an ISD::CondCode into a value suitable for SSE floating-point mask CMPs.
static SDValue Lower256IntVSETCC (SDValue Op, SelectionDAG &DAG)
Break a VSETCC 256-bit integer VSETCC into two new 128 ones and then concatenate the result back.
static SDValue LowerIntVSETCC_AVX512 (SDValue Op, SelectionDAG &DAG)
static SDValue incDecVectorConstant (SDValue V, SelectionDAG &DAG, bool IsInc)
Given a buildvector constant, return a new vector constant with each element incremented or decremented.
static SDValue LowerVSETCCWithSUBUS (SDValue Op0, SDValue Op1, MVT VT, ISD::CondCode Cond, const SDLoc &dl, const X86Subtarget &Subtarget, SelectionDAG &DAG)
As another special case, use PSUBUS[BW] when it's profitable.
static SDValue LowerVSETCC (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue EmitAVX512Test (SDValue Op0, SDValue Op1, ISD::CondCode CC, const SDLoc &dl, SelectionDAG &DAG, const X86Subtarget &Subtarget, SDValue &X86CC)
static std::pair< SDValue, SDValue > getX86XALUOOp (X86::CondCode &Cond, SDValue Op, SelectionDAG &DAG)
static SDValue LowerXALUO (SDValue Op, SelectionDAG &DAG)
static bool isX86LogicalCmp (SDValue Op)
Return true if opcode is a X86 logical comparison.
static bool isTruncWithZeroHighBitsInput (SDValue V, SelectionDAG &DAG)
static SDValue LowerSIGN_EXTEND_Mask (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerANY_EXTEND (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerEXTEND_VECTOR_INREG (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerSIGN_EXTEND (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue splitVectorStore (StoreSDNode *Store, SelectionDAG &DAG)
Change a vector store into a pair of half-size vector stores.
static SDValue scalarizeVectorStore (StoreSDNode *Store, MVT StoreVT, SelectionDAG &DAG)
Scalarize a vector store, bitcasting to TargetVT to determine the scalar type.
static SDValue LowerStore (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerLoad (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static bool isAndOrOfSetCCs (SDValue Op, unsigned &Opc)
Return true if node is an ISD::AND or ISD::OR of two X86ISD::SETCC nodes each of which has no other use apart from the AND / OR.
static bool isXor1OfSetCC (SDValue Op)
Return true if node is an ISD::XOR of a X86ISD::SETCC and 1 and that the SETCC node has a single use.
static SDValue LowerVACOPY (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static unsigned getTargetVShiftUniformOpcode (unsigned Opc, bool IsVariable)
static SDValue getTargetVShiftByConstNode (unsigned Opc, const SDLoc &dl, MVT VT, SDValue SrcOp, uint64_t ShiftAmt, SelectionDAG &DAG)
Handle vector element shifts where the shift amount is a constant.
static SDValue getTargetVShiftNode (unsigned Opc, const SDLoc &dl, MVT VT, SDValue SrcOp, SDValue ShAmt, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Handle vector element shifts where the shift amount may or may not be a constant.
static SDValue getScalarMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Creates an SDNode for a predicated scalar operation.
static int getSEHRegistrationNodeSize (const Function *Fn)
static SDValue recoverFramePointer (SelectionDAG &DAG, const Function *Fn, SDValue EntryEBP)
When the MSVC runtime transfers control to us, either to an outlined function or when returning to a parent frame after catching an exception, we recover the parent frame pointer by doing arithmetic on the incoming EBP.
static SDValue getAVX2GatherNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget &Subtarget)
static SDValue getGatherNode (SDValue Op, SelectionDAG &DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget &Subtarget)
static SDValue getScatterNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget &Subtarget)
static SDValue getPrefetchNode (unsigned Opc, SDValue Op, SelectionDAG &DAG, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget &Subtarget)
static SDValue expandIntrinsicWChainHelper (SDNode *N, const SDLoc &DL, SelectionDAG &DAG, unsigned TargetOpcode, unsigned SrcReg, const X86Subtarget &Subtarget, SmallVectorImpl< SDValue > &Results)
Handles the lowering of builtin intrinsics with chain that return their value into registers EDX:EAX.
static void getReadTimeStampCounter (SDNode *N, const SDLoc &DL, unsigned Opcode, SelectionDAG &DAG, const X86Subtarget &Subtarget, SmallVectorImpl< SDValue > &Results)
Handles the lowering of builtin intrinsics that read the time stamp counter (x86_rdtsc and x86_rdtscp).
static SDValue LowerREADCYCLECOUNTER (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue MarkEHRegistrationNode (SDValue Op, SelectionDAG &DAG)
static SDValue MarkEHGuard (SDValue Op, SelectionDAG &DAG)
static SDValue EmitTruncSStore (bool SignedSat, SDValue Chain, const SDLoc &Dl, SDValue Val, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO, SelectionDAG &DAG)
Emit Truncating Store with signed or unsigned saturation.
static SDValue EmitMaskedTruncSStore (bool SignedSat, SDValue Chain, const SDLoc &Dl, SDValue Val, SDValue Ptr, SDValue Mask, EVT MemVT, MachineMemOperand *MMO, SelectionDAG &DAG)
Emit Masked Truncating Store with signed or unsigned saturation.
static SDValue LowerINTRINSIC_W_CHAIN (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerADJUST_TRAMPOLINE (SDValue Op, SelectionDAG &DAG)
static SDValue LowerVectorIntUnary (SDValue Op, SelectionDAG &DAG)
static SDValue Lower256IntUnary (SDValue Op, SelectionDAG &DAG)
static SDValue Lower512IntUnary (SDValue Op, SelectionDAG &DAG)
static SDValue LowerVectorCTLZ_AVX512CDI (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Lower a vector CTLZ using native supported vector CTLZ instruction.
static SDValue LowerVectorCTLZInRegLUT (SDValue Op, const SDLoc &DL, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerVectorCTLZ (SDValue Op, const SDLoc &DL, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerCTLZ (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerCTTZ (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue split256IntArith (SDValue Op, SelectionDAG &DAG)
Break a 256-bit integer operation into two new 128-bit ones and then concatenate the result back.
static SDValue split512IntArith (SDValue Op, SelectionDAG &DAG)
Break a 512-bit integer operation into two new 256-bit ones and then concatenate the result back.
static SDValue lowerAddSub (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerADDSAT_SUBSAT (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerABS (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerMINMAX (SDValue Op, SelectionDAG &DAG)
static SDValue LowerMUL (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerMULH (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static bool SupportedVectorShiftWithImm (MVT VT, const X86Subtarget &Subtarget, unsigned Opcode)
static bool SupportedVectorShiftWithBaseAmnt (MVT VT, const X86Subtarget &Subtarget, unsigned Opcode)
static bool SupportedVectorVarShift (MVT VT, const X86Subtarget &Subtarget, unsigned Opcode)
static SDValue LowerScalarImmediateShift (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerScalarVariableShift (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue convertShiftLeftToScale (SDValue Amt, const SDLoc &dl, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerShift (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerRotate (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue emitLockedStackOp (SelectionDAG &DAG, const X86Subtarget &Subtarget, SDValue Chain, SDLoc DL)
Emit a locked operation on a stack location which does not change any memory location, but does involve a lock prefix.
static SDValue LowerATOMIC_FENCE (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerCMP_SWAP (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue getPMOVMSKB (const SDLoc &DL, SDValue V, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerBITCAST (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerHorizontalByteSum (SDValue V, MVT VT, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Compute the horizontal sum of bytes in V for the elements of VT.
static SDValue LowerVectorCTPOPInRegLUT (SDValue Op, const SDLoc &DL, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerVectorCTPOP (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerCTPOP (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerBITREVERSE_XOP (SDValue Op, SelectionDAG &DAG)
static SDValue LowerBITREVERSE (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue lowerAtomicArithWithLOCK (SDValue N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerAtomicArith (SDValue N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Lower atomic_load_ops into LOCK-prefixed operations.
static SDValue LowerATOMIC_STORE (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue LowerADDSUBCARRY (SDValue Op, SelectionDAG &DAG)
static SDValue LowerFSINCOS (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue ExtendToType (SDValue InOp, MVT NVT, SelectionDAG &DAG, bool FillWithZeroes=false)
Widen a vector input to a vector of NVT.
static SDValue LowerMSCATTER (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerMLOAD (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerMSTORE (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerMGATHER (SDValue Op, const X86Subtarget &Subtarget, SelectionDAG &DAG)
static SDValue LowerADDRSPACECAST (SDValue Op, SelectionDAG &DAG)
static MachineBasicBlock * emitXBegin (MachineInstr &MI, MachineBasicBlock *MBB, const TargetInstrInfo *TII)
Utility function to emit xbegin specifying the start of an RTM region.
static bool checkAndUpdateEFLAGSKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock *BB, const TargetRegisterInfo *TRI)
static bool isCMOVPseudo (MachineInstr &MI)
static MachineInstrBuilder createPHIsForCMOVsInSinkBB (MachineBasicBlock::iterator MIItBegin, MachineBasicBlock::iterator MIItEnd, MachineBasicBlock *TrueMBB, MachineBasicBlock *FalseMBB, MachineBasicBlock *SinkMBB)
static unsigned getOpcodeForRetpoline (unsigned RPOpc)
static const char * getRetpolineSymbol (const X86Subtarget &Subtarget, unsigned Reg)
static bool matchUnaryShuffle (MVT MaskVT, ArrayRef< int > Mask, bool AllowFloatDomain, bool AllowIntDomain, SDValue &V1, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget, unsigned &Shuffle, MVT &SrcVT, MVT &DstVT)
static bool matchUnaryPermuteShuffle (MVT MaskVT, ArrayRef< int > Mask, const APInt &Zeroable, bool AllowFloatDomain, bool AllowIntDomain, const X86Subtarget &Subtarget, unsigned &Shuffle, MVT &ShuffleVT, unsigned &PermuteImm)
static bool matchBinaryShuffle (MVT MaskVT, ArrayRef< int > Mask, bool AllowFloatDomain, bool AllowIntDomain, SDValue &V1, SDValue &V2, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget, unsigned &Shuffle, MVT &SrcVT, MVT &DstVT, bool IsUnary)
static bool matchBinaryPermuteShuffle (MVT MaskVT, ArrayRef< int > Mask, const APInt &Zeroable, bool AllowFloatDomain, bool AllowIntDomain, SDValue &V1, SDValue &V2, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget, unsigned &Shuffle, MVT &ShuffleVT, unsigned &PermuteImm)
static SDValue combineX86ShuffleChainWithExtract (ArrayRef< SDValue > Inputs, SDValue Root, ArrayRef< int > BaseMask, int Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineX86ShuffleChain (ArrayRef< SDValue > Inputs, SDValue Root, ArrayRef< int > BaseMask, int Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Combine an arbitrary chain of shuffles into a single instruction if possible.
static SDValue combineX86ShufflesConstants (ArrayRef< SDValue > Ops, ArrayRef< int > Mask, SDValue Root, bool HasVariableMask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineX86ShufflesRecursively (ArrayRef< SDValue > SrcOps, int SrcOpIndex, SDValue Root, ArrayRef< int > RootMask, ArrayRef< const SDNode *> SrcNodes, unsigned Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Fully generic combining of x86 shuffle instructions.
static SDValue combineX86ShufflesRecursively (SDValue Op, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Helper entry wrapper to combineX86ShufflesRecursively.
static SmallVector< int, 4 > getPSHUFShuffleMask (SDValue N)
Get the PSHUF-style mask from PSHUF node.
static SDValue combineRedundantDWordShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG &DAG)
Search for a combinable shuffle across a chain ending in pshufd.
static SDValue combineTargetShuffle (SDValue N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Try to combine x86 target specific shuffles.
static bool isAddSubOrSubAddMask (ArrayRef< int > Mask, bool &Op0Even)
Checks if the shuffle mask takes subsequent elements alternately from two vectors.
static bool isAddSubOrSubAdd (SDNode *N, const X86Subtarget &Subtarget, SelectionDAG &DAG, SDValue &Opnd0, SDValue &Opnd1, bool &IsSubAdd)
Returns true iff the shuffle node N can be replaced with ADDSUB(SUBADD) operation.
static SDValue combineShuffleToFMAddSub (SDNode *N, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Combine shuffle of two fma nodes into FMAddSub or FMSubAdd.
static SDValue combineShuffleToAddSubOrFMAddSub (SDNode *N, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Try to combine a shuffle into a target-specific add-sub or mul-add-sub node.
static SDValue combineShuffleOfConcatUndef (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue foldShuffleOfHorizOp (SDNode *N, SelectionDAG &DAG)
Eliminate a redundant shuffle of a horizontal math op.
static SDValue narrowShuffle (ShuffleVectorSDNode *Shuf, SelectionDAG &DAG)
If we have a shuffle of AVX/AVX512 (256/512 bit) vectors that only uses the low half of each source vector and does not set any high half elements in the destination vector, narrow the shuffle to half its original size.
static SDValue combineShuffle (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool checkBitcastSrcVectorSize (SDValue Src, unsigned Size)
static SDValue signExtendBitcastSrcVector (SelectionDAG &DAG, EVT SExtVT, SDValue Src, const SDLoc &DL)
static SDValue combineBitcastvxi1 (SelectionDAG &DAG, EVT VT, SDValue Src, const SDLoc &DL, const X86Subtarget &Subtarget)
static SDValue combinevXi1ConstantToInteger (SDValue Op, SelectionDAG &DAG)
static SDValue combineCastedMaskArithmetic (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue createMMXBuildVector (BuildVectorSDNode *BV, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineBitcast (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool detectZextAbsDiff (const SDValue &Abs, SDValue &Op0, SDValue &Op1)
static SDValue createPSADBW (SelectionDAG &DAG, const SDValue &Zext0, const SDValue &Zext1, const SDLoc &DL, const X86Subtarget &Subtarget)
static SDValue combineHorizontalMinMaxResult (SDNode *Extract, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineHorizontalPredicateResult (SDNode *Extract, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineBasicSADPattern (SDNode *Extract, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineExtractWithShuffle (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue scalarizeExtEltFP (SDNode *ExtElt, SelectionDAG &DAG)
Extracting a scalar FP value from vector element 0 is free, so extract each operand first, then perform the math as a scalar op.
static SDValue combineReductionToHorizontal (SDNode *ExtElt, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Try to convert a vector reduction sequence composed of binops and shuffles into horizontal ops.
static SDValue combineExtractVectorElt (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Detect vector gather/scatter index generation and convert it from being a bunch of shuffles and extracts into a somewhat faster sequence.
static SDValue combineVSelectWithAllOnesOrZeros (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
If a vector select has an operand that is -1 or 0, try to simplify the select to a bitwise logic operation.
static SDValue narrowVectorSelect (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
If both arms of a vector select are concatenated vectors, split the select, and concatenate the result to eliminate a wide (256-bit) vector instruction: vselect Cond, (concat T0, T1), (concat F0, F1) –> concat (vselect (split Cond), T0, F0), (vselect (split Cond), T1, F1)
static SDValue combineSelectOfTwoConstants (SDNode *N, SelectionDAG &DAG)
static SDValue combineVSelectToBLENDV (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
If this is a dynamic select (non-constant condition) and we can match this node with one of the variable blend instructions, restructure the condition so that blends can use the high (sign) bit of each element.
static SDValue combineLogicBlendIntoConditionalNegate (EVT VT, SDValue Mask, SDValue X, SDValue Y, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineSelect (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Do target-specific dag combines on SELECT and VSELECT nodes.
static SDValue combineSetCCAtomicArith (SDValue Cmp, X86::CondCode &CC, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Combine: (brcond/cmov/setcc .., (cmp (atomic_load_add x, 1), 0), COND_S) to: (brcond/cmov/setcc .., (LADD x, 1), COND_LE) i.e., reusing the EFLAGS produced by the LOCKed instruction.
static SDValue checkBoolTestSetCCCombine (SDValue Cmp, X86::CondCode &CC)
static bool checkBoolTestAndOrSetCCCombine (SDValue Cond, X86::CondCode &CC0, X86::CondCode &CC1, SDValue &Flags, bool &isAnd)
Check whether Cond is an AND/OR of SETCCs off of the same EFLAGS.
static SDValue combineCarryThroughADD (SDValue EFLAGS, SelectionDAG &DAG)
static SDValue combineSetCCEFLAGS (SDValue EFLAGS, X86::CondCode &CC, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Optimize an EFLAGS definition used according to the condition code CC into a simpler EFLAGS value, potentially returning a new CC and replacing uses of chain values.
static SDValue combineCMov (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Optimize X86ISD::CMOV [LHS, RHS, CONDCODE (e.g. X86::COND_NE), CONDVAL].
static bool canReduceVMulWidth (SDNode *N, SelectionDAG &DAG, ShrinkMode &Mode)
static SDValue reduceVMULWidth (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
When the operands of vector mul are extended from smaller size values, like i8 and i16, the type of mul may be shrinked to generate more efficient code.
static SDValue combineMulSpecial (uint64_t MulAmt, SDNode *N, SelectionDAG &DAG, EVT VT, const SDLoc &DL)
static SDValue combineMulToPMADDWD (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineMulToPMULDQ (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineMul (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Optimize a single multiply with constant into two operations in order to implement it with two cheaper instructions, e.g.
static SDValue combineShiftLeft (SDNode *N, SelectionDAG &DAG)
static SDValue combineShiftRightArithmetic (SDNode *N, SelectionDAG &DAG)
static SDValue combineShiftRightLogical (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineVectorPack (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineVectorShiftVar (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineVectorShiftImm (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineVectorInsert (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineCompareEqual (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Recognize the distinctive (AND (setcc ...) (setcc ..)) where both setccs reference the same FP CMP, and rewrite for CMPEQSS and friends.
static SDValue combineANDXORWithAllOnesIntoANDNP (SDNode *N, SelectionDAG &DAG)
Try to fold: (and (xor X, -1), Y) -> (andnp X, Y).
static SDValue PromoteMaskArithmetic (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue convertIntLogicToFPLogic (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
If both input operands of a logic op are being cast from floating point types, try to convert this into a floating point logic node to avoid unnecessary moves from SSE to integer registers.
static SDValue combineAndMaskToShift (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
If this is a zero/all-bits result that is bitwise-anded with a low bits mask.
static SDValue getIndexFromUnindexedLoad (LoadSDNode *Ld)
static bool hasBZHI (const X86Subtarget &Subtarget, MVT VT)
static SDValue combineAndLoadToBZHI (SDNode *Node, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineParity (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineScalarAndWithMaskSetcc (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineAnd (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue canonicalizeBitSelect (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static bool matchLogicBlend (SDNode *N, SDValue &X, SDValue &Y, SDValue &Mask)
static SDValue combineLogicBlendIntoPBLENDV (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue lowerX86CmpEqZeroToCtlzSrl (SDValue Op, EVT ExtTy, SelectionDAG &DAG)
static SDValue combineOrCmpEqZeroToCtlzSrl (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineOrShiftToFunnelShift (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineOr (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue foldXorTruncShiftIntoCmp (SDNode *N, SelectionDAG &DAG)
Try to turn tests against the signbit in the form of: XOR(TRUNCATE(SRL(X, size(X)-1)), 1) into: SETGT(X, -1)
static SDValue foldVectorXorShiftIntoCmp (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Turn vector tests of the signbit in the form of: xor (sra X, elt_size(X)-1), -1 into: pcmpgt X, -1.
static SDValue detectUSatPattern (SDValue In, EVT VT, SelectionDAG &DAG, const SDLoc &DL)
Detect patterns of truncation with unsigned saturation:
static SDValue detectSSatPattern (SDValue In, EVT VT, bool MatchPackUS=false)
Detect patterns of truncation with signed saturation: (truncate (smin ((smax (x, signed_min_of_dest_type)), signed_max_of_dest_type)) to dest_type) or: (truncate (smax ((smin (x, signed_max_of_dest_type)), signed_min_of_dest_type)) to dest_type).
static SDValue combineTruncateWithSat (SDValue In, EVT VT, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue detectAVGPattern (SDValue In, EVT VT, SelectionDAG &DAG, const X86Subtarget &Subtarget, const SDLoc &DL)
This function detects the AVG pattern between vectors of unsigned i8/i16, which is c = (a + b + 1) / 2, and replace this operation with the efficient X86ISD::AVG instruction.
static SDValue combineLoad (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static int getOneTrueElt (SDValue V)
If V is a build vector of boolean constants and exactly one of those constants is true, return the operand index of that true element.
static bool getParamsForOneTrueMaskedElt (MaskedLoadStoreSDNode *MaskedOp, SelectionDAG &DAG, SDValue &Addr, SDValue &Index, unsigned &Alignment)
Given a masked memory load/store operation, return true if it has one mask bit set.
static SDValue reduceMaskedLoadToScalarLoad (MaskedLoadSDNode *ML, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
If exactly one element of the mask is set for a non-extending masked load, it is a scalar load and vector insert.
static SDValue combineMaskedLoadConstantMask (MaskedLoadSDNode *ML, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineMaskedLoad (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue reduceMaskedStoreToScalarStore (MaskedStoreSDNode *MS, SelectionDAG &DAG)
If exactly one element of the mask is set for a non-truncating masked store, it is a vector extract and scalar store.
static SDValue combineMaskedStore (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineStore (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool isHorizontalBinOp (SDValue &LHS, SDValue &RHS, SelectionDAG &DAG, const X86Subtarget &Subtarget, bool IsCommutative)
Return 'true' if this vector operation is "horizontal" and return the operands for the horizontal operation in LHS and RHS.
static SDValue combineFaddFsub (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Do target-specific dag combines on floating-point adds/subs.
static SDValue combineTruncatedArithmetic (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget, const SDLoc &DL)
Attempt to pre-truncate inputs to arithmetic ops if it will simplify the codegen.
static SDValue combineVectorTruncationWithPACKUS (SDNode *N, const SDLoc &DL, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Truncate using ISD::AND mask and X86ISD::PACKUS.
static SDValue combineVectorTruncationWithPACKSS (SDNode *N, const SDLoc &DL, const X86Subtarget &Subtarget, SelectionDAG &DAG)
Truncate a group of v4i32 into v8i16 using X86ISD::PACKSS.
static SDValue combineVectorTruncation (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
This function transforms truncation from vXi32/vXi64 to vXi8/vXi16 into X86ISD::PACKUS/X86ISD::PACKSS operations.
static SDValue combineVectorSignBitsTruncation (SDNode *N, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
This function transforms vector truncation of 'extended sign-bits' or 'extended zero-bits' values.
static SDValue combinePMULH (SDValue Src, EVT VT, const SDLoc &DL, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue detectPMADDUBSW (SDValue In, EVT VT, SelectionDAG &DAG, const X86Subtarget &Subtarget, const SDLoc &DL)
static SDValue combineTruncate (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineVTRUNC (SDNode *N, SelectionDAG &DAG)
static SDValue isFNEG (SelectionDAG &DAG, SDNode *N, unsigned Depth=0)
Returns the negated value if the node N flips sign of FP value.
static unsigned negateFMAOpcode (unsigned Opcode, bool NegMul, bool NegAcc, bool NegRes)
static SDValue combineFneg (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Do target-specific dag combines on floating point negations.
static SDValue lowerX86FPLogicOp (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue foldXor1SetCC (SDNode *N, SelectionDAG &DAG)
Fold a xor(setcc cond, val), 1 –> setcc (inverted(cond), val)
static SDValue combineXor (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineBEXTR (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool isNullFPScalarOrVectorConst (SDValue V)
static SDValue getNullFPConstForNullVal (SDValue V, SelectionDAG &DAG, const X86Subtarget &Subtarget)
If a value is a scalar FP zero or a vector FP zero (potentially including undefined elements), return a zero constant that may be used to fold away that value.
static SDValue combineFAndFNotToFAndn (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineFAnd (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Do target-specific dag combines on X86ISD::FAND nodes.
static SDValue combineFAndn (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Do target-specific dag combines on X86ISD::FANDN nodes.
static SDValue combineFOr (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Do target-specific dag combines on X86ISD::FOR and X86ISD::FXOR nodes.
static SDValue combineFMinFMax (SDNode *N, SelectionDAG &DAG)
Do target-specific dag combines on X86ISD::FMIN and X86ISD::FMAX nodes.
static SDValue combineFMinNumFMaxNum (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineX86INT_TO_FP (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineCVTP2I_CVTTP2I (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineAndnp (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Do target-specific dag combines on X86ISD::ANDNP nodes.
static SDValue combineBT (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineSextInRegCmov (SDNode *N, SelectionDAG &DAG)
static SDValue combineSignExtendInReg (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue promoteExtBeforeAdd (SDNode *Ext, SelectionDAG &DAG, const X86Subtarget &Subtarget)
sext(add_nsw(x, C)) –> add(sext(x), C_sext) zext(add_nuw(x, C)) –> add(zext(x), C_zext) Promoting a sign/zero extension ahead of a no overflow 'add' exposes opportunities to combine math ops, use an LEA, or use a complex addressing mode.
static SDValue combineToExtendCMOV (SDNode *Extend, SelectionDAG &DAG)
static SDValue combineToExtendBoolVectorInReg (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineExtSetcc (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineSext (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineFMA (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineFMADDSUB (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineZext (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool isOrXorXorTree (SDValue X, bool Root=true)
Recursive helper for combineVectorSizedSetCCEquality() to see if we have a recognizable memcmp expansion.
template<typename F >
static SDValue emitOrXorXorTree (SDValue X, SDLoc &DL, SelectionDAG &DAG, EVT VecVT, EVT CmpVT, bool HasPT, F SToV)
Recursive helper for combineVectorSizedSetCCEquality() to emit the memcmp expansion.
static SDValue combineVectorSizedSetCCEquality (SDNode *SetCC, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Try to map a 128-bit or larger integer comparison to vector instructions before type legalization splits it up into chunks.
static SDValue combineSetCC (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineMOVMSK (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineX86GatherScatter (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineGatherScatter (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineX86SetCC (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineBrCond (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
Optimize branch condition evaluation.
static SDValue combineVectorCompareAndMaskUnaryOp (SDNode *N, SelectionDAG &DAG)
static SDValue combineToFPTruncExtElt (SDNode *N, SelectionDAG &DAG)
If we are converting a value to floating-point, try to replace scalar truncate of an extracted vector element with a bitcast.
static SDValue combineUIntToFP (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineSIntToFP (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static bool needCarryOrOverflowFlag (SDValue Flags)
static bool onlyZeroFlagUsed (SDValue Flags)
static SDValue combineCMP (SDNode *N, SelectionDAG &DAG)
static SDValue combineX86AddSub (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineSBB (SDNode *N, SelectionDAG &DAG)
static SDValue combineADC (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static SDValue combineAddOrSubToADCOrSBB (SDNode *N, SelectionDAG &DAG)
If this is an add or subtract where one operand is produced by a cmp+setcc, then try to convert it to an ADC or SBB.
static SDValue combineLoopMAddPattern (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineLoopSADPattern (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue matchPMADDWD (SelectionDAG &DAG, SDValue Op0, SDValue Op1, const SDLoc &DL, EVT VT, const X86Subtarget &Subtarget)
static SDValue matchPMADDWD_2 (SelectionDAG &DAG, SDValue N0, SDValue N1, const SDLoc &DL, EVT VT, const X86Subtarget &Subtarget)
static SDValue combineAdd (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineSubToSubus (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineSub (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineVectorCompare (SDNode *N, SelectionDAG &DAG, const X86Subtarget &Subtarget)
static SDValue combineConcatVectorOps (const SDLoc &DL, MVT VT, ArrayRef< SDValue > Ops, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
Helper that combines an array of subvector ops as if they were the operands of a ISD::CONCAT_VECTORS node, but may have come from another source (e.g.
static SDValue combineConcatVectors (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineInsertSubvector (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue narrowExtractedVectorSelect (SDNode *Ext, SelectionDAG &DAG)
If we are extracting a subvector of a vector select and the select condition is composed of concatenated vectors, try to narrow the select width.
static SDValue combineExtractSubvector (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineScalarToVector (SDNode *N, SelectionDAG &DAG)
static SDValue combinePMULDQ (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineExtInVec (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const X86Subtarget &Subtarget)
static SDValue combineKSHIFT (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI)
static bool matchAsm (StringRef S, ArrayRef< const char *> Pieces)
static bool clobbersFlagRegisters (const SmallVector< StringRef, 4 > &AsmPieces)
static X86::CondCode parseConstraintCode (llvm::StringRef Constraint)
static bool isGRClass (const TargetRegisterClass &RC)
Check if RC is a general purpose register class.
static bool isFRClass (const TargetRegisterClass &RC)
Check if RC is a vector register class.
static bool isVKClass (const TargetRegisterClass &RC)
Check if RC is a mask register class.
Variables
static cl::opt< int > ExperimentalPrefLoopAlignment ("x86-experimental-pref-loop-alignment", cl::init(4), cl::desc("Sets the preferable loop alignment for experiments (as log2 bytes)" "(the last x86-experimental-pref-loop-alignment bits" " of the loop header PC will be 0)."), cl::Hidden)
static cl::opt< bool > EnableOldKNLABI ("x86-enable-old-knl-abi", cl::init(false), cl::desc("Enables passing v32i16 and v64i8 in 2 YMM registers instead of " "one ZMM register on AVX512F, but not AVX512BW targets."), cl::Hidden)
static cl::opt< bool > MulConstantOptimization ("mul-constant-optimization", cl::init(true), cl::desc("Replace 'mul x, Const' with more effective instructions like " "SHIFT, LEA, etc."), cl::Hidden)
static cl::opt< bool > ExperimentalUnorderedISEL ("x86-experimental-unordered-atomic-isel", cl::init(false), cl::desc("Use LoadSDNode and StoreSDNode instead of " "AtomicSDNode for unordered atomic loads and " "stores respectively."), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-isel"
Definition at line 66 of file X86ISelLowering.cpp.
Enumeration Type Documentation
ShrinkMode
enum ShrinkMode strong
Different mul shrinking modes.
Enumerator
MULS8
MULU8
MULS16
MULU16
Definition at line 38887 of file X86ISelLowering.cpp.
StructReturnType
enum StructReturnType
CallIsStructReturn - Determines whether a call uses struct return semantics.
Enumerator
NotStructReturn
RegStructReturn
StackStructReturn
Definition at line 3096 of file X86ISelLowering.cpp.
Function Documentation
argsAreStructReturn()
static StructReturnType argsAreStructReturn (ArrayRef< ISD::InputArg > Ins, bool IsMCU) static
Determines whether a function uses struct return semantics.
Definition at line 3116 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::empty(), llvm::ISD::ArgFlagsTy::isInReg(), llvm::ISD::ArgFlagsTy::isSRet(), NotStructReturn, RegStructReturn, and StackStructReturn.
Referenced by isSortedByValueNo().
buildFromShuffleMostly()
static SDValue buildFromShuffleMostly (SDValue Op, SelectionDAG & DAG) static
Definition at line 8677 of file X86ISelLowering.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), getUnderlyingExtractedFromVec(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::BitmaskEnumDetail::Mask(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase::size(), and llvm::ISD::UNDEF.
Referenced by LowerBUILD_VECTORAsVariablePermute().
callIsStructReturn()
static StructReturnType callIsStructReturn (ArrayRef< ISD::OutputArg > Outs, bool IsMCU) static
Definition at line 3102 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::empty(), llvm::ISD::ArgFlagsTy::isInReg(), llvm::ISD::ArgFlagsTy::isSRet(), NotStructReturn, RegStructReturn, and StackStructReturn.
Referenced by getMOVL().
canGuaranteeTCO()
static bool canGuaranteeTCO (CallingConv::ID CC) static
Return true if the calling convention is one that we can guarantee TCO for.
Definition at line 3143 of file X86ISelLowering.cpp.
References llvm::CallingConv::Fast, llvm::CallingConv::GHC, llvm::CallingConv::HHVM, llvm::CallingConv::HiPE, llvm::CallingConv::Tail, and llvm::CallingConv::X86_RegCall.
Referenced by getMOVL(), isSortedByValueNo(), MatchingStackOffset(), mayTailCallThisCC(), and shouldGuaranteeTCO().
canLowerByDroppingEvenElements()
static int canLowerByDroppingEvenElements (ArrayRef< int > Mask, bool IsSingleInput) static
Check whether a compaction lowering can be done by dropping even elements and compute how many times even elements must be dropped.
This handles shuffles which take every Nth element where N is a power of two. Example shuffle masks:
N = 1: 0, 2, 4, 6, 8, 10, 12, 14, 0, 2, 4, 6, 8, 10, 12, 14 N = 1: 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30 N = 2: 0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12, 0, 4, 8, 12 N = 2: 0, 4, 8, 12, 16, 20, 24, 28, 0, 4, 8, 12, 16, 20, 24, 28 N = 3: 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8 N = 3: 0, 8, 16, 24, 0, 8, 16, 24, 0, 8, 16, 24, 0, 8, 16, 24
Any of these lanes can of course be undef.
This routine only supports N <= 3. FIXME: Evaluate whether either AVX or AVX-512 have any opportunities here for larger N.
Returns
N above, or the number of times even elements must be dropped if there is such a number. Otherwise returns zero.
Definition at line 14305 of file X86ISelLowering.cpp.
References llvm::array_lengthof(), assert(), llvm::numbers::e, llvm::isPowerOf2_32(), and llvm::ArrayRef< T >::size().
Referenced by lowerV16I8Shuffle().
canonicalizeBitSelect()
static SDValue canonicalizeBitSelect (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40383 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, assert(), llvm::numbers::e, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), getTargetConstantBitsFromNode(), llvm::X86Subtarget::hasAVX512(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasVLX(), llvm::X86Subtarget::hasXOP(), llvm::ISD::OR, llvm::peekThroughBitcasts(), X, and Y.
Referenced by combineOr().
canonicalizeShuffleMaskWithCommute()
static bool canonicalizeShuffleMaskWithCommute (ArrayRef< int > Mask) static
Helper function that returns true if the shuffle mask should be commuted to improve canonicalization.
Definition at line 17232 of file X86ISelLowering.cpp.
References assert(), Size, and llvm::ArrayRef< T >::size().
Referenced by combineX86ShufflesRecursively(), and lowerVECTOR_SHUFFLE().
canReduceVMulWidth()
static bool canReduceVMulWidth (SDNode * N, SelectionDAG & DAG, ShrinkMode & Mode) static
Definition at line 38889 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), MULS16, MULS8, MULU16, MULU8, and llvm::SelectionDAG::SignBitIsZero().
Referenced by combineLoopMAddPattern(), matchPMADDWD(), and reduceVMULWidth().
canWidenShuffleElements() [1/3]
static bool canWidenShuffleElements (ArrayRef< int > Mask, SmallVectorImpl< int > & WidenedMask) static
Helper function to test whether a shuffle mask could be simplified by widening the elements being shuffled.
Appends the mask for wider elements in WidenedMask if valid. Otherwise leaves it in an unspecified state.
NOTE: This must handle normal vector shuffle masks and target vector shuffle masks. The latter have the special property of a '-2' representing a zero-ed lane of a vector.
Definition at line 5443 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorImpl< T >::assign(), Size, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by canWidenShuffleElements(), combineExtractWithShuffle(), combineX86ShufflesRecursively(), LowerShift(), lowerShuffleAsBlendAndPermute(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), and lowerVECTOR_SHUFFLE().
canWidenShuffleElements() [2/3]
static bool canWidenShuffleElements (ArrayRef< int > Mask, const APInt & Zeroable, bool V2IsZero, SmallVectorImpl< int > & WidenedMask) static
Definition at line 5493 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), canWidenShuffleElements(), llvm::ArrayRef< T >::end(), llvm::APInt::isNullValue(), Size, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
canWidenShuffleElements() [3/3]
static bool canWidenShuffleElements (ArrayRef< int > Mask) static
Definition at line 5509 of file X86ISelLowering.cpp.
References canWidenShuffleElements().
checkAndUpdateEFLAGSKill()
static bool checkAndUpdateEFLAGSKill (MachineBasicBlock::iterator SelectItr, MachineBasicBlock * BB, const TargetRegisterInfo * TRI) static
Definition at line 30651 of file X86ISelLowering.cpp.
References llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineInstr::readsRegister(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by createPHIsForCMOVsInSinkBB().
checkBitcastSrcVectorSize()
static bool checkBitcastSrcVectorSize (SDValue Src, unsigned Size) static
Definition at line 36181 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::ISD::OR, llvm::ISD::SETCC, Size, and llvm::ISD::XOR.
Referenced by combineBitcastvxi1().
checkBoolTestAndOrSetCCCombine()
static bool checkBoolTestAndOrSetCCCombine (SDValue Cond, X86::CondCode & CC0, X86::CondCode & CC1, SDValue & Flags, bool & isAnd) static
Check whether Cond is an AND/OR of SETCCs off of the same EFLAGS.
Match: (X86or (X86setcc) (X86setcc)) (X86cmp (and (X86setcc) (X86setcc)), 0)
Definition at line 38561 of file X86ISelLowering.cpp.
checkBoolTestSetCCCombine()
static SDValue checkBoolTestSetCCCombine (SDValue Cmp, X86::CondCode & CC) static
Definition at line 38443 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), C, llvm::X86ISD::CMOV, llvm::X86ISD::CMP, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::dyn_cast(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::X86::GetOppositeBranchCondition(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasAnyUseOfValue(), llvm::isOneConstant(), LLVM_FALLTHROUGH, llvm::X86ISD::RDRAND, llvm::X86ISD::RDSEED, llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::X86ISD::SUB, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSetCCEFLAGS().
clobbersFlagRegisters()
static bool clobbersFlagRegisters (const SmallVector< StringRef, 4 > & AsmPieces) static
Definition at line 46287 of file X86ISelLowering.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::count(), llvm::SmallVectorTemplateCommon< T >::end(), and llvm::SmallVectorBase::size().
Referenced by llvm::X86TargetLowering::ExpandInlineAsm().
collectConcatOps()
static bool collectConcatOps (SDNode * N, SmallVectorImpl< SDValue > & Ops) static
Definition at line 5731 of file X86ISelLowering.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::ISD::CONCAT_VECTORS, llvm::SmallVectorBase::empty(), llvm::SDNode::getConstantOperandAPInt(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::isNullConstant(), llvm::SDNode::op_begin(), llvm::SDNode::op_end(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by combineInsertSubvector(), IsNOT(), LowerStore(), and narrowExtractedVectorSelect().
combineADC()
static SDValue combineADC (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 44577 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::ISD::AND, combineCarryThroughADD(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::X86::COND_B, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i8, llvm::X86::isZeroNode(), llvm::X86ISD::SETCC_CARRY, and llvm::SDValue::use_empty().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineAdd()
static SDValue combineAdd (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45139 of file X86ISelLowering.cpp.
References combineAddOrSubToADCOrSBB(), combineLoopMAddPattern(), combineLoopSADPattern(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86ISD::HADD, llvm::X86Subtarget::hasSSSE3(), llvm::SDNodeFlags::hasVectorReduction(), llvm::MVT::i1, isHorizontalBinOp(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MipsISD::MAdd, matchPMADDWD(), matchPMADDWD_2(), llvm::ISD::SIGN_EXTEND, SplitOpsAndApply(), llvm::ISD::SUB, llvm::MVT::v16i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineAddOrSubToADCOrSBB()
static SDValue combineAddOrSubToADCOrSBB (SDNode * N, SelectionDAG & DAG) static
If this is an add or subtract where one operand is produced by a cmp+setcc, then try to convert it to an ADC or SBB.
This replaces TEST+SET+{ADD/SUB} with CMP+{ADC, SBB}.
Definition at line 44613 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::CMP, llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::MVT::i8, llvm::EVT::isInteger(), llvm::X86::isZeroNode(), llvm::X86ISD::SBB, llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::ISD::SUB, llvm::X86ISD::SUB, std::swap(), X, Y, llvm::Z, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAdd(), and combineSub().
combineAnd()
static SDValue combineAnd (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 40260 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::ISD::AND, combineAndLoadToBZHI(), combineAndMaskToShift(), combineANDXORWithAllOnesIntoANDNP(), combineBitcastvxi1(), combineCompareEqual(), combineParity(), combineScalarAndWithMaskSetcc(), combineX86ShufflesRecursively(), convertIntLogicToFPLogic(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::X86ISD::FAND, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::APInt::getHighBitsSet(), llvm::EVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::APInt::isAllOnesValue(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::APInt::isNullValue(), llvm::SDNode::isOnlyUserOf(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::SelectionDAG::MaskedValueIsZero(), matchScalarReduction(), llvm::ISD::SETEQ, llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::ISD::TRUNCATE, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineAndLoadToBZHI()
static SDValue combineAndLoadToBZHI (SDNode * Node, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40050 of file X86ISelLowering.cpp.
Referenced by combineAnd().
combineAndMaskToShift()
static SDValue combineAndMaskToShift (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
If this is a zero/all-bits result that is bitwise-anded with a low bits mask.
(Mask == 1 for the x86 lowering of a SETCC + ZEXT), replace the 'and' with a shift-right to eliminate loading the vector constant mask value.
Definition at line 39976 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::APInt::countTrailingOnes(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i8, llvm::isBitwiseNot(), llvm::ISD::isConstantSplatVector(), llvm::APInt::isMask(), llvm::EVT::isSimple(), llvm::peekThroughBitcasts(), llvm::ISD::SRL, SupportedVectorShiftWithImm(), and llvm::X86ISD::VSRLI.
Referenced by combineAnd().
combineAndnp()
static SDValue combineAndnp (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Do target-specific dag combines on X86ISD::ANDNP nodes.
Definition at line 43079 of file X86ISelLowering.cpp.
References llvm::ISD::AND, combineX86ShufflesRecursively(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDNode::getSimpleValueType(), llvm::ISD::isBuildVectorAllZeros(), IsNOT(), and llvm::MVT::isVector().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineANDXORWithAllOnesIntoANDNP()
static SDValue combineANDXORWithAllOnesIntoANDNP (SDNode * N, SelectionDAG & DAG) static
Try to fold: (and (xor X, -1), Y) -> (andnp X, Y).
Definition at line 39843 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), IsNOT(), X, and Y.
Referenced by combineAnd().
combineBasicSADPattern()
static SDValue combineBasicSADPattern (SDNode * Extract, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 36955 of file X86ISelLowering.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::ANY_EXTEND, createPSADBW(), detectZextAbsDiff(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE2(), llvm::EVT::isSimple(), llvm::Log2_32(), llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::matchBinOpReduction(), llvm::ISD::SIGN_EXTEND, llvm::X86Subtarget::useBWIRegs(), and llvm::ISD::ZERO_EXTEND.
Referenced by combineExtractVectorElt().
combineBEXTR()
static SDValue combineBEXTR (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 42782 of file X86ISelLowering.cpp.
References llvm::X86ISD::BEXTR, llvm::SelectionDAG::getConstant(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), and llvm::TargetLowering::SimplifyDemandedBits().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineBitcast()
static SDValue combineBitcast (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 36461 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, C, combineBitcastvxi1(), combineCastedMaskArithmetic(), combinevXi1ConstantToInteger(), llvm::ISD::CONCAT_VECTORS, llvm::countLeadingZeros(), createMMXBuildVector(), llvm::numbers::e, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FAND, llvm::X86ISD::FOR, llvm::ISD::FP_TO_SINT, llvm::X86ISD::FXOR, llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasDQI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::APFloatBase::IEEEdouble(), llvm::EVT::is128BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::ISD::isNormalLoad(), llvm::isNullConstant(), llvm::EVT::isScalarInteger(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::X86ISD::MMX_MOVW2D, llvm::X86ISD::MOVDQ2Q, llvm::X86ISD::MOVMSK, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::ISD::OR, llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SmallVectorImpl< T >::resize(), llvm::ISD::SETCC, llvm::ISD::SETLT, llvm::ISD::TRUNCATE, llvm::MVT::v16i1, llvm::MVT::v2f32, llvm::MVT::v2i1, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i1, llvm::MVT::v8i8, llvm::X86ISD::VBROADCAST_LOAD, llvm::MVT::x86mmx, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineBitcastvxi1()
static SDValue combineBitcastvxi1 (SelectionDAG & DAG, EVT VT, SDValue Src, const SDLoc & DL, const X86Subtarget & Subtarget) static
Definition at line 36217 of file X86ISelLowering.cpp.
References checkBitcastSrcVectorSize(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPMOVMSKB(), llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i32, llvm::EVT::isSimple(), llvm::X86ISD::MOVMSK, llvm::X86ISD::PACKSS, llvm::ISD::SIGN_EXTEND, signExtendBitcastSrcVector(), llvm::MVT::SimpleTy, llvm::ISD::TRUNCATE, llvm::MVT::v16i1, llvm::MVT::v16i8, llvm::MVT::v2i1, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v32i8, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8i1, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by combineAnd(), combineBitcast(), combineExtractVectorElt(), combineHorizontalPredicateResult(), and combineOr().
combineBrCond()
static SDValue combineBrCond (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Optimize branch condition evaluation.
Definition at line 44131 of file X86ISelLowering.cpp.
References combineSetCCEFLAGS(), llvm::SDNode::getConstantOperandVal(), and llvm::SDNode::getOperand().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineBT()
static SDValue combineBT (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 43107 of file X86ISelLowering.cpp.
References llvm::X86ISD::BT, llvm::SelectionDAG::GetDemandedBits(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::i32, and llvm::Log2_32().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineCarryThroughADD()
static SDValue combineCarryThroughADD (SDValue EFLAGS, SelectionDAG & DAG) static
Definition at line 38602 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::X86::COND_A, llvm::X86::COND_B, llvm::X86::COND_E, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValueType(), llvm::SDNode::getVTList(), llvm::SDNode::hasOneUse(), llvm::isAllOnesConstant(), llvm::EVT::isInteger(), llvm::isOneConstant(), llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::ISD::SIGN_EXTEND, llvm::X86ISD::SUB, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineADC(), combineSBB(), and combineSetCCEFLAGS().
combineCastedMaskArithmetic()
static SDValue combineCastedMaskArithmetic (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 36334 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, combinevXi1ConstantToInteger(), llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86Subtarget::hasAVX512(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::EVT::isScalarInteger(), llvm::EVT::isVector(), llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by combineBitcast().
combineCMov()
static SDValue combineCMov (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Optimize X86ISD::CMOV [LHS, RHS, CONDCODE (e.g. X86::COND_NE), CONDVAL].
Definition at line 38666 of file X86ISelLowering.cpp.
References llvm::SDNode::getConstantOperandVal(), and llvm::SDNode::getOperand().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineCMP()
static SDValue combineCMP (SDNode * N, SelectionDAG & DAG) static
Definition at line 44433 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::X86ISD::AND, llvm::ISD::AND, llvm::X86ISD::CMP, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandAPInt(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::APInt::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::isNullConstant(), llvm::APInt::isSignedIntN(), needCarryOrOverflowFlag(), onlyZeroFlagUsed(), llvm::X86ISD::OR, llvm::ISD::OR, llvm::ISD::SHL, llvm::ISD::SRL, llvm::ISD::SUB, llvm::X86ISD::SUB, llvm::ISD::TRUNCATE, llvm::APInt::ult(), llvm::X86ISD::XOR, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineCompareEqual()
static SDValue combineCompareEqual (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Recognize the distinctive (AND (setcc ...) (setcc ..)) where both setccs reference the same FP CMP, and rewrite for CMPEQSS and friends.
Likewise for OR -> CMPNEQSS.
Definition at line 39740 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::X86ISD::CMP, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_P, llvm::ISD::CopyToReg, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FSETCC, llvm::X86ISD::FSETCCM, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::X86Subtarget::is64Bit(), isAndOrOfSetCCs(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT, llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v16i1, llvm::MVT::v1i1, llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAnd(), and combineOr().
combineConcatVectorOps()
static SDValue combineConcatVectorOps (const SDLoc & DL, MVT VT, ArrayRef< SDValue > Ops, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Helper that combines an array of subvector ops as if they were the operands of a ISD::CONCAT_VECTORS node, but may have come from another source (e.g.
ISD::INSERT_SUBVECTOR). The ops are assumed to be of the same type.
Definition at line 45348 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::TargetLoweringBase::allowsMemoryAccess(), assert(), llvm::ISD::CONCAT_VECTORS, EltsFromConsecutiveLoads(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::CallingConv::Fast, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::getTargetLowering(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasInt256(), llvm::MVT::is256BitVector(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), LLVM_FALLTHROUGH, MayFoldLoad(), llvm::X86ISD::MOVDDUP, llvm::X86ISD::PACKUS, llvm::peekThroughBitcasts(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ArrayRef< T >::size(), llvm::X86ISD::SUBV_BROADCAST, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v8f32, llvm::MVT::v8i32, llvm::X86ISD::VBROADCAST, and llvm::X86ISD::VPERMILPI.
Referenced by combineConcatVectors(), and combineInsertSubvector().
combineConcatVectors()
static SDValue combineConcatVectors (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45459 of file X86ISelLowering.cpp.
References combineConcatVectorOps(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86Subtarget::hasAVX(), llvm::MVT::i1, llvm::TargetLoweringBase::isTypeLegal(), llvm::SDNode::op_begin(), and llvm::SDNode::op_end().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineCVTP2I_CVTTP2I()
static SDValue combineCVTP2I_CVTTP2I (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 43042 of file X86ISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::SelectionDAG::getBitcast(), llvm::MVT::getFloatingPointVT(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDValue::hasOneUse(), llvm::tgtok::In, llvm::MVT::is128BitVector(), llvm::ISD::isNormalLoad(), llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::X86ISD::VZEXT_LOAD.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineExtInVec()
static SDValue combineExtInVec (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45892 of file X86ISelLowering.cpp.
References combineX86ShufflesRecursively(), llvm::MipsISD::Ext, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getExtLoad(), llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::SDValue::hasOneUse(), llvm::tgtok::In, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SPII::Load, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, and llvm::ISD::ZEXTLOAD.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineExtractSubvector()
static SDValue combineExtractSubvector (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45658 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::ISD::BUILD_VECTOR, Concat, llvm::ISD::CONCAT_VECTORS, llvm::X86ISD::CVTSI2P, llvm::X86ISD::CVTUI2P, llvm::ISD::EXTRACT_SUBVECTOR, extractSubVector(), llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), getOnesVector(), llvm::SDValue::getOpcode(), getOpcode_EXTEND_VECTOR_INREG(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isBitwiseNot(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::isNullConstant(), llvm::EVT::isSimple(), llvm::TargetLoweringBase::isTypeLegal(), narrowExtractedVectorSelect(), llvm::SDNode::ops(), llvm::MVT::Other, llvm::peekThroughBitcasts(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, split256IntArith(), llvm::ISD::UINT_TO_FP, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VBROADCAST_LOAD, llvm::X86ISD::VFPEXT, llvm::ISD::VSELECT, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineExtractVectorElt()
static SDValue combineExtractVectorElt (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Detect vector gather/scatter index generation and convert it from being a bunch of shuffles and extracts into a somewhat faster sequence.
For i686, the best sequence is apparently storing the value and loading scalars back, while for x64 we should use 64-bit extracts and shifts.
Definition at line 37381 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::ISD::AND, assert(), llvm::ISD::BITCAST, combineBasicSADPattern(), combineBitcastvxi1(), combineExtractWithShuffle(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineReductionToHorizontal(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::APInt::getOneBitSet(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSizeInBits(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::isInteger(), llvm::isNullConstant(), llvm::X86ISD::MMX_MOVD2W, llvm::X86ISD::PINSRB, llvm::X86ISD::PINSRW, llvm::SmallVectorTemplateBase< T >::push_back(), scalarizeExtEltFP(), llvm::ISD::SETEQ, llvm::TargetLowering::SimplifyDemandedBits(), llvm::SmallVectorBase::size(), llvm::ISD::TRUNCATE, llvm::SDNode::uses(), llvm::MVT::v1i64, llvm::MVT::v2i32, and llvm::MVT::x86mmx.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineExtractWithShuffle()
static SDValue combineExtractWithShuffle (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 37038 of file X86ISelLowering.cpp.
References assert(), canWidenShuffleElements(), llvm::numbers::e, extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::EVT::getSizeInBits(), getTargetShuffleInputs(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i32, llvm::EVT::is128BitVector(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::EVT::isFloatingPoint(), llvm::isNullConstant(), llvm::MipsISD::Lo, llvm::SPII::Load, llvm::BitmaskEnumDetail::Mask(), llvm::peekThroughBitcasts(), llvm::X86ISD::PEXTRB, llvm::X86ISD::PEXTRW, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::ISD::TRUNCATE, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::X86ISD::VBROADCAST, and llvm::X86ISD::VBROADCAST_LOAD.
Referenced by combineExtractVectorElt().
combineExtSetcc()
static SDValue combineExtSetcc (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 43433 of file X86ISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::MVT::f32, llvm::MVT::f64, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::X86Subtarget::hasAVX512(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::isUnsignedIntSetCC(), llvm::EVT::isVector(), llvm::ISD::SETCC, Size, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSext(), and combineZext().
combineFaddFsub()
static SDValue combineFaddFsub (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Do target-specific dag combines on floating-point adds/subs.
Definition at line 41933 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FSUB, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE3(), isHorizontalBinOp(), llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v8f32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFAnd()
static SDValue combineFAnd (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Do target-specific dag combines on X86ISD::FAND nodes.
Definition at line 42864 of file X86ISelLowering.cpp.
References combineFAndFNotToFAndn(), getNullFPConstForNullVal(), llvm::SDNode::getOperand(), and lowerX86FPLogicOp().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFAndFNotToFAndn()
static SDValue combineFAndFNotToFAndn (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 42832 of file X86ISelLowering.cpp.
References C, llvm::dyn_cast(), llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FANDN, llvm::X86ISD::FXOR, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::isBuildVectorAllOnes(), and llvm::MVT::v4f32.
Referenced by combineFAnd().
combineFAndn()
static SDValue combineFAndn (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Do target-specific dag combines on X86ISD::FANDN nodes.
Definition at line 42881 of file X86ISelLowering.cpp.
References getNullFPConstForNullVal(), llvm::SDNode::getOperand(), isNullFPScalarOrVectorConst(), and lowerX86FPLogicOp().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFMA()
static SDValue combineFMA (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 43514 of file X86ISelLowering.cpp.
References B, C, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAnyFMA(), llvm::Function::hasOptSize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isNullConstant(), llvm::TargetLoweringBase::isTypeLegal(), and negateFMAOpcode().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFMADDSUB()
static SDValue combineFMADDSUB (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 43576 of file X86ISelLowering.cpp.
References llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLowering::getNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::Function::hasOptSize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::TargetLowering::isNegatibleForFree(), and negateFMAOpcode().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFMinFMax()
static SDValue combineFMinFMax (SDNode * N, SelectionDAG & DAG) static
Do target-specific dag combines on X86ISD::FMIN and X86ISD::FMAX nodes.
Definition at line 42914 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::FMAX, llvm::X86ISD::FMAXC, llvm::X86ISD::FMIN, llvm::X86ISD::FMINC, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTarget(), llvm::SDNode::getValueType(), llvm_unreachable, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetOptions::NoSignedZerosFPMath, and llvm::TargetMachine::Options.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFMinNumFMaxNum()
static SDValue combineFMinNumFMaxNum (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 42935 of file X86ISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FMAX, llvm::ISD::FMAXNUM, llvm::X86ISD::FMIN, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SDNode::getFlags(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::Function::hasMinSize(), llvm::SDNodeFlags::hasNoNaNs(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::SelectionDAG::isKnownNeverNaN(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::TargetOptions::NoNaNsFPMath, llvm::TargetMachine::Options, llvm::ISD::SETUO, and llvm::X86Subtarget::useSoftFloat().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineFneg()
static SDValue combineFneg (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Do target-specific dag combines on floating point negations.
Definition at line 42564 of file X86ISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FMA, llvm::X86ISD::FMADD_RND, llvm::X86ISD::FMSUB, llvm::X86ISD::FMSUB_RND, llvm::ISD::FMUL, llvm::X86ISD::FNMADD, llvm::X86ISD::FNMADD_RND, llvm::X86ISD::FNMSUB, llvm::X86ISD::FNMSUB_RND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAnyFMA(), llvm::SDNodeFlags::hasNoSignedZeros(), llvm::SDValue::hasOneUse(), isFNEG(), llvm::TargetLoweringBase::isTypeLegal(), negateFMAOpcode(), and llvm::SDNode::ops().
Referenced by combineFOr(), combineXor(), and llvm::X86TargetLowering::PerformDAGCombine().
combineFOr()
static SDValue combineFOr (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Do target-specific dag combines on X86ISD::FOR and X86ISD::FXOR nodes.
Definition at line 42895 of file X86ISelLowering.cpp.
References assert(), combineFneg(), llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), isNullFPScalarOrVectorConst(), and lowerX86FPLogicOp().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineGatherScatter()
static SDValue combineGatherScatter (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 44005 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::APInt::getSignMask(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::BitmaskEnumDetail::Mask(), N, llvm::ISD::SIGN_EXTEND, llvm::TargetLowering::SimplifyDemandedBits(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineHorizontalMinMaxResult()
static SDValue combineHorizontalMinMaxResult (SDNode * Extract, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 36748 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, extractSubVector(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i8, llvm::MipsISD::Lo, llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::matchBinOpReduction(), llvm::X86ISD::PHMINPOS, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::Upper, llvm::MVT::v16i8, llvm::MVT::v8i16, and llvm::ISD::XOR.
Referenced by combineExtractVectorElt().
combineHorizontalPredicateResult()
static SDValue combineHorizontalPredicateResult (SDNode * Extract, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 36825 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), combineBitcastvxi1(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::CTPOP, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MVT::getFloatingPointVT(), llvm::EVT::getIntegerVT(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), getPMOVMSKB(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasVLX(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MipsISD::Lo, llvm::Match, llvm::SelectionDAG::matchBinOpReduction(), llvm::ISD::OR, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::SelectionDAG::SplitVector(), llvm::ISD::SUB, and llvm::ISD::XOR.
Referenced by combineExtractVectorElt().
combineInsertSubvector()
static SDValue combineInsertSubvector (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45480 of file X86ISelLowering.cpp.
References collectConcatOps(), combineConcatVectorOps(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::ISD::INSERT_SUBVECTOR, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isBuildVectorAllZeros(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SmallVectorBase::size(), llvm::X86ISD::VBROADCAST, and llvm::X86ISD::VBROADCAST_LOAD.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineKSHIFT()
static SDValue combineKSHIFT (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 45931 of file X86ISelLowering.cpp.
References llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::isBuildVectorAllZeros(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineLoad()
static SDValue combineLoad (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 41254 of file X86ISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::ISD::CONCAT_VECTORS, llvm::MipsISD::Ext, llvm::CallingConv::Fast, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::MachineMemOperand::getFlags(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i1, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MinAlign(), N, llvm::ISD::NON_EXTLOAD, llvm::MVT::Other, and llvm::ISD::TokenFactor.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineLogicBlendIntoConditionalNegate()
static SDValue combineLogicBlendIntoConditionalNegate (EVT VT, SDValue Mask, SDValue X, SDValue Y, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 37837 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::ISD::isBuildVectorAllZeros(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isOperationLegal(), llvm::BitmaskEnumDetail::Mask(), N, llvm::ISD::SUB, std::swap(), X, llvm::ISD::XOR, and Y.
Referenced by combineLogicBlendIntoPBLENDV().
combineLogicBlendIntoPBLENDV()
static SDValue combineLogicBlendIntoPBLENDV (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40470 of file X86ISelLowering.cpp.
References assert(), combineLogicBlendIntoConditionalNegate(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::getBitcast(), llvm::SDNode::getOpcode(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::is256BitVector(), llvm::EVT::isInteger(), llvm::BitmaskEnumDetail::Mask(), matchLogicBlend(), llvm::ISD::OR, llvm::peekThroughBitcasts(), llvm::MVT::v16i8, llvm::MVT::v32i8, X, and Y.
Referenced by combineOr().
combineLoopMAddPattern()
static SDValue combineLoopMAddPattern (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 44769 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, canReduceVMulWidth(), Concat, llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::SDNode::isOnlyUserOf(), llvm::EVT::isVector(), Mode, llvm::ISD::MUL, MULU16, llvm::SDNodeFlags::setVectorReduction(), SplitOpsAndApply(), llvm::ISD::TRUNCATE, and llvm::X86ISD::VPMADDWD.
Referenced by combineAdd().
combineLoopSADPattern()
static SDValue combineLoopSADPattern (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 44833 of file X86ISelLowering.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, createPSADBW(), detectZextAbsDiff(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i32, llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::SDNodeFlags::setVectorReduction(), std::swap(), and llvm::X86Subtarget::useBWIRegs().
Referenced by combineAdd().
combineMaskedLoad()
static SDValue combineMaskedLoad (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 41456 of file X86ISelLowering.cpp.
References combineMaskedLoadConstantMask(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::X86Subtarget::hasAVX512(), llvm::MaskedLoadSDNode::isExpandingLoad(), N, llvm::ISD::NON_EXTLOAD, and reduceMaskedLoadToScalarLoad().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineMaskedLoadConstantMask()
static SDValue combineMaskedLoadConstantMask (MaskedLoadSDNode * ML, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 41408 of file X86ISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedLoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::SelectionDAG::getLoad(), llvm::MaskedLoadSDNode::getMask(), llvm::SelectionDAG::getMaskedLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::MaskedLoadSDNode::getOffset(), llvm::SDNode::getOperand(), llvm::MaskedLoadSDNode::getPassThru(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), and llvm::MaskedLoadStoreSDNode::isUnindexed().
Referenced by combineMaskedLoad().
combineMaskedStore()
static SDValue combineMaskedStore (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 41504 of file X86ISelLowering.cpp.
References llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedStoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MaskedStoreSDNode::getMask(), llvm::SelectionDAG::getMaskedStore(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::MaskedStoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::APInt::getSignMask(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MaskedStoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), llvm::MaskedStoreSDNode::isCompressingStore(), llvm::MaskedStoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::BitmaskEnumDetail::Mask(), N, reduceMaskedStoreToScalarStore(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::ISD::TRUNCATE.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineMOVMSK()
static SDValue combineMOVMSK (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 43944 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::numbers::e, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandAPInt(), llvm::APInt::getLowBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i32, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::APInt::isNegative(), IsNOT(), llvm::SDValue::isUndef(), llvm::X86ISD::MOVMSK, llvm::APInt::setBit(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineMul()
static SDValue combineMul (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Optimize a single multiply with constant into two operations in order to implement it with two cheaper instructions, e.g.
LEA + SHL, LEA + LEA.
Definition at line 39201 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), C, combineMulSpecial(), combineMulToPMADDWD(), combineMulToPMULDQ(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::Function::hasMinSize(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, INT64_MIN, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::isPowerOf2_64(), llvm::EVT::isVector(), llvm::Log2_64(), llvm::X86ISD::MUL_IMM, MulConstantOptimization, N, reduceVMULWidth(), llvm::ISD::SHL, llvm::X86Subtarget::slowLEA(), llvm::ISD::SUB, std::swap(), UINT64_MAX, and llvm::SDNode::use_begin().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineMulSpecial()
static SDValue combineMulSpecial (uint64_t MulAmt, SDNode * N, SelectionDAG & DAG, EVT VT, const SDLoc & DL) static
Definition at line 39021 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::countTrailingZeros(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MVT::i8, llvm::isPowerOf2_64(), llvm::Log2_64(), llvm::X86ISD::MUL_IMM, llvm::MipsISD::Mult, llvm::ISD::SHL, and llvm::ISD::SUB.
Referenced by combineMul().
combineMulToPMADDWD()
static SDValue combineMulToPMADDWD (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 39109 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getBitcast(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::X86Subtarget::isPMADDWDSlow(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::SelectionDAG::MaskedValueIsZero(), SplitOpsAndApply(), llvm::MVT::v2i32, llvm::X86ISD::VPMADDWD, and llvm::ISD::ZERO_EXTEND.
Referenced by combineMul().
combineMulToPMULDQ()
static SDValue combineMulToPMULDQ (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 39157 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i64, llvm::isPowerOf2_32(), llvm::EVT::isVector(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::X86ISD::PMULDQ, llvm::X86ISD::PMULUDQ, and SplitOpsAndApply().
Referenced by combineMul().
combineOr()
static SDValue combineOr (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 40755 of file X86ISelLowering.cpp.
References canonicalizeBitSelect(), combineBitcastvxi1(), combineCompareEqual(), combineLogicBlendIntoPBLENDV(), combineOrShiftToFunnelShift(), combineX86ShufflesRecursively(), convertIntLogicToFPLogic(), llvm::X86ISD::FOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), matchScalarReduction(), llvm::ISD::OR, llvm::ISD::SETNE, llvm::SmallVectorBase::size(), llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineOrCmpEqZeroToCtlzSrl()
static SDValue combineOrCmpEqZeroToCtlzSrl (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 40543 of file X86ISelLowering.cpp.
References llvm::EVT::bitsGE(), llvm::MVT::bitsGE(), llvm::X86ISD::CMP, llvm::X86::COND_E, llvm::SDNode::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::X86Subtarget::getTargetLowering(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::X86TargetLowering::isCtlzFast(), llvm::isNullConstant(), lowerX86CmpEqZeroToCtlzSrl(), N, llvm::ISD::OR, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MipsISD::Ret, llvm::X86ISD::SETCC, llvm::SmallVectorBase::size(), std::swap(), and llvm::ISD::ZERO_EXTEND.
Referenced by combineZext().
combineOrShiftToFunnelShift()
static SDValue combineOrShiftToFunnelShift (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40622 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::tgtok::Bits, llvm::dyn_cast(), llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::SDValue::getConstantOperandAPInt(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::X86Subtarget::isSHLDSlow(), llvm::ISD::OR, llvm::ISD::SHL, llvm::SelectionDAG::shouldOptForSize(), llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::ISD::TRUNCATE, and llvm::ISD::XOR.
Referenced by combineOr().
combineParity()
static SDValue combineParity (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40130 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86::COND_NP, llvm::ISD::CTPOP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), getSETCC(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDValue::hasOneUse(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::isOneConstant(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MipsISD::Lo, llvm::ISD::SRL, llvm::ISD::TRUNCATE, X, llvm::X86ISD::XOR, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAnd().
combinePMULDQ()
static SDValue combinePMULDQ (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45840 of file X86ISelLowering.cpp.
References llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::SDValue::hasOneUse(), llvm::ISD::isBuildVectorAllZeros(), llvm::SelectionDAG::isConstantIntBuildVectorOrConstantInt(), llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::TargetLowering::SimplifyDemandedBits(), llvm::MVT::v2i64, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combinePMULH()
static SDValue combinePMULH (SDValue Src, EVT VT, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 42189 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::ISD::isConstantSplatVector(), llvm::EVT::isVector(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRL, and llvm::ISD::ZERO_EXTEND.
Referenced by combineTruncate().
combineReductionToHorizontal()
static SDValue combineReductionToHorizontal (SDNode * ExtElt, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Try to convert a vector reduction sequence composed of binops and shuffles into horizontal ops.
Definition at line 37268 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::CONCAT_VECTORS, extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, extractSubVector(), llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::X86ISD::HADD, llvm::X86Subtarget::hasFastHorizontalOps(), llvm::Function::hasOptSize(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, llvm::isNullConstant(), llvm::isPowerOf2_32(), llvm::MipsISD::Lo, llvm::Log2_32(), llvm::SelectionDAG::matchBinOpReduction(), llvm::X86ISD::PSADBW, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i8.
Referenced by combineExtractVectorElt().
combineRedundantDWordShuffle()
static SDValue combineRedundantDWordShuffle (SDValue N, MutableArrayRef< int > Mask, SelectionDAG & DAG) static
Search for a combinable shuffle across a chain ending in pshufd.
We walk up the chain and look for a combinable shuffle, skipping over shuffles that we could hoist this shuffle's transformation past without altering anything.
Definition at line 34393 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::SmallVectorBase::empty(), llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPSHUFShuffleMask(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i8, llvm::SDNode::isOnlyUserOf(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::RISCVFenceField::W.
Referenced by combineTargetShuffle().
combineSBB()
static SDValue combineSBB (SDNode * N, SelectionDAG & DAG) static
Definition at line 44555 of file X86ISelLowering.cpp.
References combineCarryThroughADD(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SDNode::hasAnyUseOfValue(), llvm::MVT::i32, llvm::isNullConstant(), llvm::X86ISD::SBB, and llvm::ISD::SUB.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineScalarAndWithMaskSetcc()
static SDValue combineScalarAndWithMaskSetcc (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 40201 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, Concat, llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandAPInt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasBWI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::EVT::is512BitVector(), llvm::APInt::isMask(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), and llvm::ISD::SETCC.
Referenced by combineAnd().
combineScalarToVector()
static SDValue combineScalarToVector (SDNode * N, SelectionDAG & DAG) static
Definition at line 45803 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, C, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::isVector(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v1i1, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSelect()
static SDValue combineSelect (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Do target-specific dag combines on SELECT and VSELECT nodes.
Definition at line 37884 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSelectOfTwoConstants()
static SDValue combineSelectOfTwoConstants (SDNode * N, SelectionDAG & DAG) static
Definition at line 37658 of file X86ISelLowering.cpp.
combineSetCC()
static SDValue combineSetCC (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 43859 of file X86ISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, assert(), llvm::ISD::BUILD_VECTOR, combineVectorSizedSetCCEquality(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i8, llvm::ISD::isBuildVectorAllZeros(), llvm::isNullConstant(), llvm::ISD::isSignedIntSetCC(), llvm::EVT::isVector(), LowerVSETCC(), llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SIGN_EXTEND, llvm::ISD::SUB, std::swap(), llvm::ISD::TRUNCATE, llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), and llvm::X86TargetLowering::PerformDAGCombine().
combineSetCCAtomicArith()
static SDValue combineSetCCAtomicArith (SDValue Cmp, X86::CondCode & CC, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Combine: (brcond/cmov/setcc .., (cmp (atomic_load_add x, 1), 0), COND_S) to: (brcond/cmov/setcc .., (LADD x, 1), COND_LE) i.e., reusing the EFLAGS produced by the LOCKed instruction.
Note that this is only legal for some op/cc combinations.
Definition at line 38336 of file X86ISelLowering.cpp.
References llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_SUB, llvm::X86ISD::CMP, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NS, llvm::X86::COND_S, llvm::dyn_cast(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDValue::hasOneUse(), llvm::APInt::isNullValue(), lowerAtomicArithWithLOCK(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::X86ISD::SUB.
Referenced by combineSetCCEFLAGS().
combineSetCCEFLAGS()
static SDValue combineSetCCEFLAGS (SDValue EFLAGS, X86::CondCode & CC, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Optimize an EFLAGS definition used according to the condition code CC into a simpler EFLAGS value, potentially returning a new CC and replacing uses of chain values.
Definition at line 38653 of file X86ISelLowering.cpp.
References checkBoolTestSetCCCombine(), combineCarryThroughADD(), combineSetCCAtomicArith(), and llvm::X86::COND_B.
Referenced by combineBrCond(), and combineX86SetCC().
combineSext()
static SDValue combineSext (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 43474 of file X86ISelLowering.cpp.
References combineExtSetcc(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::isAllOnesConstant(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::EVT::isVector(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), llvm::ISD::SUB, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSextInRegCmov()
static SDValue combineSextInRegCmov (SDNode * N, SelectionDAG & DAG) static
Definition at line 43122 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::X86ISD::CMOV, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSignExtendInReg().
combineShiftLeft()
static SDValue combineShiftLeft (SDNode * N, SelectionDAG & DAG) static
Definition at line 39343 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::Constant, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandAPInt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::APInt::isIntN(), llvm::EVT::isVector(), llvm::X86ISD::SETCC_CARRY, llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineShiftRightArithmetic()
static SDValue combineShiftRightArithmetic (SDNode * N, SelectionDAG & DAG) static
Definition at line 39402 of file X86ISelLowering.cpp.
References llvm::ISD::Constant, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::APInt::isNegative(), llvm::EVT::isVector(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, Size, and llvm::ISD::SRA.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineShiftRightLogical()
static SDValue combineShiftRightLogical (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 39455 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::APInt::countTrailingOnes(), llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::APInt::getMinSignedBits(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::TargetLowering::DAGCombinerInfo::isAfterLegalizeDAG(), llvm::APInt::isMask(), llvm::isPowerOf2_32(), llvm::APInt::lshr(), and llvm::ISD::SRL.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineShuffle()
static SDValue combineShuffle (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 35230 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, combineShuffleOfConcatUndef(), combineShuffleToAddSubOrFMAddSub(), combineTargetShuffle(), combineToConsecutiveLoads(), combineX86ShufflesRecursively(), llvm::X86ISD::CVTP2SI, llvm::X86ISD::CVTP2UI, llvm::X86ISD::CVTSI2P, llvm::X86ISD::CVTTP2SI, llvm::X86ISD::CVTTP2UI, llvm::X86ISD::CVTUI2P, foldShuffleOfHorizOp(), llvm::MemSDNode::getAlignment(), llvm::APInt::getAllOnesValue(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::SDValue::hasOneUse(), llvm::tgtok::In, llvm::ISD::INSERT_SUBVECTOR, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isNormalLoad(), llvm::isNullConstant(), llvm::MemSDNode::isSimple(), isTargetShuffle(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), llvm::ARM_MB::LD, llvm::X86ISD::MCVTP2SI, llvm::X86ISD::MCVTP2UI, llvm::X86ISD::MCVTSI2P, llvm::X86ISD::MCVTTP2SI, llvm::X86ISD::MCVTTP2UI, llvm::X86ISD::MCVTUI2P, llvm::MachineMemOperand::MOLoad, narrowShuffle(), llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86ISD::STRICT_CVTSI2P, llvm::X86ISD::STRICT_CVTTP2SI, llvm::X86ISD::STRICT_CVTTP2UI, llvm::X86ISD::STRICT_CVTUI2P, llvm::X86ISD::STRICT_VFPROUND, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::X86ISD::VFPROUND, llvm::X86ISD::VMFPROUND, llvm::X86ISD::VZEXT_LOAD, and llvm::X86ISD::VZEXT_MOVL.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineShuffleOfConcatUndef()
static SDValue combineShuffleOfConcatUndef (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 35068 of file X86ISelLowering.cpp.
References Concat, llvm::ISD::CONCAT_VECTORS, llvm::MVT::f32, llvm::MVT::f64, llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i32, llvm::MVT::i64, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), N, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by combineShuffle().
combineShuffleToAddSubOrFMAddSub()
static SDValue combineShuffleToAddSubOrFMAddSub (SDNode * N, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to combine a shuffle into a target-specific add-sub or mul-add-sub node.
Definition at line 35032 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADDSUB, combineShuffleToFMAddSub(), llvm::X86ISD::FMADDSUB, llvm::X86ISD::FMSUBADD, llvm::SelectionDAG::getNode(), llvm::SDNode::getSimpleValueType(), llvm::MVT::is512BitVector(), isAddSubOrSubAdd(), and isFMAddSubOrFMSubAdd().
Referenced by combineShuffle().
combineShuffleToFMAddSub()
static SDValue combineShuffleToFMAddSub (SDNode * N, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Combine shuffle of two fma nodes into FMAddSub or FMSubAdd.
Definition at line 34989 of file X86ISelLowering.cpp.
References llvm::ISD::FMA, llvm::X86ISD::FMADDSUB, llvm::X86ISD::FMSUB, llvm::X86ISD::FMSUBADD, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::X86Subtarget::hasAnyFMA(), llvm::SDValue::hasOneUse(), isAddSubOrSubAddMask(), llvm::TargetLoweringBase::isTypeLegal(), N, std::swap(), and llvm::ISD::VECTOR_SHUFFLE.
Referenced by combineShuffleToAddSubOrFMAddSub().
combineSignExtendInReg()
static SDValue combineSignExtendInReg (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 43183 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), combineSextInRegCmov(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasInt256(), llvm::ISD::isNormalLoad(), llvm::ISD::LOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::MVT::v4i32, and llvm::MVT::v4i64.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSIntToFP()
static SDValue combineSIntToFP (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 44274 of file X86ISelLowering.cpp.
References assert(), llvm::X86TargetLowering::BuildFILD(), combineToFPTruncExtElt(), combineVectorCompareAndMaskUnaryOp(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86ISD::CVTSI2P, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f80, llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::X86Subtarget::getTargetLowering(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasDQI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasX87(), llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ISD::isNON_EXTLoad(), llvm::MemSDNode::isSimple(), llvm::SDNode::isStrictFPOpcode(), llvm::EVT::isVector(), llvm::ISD::LOAD, llvm::MVT::Other, P, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::X86ISD::STRICT_CVTSI2P, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::TRUNCATE, llvm::X86Subtarget::useSoftFloat(), llvm::MVT::v2i32, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineStore()
static SDValue combineStore (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 41543 of file X86ISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::ISD::ANY_EXTEND, combinevXi1ConstantToInteger(), llvm::ISD::CONCAT_VECTORS, detectAVGPattern(), detectSSatPattern(), detectUSatPattern(), EmitTruncSStore(), llvm::MipsISD::Ext, llvm::ISD::EXTRACT_VECTOR_ELT, F(), llvm::MVT::f64, llvm::CallingConv::Fast, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::MachineMemOperand::getFlags(), llvm::MachineFunction::getFunction(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getUNDEF(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::Function::hasFnAttribute(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE4A(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::X86Subtarget::is64Bit(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), isSimple(), llvm::MemSDNode::isSimple(), llvm::StoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MipsISD::Lo, llvm::SelectionDAG::makeEquivalentMemoryOrdering(), llvm::MinAlign(), N, llvm::SDNode::ops(), llvm::MVT::Other, llvm::ISD::SCALAR_TO_VECTOR, llvm::TargetLowering::scalarizeVectorStore(), splitVectorStore(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::X86Subtarget::useSoftFloat(), llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v1i1, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v64i1, llvm::MVT::v8i1, llvm::X86ISD::VTRUNCS, and llvm::X86ISD::VTRUNCUS.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSub()
static SDValue combineSub (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 45285 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, C, combineAddOrSubToADCOrSBB(), combineSubToSubus(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandAPInt(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasSSSE3(), llvm::X86ISD::HSUB, isHorizontalBinOp(), SplitOpsAndApply(), llvm::MVT::v16i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineSubToSubus()
static SDValue combineSubToSubus (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 45198 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::computeKnownBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::SelectionDAG::getConstant(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::MVT::i8, llvm::EVT::isVector(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::X86Subtarget::useBWIRegs(), llvm::ISD::USUBSAT, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by combineSub().
combineTargetShuffle()
static SDValue combineTargetShuffle (SDValue N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Try to combine x86 target specific shuffles.
Definition at line 34521 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::X86ISD::BLENDI, combineRedundantDWordShuffle(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), combineX86ShufflesRecursively(), D, extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, extractSubVector(), llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FMUL, llvm::ISD::FSUB, llvm::LoadSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPSHUFShuffleMask(), llvm::EVT::getScalarSizeInBits(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), getTargetShuffleAndZeroables(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::X86ISD::HADD, llvm::SDValue::hasOneUse(), llvm::MipsISD::Hi, llvm::X86ISD::HSUB, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::X86ISD::INSERTPS, llvm::MVT::isFloatingPoint(), isNoopShuffleMask(), llvm::ISD::isNormalLoad(), isTargetShuffle(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::MipsISD::Lo, llvm::SPII::Load, llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, N, llvm::MVT::Other, llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, llvm::peekThroughBitcasts(), llvm::peekThroughOneUseBitcasts(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::TargetLowering::DAGCombinerInfo::recursivelyDeleteUnusedNodes(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SCALAR_TO_VECTOR, scaleVectorShuffleBlendMask(), Size, llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, std::swap(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::SDNode::uses(), llvm::MVT::v4f32, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VBROADCAST_LOAD, and llvm::X86ISD::VPERMI.
Referenced by combineShuffle().
combineToConsecutiveLoads()
static SDValue combineToConsecutiveLoads (EVT VT, SDNode * N, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget, bool isAfterLegalize) static
Definition at line 8321 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, EltsFromConsecutiveLoads(), getShuffleScalarElt(), llvm::EVT::getVectorNumElements(), llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by combineShuffle().
combineToExtendBoolVectorInReg()
static SDValue combineToExtendBoolVectorInReg (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 43345 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::SmallVectorImpl< T >::append(), assert(), llvm::tgtok::Bit, llvm::ISD::BITCAST, llvm::tgtok::Bits, llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::APInt::getBitsSet(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::EVT::isScalarInteger(), llvm::EVT::isVector(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SETEQ, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRL, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSext(), and combineZext().
combineToExtendCMOV()
static SDValue combineToExtendCMOV (SDNode * Extend, SelectionDAG & DAG) static
Definition at line 43297 of file X86ISelLowering.cpp.
References llvm::X86ISD::CMOV, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, and llvm::ISD::SIGN_EXTEND.
Referenced by combineSext(), and combineZext().
combineToFPTruncExtElt()
static SDValue combineToFPTruncExtElt (SDNode * N, SelectionDAG & DAG) static
If we are converting a value to floating-point, try to replace scalar truncate of an extracted vector element with a bitcast.
This tries to keep the sequence on XMM registers rather than moving between vector and GPRs.
Definition at line 44206 of file X86ISelLowering.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorVT(), llvm::SDValue::hasOneUse(), llvm::isNullConstant(), and llvm::ISD::TRUNCATE.
Referenced by combineSIntToFP().
combineTruncate()
static SDValue combineTruncate (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 42374 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, combinePMULH(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorTruncation(), detectAVGPattern(), detectPMADDUBSW(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::X86ISD::MMX_MOVD2W, and llvm::MVT::x86mmx.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineTruncatedArithmetic()
static SDValue combineTruncatedArithmetic (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget, const SDLoc & DL) static
Attempt to pre-truncate inputs to arithmetic ops if it will simplify the codegen.
e.g. TRUNC(BINOP(X, Y)) –> BINOP(TRUNC(X), TRUNC(Y)) TODO: This overlaps with the generic combiner's visitTRUNCATE. Remove anything that is guaranteed to be transformed by DAGCombiner.
Definition at line 41956 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::MVT::i64, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::EVT::isVector(), LLVM_FALLTHROUGH, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SIGN_EXTEND, llvm::ISD::SUB, llvm::ISD::TRUNCATE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by combineTruncate().
combineTruncateWithSat()
static SDValue combineTruncateWithSat (SDValue In, EVT VT, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 41013 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, detectSSatPattern(), detectUSatPattern(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::EVT::is512BitVector(), llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, truncateVectorWithPACK(), llvm::X86Subtarget::useAVX512Regs(), llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::X86ISD::VTRUNCS, and llvm::X86ISD::VTRUNCUS.
Referenced by combineTruncate().
combineUIntToFP()
static SDValue combineUIntToFP (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 44238 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::SDNode::isStrictFPOpcode(), llvm::EVT::isVector(), llvm::MVT::Other, P, llvm::SelectionDAG::SignBitIsZero(), llvm::ISD::SINT_TO_FP, llvm::ISD::STRICT_SINT_TO_FP, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorCompare()
static SDValue combineVectorCompare (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 45330 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::X86ISD::PCMPEQ, and llvm::X86ISD::PCMPGT.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorCompareAndMaskUnaryOp()
static SDValue combineVectorCompareAndMaskUnaryOp (SDNode * N, SelectionDAG & DAG) static
Definition at line 44149 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::SDNode::isStrictFPOpcode(), llvm::EVT::isVector(), llvm::MVT::Other, and llvm::ISD::SETCC.
Referenced by combineSIntToFP().
combineVectorInsert()
static SDValue combineVectorInsert (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 39715 of file X86ISelLowering.cpp.
References assert(), combineX86ShufflesRecursively(), llvm::APInt::getAllOnesValue(), llvm::SDNode::getOpcode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::X86ISD::PINSRB, llvm::X86ISD::PINSRW, llvm::TargetLowering::SimplifyDemandedBits(), llvm::MVT::v16i8, and llvm::MVT::v8i16.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorPack()
static SDValue combineVectorPack (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 39504 of file X86ISelLowering.cpp.
References assert(), llvm::tgtok::Bits, combineX86ShufflesRecursively(), llvm::SelectionDAG::ComputeNumSignBits(), Concat, llvm::ISD::CONCAT_VECTORS, llvm::APInt::getAllOnesValue(), getConstVector(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), llvm::APInt::isIntN(), llvm::APInt::isNegative(), llvm::SDNode::isOnlyUserOf(), llvm::APInt::isSignedIntN(), llvm::SDValue::isUndef(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, llvm::APInt::setBit(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v8i32, and llvm::X86ISD::VTRUNC.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorShiftImm()
static SDValue combineVectorShiftImm (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 39637 of file X86ISelLowering.cpp.
References assert(), combineX86ShufflesRecursively(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), getConstVector(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetConstant(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i8, llvm::ISD::isBuildVectorAllZeros(), llvm::SDNode::isOnlyUserOf(), llvm::SmallVectorBase::size(), llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, and llvm::X86ISD::VSRLI.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorShiftVar()
static SDValue combineVectorShiftVar (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 39604 of file X86ISelLowering.cpp.
References assert(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetLoweringInfo(), getTargetVShiftByConstNode(), getTargetVShiftUniformOpcode(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86ISD::VSHL, llvm::X86ISD::VSRA, and llvm::X86ISD::VSRL.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineVectorSignBitsTruncation()
static SDValue combineVectorSignBitsTruncation (SDNode * N, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
This function transforms vector truncation of 'extended sign-bits' or 'extended zero-bits' values.
vXi16/vXi32/vXi64 to vXi8/vXi16/vXi32 into X86ISD::PACKSS/PACKUS operations.
Definition at line 42128 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::KnownBits::countMinLeadingZeros(), llvm::SDNode::getOperand(), llvm::MVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, truncateVectorWithPACK(), and llvm::X86Subtarget::useAVX512Regs().
Referenced by combineTruncate().
combineVectorSizedSetCCEquality()
static SDValue combineVectorSizedSetCCEquality (SDNode * SetCC, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Try to map a 128-bit or larger integer comparison to vector instructions before type legalization splits it up into chunks.
Definition at line 43711 of file X86ISelLowering.cpp.
References assert(), llvm::X86::COND_E, llvm::X86::COND_NE, emitOrXorXorTree(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSetCC(), getSETCC(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INSERT_SUBVECTOR, llvm::isNullConstant(), isOrXorXorTree(), llvm::EVT::isScalarInteger(), llvm::EVT::isVector(), llvm::ISD::LOAD, llvm::X86ISD::MOVMSK, llvm::peekThroughBitcasts(), llvm::X86Subtarget::preferMaskRegisters(), llvm::X86ISD::PTEST, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::TRUNCATE, llvm::X86Subtarget::useAVX512Regs(), llvm::MVT::v16i1, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8i32, X, llvm::ISD::XOR, Y, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSetCC().
combineVectorTruncation()
static SDValue combineVectorTruncation (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
This function transforms truncation from vXi32/vXi64 to vXi8/vXi16 into X86ISD::PACKUS/X86ISD::PACKSS operations.
We do it here because after type legalization the truncation will be translated into a BUILD_VECTOR with each element that is extracted from a vector and then truncated, and it is difficult to do this optimization based on them.
Definition at line 42081 of file X86ISelLowering.cpp.
References combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::isPowerOf2_32(), llvm::EVT::isSimple(), and llvm::EVT::isVector().
Referenced by combineTruncate().
combineVectorTruncationWithPACKSS()
static SDValue combineVectorTruncationWithPACKSS (SDNode * N, const SDLoc & DL, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Truncate a group of v4i32 into v8i16 using X86ISD::PACKSS.
Definition at line 42065 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::tgtok::In, llvm::X86ISD::PACKSS, llvm::ISD::SIGN_EXTEND_INREG, and truncateVectorWithPACK().
Referenced by combineVectorTruncation().
combineVectorTruncationWithPACKUS()
static SDValue combineVectorTruncationWithPACKUS (SDNode * N, const SDLoc & DL, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Truncate using ISD::AND mask and X86ISD::PACKUS.
e.g. trunc <8 x i32> X to <8 x i16> –> MaskX = X & 0xffff (clear high bits to prevent saturation) packus (extract_subv MaskX, 0), (extract_subv MaskX, 1)
Definition at line 42051 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getConstant(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::tgtok::In, llvm::X86ISD::PACKUS, and truncateVectorWithPACK().
Referenced by combineVectorTruncation().
combineVSelectToBLENDV()
static SDValue combineVSelectToBLENDV (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
If this is a dynamic select (non-constant condition) and we can match this node with one of the variable blend instructions, restructure the condition so that blends can use the high (sign) bit of each element.
This function will also call SimplifyDemandedBits on already created BLENDV to perform additional simplifications.
Definition at line 37726 of file X86ISelLowering.cpp.
combineVSelectWithAllOnesOrZeros()
static SDValue combineVSelectWithAllOnesOrZeros (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
If a vector select has an operand that is -1 or 0, try to simplify the select to a bitwise logic operation.
TODO: Move to DAGCombiner, possibly using TargetLowering::hasAndNot()?
Definition at line 37517 of file X86ISelLowering.cpp.
combineVTRUNC()
static SDValue combineVTRUNC (SDNode * N, SelectionDAG & DAG) static
Definition at line 42415 of file X86ISelLowering.cpp.
References detectSSatPattern(), detectUSatPattern(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::tgtok::In, llvm::X86ISD::VTRUNCS, and llvm::X86ISD::VTRUNCUS.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combinevXi1ConstantToInteger()
static SDValue combinevXi1ConstantToInteger (SDValue Op, SelectionDAG & DAG) static
Definition at line 36317 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i1, llvm::tgtok::In, llvm::ISD::isBuildVectorOfConstantSDNodes(), and llvm::SDValue::isUndef().
Referenced by combineBitcast(), combineCastedMaskArithmetic(), and combineStore().
combineX86AddSub()
static SDValue combineX86AddSub (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 44521 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, assert(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNodeIfExists(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::hasAnyUseOfValue(), llvm::MVT::i32, llvm::ISD::SUB, and llvm::X86ISD::SUB.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineX86GatherScatter()
static SDValue combineX86GatherScatter (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 43991 of file X86ISelLowering.cpp.
References llvm::SDValue::getScalarValueSizeInBits(), llvm::APInt::getSignMask(), llvm::SelectionDAG::getTargetLoweringInfo(), N, and llvm::TargetLowering::SimplifyDemandedBits().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineX86INT_TO_FP()
static SDValue combineX86INT_TO_FP (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 43000 of file X86ISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDValue::hasOneUse(), llvm::tgtok::In, llvm::MVT::is128BitVector(), llvm::ISD::isNormalLoad(), llvm::MVT::Other, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and llvm::X86ISD::VZEXT_LOAD.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineX86SetCC()
static SDValue combineX86SetCC (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 44117 of file X86ISelLowering.cpp.
References combineSetCCEFLAGS(), llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getOperand(), and getSETCC().
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineX86ShuffleChain()
static SDValue combineX86ShuffleChain (ArrayRef< SDValue > Inputs, SDValue Root, ArrayRef< int > BaseMask, int Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Combine an arbitrary chain of shuffles into a single instruction if possible.
This is the leaf of the recursive combine below. When we have found some chain of single-use x86 shuffle instructions and accumulated the combined shuffle mask represented by them, this will try to pattern match that mask into either a single instruction if there is a special purpose instruction for this operation, or into a PSHUFB instruction which is a fully general instruction but should only be used to replace chains over a certain depth.
Definition at line 33345 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::any_of(), assert(), llvm::ArrayRef< T >::begin(), combineX86ShuffleChainWithExtract(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::X86ISD::EXTRQI, llvm::X86ISD::FAND, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), getConstVector(), llvm::MVT::getFloatingPointVT(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasFastVariableShuffle(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE4A(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVBMI(), llvm::X86Subtarget::hasVLX(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::X86ISD::INSERTQI, is128BitLaneCrossingShuffleMask(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MVT::isFloatingPoint(), llvm::isNullConstant(), isSequentialOrUndefInRange(), isSequentialOrUndefOrZeroInRange(), isTargetShuffleEquivalent(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), isUndefOrZeroOrInRange(), llvm::BitmaskEnumDetail::Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsEXTRQ(), matchShuffleAsINSERTQ(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), MayFoldLoad(), llvm::peekThroughBitcasts(), llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), resolveZeroablesFromTargetShuffle(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::setBit(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::X86ISD::SUBV_BROADCAST, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VPERM2X128, llvm::X86ISD::VPERMIL2, llvm::X86ISD::VPERMILPV, llvm::X86ISD::VPERMV, llvm::X86ISD::VPERMV3, llvm::X86ISD::VPPERM, and llvm::X86ISD::VZEXT_LOAD.
Referenced by combineX86ShuffleChainWithExtract(), and combineX86ShufflesRecursively().
combineX86ShuffleChainWithExtract()
static SDValue combineX86ShuffleChainWithExtract (ArrayRef< SDValue > Inputs, SDValue Root, ArrayRef< int > BaseMask, int Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 33868 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::any_of(), llvm::SmallVectorImpl< T >::append(), assert(), llvm::ArrayRef< T >::begin(), combineX86ShuffleChain(), llvm::count_if(), llvm::ArrayRef< T >::end(), llvm::ISD::EXTRACT_SUBVECTOR, extractSubVector(), llvm::SelectionDAG::getBitcast(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::TargetLoweringBase::isTypeLegal(), llvm::max(), llvm::peekThroughBitcasts(), resolveTargetShuffleInputsAndMask(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and widenSubVector().
Referenced by combineX86ShuffleChain(), combineX86ShufflesRecursively(), and matchBinaryPermuteShuffle().
combineX86ShufflesConstants()
static SDValue combineX86ShufflesConstants (ArrayRef< SDValue > Ops, ArrayRef< int > Mask, SDValue Root, bool HasVariableMask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 33970 of file X86ISelLowering.cpp.
References assert(), llvm::tgtok::Bits, llvm::SelectionDAG::getBitcast(), getConstVector(), llvm::MVT::getFloatingPointVT(), llvm::MVT::getIntegerVT(), llvm::APInt::getNullValue(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetConstantBitsFromNode(), llvm::MVT::getVectorVT(), llvm::SDValue::hasOneUse(), llvm::MVT::isFloatingPoint(), llvm::APInt::setBit(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineX86ShufflesRecursively().
combineX86ShufflesRecursively() [1/2]
static SDValue combineX86ShufflesRecursively (ArrayRef< SDValue > SrcOps, int SrcOpIndex, SDValue Root, ArrayRef< int > RootMask, ArrayRef< const SDNode *> SrcNodes, unsigned Depth, bool HasVariableMask, bool AllowVariableMask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Fully generic combining of x86 shuffle instructions.
This should be the last combine run over the x86 shuffle instructions. Once they have been fully optimized, this will recursively consider all chains of single-use shuffle instructions, build a generic model of the cumulative shuffle operation, and check for simpler instructions which implement this operation. We use this primarily for two purposes:
1) Collapse generic shuffles to specialized single instructions when equivalent. In most cases, this is just an encoding size win, but sometimes we will collapse multiple generic shuffles into a single special-purpose shuffle. 2) Look for sequences of shuffle instructions with 3 or more total instructions, and replace them with the slightly more expensive SSSE3 PSHUFB instruction if available. We do this as the last combining step to ensure we avoid using PSHUFB if we can implement the shuffle with a suitable short sequence of other instructions. The PSHUFB will either use a register or have to read from memory and so is slightly (but only slightly) more expensive than the other shuffle instructions.
Because this is inherently a quadratic operation (for each shuffle in a chain, we recurse up the chain), the depth is limited to 8 instructions. This should never be an issue in practice as the shuffle lowering doesn't produce sequences of more than 8 instructions.
FIXME: We will currently miss some cases where the redundant shuffling would simplify under the threshold for PSHUFB formation because of combine-ordering. To fix this, we should do the redundant instruction combining in this recursive walk.
Definition at line 34081 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::SmallVectorImpl< T >::append(), llvm::SDNode::areOnlyUsersOf(), assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ArrayRef< T >::begin(), canonicalizeShuffleMaskWithCommute(), canWidenShuffleElements(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::countTrailingZeros(), llvm::Depth, llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ArrayRef< T >::end(), llvm::APInt::getAllOnesValue(), llvm::SDValue::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetShuffleInputs(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), getZeroVector(), hasOneUse(), llvm::APInt::isAllOnesValue(), llvm::APInt::isNullValue(), llvm::isPowerOf2_32(), isTargetShuffleVariableMask(), isUndefOrZero(), llvm::MVT::isVector(), llvm::BitmaskEnumDetail::Mask(), llvm::peekThroughBitcasts(), llvm::peekThroughOneUseBitcasts(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), resolveTargetShuffleFromZeroables(), resolveTargetShuffleInputsAndMask(), llvm::APInt::setBit(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and std::swap().
Referenced by combineAnd(), combineAndnp(), combineExtInVec(), combineOr(), combineShuffle(), combineTargetShuffle(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineX86ShufflesRecursively(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
combineX86ShufflesRecursively() [2/2]
static SDValue combineX86ShufflesRecursively (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Helper entry wrapper to combineX86ShufflesRecursively.
Definition at line 34337 of file X86ISelLowering.cpp.
References combineX86ShufflesRecursively().
combineXor()
static SDValue combineXor (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 42752 of file X86ISelLowering.cpp.
References combineFneg(), convertIntLogicToFPLogic(), foldVectorXorShiftIntoCmp(), foldXor1SetCC(), foldXorTruncShiftIntoCmp(), llvm::X86ISD::FXOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
combineZext()
static SDValue combineZext (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const X86Subtarget & Subtarget) static
Definition at line 43598 of file X86ISelLowering.cpp.
References llvm::ISD::AND, combineExtSetcc(), combineOrCmpEqZeroToCtlzSrl(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), concatSubVectors(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isOneConstant(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::X86ISD::PACKUS, promoteExtBeforeAdd(), PromoteMaskArithmetic(), llvm::X86ISD::SETCC_CARRY, and llvm::ISD::TRUNCATE.
Referenced by llvm::X86TargetLowering::PerformDAGCombine().
computeZeroableShuffleElements()
static void computeZeroableShuffleElements (ArrayRef< int > Mask, SDValue V1, SDValue V2, APInt & KnownUndef, APInt & KnownZero) static
Compute whether each element of a shuffle is zeroable.
A "zeroable" vector shuffle element is one which can be lowered to zero. Either it is an undef element in the shuffle mask, the element of the input referenced is undef, or the element of the input referenced is known to be zero. Many x86 shuffles can zero lanes cheaply and we often want to handle as many lanes with this technique as possible to simplify the remaining shuffle.
Definition at line 6909 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::APInt::extractBits(), llvm::SDValue::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), llvm::X86::isZeroNode(), llvm::peekThroughBitcasts(), llvm::APInt::setBit(), Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerVECTOR_SHUFFLE().
concatSubVectors()
static SDValue concatSubVectors (SDValue V1, SDValue V2, SelectionDAG & DAG, const SDLoc & dl) static
Definition at line 5976 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getContext(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), and insertSubVector().
Referenced by combineZext(), and LowerBUILD_VECTORAsVariablePermute().
ConvertI1VectorToInteger()
static SDValue ConvertI1VectorToInteger (SDValue Op, SelectionDAG & DAG) static
Definition at line 8749 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueSizeInBits(), llvm::tgtok::In, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SDValue::isUndef(), and llvm::max().
convertIntLogicToFPLogic()
static SDValue convertIntLogicToFPLogic (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
If both input operands of a logic op are being cast from floating point types, try to convert this into a floating point logic node to avoid unnecessary moves from SSE to integer registers.
Definition at line 39940 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FAND, llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm_unreachable, llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by combineAnd(), combineOr(), and combineXor().
convertShiftLeftToScale()
static SDValue convertShiftLeftToScale (SDValue Amt, const SDLoc & dl, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 26557 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, C, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), getUnpackl(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::ConstantSDNode::getZExtValue(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SDNode::isUndef(), llvm::MipsISD::Lo, llvm::X86ISD::PACKUS, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SHL, llvm::APInt::shl(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::Z.
Referenced by LowerRotate(), and LowerShift().
CreateCopyOfByValArgument()
static SDValue CreateCopyOfByValArgument (SDValue Src, SDValue Dst, SDValue Chain, ISD::ArgFlagsTy Flags, SelectionDAG & DAG, const SDLoc & dl) static
Make a copy of an aggregate at address specified by "Src" to address "Dst" with size and alignment information specified by the specific parameter attribute.
The copy will be passed as a byval function parameter.
Definition at line 3131 of file X86ISelLowering.cpp.
References llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMemcpy(), and llvm::MVT::i32.
Referenced by getMOVL(), and isSortedByValueNo().
createMMXBuildVector()
static SDValue createMMXBuildVector (BuildVectorSDNode * BV, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 36390 of file X86ISelLowering.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::BuildVectorSDNode::getSplatValue(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasSSE1(), llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SDValue::isUndef(), llvm::X86ISD::MMX_MOVW2D, llvm::X86ISD::MOVDQ2Q, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::ISD::SCALAR_TO_VECTOR, llvm::SmallVectorBase::size(), llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::x86mmx.
Referenced by combineBitcast().
createPackShuffleMask()
static void createPackShuffleMask (MVT VT, SmallVectorImpl< int > & Mask, bool Unary) static
Create a shuffle mask that matches the PACKSS/PACKUS truncation.
Note: This ignores saturation, so inputs must be checked first.
Definition at line 6517 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorBase::empty(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getFauxShuffleMask(), and matchShuffleWithPACK().
createPHIsForCMOVsInSinkBB()
static MachineInstrBuilder createPHIsForCMOVsInSinkBB (MachineBasicBlock::iterator MIItBegin, MachineBasicBlock::iterator MIItEnd, MachineBasicBlock * TrueMBB, MachineBasicBlock * FalseMBB, MachineBasicBlock * SinkMBB) static
Definition at line 30720 of file X86ISelLowering.cpp.
References llvm::addDirectMem(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::CallingConv::C, checkAndUpdateEFLAGSKill(), llvm::classifyEHPersonality(), llvm::X86::COND_G, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::N86::EAX, llvm::N86::EDI, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::N86::ESP, F(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), first, llvm::X86AS::FS, llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetInstrInfo::getCallFrameSetupOpcode(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86RegisterInfo::getDarwinTLSCallPreservedMask(), llvm::MachineFunction::getDataLayout(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::MachineOperand::getImm(), llvm::MachineInstrBuilder::getInstr(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::X86Subtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::X86::GetOppositeBranchCondition(), llvm::MachineBasicBlock::getParent(), llvm::Function::getPersonalityFn(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::X86Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getTargetFlags(), llvm::X86AS::GS, llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::MachineBasicBlock::insert(), llvm::MachineFunction::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::X86Subtarget::is32Bit(), llvm::X86Subtarget::is64Bit(), llvm::isAsynchronousEHPersonality(), isCMOVPseudo(), llvm::MachineOperand::isGlobal(), llvm::TargetLowering::isPositionIndependent(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetDarwin(), llvm::X86Subtarget::isTargetNaCl64(), llvm::MachineInstr::killsRegister(), MI, MRI, llvm::MachineBasicBlock::push_back(), second, llvm::MachineOperand::setMBB(), llvm::MachineFunction::shouldSplitStack(), llvm::skipDebugInstructionsForward(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_size(), std::swap(), TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and TRI.
createPSADBW()
static SDValue createPSADBW (SelectionDAG & DAG, const SDValue & Zext0, const SDValue & Zext1, const SDLoc & DL, const X86Subtarget & Subtarget) static
Definition at line 36718 of file X86ISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::MVT::getVectorVT(), llvm::MVT::i64, llvm::MVT::i8, llvm::max(), llvm::X86ISD::PSADBW, and SplitOpsAndApply().
Referenced by combineBasicSADPattern(), and combineLoopSADPattern().
createShuffleMaskFromVSELECT()
static bool createShuffleMaskFromVSELECT (SmallVectorImpl< int > & Mask, SDValue Cond) static
Definition at line 10606 of file X86ISelLowering.cpp.
createVariablePermute()
static SDValue createVariablePermute (MVT VT, SDValue SrcVec, SDValue IndicesVec, SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Look for opportunities to create a VPERMV/VPERMILPV/PSHUFB variable permute from a vector of source values and a vector of extraction indices.
The vectors might be manipulated to match the type of the permute op.
Definition at line 9549 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::EVT::changeVectorElementTypeToInteger(), llvm::ISD::CONCAT_VECTORS, extract128BitVector(), extract256BitVector(), extractSubVector(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::SelectionDAG::getSelectCC(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVBMI(), llvm::X86Subtarget::hasVLX(), llvm::X86Subtarget::hasXOP(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::isPowerOf2_64(), llvm::MipsISD::Lo, llvm::ISD::MUL, llvm::X86ISD::PSHUFB, llvm::ISD::SETEQ, llvm::ISD::SETGT, llvm::MVT::SimpleTy, SplitOpsAndApply(), llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VPERMIL2, llvm::X86ISD::VPERMILPV, llvm::X86ISD::VPERMV, llvm::X86ISD::VPPERM, and widenSubVector().
Referenced by LowerBUILD_VECTORAsVariablePermute().
detectAVGPattern()
static SDValue detectAVGPattern (SDValue In, EVT VT, SelectionDAG & DAG, const X86Subtarget & Subtarget, const SDLoc & DL) static
This function detects the AVG pattern between vectors of unsigned i8/i16, which is c = (a + b + 1) / 2, and replace this operation with the efficient X86ISD::AVG instruction.
Definition at line 41118 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::AVG, C, llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE2(), llvm::SelectionDAG::haveNoCommonBitsSet(), llvm::MVT::i16, llvm::MVT::i8, llvm::BuildVectorSDNode::isConstant(), llvm::isPowerOf2_32(), llvm::EVT::isVector(), Operands, llvm::SDNode::ops(), llvm::ISD::OR, SplitOpsAndApply(), llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::ISD::TRUNCATE, llvm::APInt::ugt(), llvm::APInt::ult(), and llvm::ISD::ZERO_EXTEND.
Referenced by combineStore(), and combineTruncate().
detectPMADDUBSW()
static SDValue detectPMADDUBSW (SDValue In, EVT VT, SelectionDAG & DAG, const X86Subtarget & Subtarget, const SDLoc & DL) static
Definition at line 42243 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::ISD::BUILD_VECTOR, detectSSatPattern(), llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::MVT::i8, llvm::isPowerOf2_32(), llvm::EVT::isVector(), llvm::ISD::MUL, llvm::ISD::SIGN_EXTEND, SplitOpsAndApply(), std::swap(), llvm::X86ISD::VPMADDUBSW, and llvm::ISD::ZERO_EXTEND.
Referenced by combineTruncate().
detectSSatPattern()
static SDValue detectSSatPattern (SDValue In, EVT VT, bool MatchPackUS = false) static
Detect patterns of truncation with signed saturation: (truncate (smin ((smax (x, signed_min_of_dest_type)), signed_max_of_dest_type)) to dest_type) or: (truncate (smax ((smin (x, signed_max_of_dest_type)), signed_min_of_dest_type)) to dest_type).
With MatchPackUS, the smax/smin range is [0, unsigned_max_of_dest_type]. Return the source value to be truncated or SDValue() if the pattern was not matched.
Definition at line 40979 of file X86ISelLowering.cpp.
References assert(), C, llvm::APInt::getAllOnesValue(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ISD::isConstantSplatVector(), llvm::APInt::sext(), llvm::ISD::SMAX, llvm::ISD::SMIN, and llvm::APInt::zext().
Referenced by combineStore(), combineTruncateWithSat(), combineVTRUNC(), and detectPMADDUBSW().
detectUSatPattern()
static SDValue detectUSatPattern (SDValue In, EVT VT, SelectionDAG & DAG, const SDLoc & DL) static
Detect patterns of truncation with unsigned saturation:
(truncate (umin (x, unsigned_max_of_dest_type)) to dest_type). Return the source value x to be truncated or SDValue() if the pattern was not matched.
(truncate (smin (smax (x, C1), C2)) to dest_type), where C1 >= 0 and C2 is unsigned max of destination type.
(truncate (smax (smin (x, C2), C1)) to dest_type) where C1 >= 0, C2 is unsigned max of destination type and C1 <= C2.
These two patterns are equivalent to: (truncate (umin (smax(x, C1), unsigned_max_of_dest_type)) to dest_type) So return the smax(x, C1) value to be truncated or SDValue() if the pattern was not matched.
Definition at line 40932 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getValueType(), llvm::ISD::isConstantSplatVector(), llvm::APInt::isMask(), llvm::APInt::isNonNegative(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::APInt::uge(), and llvm::ISD::UMIN.
Referenced by combineStore(), combineTruncateWithSat(), and combineVTRUNC().
detectZextAbsDiff()
static bool detectZextAbsDiff (const SDValue & Abs, SDValue & Op0, SDValue & Op1) static
Definition at line 36698 of file X86ISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::i8, llvm::ISD::SUB, and llvm::ISD::ZERO_EXTEND.
Referenced by combineBasicSADPattern(), and combineLoopSADPattern().
EltsFromConsecutiveLoads()
static SDValue EltsFromConsecutiveLoads (EVT VT, ArrayRef< SDValue > Elts, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget, bool isAfterLegalize) static
Given the initializing elements 'Elts' of a vector of type 'VT', see if the elements can be replaced by a single large load which has the same value as a build_vector or insert_subvector whose loaded operands are 'Elts'.
Example: <load i32 *a, load i32 *a+4, zero, undef> -> zextload a
Definition at line 8058 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::areNonVolatileConsecutiveLoads(), assert(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::ArrayRef< T >::drop_back(), llvm::APInt::extractBits(), findEltLoadSrc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::EVT::getFloatingPointVT(), llvm::MVT::getFloatingPointVT(), llvm::EVT::getIntegerVT(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::EVT::getStoreSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i64, llvm::ISD::INSERT_SUBVECTOR, llvm::APInt::isAllOnesValue(), llvm::ISD::isBuildVectorAllZeros(), llvm::MVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::APInt::isNullValue(), llvm::TargetLoweringBase::isOperationLegal(), llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), isUndef(), llvm::X86::isZeroNode(), llvm::ARM_MB::LD, llvm::ISD::LOAD, llvm::SelectionDAG::makeEquivalentMemoryOrdering(), llvm::Match, llvm::MachineMemOperand::MOLoad, llvm::MVT::Other, llvm::peekThroughBitcasts(), llvm::APInt::setBit(), llvm::ArrayRef< T >::size(), llvm::X86ISD::SUBV_BROADCAST, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VZEXT_LOAD, and llvm::Z.
Referenced by combineConcatVectorOps(), combineToConsecutiveLoads(), and LowerBUILD_VECTORAsVariablePermute().
EmitAVX512Test()
static SDValue EmitAVX512Test (SDValue Op0, SDValue Op1, ISD::CondCode CC, const SDLoc & dl, SelectionDAG & DAG, const X86Subtarget & Subtarget, SDValue & X86CC) static
Definition at line 21756 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_INVALID, llvm::X86::COND_NE, EmitCmp(), llvm::MVT::f128, llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::X86::GetOppositeBranchCondition(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::MVT::i8, llvm::isAllOnesConstant(), llvm::MVT::isFloatingPoint(), llvm::isNullConstant(), llvm::isOneConstant(), isProfitableToUseFlagOp(), llvm::MVT::isVector(), llvm::X86ISD::KORTEST, llvm::X86ISD::KTEST, LowerAndToBT(), LowerVectorAllZeroTest(), LowerVSETCC(), llvm::ISD::OR, llvm::AArch64ISD::PTEST, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::X86ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::TargetLowering::softenSetCCOperands(), llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::Test, TranslateX86CC(), llvm::MVT::v16i1, llvm::MVT::v32i1, llvm::MVT::v64i1, and llvm::MVT::v8i1.
EmitCmp()
static std::pair<SDValue, SDValue> EmitCmp (SDValue Op0, SDValue Op1, unsigned X86CC, const SDLoc & dl, SelectionDAG & DAG, const X86Subtarget & Subtarget, SDValue Chain, bool IsSignaling) static
Emit nodes that will be selected as "cmp Op0,Op1", or something equivalent.
Definition at line 20817 of file X86ISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, assert(), llvm::X86ISD::CMP, llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86::COND_E, llvm::X86::COND_NE, llvm::APInt::countTrailingZeros(), llvm::dyn_cast(), EmitTest(), llvm::TargetLoweringBase::Enabled, llvm::MVT::f32, llvm::X86ISD::FNSTSW16r, llvm::X86ISD::FRCP, llvm::X86ISD::FRSQRT, llvm::ConstantSDNode::getAPIntValue(), llvm::Function::getAttributes(), llvm::SelectionDAG::getConstant(), llvm::MachineFunction::getFunction(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNodeIfExists(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasCMov(), llvm::X86Subtarget::hasFastScalarFSQRT(), llvm::X86Subtarget::hasFastVectorFSQRT(), llvm::X86Subtarget::hasLAHFSAHF(), llvm::Function::hasMinSize(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isAtom(), llvm::EVT::isFloatingPoint(), llvm::X86TargetLowering::isIntDivCheap(), llvm::APInt::isNonNegative(), llvm::isNullConstant(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignedIntN(), llvm::EVT::isVector(), isX86CCSigned(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::X86ISD::RCP14, llvm::X86ISD::RSQRT14, llvm::X86ISD::SAHF, llvm::ISD::SELECT, llvm::ISD::SETLT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::SRL, llvm::X86ISD::STRICT_FCMP, llvm::X86ISD::STRICT_FCMPS, llvm::ISD::SUB, llvm::X86ISD::SUB, llvm::ISD::TRUNCATE, llvm::X86Subtarget::useAVX512Regs(), llvm::MVT::v16f32, llvm::MVT::v4f32, llvm::MVT::v8f32, and llvm::ISD::ZERO_EXTEND.
Referenced by EmitAVX512Test().
emitLockedStackOp()
static SDValue emitLockedStackOp (SelectionDAG & DAG, const X86Subtarget & Subtarget, SDValue Chain, SDLoc DL) static
Emit a locked operation on a stack location which does not change any memory location, but does involve a lock prefix.
Location is chosen to be a) very likely accessed only by a single thread to minimize cache traffic, and b) definitely dereferenceable. Returns the new Chain result.
Definition at line 27464 of file X86ISelLowering.cpp.
References llvm::N86::ESP, llvm::X86Subtarget::getFrameLowering(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), and llvm::MVT::Other.
Referenced by LowerATOMIC_FENCE(), and lowerAtomicArith().
EmitMaskedTruncSStore()
static SDValue EmitMaskedTruncSStore (bool SignedSat, SDValue Chain, const SDLoc & Dl, SDValue Val, SDValue Ptr, SDValue Mask, EVT MemVT, MachineMemOperand * MMO, SelectionDAG & DAG) static
Emit Masked Truncating Store with signed or unsigned saturation.
Definition at line 24789 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getTargetMemSDNode(), llvm::SelectionDAG::getVTList(), and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
emitOrXorXorTree()
template<typename F > static SDValue emitOrXorXorTree (SDValue X, SDLoc & DL, SelectionDAG & DAG, EVT VecVT, EVT CmpVT, bool HasPT, F SToV) static
Recursive helper for combineVectorSizedSetCCEquality() to emit the memcmp expansion.
Definition at line 43685 of file X86ISelLowering.cpp.
References llvm::ISD::AND, B, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm_unreachable, llvm::ISD::OR, llvm::ISD::SETEQ, llvm::ISD::SETNE, and llvm::ISD::XOR.
Referenced by combineVectorSizedSetCCEquality().
EmitTailCallStoreRetAddr()
static SDValue EmitTailCallStoreRetAddr (SelectionDAG & DAG, MachineFunction & MF, SDValue Chain, SDValue RetAddrFrIdx, EVT PtrVT, unsigned SlotSize, int FPDiff, const SDLoc & dl) static
Emit a store of the return address if tail call optimization is performed and it is required (FPDiff!=0).
Definition at line 3748 of file X86ISelLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), and llvm::SelectionDAG::getStore().
Referenced by getMOVL().
EmitTest()
static SDValue EmitTest (SDValue Op, unsigned X86CC, const SDLoc & dl, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Emit nodes that will be selected as "test Op0,Op0", or something equivalent.
Definition at line 20709 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::X86ISD::AND, llvm::ISD::AND, llvm::X86ISD::CMP, llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NO, llvm::X86::COND_O, llvm::SelectionDAG::getConstant(), llvm::SDNode::getFlags(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), hasNonFlagsUse(), llvm::SDNodeFlags::hasNoSignedWrap(), llvm::MVT::i32, isProfitableToUseFlagOp(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::MUL, llvm::SDNode::op_begin(), llvm::X86ISD::OR, llvm::ISD::OR, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SHL, llvm::ISD::SSUBO, llvm::ISD::SUB, llvm::X86ISD::SUB, llvm::ISD::USUBO, llvm::X86ISD::XOR, and llvm::ISD::XOR.
Referenced by EmitCmp().
EmitTruncSStore()
static SDValue EmitTruncSStore (bool SignedSat, SDValue Chain, const SDLoc & Dl, SDValue Val, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO, SelectionDAG & DAG) static
Emit Truncating Store with signed or unsigned saturation.
Definition at line 24775 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getTargetMemSDNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Other, and llvm::RegState::Undef.
Referenced by combineStore(), and LowerINTRINSIC_W_CHAIN().
emitXBegin()
static MachineBasicBlock* emitXBegin (MachineInstr & MI, MachineBasicBlock * MBB, const TargetInstrInfo * TII) static
Utility function to emit xbegin specifying the start of an RTM region.
Definition at line 30234 of file X86ISelLowering.cpp.
References add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::X86::AddrNumOperands, llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::X86::COND_AE, llvm::X86::COND_E, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::numbers::e, llvm::N86::EAX, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), F(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::Function::getCallingConv(), llvm::MachineInstr::getDebugLoc(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::X86Subtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::X86Subtarget::hasAVX(), llvm::MachineInstr::hasOneMemOperand(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::MachineFunction::insert(), llvm::X86Subtarget::isCallingConvWin64(), llvm::isPowerOf2_32(), isReg(), llvm::MachineInstr::memoperands(), MI, llvm::MachineMemOperand::MOStore, MRI, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter().
errorUnsupported()
static void errorUnsupported (SelectionDAG & DAG, const SDLoc & dl, const char * Msg) static
Call this when the user attempts to do something unsupported, like returning a double without SSE2 enabled on x86_64.
This is not fatal, unlike report_fatal_error, so calling code should attempt to recover without crashing.
Definition at line 102 of file X86ISelLowering.cpp.
References llvm::LLVMContext::diagnose(), llvm::SelectionDAG::getContext(), llvm::SDLoc::getDebugLoc(), llvm::MachineFunction::getFunction(), and llvm::SelectionDAG::getMachineFunction().
Referenced by lowerRegToMasks(), and Passv64i1ArgInRegs().
ExpandHorizontalBinOp()
static SDValue ExpandHorizontalBinOp (const SDValue & V0, const SDValue & V1, const SDLoc & DL, SelectionDAG & DAG, unsigned X86Opcode, bool Mode, bool isUndefLO, bool isUndefHI) static
Emit a sequence of two 128-bit horizontal add/sub followed by a concat_vector.
This is a helper function of LowerToHorizontalOp(). This function expects two 256-bit vectors called V0 and V1. At first, each vector is split into two separate 128-bit vectors. Then, the resulting 128-bit vectors are used to implement two horizontal binary operations.
The kind of horizontal binary operation is defined by X86Opcode.
Mode specifies how the 128-bit parts of V0 and V1 are passed in input to the two new horizontal binop. When Mode is set, the first horizontal binop dag node would take as input the lower 128-bit of V0 and the upper 128-bit of V0. The second horizontal binop dag node would take as input the lower 128-bit of V1 and the upper 128-bit of V1. Example: HADD V0_LO, V0_HI HADD V1_LO, V1_HI
Otherwise, the first horizontal binop dag node takes as input the lower 128-bit of V0 and the lower 128-bit of V1, and the second horizontal binop dag node takes the upper 128-bit of V0 and the upper 128-bit of V1. Example: HADD V0_LO, V1_LO HADD V0_HI, V1_HI
If isUndefLO is set, then the algorithm propagates UNDEF to the lower 128-bits of the result. If isUndefHI is set, then UNDEF is propagated to the upper 128-bits of the result.
Definition at line 8976 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::AArch64CC::HI, llvm::MVT::is256BitVector(), llvm::SDNode::isUndef(), and llvm::AArch64CC::LO.
Referenced by LowerToHorizontalOp().
expandIntrinsicWChainHelper()
static SDValue expandIntrinsicWChainHelper (SDNode * N, const SDLoc & DL, SelectionDAG & DAG, unsigned TargetOpcode, unsigned SrcReg, const X86Subtarget & Subtarget, SmallVectorImpl< SDValue > & Results) static
Handles the lowering of builtin intrinsics with chain that return their value into registers EDX:EAX.
If operand ScrReg is a valid register identifier, then operand 2 of N is copied to SrcReg. The assumption is that SrcReg is an implicit input to TargetOpcode. Returns a Glue value which can be used to add extra copy-from-reg if the expanded intrinsics implicitly defines extra registers (i.e. not just EDX:EAX).
Definition at line 24652 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_PAIR, llvm::N86::EAX, llvm::N86::EDX, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::AArch64CC::HI, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::AArch64CC::LO, llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::SHL.
Referenced by getReadTimeStampCounter(), LowerINTRINSIC_W_CHAIN(), and llvm::X86TargetLowering::ReplaceNodeResults().
ExtendToType()
static SDValue ExtendToType (SDValue InOp, MVT NVT, SelectionDAG & DAG, bool FillWithZeroes = false) static
Widen a vector input to a vector of NVT.
The input vector must have the same element type as NVT.
Definition at line 28194 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::isBuildVectorAllZeros(), llvm::ISD::isBuildVectorOfConstantFPSDNodes(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SDValue::isUndef(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), and LowerMSTORE().
extract128BitVector()
static SDValue extract128BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & dl) static
Generate a DAG to grab 128-bits from a vector > 128 bits.
This sets things up to match to an AVX VEXTRACTF128 / VEXTRACTI128 or AVX-512 VEXTRACTF32x4 / VEXTRACTI32x4 instructions or a simple subregister reference. Idx is an index in the 128 bits we want. It need not be aligned to a 128-bit boundary. That makes lowering EXTRACT_VECTOR_ELT operations easier.
Definition at line 5650 of file X86ISelLowering.cpp.
References assert(), extractSubVector(), llvm::SDValue::getValueType(), llvm::EVT::is256BitVector(), and llvm::EVT::is512BitVector().
Referenced by combineExtractWithShuffle(), combineReductionToHorizontal(), combineTargetShuffle(), createVariablePermute(), ExpandHorizontalBinOp(), ExtractBitFromMaskVector(), InsertBitToMaskVector(), isHorizontalBinOp(), Lower256IntVSETCC(), lowerAddSubToHorizontalOp(), LowerMULH(), lowerShuffleAsBroadcast(), LowerTruncateVecI1(), narrowExtractedVectorSelect(), split256IntArith(), and vectorizeExtractedCast().
extract256BitVector()
static SDValue extract256BitVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & dl) static
Generate a DAG to grab 256-bits from a 512-bit vector.
Definition at line 5658 of file X86ISelLowering.cpp.
References assert(), extractSubVector(), llvm::SDValue::getValueType(), and llvm::EVT::is512BitVector().
Referenced by createVariablePermute(), and split512IntArith().
ExtractBitFromMaskVector()
static SDValue ExtractBitFromMaskVector (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Extract one bit from mask vector, like v16i1 or v8i1.
AVX-512 feature.
Definition at line 17577 of file X86ISelLowering.cpp.
References assert(), llvm::MipsISD::Ext, extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::SDNode::isOnlyUserOf(), llvm::isPowerOf2_32(), llvm::X86ISD::KSHIFTR, LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::BitmaskEnumDetail::Mask(), MayFoldIntoStore(), MayFoldIntoZeroExtend(), llvm::X86ISD::PEXTRW, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::MVT::v16i1, llvm::MVT::v4i32, llvm::MVT::v8i1, and llvm::MVT::v8i16.
extractSubVector()
static SDValue extractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & dl, unsigned vectorWidth) static
Definition at line 5619 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::isPowerOf2_32(), and llvm::SDNode::ops().
Referenced by combineExtractSubvector(), combineHorizontalMinMaxResult(), combineReductionToHorizontal(), combineTargetShuffle(), combineX86ShuffleChainWithExtract(), createVariablePermute(), extract128BitVector(), extract256BitVector(), getExtendInVec(), getHopForBuildVector(), LowerEXTEND_VECTOR_INREG(), LowerVectorIntUnary(), matchUnaryShuffle(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), SplitOpsAndApply(), splitVectorStore(), and truncateVectorWithPACK().
findEltLoadSrc()
static bool findEltLoadSrc (SDValue Elt, LoadSDNode *& Ld, int64_t & ByteOffset) static
Definition at line 8011 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::ISD::isNON_EXTLoad(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
Referenced by EltsFromConsecutiveLoads().
foldShuffleOfHorizOp()
static SDValue foldShuffleOfHorizOp (SDNode * N, SelectionDAG & DAG) static
Eliminate a redundant shuffle of a horizontal math op.
Definition at line 35111 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::X86ISD::HADD, HOp, llvm::X86ISD::HSUB, llvm::isNullConstant(), isTargetShuffleEquivalent(), llvm::SDValue::isUndef(), llvm::X86ISD::MOVDDUP, N, llvm::MVT::v2f64, llvm::MVT::v4f64, llvm::X86ISD::VBROADCAST, llvm::ISD::VECTOR_SHUFFLE, and X.
Referenced by combineShuffle().
foldVectorXorShiftIntoCmp()
static SDValue foldVectorXorShiftIntoCmp (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Turn vector tests of the signbit in the form of: xor (sra X, elt_size(X)-1), -1 into: pcmpgt X, -1.
This should be called before type legalization because the pattern may not persist after that.
Definition at line 40878 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSimpleVT(), llvm::SDNode::getValueType(), llvm::X86Subtarget::hasAVX2(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::isBuildVectorAllOnes(), llvm::isConstOrConstSplat(), llvm::EVT::isSimple(), llvm::ISD::SETGT, llvm::MVT::SimpleTy, llvm::ISD::SRA, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by combineXor().
foldXor1SetCC()
static SDValue foldXor1SetCC (SDNode * N, SelectionDAG & DAG) static
Fold a xor(setcc cond, val), 1 –> setcc (inverted(cond), val)
Definition at line 42738 of file X86ISelLowering.cpp.
References llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::X86::GetOppositeBranchCondition(), getSETCC(), llvm::isOneConstant(), llvm::X86ISD::SETCC, and llvm::ISD::XOR.
Referenced by combineXor().
foldXorTruncShiftIntoCmp()
static SDValue foldXorTruncShiftIntoCmp (SDNode * N, SelectionDAG & DAG) static
Try to turn tests against the signbit in the form of: XOR(TRUNCATE(SRL(X, size(X)-1)), 1) into: SETGT(X, -1)
Definition at line 40823 of file X86ISelLowering.cpp.
References llvm::SDValue::getConstantOperandAPInt(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::isOneConstant(), llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
Referenced by combineXor().
get64BitArgumentGPRs()
static ArrayRef<MCPhysReg> get64BitArgumentGPRs (CallingConv::ID CallConv, const X86Subtarget & Subtarget) static
Definition at line 3295 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::sys::path::end(), llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isCallingConvWin64(), and llvm::makeArrayRef().
Referenced by isSortedByValueNo().
get64BitArgumentXMMs()
static ArrayRef<MCPhysReg> get64BitArgumentXMMs (MachineFunction & MF, CallingConv::ID CallConv, const X86Subtarget & Subtarget) static
Definition at line 3313 of file X86ISelLowering.cpp.
References assert(), llvm::sys::path::begin(), llvm::sys::path::end(), F(), llvm::MachineFunction::getFunction(), llvm::Function::hasFnAttribute(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isCallingConvWin64(), llvm::makeArrayRef(), llvm::None, and llvm::X86Subtarget::useSoftFloat().
Referenced by isSortedByValueNo().
getAVX2GatherNode()
static SDValue getAVX2GatherNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget & Subtarget) static
Definition at line 24527 of file X86ISelLowering.cpp.
References C, llvm::EVT::changeVectorElementTypeToInteger(), llvm::dyn_cast(), llvm::SelectionDAG::getDataLayout(), llvm::SDValue::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::ISD::isBuildVectorAllOnes(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
getConstantVector()
static Constant* getConstantVector (MVT VT, const APInt & SplatValue, unsigned SplatBitSize, LLVMContext & C) static
Definition at line 8338 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, assert(), llvm::APInt::extractBits(), llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::Constant::getIntegerValue(), llvm::Type::getIntNTy(), llvm::MVT::getScalarSizeInBits(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::MVT::isFloatingPoint(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by lowerBuildVectorAsBroadcast().
getConstVector() [1/2]
static SDValue getConstVector (ArrayRef< int > Values, MVT VT, SelectionDAG & DAG, const SDLoc & dl, bool IsMask = false) static
Definition at line 5522 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::isTypeLegal(), and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by combineVectorPack(), combineVectorShiftImm(), combineX86ShuffleChain(), combineX86ShufflesConstants(), lowerShuffleWithPERMV(), lowerV16F32Shuffle(), lowerV8F32Shuffle(), and lowerV8I32Shuffle().
getConstVector() [2/2]
static SDValue getConstVector (ArrayRef< APInt > Bits, APInt & Undefs, MVT VT, SelectionDAG & DAG, const SDLoc & dl) static
Definition at line 5552 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getBitcast(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::TargetLoweringBase::isTypeLegal(), llvm::APInt::lshr(), llvm::ArrayRef< T >::size(), and llvm::APInt::trunc().
getExtendInVec()
static SDValue getExtendInVec (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue In, SelectionDAG & DAG) static
Definition at line 6017 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), extractSubVector(), llvm::SelectionDAG::getNode(), getOpcode_EXTEND_VECTOR_INREG(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isVector(), llvm::max(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerShuffleAsSpecificZeroOrAnyExtend(), and llvm::X86TargetLowering::ReplaceNodeResults().
getFauxShuffleMask()
static bool getFauxShuffleMask (SDValue N, const APInt & DemandedElts, SmallVectorImpl< int > & Mask, SmallVectorImpl< SDValue > & Ops, SelectionDAG & DAG, unsigned Depth, bool ResolveKnownElts) static
Definition at line 7120 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ArrayRef< T >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), createPackShuffleMask(), llvm::DecodeZeroExtendMask(), llvm::numbers::e, llvm::SmallVectorTemplateCommon< T >::end(), llvm::ArrayRef< T >::end(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::APInt::getBitWidth(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getPackDemandedElts(), llvm::EVT::getScalarSizeInBits(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), getTargetConstantBitsFromNode(), getTargetShuffleInputs(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::ISD::INSERT_SUBVECTOR, llvm::APInt::isNullValue(), llvm::SDNode::isOnlyUserOf(), llvm::EVT::isSimple(), llvm::SDValue::isUndef(), isUndefOrInRange(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::X86::isZeroNode(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::max(), N, llvm::KnownBits::One, llvm::ISD::OR, llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, llvm::peekThroughOneUseBitcasts(), llvm::X86ISD::PEXTRB, llvm::X86ISD::PEXTRW, llvm::X86ISD::PINSRB, llvm::X86ISD::PINSRW, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::setBit(), llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::MVT::v16i8, llvm::MVT::v8i16, llvm::X86ISD::VBROADCAST, llvm::ISD::VECTOR_SHUFFLE, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRLI, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by getTargetShuffleInputs().
getGatherNode()
static SDValue getGatherNode (SDValue Op, SelectionDAG & DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget & Subtarget) static
Definition at line 24555 of file X86ISelLowering.cpp.
References C, llvm::dyn_cast(), llvm::SelectionDAG::getDataLayout(), getMaskNode(), llvm::SDValue::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::MVT::i1, llvm::ISD::isBuildVectorAllOnes(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
getHalfShuffleMask()
static bool getHalfShuffleMask (ArrayRef< int > Mask, MutableArrayRef< int > HalfMask, int & HalfIdx1, int & HalfIdx2) static
If the input shuffle mask results in a vector that is undefined in all upper or lower half elements and that mask accesses only 2 halves of the shuffle's operands, return true.
A mask of half the width with mask indexes adjusted to access the extracted halves of the original shuffle operands is returned in HalfMask. HalfIdx1 and HalfIdx2 return whether the upper or lower half of each input operand is accessed.
Definition at line 15326 of file X86ISelLowering.cpp.
References assert(), isUndefLowerHalf(), isUndefUpperHalf(), and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleWithUndefHalf(), and narrowShuffle().
getHopForBuildVector()
static SDValue getHopForBuildVector (const BuildVectorSDNode * BV, SelectionDAG & DAG, unsigned HOpcode, SDValue V0, SDValue V1) static
Definition at line 9295 of file X86ISelLowering.cpp.
References llvm::APInt::clearBit(), extractSubVector(), llvm::APInt::getAllOnesValue(), llvm::MVT::getHalfNumVectorElementsVT(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::getVectorNumElements(), insertSubVector(), llvm::MVT::is256BitVector(), llvm::SDValue::isUndef(), and llvm::APInt::lshr().
Referenced by LowerToHorizontalOp().
getHorizDemandedElts()
static void getHorizDemandedElts (EVT VT, const APInt & DemandedElts, APInt & DemandedLHS, APInt & DemandedRHS) static
Definition at line 6559 of file X86ISelLowering.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getNullValue(), llvm::EVT::getSizeInBits(), and llvm::APInt::setBit().
Referenced by llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
getIndexFromUnindexedLoad()
static SDValue getIndexFromUnindexedLoad (LoadSDNode * Ld) static
Definition at line 40011 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::LoadSDNode::getBasePtr(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::LSBaseSDNode::isIndexed(), and llvm::ISD::SHL.
getMaskNode()
static SDValue getMaskNode (SDValue Mask, MVT MaskVT, const X86Subtarget & Subtarget, SelectionDAG & DAG, const SDLoc & dl) static
Return Mask with the necessary casting or extending for Mask according to MaskVT when lowering masking intrinsics.
Definition at line 23435 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::bitsLE(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is32Bit(), llvm::isAllOnesConstant(), llvm::X86::isZeroNode(), llvm::MipsISD::Lo, llvm::MVT::v32i1, and llvm::MVT::v64i1.
Referenced by getGatherNode(), getPrefetchNode(), getScatterNode(), getVectorMaskingNode(), LowerINTRINSIC_W_CHAIN(), lowerShuffleToEXPAND(), lowerShuffleWithPSHUFB(), and recoverFramePointer().
getMaxByValAlign()
static void getMaxByValAlign (Type * Ty, unsigned & MaxAlign) static
Helper for getByValTypeAlignment to determine the desired ByVal argument alignment.
Definition at line 2197 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::getByValTypeAlignment().
getMOVL()
static SDValue getMOVL (SelectionDAG & DAG, const SDLoc & dl, MVT VT, SDValue V1, SDValue V2) static
Returns a vector_shuffle mask for an movs{s|d}, movd operation of specified width.
Definition at line 3767 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::addCallSiteInfo(), llvm::SelectionDAG::addHeapAllocSite(), llvm::CCValAssign::AExt, llvm::AArch64CC::AL, llvm::alignTo(), llvm::MachineFunction::allocateRegMask(), llvm::CCState::AllocateStack(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::CCValAssign::BCvt, llvm::X86ISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, Callee, llvm::TargetLowering::CallLoweringInfo::Callee, callIsStructReturn(), canGuaranteeTCO(), llvm::CC_X86(), llvm::TargetLowering::CallLoweringInfo::Chain, llvm::classifyEHPersonality(), CreateCopyOfByValArgument(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::TargetLowering::CallLoweringInfo::CS, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::TargetLowering::CallLoweringInfo::DL, llvm::TargetLowering::CallLoweringInfo::DoesNotReturn, llvm::dyn_cast(), llvm::numbers::e, E, llvm::N86::EBX, EmitTailCallStoreRetAddr(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase::empty(), llvm::TargetOptions::EnableDebugEntryValues, llvm::ISD::ExternalSymbol, F(), first, llvm::CCValAssign::Full, G, llvm::SelectionDAG::getBitcast(), llvm::X86MachineFunctionInfo::getBytesToPopOnReturn(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::TargetMachine::getCodeModel(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::X86MachineFunctionInfo::getForwardedMustTailRegParms(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::X86Subtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachineFunction::getInfo(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getInstruction(), llvm::SelectionDAG::getIntPtrConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), llvm::Module::getModuleFlag(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::X86RegisterInfo::getNoPreservedMask(), llvm::MCRegisterInfo::getNumRegs(), llvm::SDNode::getOpcode(), llvm::Function::getPersonalityFn(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::X86Subtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::MachineOperand::getRegMaskSize(), llvm::MVT::getSizeInBits(), llvm::X86RegisterInfo::getSlotSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::X86RegisterInfo::getStackRegister(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTarget(), llvm::MachineFunction::getTarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::X86Subtarget::getTargetTriple(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::CCValAssign::getValVT(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::ISD::GlobalAddress, llvm::X86ISD::GlobalBaseReg, llvm::MVT::Glue, llvm::TargetOptions::GuaranteedTailCallOpt, llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::Function::hasPersonalityFn(), llvm::X86Subtarget::hasSSE1(), llvm::Function::hasStructRetAttr(), I, llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CCValAssign::Indirect, llvm::MipsISD::Ins, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::EVT::is128BitVector(), llvm::X86Subtarget::is64Bit(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::X86::isCalleePop(), llvm::X86Subtarget::isCallingConvWin64(), llvm::isFuncletEHPersonality(), llvm::ISD::ArgFlagsTy::isInAlloca(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isInvoke(), llvm::CCValAssign::isMemLoc(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::isMustTailCall(), llvm::Triple::isOSMSVCRT(), llvm::X86Subtarget::isPICStyleGOT(), llvm::CCValAssign::isRegLoc(), isSortedByValueNo(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::X86Subtarget::isTarget64BitILP32(), llvm::X86Subtarget::isTargetMCU(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::EVT::isVector(), llvm::CodeModel::Large, llvm_unreachable, lowerMasksToReg(), llvm::BitmaskEnumDetail::Mask(), llvm::max(), llvm::CCValAssign::needsCustom(), NotStructReturn, llvm::X86ISD::NT_CALL, llvm::TargetMachine::Options, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, Passv64i1ArgInRegs(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::MipsISD::Ret, llvm::TargetLowering::CallLoweringInfo::RetTy, llvm::ISD::SCALAR_TO_VECTOR, second, llvm::MachineFrameInfo::setHasTailCall(), llvm::X86MachineFunctionInfo::setTCReturnAddrDelta(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), llvm::Sched::Source, StackStructReturn, llvm::CallingConv::Tail, llvm::X86ISD::TC_RETURN, llvm::ISD::TokenFactor, llvm::TargetOptions::TrapUnreachable, TRI, llvm::Unknown, llvm::MVT::v2i64, llvm::MVT::v64i1, llvm::CallingConv::X86_INTR, llvm::CallingConv::X86_RegCall, llvm::CallingConv::X86_VectorCall, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by LowerBUILD_VECTORAsVariablePermute().
getNullFPConstForNullVal()
static SDValue getNullFPConstForNullVal (SDValue V, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
If a value is a scalar FP zero or a vector FP zero (potentially including undefined elements), return a zero constant that may be used to fold away that value.
In the case of a vector, the returned constant will not contain undefined elements even if the input parameter does. This makes it suitable to be used as a replacement operand with operations (eg, bitwise-and) where an undef should not propagate.
Definition at line 42821 of file X86ISelLowering.cpp.
References llvm::SDValue::getSimpleValueType(), llvm::SDValue::getValueType(), getZeroVector(), isNullFPScalarOrVectorConst(), and llvm::EVT::isVector().
Referenced by combineFAnd(), and combineFAndn().
getOnesVector()
static SDValue getOnesVector (EVT VT, SelectionDAG & DAG, const SDLoc & dl) static
Returns a vector of specified type with all bits set.
Always build ones vectors as <4 x i32>, <8 x i32> or <16 x i32>. Then bitcast to their original type, ensuring they get CSE'd.
Definition at line 5991 of file X86ISelLowering.cpp.
References assert(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::EVT::getSizeInBits(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), and llvm::EVT::is512BitVector().
Referenced by combineExtractSubvector(), InsertBitToMaskVector(), and materializeVectorConstant().
getOneTrueElt()
static int getOneTrueElt (SDValue V) static
If V is a build vector of boolean constants and exactly one of those constants is true, return the operand index of that true element.
Otherwise, return -1.
Definition at line 41319 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i1, and llvm::SDValue::isUndef().
Referenced by getParamsForOneTrueMaskedElt().
getOpcode_EXTEND_VECTOR_INREG()
static unsigned getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode) static
Definition at line 6002 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm_unreachable, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by combineExtractSubvector(), getExtendInVec(), LowerAVXExtend(), and matchUnaryShuffle().
getOpcodeForRetpoline()
static unsigned getOpcodeForRetpoline (unsigned RPOpc) static
Definition at line 31345 of file X86ISelLowering.cpp.
References llvm_unreachable.
Referenced by getRetpolineSymbol().
getPackDemandedElts()
static void getPackDemandedElts (EVT VT, const APInt & DemandedElts, APInt & DemandedLHS, APInt & DemandedRHS) static
Definition at line 6534 of file X86ISelLowering.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getNullValue(), llvm::EVT::getSizeInBits(), and llvm::APInt::setBit().
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), getFauxShuffleMask(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
getParamsForOneTrueMaskedElt()
static bool getParamsForOneTrueMaskedElt (MaskedLoadStoreSDNode * MaskedOp, SelectionDAG & DAG, SDValue & Addr, SDValue & Index, unsigned & Alignment) static
Given a masked memory load/store operation, return true if it has one mask bit set.
If it has one mask bit set, then also return the memory address of the scalar element to load/store, the vector index to insert/extract that scalar element, and the alignment for the scalar memory access.
Definition at line 41354 of file X86ISelLowering.cpp.
References llvm::MemSDNode::getAlignment(), llvm::MaskedLoadStoreSDNode::getBasePtr(), llvm::SelectionDAG::getIntPtrConstant(), llvm::MaskedLoadStoreSDNode::getMask(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemoryVT(), getOneTrueElt(), llvm::EVT::getStoreSize(), llvm::EVT::getVectorElementType(), and llvm::MinAlign().
Referenced by reduceMaskedLoadToScalarLoad(), and reduceMaskedStoreToScalarStore().
getPMOVMSKB()
static SDValue getPMOVMSKB (const SDLoc & DL, SDValue V, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 27587 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasInt256(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MipsISD::Lo, llvm::X86ISD::MOVMSK, llvm::ISD::OR, llvm::ISD::SHL, llvm::SelectionDAG::SplitVector(), llvm::MVT::v32i8, llvm::MVT::v64i8, and llvm::ISD::ZERO_EXTEND.
Referenced by combineBitcastvxi1(), combineHorizontalPredicateResult(), and LowerBITCAST().
getPrefetchNode()
static SDValue getPrefetchNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget & Subtarget) static
Definition at line 24622 of file X86ISelLowering.cpp.
References C, llvm::dyn_cast(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), getMaskNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i1, llvm::MVT::i32, and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
getPSHUFShuffleMask()
static SmallVector<int, 4> getPSHUFShuffleMask (SDValue N) static
Get the PSHUF-style mask from PSHUF node.
This is a very minor wrapper around getTargetShuffleMask to easy forming v4 PSHUF-style masks that can be reused with such instructions.
Definition at line 34348 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetShuffleMask(), llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, and llvm::X86ISD::PSHUFLW.
Referenced by combineRedundantDWordShuffle(), and combineTargetShuffle().
getReadTimeStampCounter()
static void getReadTimeStampCounter (SDNode * N, const SDLoc & DL, unsigned Opcode, SelectionDAG & DAG, const X86Subtarget & Subtarget, SmallVectorImpl< SDValue > & Results) static
Handles the lowering of builtin intrinsics that read the time stamp counter (x86_rdtsc and x86_rdtscp).
This function is also used to custom lower READCYCLECOUNTER nodes.
Definition at line 24707 of file X86ISelLowering.cpp.
References llvm::N86::ECX, expandIntrinsicWChainHelper(), llvm::SelectionDAG::getCopyFromReg(), llvm::SDValue::getValue(), llvm::MVT::i32, and llvm::SmallVectorTemplateBase< T >::push_back().
Referenced by LowerINTRINSIC_W_CHAIN(), LowerREADCYCLECOUNTER(), and llvm::X86TargetLowering::ReplaceNodeResults().
getRetpolineSymbol()
static const char* getRetpolineSymbol (const X86Subtarget & Subtarget, unsigned Reg) static
Definition at line 31359 of file X86ISelLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addDisp(), llvm::addFrameReference(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addJumpTableIndex(), llvm::MachineInstrBuilder::addMBB(), llvm::X86::AddrDisp, llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::addRegOffset(), llvm::X86::AddrNumOperands, llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineOperand::ChangeToES(), llvm::X86Subtarget::classifyBlockAddressReference(), llvm::X86::COND_AE, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Dead, llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDI, llvm::N86::EDX, llvm::MachineJumpTableInfo::EK_BlockAddress, llvm::MachineJumpTableInfo::EK_LabelDifference32, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::FrameSetup, llvm::MCInstrInfo::get(), llvm::X86RegisterInfo::getBaseRegister(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getDataLayout(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::X86RegisterInfo::getFrameRegister(), llvm::MachineFrameInfo::getFunctionContextIndex(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::MachineFunction::getInfo(), llvm::X86Subtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::X86TargetLowering::getJumpTableEncoding(), llvm::MachineOperand::getMCSymbol(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), llvm::Module::getModuleFlag(), llvm::X86RegisterInfo::getNoPreservedMask(), llvm::MachineInstr::getOpcode(), getOpcodeForRetpoline(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::X86InstrInfo::getRegisterInfo(), llvm::X86Subtarget::getRegisterInfo(), llvm::X86MachineFunctionInfo::getRestoreBasePointerOffset(), llvm::X86RegisterInfo::getStackRegister(), llvm::MVT::getStoreSize(), llvm::MachineFunction::getTarget(), llvm::X86RegisterInfo::hasBasePointer(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineFunction::insert(), llvm::X86Subtarget::is64Bit(), llvm::MachineInstr::isDebugInstr(), llvm::MachineInstr::isEHLabel(), llvm::MachineBasicBlock::isEHPad(), llvm::TargetLowering::isPositionIndependent(), llvm::MachineOperand::isReg(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetNaCl64(), llvm::TargetRegisterInfo::isTypeLegalForClass(), llvm::RegState::Kill, llvm_unreachable, llvm::max(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), MI, MRI, llvm::MachineInstr::operands(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::MachineFunction::push_back(), Reg, llvm::MachineBasicBlock::removeSuccessor(), llvm::report_fatal_error(), llvm::reverse(), llvm::MachineInstr::setDesc(), llvm::MachineBasicBlock::setHasAddressTaken(), llvm::MachineBasicBlock::setIsEHPad(), llvm::MachineInstrBuilder::setMemRefs(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::CodeModel::Small, llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_rbegin(), llvm::MachineBasicBlock::succ_rend(), llvm::ARMBuildAttrs::Symbol, TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), llvm::ISD::TRAP, TRI, llvm::RegState::Undef, and llvm::X86Subtarget::useRetpolineExternalThunk().
getScalarMaskingNode()
static SDValue getScalarMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Creates an SDNode for a predicated scalar operation.
Returns
(X86vselect Mask, Op, PreservedSrc). The mask is coming as MVT::i8 and it should be transformed to MVT::v1i1 while lowering masking intrinsics. The main difference between ScalarMaskingNode and VectorMaskingNode is using "X86select" instead of "vselect". We just can't create the "vselect" node for a scalar instruction.
Definition at line 23500 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::X86ISD::FSETCCM, llvm::X86ISD::FSETCCM_SAE, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::getValueType(), getZeroVector(), llvm::MVT::i8, llvm::SDValue::isUndef(), llvm::X86ISD::SELECTS, llvm::MVT::v1i1, llvm::MVT::v8i1, and llvm::X86ISD::VFPCLASSS.
Referenced by recoverFramePointer().
getScalarValueForVectorElement()
static SDValue getScalarValueForVectorElement (SDValue V, int Idx, SelectionDAG & DAG) static
Try to get a scalar value for a specific element of a vector.
Looks through BUILD_VECTOR and SCALAR_TO_VECTOR nodes to find a scalar.
Definition at line 12427 of file X86ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::isVector(), llvm::peekThroughBitcasts(), and llvm::ISD::SCALAR_TO_VECTOR.
Referenced by lowerShuffleAsElementInsertion(), and lowerV2F64Shuffle().
getScatterNode()
static SDValue getScatterNode (unsigned Opc, SDValue Op, SelectionDAG & DAG, SDValue Src, SDValue Mask, SDValue Base, SDValue Index, SDValue ScaleOp, SDValue Chain, const X86Subtarget & Subtarget) static
Definition at line 24592 of file X86ISelLowering.cpp.
References C, llvm::dyn_cast(), llvm::SelectionDAG::getDataLayout(), getMaskNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::MVT::i1, llvm::BitmaskEnumDetail::Mask(), and llvm::MVT::Other.
Referenced by LowerINTRINSIC_W_CHAIN().
getSEHRegistrationNodeSize()
static int getSEHRegistrationNodeSize (const Function * Fn) static
Definition at line 23526 of file X86ISelLowering.cpp.
References llvm::classifyEHPersonality(), llvm::Function::getPersonalityFn(), llvm::Function::hasPersonalityFn(), llvm::MSVC_CXX, llvm::MSVC_X86SEH, and llvm::report_fatal_error().
Referenced by recoverFramePointer().
getSETCC()
static SDValue getSETCC (X86::CondCode Cond, SDValue EFLAGS, const SDLoc & dl, SelectionDAG & DAG) static
Helper for creating a X86ISD::SETCC node.
Definition at line 20564 of file X86ISelLowering.cpp.
Referenced by combineParity(), combineVectorSizedSetCCEquality(), combineX86SetCC(), foldXor1SetCC(), LowerADDSUBCARRY(), LowerCMP_SWAP(), LowerINTRINSIC_W_CHAIN(), recoverFramePointer(), and llvm::X86TargetLowering::ReplaceNodeResults().
getShuffleHalfVectors()
static SDValue getShuffleHalfVectors (const SDLoc & DL, SDValue V1, SDValue V2, ArrayRef< int > HalfMask, int HalfIdx1, int HalfIdx2, bool UndefLower, SelectionDAG & DAG, bool UseConcat = false) static
Given the output values from getHalfShuffleMask(), create a half width shuffle of extracted vectors followed by an insert back to full width.
Definition at line 15377 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::ISD::INSERT_SUBVECTOR, llvm::EVT::isSimple(), std::swap(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerShuffleWithUndefHalf(), and narrowShuffle().
getShuffleScalarElt()
static SDValue getShuffleScalarElt (SDNode * N, unsigned Index, SelectionDAG & DAG, unsigned Depth) static
Returns the scalar element that will make up the ith element of the result of the vector shuffle.
Definition at line 7588 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), getTargetShuffleMask(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::isInteger(), isTargetShuffle(), llvm::EVT::isVector(), llvm::ISD::SCALAR_TO_VECTOR, llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineToConsecutiveLoads().
getShuffleVectorZeroOrUndef()
static SDValue getShuffleVectorZeroOrUndef (SDValue V2, int Idx, bool IsZero, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Return a vector_shuffle of the specified vector of zero or undef vector.
This produces a shuffle where the low element of V2 is swizzled into the zero/undef vector, landing at element Idx. This produces a shuffle mask like 4,1,2,3 (idx=0) or 0,1,2,4 (idx=3).
Definition at line 6090 of file X86ISelLowering.cpp.
References llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), and getZeroVector().
Referenced by InsertBitToMaskVector(), LowerBUILD_VECTORAsVariablePermute(), and LowerUINT_TO_FP_i32().
getTargetConstantBitsFromNode()
static bool getTargetConstantBitsFromNode (SDValue Op, unsigned EltSizeInBits, APInt & UndefElts, SmallVectorImpl< APInt > & EltBits, bool AllowWholeUndefs = true, bool AllowPartialUndefs = true) static
Definition at line 6133 of file X86ISelLowering.cpp.
References llvm::any_of(), llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorImpl< T >::assign(), C, llvm::dyn_cast(), llvm::numbers::e, llvm::SmallVectorBase::empty(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::extractBits(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::APInt::getBitWidth(), llvm::APInt::getBoolValue(), llvm::APInt::getNullValue(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::APInt::getSplat(), getTargetConstantFromNode(), llvm::Value::getType(), llvm::EVT::getVectorNumElements(), llvm::ISD::INSERT_SUBVECTOR, llvm::APInt::insertBits(), llvm::APInt::isAllOnesValue(), isAnyInRange(), llvm::ISD::isBuildVectorOfConstantFPSDNodes(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SDValue::isUndef(), llvm::Type::isVectorTy(), llvm::BitmaskEnumDetail::Mask(), llvm::peekThroughBitcasts(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::setBit(), llvm::APInt::setBits(), llvm::SmallVectorBase::size(), llvm::X86ISD::SUBV_BROADCAST, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VBROADCAST_LOAD, llvm::X86ISD::VZEXT_MOVL, llvm::X86ISD::Wrapper, and llvm::X86ISD::WrapperRIP.
Referenced by canonicalizeBitSelect(), combineAnd(), combineBitcast(), combineExtractVectorElt(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), combineX86ShufflesConstants(), getFauxShuffleMask(), getTargetShuffleAndZeroables(), getTargetShuffleMaskIndices(), llvm::X86::isConstantSplat(), isFNEG(), and LowerRotate().
getTargetConstantFromNode() [1/2]
static const Constant* getTargetConstantFromNode (LoadSDNode * Load) static
Definition at line 6105 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::LoadSDNode::getBasePtr(), llvm::ConstantPoolSDNode::getConstVal(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::isNormalLoad(), llvm::X86ISD::Wrapper, and llvm::X86ISD::WrapperRIP.
Referenced by getTargetConstantBitsFromNode(), llvm::X86TargetLowering::getTargetConstantFromLoad(), and getTargetConstantFromNode().
getTargetConstantFromNode() [2/2]
static const Constant* getTargetConstantFromNode (SDValue Op) static
Definition at line 6121 of file X86ISelLowering.cpp.
References getTargetConstantFromNode(), and llvm::peekThroughBitcasts().
getTargetShuffleAndZeroables()
static bool getTargetShuffleAndZeroables (SDValue N, SmallVectorImpl< int > & Mask, SmallVectorImpl< SDValue > & Ops, APInt & KnownUndef, APInt & KnownZero) static
Decode a target shuffle mask and inputs and see if any values are known to be undef or zero from their inputs.
Returns true if the target shuffle mask was decoded. FIXME: Merge this with computeZeroableShuffleElements?
Definition at line 6992 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::isFloatingPoint(), isTargetShuffle(), llvm::SDValue::isUndef(), isUndefOrZero(), llvm::X86::isZeroNode(), llvm::BitmaskEnumDetail::Mask(), llvm::peekThroughBitcasts(), llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::setBit(), Size, llvm::SM_SentinelUndef, llvm::SM_SentinelZero, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by combineTargetShuffle(), and getTargetShuffleInputs().
getTargetShuffleInputs() [1/2]
static bool getTargetShuffleInputs (SDValue Op, SmallVectorImpl< SDValue > & Inputs, SmallVectorImpl< int > & Mask, SelectionDAG & DAG, unsigned Depth = 0, bool ResolveKnownElts = true) static
Definition at line 7571 of file X86ISelLowering.cpp.
References llvm::APInt::getAllOnesValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isSimple(), and llvm::EVT::isVector().
Referenced by combineExtractWithShuffle(), combineX86ShufflesRecursively(), getFauxShuffleMask(), resolveZeroablesFromTargetShuffle(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode().
getTargetShuffleInputs() [2/2]
static bool getTargetShuffleInputs (SDValue Op, const APInt & DemandedElts, SmallVectorImpl< SDValue > & Inputs, SmallVectorImpl< int > & Mask, APInt & KnownUndef, APInt & KnownZero, SelectionDAG & DAG, unsigned Depth, bool ResolveKnownElts) static
Calls getTargetShuffleAndZeroables to resolve a target shuffle mask's inputs and then sets the SM_SentinelUndef and SM_SentinelZero values.
Returns true if the target shuffle mask was decoded.
Definition at line 7548 of file X86ISelLowering.cpp.
References getFauxShuffleMask(), getTargetShuffleAndZeroables(), llvm::SDValue::getValueType(), llvm::EVT::isSimple(), llvm::EVT::isVector(), resolveTargetShuffleFromZeroables(), and resolveZeroablesFromTargetShuffle().
getTargetShuffleMask()
static bool getTargetShuffleMask (SDNode * N, MVT VT, bool AllowSentinelZero, SmallVectorImpl< SDValue > & Ops, SmallVectorImpl< int > & Mask, bool & IsUnary) static
Calculates the shuffle mask corresponding to the target-specific opcode.
If the mask could be calculated, returns it in Mask, returns the shuffle operands in Ops, and returns true. Sets IsUnary to true if only one source is used. Note that this will set IsUnary for shuffles which use a single input multiple times, and in those cases it will adjust the mask to only have indices within that single input. It is an error to call this with non-empty Mask/Ops vectors.
Definition at line 6593 of file X86ISelLowering.cpp.
References llvm::any_of(), assert(), llvm::X86ISD::BLENDI, llvm::DecodeBLENDMask(), llvm::DecodeEXTRQIMask(), llvm::DecodeINSERTPSMask(), llvm::DecodeINSERTQIMask(), llvm::DecodeMOVDDUPMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodePSLLDQMask(), llvm::DecodePSRLDQMask(), llvm::DecodeScalarMoveMask(), llvm::DecodeSHUFPMask(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVectorBroadcast(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::decodeVSHUF64x2FamilyMask(), llvm::DecodeZeroMoveLowMask(), llvm::SmallVectorBase::empty(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::X86ISD::EXTRQI, llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), getTargetShuffleMaskIndices(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i8, llvm::X86ISD::INSERTPS, llvm::X86ISD::INSERTQI, llvm_unreachable, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::MOVSS, llvm::X86ISD::PALIGNR, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::X86ISD::SHUF128, llvm::X86ISD::SHUFP, llvm::SM_SentinelZero, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VPERM2X128, llvm::X86ISD::VPERMI, llvm::X86ISD::VPERMIL2, llvm::X86ISD::VPERMILPI, llvm::X86ISD::VPERMILPV, llvm::X86ISD::VPERMV, llvm::X86ISD::VPERMV3, llvm::X86ISD::VPPERM, llvm::X86ISD::VSHLDQ, llvm::X86ISD::VSRLDQ, and llvm::X86ISD::VZEXT_MOVL.
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), getPSHUFShuffleMask(), getShuffleScalarElt(), getTargetShuffleAndZeroables(), and isHorizontalBinOp().
getTargetShuffleMaskIndices()
static bool getTargetShuffleMaskIndices (SDValue MaskNode, unsigned MaskEltSizeInBits, SmallVectorImpl< uint64_t > & RawMask, APInt & UndefElts) static
Definition at line 6497 of file X86ISelLowering.cpp.
References getTargetConstantBitsFromNode(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getTargetShuffleMask().
getTargetVShiftByConstNode()
static SDValue getTargetVShiftByConstNode (unsigned Opc, const SDLoc & dl, MVT VT, SDValue SrcOp, uint64_t ShiftAmt, SelectionDAG & DAG) static
Handle vector element shifts where the shift amount is a constant.
Takes immediate version of shift as input.
Definition at line 23285 of file X86ISelLowering.cpp.
References assert(), C, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorElementType(), llvm::MVT::i8, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SDNode::isUndef(), llvm_unreachable, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, and llvm::X86ISD::VSRLI.
Referenced by combineVectorShiftVar(), getTargetVShiftNode(), LowerMUL(), LowerMULH(), LowerScalarImmediateShift(), LowerScalarVariableShift(), and LowerShift().
getTargetVShiftNode()
static SDValue getTargetVShiftNode (unsigned Opc, const SDLoc & dl, MVT VT, SDValue SrcOp, SDValue ShAmt, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle vector element shifts where the shift amount may or may not be a constant.
Takes immediate version of shift as input.
Definition at line 23365 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftUniformOpcode(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::X86ISD::VSHLDQ, llvm::X86ISD::VSRLDQ, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by LowerScalarVariableShift(), and recoverFramePointer().
getTargetVShiftUniformOpcode()
static unsigned getTargetVShiftUniformOpcode (unsigned Opc, bool IsVariable) static
Definition at line 23265 of file X86ISelLowering.cpp.
References llvm_unreachable, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::X86ISD::VSHL, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRA, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRL, and llvm::X86ISD::VSRLI.
Referenced by combineVectorShiftVar(), getTargetVShiftNode(), LowerScalarImmediateShift(), LowerScalarVariableShift(), and LowerShift().
GetTLSADDR()
static SDValue GetTLSADDR (SelectionDAG & DAG, SDValue Chain, GlobalAddressSDNode * GA, SDValue * InFlag, const EVT PtrVT, unsigned ReturnReg, unsigned char OperandFlags, bool LocalDynamic = false) static
Definition at line 18187 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getFrameInfo(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::TLSModel::LocalDynamic, llvm::MVT::Other, llvm::MachineFrameInfo::setAdjustsStack(), llvm::MachineFrameInfo::setHasCalls(), llvm::X86ISD::TLSADDR, and llvm::X86ISD::TLSBASEADDR.
Referenced by LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), and LowerToTLSLocalDynamicModel().
getUnderlyingExtractedFromVec()
static int getUnderlyingExtractedFromVec (SDValue & ExtractedFromVec, SDValue ExtIdx) static
For an EXTRACT_VECTOR_ELT with a constant index return the real underlying vector and index.
Modifies ExtractedFromVec to the real vector and returns the real index.
Definition at line 8647 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and isUndefOrInRange().
Referenced by buildFromShuffleMostly().
getUnpackh()
static SDValue getUnpackh (SelectionDAG & DAG, const SDLoc & dl, MVT VT, SDValue V1, SDValue V2) static
Returns a vector_shuffle node for an unpackh operation.
Definition at line 6079 of file X86ISelLowering.cpp.
References llvm::createUnpackShuffleMask(), llvm::SelectionDAG::getVectorShuffle(), and llvm::BitmaskEnumDetail::Mask().
Referenced by convertShiftLeftToScale(), LowerAVXExtend(), LowerHorizontalByteSum(), LowerMUL(), LowerMULH(), and LowerShift().
getUnpackl()
static SDValue getUnpackl (SelectionDAG & DAG, const SDLoc & dl, MVT VT, SDValue V1, SDValue V2) static
Returns a vector_shuffle node for an unpackl operation.
Definition at line 6071 of file X86ISelLowering.cpp.
References llvm::createUnpackShuffleMask(), llvm::SelectionDAG::getVectorShuffle(), and llvm::BitmaskEnumDetail::Mask().
Referenced by convertShiftLeftToScale(), LowerBUILD_VECTORAsVariablePermute(), LowerHorizontalByteSum(), LowerMUL(), LowerMULH(), LowerShift(), and LowerUINT_TO_FP_i64().
getV4X86ShuffleImm()
static unsigned getV4X86ShuffleImm (ArrayRef< int > Mask) static
Get a 4-lane 8-bit shuffle immediate for a mask.
This helper function produces an 8-bit shuffle immediate corresponding to the ubiquitous shuffle encoding scheme used in x86 instructions for shuffling 4 lanes. It can be used with most of the PSHUF instructions for example.
NB: We rely heavily on "undef" masks preserving the input lane.
Definition at line 10686 of file X86ISelLowering.cpp.
References assert(), and llvm::ArrayRef< T >::size().
Referenced by getV4X86ShuffleImm8ForMask(), matchBinaryPermuteShuffle(), and matchUnaryPermuteShuffle().
getV4X86ShuffleImm8ForMask()
static SDValue getV4X86ShuffleImm8ForMask (ArrayRef< int > Mask, const SDLoc & DL, SelectionDAG & DAG) static
Definition at line 10701 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getTargetConstant(), getV4X86ShuffleImm(), and llvm::MVT::i8.
Referenced by combineRedundantDWordShuffle(), combineTargetShuffle(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithSHUFPS(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
getv64i1Argument()
static SDValue getv64i1Argument (CCValAssign & VA, CCValAssign & NextVA, SDValue & Root, SelectionDAG & DAG, const SDLoc & Dl, const X86Subtarget & Subtarget, SDValue * InFlag = nullptr) static
Reads two 32 bit registers and creates a 64 bit mask value.
Parameters
VA The current 32 bit value that need to be assigned.
NextVA The next 32 bit value that need to be assigned.
Root The parent DAG node.
[in,out] InFlag Represents SDvalue in the parent DAG node for glue purposes. In the case the DAG is already using physical register instead of virtual, we should glue our new SDValue to InFlag SDvalue.
Returns
a new SDvalue of size 64bit.
Definition at line 2904 of file X86ISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), assert(), llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getCopyFromReg(), llvm::CCValAssign::getLocReg(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::CCValAssign::getValVT(), llvm::X86Subtarget::hasBWI(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::X86Subtarget::is32Bit(), llvm::CCValAssign::isRegLoc(), llvm::MipsISD::Lo, Reg, llvm::MVT::v32i1, and llvm::MVT::v64i1.
Referenced by isSortedByValueNo(), and lowerRegToMasks().
getVectorMaskingNode()
static SDValue getVectorMaskingNode (SDValue Op, SDValue Mask, SDValue PreservedSrc, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Return (and Op, Mask) for compare instructions or (vselect Mask, Op, PreservedSrc) for others along with the necessary casting or extending for Mask when lowering masking intrinsics.
Definition at line 23474 of file X86ISelLowering.cpp.
References getMaskNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::MVT::i1, llvm::isAllOnesConstant(), llvm::SDValue::isUndef(), and llvm::ISD::VSELECT.
Referenced by lowerShuffleAsBitBlend(), lowerShuffleAsBlend(), and recoverFramePointer().
getVShift()
static SDValue getVShift (bool isLeft, EVT VT, SDValue SrcOp, unsigned NumBits, SelectionDAG & DAG, const TargetLowering & TLI, const SDLoc & dl) static
Return a vector logical shift node.
Definition at line 7925 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i8, llvm::EVT::is128BitVector(), llvm::MVT::v16i8, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
Referenced by LowerBUILD_VECTORAsVariablePermute().
getX86XALUOOp()
static std::pair<SDValue, SDValue> getX86XALUOOp (X86::CondCode & Cond, SDValue Op, SelectionDAG & DAG) static
Definition at line 21963 of file X86ISelLowering.cpp.
getZeroVector()
static SDValue getZeroVector (MVT VT, const X86Subtarget & Subtarget, SelectionDAG & DAG, const SDLoc & dl) static
Returns a vector of specified type with all zero elements.
Definition at line 5594 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MVT::isFloatingPoint(), and llvm::MVT::v4f32.
Referenced by combineConcatVectorOps(), combineExtractSubvector(), combineInsertSubvector(), combineReductionToHorizontal(), combineShuffle(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), createVariablePermute(), getAVX2GatherNode(), getGatherNode(), getNullFPConstForNullVal(), getScalarMaskingNode(), getShuffleVectorZeroOrUndef(), getVectorMaskingNode(), InsertBitToMaskVector(), LowerAVXCONCAT_VECTORS(), LowerBUILD_VECTORAsVariablePermute(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerMLOAD(), LowerSCALAR_TO_VECTOR(), lowerShuffleAsBlend(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithSHUFPD(), lowerV16I8Shuffle(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), lowerVECTOR_SHUFFLE(), matchBinaryPermuteShuffle(), matchShuffleWithUNPCK(), recoverFramePointer(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), and widenSubVector().
hasBZHI()
static bool hasBZHI (const X86Subtarget & Subtarget, MVT VT) static
Definition at line 40029 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::X86Subtarget::hasBMI2(), llvm::X86Subtarget::is64Bit(), llvm::MVT::isScalarInteger(), and true.
hasFPCMov()
static bool hasFPCMov (unsigned X86CC) static
Is there a floating point cmov for the specific X86 condition code? Current x86 isa includes the following FP cmov instructions: fcmovb, fcomvbe, fcomve, fcmovu, fcmovae, fcmova, fcmovne, fcmovnu.
Definition at line 4930 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::X86::COND_NP, and llvm::X86::COND_P.
hasIdenticalHalvesShuffleMask()
static bool hasIdenticalHalvesShuffleMask (ArrayRef< int > Mask) static
Return true if a shuffle mask chooses elements identically in its top and bottom halves.
For example, any splat mask has the same top and bottom halves. If an element is undefined in only one half of the mask, the halves are not considered identical.
Definition at line 10668 of file X86ISelLowering.cpp.
References assert(), and llvm::ArrayRef< T >::size().
Referenced by LowerAVXExtend().
hasNonFlagsUse()
static bool hasNonFlagsUse (SDValue Op) static
return true if Op has a use that doesn't just read flags.
Definition at line 20676 of file X86ISelLowering.cpp.
References llvm::ISD::BRCOND, llvm::SDNode::getOpcode(), llvm::SDNode::use_iterator::getOperandNo(), llvm::SDNode::hasOneUse(), llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by EmitTest().
hasStackGuardSlotTLS()
static bool hasStackGuardSlotTLS (const Triple & TargetTriple) static
Definition at line 2455 of file X86ISelLowering.cpp.
References llvm::Triple::isAndroid(), llvm::Triple::isAndroidVersionLT(), llvm::Triple::isOSFuchsia(), and llvm::Triple::isOSGlibc().
Referenced by llvm::X86TargetLowering::getIRStackGuard(), and llvm::X86TargetLowering::insertSSPDeclarations().
incDecVectorConstant()
static SDValue incDecVectorConstant (SDValue V, SelectionDAG & DAG, bool IsInc) static
Given a buildvector constant, return a new vector constant with each element incremented or decremented.
If incrementing or decrementing would result in unsigned overflow or underflow or this is not a simple vector constant, return an empty value.
Definition at line 21268 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::APInt::isMaxValue(), llvm::APInt::isNullValue(), and llvm::SmallVectorTemplateBase< T >::push_back().
insert128BitVector()
static SDValue insert128BitVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & dl) static
Generate a DAG to put 128-bits into a vector > 128 bits.
This sets things up to match to an AVX VINSERTF128/VINSERTI128 or AVX-512 VINSERTF32x4/VINSERTI32x4 instructions or a simple superregister reference. Idx is an index in the 128 bits we want. It need not be aligned to a 128-bit boundary. That makes lowering INSERT_VECTOR_ELT operations easier.
Definition at line 5694 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getValueType(), insertSubVector(), and llvm::EVT::is128BitVector().
Referenced by InsertBitToMaskVector(), LowerSCALAR_TO_VECTOR(), and lowerV4X128Shuffle().
insert1BitVector()
static SDValue insert1BitVector (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Insert i1-subvector to i1-vector.
Definition at line 5811 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::flipAllBits(), llvm::APInt::getBitsSet(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasDQI(), High, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::X86Subtarget::is64Bit(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), llvm::X86ISD::KSHIFTL, llvm::X86ISD::KSHIFTR, llvm::ISD::OR, llvm::RegState::Undef, llvm::MVT::v16i1, llvm::MVT::v64i1, and llvm::MVT::v8i1.
Referenced by LowerINSERT_SUBVECTOR().
InsertBitToMaskVector()
static SDValue InsertBitToMaskVector (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Insert one bit to mask vector, like v16i1 or v8i1.
AVX-512 feature.
Definition at line 17770 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::X86ISD::BLENDI, llvm::dyn_cast(), extract128BitVector(), llvm::MVT::f32, llvm::MVT::f64, llvm::MachineFunction::getFunction(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), getOnesVector(), llvm::SDValue::getOperand(), getShuffleVectorZeroOrUndef(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::Function::hasMinSize(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, insert128BitVector(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::X86ISD::INSERTPS, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::isAllOnesConstant(), llvm::ISD::isBuildVectorAllZeros(), llvm::MVT::isInteger(), llvm::isPowerOf2_32(), llvm::X86::isZeroNode(), MayFoldLoad(), llvm::X86ISD::PINSRB, llvm::X86ISD::PINSRW, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, llvm::MVT::v16i8, llvm::MVT::v1i1, llvm::MVT::v4f32, and llvm::MVT::v8i16.
insertSubVector()
static SDValue insertSubVector (SDValue Result, SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & dl, unsigned vectorWidth) static
Definition at line 5664 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::ISD::INSERT_SUBVECTOR, llvm::isPowerOf2_32(), and llvm::SDValue::isUndef().
Referenced by concatSubVectors(), getHopForBuildVector(), insert128BitVector(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
is128BitLaneCrossingShuffleMask()
static bool is128BitLaneCrossingShuffleMask (MVT VT, ArrayRef< int > Mask) static
Test whether there are elements crossing 128-bit lanes in this shuffle mask.
Definition at line 10422 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), isLaneCrossingShuffleMask(), and llvm::BitmaskEnumDetail::Mask().
Referenced by combineX86ShuffleChain(), llvm::X86TargetLowering::isDesirableToCombineBuildVectorToShuffleTruncate(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), and matchUnaryPermuteShuffle().
is128BitLaneRepeatedShuffleMask() [1/2]
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > & RepeatedMask) static
Test whether a shuffle mask is equivalent within each 128-bit lane.
Definition at line 10467 of file X86ISelLowering.cpp.
References isRepeatedShuffleMask().
Referenced by LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV32I16Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), matchShuffleAsByteRotate(), and matchUnaryPermuteShuffle().
is128BitLaneRepeatedShuffleMask() [2/2]
static bool is128BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask) static
Definition at line 10473 of file X86ISelLowering.cpp.
References isRepeatedShuffleMask().
is128BitUnpackShuffleMask()
static bool is128BitUnpackShuffleMask (ArrayRef< int > Mask) static
Definition at line 10644 of file X86ISelLowering.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::createUnpackShuffleMask(), llvm::ArrayRef< T >::end(), llvm::MVT::getIntegerVT(), llvm::MVT::getVectorVT(), isTargetShuffleEquivalent(), and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleOfExtractsAsVperm(), and lowerShuffleWithUndefHalf().
is256BitLaneRepeatedShuffleMask()
static bool is256BitLaneRepeatedShuffleMask (MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > & RepeatedMask) static
Test whether a shuffle mask is equivalent within each 256-bit lane.
Definition at line 10480 of file X86ISelLowering.cpp.
References isRepeatedShuffleMask().
Referenced by lowerV8F64Shuffle(), lowerV8I64Shuffle(), and matchUnaryPermuteShuffle().
isAddSubOrSubAdd() [1/2]
static bool isAddSubOrSubAdd (const BuildVectorSDNode * BV, const X86Subtarget & Subtarget, SelectionDAG & DAG, SDValue & Opnd0, SDValue & Opnd1, unsigned & NumExtracts, bool & IsSubAdd) static
Returns true iff BV builds a vector with the result equivalent to the result of ADDSUB/SUBADD operation.
If true is returned then the operands of ADDSUB = Opnd0 +- Opnd1 (SUBADD = Opnd0 -+ Opnd1) operation are written to the parameters Opnd0 and Opnd1.
Definition at line 9017 of file X86ISelLowering.cpp.
References llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FSUB, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasSSE3(), llvm::MVT::isFloatingPoint(), llvm::SDValue::isUndef(), std::swap(), and llvm::ISD::UNDEF.
Referenced by combineShuffleToAddSubOrFMAddSub(), and lowerToAddSubOrFMAddSub().
isAddSubOrSubAdd() [2/2]
static bool isAddSubOrSubAdd (SDNode * N, const X86Subtarget & Subtarget, SelectionDAG & DAG, SDValue & Opnd0, SDValue & Opnd1, bool & IsSubAdd) static
Returns true iff the shuffle node N can be replaced with ADDSUB(SUBADD) operation.
If true is returned then the operands of ADDSUB(SUBADD) operation are written to the parameters Opnd0 and Opnd1.
We combine shuffle to ADDSUB(SUBADD) directly on the abstract vector shuffle nodes so it is easier to generically match. We also insert dummy vector shuffle nodes for the operands which explicitly discard the lanes which are unused by this operation to try to flow through the rest of the combiner the fact that they're unused.
Definition at line 34929 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::FADD, llvm::ISD::FSUB, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDNode::getValueType(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasSSE3(), isAddSubOrSubAddMask(), llvm::MVT::isFloatingPoint(), llvm::TargetLoweringBase::isTypeLegal(), N, and llvm::ISD::VECTOR_SHUFFLE.
isAddSubOrSubAddMask()
static bool isAddSubOrSubAddMask (ArrayRef< int > Mask, bool & Op0Even) static
Checks if the shuffle mask takes subsequent elements alternately from two vectors.
For example <0, 5, 2, 7> or <8, 1, 10, 3, 12, 5, 14, 7> are both correct.
Definition at line 34892 of file X86ISelLowering.cpp.
References Size, and llvm::ArrayRef< T >::size().
Referenced by combineShuffleToFMAddSub(), and isAddSubOrSubAdd().
isAndOrOfSetCCs()
static bool isAndOrOfSetCCs (SDValue Op, unsigned & Opc) static
Return true if node is an ISD::AND or ISD::OR of two X86ISD::SETCC nodes each of which has no other use apart from the AND / OR.
Definition at line 22794 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::ISD::OR, and llvm::X86ISD::SETCC.
Referenced by combineCompareEqual().
isAnyInRange()
static bool isAnyInRange (ArrayRef< int > Mask, int Low, int Hi) static
Return true if the value of any element in Mask falls within the specified range (L, H].
Definition at line 5373 of file X86ISelLowering.cpp.
References llvm::any_of(), and isInRange().
Referenced by getTargetConstantBitsFromNode(), and matchShuffleAsVPMOV().
isCMOVPseudo()
static bool isCMOVPseudo (MachineInstr & MI) static
Definition at line 30685 of file X86ISelLowering.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by createPHIsForCMOVsInSinkBB().
isFMAddSubOrFMSubAdd()
static bool isFMAddSubOrFMSubAdd (const X86Subtarget & Subtarget, SelectionDAG & DAG, SDValue & Opnd0, SDValue & Opnd1, SDValue & Opnd2, unsigned ExpectedUses) static
Returns true if is possible to fold MUL and an idiom that has already been recognized as ADDSUB/SUBADD(Opnd0, Opnd1) into FMADDSUB/FMSUBADD(x, y, Opnd1).
If (and only if) true is returned, the operands of FMADDSUB/FMSUBADD are written to parameters Opnd0, Opnd1, Opnd2.
Prior to calling this function it should be known that there is some SDNode that potentially can be replaced with an X86ISD::ADDSUB operation using Opnd0 and Opnd1 as operands. Also, this method is called before replacement of such SDNode with ADDSUB operation. Thus the number of Opnd0 uses is expected to be equal to 2. For example, this function may be called for the following IR: AB = fmul fast <2 x double> A, B Sub = fsub fast <2 x double> AB, C Add = fadd fast <2 x double> AB, C Addsub = shufflevector <2 x double> Sub, <2 x double> Add, <2 x i32> <i32 0, i32 3> There is a def for Addsub here, which potentially can be replaced by X86ISD::ADDSUB operation: Addsub = X86ISD::ADDSUB AB, C and such ADDSUB can further be replaced with FMADDSUB: Addsub = FMADDSUB A, B, C.
The main reason why this method is called before the replacement of the recognized ADDSUB idiom with ADDSUB operation is that such replacement is illegal sometimes. E.g. 512-bit ADDSUB is not available, while 512-bit FMADDSUB is.
Definition at line 9145 of file X86ISelLowering.cpp.
References llvm::TargetOptions::AllowFPOpFusion, llvm::FPOpFusion::Fast, llvm::ISD::FMUL, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTarget(), llvm::X86Subtarget::hasAnyFMA(), llvm::SDNode::hasNUsesOfValue(), llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
Referenced by combineShuffleToAddSubOrFMAddSub(), and lowerToAddSubOrFMAddSub().
isFNEG()
static SDValue isFNEG (SelectionDAG & DAG, SDNode * N, unsigned Depth = 0) static
Returns the negated value if the node N flips sign of FP value.
FP-negation node may have different forms: FNEG(x), FXOR (x, 0x80000000) or FSUB(0, x) AVX512F does not have FXOR, so FNEG is lowered as (bitcast (xor (bitcast x), (bitcast ConstantFP(0x80000000)))). In this case we go though all bitcasts. This also recognizes splat of a negated value and returns the splat of that value.
Definition at line 42437 of file X86ISelLowering.cpp.
References E, llvm::ISD::FNEG, llvm::ISD::FSUB, llvm::X86ISD::FXOR, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::SelectionDAG::getVectorShuffle(), I, llvm::ISD::INSERT_VECTOR_ELT, llvm::SDValue::isUndef(), llvm::SelectionDAG::MaxRecursionDepth, llvm::peekThroughBitcasts(), llvm::SmallVectorBase::size(), std::swap(), llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::XOR.
Referenced by combineFneg(), llvm::X86TargetLowering::getNegatedExpression(), and llvm::X86TargetLowering::isNegatibleForFree().
isFoldableUseOfShuffle()
static bool isFoldableUseOfShuffle (SDNode * N) static
Definition at line 8361 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDNode::hasOneUse(), isTargetShuffle(), N, llvm::SDNode::uses(), llvm::X86ISD::VPERMV, and llvm::X86ISD::VPERMV3.
Referenced by lowerBuildVectorAsBroadcast().
isFRClass()
static bool isFRClass (const TargetRegisterClass & RC) static
Check if RC is a vector register class.
I.e., FR* / VR* or one of their variant.
Definition at line 46828 of file X86ISelLowering.cpp.
References llvm::TargetRegisterClass::hasSuperClassEq().
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint().
isGRClass()
static bool isGRClass (const TargetRegisterClass & RC) static
Check if RC is a general purpose register class.
I.e., GR* or one of their variant.
Definition at line 46818 of file X86ISelLowering.cpp.
References llvm::TargetRegisterClass::hasSuperClassEq().
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint().
isHopBuildVector()
static bool isHopBuildVector (const BuildVectorSDNode * BV, SelectionDAG & DAG, unsigned & HOpcode, SDValue & V0, SDValue & V1) static
Definition at line 9208 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::DELETED_NODE, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FSUB, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::X86ISD::HADD, llvm::SDValue::hasOneUse(), llvm::X86ISD::HSUB, llvm::MVT::is256BitVector(), llvm::SDValue::isUndef(), and llvm::ISD::SUB.
Referenced by LowerToHorizontalOp().
isHorizontalBinOp()
static bool isHorizontalBinOp (SDValue & LHS, SDValue & RHS, SelectionDAG & DAG, const X86Subtarget & Subtarget, bool IsCommutative) static
Return 'true' if this vector operation is "horizontal" and return the operands for the horizontal operation in LHS and RHS.
A horizontal operation performs the binary operation on successive elements of its first operand, then on successive elements of its second operand, returning the resulting values in a vector. For example, if A = < float a0, float a1, float a2, float a3 > and B = < float b0, float b1, float b2, float b3 > then the result of doing a horizontal operation on A and B is A horizontal-op B = < a0 op a1, a2 op a3, b0 op b1, b2 op b3 >. In short, LHS and RHS are inspected to see if LHS op RHS is of the form A horizontal-op B, for some already available A and B, and if so then LHS is set to A, RHS to B, and the routine returns 'true'.
Definition at line 41782 of file X86ISelLowering.cpp.
References assert(), B, llvm::ArrayRef< T >::begin(), C, llvm::ShuffleVectorSDNode::commuteMask(), D, llvm::SmallVectorBase::empty(), llvm::ArrayRef< T >::end(), extract128BitVector(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getTargetShuffleMask(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::MVT::is256BitVector(), llvm::isNullConstant(), isTargetShuffle(), llvm::SDValue::isUndef(), llvm::peekThroughBitcasts(), llvm::SmallVectorTemplateBase< T >::push_back(), shouldUseHorizontalOp(), llvm::SmallVectorBase::size(), std::swap(), and llvm::ISD::VECTOR_SHUFFLE.
Referenced by combineAdd(), combineFaddFsub(), and combineSub().
isHorizontalBinOpPart()
static bool isHorizontalBinOpPart (const BuildVectorSDNode * N, unsigned Opcode, SelectionDAG & DAG, unsigned BaseIdx, unsigned LastIdx, SDValue & V0, SDValue & V1) static
This is a helper function of LowerToHorizontalOp().
This function checks that the build_vector N in input implements a 128-bit partial horizontal operation on a 256-bit vector, but that operation may not match the layout of an x86 256-bit horizontal instruction. In other words, if this returns true, then some extraction/insertion will be required to produce a valid horizontal instruction.
Parameter Opcode defines the kind of horizontal operation to match. For example, if Opcode is equal to ISD::ADD, then this function checks if N implements a horizontal arithmetic add; if instead Opcode is equal to ISD::SUB, then this function checks if this is a horizontal arithmetic sub.
This function only analyzes elements of N whose indices are in range [BaseIdx, LastIdx).
TODO: This function was originally used to match both real and fake partial horizontal operations, but the index-matching logic is incorrect for that. See the corrected implementation in isHopBuildVector(). Can we reduce this code because it is only used for partial h-op matching now?
Definition at line 8862 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SDNode::hasOneUse(), llvm::EVT::is256BitVector(), llvm::SDValue::isUndef(), llvm::SDNode::isUndef(), and llvm::EVT::isVector().
Referenced by LowerToHorizontalOp().
isInRange()
static bool isInRange (int Val, int Low, int Hi) static
Return true if Val falls within the specified range (L, H].
Definition at line 5367 of file X86ISelLowering.cpp.
Referenced by isAnyInRange(), isUndefOrInRange(), and isUndefOrZeroOrInRange().
isLaneCrossingShuffleMask()
static bool isLaneCrossingShuffleMask (unsigned LaneSizeInBits, unsigned ScalarSizeInBits, ArrayRef< int > Mask) static
Test whether there are elements crossing LaneSizeInBits lanes in this shuffle mask.
X86 divides up its shuffles into in-lane and cross-lane shuffle operations and we routinely test for these.
Definition at line 10406 of file X86ISelLowering.cpp.
References assert(), Size, and llvm::ArrayRef< T >::size().
Referenced by is128BitLaneCrossingShuffleMask().
isNonZeroElementsInOrder()
static bool isNonZeroElementsInOrder (const APInt & Zeroable, ArrayRef< int > Mask, const EVT & VectorType, bool & IsZeroSideLeft) static
Definition at line 10713 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::EVT::getVectorNumElements(), and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleToEXPAND().
isNoopShuffleMask()
static bool isNoopShuffleMask (ArrayRef< int > Mask) static
Tiny helper function to identify a no-op mask.
This is a somewhat boring predicate function. It checks whether the mask array input, which is assumed to be a single-input shuffle mask of the kind used by the X86 shuffle instructions (not a fully general ShuffleVectorSDNode mask) requires any shuffles to occur. Both undef and an in-place shuffle are 'no-op's.
Definition at line 10392 of file X86ISelLowering.cpp.
References assert(), Size, and llvm::ArrayRef< T >::size().
Referenced by combineTargetShuffle(), lowerShuffleAsByteRotate(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), and lowerV8I16GeneralSingleInputShuffle().
IsNOT()
static SDValue IsNOT (SDValue V, SelectionDAG & DAG) static
Definition at line 6045 of file X86ISelLowering.cpp.
References collectConcatOps(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::ISD::isBuildVectorAllOnes(), llvm::isNullConstant(), llvm::peekThroughBitcasts(), and llvm::ISD::XOR.
Referenced by combineAndnp(), combineANDXORWithAllOnesIntoANDNP(), and combineMOVMSK().
isNullFPScalarOrVectorConst()
static bool isNullFPScalarOrVectorConst (SDValue V) static
Definition at line 42811 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::ISD::isBuildVectorAllZeros(), and llvm::isNullFPConstant().
Referenced by combineFAndn(), combineFOr(), and getNullFPConstForNullVal().
isOrXorXorTree()
static bool isOrXorXorTree (SDValue X, bool Root = true) static
Recursive helper for combineVectorSizedSetCCEquality() to see if we have a recognizable memcmp expansion.
Definition at line 43673 of file X86ISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by combineVectorSizedSetCCEquality().
isProfitableToUseFlagOp()
static bool isProfitableToUseFlagOp (SDValue Op) static
Definition at line 20697 of file X86ISelLowering.cpp.
References llvm::ISD::CopyToReg, llvm::ISD::SETCC, llvm::ISD::STORE, and llvm::SDNode::uses().
Referenced by EmitAVX512Test(), and EmitTest().
isRepeatedShuffleMask()
static bool isRepeatedShuffleMask (unsigned LaneSizeInBits, MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > & RepeatedMask) static
Test whether a shuffle mask is equivalent within each sub-lane.
This checks a shuffle mask to see if it is performing the same lane-relative shuffle in each sub-lane. This trivially implies that it is also not lane-crossing. It may however involve a blend from the same lane of a second vector.
The specific repeated shuffle mask is populated in RepeatedMask, as it is non-trivial to compute in the face of undef lanes. The representation is suitable for use with existing 128-bit shuffles as entries from the second vector have been remapped to [LaneSize, 2*LaneSize).
Definition at line 10437 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorImpl< T >::assign(), llvm::MVT::getScalarSizeInBits(), Size, llvm::ArrayRef< T >::size(), and llvm::SM_SentinelUndef.
Referenced by is128BitLaneRepeatedShuffleMask(), and is256BitLaneRepeatedShuffleMask().
isRepeatedTargetShuffleMask()
static bool isRepeatedTargetShuffleMask (unsigned LaneSizeInBits, MVT VT, ArrayRef< int > Mask, SmallVectorImpl< int > & RepeatedMask) static
Test whether a target shuffle mask is equivalent within each sub-lane.
Unlike isRepeatedShuffleMask we must respect SM_SentinelZero.
Definition at line 10487 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorImpl< T >::assign(), llvm::MVT::getScalarSizeInBits(), isUndefOrZero(), Size, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by matchBinaryPermuteShuffle().
isSequentialOrUndefInRange()
static bool isSequentialOrUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low, int Step = 1) static
Return true if every element in Mask, beginning from position Pos and ending in Pos + Size, falls within the specified sequence (Low, Low + Step, ..., Low + (Size - 1) * Step) or is undef.
Definition at line 5406 of file X86ISelLowering.cpp.
References llvm::numbers::e, and isUndefOrEqual().
Referenced by combineX86ShuffleChain(), lowerShuffleAsByteShiftMask(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithUndefHalf(), lowerV8I16GeneralSingleInputShuffle(), match1BitShuffleAsKSHIFT(), matchShuffleAsINSERTQ(), matchShuffleAsShift(), matchShuffleAsVPMOV(), matchUnaryPermuteShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
isSequentialOrUndefOrZeroInRange()
static bool isSequentialOrUndefOrZeroInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size, int Low, int Step = 1) static
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size, falls within the specified sequential range (Low, Low+Size], or is undef or is zero.
Definition at line 5417 of file X86ISelLowering.cpp.
References llvm::numbers::e, and isUndefOrZero().
Referenced by combineX86ShuffleChain(), and matchShuffleWithUNPCK().
isShuffleEquivalent()
static bool isShuffleEquivalent (SDValue V1, SDValue V2, ArrayRef< int > Mask, ArrayRef< int > ExpectedMask) static
Checks whether a shuffle mask is equivalent to an explicit list of arguments.
This is a fast way to test a shuffle mask against a fixed pattern:
if (isShuffleEquivalent(Mask, 3, 2, {1, 0})) { ... }
It returns true if the mask is exactly as wide as the argument list, and each element of the mask is either -1 (signifying undef) or the value given in the argument.
Definition at line 10531 of file X86ISelLowering.cpp.
References assert(), llvm::dyn_cast(), Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerShuffleAsBroadcast(), lowerShuffleWithUNPCK(), lowerV16F32Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), and lowerV8F64Shuffle().
isShuffleFoldableLoad()
static bool isShuffleFoldableLoad (SDValue V) static
Helper to test for a load that can be folded with x86 shuffles.
This is particularly important because the set of instructions varies significantly based on whether the operand is a load or not.
Definition at line 12455 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::ISD::isNON_EXTLoad(), and llvm::peekThroughBitcasts().
Referenced by lowerShuffleAsBroadcast().
isShuffleMaskInputInPlace()
static bool isShuffleMaskInputInPlace (int Input, ArrayRef< int > Mask) static
Test whether the specified input (0 or 1) is in-place blended by the given mask.
This returns true if the elements from a particular input are already in the slot required by the given mask and require no permutation.
Definition at line 15529 of file X86ISelLowering.cpp.
References assert(), Size, and llvm::ArrayRef< T >::size().
Referenced by lowerV4F64Shuffle(), and lowerV4I64Shuffle().
isSingleSHUFPSMask()
static bool isSingleSHUFPSMask (ArrayRef< int > Mask) static
Test whether this can be lowered with a single SHUFPS instruction.
This is used to disable more specialized lowerings when the shufps lowering will happen to be efficient.
Definition at line 12615 of file X86ISelLowering.cpp.
References assert(), and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUndefHalf(), lowerV16I32Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), and lowerV8I32Shuffle().
isSortedByValueNo()
static bool isSortedByValueNo (ArrayRef< CCValAssign > ArgLocs) static
Definition at line 3343 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::AArch64CC::AL, llvm::CCState::AllocateStack(), Arg, ArgGPRs, argsAreStructReturn(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, B, llvm::CCValAssign::BCvt, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ArrayRef< T >::begin(), canGuaranteeTCO(), llvm::CC_X86(), llvm::classifyEHPersonality(), llvm::CoreCLR, CreateCopyOfByValArgument(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), E, llvm::SmallVectorBase::empty(), llvm::ArrayRef< T >::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ArrayRef< T >::end(), F(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::X86MachineFunctionInfo::getForwardedMustTailRegParms(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::X86Subtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::SelectionDAG::getMachineFunction(), llvm::Value::getName(), llvm::SelectionDAG::getNode(), llvm::Function::getPersonalityFn(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::X86MachineFunctionInfo::getRegSaveFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::X86MachineFunctionInfo::getSRetReturnReg(), llvm::MachinePointerInfo::getStack(), llvm::SelectionDAG::getStore(), llvm::MachineFunction::getTarget(), llvm::X86Subtarget::getTargetTriple(), getv64i1Argument(), llvm::CCValAssign::getValNo(), llvm::SelectionDAG::getValueType(), llvm::X86MachineFunctionInfo::getVarArgsFPOffset(), llvm::X86MachineFunctionInfo::getVarArgsGPOffset(), llvm::MachineFunction::getWinEHFuncInfo(), llvm::GPR, llvm::TargetOptions::GuaranteedTailCallOpt, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::GlobalValue::hasExternalLinkage(), llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::hasMustTailInVarArgFunc(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MachineFrameInfo::hasVAStart(), llvm::X86Subtarget::hasVLX(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CCValAssign::Indirect, llvm::SmallVectorImpl< T >::insert(), llvm::CallingConv::Intel_OCL_BI, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::X86Subtarget::is64Bit(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::X86::isCalleePop(), llvm::X86Subtarget::isCallingConvWin64(), llvm::Triple::isOSMSVCRT(), llvm::X86Subtarget::isTargetCygMing(), llvm::X86Subtarget::isTargetMCU(), llvm::EVT::isVector(), llvm::MachineRegisterInfo::liveins(), llvm_unreachable, lowerRegToMasks(), llvm::X86ISD::MOVDQ2Q, MRI, llvm::TargetMachine::Options, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::X86MachineFunctionInfo::setArgumentStackSize(), llvm::X86MachineFunctionInfo::setBytesToPopOnReturn(), llvm::X86MachineFunctionInfo::setForceFramePointer(), llvm::X86MachineFunctionInfo::setRegSaveFrameIndex(), llvm::X86MachineFunctionInfo::setSRetReturnReg(), llvm::X86MachineFunctionInfo::setVarArgsFPOffset(), llvm::X86MachineFunctionInfo::setVarArgsFrameIndex(), llvm::X86MachineFunctionInfo::setVarArgsGPOffset(), llvm::CCValAssign::SExt, shouldGuaranteeTCO(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), StackStructReturn, llvm::SPII::Store, llvm::CallingConv::Swift, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::X86Subtarget::useAVX512Regs(), llvm::X86Subtarget::useSoftFloat(), llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v1i1, llvm::MVT::v32i1, llvm::MVT::v4f32, llvm::MVT::v64i1, llvm::MVT::v8f32, llvm::MVT::v8i1, llvm::X86ISD::VASTART_SAVE_XMM_REGS, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_INTR, llvm::CallingConv::X86_RegCall, llvm::CallingConv::X86_ThisCall, llvm::CallingConv::X86_VectorCall, llvm::MVT::x86mmx, and llvm::CCValAssign::ZExt.
Referenced by getMOVL().
isSplatZeroExtended()
static SDValue isSplatZeroExtended (const BuildVectorSDNode * Op, unsigned & NumElt, MVT & EltType) static
Definition at line 8384 of file X86ISelLowering.cpp.
References llvm::MVT::getIntegerVT(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDNode::getSimpleValueType(), llvm::isNullConstant(), llvm::isPowerOf2_32(), and llvm::SDValue::isUndef().
Referenced by lowerBuildVectorAsBroadcast().
isTargetShuffle()
static bool isTargetShuffle (unsigned Opcode) static
Definition at line 4684 of file X86ISelLowering.cpp.
References llvm::X86ISD::BLENDI, llvm::X86ISD::EXTRQI, llvm::X86ISD::INSERTPS, llvm::X86ISD::INSERTQI, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::MOVSS, llvm::X86ISD::PALIGNR, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::X86ISD::SHUF128, llvm::X86ISD::SHUFP, llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VPERM2X128, llvm::X86ISD::VPERMI, llvm::X86ISD::VPERMIL2, llvm::X86ISD::VPERMILPI, llvm::X86ISD::VPERMILPV, llvm::X86ISD::VPERMV, llvm::X86ISD::VPERMV3, llvm::X86ISD::VPPERM, llvm::X86ISD::VSHLDQ, llvm::X86ISD::VSRLDQ, and llvm::X86ISD::VZEXT_MOVL.
Referenced by combineShuffle(), combineTargetShuffle(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), getShuffleScalarElt(), getTargetShuffleAndZeroables(), isFoldableUseOfShuffle(), and isHorizontalBinOp().
isTargetShuffleEquivalent()
static bool isTargetShuffleEquivalent (ArrayRef< int > Mask, ArrayRef< int > ExpectedMask, SDValue V1 = SDValue(), SDValue V2 = SDValue()) static
Checks whether a target shuffle mask is equivalent to an explicit pattern.
The masks must be exactly the same width.
If an element in Mask matches SM_SentinelUndef (-1) then the corresponding value in ExpectedMask is always accepted. Otherwise the indices must match.
SM_SentinelZero is accepted as a valid negative index but must match in both.
Definition at line 10567 of file X86ISelLowering.cpp.
References assert(), isUndefOrZeroOrInRange(), Size, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by combineX86ShuffleChain(), foldShuffleOfHorizOp(), is128BitUnpackShuffleMask(), isUnpackWdShuffleMask(), matchBinaryShuffle(), matchShuffleWithPACK(), matchShuffleWithUNPCK(), and matchUnaryShuffle().
isTargetShuffleVariableMask()
static bool isTargetShuffleVariableMask (unsigned Opcode) static
Definition at line 4723 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, llvm::ISD::OR, llvm::X86ISD::PSHUFB, llvm::X86ISD::VPERMIL2, llvm::X86ISD::VPERMILPV, llvm::X86ISD::VPERMV, llvm::X86ISD::VPERMV3, and llvm::X86ISD::VPPERM.
Referenced by combineX86ShufflesRecursively().
isTruncWithZeroHighBitsInput()
static bool isTruncWithZeroHighBitsInput (SDValue V, SelectionDAG & DAG) static
Definition at line 22038 of file X86ISelLowering.cpp.
References llvm::tgtok::Bits, llvm::APInt::getHighBitsSet(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::SelectionDAG::MaskedValueIsZero(), and llvm::ISD::TRUNCATE.
isUndefInRange()
static bool isUndefInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size) static
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size is the undef sentinel value.
Definition at line 5349 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::ArrayRef< T >::slice(), and llvm::SM_SentinelUndef.
Referenced by isUndefLowerHalf(), isUndefUpperHalf(), matchBinaryPermuteShuffle(), matchShuffleAsINSERTQ(), matchUnaryShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
isUndefLowerHalf()
static bool isUndefLowerHalf (ArrayRef< int > Mask) static
Return true if the mask creates a vector whose lower half is undefined.
Definition at line 5355 of file X86ISelLowering.cpp.
References isUndefInRange(), and llvm::ArrayRef< T >::size().
Referenced by getHalfShuffleMask(), and lowerShuffleWithUndefHalf().
isUndefOrEqual()
static bool isUndefOrEqual (int Val, int CmpVal) static
Val is the undef sentinel value or equal to the specified value.
Definition at line 5338 of file X86ISelLowering.cpp.
References llvm::SM_SentinelUndef.
Referenced by isSequentialOrUndefInRange(), lowerShuffleAsLanePermuteAndPermute(), lowerV8I16GeneralSingleInputShuffle(), matchUnaryShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
isUndefOrInRange() [1/2]
static bool isUndefOrInRange (int Val, int Low, int Hi) static
Return true if Val is undef or if its value falls within the specified range (L, H].
Definition at line 5379 of file X86ISelLowering.cpp.
References isInRange(), and llvm::SM_SentinelUndef.
Referenced by getFauxShuffleMask(), getUnderlyingExtractedFromVec(), isUndefOrInRange(), lowerShuffleAsByteShiftMask(), lowerShuffleAsUNPCKAndPermute(), lowerV8I16GeneralSingleInputShuffle(), matchBinaryPermuteShuffle(), and matchUnaryPermuteShuffle().
isUndefOrInRange() [2/2]
static bool isUndefOrInRange (ArrayRef< int > Mask, int Low, int Hi) static
Return true if every element in Mask is undef or if its value falls within the specified range (L, H].
Definition at line 5385 of file X86ISelLowering.cpp.
References llvm::all_of(), and isUndefOrInRange().
isUndefOrZero()
static bool isUndefOrZero (int Val) static
Val is either the undef or zero sentinel value.
Definition at line 5343 of file X86ISelLowering.cpp.
References llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineX86ShufflesRecursively(), getTargetShuffleAndZeroables(), isRepeatedTargetShuffleMask(), isSequentialOrUndefOrZeroInRange(), isUndefOrZeroInRange(), isUndefOrZeroOrInRange(), matchShuffleWithUNPCK(), and matchUnaryShuffle().
isUndefOrZeroInRange()
static bool isUndefOrZeroInRange (ArrayRef< int > Mask, unsigned Pos, unsigned Size) static
Return true if every element in Mask, beginning from position Pos and ending in Pos+Size is undef or is zero.
Definition at line 5428 of file X86ISelLowering.cpp.
References llvm::all_of(), isUndefOrZero(), and llvm::ArrayRef< T >::slice().
Referenced by matchBinaryPermuteShuffle(), matchUnaryShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
isUndefOrZeroOrInRange() [1/2]
static bool isUndefOrZeroOrInRange (int Val, int Low, int Hi) static
Return true if Val is undef, zero or if its value falls within the specified range (L, H].
Definition at line 5392 of file X86ISelLowering.cpp.
References isInRange(), and isUndefOrZero().
Referenced by combineX86ShuffleChain(), isTargetShuffleEquivalent(), isUndefOrZeroOrInRange(), and matchShuffleWithSHUFPD().
isUndefOrZeroOrInRange() [2/2]
static bool isUndefOrZeroOrInRange (ArrayRef< int > Mask, int Low, int Hi) static
Return true if every element in Mask is undef, zero or if its value falls within the specified range (L, H].
Definition at line 5398 of file X86ISelLowering.cpp.
References llvm::all_of(), and isUndefOrZeroOrInRange().
isUndefUpperHalf()
static bool isUndefUpperHalf (ArrayRef< int > Mask) static
Return true if the mask creates a vector whose upper half is undefined.
Definition at line 5361 of file X86ISelLowering.cpp.
References isUndefInRange(), and llvm::ArrayRef< T >::size().
Referenced by getHalfShuffleMask(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithUndefHalf(), matchShuffleAsEXTRQ(), matchShuffleAsINSERTQ(), and narrowShuffle().
isUnpackWdShuffleMask()
static bool isUnpackWdShuffleMask (ArrayRef< int > Mask, MVT VT) static
Definition at line 10629 of file X86ISelLowering.cpp.
References llvm::createUnpackShuffleMask(), isTargetShuffleEquivalent(), llvm::MVT::v8f32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by lowerV8F32Shuffle(), and lowerV8I32Shuffle().
isVKClass()
static bool isVKClass (const TargetRegisterClass & RC) static
Check if RC is a mask register class.
I.e., VK* or one of their variant.
Definition at line 46838 of file X86ISelLowering.cpp.
References llvm::TargetRegisterClass::hasSuperClassEq().
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint().
isX86CCSigned()
static bool isX86CCSigned (unsigned X86CC) static
Return true if the condition is an signed comparison operation.
Definition at line 4811 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, and llvm_unreachable.
Referenced by EmitCmp().
isX86LogicalCmp()
static bool isX86LogicalCmp (SDValue Op) static
Return true if opcode is a X86 logical comparison.
Definition at line 22024 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::ADD, llvm::X86ISD::AND, llvm::X86ISD::CMP, llvm::X86ISD::COMI, llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::X86ISD::OR, llvm::X86ISD::SAHF, llvm::X86ISD::SBB, llvm::X86ISD::SMUL, llvm::X86ISD::SUB, llvm::X86ISD::UCOMI, llvm::X86ISD::UMUL, and llvm::X86ISD::XOR.
isXor1OfSetCC()
static bool isXor1OfSetCC (SDValue Op) static
Return true if node is an ISD::XOR of a X86ISD::SETCC and 1 and that the SETCC node has a single use.
Definition at line 22806 of file X86ISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::isOneConstant(), llvm::X86ISD::SETCC, and llvm::ISD::XOR.
lower128BitShuffle()
static SDValue lower128BitShuffle (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Dispatching routine to lower various 128-bit x86 vector shuffles.
This routine breaks down the specific type of 128-bit shuffle and dispatches to the lowering routines accordingly.
Definition at line 14685 of file X86ISelLowering.cpp.
References llvm_unreachable, lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), lowerV8I16Shuffle(), llvm::MVT::SimpleTy, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by lowerVECTOR_SHUFFLE().
lower1BitShuffle()
static SDValue lower1BitShuffle (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 17101 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512BW(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::APInt::countLeadingOnes(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::X86ISD::KSHIFTL, llvm::X86ISD::KSHIFTR, llvm_unreachable, lower1BitShuffleAsKSHIFTR(), match1BitShuffleAsKSHIFT(), llvm::PowerOf2Floor(), llvm::ISD::SETGT, llvm::ISD::SIGN_EXTEND, llvm::MVT::SimpleTy, llvm::ArrayRef< T >::size(), llvm::ISD::TRUNCATE, llvm::X86Subtarget::useBWIRegs(), llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v2i1, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8i1, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by lowerVECTOR_SHUFFLE().
lower1BitShuffleAsKSHIFTR()
static SDValue lower1BitShuffleAsKSHIFTR (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 17021 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasDQI(), llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::SDValue::isUndef(), llvm::X86ISD::KSHIFTR, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::MVT::v16i1, and llvm::MVT::v8i1.
Referenced by lower1BitShuffle().
lower256BitShuffle()
static SDValue lower256BitShuffle (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
High-level routine to lower various 256-bit x86 vector shuffles.
This routine either breaks down the specific type of a 256-bit x86 vector shuffle or splits it into two 128-bit shuffles and fuses the results back together based on the available instructions.
Definition at line 16444 of file X86ISelLowering.cpp.
References llvm::count_if(), llvm::SelectionDAG::getBitcast(), llvm::MVT::getFloatingPointVT(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::isInteger(), llvm_unreachable, lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsElementInsertion(), lowerShuffleWithUndefHalf(), lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I32Shuffle(), llvm::MVT::SimpleTy, splitAndLowerShuffle(), llvm::MVT::v16i16, llvm::MVT::v32i8, llvm::MVT::v4f64, llvm::MVT::v4i64, llvm::MVT::v8f32, and llvm::MVT::v8i32.
Referenced by lowerVECTOR_SHUFFLE().
Lower256IntUnary()
static SDValue Lower256IntUnary (SDValue Op, SelectionDAG & DAG) static
Definition at line 25467 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), and LowerVectorIntUnary().
Referenced by LowerABS(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerVectorCTLZ(), and LowerVectorCTPOP().
Lower256IntVSETCC()
static SDValue Lower256IntVSETCC (SDValue Op, SelectionDAG & DAG) static
Break a VSETCC 256-bit integer VSETCC into two new 128 ones and then concatenate the result back.
Definition at line 21214 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is256BitVector(), and llvm::ISD::SETCC.
lower512BitShuffle()
static SDValue lower512BitShuffle (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
High-level routine to lower various 512-bit x86 vector shuffles.
This routine either breaks down the specific type of a 512-bit x86 vector shuffle or splits it into two 256-bit shuffles and fuses the results back together based on the available instructions.
Definition at line 16970 of file X86ISelLowering.cpp.
References assert(), llvm::count_if(), llvm::X86Subtarget::hasAVX512(), llvm_unreachable, lowerShuffleAsBroadcast(), lowerShuffleAsElementInsertion(), lowerShuffleWithUndefHalf(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV32I16Shuffle(), lowerV64I8Shuffle(), lowerV8F64Shuffle(), lowerV8I64Shuffle(), llvm::MVT::SimpleTy, llvm::ArrayRef< T >::size(), llvm::MVT::v16f32, llvm::MVT::v16i32, llvm::MVT::v32i16, llvm::MVT::v64i8, llvm::MVT::v8f64, and llvm::MVT::v8i64.
Referenced by lowerVECTOR_SHUFFLE().
Lower512IntUnary()
static SDValue Lower512IntUnary (SDValue Op, SelectionDAG & DAG) static
Definition at line 25475 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::is512BitVector(), llvm::MVT::isInteger(), and LowerVectorIntUnary().
Referenced by LowerBITREVERSE(), LowerVectorCTLZ(), and LowerVectorCTPOP().
LowerABS()
static SDValue LowerABS (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25804 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::BLENDV, llvm::X86ISD::CMOV, llvm::X86::COND_GE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), Lower256IntUnary(), llvm::ISD::SUB, llvm::X86ISD::SUB, llvm::MVT::v2i64, and llvm::MVT::v4i64.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), and llvm::X86TargetLowering::LowerOperation().
LowerADDRSPACECAST()
static SDValue LowerADDRSPACECAST (SDValue Op, SelectionDAG & DAG) static
Definition at line 28468 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::f128, llvm::AddrSpaceCastSDNode::getDestAddressSpace(), llvm::SDNode::getGluedNode(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::AddrSpaceCastSDNode::getSrcAddressSpace(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::i64, llvm::SDNode::isStrictFPOpcode(), llvm::TargetLowering::makeLibCall(), llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, llvm::X86AS::PTR32_UPTR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerADDSAT_SUBSAT()
static SDValue LowerADDSAT_SUBSAT (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 25756 of file X86ISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::SelectionDAG::getAllOnesConstant(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::i1, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), llvm::TargetLoweringBase::isOperationLegal(), llvm_unreachable, llvm::ISD::OR, llvm::ISD::SADDSAT, llvm::ISD::SETUGT, split256IntArith(), llvm::ISD::SSUBSAT, llvm::ISD::SUB, llvm::ISD::UADDSAT, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::USUBSAT, X, and Y.
Referenced by llvm::X86TargetLowering::LowerOperation().
lowerAddSub()
static SDValue lowerAddSub (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 25740 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::is256BitVector(), llvm::MVT::isInteger(), lowerAddSubToHorizontalOp(), split256IntArith(), and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerADDSUBCARRY()
static SDValue LowerADDSUBCARRY (SDValue Op, SelectionDAG & DAG) static
Definition at line 28109 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADC, llvm::X86ISD::ADD, llvm::ISD::ADDCARRY, llvm::X86::COND_B, llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), getSETCC(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::MVT::i1, llvm::MVT::i32, llvm::TargetLoweringBase::isTypeLegal(), llvm::ISD::MERGE_VALUES, llvm::X86ISD::SBB, and llvm::ISD::TRUNCATE.
Referenced by llvm::X86TargetLowering::LowerOperation().
lowerAddSubToHorizontalOp()
static SDValue lowerAddSubToHorizontalOp (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Depending on uarch and/or optimizing for size, we might prefer to use a vector operation in place of the typical scalar operation.
Definition at line 20338 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FSUB, llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::X86ISD::HADD, llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSSE3(), HOp, llvm::X86ISD::HSUB, llvm::MVT::isFloatingPoint(), llvm_unreachable, shouldUseHorizontalOp(), llvm::ISD::SUB, std::swap(), and X.
Referenced by lowerAddSub().
LowerADJUST_TRAMPOLINE()
static SDValue LowerADJUST_TRAMPOLINE (SDValue Op, SelectionDAG & DAG) static
Definition at line 25224 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::CallingConv::C, llvm::MachineFrameInfo::CreateStackObject(), E, llvm::N86::EAX, llvm::N86::ECX, llvm::CallingConv::Fast, llvm::X86ISD::FNSTCW16m, llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::MCRegisterInfo::getEncodingValue(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::X86Subtarget::getFrameLowering(), llvm::Function::getFunctionType(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::X86Subtarget::getRegisterInfo(), llvm::SDValue::getSimpleValueType(), llvm::TargetFrameLowering::getStackAlignment(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getVTList(), llvm::AttributeList::hasAttribute(), I, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::AttributeList::isEmpty(), llvm::Function::isVarArg(), llvm_unreachable, llvm::MachineMemOperand::MOStore, llvm::ISD::OR, llvm::MVT::Other, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::report_fatal_error(), llvm::ISD::SRL, llvm::ISD::SUB, llvm::CallingConv::Tail, llvm::ISD::TokenFactor, TRI, llvm::ISD::TRUNCATE, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::XCoreTargetLowering::getExceptionSelectorRegister(), and llvm::X86TargetLowering::LowerOperation().
LowerAndToBT()
static SDValue LowerAndToBT (SDValue And, ISD::CondCode CC, const SDLoc & dl, SelectionDAG & DAG, SDValue & X86CC) static
Result of 'and' is compared against zero.
Change to a BT node if possible. Returns the BT node and the condition code needed to use it.
Definition at line 21072 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::X86ISD::BT, llvm::SelectionDAG::computeKnownBits(), llvm::X86::COND_AE, llvm::X86::COND_B, llvm::ISD::Constant, llvm::KnownBits::countMinLeadingZeros(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::isOneConstant(), llvm::isPowerOf2_64(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm::Log2_64_Ceil(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::SETEQ, llvm::ISD::SHL, llvm::SelectionDAG::shouldOptForSize(), llvm::ISD::SRL, std::swap(), and llvm::ISD::TRUNCATE.
Referenced by EmitAVX512Test().
LowerANY_EXTEND()
static SDValue LowerANY_EXTEND (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22423 of file X86ISelLowering.cpp.
References assert(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::X86Subtarget::hasAVX(), llvm::MVT::i1, llvm::tgtok::In, LowerAVXExtend(), and LowerSIGN_EXTEND_Mask().
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
LowerAsSplatVectorLoad()
static SDValue LowerAsSplatVectorLoad (SDValue SrcOp, MVT VT, const SDLoc & dl, SelectionDAG & DAG) static
Definition at line 7937 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::i32, llvm::SelectionDAG::InferPtrAlignment(), llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::ISD::isNormalLoad(), llvm::ARM_MB::LD, llvm::BitmaskEnumDetail::Mask(), and llvm::MachineFrameInfo::setObjectAlignment().
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerATOMIC_FENCE()
static SDValue LowerATOMIC_FENCE (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27525 of file X86ISelLowering.cpp.
References emitLockedStackOp(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::X86Subtarget::hasMFence(), llvm::X86ISD::MEMBARRIER, llvm::X86ISD::MFENCE, llvm::MVT::Other, llvm::SequentiallyConsistent, and llvm::SyncScope::System.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerATOMIC_STORE()
static SDValue LowerATOMIC_STORE (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 28058 of file X86ISelLowering.cpp.
Referenced by llvm::XCoreTargetLowering::getExceptionSelectorRegister(), and llvm::X86TargetLowering::LowerOperation().
lowerAtomicArith()
static SDValue lowerAtomicArith (SDValue N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Lower atomic_load_ops into LOCK-prefixed operations.
Definition at line 27994 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, emitLockedStackOp(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getConstant(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MemSDNode::getOrdering(), llvm::SDNode::getSimpleValueType(), llvm::MemSDNode::getSyncScopeID(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDNode::getVTList(), llvm::SDNode::hasAnyUseOfValue(), llvm::isNullConstant(), lowerAtomicArithWithLOCK(), llvm::X86ISD::MEMBARRIER, llvm::ISD::MERGE_VALUES, N, llvm::MVT::Other, llvm::SequentiallyConsistent, llvm::ISD::SUB, and llvm::SyncScope::System.
Referenced by llvm::X86TargetLowering::LowerOperation().
lowerAtomicArithWithLOCK()
static SDValue lowerAtomicArithWithLOCK (SDValue N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 27962 of file X86ISelLowering.cpp.
References llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_XOR, llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::X86ISD::LADD, llvm::X86ISD::LAND, llvm_unreachable, llvm::X86ISD::LOR, llvm::X86ISD::LSUB, llvm::X86ISD::LXOR, N, and llvm::MVT::Other.
Referenced by combineSetCCAtomicArith(), and lowerAtomicArith().
LowerAVXCONCAT_VECTORS()
static SDValue LowerAVXCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 10219 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), getZeroVector(), llvm::MipsISD::Hi, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), llvm::MipsISD::Lo, llvm::SDNode::ops(), and llvm::ArrayRef< T >::slice().
Referenced by LowerCONCAT_VECTORS().
LowerAVXExtend()
static SDValue LowerAVXExtend (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 19569 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), getOpcode_EXTEND_VECTOR_INREG(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), hasIdenticalHalvesShuffleMask(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::isVector(), llvm::RegState::Undef, llvm::MVT::v16i8, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerANY_EXTEND(), and LowerZERO_EXTEND().
LowerBITCAST()
static SDValue LowerBITCAST (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27615 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::SelectionDAG::getBitcast(), llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), getPMOVMSKB(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE2(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::MVT::isScalarInteger(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MVT::isVector(), llvm::MipsISD::Lo, llvm::X86ISD::MOVDQ2Q, llvm::ISD::SCALAR_TO_VECTOR, llvm::SelectionDAG::SplitVector(), llvm::MVT::v16i1, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i16, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8i8, and llvm::MVT::x86mmx.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerBITREVERSE()
static SDValue LowerBITREVERSE (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27904 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasXOP(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MipsISD::Lo, Lower256IntUnary(), Lower512IntUnary(), LowerBITREVERSE_XOP(), llvm::ISD::OR, llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SRL, llvm::MVT::v16i32, and llvm::MVT::v8i64.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerBITREVERSE_XOP()
static SDValue LowerBITREVERSE_XOP (SDValue Op, SelectionDAG & DAG) static
Definition at line 27859 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITREVERSE, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::isVector(), Lower256IntUnary(), llvm::BitmaskEnumDetail::Mask(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v16i8, and llvm::X86ISD::VPPERM.
Referenced by LowerBITREVERSE().
LowerBUILD_VECTORAsVariablePermute()
static SDValue LowerBUILD_VECTORAsVariablePermute (SDValue V, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 9806 of file X86ISelLowering.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), buildFromShuffleMostly(), C, concatSubVectors(), llvm::countTrailingZeros(), createVariablePermute(), llvm::dyn_cast(), llvm::numbers::e, E, EltsFromConsecutiveLoads(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), getMOVL(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getShuffleVectorZeroOrUndef(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::EVT::getTypeForEVT(), llvm::SelectionDAG::getUNDEF(), getUnpackl(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getVShift(), getZeroVector(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::SmallSet< T, N, C >::insert(), llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MVT::isFloatingPoint(), llvm::SDNode::isOnlyUserOf(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::SDValue::isUndef(), isZero(), llvm::X86::isZeroNode(), llvm::ARM_MB::LD, llvm_unreachable, llvm::Lower, LowerAsSplatVectorLoad(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerBuildVectorv8i16(), lowerToAddSubOrFMAddSub(), LowerToHorizontalOp(), llvm::BitmaskEnumDetail::Mask(), materializeVectorConstant(), llvm::SDNode::op_begin(), llvm::SDNode::ops(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), llvm::SmallSet< T, N, C >::size(), llvm::SM_SentinelUndef, llvm::Upper, llvm::NVPTX::PTXLdStInstCode::V2, llvm::X86ISD::VBROADCAST, llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::ZERO_EXTEND.
LowerBUILD_VECTORvXi1()
static SDValue LowerBUILD_VECTORvXi1 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 8764 of file X86ISelLowering.cpp.
References assert(), llvm::numbers::e, llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::i1, llvm::tgtok::In, llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by LowerBUILD_VECTORAsVariablePermute().
lowerBuildVectorAsBroadcast()
static SDValue lowerBuildVectorAsBroadcast (BuildVectorSDNode * BVOp, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Attempt to use the vbroadcast instruction to generate a splat value from a splat BUILD_VECTOR which uses: a.
A single scalar load, or a constant. b. Repeated pattern of constants (e.g. <0,1,0,1> or <0,1,2,3,0,1,2,3>).
The VBROADCAST node is returned when a pattern is found, or SDValue() otherwise.
Definition at line 8423 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, assert(), llvm::ISD::BITCAST, C, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::BitVector::count(), llvm::HexagonISD::CP, llvm::ConstantFP::get(), getAlignment(), llvm::SelectionDAG::getBitcast(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), getConstantVector(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MVT::getFloatingPointVT(), llvm::Constant::getIntegerValue(), llvm::MVT::getIntegerVT(), llvm::Type::getIntNTy(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::BuildVectorSDNode::getSplatValue(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasCDI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::X86Subtarget::is32Bit(), llvm::MVT::is512BitVector(), llvm::BuildVectorSDNode::isConstantSplat(), isFoldableUseOfShuffle(), llvm::EVT::isInteger(), llvm::ISD::isNormalLoad(), llvm::SDNode::isOnlyUserOf(), isSplatZeroExtended(), llvm::EVT::isVector(), llvm::SelectionDAG::shouldOptForSize(), llvm::X86ISD::SUBV_BROADCAST, llvm::RegState::Undef, llvm::MVT::v16i1, llvm::MVT::v8i1, llvm::X86ISD::VBROADCAST, llvm::X86ISD::VBROADCASTM, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerBuildVectorAsInsert()
static SDValue LowerBuildVectorAsInsert (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 7678 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorNumElements(), getZeroVector(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v16i8, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by LowerBuildVectorv16i8(), and LowerBuildVectorv8i16().
lowerBuildVectorToBitOp()
static SDValue lowerBuildVectorToBitOp (BuildVectorSDNode * Op, SelectionDAG & DAG) static
If a BUILD_VECTOR's source elements all apply the same bit operation and one of their operands is constant, lower to a pair of BUILD_VECTOR and just apply the bit to the vectors.
NOTE: Its not in our interest to start make a general purpose vectorizer from this, but enough scalar bit operations are created from the later legalization + scalarization stages to need basic support.
Definition at line 9454 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::any_of(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::SDNode::getSimpleValueType(), llvm::BuildVectorSDNode::getSplatValue(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::SDNode::ops(), llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::XOR.
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerBuildVectorv16i8()
static SDValue LowerBuildVectorv16i8 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Custom lower build_vector of v16i8.
Definition at line 7720 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), getZeroVector(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INSERT_VECTOR_ELT, LowerBuildVectorAsInsert(), llvm::ISD::OR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SHL, llvm::ISD::TRUNCATE, llvm::MVT::v16i8, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerBuildVectorv4x32()
static SDValue LowerBuildVectorv4x32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Custom lower build_vector of v4i32 or v4f32.
Definition at line 7798 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SDValue::getConstantOperandAPInt(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasXOP(), llvm::X86ISD::INSERTPS, llvm::MVT::is128BitVector(), llvm::SDValue::isUndef(), llvm::X86::isZeroNode(), llvm::X86ISD::MOVDDUP, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, and llvm::MVT::v4f32.
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerBuildVectorv8i16()
static SDValue LowerBuildVectorv8i16 (SDValue Op, unsigned NonZeros, unsigned NumNonZero, unsigned NumZero, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Custom lower build_vector of v8i16.
Definition at line 7785 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasSSE41(), and LowerBuildVectorAsInsert().
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerCMP_SWAP()
static SDValue LowerCMP_SWAP (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27548 of file X86ISelLowering.cpp.
References llvm::AArch64CC::AL, assert(), llvm::X86::COND_E, llvm::N86::EAX, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), getSETCC(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::MVT::Glue, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::X86ISD::LCMPXCHG_DAG, llvm_unreachable, llvm::ISD::MERGE_VALUES, llvm::MVT::Other, Reg, llvm::MVT::SimpleTy, llvm::size(), Success, and llvm::T.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerCONCAT_VECTORS()
static SDValue LowerCONCAT_VECTORS (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 10356 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNumOperands(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::i1, llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), LowerAVXCONCAT_VECTORS(), and LowerCONCAT_VECTORSvXi1().
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerCONCAT_VECTORSvXi1()
static SDValue LowerCONCAT_VECTORSvXi1 (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 10277 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::countPopulation(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasDQI(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::isBuildVectorAllZeros(), llvm::isPowerOf2_32(), llvm::isPowerOf2_64(), llvm::SDValue::isUndef(), llvm::X86ISD::KSHIFTL, llvm::MipsISD::Lo, llvm::Log2_64(), llvm::SDNode::ops(), llvm::ArrayRef< T >::slice(), llvm::MVT::v16i1, and llvm::MVT::v8i1.
Referenced by LowerCONCAT_VECTORS().
LowerCTLZ()
static SDValue LowerCTLZ (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25622 of file X86ISelLowering.cpp.
References llvm::X86ISD::BSR, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::ISD::CTLZ, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::isVector(), LowerVectorCTLZ(), llvm::ISD::TRUNCATE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerCTPOP()
static SDValue LowerCTPOP (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27852 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::isVector(), and LowerVectorCTPOP().
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerCTTZ()
static SDValue LowerCTTZ (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25661 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::BSF, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::ISD::CTTZ, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::i8, and llvm::MVT::isVector().
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerEXTEND_VECTOR_INREG()
static SDValue LowerEXTEND_VECTOR_INREG (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22439 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extractSubVector(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MipsISD::Lo, llvm::BitmaskEnumDetail::Mask(), llvm::max(), llvm::ISD::SETGT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::SM_SentinelUndef, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::X86ISD::VSRAI, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerEXTRACT_SUBVECTOR()
static SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 17977 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::X86Subtarget::classifyBlockAddressReference(), llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalReference(), llvm::X86Subtarget::classifyLocalReference(), llvm::HexagonISD::CP, llvm::ISD::EXTRACT_SUBVECTOR, G, llvm::ConstantPoolSDNode::getAlignment(), llvm::TargetMachine::getCodeModel(), llvm::SelectionDAG::getConstant(), llvm::ConstantPoolSDNode::getConstVal(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFunction(), llvm::MachinePointerInfo::getGOT(), llvm::JumpTableSDNode::getIndex(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::getOffset(), llvm::ConstantPoolSDNode::getOffset(), llvm::SDValue::getOperand(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetBlockAddress(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTargetJumpTable(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86ISD::GlobalBaseReg, llvm::X86Subtarget::hasDQI(), llvm::MVT::i1, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::GlobalValue::isAbsoluteSymbolRef(), llvm::isGlobalRelativeToPICBase(), llvm::isGlobalStubReference(), llvm::X86::isOffsetSuitableForCodeModel(), llvm::X86Subtarget::isPICStyleRIPRel(), llvm::HexagonISD::JT, llvm::CodeModel::Kernel, llvm::X86ISD::KSHIFTR, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_NO_FLAG, llvm::Mod, llvm::CodeModel::Small, std::swap(), llvm::MVT::v16i1, llvm::MVT::v8i1, llvm::X86ISD::Wrapper, and llvm::X86ISD::WrapperRIP.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerEXTRACT_VECTOR_ELT_SSE4()
static SDValue LowerEXTRACT_VECTOR_ELT_SSE4 (SDValue Op, SelectionDAG & DAG) static
Definition at line 17533 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::is128BitVector(), llvm::isNullConstant(), llvm::X86ISD::PEXTRB, llvm::ISD::STORE, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), and llvm::MVT::v4i32.
Referenced by ExtractBitFromMaskVector().
LowerFABSorFNEG()
static SDValue LowerFABSorFNEG (SDValue Op, SelectionDAG & DAG) static
The only differences between FABS and FNEG are the mask and the logic op.
FNEG also has a folding opportunity for FNEG(FABS(x)).
Definition at line 20418 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, assert(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::X86ISD::FAND, llvm::ISD::FNEG, llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignMask(), llvm::SDValue::getSimpleValueType(), llvm::MVT::isVector(), llvm::ISD::SCALAR_TO_VECTOR, llvm::SDNode::uses(), llvm::MVT::v16f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v8f32, and llvm::MVT::v8f64.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerFCOPYSIGN()
static SDValue LowerFCOPYSIGN (SDValue Op, SelectionDAG & DAG) static
Definition at line 20478 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, assert(), llvm::MVT::bitsGT(), llvm::MVT::bitsLT(), llvm::APFloat::clearSign(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::X86ISD::FAND, llvm::X86ISD::FOR, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignMask(), llvm::SDValue::getSimpleValueType(), llvm::isConstOrConstSplatFP(), llvm::MVT::isVector(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v16f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v8f32, and llvm::MVT::v8f64.
Referenced by llvm::ARMTargetLowering::hasStandaloneRem(), llvm::X86TargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerFGETSIGN()
static SDValue LowerFGETSIGN (SDValue Op, SelectionDAG & DAG) static
Definition at line 20545 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i32, llvm::X86ISD::MOVMSK, llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v2f64, and llvm::MVT::v4f32.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerFSINCOS()
static SDValue LowerFSINCOS (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 28138 of file X86ISelLowering.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::SelectionDAG::getContext(), llvm::SDValue::getOperand(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::X86Subtarget::is64Bit(), and llvm::X86Subtarget::isTargetDarwin().
Referenced by llvm::ARMTargetLowering::hasStandaloneRem(), llvm::X86TargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerFunnelShift()
static SDValue LowerFunnelShift (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 18528 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::X86Subtarget::hasVBMI2(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86::isConstantSplat(), llvm::X86Subtarget::isSHLDSlow(), llvm::MVT::isVector(), llvm::X86ISD::SHLD, llvm::SelectionDAG::shouldOptForSize(), llvm::X86ISD::SHRD, std::swap(), llvm::APInt::urem(), llvm::X86ISD::VSHLD, llvm::X86ISD::VSHLDV, llvm::X86ISD::VSHRD, and llvm::X86ISD::VSHRDV.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerHorizontalByteSum()
static SDValue LowerHorizontalByteSum (SDValue V, MVT VT, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Compute the horizontal sum of bytes in V for the elements of VT.
Requires V to be a byte vector and VT to be an integer vector type with wider elements than V's type. The width of the elements of VT determines how many bytes of V are summed horizontally to produce each element of the result.
Definition at line 27697 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), getUnpackh(), getUnpackl(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), High, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::PACKUS, llvm::X86ISD::PSADBW, llvm::ISD::SHL, and llvm::ISD::SRL.
Referenced by LowerVectorCTPOP().
LowerI64IntToFP_AVX512DQ()
static SDValue LowerI64IntToFP_AVX512DQ (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 18580 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::getValue(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::SDNode::isStrictFPOpcode(), llvm::MVT::Other, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SINT_TO_FP, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::STRICT_UINT_TO_FP, and llvm::ISD::UINT_TO_FP.
Referenced by lowerINT_TO_FP_vXi64(), and lowerUINT_TO_FP_vec().
LowerINSERT_SUBVECTOR()
static SDValue LowerINSERT_SUBVECTOR (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 17970 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::i1, and insert1BitVector().
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
lowerINT_TO_FP_vXi64()
static SDValue lowerINT_TO_FP_vXi64 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 18685 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86TargetLowering::BuildFILD(), llvm::ISD::CONCAT_VECTORS, llvm::MachineFrameInfo::CreateStackObject(), llvm::X86ISD::CVTSI2P, llvm::MipsISD::Ext, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::MachineFunction::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::RTLIB::getSINTTOFP(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INSERT_SUBVECTOR, llvm::X86Subtarget::is64Bit(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::SDNode::isStrictFPOpcode(), llvm::MVT::isVector(), LowerI64IntToFP_AVX512DQ(), llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SETLT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, Size, llvm::ISD::SRL, llvm::X86ISD::STRICT_CVTSI2P, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i64, and vectorizeExtractedCast().
Referenced by lowerUINT_TO_FP_vec().
LowerINTRINSIC_W_CHAIN()
static SDValue LowerINTRINSIC_W_CHAIN (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 24800 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::X86ISD::CMOV, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::MachineFrameInfo::CreateFixedObject(), llvm::dyn_cast(), llvm::N86::ECX, EmitMaskedTruncSStore(), EmitTruncSStore(), llvm::X86ISD::ENQCMD, llvm::X86ISD::ENQCMDS, expandIntrinsicWChainHelper(), llvm::GATHER, llvm::GATHER_AVX2, getAVX2GatherNode(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandAPInt(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::X86MachineFunctionInfo::getFAIndex(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), getGatherNode(), llvm::MachineFunction::getInfo(), llvm::getIntrinsicWithChain(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMaskedStore(), getMaskNode(), llvm::TargetMachine::getMCAsmInfo(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), getPrefetchNode(), getReadTimeStampCounter(), llvm::X86Subtarget::getRegisterInfo(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getScatterNode(), getSETCC(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFunction::getTarget(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::isAllOnesConstant(), llvm_unreachable, llvm::X86ISD::LWPINS, MarkEHGuard(), MarkEHRegistrationNode(), llvm::ISD::MERGE_VALUES, llvm::IntrinsicData::Opc0, llvm::IntrinsicData::Opc1, Operation, llvm::MVT::Other, llvm::PREFETCH, llvm::X86ISD::RDPKRU, llvm::RDPMC, llvm::RDRAND, llvm::RDSEED, llvm::RDTSC, Results, llvm::MipsISD::Ret, llvm::SCATTER, llvm::X86MachineFunctionInfo::setFAIndex(), llvm::MachineFrameInfo::setFrameAddressIsTaken(), llvm::MachineFrameInfo::setHasCopyImplyingStackAdjustment(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), llvm::X86ISD::TPAUSE, llvm::TRUNCATE_TO_MEM_VI16, llvm::TRUNCATE_TO_MEM_VI32, llvm::TRUNCATE_TO_MEM_VI8, llvm::IntrinsicData::Type, llvm::X86ISD::UMWAIT, llvm::ISD::UNINDEXED, llvm::MCAsmInfo::usesWindowsCFI(), llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::X86ISD::VTRUNC, llvm::X86ISD::VTRUNCS, llvm::X86ISD::VTRUNCUS, llvm::X86ISD::WRPKRU, llvm::XGETBV, llvm::XTEST, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerIntVSETCC_AVX512()
static SDValue LowerIntVSETCC_AVX512 (SDValue Op, SelectionDAG & DAG) static
Definition at line 21242 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::i1, llvm::ISD::SETLT, and std::swap().
LowerLoad()
static SDValue LowerLoad (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22758 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasDQI(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i8, llvm::MVT::isInteger(), llvm::MVT::isVector(), and llvm::MVT::v16i1.
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
lowerMasksToReg()
static SDValue lowerMasksToReg (const SDValue & ValArg, const EVT & ValLoc, const SDLoc & Dl, SelectionDAG & DAG) static
Lowers masks values (v*i1) to the local register values.
Returns
DAG node after lowering to register type
Definition at line 2581 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::v16i1, llvm::MVT::v1i1, llvm::MVT::v32i1, llvm::MVT::v64i1, and llvm::MVT::v8i1.
Referenced by getMOVL(), and Passv64i1ArgInRegs().
LowerMGATHER()
static SDValue LowerMGATHER (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 28418 of file X86ISelLowering.cpp.
References assert(), ExtendToType(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::SDValue::getValue(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::is512BitVector(), llvm::BitmaskEnumDetail::Mask(), llvm::MVT::Other, and llvm::MVT::v2i32.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMINMAX()
static SDValue LowerMINMAX (SDValue Op, SelectionDAG & DAG) static
Definition at line 25838 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::APInt::getSignedMinValue(), llvm::SDValue::getSimpleValueType(), llvm::MVT::i64, llvm::MVT::is256BitVector(), llvm_unreachable, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SMAX, llvm::ISD::SMIN, split256IntArith(), llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::MVT::v8i16, and llvm::ISD::XOR.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMLOAD()
static SDValue LowerMLOAD (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 28309 of file X86ISelLowering.cpp.
References assert(), ExtendToType(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedLoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MaskedLoadSDNode::getExtensionType(), llvm::SelectionDAG::getIntPtrConstant(), llvm::MaskedLoadSDNode::getMask(), llvm::SelectionDAG::getMaskedLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MaskedLoadSDNode::getOffset(), llvm::MaskedLoadSDNode::getPassThru(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i8, llvm::ISD::isBuildVectorAllZeros(), llvm::MaskedLoadSDNode::isExpandingLoad(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), llvm::MCID::Select, and llvm::ISD::VSELECT.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMSCATTER()
static SDValue LowerMSCATTER (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 28243 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, ExtendToType(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getTargetMemSDNode(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::is512BitVector(), llvm::BitmaskEnumDetail::Mask(), llvm::MVT::Other, llvm::MVT::v2f32, llvm::MVT::v2i1, llvm::MVT::v2i32, and llvm::MVT::v2i64.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMSTORE()
static SDValue LowerMSTORE (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 28376 of file X86ISelLowering.cpp.
References assert(), ExtendToType(), llvm::MaskedLoadStoreSDNode::getAddressingMode(), llvm::MaskedStoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MaskedStoreSDNode::getMask(), llvm::SelectionDAG::getMaskedStore(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::MaskedStoreSDNode::getOffset(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MaskedStoreSDNode::getValue(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i8, llvm::MVT::is512BitVector(), llvm::MaskedStoreSDNode::isCompressingStore(), llvm::MaskedStoreSDNode::isTruncatingStore(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMUL()
static SDValue LowerMUL (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25877 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), B, llvm::X86Subtarget::canExtendTo512BW(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), getTargetVShiftByConstNode(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), getUnpackl(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::is256BitVector(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::APInt::isSubsetOf(), llvm::ISD::MUL, llvm::X86ISD::PACKUS, llvm::X86ISD::PMULUDQ, llvm::SmallVectorTemplateBase< T >::push_back(), split256IntArith(), llvm::ISD::TRUNCATE, llvm::RegState::Undef, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8i64, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRLI, and llvm::KnownBits::Zero.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerMULH()
static SDValue LowerMULH (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 26022 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), B, llvm::X86Subtarget::canExtendTo512BW(), extract128BitVector(), Fixup, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SDValue::getSimpleValueType(), getTargetVShiftByConstNode(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), getUnpackl(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i64, llvm::MVT::is256BitVector(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::X86Subtarget::isTargetWin64(), llvm_unreachable, llvm::MipsISD::Lo, llvm::makeArrayRef(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::X86ISD::PACKUS, llvm::X86ISD::PMULDQ, llvm::X86ISD::PMULUDQ, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SETGT, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, split256IntArith(), split512IntArith(), llvm::ISD::SREM, llvm::ISD::SUB, T1, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UREM, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v64i8, llvm::MVT::v8i32, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRLI, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerREADCYCLECOUNTER()
static SDValue LowerREADCYCLECOUNTER (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 24728 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), getReadTimeStampCounter(), llvm::RDTSC, and Results.
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
lowerRegToMasks()
static SDValue lowerRegToMasks (const SDValue & ValArg, const EVT & ValVT, const EVT & ValLoc, const SDLoc & Dl, SelectionDAG & DAG) static
The function will lower a register of various sizes (8/16/32/64) to a mask value of the expected size (v8i1/v16i1/v32i1/v64i1)
Returns
a DAG node contains the operand after lowering to mask type.
Definition at line 2955 of file X86ISelLowering.cpp.
References llvm::CCState::AnalyzeCallResult(), assert(), llvm::CCValAssign::BCvt, llvm::CCValAssign::convertToReg(), E, errorUnsupported(), llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getIntPtrConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::X86Subtarget::getRegisterInfo(), llvm::MVT::getScalarType(), llvm::EVT::getSimpleVT(), getv64i1Argument(), llvm::SDValue::getValue(), llvm::CCValAssign::getValVT(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasX87(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MipsISD::Ins, llvm::CCValAssign::isExtInLoc(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MVT::isVector(), llvm_unreachable, llvm::CCValAssign::needsCustom(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::report_fatal_error(), llvm::RetCC_X86(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::SimpleTy, llvm::SmallVectorBase::size(), TRI, llvm::ISD::TRUNCATE, llvm::MVT::v16i1, llvm::MVT::v1i1, llvm::MVT::v32i1, llvm::MVT::v64i1, and llvm::MVT::v8i1.
Referenced by isSortedByValueNo().
LowerRotate()
static SDValue LowerRotate (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27101 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::AtomicRMWInst::Add, llvm::ISD::AND, llvm::AtomicRMWInst::And, assert(), C, llvm::TargetLoweringBase::CmpXChg, convertShiftLeftToScale(), llvm::Instruction::eraseFromParent(), ExperimentalUnorderedISEL, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FSub, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::getFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::AtomicRMWInst::getOperation(), llvm::AtomicRMWInst::getOrdering(), llvm::AtomicRMWInst::getPointerOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::SDValue::getSimpleValueType(), llvm::AtomicCmpXchgInst::getStrongestFailureOrdering(), llvm::AtomicRMWInst::getSyncScopeID(), llvm::SelectionDAG::getTargetConstant(), getTargetConstantBitsFromNode(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), llvm::StoreInst::getValueOperand(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasCmpxchg16b(), llvm::X86Subtarget::hasCmpxchg8b(), llvm::Function::hasFnAttribute(), llvm::X86Subtarget::hasMFence(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasX87(), llvm::X86Subtarget::hasXOP(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::X86Subtarget::is64Bit(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SelectionDAG::isSplatValue(), llvm::LoadInst::isUnordered(), llvm::StoreInst::isUnordered(), llvm::MVT::isVector(), llvm_unreachable, llvm::MipsISD::Lo, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::ISD::MUL, llvm::ISD::MULHU, llvm::AtomicRMWInst::Nand, llvm::TargetLoweringBase::None, llvm::ISD::OR, llvm::AtomicRMWInst::Or, llvm::X86ISD::PCMPGT, llvm::X86ISD::PMULUDQ, llvm::Value::replaceAllUsesWith(), llvm::ISD::ROTL, llvm::LoadInst::setAtomic(), llvm::ISD::SHL, SI, llvm::SyncScope::SingleThread, split256IntArith(), llvm::ISD::SRL, llvm::ISD::SUB, llvm::AtomicRMWInst::Sub, SupportedVectorVarShift(), llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::Value::use_empty(), llvm::X86Subtarget::useSoftFloat(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::X86ISD::VROTLI, llvm::X86ISD::VROTRI, llvm::AtomicRMWInst::Xchg, llvm::AtomicRMWInst::Xor, and llvm::Z.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerSCALAR_TO_VECTOR()
static SDValue LowerSCALAR_TO_VECTOR (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 17932 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::MVT::i32, insert128BitVector(), llvm::MVT::is128BitVector(), llvm::MVT::isInteger(), llvm::X86::isZeroNode(), llvm::ISD::SCALAR_TO_VECTOR, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::X86TargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
LowerScalarImmediateShift()
static SDValue LowerScalarImmediateShift (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 26345 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::ARCISD::CMP, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), getTargetVShiftByConstNode(), getTargetVShiftUniformOpcode(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::APInt::getZExtValue(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE42(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::is512BitVector(), llvm::X86::isConstantSplat(), llvm_unreachable, llvm::Lower, llvm::X86ISD::PCMPGT, llvm::ISD::SETGT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, SupportedVectorShiftWithImm(), llvm::APInt::uge(), llvm::Upper, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i64, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRLI, and llvm::ISD::XOR.
Referenced by LowerShift().
LowerScalarVariableShift()
static SDValue LowerScalarVariableShift (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 26469 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::BITCAST, llvm::MVT::bitsGT(), llvm::MVT::bitsLE(), llvm::MVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::X86Subtarget::canExtendTo512BW(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::numbers::e, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getSplatValue(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTargetVShiftUniformOpcode(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasXOP(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, SupportedVectorShiftWithBaseAmnt(), llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v64i8, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerShift().
LowerShift()
static SDValue LowerShift (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 26620 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), C, llvm::X86Subtarget::canExtendTo512BW(), llvm::X86Subtarget::canExtendTo512DQ(), canWidenShuffleElements(), convertShiftLeftToScale(), llvm::dyn_cast(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::APInt::getSignMask(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftUniformOpcode(), llvm::SelectionDAG::getUNDEF(), getUnpackh(), getUnpackl(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::X86Subtarget::hasXOP(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, is128BitLaneRepeatedShuffleMask(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SelectionDAG::isKnownNeverZero(), llvm::SDValue::isUndef(), llvm::MVT::isVector(), llvm::MipsISD::Lo, LowerScalarImmediateShift(), LowerScalarVariableShift(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::X86ISD::PACKUS, llvm::X86ISD::PCMPGT, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T >::push_back(), R2, llvm::ISD::SETEQ, llvm::ISD::SETGT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, split256IntArith(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, SupportedVectorVarShift(), llvm::ISD::TRUNCATE, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::X86ISD::VPSHA, llvm::X86ISD::VPSHL, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRAI, llvm::X86ISD::VSRLI, llvm::ISD::XOR, llvm::Z, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerShiftParts()
static SDValue LowerShiftParts (SDValue Op, SelectionDAG & DAG) static
Lower SRA_PARTS and friends, which return two i32 values and take a 2 x i32 value to shift plus a shift amount.
TODO: Can this be moved to general expansion code?
Definition at line 18481 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::i8, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, and llvm::ISD::SRL.
Referenced by llvm::X86TargetLowering::LowerOperation().
lowerShuffleAsBitBlend()
static SDValue lowerShuffleAsBitBlend (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Try to emit a blend instruction for a shuffle using bit math.
This is used as a fallback approach when first class blend instructions are unavailable. Currently it is only suitable for integer vectors, but could be generalized for floating point vectors if desirable.
Definition at line 11150 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, assert(), llvm::SelectionDAG::getAllOnesConstant(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getVectorElementType(), getVectorMaskingNode(), llvm::MVT::isInteger(), llvm::ISD::OR, llvm::SmallVectorTemplateBase< T >::push_back(), Size, and llvm::ArrayRef< T >::size().
Referenced by lower256BitShuffle(), lowerV16I8Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsBitMask()
static SDValue lowerShuffleAsBitMask (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to emit a bitmask instruction for a shuffle.
This handles cases where we can model a blend exactly as a bitmask due to one of the inputs being zeroable.
Definition at line 11095 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getAllOnesConstant(), llvm::APFloat::getAllOnesValue(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lower256BitShuffle(), lowerShuffleAsBlend(), lowerV16I8Shuffle(), lowerV4I32Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsBlend()
static SDValue lowerShuffleAsBlend (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Original, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to emit a blend instruction for a shuffle.
This doesn't do any checks for the availability of instructions for blending these values. It relies on the availability of the X86ISD::BLENDI pattern to be matched in the backend with the type given. What it does check for is that the shuffle mask is a blend, or convertible into a blend with zero.
Definition at line 11233 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::X86ISD::BLENDI, llvm::ShuffleVectorSDNode::commuteMask(), llvm::ArrayRef< T >::end(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), getVectorMaskingNode(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::MipsISD::Hi, llvm::MVT::i8, is128BitLaneRepeatedShuffleMask(), llvm::ISD::isNormalLoad(), LLVM_FALLTHROUGH, llvm_unreachable, llvm::MipsISD::Lo, lowerShuffleAsBitMask(), llvm::BitmaskEnumDetail::Mask(), matchShuffleAsBlend(), llvm::max(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SelectionDAG::shouldOptForSize(), llvm::MVT::SimpleTy, Size, std::swap(), llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleAsBlendAndPermute()
static SDValue lowerShuffleAsBlendAndPermute (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG, bool ImmBlends = false) static
Try to lower as a blend of elements from two inputs followed by a single-input permutation.
This matches the pattern where we can blend elements from two inputs and then reduce the shuffle to a single-input permutation.
Definition at line 11388 of file X86ISelLowering.cpp.
References assert(), canWidenShuffleElements(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), Size, and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleAsDecomposedShuffleBlend(), and lowerV4F32Shuffle().
lowerShuffleAsBlendOfPSHUFBs()
static SDValue lowerShuffleAsBlendOfPSHUFBs (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, SelectionDAG & DAG, bool & V1InUse, bool & V2InUse) static
Helper to form a PSHUFB-based shuffle+blend, opportunistically avoiding the blend if only one input is used.
Definition at line 14099 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorVT(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), llvm::ISD::OR, llvm::X86ISD::PSHUFB, Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I8Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsBroadcast()
static SDValue lowerShuffleAsBroadcast (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower broadcast of a single element.
For convenience, this code also bundles all of the subtarget feature set filtering. While a little annoying to re-dispatch on type here, there isn't a convenient way to factor it out.
Definition at line 12691 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::dyn_cast(), extract128BitVector(), llvm::MVT::f64, llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE3(), llvm::MVT::i64, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::X86Subtarget::is64Bit(), llvm::MVT::isFloatingPoint(), llvm::MVT::isInteger(), isShuffleEquivalent(), isShuffleFoldableLoad(), isSimple(), llvm::EVT::isVector(), lowerShuffleAsTruncBroadcast(), llvm::SelectionDAG::makeEquivalentMemoryOrdering(), MayFoldLoad(), llvm::X86ISD::MOVDDUP, llvm::peekThroughBitcasts(), llvm::ISD::SCALAR_TO_VECTOR, llvm::ArrayRef< T >::size(), llvm::MVT::v2f64, llvm::MVT::v4f64, llvm::MVT::v4i64, and llvm::X86ISD::VBROADCAST.
Referenced by lower512BitShuffle(), lowerV16I16Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), and lowerVECTOR_SHUFFLE().
lowerShuffleAsByteRotate()
static SDValue lowerShuffleAsByteRotate (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 11734 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSSE3(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is512BitVector(), isNoopShuffleMask(), llvm::MipsISD::Lo, matchShuffleAsByteRotate(), llvm::ISD::OR, llvm::X86ISD::PALIGNR, llvm::ArrayRef< T >::size(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
Referenced by lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleAsByteRotateAndPermute()
static SDValue lowerShuffleAsByteRotateAndPermute (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Helper to form a PALIGNR-based rotate+permute, merging 2 inputs and then permuting the elements of the result in place.
Definition at line 11490 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSSE3(), llvm::MipsISD::Hi, llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MipsISD::Lo, llvm::max(), llvm::X86ISD::PALIGNR, and llvm::SM_SentinelUndef.
Referenced by lowerShuffleAsDecomposedShuffleBlend(), and lowerV16I8Shuffle().
lowerShuffleAsByteShiftMask()
static SDValue lowerShuffleAsByteShiftMask (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a byte shift sequence.
Definition at line 11812 of file X86ISelLowering.cpp.
References assert(), llvm::APInt::countLeadingOnes(), llvm::APInt::countTrailingOnes(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i8, llvm::MVT::is128BitVector(), isNoopShuffleMask(), isSequentialOrUndefInRange(), isUndefOrInRange(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), llvm::MVT::v16i8, llvm::X86ISD::VSHLDQ, and llvm::X86ISD::VSRLDQ.
Referenced by lowerV16I8Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsDecomposedShuffleBlend()
static SDValue lowerShuffleAsDecomposedShuffleBlend (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Generic routine to decompose a shuffle and blend into independent blends and permutes.
This matches the extremely common pattern for handling combined shuffle+blend operations on newer X86 ISAs where we have very fast blend operations. It will try to pick the best arrangement of shuffles and blends.
Definition at line 11581 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), isNoopShuffleMask(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsUNPCKAndPermute(), Size, and llvm::ArrayRef< T >::size().
Referenced by lowerShuffleAsSplitOrBlend(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I16Shuffle(), and lowerV8I32Shuffle().
lowerShuffleAsElementInsertion()
static SDValue lowerShuffleAsElementInsertion (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower insertion of a single element into a zero vector.
This is a common pattern that we have especially efficient patterns to lower across all subtarget feature sets.
Definition at line 12464 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::MVT::f32, llvm::MVT::f64, llvm::find_if(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), getScalarValueForVectorElement(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::isFloatingPoint(), isNoopShuffleMask(), llvm::TargetLoweringBase::isTypeLegal(), llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::ISD::SCALAR_TO_VECTOR, Size, llvm::ArrayRef< T >::size(), llvm::MVT::v16i8, llvm::NVPTX::PTXLdStInstCode::V2, llvm::X86ISD::VSHLDQ, llvm::X86ISD::VZEXT_MOVL, and llvm::ISD::ZERO_EXTEND.
Referenced by lower256BitShuffle(), lower512BitShuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsInsertPS()
static SDValue lowerShuffleAsInsertPS (const SDLoc & DL, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, SelectionDAG & DAG) static
Definition at line 12970 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i8, llvm::X86ISD::INSERTPS, matchShuffleAsInsertPS(), and llvm::MVT::v4f32.
Referenced by lowerV4F32Shuffle().
lowerShuffleAsLanePermuteAndPermute()
static SDValue lowerShuffleAsLanePermuteAndPermute (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Lower a vector shuffle crossing multiple 128-bit lanes as a lane permutation followed by a per-lane permutation.
This is mainly for cases where we can have non-repeating permutes in each lane.
TODO: This is very similar to lowerShuffleAsLanePermuteAndRepeatedMask, we should investigate merging them.
Definition at line 14929 of file X86ISelLowering.cpp.
References llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), isSequentialOrUndefInRange(), isUndefOrEqual(), and llvm::SM_SentinelUndef.
Referenced by lowerV16I16Shuffle(), lowerV32I8Shuffle(), and lowerV4F64Shuffle().
lowerShuffleAsLanePermuteAndRepeatedMask()
static SDValue lowerShuffleAsLanePermuteAndRepeatedMask (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower a vector shuffle by first fixing the 128-bit lanes and then shuffling each lane.
This attempts to create a repeated lane shuffle where each lane uses one or two of the lanes of the inputs. The lanes of the input vectors are shuffled in one or two independent shuffles to get the lanes into the position needed by the final shuffle.
Definition at line 15157 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::numbers::e, llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getVectorShuffle(), is128BitLaneRepeatedShuffleMask(), llvm::SDValue::isUndef(), llvm::BitmaskEnumDetail::Mask(), llvm::ArrayRef< T >::size(), and std::swap().
Referenced by lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8F32Shuffle(), and lowerV8I32Shuffle().
lowerShuffleAsLanePermuteAndShuffle()
static SDValue lowerShuffleAsLanePermuteAndShuffle (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Lower a vector shuffle crossing multiple 128-bit lanes by shuffling one source with a lane permutation.
This lowering strategy results in four instructions in the worst case for a single-input cross lane shuffle which is lower than any other fully general cross-lane shuffle strategy I'm aware of. Special cases for each particular shuffle pattern should be handled prior to trying this lowering.
Definition at line 14991 of file X86ISelLowering.cpp.
References llvm::all_of(), assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX2(), is128BitLaneCrossingShuffleMask(), llvm::MVT::is256BitVector(), llvm::MVT::isFloatingPoint(), llvm::SDValue::isUndef(), lowerShuffleAsLanePermuteAndSHUFP(), Size, llvm::ArrayRef< T >::size(), splitAndLowerShuffle(), llvm::MVT::v4f64, and llvm::MVT::v4i64.
Referenced by lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), and lowerV8F32Shuffle().
lowerShuffleAsLanePermuteAndSHUFP()
static SDValue lowerShuffleAsLanePermuteAndSHUFP (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Definition at line 14893 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::i8, llvm::X86ISD::SHUFP, and llvm::MVT::v4f64.
Referenced by lowerShuffleAsLanePermuteAndShuffle(), and lowerV4F64Shuffle().
lowerShuffleAsPermuteAndUnpack()
static SDValue lowerShuffleAsPermuteAndUnpack (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a shuffle as a permute of the inputs followed by an UNPCK instruction.
This specifically targets cases where we end up with alternating between the two inputs, and so can permute them into something that feeds a single UNPCK instruction. Note that this routine only targets integer vectors because for floating point vectors we have a generalized SHUFPS lowering strategy that handles everything that doesn't exactly match an unpack, making this clever lowering unnecessary.
Definition at line 12995 of file X86ISelLowering.cpp.
References assert(), llvm::count_if(), llvm::SelectionDAG::getBitcast(), llvm::MVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::MVT::is128BitVector(), llvm::ISD::isBuildVectorAllZeros(), llvm::MVT::isFloatingPoint(), isNoopShuffleMask(), llvm::SDValue::isUndef(), Size, llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, and llvm::X86ISD::UNPCKL.
Referenced by lowerV16I8Shuffle(), lowerV4I32Shuffle(), and lowerV8I16Shuffle().
lowerShuffleAsRepeatedMaskAndLanePermute()
static SDValue lowerShuffleAsRepeatedMaskAndLanePermute (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle case where shuffle sources are coming from the same 128-bit lane and every lane can be represented as the same repeating mask - allowing us to shuffle the sources with the repeating shuffle and then permute the result to the destination lanes.
Definition at line 15543 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX2(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), llvm::MVT::is256BitVector(), llvm::max(), and llvm::SM_SentinelUndef.
Referenced by lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8F32Shuffle(), and lowerV8I32Shuffle().
lowerShuffleAsRotate()
static SDValue lowerShuffleAsRotate (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a dword/qword rotation.
AVX512 has a VALIGND/VALIGNQ instructions that will do an arbitrary rotation of the concatenation of two vectors; This routine will try to generically lower a vector shuffle through such an pattern.
Essentially it concatenates V1 and V2, shifts right by some number of elements, and takes the low elements as the result. Note that while this is specified as a right shift because x86 is little-endian, it is a left rotate of the vector lanes.
Definition at line 11791 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarType(), llvm::SelectionDAG::getTargetConstant(), llvm::X86Subtarget::hasVLX(), llvm::MipsISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MipsISD::Lo, matchShuffleAsRotate(), llvm::NVPTX::PTXLdStInstCode::V2, and llvm::X86ISD::VALIGN.
Referenced by lowerV16I32Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleAsShift()
static SDValue lowerShuffleAsShift (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 11961 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::getVectorNumElements(), llvm::MVT::i8, llvm::TargetLoweringBase::isTypeLegal(), llvm::BitmaskEnumDetail::Mask(), matchShuffleAsShift(), Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleAsSpecificZeroOrAnyExtend()
static SDValue lowerShuffleAsSpecificZeroOrAnyExtend (const SDLoc & DL, MVT VT, int Scale, int Offset, bool AnyExt, SDValue InputV, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower a vector shuffle as a zero or any extension.
Given a specific number of elements, element bit width, and extension stride, produce either a zero or any extension based on the available features of the subtarget. The extended elements are consecutive and begin and can start from an offsetted element index in the input; to avoid excess shuffling the offset must either being in the bottom lane or at the start of a higher lane. All extended elements must be from the same lane.
Definition at line 12146 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::MipsISD::Ext, llvm::X86ISD::EXTRQI, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), getExtendInVec(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm8ForMask(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE4A(), llvm::X86Subtarget::hasSSSE3(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::MVT::is128BitVector(), isUndefUpperHalf(), llvm::MipsISD::Lo, llvm::X86ISD::PSHUFB, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v8i16, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerShuffleAsZeroOrAnyExtend().
lowerShuffleAsSplitOrBlend()
static SDValue lowerShuffleAsSplitOrBlend (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Either split a vector in halves or decompose the shuffles and the blend.
This is provided as a good fallback for many lowerings of non-single-input shuffles with more than one 128-bit lane. In those cases, we want to select between splitting the shuffle into 128-bit components and stitching those back together vs. extracting the single-input shuffles and blending those results.
Definition at line 14840 of file X86ISelLowering.cpp.
References assert(), llvm::SmallBitVector::count(), llvm::count(), llvm::MVT::getSizeInBits(), llvm::SDValue::isUndef(), lowerShuffleAsDecomposedShuffleBlend(), llvm::SmallBitVector::resize(), Size, llvm::ArrayRef< T >::size(), and splitAndLowerShuffle().
Referenced by lowerV16I16Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV8F32Shuffle(), and lowerV8I32Shuffle().
lowerShuffleAsTruncBroadcast()
static SDValue lowerShuffleAsTruncBroadcast (const SDLoc & DL, MVT VT, SDValue V0, int BroadcastIdx, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower broadcast of a single - truncated - integer element, coming from a scalar_to_vector/build_vector node V0 with larger elements.
This assumes we have AVX2.
Definition at line 12562 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::X86Subtarget::hasAVX2(), llvm::MVT::i8, llvm::MVT::isInteger(), llvm::EVT::isVector(), llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SRL, llvm::ISD::TRUNCATE, and llvm::X86ISD::VBROADCAST.
Referenced by lowerShuffleAsBroadcast().
lowerShuffleAsUNPCKAndPermute()
static SDValue lowerShuffleAsUNPCKAndPermute (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Try to lower as an unpack of elements from two inputs followed by a single-input permutation.
This matches the pattern where we can unpack elements from two inputs and then reduce the shuffle to a single-input (wider) permutation.
Definition at line 11427 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), llvm::MipsISD::Hi, llvm::SDValue::isUndef(), isUndefOrInRange(), llvm::MipsISD::Lo, llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerShuffleAsDecomposedShuffleBlend().
lowerShuffleAsVTRUNCAndUnpack()
static SDValue lowerShuffleAsVTRUNCAndUnpack (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, SelectionDAG & DAG) static
Definition at line 15781 of file X86ISelLowering.cpp.
References assert(), llvm::APInt::countLeadingOnes(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVectorShuffle(), llvm::ISD::INSERT_SUBVECTOR, isSequentialOrUndefInRange(), llvm::ArrayRef< T >::size(), llvm::MVT::v16i8, llvm::MVT::v32i8, llvm::MVT::v4i64, and llvm::X86ISD::VTRUNC.
Referenced by lowerV32I8Shuffle().
lowerShuffleAsZeroOrAnyExtend()
static SDValue lowerShuffleAsZeroOrAnyExtend (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a zero extension on any microarch.
This routine will try to do everything in its power to cleverly lower a shuffle which happens to match the pattern of a zero extend. It doesn't check for the profitability of this lowering, it tries to aggressively match this pattern. It will use all of the micro-architectural details it can to emit an efficient lowering. It handles both blends with all-zero inputs to explicitly zero-extend and undef-lanes (sometimes undef due to masking out later).
The reason we have dedicated lowering for zext-style shuffles is that they are both incredibly common and often quite performance sensitive.
Definition at line 12308 of file X86ISelLowering.cpp.
References assert(), llvm::tgtok::Bits, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), isSequentialOrUndefInRange(), llvm::Lower, lowerShuffleAsSpecificZeroOrAnyExtend(), llvm::ArrayRef< T >::size(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2i64, and llvm::X86ISD::VZEXT_MOVL.
Referenced by lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4I32Shuffle(), lowerV64I8Shuffle(), lowerV8I16Shuffle(), and lowerV8I32Shuffle().
lowerShuffleOfExtractsAsVperm()
static SDValue lowerShuffleOfExtractsAsVperm (const SDLoc & DL, SDValue N0, SDValue N1, ArrayRef< int > Mask, SelectionDAG & DAG) static
If we are extracting two 128-bit halves of a vector and shuffling the result, match that to a 256-bit AVX2 vperm* instruction to avoid a multi-shuffle lowering.
Definition at line 12636 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::ArrayRef< T >::end(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SDValue::getConstantOperandAPInt(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SDValue::hasOneUse(), is128BitUnpackShuffleMask(), llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), and isSingleSHUFPSMask().
Referenced by lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), and lowerV4I32Shuffle().
lowerShuffleToEXPAND()
static SDValue lowerShuffleToEXPAND (const SDLoc & DL, MVT VT, const APInt & Zeroable, ArrayRef< int > Mask, SDValue & V1, SDValue & V2, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 10797 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::EXPAND, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), getMaskNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::MVT::i1, isNonZeroElementsInOrder(), llvm::max(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV4F64Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleWithPACK()
static SDValue lowerShuffleWithPACK (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 11078 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), and matchShuffleWithPACK().
Referenced by lowerV16I16Shuffle(), lowerV16I8Shuffle(), lowerV32I8Shuffle(), lowerV64I8Shuffle(), and lowerV8I16Shuffle().
lowerShuffleWithPERMV()
static SDValue lowerShuffleWithPERMV (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG & DAG) static
Definition at line 14350 of file X86ISelLowering.cpp.
References getConstVector(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SDValue::isUndef(), llvm::X86ISD::VPERMV, and llvm::X86ISD::VPERMV3.
Referenced by lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV64I8Shuffle(), lowerV8F64Shuffle(), and lowerV8I64Shuffle().
lowerShuffleWithPSHUFB()
static SDValue lowerShuffleWithPSHUFB (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a shuffle with a single PSHUFB of V1 or V2.
Definition at line 10739 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), getMaskNode(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::X86ISD::PSHUFB, Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I16Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), and lowerV64I8Shuffle().
lowerShuffleWithSHUFPD()
static SDValue lowerShuffleWithSHUFPD (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 15754 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), getZeroVector(), llvm::MVT::i8, matchShuffleWithSHUFPD(), llvm::X86ISD::SHUFP, llvm::MVT::v2f64, llvm::MVT::v4f64, and llvm::MVT::v8f64.
Referenced by lowerV4F64Shuffle(), and lowerV8F64Shuffle().
lowerShuffleWithSHUFPS()
static SDValue lowerShuffleWithSHUFPS (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG & DAG) static
Lower a vector shuffle using the SHUFPS instruction.
This is a helper routine dedicated to lowering vector shuffles using SHUFPS. It makes no assumptions about whether this is the best lowering, it simply uses it.
Definition at line 13292 of file X86ISelLowering.cpp.
References llvm::count_if(), llvm::find_if(), llvm::SelectionDAG::getNode(), getV4X86ShuffleImm8ForMask(), llvm::X86ISD::SHUFP, std::swap(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV4F32Shuffle(), lowerV8F32Shuffle(), and lowerV8I32Shuffle().
lowerShuffleWithSSE4A()
static SDValue lowerShuffleWithSSE4A (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, SelectionDAG & DAG) static
Try to lower a vector shuffle using SSE4a EXTRQ/INSERTQ.
Definition at line 12119 of file X86ISelLowering.cpp.
References llvm::X86ISD::EXTRQI, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::i8, llvm::X86ISD::INSERTQI, matchShuffleAsEXTRQ(), matchShuffleAsINSERTQ(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV16I8Shuffle(), and lowerV8I16Shuffle().
lowerShuffleWithUndefHalf()
static SDValue lowerShuffleWithUndefHalf (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower shuffles where an entire half of a 256 or 512-bit vector is UNDEF.
This allows for fast cases such as subvector extraction/insertion or shuffling smaller vector types which can lower more efficiently.
Definition at line 15417 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::getHalfNumVectorElementsVT(), getHalfShuffleMask(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), getShuffleHalfVectors(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasFastVariableShuffle(), llvm::MipsISD::Hi, llvm::ISD::INSERT_SUBVECTOR, is128BitUnpackShuffleMask(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), isSequentialOrUndefInRange(), isSingleSHUFPSMask(), llvm::SDValue::isUndef(), isUndefLowerHalf(), isUndefUpperHalf(), and llvm::SmallVectorBase::size().
Referenced by lower256BitShuffle(), and lower512BitShuffle().
lowerShuffleWithUNPCK()
static SDValue lowerShuffleWithUNPCK (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, SDValue V1, SDValue V2, SelectionDAG & DAG) static
Definition at line 10907 of file X86ISelLowering.cpp.
References llvm::ShuffleVectorSDNode::commuteMask(), llvm::createUnpackShuffleMask(), llvm::SelectionDAG::getNode(), isShuffleEquivalent(), llvm::X86ISD::UNPCKH, and llvm::X86ISD::UNPCKL.
Referenced by lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV64I8Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), and lowerV8I64Shuffle().
lowerShuffleWithVPMOV()
static SDValue lowerShuffleWithVPMOV (const SDLoc & DL, ArrayRef< int > Mask, MVT VT, SDValue V1, SDValue V2, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 10971 of file X86ISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i16, llvm::MVT::is512BitVector(), llvm::ISD::isBuildVectorAllZeros(), matchShuffleAsVPMOV(), llvm::ArrayRef< T >::size(), std::swap(), llvm::ISD::TRUNCATE, llvm::MVT::v16i8, llvm::MVT::v8i16, and llvm::X86ISD::VTRUNC.
Referenced by lowerVECTOR_SHUFFLE().
LowerSIGN_EXTEND()
static SDValue LowerSIGN_EXTEND (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22551 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::MVT::getHalfNumVectorElementsVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasInt256(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::MVT::isVector(), LowerSIGN_EXTEND_Mask(), llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::MVT::v16i8, llvm::MVT::v8i64, and llvm::MVT::v8i8.
Referenced by llvm::MSP430TargetLowering::getScalarShiftAmountTy(), llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
LowerSIGN_EXTEND_Mask()
static SDValue LowerSIGN_EXTEND_Mask (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22366 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSelect(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i32, llvm::tgtok::In, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is512BitVector(), SplitAndExtendv16i1(), and llvm::ISD::TRUNCATE.
Referenced by LowerANY_EXTEND(), and LowerSIGN_EXTEND().
LowerStore()
static SDValue LowerStore (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 22680 of file X86ISelLowering.cpp.
References assert(), collectConcatOps(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getContext(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::SelectionDAG::getUNDEF(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasDQI(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is256BitVector(), llvm::X86Subtarget::is64Bit(), llvm::MVT::isInteger(), llvm::StoreSDNode::isTruncatingStore(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::MVT::Other, splitVectorStore(), llvm::ISD::TRUNCATE, llvm::TargetLoweringBase::TypeWidenVector, llvm::MVT::v16i1, and llvm::X86ISD::VEXTRACT_STORE.
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
lowerToAddSubOrFMAddSub()
static SDValue lowerToAddSubOrFMAddSub (const BuildVectorSDNode * BV, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to fold a build_vector that performs an 'addsub' or 'fmaddsub' or 'fsubadd' operation accordingly to X86ISD::ADDSUB or X86ISD::FMADDSUB or X86ISD::FMSUBADD node.
Definition at line 9173 of file X86ISelLowering.cpp.
References llvm::X86ISD::ADDSUB, llvm::X86ISD::FMADDSUB, llvm::X86ISD::FMSUBADD, llvm::SelectionDAG::getNode(), llvm::SDNode::getSimpleValueType(), llvm::MVT::is512BitVector(), isAddSubOrSubAdd(), and isFMAddSubOrFMSubAdd().
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerToHorizontalOp()
static SDValue LowerToHorizontalOp (const BuildVectorSDNode * BV, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower BUILD_VECTOR to a horizontal add/sub operation if possible.
Definition at line 9333 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::count_if(), llvm::numbers::e, ExpandHorizontalBinOp(), llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::X86ISD::FHSUB, llvm::ISD::FSUB, getHopForBuildVector(), llvm::SDNode::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::X86ISD::HADD, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSSE3(), llvm::X86ISD::HSUB, llvm::MVT::is256BitVector(), isHopBuildVector(), isHorizontalBinOpPart(), llvm::SDValue::isUndef(), llvm::SDNode::isUndef(), llvm::SDNode::op_values(), llvm::ISD::SUB, llvm::MVT::v16i16, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v8f32, llvm::MVT::v8i16, and llvm::MVT::v8i32.
Referenced by LowerBUILD_VECTORAsVariablePermute().
LowerToTLSExecModel()
static SDValue LowerToTLSExecModel (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT, TLSModel::Model model, bool is64Bit, bool isPIC) static
Definition at line 18279 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::N86::EAX, llvm::TLSModel::GeneralDynamic, llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getExtLoad(), llvm::MachineFunction::getFrameInfo(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachinePointerInfo::getGOT(), llvm::Type::getInt32PtrTy(), llvm::Type::getInt8PtrTy(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::Constant::getNullValue(), llvm::GlobalAddressSDNode::getOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::GlobalValue::getThreadLocalMode(), llvm::TargetMachine::getTLSModel(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86ISD::GlobalBaseReg, llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::i8, llvm::TLSModel::InitialExec, llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isOSWindows(), llvm::X86Subtarget::isPICStyleRIPRel(), llvm::TargetLowering::isPositionIndependent(), llvm::X86Subtarget::isTargetDarwin(), llvm::X86Subtarget::isTargetELF(), llvm::X86Subtarget::isTargetWindowsGNU(), llvm_unreachable, llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, llvm::GlobalValue::LocalExecTLSModel, llvm::Log2_64_Ceil(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), LowerToTLSLocalDynamicModel(), llvm::X86II::MO_GOTNTPOFF, llvm::X86II::MO_GOTTPOFF, llvm::X86II::MO_INDNTPOFF, llvm::X86II::MO_NTPOFF, llvm::X86II::MO_SECREL, llvm::X86II::MO_TLVP, llvm::X86II::MO_TLVP_PIC_BASE, llvm::X86II::MO_TPOFF, llvm::MVT::Other, Reg, llvm::MachineFrameInfo::setAdjustsStack(), llvm::ISD::SHL, llvm::MipsISD::ThreadPointer, llvm::X86ISD::TLSCALL, llvm::TargetMachine::useEmulatedTLS(), llvm::X86ISD::Wrapper, llvm::X86ISD::WrapperRIP, and llvm::ISD::ZEXTLOAD.
LowerToTLSGeneralDynamicModel32()
static SDValue LowerToTLSGeneralDynamicModel32 (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT) static
Definition at line 18219 of file X86ISelLowering.cpp.
References llvm::N86::EAX, llvm::N86::EBX, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getNode(), GetTLSADDR(), llvm::SDValue::getValue(), llvm::X86ISD::GlobalBaseReg, and llvm::X86II::MO_TLSGD.
Referenced by LowerToTLSExecModel().
LowerToTLSGeneralDynamicModel64()
static SDValue LowerToTLSGeneralDynamicModel64 (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT) static
Definition at line 18233 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::getEntryNode(), GetTLSADDR(), and llvm::X86II::MO_TLSGD.
Referenced by LowerToTLSExecModel().
LowerToTLSLocalDynamicModel()
static SDValue LowerToTLSLocalDynamicModel (GlobalAddressSDNode * GA, SelectionDAG & DAG, const EVT PtrVT, bool is64Bit) static
Definition at line 18239 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::N86::EAX, llvm::N86::EBX, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getTargetGlobalAddress(), GetTLSADDR(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::X86ISD::GlobalBaseReg, llvm::X86MachineFunctionInfo::incNumLocalDynamicTLSAccesses(), llvm::X86II::MO_DTPOFF, llvm::X86II::MO_TLSLD, llvm::X86II::MO_TLSLDM, and llvm::X86ISD::Wrapper.
Referenced by LowerToTLSExecModel().
LowerTruncateVecI1()
static SDValue LowerTruncateVecI1 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 19830 of file X86ISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMinLeadingZeros(), llvm::X86ISD::CVTTP2SI, llvm::X86ISD::CVTTP2UI, extract128BitVector(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::f128, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::RTLIB::getFPEXT(), llvm::RTLIB::getFPROUND(), llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasDQI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::tgtok::In, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::X86Subtarget::is64Bit(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::SDNode::isStrictFPOpcode(), llvm::MVT::isVector(), llvm_unreachable, llvm::MipsISD::Lo, llvm::TargetLowering::makeLibCall(), llvm::MVT::Other, llvm::X86ISD::PACKSS, llvm::X86ISD::PACKUS, llvm::ISD::SETGT, llvm::ISD::SETNE, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::SelectionDAG::SplitVector(), llvm::X86ISD::STRICT_CVTTP2SI, llvm::X86ISD::STRICT_CVTTP2UI, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::X86ISD::STRICT_VFPEXT, llvm::ISD::TRUNCATE, truncateVectorWithPACK(), llvm::X86Subtarget::useAVX512Regs(), llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i64, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, and llvm::X86ISD::VFPEXT.
LowerUINT_TO_FP_i32()
static SDValue LowerUINT_TO_FP_i32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
32-bit unsigned integer to float expansion.
Definition at line 19011 of file X86ISelLowering.cpp.
References llvm::BitsToDouble(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::ISD::FSUB, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getFPExtendOrRound(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), getShuffleVectorZeroOrUndef(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getStrictFPExtendOrRound(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::isStrictFPOpcode(), llvm::SPII::Load, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::STRICT_FSUB, llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lowerUINT_TO_FP_vec().
LowerUINT_TO_FP_i64()
static SDValue LowerUINT_TO_FP_i64 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
64-bit unsigned integer to double expansion.
Definition at line 18927 of file X86ISelLowering.cpp.
References llvm::lltok::APFloat, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f64, llvm::ISD::FADD, llvm::X86ISD::FHADD, llvm::ISD::FSUB, llvm::ConstantFP::get(), llvm::ConstantVector::get(), llvm::ConstantDataVector::get(), llvm::SelectionDAG::getBitcast(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetLoweringInfo(), getUnpackl(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasSSE3(), llvm::APFloatBase::IEEEdouble(), llvm::SDNode::isStrictFPOpcode(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SCALAR_TO_VECTOR, shouldUseHorizontalOp(), llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FSUB, llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lowerUINT_TO_FP_vec().
lowerUINT_TO_FP_v2i32()
static SDValue lowerUINT_TO_FP_v2i32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget, const SDLoc & DL) static
Definition at line 19061 of file X86ISelLowering.cpp.
References assert(), llvm::BitsToDouble(), llvm::ISD::CONCAT_VECTORS, llvm::X86ISD::CVTUI2P, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FSUB, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), llvm::SDNode::isStrictFPOpcode(), llvm::ISD::OR, llvm::MVT::Other, llvm::X86ISD::STRICT_CVTUI2P, llvm::ISD::STRICT_FSUB, llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4f64, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerUINT_TO_FP_vec().
lowerUINT_TO_FP_vec()
static SDValue lowerUINT_TO_FP_vec (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 19272 of file X86ISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, assert(), llvm::X86TargetLowering::BuildFILD(), llvm::APFloat::convert(), llvm::MachineFrameInfo::CreateStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::ISD::EXTLOAD, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FADD, llvm::X86ISD::FILD, llvm::X86ISD::FIST, llvm::X86ISD::FLD, llvm::ISD::FP_ROUND, llvm::X86ISD::FP_TO_INT_IN_MEM, llvm::ISD::FSUB, llvm::ConstantInt::get(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::X86TargetLowering::getSetCCResultType(), llvm::APInt::getSignMask(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::RTLIB::getUINTTOFP(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX512(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::X86Subtarget::is64Bit(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::SDNode::isStrictFPOpcode(), llvm::MVT::isVector(), LLVM_ATTRIBUTE_UNUSED, llvm_unreachable, LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::APFloatBase::opOK, llvm::MVT::Other, llvm::APFloatBase::rmNearestTiesToEven, llvm::ISD::SETLT, llvm::MVT::SimpleTy, llvm::ISD::SINT_TO_FP, llvm::SPII::Store, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FSUB, llvm::ISD::STRICT_SINT_TO_FP, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i32, vectorizeExtractedCast(), llvm::APFloatBase::x87DoubleExtended(), llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
lowerUINT_TO_FP_vXi32()
static SDValue lowerUINT_TO_FP_vXi32 (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 19114 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::lltok::APFloat, assert(), llvm::X86ISD::BLENDI, llvm::ISD::EXTRACT_SUBVECTOR, llvm::MVT::f64, llvm::ISD::FADD, llvm::ISD::FSUB, llvm::ConstantFP::get(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasVLX(), High, llvm::MVT::i8, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEsingle(), llvm::ISD::INSERT_SUBVECTOR, llvm::SDNode::isStrictFPOpcode(), llvm::MachineMemOperand::MOLoad, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SRL, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FSUB, llvm::ISD::STRICT_UINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::X86ISD::VBROADCAST_LOAD, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerUINT_TO_FP_vec().
lowerV16F32Shuffle()
static SDValue lowerV16F32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 32-bit floating point shuffles.
Definition at line 16663 of file X86ISelLowering.cpp.
References assert(), getConstVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), isShuffleEquivalent(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithSHUFPS(), lowerShuffleWithUNPCK(), llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::ArrayRef< T >::size(), llvm::MVT::v16f32, llvm::MVT::v16i32, llvm::X86ISD::VPERMILPI, and llvm::X86ISD::VPERMILPV.
Referenced by lower512BitShuffle().
lowerV16I16Shuffle()
static SDValue lowerV16I16Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 16-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v16i16 shuffling..
Definition at line 16246 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVLX(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK(), lowerV8I16GeneralSingleInputShuffle(), llvm::X86ISD::PSHUFB, llvm::ArrayRef< T >::size(), and llvm::MVT::v16i16.
Referenced by lower256BitShuffle().
lowerV16I32Shuffle()
static SDValue lowerV16I32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 16-lane 32-bit integer shuffles.
Definition at line 16779 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasBWI(), is128BitLaneRepeatedShuffleMask(), isSingleSHUFPSMask(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithSHUFPS(), lowerShuffleWithUNPCK(), llvm::X86ISD::PSHUFD, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::MVT::v16f32, and llvm::MVT::v16i32.
Referenced by lower512BitShuffle().
lowerV16I8Shuffle()
static SDValue lowerV16I8Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Generic lowering of v16i8 shuffles.
This is a hybrid strategy to lower v16i8 vectors. It first attempts to detect any complexity reducing interleaving. If that doesn't help, it uses UNPCK to spread the i8 elements across two i16-element vectors, and uses the existing lowering for v8i16 blends on each half, finally PACK-ing them back together.
Definition at line 14370 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::array_pod_sort(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), canLowerByDroppingEvenElements(), llvm::copy_if(), llvm::count_if(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVectorShuffle(), getZeroVector(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE4A(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVBMI(), llvm::X86Subtarget::hasVLX(), I, llvm::MVT::i8, llvm::SDValue::isUndef(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithSSE4A(), lowerShuffleWithUNPCK(), llvm::BitmaskEnumDetail::Mask(), llvm::none_of(), llvm::X86ISD::PACKUS, llvm::X86ISD::PSHUFB, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i8, and llvm::MVT::v8i16.
Referenced by lower128BitShuffle().
lowerV2F64Shuffle()
static SDValue lowerV2F64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 2-lane 64-bit floating point shuffles.
This is the basis function for the 2-lane 64-bit shuffles as we have full support for floating point shuffles but not integer shuffles. These instructions will incur a domain crossing penalty on some chips though so it is better to avoid lowering through this for integer vectors where possible.
Definition at line 13110 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), getScalarValueForVectorElement(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i8, isShuffleEquivalent(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsElementInsertion(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK(), llvm::X86ISD::MOVSD, llvm::ISD::SCALAR_TO_VECTOR, llvm::X86ISD::SHUFP, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::MVT::v2f64, and llvm::X86ISD::VPERMILPI.
Referenced by lower128BitShuffle().
lowerV2I64Shuffle()
static SDValue lowerV2I64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 2-lane 64-bit integer shuffles.
Tries to lower a 2-lane 64-bit shuffle using shuffle operations provided by the integer unit to minimize domain crossing penalties. However, for blends it falls back to the floating point shuffle operation with appropriate bit casting.
Definition at line 13194 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVLX(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK(), llvm::max(), llvm::X86ISD::PSHUFD, llvm::ArrayRef< T >::size(), llvm::MVT::v2f64, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lower128BitShuffle().
lowerV2X128Shuffle()
static SDValue lowerV2X128Shuffle (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, const APInt & Zeroable, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering 2-lane 128-bit shuffles.
Definition at line 15052 of file X86ISelLowering.cpp.
References assert(), canWidenShuffleElements(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::isBuildVectorAllZeros(), isShuffleEquivalent(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), llvm::peekThroughBitcasts(), llvm::X86ISD::SHUF128, and llvm::X86ISD::VPERM2X128.
Referenced by lowerV4F64Shuffle(), and lowerV4I64Shuffle().
lowerV32I16Shuffle()
static SDValue lowerV32I16Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 32-lane 16-bit integer shuffles.
Definition at line 16848 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasBWI(), is128BitLaneRepeatedShuffleMask(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK(), lowerV8I16GeneralSingleInputShuffle(), llvm::X86ISD::PSHUFB, llvm::ArrayRef< T >::size(), and llvm::MVT::v32i16.
Referenced by lower512BitShuffle().
lowerV32I8Shuffle()
static SDValue lowerV32I8Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 32-lane 8-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v32i8 shuffling..
Definition at line 16346 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasVBMI(), llvm::X86Subtarget::hasVLX(), is128BitLaneCrossingShuffleMask(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK(), llvm::X86ISD::PSHUFB, llvm::ArrayRef< T >::size(), and llvm::MVT::v32i8.
Referenced by lower256BitShuffle().
lowerV4F32Shuffle()
static SDValue lowerV4F32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower 4-lane 32-bit floating point shuffles.
Uses instructions exclusively from the floating point unit to minimize domain crossing penalties, as these are sufficient to implement all v4f32 shuffles.
Definition at line 13379 of file X86ISelLowering.cpp.
References assert(), llvm::count_if(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSE41(), isShuffleEquivalent(), isSingleSHUFPSMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBroadcast(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithSHUFPS(), lowerShuffleWithUNPCK(), llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::X86ISD::SHUFP, llvm::ArrayRef< T >::size(), llvm::MVT::v4f32, and llvm::X86ISD::VPERMILPI.
Referenced by lower128BitShuffle().
lowerV4F64Shuffle()
static SDValue lowerV4F64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 4-lane 64-bit floating point shuffles.
Also ends up handling lowering of 4-lane 64-bit integer shuffles when AVX2 isn't available.
Definition at line 15818 of file X86ISelLowering.cpp.
References llvm::all_of(), assert(), llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), isShuffleEquivalent(), isShuffleMaskInputInPlace(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSplitOrBlend(), lowerShuffleToEXPAND(), lowerShuffleWithSHUFPD(), lowerShuffleWithUNPCK(), lowerV2X128Shuffle(), llvm::X86ISD::MOVDDUP, llvm::ArrayRef< T >::size(), llvm::MVT::v4f64, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
Referenced by lower256BitShuffle().
lowerV4I32Shuffle()
static SDValue lowerV4I32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lower 4-lane i32 vector shuffles.
We try to handle these with integer-domain shuffles where we can, but for blends we use the floating point domain blend instructions.
Definition at line 13475 of file X86ISelLowering.cpp.
References assert(), llvm::count_if(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVLX(), isShuffleEquivalent(), isSingleSHUFPSMask(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK(), llvm::X86ISD::PSHUFD, llvm::ArrayRef< T >::size(), llvm::MVT::v4f32, and llvm::MVT::v4i32.
Referenced by lower128BitShuffle().
lowerV4I64Shuffle()
static SDValue lowerV4I64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 4-lane 64-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v4i64 shuffling..
Definition at line 15938 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasVLX(), is128BitLaneRepeatedShuffleMask(), isShuffleMaskInputInPlace(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleToEXPAND(), lowerShuffleWithUNPCK(), lowerV2X128Shuffle(), llvm::X86ISD::PSHUFD, llvm::ArrayRef< T >::size(), llvm::MVT::v4i64, llvm::MVT::v8i32, and llvm::X86ISD::VPERMI.
Referenced by lower256BitShuffle().
lowerV4X128Shuffle()
static SDValue lowerV4X128Shuffle (const SDLoc & DL, MVT VT, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a vector shuffle as a 128-bit shuffles.
Definition at line 16509 of file X86ISelLowering.cpp.
References assert(), canWidenShuffleElements(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::MVT::i8, insert128BitVector(), llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is512BitVector(), isShuffleEquivalent(), isUndef(), llvm::X86ISD::SHUF128, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerV8F64Shuffle(), and lowerV8I64Shuffle().
lowerV64I8Shuffle()
static SDValue lowerV64I8Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 64-lane 8-bit integer shuffles.
Definition at line 16901 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVBMI(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK(), llvm::X86ISD::PSHUFB, llvm::ArrayRef< T >::size(), splitAndLowerShuffle(), and llvm::MVT::v64i8.
Referenced by lower512BitShuffle().
lowerV8F32Shuffle()
static SDValue lowerV8F32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 32-bit floating point shuffles.
Also ends up handling lowering of 8-lane 32-bit integer shuffles when AVX2 isn't available.
Definition at line 16036 of file X86ISelLowering.cpp.
References assert(), getConstVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), isShuffleEquivalent(), llvm::SDValue::isUndef(), isUnpackWdShuffleMask(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSplitOrBlend(), lowerShuffleToEXPAND(), lowerShuffleWithSHUFPS(), lowerShuffleWithUNPCK(), llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::MVT::v8f32, llvm::MVT::v8i32, llvm::X86ISD::VPERMILPI, llvm::X86ISD::VPERMILPV, and llvm::X86ISD::VPERMV.
Referenced by lower256BitShuffle().
lowerV8F64Shuffle()
static SDValue lowerV8F64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 64-bit floating point shuffles.
Definition at line 16609 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getTargetConstant(), getV4X86ShuffleImm8ForMask(), llvm::MVT::i8, is128BitLaneCrossingShuffleMask(), is256BitLaneRepeatedShuffleMask(), isShuffleEquivalent(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithSHUFPD(), lowerShuffleWithUNPCK(), lowerV4X128Shuffle(), llvm::X86ISD::MOVDDUP, llvm::ArrayRef< T >::size(), llvm::MVT::v8f64, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
Referenced by lower512BitShuffle().
lowerV8I16GeneralSingleInputShuffle()
static SDValue lowerV8I16GeneralSingleInputShuffle (const SDLoc & DL, MVT VT, SDValue V, MutableArrayRef< int > Mask, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Lowering of single-input v8i16 shuffles is the cornerstone of SSE2 shuffle lowering, and the most complex part.
The lowering strategy is to try to form pairs of input lanes which are targeted at the same half of the final vector, and then use a dword shuffle to place them onto the right half, and finally unpack the paired lanes into their final position.
The exact breakdown of how to form these dword pairs and align them on the correct sides is really tricky. See the comments within the function for more of the details.
This code also handles repeated 128-bit lanes of v8i16 shuffles, but each lane must shuffle the exact same way. In fact, you must pass a v8 Mask to this routine for it to work correctly. To shuffle a 256-bit or 512-bit i16 vector, form the analogous 128-bit 8-element Mask.
Definition at line 13603 of file X86ISelLowering.cpp.
References llvm::array_pod_sort(), assert(), llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::begin(), llvm::MutableArrayRef< T >::begin(), llvm::copy_if(), llvm::count(), llvm::count_if(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::numbers::e, llvm::ArrayRef< T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ArrayRef< T >::end(), llvm::MutableArrayRef< T >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::find(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), getV4X86ShuffleImm8ForMask(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i16, llvm::MVT::i32, llvm::is_contained(), isNoopShuffleMask(), isSequentialOrUndefInRange(), isUndefOrEqual(), isUndefOrInRange(), llvm_unreachable, llvm::lower_bound(), llvm::BitmaskEnumDetail::Mask(), llvm::Match, llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::SmallVectorTemplateBase< T >::push_back(), replace(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::MutableArrayRef< T >::slice(), and std::swap().
Referenced by lowerV16I16Shuffle(), lowerV32I16Shuffle(), and lowerV8I16Shuffle().
lowerV8I16Shuffle()
static SDValue lowerV8I16Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Generic lowering of 8-lane i16 shuffles.
This handles both single-input shuffles and combined shuffle/blends with two inputs. The single input shuffles are immediately delegated to a dedicated lowering routine.
The blends are lowered in one of three fundamental ways. If there are few enough inputs, it delegates to a basic UNPCK-based strategy. If the shuffle of the input is significantly cheaper when lowered as an interleaving of the two inputs, try to interleave them. Otherwise, blend the low and high halves of the inputs separately (making them have relatively few inputs) and then concatenate them.
Definition at line 14162 of file X86ISelLowering.cpp.
References llvm::any_of(), assert(), llvm::ArrayRef< T >::begin(), llvm::count_if(), llvm::ArrayRef< T >::end(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSE4A(), llvm::X86Subtarget::hasSSSE3(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsElementInsertion(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithSSE4A(), lowerShuffleWithUNPCK(), lowerV8I16GeneralSingleInputShuffle(), llvm::ArrayRef< T >::size(), and llvm::MVT::v8i16.
Referenced by lower128BitShuffle().
lowerV8I32Shuffle()
static SDValue lowerV8I32Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 32-bit integer shuffles.
This routine is only called when we have AVX2 and thus a reasonable instruction set for v8i32 shuffling..
Definition at line 16135 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), getConstVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasVLX(), is128BitLaneRepeatedShuffleMask(), isSingleSHUFPSMask(), llvm::SDValue::isUndef(), isUnpackWdShuffleMask(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsDecomposedShuffleBlend(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleToEXPAND(), lowerShuffleWithSHUFPS(), lowerShuffleWithUNPCK(), llvm::X86ISD::PSHUFD, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::MVT::v8f32, llvm::MVT::v8i32, and llvm::X86ISD::VPERMV.
Referenced by lower256BitShuffle().
lowerV8I64Shuffle()
static SDValue lowerV8I64Shuffle (const SDLoc & DL, ArrayRef< int > Mask, const APInt & Zeroable, SDValue V1, SDValue V2, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Handle lowering of 8-lane 64-bit integer shuffles.
Definition at line 16716 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), getV4X86ShuffleImm8ForMask(), is128BitLaneRepeatedShuffleMask(), is256BitLaneRepeatedShuffleMask(), llvm::SDValue::isUndef(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsRotate(), lowerShuffleAsShift(), lowerShuffleToEXPAND(), lowerShuffleWithPERMV(), lowerShuffleWithUNPCK(), lowerV4X128Shuffle(), llvm::X86ISD::PSHUFD, llvm::ArrayRef< T >::size(), llvm::MVT::v16i32, llvm::MVT::v8i64, and llvm::X86ISD::VPERMI.
Referenced by lower512BitShuffle().
LowerVACOPY()
static SDValue LowerVACOPY (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 23241 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::expandVACopy(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemcpy(), llvm::SDValue::getNode(), llvm::SDValue::getOperand(), llvm::X86Subtarget::is64Bit(), and llvm::X86Subtarget::isCallingConvWin64().
Referenced by llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::X86TargetLowering::LowerOperation(), and llvm::AArch64TargetLowering::supportSwiftError().
lowerVECTOR_SHUFFLE()
static SDValue lowerVECTOR_SHUFFLE (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Top-level lowering for x86 vector shuffles.
This handles decomposition, canonicalization, and lowering of all x86 vector shuffles. Most of the specific lowering strategies are encapsulated above in helper routines. The canonicalization attempts to widen shuffles to involve fewer lanes of wider elements, consolidate symmetric patterns s.t. only one of the two inputs needs to be tested, etc.
Definition at line 17301 of file X86ISelLowering.cpp.
References llvm::all_of(), llvm::any_of(), assert(), canonicalizeShuffleMaskWithCommute(), canWidenShuffleElements(), llvm::ShuffleVectorSDNode::commuteMask(), computeZeroableShuffleElements(), llvm::find(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getCommutedVectorShuffle(), llvm::MVT::getFloatingPointVT(), llvm::MVT::getIntegerVT(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDValue::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::MVT::i1, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::APInt::isAllOnesValue(), llvm::ISD::isBuildVectorAllZeros(), llvm::MVT::isFloatingPoint(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SDValue::isUndef(), llvm_unreachable, lower128BitShuffle(), lower1BitShuffle(), lower256BitShuffle(), lower512BitShuffle(), lowerShuffleAsBroadcast(), lowerShuffleWithVPMOV(), llvm::BitmaskEnumDetail::Mask(), llvm::SM_SentinelZero, and std::swap().
Referenced by llvm::X86TargetLowering::LowerOperation(), and llvm::SystemZTargetLowering::supportSwiftError().
LowerVectorAllZeroTest()
static SDValue LowerVectorAllZeroTest (SDValue Op, ISD::CondCode CC, const X86Subtarget & Subtarget, SelectionDAG & DAG, SDValue & X86CC) static
Definition at line 20637 of file X86ISelLowering.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::X86::COND_E, llvm::X86::COND_NE, llvm::numbers::e, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SelectionDAG::getTargetConstant(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i32, llvm::MVT::i8, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), matchScalarReduction(), llvm::ISD::OR, llvm::X86ISD::PTEST, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SETEQ, llvm::SmallVectorBase::size(), llvm::MVT::v2i64, and llvm::MVT::v4i64.
Referenced by EmitAVX512Test().
LowerVectorCTLZ()
static SDValue LowerVectorCTLZ (SDValue Op, const SDLoc & DL, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25600 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasCDI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i8, llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), Lower256IntUnary(), Lower512IntUnary(), LowerVectorCTLZ_AVX512CDI(), and LowerVectorCTLZInRegLUT().
Referenced by LowerCTLZ().
LowerVectorCTLZ_AVX512CDI()
static SDValue LowerVectorCTLZ_AVX512CDI (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Lower a vector CTLZ using native supported vector CTLZ instruction.
Definition at line 25488 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::ISD::CTLZ, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), LowerVectorIntUnary(), llvm::ISD::SUB, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerVectorCTLZ().
LowerVectorCTLZInRegLUT()
static SDValue LowerVectorCTLZInRegLUT (SDValue Op, const SDLoc & DL, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 25518 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSetCC(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MipsISD::Hi, llvm::MVT::i1, llvm::MVT::i8, llvm::MipsISD::Lo, llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SETEQ, llvm::ISD::SIGN_EXTEND, and llvm::ISD::SRL.
Referenced by LowerVectorCTLZ().
LowerVectorCTPOP()
static SDValue LowerVectorCTPOP (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27808 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::ISD::CTPOP, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSSE3(), llvm::X86Subtarget::hasVPOPCNTDQ(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), Lower256IntUnary(), Lower512IntUnary(), LowerHorizontalByteSum(), LowerVectorCTPOPInRegLUT(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerCTPOP().
LowerVectorCTPOPInRegLUT()
static SDValue LowerVectorCTPOPInRegLUT (SDValue Op, const SDLoc & DL, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 27761 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::i8, llvm::X86ISD::PSHUFB, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::SRL.
Referenced by LowerVectorCTPOP().
LowerVectorIntUnary()
static SDValue LowerVectorIntUnary (SDValue Op, SelectionDAG & DAG) static
Definition at line 25446 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extractSubVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MipsISD::Hi, and llvm::MipsISD::Lo.
Referenced by Lower256IntUnary(), Lower512IntUnary(), and LowerVectorCTLZ_AVX512CDI().
lowerVSELECTtoVectorShuffle()
static SDValue lowerVSELECTtoVectorShuffle (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Try to lower a VSELECT instruction to a vector shuffle.
Definition at line 17430 of file X86ISelLowering.cpp.
LowerVSETCC()
static SDValue LowerVSETCC (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 21351 of file X86ISelLowering.cpp.
References llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getSimpleValueType(), llvm::ISD::STRICT_FSETCC, and llvm::ISD::STRICT_FSETCCS.
Referenced by combineSetCC(), and EmitAVX512Test().
LowerVSETCCWithSUBUS()
static SDValue LowerVSETCCWithSUBUS (SDValue Op0, SDValue Op1, MVT VT, ISD::CondCode Cond, const SDLoc & dl, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
As another special case, use PSUBUS[BW] when it's profitable.
E.g. for Op0 u<= Op1: t = psubus Op0, Op1 pcmpeq t, <0..0>
Definition at line 21298 of file X86ISelLowering.cpp.
lowerX86CmpEqZeroToCtlzSrl()
static SDValue lowerX86CmpEqZeroToCtlzSrl (SDValue Op, EVT ExtTy, SelectionDAG & DAG) static
Definition at line 40521 of file X86ISelLowering.cpp.
References llvm::ISD::CTLZ, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i32, llvm::MVT::i8, llvm::Log2_32(), and llvm::ISD::SRL.
Referenced by combineOrCmpEqZeroToCtlzSrl().
lowerX86FPLogicOp()
static SDValue lowerX86FPLogicOp (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 42709 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, llvm::X86ISD::FAND, llvm::X86ISD::FANDN, llvm::X86ISD::FOR, llvm::X86ISD::FXOR, llvm::SelectionDAG::getBitcast(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::isVector(), llvm_unreachable, llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by combineFAnd(), combineFAndn(), and combineFOr().
LowerXALUO()
static SDValue LowerXALUO (SDValue Op, SelectionDAG & DAG) static
Definition at line 22008 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::LowerOperation().
LowerZERO_EXTEND()
static SDValue LowerZERO_EXTEND (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 19708 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::X86Subtarget::hasAVX(), llvm::MVT::i1, llvm::tgtok::In, LowerAVXExtend(), and LowerZERO_EXTEND_Mask().
Referenced by llvm::HexagonTargetLowering::isCtlzFast(), and llvm::X86TargetLowering::LowerOperation().
LowerZERO_EXTEND_Mask()
static SDValue LowerZERO_EXTEND_Mask (SDValue Op, const X86Subtarget & Subtarget, SelectionDAG & DAG) static
Definition at line 19650 of file X86ISelLowering.cpp.
References assert(), llvm::X86Subtarget::canExtendTo512DQ(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasVLX(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i8, llvm::tgtok::In, llvm::ISD::INSERT_SUBVECTOR, llvm::MVT::is512BitVector(), llvm::ISD::SIGN_EXTEND, SplitAndExtendv16i1(), llvm::ISD::SRL, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by LowerZERO_EXTEND().
MarkEHGuard()
static SDValue MarkEHGuard (SDValue Op, SelectionDAG & DAG) static
Definition at line 24755 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::WinEHFuncInfo::EHGuardFrameIndex, llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::MachineFunction::getWinEHFuncInfo(), and llvm::report_fatal_error().
Referenced by LowerINTRINSIC_W_CHAIN().
MarkEHRegistrationNode()
static SDValue MarkEHRegistrationNode (SDValue Op, SelectionDAG & DAG) static
Definition at line 24737 of file X86ISelLowering.cpp.
References llvm::dyn_cast(), llvm::WinEHFuncInfo::EHRegNodeFrameIndex, llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::MachineFunction::getWinEHFuncInfo(), and llvm::report_fatal_error().
Referenced by LowerINTRINSIC_W_CHAIN().
match1BitShuffleAsKSHIFT()
static int match1BitShuffleAsKSHIFT (unsigned & Opcode, ArrayRef< int > Mask, int MaskOffset, const APInt & Zeroable) static
Definition at line 17067 of file X86ISelLowering.cpp.
References isSequentialOrUndefInRange(), llvm::X86ISD::KSHIFTL, llvm::X86ISD::KSHIFTR, llvm::Left, Size, and llvm::ArrayRef< T >::size().
Referenced by lower1BitShuffle().
matchAsm()
static bool matchAsm (StringRef S, ArrayRef< const char *> Pieces) static
Definition at line 46269 of file X86ISelLowering.cpp.
References llvm::StringRef::empty(), llvm::StringRef::find_first_not_of(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::X86TargetLowering::ExpandInlineAsm().
matchBinaryPermuteShuffle()
static bool matchBinaryPermuteShuffle (MVT MaskVT, ArrayRef< int > Mask, const APInt & Zeroable, bool AllowFloatDomain, bool AllowIntDomain, SDValue & V1, SDValue & V2, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget, unsigned & Shuffle, MVT & ShuffleVT, unsigned & PermuteImm) static
Definition at line 33188 of file X86ISelLowering.cpp.
References llvm::any_of(), assert(), llvm::ArrayRef< T >::begin(), llvm::X86ISD::BLENDI, combineX86ShuffleChainWithExtract(), llvm::ArrayRef< T >::end(), llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), getV4X86ShuffleImm(), llvm::MVT::getVectorVT(), getZeroVector(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::X86Subtarget::hasSSSE3(), llvm::MipsISD::Hi, llvm::MVT::i8, llvm::X86ISD::INSERTPS, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), isRepeatedTargetShuffleMask(), isUndefInRange(), isUndefOrInRange(), isUndefOrZeroInRange(), llvm::MipsISD::Lo, matchShuffleAsBlend(), matchShuffleAsByteRotate(), matchShuffleAsInsertPS(), matchShuffleWithSHUFPD(), llvm::X86ISD::PALIGNR, llvm::X86ISD::SHUFP, llvm::SmallVectorBase::size(), llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::MVT::v16i16, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::MVT::v4f32.
Referenced by combineX86ShuffleChain().
matchBinaryShuffle()
static bool matchBinaryShuffle (MVT MaskVT, ArrayRef< int > Mask, bool AllowFloatDomain, bool AllowIntDomain, SDValue & V1, SDValue & V2, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget, unsigned & Shuffle, MVT & SrcVT, MVT & DstVT, bool IsUnary) static
Definition at line 33122 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), isTargetShuffleEquivalent(), matchShuffleWithPACK(), matchShuffleWithUNPCK(), llvm::X86ISD::MOVHLPS, llvm::X86ISD::MOVLHPS, llvm::X86ISD::MOVSD, llvm::X86ISD::MOVSS, llvm::SM_SentinelUndef, std::swap(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v64i8, llvm::MVT::v8f32, and llvm::MVT::v8i16.
Referenced by combineX86ShuffleChain().
MatchingStackOffset()
static bool MatchingStackOffset (SDValue Arg, unsigned Offset, ISD::ArgFlagsTy Flags, MachineFrameInfo & MFI, const MachineRegisterInfo * MRI, const X86InstrInfo * TII, const CCValAssign & VA) static
Return true if the given stack call argument is already available in the same position (relatively) of the caller's incoming argument stack.
Definition at line 4372 of file X86ISelLowering.cpp.
References llvm::CCState::AllocateStack(), llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::ISD::AssertZext, llvm::ISD::BITCAST, C, Callee, canGuaranteeTCO(), llvm::CC_X86(), llvm::ISD::CopyFromReg, llvm::tgtok::Def, llvm::dyn_cast(), llvm::numbers::e, llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDX, llvm::SmallVectorBase::empty(), llvm::ISD::FrameIndex, llvm::X86MachineFunctionInfo::getBytesToPopOnReturn(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::Function::getCallingConv(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getIndex(), llvm::FrameIndexSDNode::getIndex(), llvm::MachineFunction::getInfo(), llvm::X86Subtarget::getInstrInfo(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::SDValue::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::SDValue::getOperand(), llvm::MachineInstr::getOperand(), getReg(), llvm::MachineFunction::getRegInfo(), llvm::X86Subtarget::getRegisterInfo(), llvm::Function::getReturnType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTarget(), llvm::MachineFunction::getTarget(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::CCValAssign::Indirect, llvm::X86Subtarget::is64Bit(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::X86::isCalleePop(), llvm::X86Subtarget::isCallingConvWin64(), llvm::MachineOperand::isFI(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::MachineFrameInfo::isImmutableObjectIndex(), llvm::X86InstrInfo::isLoadFromStackSlot(), llvm::MachineFrameInfo::isObjectSExt(), llvm::MachineFrameInfo::isObjectZExt(), llvm::TargetLowering::isPositionIndependent(), llvm::CCValAssign::isRegLoc(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::Register::isVirtualRegister(), llvm::Type::isX86_FP80Ty(), llvm::ISD::ArgFlagsTy::isZExt(), mayTailCallThisCC(), MRI, llvm::TargetMachine::Options, llvm::TargetLowering::parametersInCSRMatch(), Reg, llvm::CCState::resultsCompatible(), llvm::RetCC_X86(), llvm::SmallVectorBase::size(), llvm::CallingConv::Tail, TII, TRI, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
matchLogicBlend()
static bool matchLogicBlend (SDNode * N, SDValue & X, SDValue & Y, SDValue & Mask) static
Definition at line 40431 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::X86ISD::ANDNP, llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::OR, and std::swap().
Referenced by combineLogicBlendIntoPBLENDV().
matchPMADDWD()
static SDValue matchPMADDWD (SelectionDAG & DAG, SDValue Op0, SDValue Op1, const SDLoc & DL, EVT VT, const X86Subtarget & Subtarget) static
Definition at line 44908 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, canReduceVMulWidth(), llvm::dyn_cast(), llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::isPowerOf2_32(), llvm::EVT::isVector(), Mode, llvm::ISD::MUL, MULU16, SplitOpsAndApply(), std::swap(), llvm::ISD::TRUNCATE, and llvm::X86ISD::VPMADDWD.
Referenced by combineAdd().
matchPMADDWD_2()
static SDValue matchPMADDWD_2 (SelectionDAG & DAG, SDValue N0, SDValue N1, const SDLoc & DL, EVT VT, const X86Subtarget & Subtarget) static
Definition at line 45021 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, llvm::dyn_cast(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::isPowerOf2_32(), llvm::EVT::isVector(), llvm::ISD::MUL, llvm::ISD::SIGN_EXTEND, SplitOpsAndApply(), std::swap(), and llvm::X86ISD::VPMADDWD.
Referenced by combineAdd().
matchScalarReduction()
static bool matchScalarReduction (SDValue Op, ISD::NodeType BinOp, SmallVectorImpl< SDValue > & SrcOps) static
Helper for matching OR(EXTRACTELT(X,0),OR(EXTRACTELT(X,1),...)) style scalarized (associative) reduction patterns.
Definition at line 20572 of file X86ISelLowering.cpp.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::numbers::e, E, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::APInt::getNullValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::SmallVectorBase::size().
Referenced by combineAnd(), combineOr(), and LowerVectorAllZeroTest().
matchShuffleAsBlend()
static bool matchShuffleAsBlend (SDValue V1, SDValue V2, MutableArrayRef< int > Mask, const APInt & Zeroable, bool & ForceV1Zero, bool & ForceV2Zero, uint64_t & BlendMask) static
Definition at line 11175 of file X86ISelLowering.cpp.
References assert(), llvm::SDValue::getNode(), llvm::ISD::isBuildVectorAllZeros(), llvm::SDValue::isUndef(), Size, llvm::ArrayRef< T >::size(), and llvm::SM_SentinelUndef.
Referenced by lowerShuffleAsBlend(), and matchBinaryPermuteShuffle().
matchShuffleAsByteRotate()
static int matchShuffleAsByteRotate (MVT VT, SDValue & V1, SDValue & V2, ArrayRef< int > Mask) static
Try to lower a vector shuffle as a byte rotation.
SSSE3 has a generic PALIGNR instruction in x86 that will do an arbitrary byte-rotation of the concatenation of two vectors; pre-SSSE3 can use a PSRLDQ/PSLLDQ/POR pattern to get a similar effect. This routine will try to generically lower a vector shuffle through such an pattern. It does not check for the profitability of lowering either as PALIGNR or PSRLDQ/PSLLDQ/POR, only whether the mask is valid to lower in that form. This matches shuffle vectors that look like:
v8i16 [11, 12, 13, 14, 15, 0, 1, 2]
Essentially it concatenates V1 and V2, shifts right by some number of elements, and takes the low elements as the result. Note that while this is specified as a right shift because x86 is little-endian, it is a left rotate of the vector lanes.
Definition at line 11712 of file X86ISelLowering.cpp.
References llvm::any_of(), is128BitLaneRepeatedShuffleMask(), matchShuffleAsRotate(), llvm::SmallVectorBase::size(), and llvm::SM_SentinelZero.
Referenced by lowerShuffleAsByteRotate(), and matchBinaryPermuteShuffle().
matchShuffleAsEXTRQ()
static bool matchShuffleAsEXTRQ (MVT VT, SDValue & V1, SDValue & V2, ArrayRef< int > Mask, uint64_t & BitLen, uint64_t & BitIdx, const APInt & Zeroable) static
Definition at line 11997 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::APInt::isAllOnesValue(), isUndefUpperHalf(), Size, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by combineX86ShuffleChain(), and lowerShuffleWithSSE4A().
matchShuffleAsInsertPS()
static bool matchShuffleAsInsertPS (SDValue & V1, SDValue & V2, unsigned & InsertPSMask, const APInt & Zeroable, ArrayRef< int > Mask, SelectionDAG & DAG) static
Definition at line 12882 of file X86ISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::ArrayRef< T >::end(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::is128BitVector(), llvm::ArrayRef< T >::size(), llvm::MVT::v4f32, and llvm::codeview::VB.
Referenced by lowerShuffleAsInsertPS(), and matchBinaryPermuteShuffle().
matchShuffleAsINSERTQ()
static bool matchShuffleAsINSERTQ (MVT VT, SDValue & V1, SDValue & V2, ArrayRef< int > Mask, uint64_t & BitLen, uint64_t & BitIdx) static
Definition at line 12053 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MipsISD::Hi, isSequentialOrUndefInRange(), isUndefInRange(), isUndefUpperHalf(), Size, llvm::ArrayRef< T >::size(), and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by combineX86ShuffleChain(), and lowerShuffleWithSSE4A().
matchShuffleAsRotate()
static int matchShuffleAsRotate (SDValue & V1, SDValue & V2, ArrayRef< int > Mask) static
Try to lower a vector shuffle as a rotation.
This is used for support PALIGNR for SSSE3 or VALIGND/Q for AVX512.
Definition at line 11628 of file X86ISelLowering.cpp.
References assert(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by lowerShuffleAsRotate(), and matchShuffleAsByteRotate().
matchShuffleAsShift()
static int matchShuffleAsShift (MVT & ShiftVT, unsigned & Opcode, unsigned ScalarSizeInBits, ArrayRef< int > Mask, int MaskOffset, const APInt & Zeroable, const X86Subtarget & Subtarget) static
Try to lower a vector shuffle as a bit shift (shifts in zeros).
Attempts to match a shuffle mask against the PSLL(W/D/Q/DQ) and PSRL(W/D/Q/DQ) SSE2 and AVX2 logical bit-shift instructions. The function matches elements from one of the input vectors shuffled to the left or right with zeroable elements 'shifted in'. It handles both the strictly bit-wise element shifts and the byte shift across an entire 128-bit double quad word lane.
PSHL : (little-endian) left bit shift. [ zz, 0, zz, 2 ] [ -1, 4, zz, -1 ] PSRL : (little-endian) right bit shift. [ 1, zz, 3, zz] [ -1, -1, 7, zz] PSLLDQ : (little-endian) left byte shift [ zz, 0, 1, 2, 3, 4, 5, 6] [ zz, zz, -1, -1, 2, 3, 4, -1] [ zz, zz, zz, zz, zz, zz, -1, 1] PSRLDQ : (little-endian) right byte shift [ 5, 6, 7, zz, zz, zz, zz, zz] [ -1, 5, 6, 7, zz, zz, zz, zz] [ 1, 2, -1, -1, -1, -1, zz, zz]
Definition at line 11899 of file X86ISelLowering.cpp.
References llvm::MVT::getIntegerVT(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasBWI(), llvm::MVT::i8, isSequentialOrUndefInRange(), llvm::Left, Size, llvm::ArrayRef< T >::size(), llvm::X86ISD::VSHLDQ, llvm::X86ISD::VSHLI, llvm::X86ISD::VSRLDQ, and llvm::X86ISD::VSRLI.
Referenced by lowerShuffleAsShift(), and matchUnaryPermuteShuffle().
matchShuffleAsVPMOV()
static bool matchShuffleAsVPMOV (ArrayRef< int > Mask, bool SwappedOps, int Delta) static
Definition at line 10932 of file X86ISelLowering.cpp.
References isAnyInRange(), isSequentialOrUndefInRange(), Size, llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by lowerShuffleWithVPMOV().
matchShuffleWithPACK()
static bool matchShuffleWithPACK (MVT VT, MVT & SrcVT, SDValue & V1, SDValue & V2, unsigned & PackOpcode, ArrayRef< int > TargetMask, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 11027 of file X86ISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), createPackShuffleMask(), llvm::SelectionDAG::getBitcast(), llvm::APInt::getHighBitsSet(), llvm::MVT::getIntegerVT(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, isTargetShuffleEquivalent(), llvm::SDValue::isUndef(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::X86ISD::PACKSS, and llvm::X86ISD::PACKUS.
Referenced by lowerShuffleWithPACK(), and matchBinaryShuffle().
matchShuffleWithSHUFPD()
static bool matchShuffleWithSHUFPD (MVT VT, SDValue & V1, SDValue & V2, bool & ForceV1Zero, bool & ForceV2Zero, unsigned & ShuffleImm, ArrayRef< int > Mask, const APInt & Zeroable) static
Definition at line 15709 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorNumElements(), isUndefOrZeroOrInRange(), llvm::SM_SentinelUndef, and std::swap().
Referenced by lowerShuffleWithSHUFPD(), and matchBinaryPermuteShuffle().
matchShuffleWithUNPCK()
static bool matchShuffleWithUNPCK (MVT VT, SDValue & V1, SDValue & V2, unsigned & UnpackOpcode, bool IsUnary, ArrayRef< int > TargetMask, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 10820 of file X86ISelLowering.cpp.
References assert(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::createUnpackShuffleMask(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), getZeroVector(), llvm::X86Subtarget::hasSSE41(), isSequentialOrUndefOrZeroInRange(), isTargetShuffleEquivalent(), isUndefOrZero(), llvm::SM_SentinelUndef, std::swap(), llvm::X86ISD::UNPCKH, llvm::X86ISD::UNPCKL, llvm::NVPTX::PTXLdStInstCode::V2, llvm::MVT::v2f64, and llvm::MVT::v2i64.
Referenced by matchBinaryShuffle().
matchUnaryPermuteShuffle()
static bool matchUnaryPermuteShuffle (MVT MaskVT, ArrayRef< int > Mask, const APInt & Zeroable, bool AllowFloatDomain, bool AllowIntDomain, const X86Subtarget & Subtarget, unsigned & Shuffle, MVT & ShuffleVT, unsigned & PermuteImm) static
Definition at line 33002 of file X86ISelLowering.cpp.
References llvm::any_of(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::numbers::e, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::getIntegerVT(), llvm::MVT::getSizeInBits(), getV4X86ShuffleImm(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), llvm::MVT::is128BitVector(), is256BitLaneRepeatedShuffleMask(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), isSequentialOrUndefInRange(), isUndefOrInRange(), matchShuffleAsShift(), llvm::X86ISD::PSHUFD, llvm::X86ISD::PSHUFHW, llvm::X86ISD::PSHUFLW, llvm::ArrayRef< T >::size(), llvm::SM_SentinelUndef, llvm::SM_SentinelZero, llvm::MVT::v4f64, llvm::MVT::v4i64, llvm::MVT::v8f64, llvm::MVT::v8i64, llvm::X86ISD::VPERMI, and llvm::X86ISD::VPERMILPI.
Referenced by combineX86ShuffleChain().
matchUnaryShuffle()
static bool matchUnaryShuffle (MVT MaskVT, ArrayRef< int > Mask, bool AllowFloatDomain, bool AllowIntDomain, SDValue & V1, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget, unsigned & Shuffle, MVT & SrcVT, MVT & DstVT) static
Definition at line 32871 of file X86ISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), extractSubVector(), llvm::MVT::getIntegerVT(), getOpcode_EXTEND_VECTOR_INREG(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE3(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::MVT::isInteger(), isTargetShuffleEquivalent(), isUndefInRange(), isUndefOrEqual(), isUndefOrZero(), isUndefOrZeroInRange(), llvm::max(), llvm::ScaledNumbers::MaxScale, llvm::X86ISD::MOVDDUP, llvm::X86ISD::MOVSHDUP, llvm::X86ISD::MOVSLDUP, llvm::ArrayRef< T >::size(), llvm::MVT::v16f32, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::X86ISD::VZEXT_MOVL, and llvm::ISD::ZERO_EXTEND.
Referenced by combineX86ShuffleChain().
materializeVectorConstant()
static SDValue materializeVectorConstant (SDValue Op, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Create a vector constant without a load.
SSE/AVX provide the bare minimum functionality to do this, so it's all zeros, all ones, or some derivation that is cheap to calculate.
Definition at line 9524 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), getOnesVector(), llvm::SDValue::getSimpleValueType(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::MVT::v16i32, llvm::MVT::v4i32, and llvm::MVT::v8i32.
Referenced by LowerBUILD_VECTORAsVariablePermute().
MayFoldIntoStore()
static bool MayFoldIntoStore (SDValue Op) static
Definition at line 4672 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::hasOneUse(), llvm::ISD::isNormalStore(), and llvm::SDNode::use_begin().
Referenced by ExtractBitFromMaskVector().
MayFoldIntoZeroExtend()
static bool MayFoldIntoZeroExtend (SDValue Op) static
Definition at line 4676 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::hasOneUse(), llvm::SDNode::use_begin(), and llvm::ISD::ZERO_EXTEND.
Referenced by ExtractBitFromMaskVector().
MayFoldLoad()
static bool MayFoldLoad (SDValue Op) static
Definition at line 4668 of file X86ISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SDValue::hasOneUse(), and llvm::ISD::isNormalLoad().
Referenced by combineConcatVectorOps(), combineX86ShuffleChain(), InsertBitToMaskVector(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), and lowerShuffleAsBroadcast().
mayTailCallThisCC()
static bool mayTailCallThisCC (CallingConv::ID CC) static
Return true if we might ever do TCO for calls with this calling convention.
Definition at line 3150 of file X86ISelLowering.cpp.
References llvm::CallingConv::C, canGuaranteeTCO(), llvm::CallingConv::Swift, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by MatchingStackOffset(), and shouldGuaranteeTCO().
narrowExtractedVectorSelect()
static SDValue narrowExtractedVectorSelect (SDNode * Ext, SelectionDAG & DAG) static
If we are extracting a subvector of a vector select and the select condition is composed of concatenated vectors, try to narrow the select width.
This is a common pattern for AVX1 integer code because 256-bit selects may be legal, but there is almost no integer math/logic available for 256-bit. This function should only be called with legal types (otherwise, the calls to get simple value types will assert).
Definition at line 45606 of file X86ISelLowering.cpp.
References assert(), collectConcatOps(), extract128BitVector(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm_unreachable, llvm::peekThroughBitcasts(), and llvm::ISD::VSELECT.
Referenced by combineExtractSubvector().
narrowShuffle()
static SDValue narrowShuffle (ShuffleVectorSDNode * Shuf, SelectionDAG & DAG) static
If we have a shuffle of AVX/AVX512 (256/512 bit) vectors that only uses the low half of each source vector and does not set any high half elements in the destination vector, narrow the shuffle to half its original size.
Definition at line 35200 of file X86ISelLowering.cpp.
References getHalfShuffleMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), getShuffleHalfVectors(), llvm::SDNode::getSimpleValueType(), llvm::SDNode::getValueType(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::EVT::isSimple(), isUndefUpperHalf(), and llvm::ArrayRef< T >::size().
Referenced by combineShuffle().
narrowVectorSelect()
static SDValue narrowVectorSelect (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
If both arms of a vector select are concatenated vectors, split the select, and concatenate the result to eliminate a wide (256-bit) vector instruction: vselect Cond, (concat T0, T1), (concat F0, F1) –> concat (vselect (split Cond), T0, F0), (vselect (split Cond), T1, F1)
Definition at line 37629 of file X86ISelLowering.cpp.
References llvm::X86ISD::BLENDV, llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::EVT::is256BitVector(), and llvm::ISD::VSELECT.
needCarryOrOverflowFlag()
static bool needCarryOrOverflowFlag (SDValue Flags) static
Definition at line 44369 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::BRCOND, llvm::X86ISD::CMOV, llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NO, llvm::X86::COND_O, llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getOpcode(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by combineCMP().
negateFMAOpcode()
static unsigned negateFMAOpcode (unsigned Opcode, bool NegMul, bool NegAcc, bool NegRes) static
Definition at line 42512 of file X86ISelLowering.cpp.
References llvm::ISD::FMA, llvm::X86ISD::FMADD_RND, llvm::X86ISD::FMADDSUB, llvm::X86ISD::FMADDSUB_RND, llvm::X86ISD::FMSUB, llvm::X86ISD::FMSUB_RND, llvm::X86ISD::FMSUBADD, llvm::X86ISD::FMSUBADD_RND, llvm::X86ISD::FNMADD, llvm::X86ISD::FNMADD_RND, llvm::X86ISD::FNMSUB, llvm::X86ISD::FNMSUB_RND, and llvm_unreachable.
Referenced by combineFMA(), combineFMADDSUB(), combineFneg(), and llvm::X86TargetLowering::getNegatedExpression().
onlyZeroFlagUsed()
static bool onlyZeroFlagUsed (SDValue Flags) static
Definition at line 44407 of file X86ISelLowering.cpp.
References assert(), llvm::X86ISD::BRCOND, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getOpcode(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by combineCMP().
parseConstraintCode()
static X86::CondCode parseConstraintCode (llvm::StringRef Constraint) static
Definition at line 46379 of file X86ISelLowering.cpp.
Referenced by llvm::X86TargetLowering::getConstraintType(), and llvm::X86TargetLowering::getRegForInlineAsmConstraint().
Passv64i1ArgInRegs()
static void Passv64i1ArgInRegs (const SDLoc & Dl, SelectionDAG & DAG, SDValue & Arg, SmallVectorImpl< std::pair< unsigned, SDValue >> & RegsToPass, CCValAssign & VA, CCValAssign & NextVA, const X86Subtarget & Subtarget) static
Breaks v64i1 value into two registers and adds the new node to the DAG.
Definition at line 2612 of file X86ISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeReturn(), llvm::ISD::ANY_EXTEND, assert(), llvm::CCValAssign::BCvt, llvm::EVT::bitsLT(), contains(), llvm::CCValAssign::convertToReg(), llvm::ISD::CopyToReg, llvm::MachineRegisterInfo::disableCalleeSavedRegister(), E, llvm::N86::EAX, llvm::SmallVectorBase::empty(), errorUnsupported(), llvm::ISD::EXTRACT_ELEMENT, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FP_EXTEND, llvm::CCValAssign::FPExt, llvm::SelectionDAG::getBitcast(), llvm::X86MachineFunctionInfo::getBytesToPopOnReturn(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::X86Subtarget::getRegisterInfo(), llvm::TargetLoweringBase::getRegisterType(), llvm::X86MachineFunctionInfo::getSRetReturnReg(), llvm::SelectionDAG::getTargetConstant(), llvm::X86Subtarget::getTargetTriple(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::CCValAssign::getValVT(), llvm::EVT::getVectorElementType(), llvm::MVT::Glue, llvm::X86Subtarget::hasBWI(), llvm::Function::hasFnAttribute(), llvm::SDNode::hasNUsesOfValue(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MipsISD::Hi, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::IRET, llvm::X86Subtarget::is32Bit(), llvm::X86Subtarget::is64Bit(), llvm::Triple::isOSDarwin(), llvm::CCValAssign::isRegLoc(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::X86Subtarget::isTarget64BitILP32(), llvm::EVT::isVector(), llvm_unreachable, llvm::MipsISD::Lo, lowerMasksToReg(), N, llvm::CCValAssign::needsCustom(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), Reg, llvm::report_fatal_error(), llvm::X86ISD::RET_FLAG, llvm::RetCC_X86(), llvm::ISD::SCALAR_TO_VECTOR, llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase::size(), TRI, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v64i1, llvm::CallingConv::X86_INTR, llvm::CallingConv::X86_RegCall, llvm::MVT::x86mmx, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by getMOVL().
promoteExtBeforeAdd()
static SDValue promoteExtBeforeAdd (SDNode * Ext, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
sext(add_nsw(x, C)) –> add(sext(x), C_sext) zext(add_nuw(x, C)) –> add(zext(x), C_zext) Promoting a sign/zero extension ahead of a no overflow 'add' exposes opportunities to combine math ops, use an LEA, or use a complex addressing mode.
This can eliminate extend, add, and shift instructions.
Definition at line 43225 of file X86ISelLowering.cpp.
References llvm::MCID::Add, llvm::ISD::ADD, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getFlags(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::SDNodeFlags::hasNoSignedWrap(), llvm::SDNodeFlags::hasNoUnsignedWrap(), llvm::MVT::i64, llvm::SDNodeFlags::setNoSignedWrap(), llvm::SDNodeFlags::setNoUnsignedWrap(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::SDNode::uses(), and llvm::ISD::ZERO_EXTEND.
Referenced by combineSext(), and combineZext().
PromoteMaskArithmetic()
static SDValue PromoteMaskArithmetic (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Definition at line 39874 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isOperationLegalOrPromote(), llvm::EVT::isVector(), llvm_unreachable, llvm::ISD::OR, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::TRUNCATE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by combineSext(), and combineZext().
recoverFramePointer()
static SDValue recoverFramePointer (SelectionDAG & DAG, const Function * Fn, SDValue EntryEBP) static
When the MSVC runtime transfers control to us, either to an outlined function or when returning to a parent frame after catching an exception, we recover the parent frame pointer by doing arithmetic on the incoming EBP.
Here's the math: RegNodeBase = EntryEBP - RegNodeSize ParentFP = RegNodeBase - ParentFrameOffset Subtracting RegNodeSize takes us to the offset of the registration node, and subtracting the offset (negative on x86) takes us back to the parent FP.
Definition at line 23549 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::ADX, llvm::ISD::AND, assert(), llvm::X86ISD::BEXTR, llvm::BEXTRI, llvm::BLENDV, C, llvm::EVT::changeVectorElementTypeToInteger(), llvm::CMP_MASK_CC, llvm::CMP_MASK_SCALAR_CC, llvm::COMI, llvm::COMI_RM, llvm::COMPRESS_EXPAND_IN_REG, llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_E, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_O, llvm::X86::COND_P, llvm::X86::COND_S, llvm::X86::CUR_DIRECTION, llvm::CVTNEPS2BF16_MASK, llvm::CVTPD2DQ_MASK, llvm::CVTPD2PS_MASK, llvm::CVTPS2PH_MASK, llvm::CVTQQ2PS_MASK, llvm::GlobalValue::dropLLVMManglingEscape(), llvm::dyn_cast(), llvm::FIXUPIMM, llvm::FIXUPIMM_MASKZ, llvm::FPCLASSS, llvm::X86ISD::FSETCCM, llvm::X86ISD::FSETCCM_SAE, llvm::X86RegisterInfo::getBaseRegister(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::MachineModuleInfo::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFunctionNumber(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::getIntrinsicWithoutChain(), llvm::SelectionDAG::getMachineFunction(), getMaskNode(), llvm::SelectionDAG::getMCSymbol(), llvm::SelectionDAG::getMergeValues(), llvm::MachineFunction::getMMI(), llvm::Value::getName(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MCContext::getOrCreateLSDASymbol(), llvm::MCContext::getOrCreateParentFrameOffsetSymbol(), llvm::TargetLoweringBase::getPointerTy(), llvm::X86RegisterInfo::getPtrSizedFrameRegister(), llvm::X86RegisterInfo::getPtrSizedStackRegister(), llvm::X86Subtarget::getRegisterInfo(), getScalarMaskingNode(), getSEHRegistrationNodeSize(), getSETCC(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetLoweringInfo(), getTargetVShiftNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), getVectorMaskingNode(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getVTList(), getZeroVector(), llvm::X86RegisterInfo::hasBasePointer(), llvm::Function::hasPersonalityFn(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::IFMA_OP, llvm::ISD::INSERT_SUBVECTOR, llvm::INTR_TYPE_1OP, llvm::INTR_TYPE_1OP_MASK, llvm::INTR_TYPE_1OP_MASK_SAE, llvm::INTR_TYPE_1OP_SAE, llvm::INTR_TYPE_2OP, llvm::INTR_TYPE_2OP_MASK, llvm::INTR_TYPE_2OP_MASK_SAE, llvm::INTR_TYPE_2OP_SAE, llvm::INTR_TYPE_3OP, llvm::INTR_TYPE_3OP_IMM8, llvm::INTR_TYPE_3OP_MASK_SAE, llvm::INTR_TYPE_3OP_SCALAR_MASK_SAE, llvm::INTR_TYPE_4OP, llvm::INTR_TYPE_SCALAR_MASK, llvm::INTR_TYPE_SCALAR_MASK_RND, llvm::INTR_TYPE_SCALAR_MASK_SAE, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::X86Subtarget::is64Bit(), llvm::isAllOnesConstant(), llvm::ISD::isBuildVectorAllOnes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::X86ISD::KTEST, LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::LOCAL_RECOVER, llvm::BitmaskEnumDetail::Mask(), llvm::X86ISD::MMX_MOVW2D, llvm::X86::NO_EXC, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::IntrinsicData::Opc0, llvm::IntrinsicData::Opc1, Operation, llvm::ISD::OR, llvm::MVT::Other, llvm::X86ISD::PCMPESTR, llvm::X86ISD::PCMPISTR, llvm::X86ISD::PTEST, Reg, llvm::report_fatal_error(), Results, llvm::ROUNDP, llvm::ROUNDS, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SUB, llvm::Test, llvm::X86ISD::TESTP, llvm::X86::TO_NEAREST_INT, llvm::X86::TO_NEG_INF, llvm::X86::TO_POS_INF, llvm::X86::TO_ZERO, llvm::TRUNCATE_TO_REG, llvm::IntrinsicData::Type, llvm::MVT::Untyped, llvm::MVT::v16i1, llvm::MVT::v16i8, llvm::MVT::v1i1, llvm::MVT::v8i1, llvm::X86ISD::VFIXUPIMM, llvm::X86ISD::VFIXUPIMM_SAE, llvm::X86ISD::VP2INTERSECT, llvm::VPERM_2OP, llvm::X86ISD::VRNDSCALE, llvm::X86ISD::VRNDSCALES, llvm::VSHIFT, llvm::X86ISD::Wrapper, llvm::MVT::x86mmx, and llvm::ISD::ZERO_EXTEND.
reduceMaskedLoadToScalarLoad()
static SDValue reduceMaskedLoadToScalarLoad (MaskedLoadSDNode * ML, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI) static
If exactly one element of the mask is set for a non-extending masked load, it is a scalar load and vector insert.
Note: It is expected that the degenerate cases of an all-zeros or all-ones mask have already been optimized in IR, so we don't bother with those here.
Definition at line 41380 of file X86ISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), getParamsForOneTrueMaskedElt(), llvm::MaskedLoadSDNode::getPassThru(), llvm::MemSDNode::getPointerInfo(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::ISD::INSERT_VECTOR_ELT, llvm::MaskedLoadStoreSDNode::isUnindexed(), and llvm::SPII::Load.
Referenced by combineMaskedLoad().
reduceMaskedStoreToScalarStore()
static SDValue reduceMaskedStoreToScalarStore (MaskedStoreSDNode * MS, SelectionDAG & DAG) static
If exactly one element of the mask is set for a non-truncating masked store, it is a vector extract and scalar store.
Note: It is expected that the degenerate cases of an all-zeros or all-ones mask have already been optimized in IR, so we don't bother with those here.
Definition at line 41481 of file X86ISelLowering.cpp.
References llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), getParamsForOneTrueMaskedElt(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::MaskedStoreSDNode::getValue(), llvm::SDValue::getValueType(), and llvm::EVT::getVectorElementType().
Referenced by combineMaskedStore().
reduceVMULWidth()
static SDValue reduceVMULWidth (SDNode * N, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
When the operands of vector mul are extended from smaller size values, like i8 and i16, the type of mul may be shrinked to generate more efficient code.
Two typical patterns are handled: Pattern1: %2 = sext/zext <N x="" i8>=""> %1 to <N x="" i32>=""> %4 = sext/zext <N x="" i8>=""> %3 to <N x="" i32>=""> %5 = mul <N x="" i32>=""> %2, %4
Pattern2: %2 = zext/sext <N x="" i16>=""> %1 to <N x="" i32>=""> %4 = zext/sext <N x="" i16>=""> %3 to <N x="" i32>=""> or %4 = build_vector <N x="" i32>=""> C1, ..., CN (C1..CN are constants) %5 = mul <N x="" i32>=""> %2, %4
There are four mul shrinking modes: If %2 == sext32(trunc8(%2)), i.e., the scalar value range of %2 is -128 to 128, and the scalar value range of %4 is also -128 to 128, generate pmullw+sext32 for it (MULS8 mode). If %2 == zext32(trunc8(%2)), i.e., the scalar value range of %2 is 0 to 255, and the scalar value range of %4 is also 0 to 255, generate pmullw+zext32 for it (MULU8 mode). If %2 == sext32(trunc16(%2)), i.e., the scalar value range of %2 is -32768 to 32767, and the scalar value range of %4 is also -32768 to 32767, generate pmullw+pmulhw for it (MULS16 mode). If %2 == zext32(trunc16(%2)), i.e., the scalar value range of %2 is 0 to 65535, and the scalar value range of %4 is also 0 to 65535, generate pmullw+pmulhuw for it (MULU16 mode).
Definition at line 38951 of file X86ISelLowering.cpp.
References canReduceVMulWidth(), llvm::ISD::CONCAT_VECTORS, llvm::numbers::e, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::Function::hasMinSize(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::X86Subtarget::isPMULLDSlow(), Mode, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, MULS16, MULS8, MULU8, llvm::ISD::SIGN_EXTEND, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineMul().
resolveTargetShuffleFromZeroables()
static void resolveTargetShuffleFromZeroables (SmallVectorImpl< int > & Mask, const APInt & KnownUndef, const APInt & KnownZero, bool ResolveKnownZeros = true) static
Definition at line 7078 of file X86ISelLowering.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineX86ShufflesRecursively(), and getTargetShuffleInputs().
resolveTargetShuffleInputsAndMask()
static void resolveTargetShuffleInputsAndMask (SmallVectorImpl< SDValue > & Inputs, SmallVectorImpl< int > & Mask) static
Removes unused/repeated shuffle source inputs and adjusts the shuffle mask.
Definition at line 7504 of file X86ISelLowering.cpp.
References llvm::numbers::e, isUndef(), llvm::none_of(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::SmallVectorBase::size(), and llvm::SM_SentinelUndef.
Referenced by combineX86ShuffleChainWithExtract(), and combineX86ShufflesRecursively().
resolveZeroablesFromTargetShuffle()
static void resolveZeroablesFromTargetShuffle (const SmallVectorImpl< int > & Mask, APInt & KnownUndef, APInt & KnownZero) static
Definition at line 7095 of file X86ISelLowering.cpp.
References llvm::Depth, llvm::APInt::getNullValue(), getTargetShuffleInputs(), llvm::BitmaskEnumDetail::Mask(), llvm::APInt::setBit(), llvm::SmallVectorBase::size(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by combineX86ShuffleChain(), and getTargetShuffleInputs().
scalarizeExtEltFP()
static SDValue scalarizeExtEltFP (SDNode * ExtElt, SelectionDAG & DAG) static
Extracting a scalar FP value from vector element 0 is free, so extract each operand first, then perform the math as a scalar op.
Definition at line 37170 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::X86ISD::FMAX, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::X86ISD::FMIN, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::X86ISD::FRCP, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::X86ISD::FRSQRT, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SDNode::getValueType(), llvm::MVT::i1, llvm::isNullConstant(), llvm_unreachable, llvm::SDNode::ops(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::SELECT, llvm::ISD::SETCC, and llvm::ISD::VSELECT.
Referenced by combineExtractVectorElt().
scalarizeVectorStore()
static SDValue scalarizeVectorStore (StoreSDNode * Store, MVT StoreVT, SelectionDAG & DAG) static
Scalarize a vector store, bitcasting to TargetVT to determine the scalar type.
Definition at line 22646 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getBitcast(), llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::MVT::getScalarType(), llvm::SelectionDAG::getStore(), llvm::MVT::getStoreSize(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::MVT::getVectorNumElements(), llvm::MachinePointerInfo::getWithOffset(), llvm::EVT::is128BitVector(), llvm::MVT::is128BitVector(), llvm::MemSDNode::isSimple(), llvm::MinAlign(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::TokenFactor.
Referenced by llvm::TargetLowering::getRecipEstimate().
scaleVectorShuffleBlendMask()
static uint64_t scaleVectorShuffleBlendMask (uint64_t BlendMask, int Size, int Scale) static
Definition at line 11218 of file X86ISelLowering.cpp.
References Size.
Referenced by combineTargetShuffle().
SegmentOffset()
static Constant* SegmentOffset (IRBuilder<> & IRB, unsigned Offset, unsigned AddressSpace) static
Definition at line 2460 of file X86ISelLowering.cpp.
References llvm::ConstantInt::get(), llvm::IRBuilderBase::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), and llvm::ConstantExpr::getIntToPtr().
Referenced by llvm::object::MachORebaseEntry::address(), llvm::object::MachOBindEntry::address(), llvm::X86TargetLowering::getIRStackGuard(), llvm::X86TargetLowering::getSafeStackPointerLocation(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::object::MachORebaseEntry::sectionName(), llvm::object::MachOBindEntry::sectionName(), llvm::object::MachORebaseEntry::segmentOffset(), and llvm::object::MachOBindEntry::segmentOffset().
shouldGuaranteeTCO()
static bool shouldGuaranteeTCO (CallingConv::ID CC, bool GuaranteedTailCallOpt) static
Return true if the function is being made into a tailcall target by changing its ABI.
Definition at line 3171 of file X86ISelLowering.cpp.
References llvm::ISD::ADD, canGuaranteeTCO(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CallSiteBase< FunTy, BBTy, ValTy, UserTy, UseTy, InstrTy, CallTy, InvokeTy, CallBrTy, IterTy >::getCallingConv(), llvm::SelectionDAG::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTarget(), llvm::CCValAssign::getValVT(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::MVT::i1, llvm::CCValAssign::Indirect, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isCopyElisionCandidate(), llvm::CCValAssign::isExtInLoc(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::CallInst::isTailCall(), llvm::MVT::isVector(), mayTailCallThisCC(), llvm::TargetMachine::Options, llvm::ISD::SCALAR_TO_VECTOR, llvm::MachineFrameInfo::setObjectSExt(), llvm::MachineFrameInfo::setObjectZExt(), llvm::CCValAssign::SExt, llvm::CallingConv::Tail, llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
Referenced by llvm::X86::isCalleePop(), and isSortedByValueNo().
shouldUseHorizontalOp()
static bool shouldUseHorizontalOp (bool IsSingleSource, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Horizontal vector math instructions may be slower than normal math with shuffles.
Limit horizontal op codegen based on size/speed trade-offs, uarch implementation, and likely shuffle complexity of the alternate sequence.
Definition at line 18919 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasFastHorizontalOps(), and llvm::SelectionDAG::shouldOptForSize().
Referenced by isHorizontalBinOp(), lowerAddSubToHorizontalOp(), and LowerUINT_TO_FP_i64().
signExtendBitcastSrcVector()
static SDValue signExtendBitcastSrcVector (SelectionDAG & DAG, EVT SExtVT, SDValue Src, const SDLoc & DL) static
Definition at line 36195 of file X86ISelLowering.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm_unreachable, llvm::ISD::OR, llvm::ISD::SETCC, llvm::ISD::SIGN_EXTEND, and llvm::ISD::XOR.
Referenced by combineBitcastvxi1().
split256IntArith()
static SDValue split256IntArith (SDValue Op, SelectionDAG & DAG) static
Break a 256-bit integer operation into two new 128-bit ones and then concatenate the result back.
Definition at line 25684 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extract128BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is256BitVector(), and llvm::MVT::isInteger().
Referenced by combineExtractSubvector(), LowerADDSAT_SUBSAT(), lowerAddSub(), LowerMINMAX(), LowerMUL(), LowerMULH(), LowerRotate(), and LowerShift().
split512IntArith()
static SDValue split512IntArith (SDValue Op, SelectionDAG & DAG) static
Break a 512-bit integer operation into two new 256-bit ones and then concatenate the result back.
Definition at line 25713 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extract256BitVector(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::is512BitVector(), and llvm::MVT::isInteger().
Referenced by LowerMULH().
SplitAndExtendv16i1()
static SDValue SplitAndExtendv16i1 (unsigned ExtOpc, MVT VT, SDValue In, const SDLoc & dl, SelectionDAG & DAG) static
Definition at line 19637 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::ISD::TRUNCATE, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v8i1, and llvm::MVT::v8i16.
Referenced by LowerSIGN_EXTEND_Mask(), and LowerZERO_EXTEND_Mask().
splitAndLowerShuffle()
static SDValue splitAndLowerShuffle (const SDLoc & DL, MVT VT, SDValue V1, SDValue V2, ArrayRef< int > Mask, SelectionDAG & DAG) static
Generic routine to split vector shuffle into half-sized shuffles.
This routine just extracts two subvectors, shuffles them independently, and then concatenates them back together. This should work effectively with all AVX vector shuffle types.
Definition at line 14714 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, llvm::dyn_cast(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::peekThroughBitcasts(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
Referenced by lower256BitShuffle(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsSplitOrBlend(), and lowerV64I8Shuffle().
SplitOpsAndApply()
template<typename F > SDValue SplitOpsAndApply (SelectionDAG & DAG, const X86Subtarget & Subtarget, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, F Builder, bool CheckBWI = true)
Definition at line 5770 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extractSubVector(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSE2(), llvm::SmallVectorTemplateBase< T >::push_back(), llvm::X86Subtarget::useAVX512Regs(), and llvm::X86Subtarget::useBWIRegs().
Referenced by combineAdd(), combineLoopMAddPattern(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineSub(), createPSADBW(), createVariablePermute(), detectAVGPattern(), detectPMADDUBSW(), matchPMADDWD(), and matchPMADDWD_2().
splitVectorStore()
static SDValue splitVectorStore (StoreSDNode * Store, SelectionDAG & DAG) static
Change a vector store into a pair of half-size vector stores.
Definition at line 22609 of file X86ISelLowering.cpp.
References assert(), extractSubVector(), llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MachinePointerInfo::getWithOffset(), llvm::EVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::MemSDNode::isSimple(), llvm::MinAlign(), llvm::MVT::Other, and llvm::ISD::TokenFactor.
Referenced by combineStore(), and LowerStore().
STATISTIC()
STATISTIC (NumTailCalls , "Number of tail calls")
SupportedVectorShiftWithBaseAmnt()
static bool SupportedVectorShiftWithBaseAmnt (MVT VT, const X86Subtarget & Subtarget, unsigned Opcode) static
Definition at line 26320 of file X86ISelLowering.cpp.
References SupportedVectorShiftWithImm().
Referenced by LowerScalarVariableShift().
SupportedVectorShiftWithImm()
static bool SupportedVectorShiftWithImm (MVT VT, const X86Subtarget & Subtarget, unsigned Opcode) static
Definition at line 26300 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::ISD::SRA, llvm::MVT::v2i64, and llvm::MVT::v4i64.
Referenced by combineAndMaskToShift(), LowerScalarImmediateShift(), and SupportedVectorShiftWithBaseAmnt().
SupportedVectorVarShift()
static bool SupportedVectorVarShift (MVT VT, const X86Subtarget & Subtarget, unsigned Opcode) static
Definition at line 26327 of file X86ISelLowering.cpp.
References llvm::MVT::getScalarSizeInBits(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasBWI(), llvm::X86Subtarget::hasInt256(), llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::ISD::SRA, llvm::MVT::v2i64, and llvm::MVT::v4i64.
Referenced by LowerRotate(), and LowerShift().
TranslateIntegerX86CC()
static X86::CondCode TranslateIntegerX86CC (ISD::CondCode SetCCOpcode) static
Definition at line 4830 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
Referenced by TranslateX86CC().
TranslateX86CC()
static X86::CondCode TranslateX86CC (ISD::CondCode SetCCOpcode, const SDLoc & DL, bool isFP, SDValue & LHS, SDValue & RHS, SelectionDAG & DAG) static
Do a one-to-one translation of a ISD::CondCode to the X86-specific condition code, returning the condition code and the LHS/RHS of the comparison to make.
Definition at line 4849 of file X86ISelLowering.cpp.
References llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_INVALID, llvm::X86::COND_LE, llvm::X86::COND_NE, llvm::X86::COND_NP, llvm::X86::COND_NS, llvm::X86::COND_P, llvm::X86::COND_S, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getValueType(), llvm::ISD::isNON_EXTLoad(), llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, std::swap(), and TranslateIntegerX86CC().
Referenced by EmitAVX512Test().
translateX86FSETCC()
static unsigned translateX86FSETCC (ISD::CondCode SetCCOpcode, SDValue & Op0, SDValue & Op1, bool & IsAlwaysSignaling) static
Turns an ISD::CondCode into a value suitable for SSE floating-point mask CMPs.
Definition at line 21153 of file X86ISelLowering.cpp.
References LLVM_FALLTHROUGH, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, and std::swap().
truncateVectorWithPACK()
static SDValue truncateVectorWithPACK (unsigned Opcode, EVT DstVT, SDValue In, const SDLoc & DL, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Helper to recursively truncate vector elements in half with PACKSS/PACKUS.
It makes use of the fact that vectors with enough leading sign/zero bits prevent the PACKSS/PACKUS from saturating the results. AVX2 (Int256) sub-targets require extra shuffling as the PACK*S operates within each 128-bit lane.
Definition at line 19725 of file X86ISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, extractSubVector(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::X86Subtarget::hasInt256(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MipsISD::Hi, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::tgtok::In, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::EVT::is512BitVector(), llvm::isPowerOf2_32(), llvm::EVT::isVector(), llvm::MipsISD::Lo, llvm::BitmaskEnumDetail::Mask(), llvm::X86ISD::PACKSS, and llvm::X86ISD::PACKUS.
Referenced by combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), and LowerTruncateVecI1().
useVectorCast()
static bool useVectorCast (unsigned Opcode, MVT FromVT, MVT ToVT, const X86Subtarget & Subtarget) static
Definition at line 18621 of file X86ISelLowering.cpp.
References llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v4i32.
Referenced by vectorizeExtractedCast().
vectorizeExtractedCast()
static SDValue vectorizeExtractedCast (SDValue Cast, SelectionDAG & DAG, const X86Subtarget & Subtarget) static
Given a scalar cast operation that is extracted from a vector, try to vectorize the cast op followed by extraction.
This will avoid an expensive round-trip between XMM and GPR.
Definition at line 18646 of file X86ISelLowering.cpp.
References extract128BitVector(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::getVectorVT(), llvm::isNullConstant(), llvm::BitmaskEnumDetail::Mask(), and useVectorCast().
Referenced by lowerINT_TO_FP_vXi64(), and lowerUINT_TO_FP_vec().
widenSubVector() [1/2]
static SDValue widenSubVector (MVT VT, SDValue Vec, bool ZeroNewElements, const X86Subtarget & Subtarget, SelectionDAG & DAG, const SDLoc & dl) static
Widen a vector to a larger size with the same scalar type, with the new elements either zero or undef.
Definition at line 5702 of file X86ISelLowering.cpp.
References assert(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::MVT::getScalarType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), getZeroVector(), and llvm::ISD::INSERT_SUBVECTOR.
Referenced by combineX86ShuffleChainWithExtract(), createVariablePermute(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and widenSubVector().
widenSubVector() [2/2]
static SDValue widenSubVector (SDValue Vec, bool ZeroNewElements, const X86Subtarget & Subtarget, SelectionDAG & DAG, const SDLoc & dl, unsigned WideSizeInBits) static
Widen a vector to a larger size with the same scalar type, with the new elements either zero or undef.
Definition at line 5716 of file X86ISelLowering.cpp.
References assert(), llvm::MVT::getScalarType(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::getValueSizeInBits(), llvm::MVT::getVectorVT(), and widenSubVector().
Variable Documentation
EnableOldKNLABI
cl::opt<bool> EnableOldKNLABI("x86-enable-old-knl-abi", cl::init(false), cl::desc("Enables passing v32i16 and v64i8 in 2 YMM registers instead of " "one ZMM register on AVX512F, but not AVX512BW targets."), cl::Hidden) static
Referenced by llvm::X86TargetLowering::getNumRegistersForCallingConv(), and llvm::X86TargetLowering::getRegisterTypeForCallingConv().
ExperimentalPrefLoopAlignment
cl::opt<int> ExperimentalPrefLoopAlignment("x86-experimental-pref-loop-alignment", cl::init(4), cl::desc("Sets the preferable loop alignment for experiments (as log2 bytes)" "(the last x86-experimental-pref-loop-alignment bits" " of the loop header PC will be 0)."), cl::Hidden) static
Referenced by llvm::X86TargetLowering::X86TargetLowering().
ExperimentalUnorderedISEL
cl::opt<bool> ExperimentalUnorderedISEL("x86-experimental-unordered-atomic-isel", cl::init(false), cl::desc("Use LoadSDNode and StoreSDNode instead of " "AtomicSDNode for unordered atomic loads and " "stores respectively."), cl::Hidden) static
Referenced by LowerRotate().
MulConstantOptimization
cl::opt<bool> MulConstantOptimization("mul-constant-optimization", cl::init(true), cl::desc("Replace 'mul x, Const' with more effective instructions like " "SHIFT, LEA, etc."), cl::Hidden) static
Referenced by combineMul().