LLVM: lib/Target/X86/X86InterleavedAccess.cpp File Reference
X86InterleavedAccess.cpp File Reference
This file contains the X86 implementation of the interleaved accesses optimization generating X86-specific instructions/intrinsics for interleaved access groups.
#include "X86ISelLowering.h"
#include "X86Subtarget.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/MachineValueType.h"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdint>
Functions
static MVT scaleVectorType (MVT VT)
static void genShuffleBland (MVT VT, ArrayRef< uint32_t > Mask, SmallVectorImpl< uint32_t > &Out, int LowOffset, int HighOffset)
static void reorderSubVector (MVT VT, SmallVectorImpl< Value *> &TransposedMatrix, ArrayRef< Value *> Vec, ArrayRef< uint32_t > VPShuf, unsigned VecElems, unsigned Stride, IRBuilder<> Builder)
static void createShuffleStride (MVT VT, int Stride, SmallVectorImpl< uint32_t > &Mask)
static void setGroupSize (MVT VT, SmallVectorImpl< uint32_t > &SizeInfo)
static void DecodePALIGNRMask (MVT VT, unsigned Imm, SmallVectorImpl< uint32_t > &ShuffleMask, bool AlignDirection=true, bool Unary=false)
static void concatSubVector (Value **Vec, ArrayRef< Instruction *> InVec, unsigned VecElems, IRBuilder<> Builder)
static void group2Shuffle (MVT VT, SmallVectorImpl< uint32_t > &Mask, SmallVectorImpl< uint32_t > &Output)
Variables
static uint32_t Concat []
Detailed Description
This file contains the X86 implementation of the interleaved accesses optimization generating X86-specific instructions/intrinsics for interleaved access groups.
Definition in file X86InterleavedAccess.cpp.
Function Documentation
concatSubVector()
static void concatSubVector (Value ** Vec, ArrayRef< Instruction *> InVec, unsigned VecElems, IRBuilder<> Builder) static
Definition at line 521 of file X86InterleavedAccess.cpp.
References createShuffleStride(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), llvm::DecodePALIGNRMask(), llvm::UndefValue::get(), getType(), llvm::Value::getType(), llvm::MVT::getVT(), llvm::makeArrayRef(), llvm::SmallVectorImpl< T >::resize(), and setGroupSize().
createShuffleStride()
static void createShuffleStride (MVT VT, int Stride, SmallVectorImpl< uint32_t > & Mask) static
Definition at line 435 of file X86InterleavedAccess.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::max(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by concatSubVector().
DecodePALIGNRMask()
static void DecodePALIGNRMask (MVT VT, unsigned Imm, SmallVectorImpl< uint32_t > & ShuffleMask, bool AlignDirection = true, bool Unary = false) static
Definition at line 472 of file X86InterleavedAccess.cpp.
References llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::max(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
genShuffleBland()
static void genShuffleBland (MVT VT, ArrayRef< uint32_t > Mask, SmallVectorImpl< uint32_t > & Out, int LowOffset, int HighOffset) static
Definition at line 254 of file X86InterleavedAccess.cpp.
References assert(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ArrayRef< T >::size().
Referenced by reorderSubVector().
group2Shuffle()
static void group2Shuffle (MVT VT, SmallVectorImpl< uint32_t > & Mask, SmallVectorImpl< uint32_t > & Output) static
Definition at line 608 of file X86InterleavedAccess.cpp.
References assert(), llvm::concatenateVectors(), llvm::DecodePALIGNRMask(), llvm::numbers::e, llvm::VectorType::get(), llvm::UndefValue::get(), llvm::StoreInst::getAlignment(), llvm::StoreInst::getPointerOperand(), llvm::MVT::getSizeInBits(), getType(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i8, llvm::makeArrayRef(), llvm::BitmaskEnumDetail::Mask(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), reorderSubVector(), llvm::SmallVectorImpl< T >::resize(), setGroupSize(), SI, and llvm::ArrayRef< T >::size().
reorderSubVector()
static void reorderSubVector (MVT VT, SmallVectorImpl< Value *> & TransposedMatrix, ArrayRef< Value *> Vec, ArrayRef< uint32_t > VPShuf, unsigned VecElems, unsigned Stride, IRBuilder<> Builder) static
Definition at line 284 of file X86InterleavedAccess.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::copy(), llvm::IRBuilder< T, Inserter >::CreateShuffleVector(), genShuffleBland(), llvm::UndefValue::get(), llvm::MVT::getVectorVT(), llvm::MVT::i8, llvm::makeArrayRef(), Matrix, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), scaleVectorType(), llvm::MVT::v16i8, and llvm::MVT::v8i16.
Referenced by group2Shuffle().
scaleVectorType()
static MVT scaleVectorType (MVT VT) static
Definition at line 226 of file X86InterleavedAccess.cpp.
References llvm::MVT::getIntegerVT(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and llvm::MVT::getVectorVT().
Referenced by reorderSubVector().
setGroupSize()
static void setGroupSize (MVT VT, SmallVectorImpl< uint32_t > & SizeInfo) static
Definition at line 449 of file X86InterleavedAccess.cpp.
References llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::max(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by concatSubVector(), and group2Shuffle().
Variable Documentation
Concat
uint32_t Concat[] static
Initial value:
= {
  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63 }
Definition at line 232 of file X86InterleavedAccess.cpp.
Referenced by AddCombineVUZPToVPADDL(), combineExtractSubvector(), combineLoopMAddPattern(), combineScalarAndWithMaskSetcc(), combineShuffleOfConcatUndef(), combineVectorPack(), ConcatStringInits(), llvm::LegalizerHelper::fewerElementsVectorBuildVector(), getDUPLANEOp(), getInsertVecEltOpInfo(), llvm::LegalizerHelper::narrowScalar(), reduceBuildVecToShuffleWithZero(), scalarizeBinOpOfSplats(), and llvm::SITargetLowering::shouldEmitPCReloc().