LLVM: lib/Target/X86/X86IndirectBranchTracking.cpp File Reference
X86IndirectBranchTracking.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
Macros
#define DEBUG_TYPE "x86-indirect-branch-tracking"
Functions
STATISTIC (NumEndBranchAdded, "Number of ENDBR instructions added")
static bool IsCallReturnTwice (llvm::MachineOperand &MOp)
Variables
static cl::opt< bool > IndirectBranchTracking ("x86-indirect-branch-tracking", cl::init(false), cl::Hidden, cl::desc("Enable X86 indirect branch tracking pass."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-indirect-branch-tracking"
Definition at line 28 of file X86IndirectBranchTracking.cpp.
Function Documentation
IsCallReturnTwice()
static bool IsCallReturnTwice (llvm::MachineOperand & MOp) static
Definition at line 87 of file X86IndirectBranchTracking.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Attrs, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::Function::doesNoCfCheck(), llvm::dyn_cast(), llvm::MachineBasicBlock::end(), llvm::AttributeList::FunctionIndex, llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::X86Subtarget::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), llvm::Module::getModuleFlag(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::hasAddressTaken(), llvm::Function::hasAddressTaken(), llvm::AttributeList::hasAttribute(), llvm::GlobalValue::hasLocalLinkage(), I, IndirectBranchTracking, llvm::X86Subtarget::is64Bit(), llvm::MachineOperand::isGlobal(), and TII.
STATISTIC()
STATISTIC (NumEndBranchAdded , "Number of ENDBR instructions added")
Variable Documentation
IndirectBranchTracking
cl::opt<bool> IndirectBranchTracking("x86-indirect-branch-tracking", cl::init(false), cl::Hidden, cl::desc("Enable X86 indirect branch tracking pass.")) static
Referenced by IsCallReturnTwice().