LLVM: lib/Target/X86/X86ISelDAGToDAG.cpp File Reference
X86ISelDAGToDAG.cpp File Reference
#include "X86.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <stdint.h>
#include "X86GenDAGISel.inc"
Macros
#define DEBUG_TYPE "x86-isel"
Functions
STATISTIC (NumLoadMoved, "Number of loads moved below TokenFactor")
static bool isLegalMaskCompare (SDNode *N, const X86Subtarget *Subtarget)
static void moveBelowOrigChain (SelectionDAG *CurDAG, SDValue Load, SDValue Call, SDValue OrigChain)
Replace the original chain operand of the call with load's chain operand and move load below the call's chain operand.
static bool isCalleeLoad (SDValue Callee, SDValue &Chain, bool HasCallSeq)
Return true if call address is a load and it can be moved below CALLSEQ_START and the chains leading up to the call.
static bool isDispSafeForFrameIndex (int64_t Val)
static void insertDAGNode (SelectionDAG &DAG, SDValue Pos, SDValue N)
static bool foldMaskAndShiftToExtract (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool foldMaskedShiftToScaledMask (SelectionDAG &DAG, SDValue N, X86ISelAddressMode &AM)
static bool foldMaskAndShiftToScale (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool foldMaskedShiftToBEXTR (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM, const X86Subtarget &Subtarget)
static bool hasSingleUsesFromRoot (SDNode *Root, SDNode *User)
static X86::CondCode getCondFromNode (SDNode *N)
static bool mayUseCarryFlag (X86::CondCode CC)
static bool isFusableLoadOpStorePattern (StoreSDNode *StoreNode, SDValue StoredVal, SelectionDAG *CurDAG, unsigned LoadOpNo, LoadSDNode *&LoadNode, SDValue &InputChain)
Check whether or not the chain ending in StoreNode is suitable for doing the {load; op; store} to modify transformation.
static unsigned getVPTESTMOpc (MVT TestVT, bool IsTestN, bool FoldedLoad, bool FoldedBCast, bool Masked)
Variables
static cl::opt< bool > AndImmShrink ("x86-and-imm-shrink", cl::init(true), cl::desc("Enable setting constant bits to reduce size of mask immediates"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-isel"
Definition at line 40 of file X86ISelDAGToDAG.cpp.
Function Documentation
foldMaskAndShiftToExtract()
static bool foldMaskAndShiftToExtract (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 1631 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i8, insertDAGNode(), llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, and llvm::ISD::SRL.
Referenced by foldMaskedShiftToBEXTR().
foldMaskAndShiftToScale()
static bool foldMaskAndShiftToScale (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 1767 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::SelectionDAG::computeKnownBits(), llvm::countLeadingZeros(), llvm::countTrailingOnes(), llvm::countTrailingZeros(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i8, insertDAGNode(), llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, llvm::ISD::SRL, and llvm::ISD::ZERO_EXTEND.
Referenced by foldMaskedShiftToBEXTR().
foldMaskedShiftToBEXTR()
static bool foldMaskedShiftToBEXTR (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM, const X86Subtarget & Subtarget) static
Definition at line 1854 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::ISD::Constant, llvm::ISD::CopyFromReg, llvm::countTrailingZeros(), llvm::dbgs(), llvm::dyn_cast(), llvm::X86ISD::EH_SJLJ_LONGJMP, llvm::X86ISD::EH_SJLJ_SETJMP, llvm::X86ISD::ENQCMD, llvm::X86ISD::ENQCMDS, foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToScaledMask(), llvm::ISD::FrameIndex, llvm::X86AS::FS, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::HandleSDNode::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::X86AS::GS, llvm::X86Subtarget::hasBMI(), llvm::X86Subtarget::hasFastBEXTR(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::X86Subtarget::hasTBM(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, insertDAGNode(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, isDispSafeForFrameIndex(), llvm::isShiftedMask_64(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm::ISD::LOAD, llvm::ISD::LOCAL_RECOVER, llvm::ISD::MUL, llvm::X86ISD::MUL_IMM, N, llvm::ISD::OR, Reg, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, llvm::ISD::SMUL_LOHI, llvm::ISD::SRL, llvm::X86AS::SS, llvm::ISD::SUB, llvm::X86ISD::TLSCALL, llvm::ISD::TRUNCATE, llvm::ISD::UMUL_LOHI, llvm::X86ISD::Wrapper, llvm::X86ISD::WrapperRIP, X, and llvm::ISD::ZERO_EXTEND.
foldMaskedShiftToScaledMask()
static bool foldMaskedShiftToScaledMask (SelectionDAG & DAG, SDValue N, X86ISelAddressMode & AM) static
Definition at line 1675 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, insertDAGNode(), llvm::isUInt< 32 >(), llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, and X.
Referenced by foldMaskedShiftToBEXTR().
getCondFromNode()
static X86::CondCode getCondFromNode (SDNode * N) static
Definition at line 2701 of file X86ISelDAGToDAG.cpp.
References assert(), llvm::X86::COND_A, llvm::X86::COND_AE, llvm::X86::COND_B, llvm::X86::COND_BE, llvm::X86::COND_E, llvm::X86::COND_INVALID, llvm::X86::COND_NE, llvm::X86::COND_NO, llvm::X86::COND_NP, llvm::X86::COND_O, llvm::X86::COND_P, llvm::ISD::CopyToReg, llvm::SDNode::getConstantOperandVal(), llvm::SDNode::getMachineOpcode(), getReg(), llvm::SDValue::getResNo(), llvm::SDNode::isMachineOpcode(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by mayUseCarryFlag().
getVPTESTMOpc()
static unsigned getVPTESTMOpc (MVT TestVT, bool IsTestN, bool FoldedLoad, bool FoldedBCast, bool Masked) static
Definition at line 4015 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::AArch64CC::AL, llvm::ISD::AND, AndImmShrink, llvm::X86ISD::ANDNP, assert(), B, llvm::X86ISD::BEXTR, llvm::ISD::BITCAST, llvm::X86ISD::BLENDV, llvm::ISD::BRIND, C, llvm::X86ISD::CMP, llvm::InlineAsm::Constraint_m, llvm::InlineAsm::Constraint_o, llvm::InlineAsm::Constraint_v, llvm::InlineAsm::Constraint_X, llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::dbgs(), llvm::SDNode::dump(), llvm::dyn_cast(), llvm::N86::EAX, llvm::N86::ECX, llvm::N86::EDX, llvm::MVT::f128, llvm::SDNode::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::ConstantSDNode::getZExtValue(), llvm::X86ISD::GlobalBaseReg, llvm::MVT::Glue, llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INTRINSIC_VOID, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::ISD::isBuildVectorAllZeros(), llvm::isInt< 32 >(), llvm::isInt< 8 >(), llvm::SDNode::isMachineOpcode(), llvm::isMask_64(), IsMasked(), llvm::isNullConstant(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::isUInt< 8 >(), llvm::MVT::isVector(), LLVM_DEBUG, LLVM_FALLTHROUGH, llvm_unreachable, llvm::SPII::Load, llvm::ISD::OR, llvm::MVT::Other, llvm::X86ISD::PCMPESTR, llvm::X86ISD::PCMPISTR, Reg, llvm::ISD::SDIVREM, llvm::MCID::Select, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::SDNode::setNodeId(), llvm::ISD::SHL, llvm::MVT::SimpleTy, llvm::X86ISD::SMUL, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, SubReg, std::swap(), llvm::Test, llvm::ISD::TRUNCATE, llvm::ISD::UDIVREM, llvm::X86ISD::UMUL, llvm::ISD::UMUL_LOHI, llvm::SDValue::use_empty(), llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2i1, llvm::MVT::v2i64, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i1, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::X86ISD::VBROADCAST_LOAD, llvm::X86ISD::VPTERNLOG, llvm::ISD::VSELECT, Widen(), and llvm::ISD::XOR.
hasSingleUsesFromRoot()
static bool hasSingleUsesFromRoot (SDNode * Root, SDNode * User) static
Definition at line 2357 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::ADC, llvm::ISD::ADD, llvm::X86ISD::ADD, assert(), llvm::dyn_cast(), llvm::N86::EBX, llvm::LoadSDNode::getBasePtr(), llvm::MachineFunction::getDataLayout(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::ConstantRange::getSignedMax(), llvm::ConstantRange::getSignedMin(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::ConstantRange::getUnsignedMax(), llvm::SDValue::getValueType(), llvm::PPCISD::GlobalBaseReg, llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::isNON_EXTLoad(), llvm::MemSDNode::isSimple(), llvm::isUInt< 32 >(), llvm::ARM_MB::LD, MI, N, P, llvm::NVPTX::PTXCvtMode::RN, llvm::X86ISD::SBB, llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::sge(), llvm::APInt::slt(), llvm::CodeModel::Small, llvm::X86ISD::SUB, llvm::T, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::SystemZISD::TM, llvm::ISD::TRUNCATE, llvm::APInt::ult(), llvm::SDNode::use_begin(), llvm::X86ISD::VBROADCAST_LOAD, llvm::X86ISD::VZEXT_LOAD, and llvm::X86ISD::Wrapper.
insertDAGNode()
static void insertDAGNode (SelectionDAG & DAG, SDValue Pos, SDValue N) static
Definition at line 1613 of file X86ISelDAGToDAG.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::SDValue::getNode(), llvm::SDNode::getNodeId(), llvm::SelectionDAGISel::getUninvalidatedNodeId(), llvm::SelectionDAGISel::InvalidateNodeId(), llvm::SelectionDAG::RepositionNode(), and llvm::SDNode::setNodeId().
Referenced by foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), and foldMaskedShiftToScaledMask().
isCalleeLoad()
static bool isCalleeLoad (SDValue Callee, SDValue & Chain, bool HasCallSeq) static
Return true if call address is a load and it can be moved below CALLSEQ_START and the chains leading up to the call.
Return the CALLSEQ_START by reference as a second output. In the case of a tail call, there isn't a callseq node between the call chain and the load.
Definition at line 764 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::AND, llvm::ISD::AND, llvm::X86ISD::ANDNP, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::ISD::BITCAST, llvm::CallingConv::C, llvm::X86ISD::CALL, llvm::ISD::CALLSEQ_START, llvm::EVT::changeVectorElementTypeToInteger(), llvm::X86ISD::CVTTP2SI, llvm::X86ISD::CVTTP2UI, llvm::dyn_cast(), E, llvm::X86II::EncodingMask, llvm::X86II::EVEX, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, F(), llvm::MVT::f128, llvm::MVT::f64, llvm::X86ISD::FAND, llvm::X86ISD::FANDN, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::X86ISD::FLD, llvm::ISD::FNEARBYINT, llvm::X86ISD::FOR, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRINT, llvm::X86ISD::FST, llvm::ISD::FTRUNC, llvm::X86ISD::FXOR, llvm::LSBaseSDNode::getAddressingMode(), llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getConstantOperandVal(), llvm::LoadSDNode::getExtensionType(), llvm::SDNode::getFlags(), llvm::MachineFunction::getFunction(), llvm::SDValue::getMachineOpcode(), llvm::SDNode::getMachineOpcode(), llvm::Value::getName(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::Type::getVoidTy(), llvm::SDNode::hasAnyUseOfValue(), llvm::GlobalValue::hasExternalLinkage(), llvm::SDNodeFlags::hasNoFPExcept(), llvm::SDValue::hasOneUse(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::SDValue::isMachineOpcode(), llvm::SDNode::isMachineOpcode(), llvm::SDNode::isOnlyUserOf(), llvm::SDValue::isOperandOf(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::MemSDNode::isSimple(), llvm::SDNode::isStrictFPOpcode(), llvm::EVT::isVector(), llvm::MVT::isVector(), llvm::ARM_MB::LD, llvm_unreachable, llvm::SPII::Load, llvm::TargetLowering::LowerCallTo(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, moveBelowOrigChain(), llvm::ISD::NON_EXTLOAD, llvm::CodeGenOpt::None, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SCALAR_TO_VECTOR, llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::SDNode::setFlags(), llvm::SDNodeFlags::setNoFPExcept(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::SPII::Store, llvm::X86ISD::STRICT_CVTTP2SI, llvm::X86ISD::STRICT_CVTTP2UI, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FTRUNC, llvm::X86ISD::STRICT_VFPROUND, llvm::X86ISD::STRICT_VRNDSCALE, llvm::X86ISD::TC_RETURN, llvm::Test, llvm::SystemZISD::TM, llvm::ISD::TokenFactor, llvm::ISD::UNINDEXED, llvm::SDNode::use_empty(), llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::X86II::VEX, llvm::X86ISD::VFPROUND, llvm::X86ISD::VRNDSCALE, llvm::X86ISD::VSHLV, llvm::X86ISD::VSRAV, llvm::X86ISD::VSRLV, llvm::X86II::XOP, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
isDispSafeForFrameIndex()
static bool isDispSafeForFrameIndex (int64_t Val) static
Definition at line 1400 of file X86ISelDAGToDAG.cpp.
References llvm::Address, C, llvm::Depth, llvm::X86AS::FS, G, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::HandleSDNode::getValue(), llvm::X86AS::GS, llvm::MVT::i16, llvm::MVT::i64, llvm::X86::isOffsetSuitableForCodeModel(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm_unreachable, llvm::CodeModel::Medium, llvm::X86II::MO_NO_FLAG, llvm::CodeModel::Small, llvm::ISD::TargetGlobalTLSAddress, llvm::SystemZISD::TM, and llvm::X86ISD::WrapperRIP.
Referenced by foldMaskedShiftToBEXTR().
isFusableLoadOpStorePattern()
static bool isFusableLoadOpStorePattern (StoreSDNode * StoreNode, SDValue StoredVal, SelectionDAG * CurDAG, unsigned LoadOpNo, LoadSDNode *& LoadNode, SDValue & InputChain) static
Check whether or not the chain ending in StoreNode is suitable for doing the {load; op; store} to modify transformation.
Definition at line 2871 of file X86ISelDAGToDAG.cpp.
References llvm::numbers::e, llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValue(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasPredecessorHelper(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::SPII::Load, llvm::SDNode::ops(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), and llvm::ISD::TokenFactor.
isLegalMaskCompare()
static bool isLegalMaskCompare (SDNode * N, const X86Subtarget * Subtarget) static
Definition at line 538 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::ADC, llvm::ISD::ADD, llvm::X86ISD::ADD, llvm::ISD::ADDCARRY, llvm::X86ISD::AND, llvm::ISD::AND, C, llvm::X86ISD::CMPM, llvm::X86ISD::CMPM_SAE, llvm::dyn_cast(), llvm::X86ISD::FSETCCM, llvm::X86ISD::FSETCCM_SAE, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::X86Subtarget::hasVLX(), llvm::ISD::INSERT_SUBVECTOR, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::ISD::isBuildVectorAllZeros(), llvm::isNullConstant(), llvm::isOneConstant(), llvm::SDValue::isUndef(), llvm::ISD::LOAD, llvm::CodeGenOpt::None, llvm::X86ISD::OR, llvm::ISD::OR, llvm::ISD::ROTL, llvm::X86ISD::SBB, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::X86ISD::STRICT_CMPM, llvm::ISD::SUB, llvm::X86ISD::SUB, llvm::ISD::TargetGlobalTLSAddress, llvm::X86ISD::VBROADCAST_LOAD, llvm::X86ISD::VFPCLASS, llvm::X86ISD::VFPCLASSS, llvm::ISD::VSELECT, llvm::X86ISD::Wrapper, llvm::X86ISD::XOR, and llvm::ISD::XOR.
mayUseCarryFlag()
static bool mayUseCarryFlag (X86::CondCode CC) static
Definition at line 2797 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::BRCOND, llvm::X86ISD::CMOV, llvm::X86::COND_E, llvm::X86::COND_G, llvm::X86::COND_GE, llvm::X86::COND_L, llvm::X86::COND_LE, llvm::X86::COND_NE, llvm::X86::COND_NO, llvm::X86::COND_NP, llvm::X86::COND_NS, llvm::X86::COND_O, llvm::X86::COND_P, llvm::X86::COND_S, llvm::ISD::CopyToReg, getCondFromNode(), getReg(), llvm::SDValue::getResNo(), llvm::X86ISD::SETCC, llvm::X86ISD::SETCC_CARRY, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
moveBelowOrigChain()
static void moveBelowOrigChain (SelectionDAG * CurDAG, SDValue Load, SDValue Call, SDValue OrigChain) static
Replace the original chain operand of the call with load's chain operand and move load below the call's chain operand.
Definition at line 729 of file X86ISelDAGToDAG.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorImpl< T >::clear(), llvm::numbers::e, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T >::push_back(), llvm::ISD::TokenFactor, and llvm::SelectionDAG::UpdateNodeOperands().
Referenced by isCalleeLoad().
STATISTIC()
STATISTIC (NumLoadMoved , "Number of loads moved below TokenFactor")
Variable Documentation
AndImmShrink
cl::opt<bool> AndImmShrink("x86-and-imm-shrink", cl::init(true), cl::desc("Enable setting constant bits to reduce size of mask immediates"), cl::Hidden) static
Referenced by getVPTESTMOpc().