LLVM: lib/Target/X86/X86InstrFMA3Info.cpp File Reference
X86InstrFMA3Info.cpp File Reference
#include "X86InstrFMA3Info.h"
#include "X86InstrInfo.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Threading.h"
#include <cassert>
#include <cstdint>
Macros
#define FMA3GROUP(Name, Suf, Attrs) { { X86::Name##132##Suf, X86::Name##213##Suf, X86::Name##231##Suf }, Attrs },
#define FMA3GROUP_MASKED(Name, Suf, Attrs)
#define FMA3GROUP_PACKED_WIDTHS(Name, Suf, Attrs)
#define FMA3GROUP_PACKED(Name, Attrs)
#define FMA3GROUP_SCALAR_WIDTHS(Name, Suf, Attrs)
#define FMA3GROUP_SCALAR(Name, Attrs)
#define FMA3GROUP_FULL(Name, Attrs)
#define FMA3GROUP_PACKED_AVX512_WIDTHS(Name, Type, Suf, Attrs)
#define FMA3GROUP_PACKED_AVX512(Name, Suf, Attrs)
#define FMA3GROUP_PACKED_AVX512_ROUND(Name, Suf, Attrs)
#define FMA3GROUP_SCALAR_AVX512_ROUND(Name, Suf, Attrs)
Functions
static void verifyTables ()
Variables
static const X86InstrFMA3Group Groups []
static const X86InstrFMA3Group BroadcastGroups []
static const X86InstrFMA3Group RoundGroups []
Macro Definition Documentation
FMA3GROUP
#define FMA3GROUP (Name, Suf, Attrs) { { X86::Name##132##Suf, X86::Name##213##Suf, X86::Name##231##Suf }, Attrs },
Definition at line 23 of file X86InstrFMA3Info.cpp.
FMA3GROUP_FULL
#define FMA3GROUP_FULL (Name, Attrs)
Value:
FMA3GROUP_PACKED(Name, Attrs) \
  FMA3GROUP_SCALAR(Name, Attrs)
Definition at line 61 of file X86InstrFMA3Info.cpp.
FMA3GROUP_MASKED
#define FMA3GROUP_MASKED (Name, Suf, Attrs)
Value:
FMA3GROUP(Name, Suf, Attrs) \
  FMA3GROUP(Name, Suf##k, Attrs | X86InstrFMA3Group::KMergeMasked) \
  FMA3GROUP(Name, Suf##kz, Attrs | X86InstrFMA3Group::KZeroMasked)
Definition at line 26 of file X86InstrFMA3Info.cpp.
FMA3GROUP_PACKED
#define FMA3GROUP_PACKED (Name, Attrs)
Value:
FMA3GROUP_PACKED_WIDTHS(Name, PD, Attrs) \
  FMA3GROUP_PACKED_WIDTHS(Name, PS, Attrs)
Definition at line 43 of file X86InstrFMA3Info.cpp.
FMA3GROUP_PACKED_AVX512
#define FMA3GROUP_PACKED_AVX512 (Name, Suf, Attrs)
Value:
FMA3GROUP_PACKED_AVX512_WIDTHS(Name, PD, Suf, Attrs) \
  FMA3GROUP_PACKED_AVX512_WIDTHS(Name, PS, Suf, Attrs)
Definition at line 79 of file X86InstrFMA3Info.cpp.
FMA3GROUP_PACKED_AVX512_ROUND
#define FMA3GROUP_PACKED_AVX512_ROUND (Name, Suf, Attrs)
Value:
FMA3GROUP_MASKED(Name, PDZ##Suf, Attrs) \
  FMA3GROUP_MASKED(Name, PSZ##Suf, Attrs)
Definition at line 83 of file X86InstrFMA3Info.cpp.
FMA3GROUP_PACKED_AVX512_WIDTHS
#define FMA3GROUP_PACKED_AVX512_WIDTHS (Name, Type, Suf, Attrs)
Value:
FMA3GROUP_MASKED(Name, Type##Z128##Suf, Attrs) \
  FMA3GROUP_MASKED(Name, Type##Z256##Suf, Attrs) \
  FMA3GROUP_MASKED(Name, Type##Z##Suf, Attrs)
Definition at line 74 of file X86InstrFMA3Info.cpp.
FMA3GROUP_PACKED_WIDTHS
#define FMA3GROUP_PACKED_WIDTHS (Name, Suf, Attrs)
Value:
FMA3GROUP(Name, Suf##Ym, Attrs) \
  FMA3GROUP(Name, Suf##Yr, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Z128m, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Z128r, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Z256m, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Z256r, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Zm, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Zr, Attrs) \
  FMA3GROUP(Name, Suf##m, Attrs) \
  FMA3GROUP(Name, Suf##r, Attrs)
Definition at line 31 of file X86InstrFMA3Info.cpp.
FMA3GROUP_SCALAR
#define FMA3GROUP_SCALAR (Name, Attrs)
Value:
FMA3GROUP_SCALAR_WIDTHS(Name, SD, Attrs) \
  FMA3GROUP_SCALAR_WIDTHS(Name, SS, Attrs)
Definition at line 57 of file X86InstrFMA3Info.cpp.
FMA3GROUP_SCALAR_AVX512_ROUND
#define FMA3GROUP_SCALAR_AVX512_ROUND (Name, Suf, Attrs)
Value:
FMA3GROUP(Name, SDZ##Suf, Attrs) \
  FMA3GROUP_MASKED(Name, SDZ##Suf##_Int, Attrs) \
  FMA3GROUP(Name, SSZ##Suf, Attrs) \
  FMA3GROUP_MASKED(Name, SSZ##Suf##_Int, Attrs)
Definition at line 87 of file X86InstrFMA3Info.cpp.
FMA3GROUP_SCALAR_WIDTHS
#define FMA3GROUP_SCALAR_WIDTHS (Name, Suf, Attrs)
Value:
FMA3GROUP(Name, Suf##Zm, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Zm_Int, Attrs | X86InstrFMA3Group::Intrinsic) \
  FMA3GROUP(Name, Suf##Zr, Attrs) \
  FMA3GROUP_MASKED(Name, Suf##Zr_Int, Attrs | X86InstrFMA3Group::Intrinsic) \
  FMA3GROUP(Name, Suf##m, Attrs) \
  FMA3GROUP(Name, Suf##m_Int, Attrs | X86InstrFMA3Group::Intrinsic) \
  FMA3GROUP(Name, Suf##r, Attrs) \
  FMA3GROUP(Name, Suf##r_Int, Attrs | X86InstrFMA3Group::Intrinsic)
Definition at line 47 of file X86InstrFMA3Info.cpp.
Function Documentation
verifyTables()
static void verifyTables () static
Definition at line 115 of file X86InstrFMA3Info.cpp.
References assert(), llvm::sys::path::begin(), and llvm::sys::path::end().
Referenced by llvm::getFMA3Group().
Variable Documentation
BroadcastGroups
const X86InstrFMA3Group BroadcastGroups[] static
Initial value:
= {
}
Definition at line 93 of file X86InstrFMA3Info.cpp.
Groups
const X86InstrFMA3Group Groups[] static
Initial value:
= {
}
Definition at line 65 of file X86InstrFMA3Info.cpp.
Referenced by INITIALIZE_PASS(), isIFunc(), llvm::UpgradeDataLayoutString(), and UpgradeIntrinsicFunction1().
RoundGroups
const X86InstrFMA3Group RoundGroups[] static
Initial value:
= {
}
Definition at line 102 of file X86InstrFMA3Info.cpp.