LLVM: lib/Target/X86/X86LegalizerInfo.cpp File Reference
X86LegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for X86.
#include "X86LegalizerInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Type.h"
Functions
static void addAndInterleaveWithUnsupported (LegalizerInfo::SizeAndActionsVec &result, const LegalizerInfo::SizeAndActionsVec &v)
FIXME: The following static functions are SizeChangeStrategy functions that are meant to temporarily mimic the behaviour of the old legalization based on doubling/halving non-legal types as closely as possible.
static LegalizerInfo::SizeAndActionsVec widen_1 (const LegalizerInfo::SizeAndActionsVec &v)
Detailed Description
This file implements the targeting of the Machinelegalizer class for X86.
Todo:
This should be generated by TableGen.
Definition in file X86LegalizerInfo.cpp.
Function Documentation
addAndInterleaveWithUnsupported()
static void addAndInterleaveWithUnsupported (LegalizerInfo::SizeAndActionsVec & result, const LegalizerInfo::SizeAndActionsVec & v) static
FIXME: The following static functions are SizeChangeStrategy functions that are meant to temporarily mimic the behaviour of the old legalization based on doubling/halving non-legal types as closely as possible.
This is not entirly possible as only legalizing the types that are exactly a power of 2 times the size of the legal types would require specifying all those sizes explicitly. In practice, not specifying those isn't a problem, and the below functions should disappear quickly as we add support for legalizing non-power-of-2 sized types further.
Definition at line 36 of file X86LegalizerInfo.cpp.
References first.
Referenced by widen_1().
widen_1()
static LegalizerInfo::SizeAndActionsVec widen_1 (const LegalizerInfo::SizeAndActionsVec & v) static
Definition at line 47 of file X86LegalizerInfo.cpp.
References addAndInterleaveWithUnsupported(), assert(), first, llvm::LegalizeActions::Unsupported, and llvm::LegalizeActions::WidenScalar.
Referenced by llvm::X86LegalizerInfo::X86LegalizerInfo().