LLVM: lib/Target/X86/X86MCInstLower.cpp File Reference
X86MCInstLower.cpp File Reference
#include "MCTargetDesc/X86ATTInstPrinter.h"
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86InstComments.h"
#include "MCTargetDesc/X86TargetStreamer.h"
#include "Utils/X86ShuffleDecode.h"
#include "X86AsmPrinter.h"
#include "X86RegisterInfo.h"
#include "X86ShuffleDecodeConstantPool.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Classes
struct NoAutoPaddingScope
A RAII helper which defines a region of instructions which can't have padding added between them for correctness.
Macros
#define MOV_CASE(Prefix, Suffix)
#define MOV_AVX512_CASE(Suffix)
#define CASE_ALL_MOV_RM()
Functions
static void EmitNops (MCStreamer &OS, unsigned NumBytes, bool Is64Bit, const MCSubtargetInfo &STI)
Emit the optimal amount of multi-byte nops on X86.
static void SimplifyShortImmForm (MCInst &Inst, unsigned Opcode)
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
static void SimplifyMOVSX (MCInst &Inst)
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
static void SimplifyShortMoveForm (X86AsmPrinter &Printer, MCInst &Inst, unsigned Opcode)
Simplify things like MOV32rm to MOV32o32a.
static unsigned getRetOpcode (const X86Subtarget &Subtarget)
static unsigned convertTailJumpOpcode (unsigned Opcode)
static unsigned MaxLongNopLength (const MCSubtargetInfo &STI)
Return the longest nop which can be efficiently decoded for the given target cpu.
static unsigned EmitNop (MCStreamer &OS, unsigned NumBytes, bool Is64Bit, const MCSubtargetInfo &STI)
Emit the largest nop instruction smaller than or equal to NumBytes bytes.
static MachineBasicBlock::const_iterator PrevCrossBBInst (MachineBasicBlock::const_iterator MBBI)
static const Constant * getConstantFromPool (const MachineInstr &MI, const MachineOperand &Op)
static std::string getShuffleComment (const MachineInstr *MI, unsigned SrcOp1Idx, unsigned SrcOp2Idx, ArrayRef< int > Mask)
static void printConstant (const APInt &Val, raw_ostream &CS)
static void printConstant (const APFloat &Flt, raw_ostream &CS)
static void printConstant (const Constant *COp, raw_ostream &CS)
static unsigned getRegisterWidth (const MCOperandInfo &Info)
Macro Definition Documentation
CASE_ALL_MOV_RM
#define CASE_ALL_MOV_RM ()
Value:
MOV_CASE(,)   /* SSE */                                                     \
  MOV_CASE(V, )  /* AVX-128 */                                                 \
  MOV_CASE(V, Y) /* AVX-256 */                                                 \
  MOV_AVX512_CASE(Z)                                                           \
  MOV_AVX512_CASE(Z256)                                                        \
  MOV_AVX512_CASE(Z128)
Referenced by llvm::X86AsmPrinter::EmitInstruction().
MOV_AVX512_CASE
#define MOV_AVX512_CASE (Suffix)
Value:
case X86::VMOVDQA64##Suffix##rm:                                             \
  case X86::VMOVDQA32##Suffix##rm:                                             \
  case X86::VMOVDQU64##Suffix##rm:                                             \
  case X86::VMOVDQU32##Suffix##rm:                                             \
  case X86::VMOVDQU16##Suffix##rm:                                             \
  case X86::VMOVDQU8##Suffix##rm:                                              \
  case X86::VMOVAPS##Suffix##rm:                                               \
  case X86::VMOVAPD##Suffix##rm:                                               \
  case X86::VMOVUPS##Suffix##rm:                                               \
  case X86::VMOVUPD##Suffix##rm:
MOV_CASE
#define MOV_CASE (Prefix, Suffix)
Value:
case X86::Prefix##MOVAPD##Suffix##rm:                                        \
  case X86::Prefix##MOVAPS##Suffix##rm:                                        \
  case X86::Prefix##MOVUPD##Suffix##rm:                                        \
  case X86::Prefix##MOVUPS##Suffix##rm:                                        \
  case X86::Prefix##MOVDQA##Suffix##rm:                                        \
  case X86::Prefix##MOVDQU##Suffix##rm:
Function Documentation
convertTailJumpOpcode()
static unsigned convertTailJumpOpcode (unsigned Opcode) static
Definition at line 432 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::X86::AddrNumOperands, llvm::X86::AddrSegmentReg, assert(), llvm::MCAsmInfo::canRelaxRelocations(), llvm::ISD::CATCHRET, llvm::ISD::CLEANUPRET, llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createReg(), llvm::N86::EAX, llvm::N86::EBX, llvm::ISD::EH_RETURN, llvm::X86II::EncodingMask, llvm::MCInst::erase(), llvm::X86II::FormMask, llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineModuleInfo::getModule(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MCInst::getOperand(), llvm::MachineInstr::getOperand(), llvm::MCContext::getOrCreateSymbol(), llvm::MCOperand::getReg(), getRetOpcode(), llvm::Module::getRtLibUseGOT(), llvm::X86Subtarget::is64Bit(), llvm::MCInstrDesc::isCommutable(), llvm::X86II::isX86_64ExtendedReg(), llvm_unreachable, llvm::Lower, llvm::AsmPrinter::MMI, llvm::X86II::MRMSrcReg, llvm::MachineInstr::operands(), llvm::X86II::OpMapMask, llvm::MCInst::setOpcode(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), std::swap(), llvm::X86II::TB, llvm::MCInstrDesc::TSFlags, llvm::X86II::VEX, llvm::X86II::VEX_4V, llvm::X86II::VEX_W, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_GOTPCREL, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_TLSGD, llvm::MCSymbolRefExpr::VK_TLSLD, and llvm::MCSymbolRefExpr::VK_TLSLDM.
Referenced by NoAutoPaddingScope::changeAndComment().
EmitNop()
static unsigned EmitNop (MCStreamer & OS, unsigned NumBytes, bool Is64Bit, const MCSubtargetInfo & STI) static
Emit the largest nop instruction smaller than or equal to NumBytes bytes.
Return the size of nop emitted.
Definition at line 1050 of file X86MCInstLower.cpp.
References assert(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitInstruction(), llvm_unreachable, and MaxLongNopLength().
Referenced by NoAutoPaddingScope::changeAndComment(), and EmitNops().
EmitNops()
static void EmitNops (MCStreamer & OS, unsigned NumBytes, bool Is64Bit, const MCSubtargetInfo & STI) static
Emit the optimal amount of multi-byte nops on X86.
Definition at line 1154 of file X86MCInstLower.cpp.
References assert(), and EmitNop().
Referenced by llvm::MCBoundaryAlignFragment::canEmitNops(), NoAutoPaddingScope::changeAndComment(), llvm::MCAlignFragment::hasEmitNops(), llvm::MCAlignFragment::setEmitNops(), and llvm::MCBoundaryAlignFragment::setEmitNops().
getConstantFromPool()
static const Constant* getConstantFromPool (const MachineInstr & MI, const MachineOperand & Op) static
Definition at line 1738 of file X86MCInstLower.cpp.
References assert(), C, llvm::MachineConstantPoolEntry::ConstVal, llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineConstantPoolEntry::getType(), llvm::Value::getType(), llvm::MachineOperand::isCPI(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), and llvm::MachineConstantPoolEntry::Val.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
getRegisterWidth()
static unsigned getRegisterWidth (const MCOperandInfo & Info) static
Definition at line 1952 of file X86MCInstLower.cpp.
References llvm_unreachable, and llvm::MCOperandInfo::RegClass.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
getRetOpcode()
static unsigned getRetOpcode (const X86Subtarget & Subtarget) static
Definition at line 393 of file X86MCInstLower.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::errs(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getReg(), GetSymbolFromOperand(), llvm::MachineOperand::getType(), llvm::X86Subtarget::is64Bit(), llvm::MachineOperand::isImplicit(), llvm_unreachable, LowerSymbolOperand(), MI, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::None, and llvm::MachineInstr::print().
Referenced by convertTailJumpOpcode(), and llvm::X86AsmPrinter::EmitInstruction().
getShuffleComment()
static std::string getShuffleComment (const MachineInstr * MI, unsigned SrcOp1Idx, unsigned SrcOp2Idx, ArrayRef< int > Mask) static
Definition at line 1758 of file X86MCInstLower.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::numbers::e, llvm::ArrayRef< T >::end(), llvm::raw_ostream::flush(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::X86ATTInstPrinter::getRegisterName(), llvm::MachineOperand::isReg(), llvm::SM_SentinelUndef, and llvm::SM_SentinelZero.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
MaxLongNopLength()
static unsigned MaxLongNopLength (const MCSubtargetInfo & STI) static
Return the longest nop which can be efficiently decoded for the given target cpu.
15-bytes is the longest single NOP instruction, but some platforms can't decode the longest forms efficiently.
Definition at line 1037 of file X86MCInstLower.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
Referenced by EmitNop().
PrevCrossBBInst()
static MachineBasicBlock::const_iterator PrevCrossBBInst (MachineBasicBlock::const_iterator MBBI) static
Definition at line 1726 of file X86MCInstLower.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::front(), llvm::MachineBasicBlock::getParent(), and llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode().
Referenced by llvm::X86AsmPrinter::EmitInstruction().
printConstant() [1/3]
static void printConstant (const APInt & Val, raw_ostream & CS) static
Definition at line 1843 of file X86MCInstLower.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getNumWords(), llvm::APInt::getRawData(), llvm::APInt::getZExtValue(), and N.
Referenced by llvm::X86AsmPrinter::EmitInstruction(), and printConstant().
printConstant() [2/3]
static void printConstant (const APFloat & Flt, raw_ostream & CS) static
Definition at line 1858 of file X86MCInstLower.cpp.
References llvm::APFloat::toString().
printConstant() [3/3]
static void printConstant (const Constant * COp, raw_ostream & CS) static
Definition at line 1865 of file X86MCInstLower.cpp.
References assert(), llvm::X86TargetStreamer::emitFPOEndPrologue(), llvm::X86TargetStreamer::emitFPOPushReg(), llvm::X86TargetStreamer::emitFPOSetFrame(), llvm::X86TargetStreamer::emitFPOStackAlign(), llvm::X86TargetStreamer::emitFPOStackAlloc(), llvm::MCStreamer::EmitWinCFIAllocStack(), llvm::MCStreamer::EmitWinCFIEndProlog(), llvm::MCStreamer::EmitWinCFIPushFrame(), llvm::MCStreamer::EmitWinCFIPushReg(), llvm::MCStreamer::EmitWinCFISaveReg(), llvm::MCStreamer::EmitWinCFISaveXMM(), llvm::MCStreamer::EmitWinCFISetFrame(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::X86AsmPrinter::getSubtarget(), llvm::MCStreamer::getTargetStreamer(), llvm::MachineFunction::hasWinCFI(), llvm_unreachable, llvm::AsmPrinter::MF, and printConstant().
SimplifyMOVSX()
static void SimplifyMOVSX (MCInst & Inst) static
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
Definition at line 315 of file X86MCInstLower.cpp.
References llvm::AArch64CC::AL, llvm::N86::EAX, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, and llvm::MCInst::setOpcode().
Referenced by convertTailJumpOpcode().
SimplifyShortImmForm()
static void SimplifyShortImmForm (MCInst & Inst, unsigned Opcode) static
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
Definition at line 292 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::AArch64CC::AL, assert(), llvm::N86::EAX, llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), Reg, and llvm::MCInst::setOpcode().
Referenced by convertTailJumpOpcode().
SimplifyShortMoveForm()
static void SimplifyShortMoveForm (X86AsmPrinter & Printer, MCInst & Inst, unsigned Opcode) static
Simplify things like MOV32rm to MOV32o32a.
Definition at line 342 of file X86MCInstLower.cpp.
References llvm::HexagonII::Absolute, llvm::MCInst::addOperand(), llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::X86::AddrScaleAmt, llvm::X86::AddrSegmentReg, llvm::AArch64CC::AL, assert(), llvm::N86::EAX, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::X86AsmPrinter::getSubtarget(), llvm::X86Subtarget::is64Bit(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), Reg, llvm::MCInst::setOpcode(), and llvm::MCSymbolRefExpr::VK_TLVP.
Referenced by convertTailJumpOpcode().