LLVM: lib/Target/X86/X86MacroFusion.cpp File Reference
X86MacroFusion.cpp File Reference
#include "MCTargetDesc/X86BaseInfo.h"
#include "X86MacroFusion.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MacroFusion.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Namespaces
llvm
This class represents lattice values for constants.
Functions
static X86::FirstMacroFusionInstKind classifyFirst (const MachineInstr &MI)
static X86::SecondMacroFusionInstKind classifySecond (const MachineInstr &MI)
static bool shouldScheduleAdjacent (const TargetInstrInfo &TII, const TargetSubtargetInfo &TSI, const MachineInstr *FirstMI, const MachineInstr &SecondMI)
Check if the instr pair, FirstMI and SecondMI, should be fused together.
std::unique_ptr< ScheduleDAGMutation > llvm::createX86MacroFusionDAGMutation ()
Note that you have to add: DAG.addMutation(createX86MacroFusionDAGMutation()); to X86PassConfig::createMachineScheduler() to have an effect.
Function Documentation
classifyFirst()
static X86::FirstMacroFusionInstKind classifyFirst (const MachineInstr & MI) static
Definition at line 22 of file X86MacroFusion.cpp.
References llvm::X86::classifyFirstOpcodeInMacroFusion(), and llvm::MachineInstr::getOpcode().
Referenced by shouldScheduleAdjacent().
classifySecond()
static X86::SecondMacroFusionInstKind classifySecond (const MachineInstr & MI) static
Definition at line 26 of file X86MacroFusion.cpp.
References llvm::X86::classifySecondCondCodeInMacroFusion(), and llvm::X86::getCondFromBranch().
Referenced by shouldScheduleAdjacent().
shouldScheduleAdjacent()
static bool shouldScheduleAdjacent (const TargetInstrInfo & TII, const TargetSubtargetInfo & TSI, const MachineInstr * FirstMI, const MachineInstr & SecondMI) static
Check if the instr pair, FirstMI and SecondMI, should be fused together.
Given SecondMI, when FirstMI is unspecified, then check if SecondMI may be part of a fused pair at all.
Definition at line 34 of file X86MacroFusion.cpp.
References classifyFirst(), classifySecond(), llvm::X86::Cmp, llvm::X86Subtarget::hasBranchFusion(), llvm::X86Subtarget::hasMacroFusion(), llvm::X86::Invalid, llvm::X86::isMacroFused(), llvm_unreachable, llvm::ARM_MB::ST, and llvm::X86::Test.