LLVM: lib/Target/X86/MCTargetDesc/X86MachObjectWriter.cpp File Reference
X86MachObjectWriter.cpp File Reference
#include "MCTargetDesc/X86FixupKinds.h"
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
Functions
static bool isFixupKindRIPRel (unsigned Kind)
static unsigned getFixupKindLog2Size (unsigned Kind)
Function Documentation
getFixupKindLog2Size()
static unsigned getFixupKindLog2Size (unsigned Kind) static
Definition at line 80 of file X86MachObjectWriter.cpp.
References llvm::MachObjectWriter::addRelocation(), llvm::HexStyle::Asm, assert(), B, llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), llvm::MachObjectWriter::findAliasedSymbol(), Fixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm::format(), llvm::MachO::GENERIC_RELOC_LOCAL_SECTDIFF, llvm::MachO::GENERIC_RELOC_PAIR, llvm::MachO::GENERIC_RELOC_SECTDIFF, llvm::MachO::GENERIC_RELOC_TLV, llvm::MachO::GENERIC_RELOC_VANILLA, llvm::MCContext::getAsmInfo(), llvm::MCAssembler::getAtom(), llvm::MCValue::getConstant(), llvm::MCAssembler::getContext(), llvm::MCSymbol::getFragment(), llvm::MachObjectWriter::getFragmentAddress(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCFixup::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCFixup::getLoc(), llvm::MCSymbol::getName(), llvm::MCFixup::getOffset(), llvm::MCSection::getOrdinal(), llvm::MCFragment::getParent(), llvm::MCSymbol::getSection(), llvm::MachObjectWriter::getSectionAddress(), llvm::MachObjectWriter::getSectionAddressMap(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCFixup::getTargetKind(), llvm::MCSymbol::getVariableValue(), llvm::MCSectionMachO::hasAttribute(), is64Bit(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isExternal(), llvm::MachObjectWriter::isFixupKindPCRel(), isFixupKindRIPRel(), llvm::MCSymbol::isInSection(), llvm::MCAsmInfo::isSectionAtomizableBySymbols(), llvm::MCSymbol::isTemporary(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), llvm_unreachable, Name, llvm::MachO::R_SCATTERED, llvm::MachO::any_relocation_info::r_word0, llvm::MachO::any_relocation_info::r_word1, llvm::X86::reloc_branch_4byte_pcrel, llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_riprel_4byte_relax, llvm::X86::reloc_riprel_4byte_relax_rex, llvm::X86::reloc_signed_4byte, llvm::X86::reloc_signed_4byte_relax, llvm::MCContext::reportError(), llvm::MachO::S_ATTR_DEBUG, llvm::ARMBuildAttrs::Section, llvm::MCSymbol::setUsedInReloc(), llvm::ARMBuildAttrs::Symbol, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_GOTPCREL, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_TLVP, llvm::MachO::X86_64_RELOC_BRANCH, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, llvm::MachO::X86_64_RELOC_SIGNED, llvm::MachO::X86_64_RELOC_SIGNED_1, llvm::MachO::X86_64_RELOC_SIGNED_2, llvm::MachO::X86_64_RELOC_SIGNED_4, llvm::MachO::X86_64_RELOC_SUBTRACTOR, llvm::MachO::X86_64_RELOC_TLV, and llvm::MachO::X86_64_RELOC_UNSIGNED.
isFixupKindRIPRel()
static bool isFixupKindRIPRel (unsigned Kind) static
Definition at line 73 of file X86MachObjectWriter.cpp.
References llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_riprel_4byte_relax, and llvm::X86::reloc_riprel_4byte_relax_rex.
Referenced by getFixupKindLog2Size().