LLVM: lib/Target/X86/MCTargetDesc/X86WinCOFFTargetStreamer.cpp File Reference
X86WinCOFFTargetStreamer.cpp File Reference
#include "X86MCTargetDesc.h"
#include "X86TargetStreamer.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCCodeView.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/FormattedStream.h"
Functions
static Printable printFPOReg (const MCRegisterInfo *MRI, unsigned LLVMReg)
Function Documentation
printFPOReg()
static Printable printFPOReg (const MCRegisterInfo * MRI, unsigned LLVMReg) static
Definition at line 290 of file X86WinCOFFTargetStreamer.cpp.
References llvm::CodeViewContext::addToStringTable(), assert(), llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::N86::EAX, llvm::N86::EBX, llvm::N86::ECX, llvm::N86::EDI, llvm::N86::EDX, llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::N86::ESI, llvm::N86::ESP, llvm::codeview::FrameData, llvm::MCRegisterInfo::getCodeViewRegNum(), llvm::MCStreamer::getContext(), llvm::MCContext::getCVContext(), llvm::MCSymbol::getName(), llvm::MCContext::getRegisterInfo(), I, llvm::codeview::FrameData::IsFunctionStart, MRI, llvm::MCContext::reportError(), second, llvm::raw_svector_ostream::str(), and llvm::MCSymbolRefExpr::VK_COFF_IMGREL32.