LLVM: lib/Target/XCore/Disassembler/XCoreDisassembler.cpp File Reference
XCoreDisassembler.cpp File Reference
This file is part of the XCore Disassembler.
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCore.h"
#include "XCoreRegisterInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
#include "XCoreGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "xcore-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint16_t &Insn)
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static unsigned getReg (const void *D, unsigned RC, unsigned RegNo)
static DecodeStatus DecodeGRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBitpOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeNegImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2RImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeR2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRUSSrcDstBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLR2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode3RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode3RImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2RUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2RUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL3RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL3RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL2RUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL2RUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL6RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL5RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL4RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL4RSrcDstSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus Decode2OpInstruction (unsigned Insn, unsigned &Op1, unsigned &Op2)
static DecodeStatus Decode3OpInstruction (unsigned Insn, unsigned &Op1, unsigned &Op2, unsigned &Op3)
static DecodeStatus Decode2OpInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL2OpInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeL5RInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static MCDisassembler * createXCoreDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreDisassembler ()
Detailed Description
This file is part of the XCore Disassembler.
Definition in file XCoreDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xcore-disassembler"
Definition at line 26 of file XCoreDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 28 of file XCoreDisassembler.cpp.
Function Documentation
createXCoreDisassembler()
static MCDisassembler* createXCoreDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 771 of file XCoreDisassembler.cpp.
Referenced by LLVMInitializeXCoreDisassembler().
Decode2OpInstruction()
static DecodeStatus Decode2OpInstruction (unsigned Insn, unsigned & Op1, unsigned & Op2) static
Definition at line 240 of file XCoreDisassembler.cpp.
References llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), DecodeL2RInstruction(), DecodeL5RInstruction(), DecodeLR2RInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), and DecodeRUSSrcDstBitpInstruction().
Decode2OpInstructionFail()
static DecodeStatus Decode2OpInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 274 of file XCoreDisassembler.cpp.
References Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), llvm::MCDisassembler::Fail, and llvm::MCInst::setOpcode().
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), and DecodeRUSSrcDstBitpInstruction().
Decode2RImmInstruction()
static DecodeStatus Decode2RImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 357 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
Decode2RInstruction()
static DecodeStatus Decode2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 344 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
Decode2RSrcDstInstruction()
static DecodeStatus Decode2RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 383 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
Decode2RUSBitpInstruction()
static DecodeStatus Decode2RUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 575 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail(), and getReg().
Decode2RUSInstruction()
static DecodeStatus Decode2RUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 562 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail(), and getReg().
Decode3OpInstruction()
static DecodeStatus Decode3OpInstruction (unsigned Insn, unsigned & Op1, unsigned & Op2, unsigned & Op3) static
Definition at line 258 of file XCoreDisassembler.cpp.
References llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), DecodeL4RSrcDstInstruction(), DecodeL4RSrcDstSrcDstInstruction(), DecodeL5RInstruction(), and DecodeL6RInstruction().
Decode3RImmInstruction()
static DecodeStatus Decode3RImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 549 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail(), and getReg().
Decode3RInstruction()
static DecodeStatus Decode3RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 536 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail(), and getReg().
DecodeBitpOperand()
static DecodeStatus DecodeBitpOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 222 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Decode2RUSBitpInstruction(), DecodeL2RUSBitpInstruction(), DecodeRUSBitpInstruction(), DecodeRUSSrcDstBitpInstruction(), and getReg().
DecodeGRRegsRegisterClass()
static DecodeStatus DecodeGRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 198 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), Reg, and llvm::MCDisassembler::Success.
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), DecodeL2RInstruction(), DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), DecodeL4RSrcDstInstruction(), DecodeL4RSrcDstSrcDstInstruction(), DecodeL5RInstruction(), DecodeL6RInstruction(), DecodeLR2RInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), DecodeRUSSrcDstBitpInstruction(), and getReg().
DecodeL2OpInstructionFail()
static DecodeStatus DecodeL2OpInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 437 of file XCoreDisassembler.cpp.
References DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), llvm::MCDisassembler::Fail, and llvm::MCInst::setOpcode().
Referenced by DecodeL2RInstruction(), and DecodeLR2RInstruction().
DecodeL2RInstruction()
static DecodeStatus DecodeL2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 508 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL2OpInstructionFail(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeL2RUSBitpInstruction()
static DecodeStatus DecodeL2RUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 631 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail(), and getReg().
DecodeL2RUSInstruction()
static DecodeStatus DecodeL2RUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 617 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail(), and getReg().
DecodeL3RInstruction()
static DecodeStatus DecodeL3RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 588 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail(), and getReg().
DecodeL3RSrcDstInstruction()
static DecodeStatus DecodeL3RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 602 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail(), and getReg().
DecodeL4RSrcDstInstruction()
static DecodeStatus DecodeL4RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 699 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeL4RSrcDstSrcDstInstruction()
static DecodeStatus DecodeL4RSrcDstSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 718 of file XCoreDisassembler.cpp.
References llvm::Address, Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Fail, readInstruction16(), readInstruction32(), Size, and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeL5RInstruction()
static DecodeStatus DecodeL5RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 679 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL5RInstructionFail(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeL5RInstructionFail()
static DecodeStatus DecodeL5RInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 665 of file XCoreDisassembler.cpp.
References llvm::MCInst::clear(), DecodeL6RInstruction(), llvm::MCDisassembler::Fail, and llvm::MCInst::setOpcode().
Referenced by DecodeL5RInstruction().
DecodeL6RInstruction()
static DecodeStatus DecodeL6RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 645 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by DecodeL5RInstructionFail(), and getReg().
DecodeLR2RInstruction()
static DecodeStatus DecodeLR2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 522 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL2OpInstructionFail(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeNegImmOperand()
static DecodeStatus DecodeNegImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const void * Decoder) static
Definition at line 233 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeR2RInstruction()
static DecodeStatus DecodeR2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 370 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeRRegsRegisterClass()
static DecodeStatus DecodeRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 210 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), Reg, and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeRUSBitpInstruction()
static DecodeStatus DecodeRUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 410 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeRUSInstruction()
static DecodeStatus DecodeRUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 397 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
DecodeRUSSrcDstBitpInstruction()
static DecodeStatus DecodeRUSSrcDstBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 423 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), and llvm::MCDisassembler::Success.
Referenced by getReg().
getReg()
static unsigned getReg (const void * D, unsigned RC, unsigned RegNo) static
Definition at line 69 of file XCoreDisassembler.cpp.
References llvm::Address, llvm::MCRegisterClass::begin(), D, Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), DecodeL2RInstruction(), DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), DecodeL4RSrcDstInstruction(), DecodeL4RSrcDstSrcDstInstruction(), DecodeL5RInstruction(), DecodeL6RInstruction(), DecodeLR2RInstruction(), DecodeNegImmOperand(), DecodeR2RInstruction(), DecodeRRegsRegisterClass(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), DecodeRUSSrcDstBitpInstruction(), and llvm::MCRegisterInfo::getRegClass().
Referenced by DecodeGRRegsRegisterClass(), and DecodeRRegsRegisterClass().
LLVMInitializeXCoreDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreDisassembler ()
Definition at line 777 of file XCoreDisassembler.cpp.
References createXCoreDisassembler(), llvm::getTheXCoreTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint16_t & Insn) static
Definition at line 44 of file XCoreDisassembler.cpp.
References llvm::ArrayRef< T >::size().
Referenced by DecodeL4RSrcDstSrcDstInstruction().
readInstruction32()
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 56 of file XCoreDisassembler.cpp.
References llvm::ArrayRef< T >::size().
Referenced by DecodeL4RSrcDstSrcDstInstruction().