LLVM: lib/Target/XCore/XCoreTargetObjectFile.cpp File Reference
XCoreTargetObjectFile.cpp File Reference
#include "XCoreTargetObjectFile.h"
#include "XCoreSubtarget.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Target/TargetMachine.h"
Functions
static unsigned getXCoreSectionType (SectionKind K)
static unsigned getXCoreSectionFlags (SectionKind K, bool IsCPRel)
Function Documentation
getXCoreSectionFlags()
static unsigned getXCoreSectionFlags (SectionKind K, bool IsCPRel) static
Definition at line 71 of file XCoreTargetObjectFile.cpp.
References llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isMergeableCString(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isText(), llvm::SectionKind::isWriteable(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_WRITE, llvm::ELF::XCORE_SHF_CP_SECTION, and llvm::ELF::XCORE_SHF_DP_SECTION.
Referenced by llvm::XCoreTargetObjectFile::getExplicitSectionGlobal().
getXCoreSectionType()
static unsigned getXCoreSectionType (SectionKind K) static
Definition at line 65 of file XCoreTargetObjectFile.cpp.
References llvm::SectionKind::isBSS(), llvm::ELF::SHT_NOBITS, and llvm::ELF::SHT_PROGBITS.
Referenced by llvm::XCoreTargetObjectFile::getExplicitSectionGlobal().