LLVM: lib/Target/XCore/XCoreRegisterInfo.cpp File Reference
XCoreRegisterInfo.cpp File Reference
#include "XCoreRegisterInfo.h"
#include "XCore.h"
#include "XCoreInstrInfo.h"
#include "XCoreMachineFunctionInfo.h"
#include "XCoreSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "XCoreGenRegisterInfo.inc"
Macros
#define DEBUG_TYPE "xcore-reg-info"
#define GET_REGINFO_TARGET_DESC
Functions
static bool isImmUs (unsigned val)
static bool isImmU6 (unsigned val)
static bool isImmU16 (unsigned val)
static void InsertFPImmInst (MachineBasicBlock::iterator II, const XCoreInstrInfo &TII, unsigned Reg, unsigned FrameReg, int Offset)
static void InsertFPConstInst (MachineBasicBlock::iterator II, const XCoreInstrInfo &TII, unsigned Reg, unsigned FrameReg, int Offset, RegScavenger *RS)
static void InsertSPImmInst (MachineBasicBlock::iterator II, const XCoreInstrInfo &TII, unsigned Reg, int Offset)
static void InsertSPConstInst (MachineBasicBlock::iterator II, const XCoreInstrInfo &TII, unsigned Reg, int Offset, RegScavenger *RS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xcore-reg-info"
Definition at line 38 of file XCoreRegisterInfo.cpp.
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 40 of file XCoreRegisterInfo.cpp.
Function Documentation
InsertFPConstInst()
static void InsertFPConstInst (MachineBasicBlock::iterator II, const XCoreInstrInfo & TII, unsigned Reg, unsigned FrameReg, int Offset, RegScavenger * RS) static
Definition at line 92 of file XCoreRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, llvm_unreachable, llvm::XCoreInstrInfo::loadImmediate(), llvm::MachineInstr::memoperands_begin(), MI, Reg, llvm::RegScavenger::scavengeRegister(), and llvm::RegScavenger::setRegUsed().
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().
InsertFPImmInst()
static void InsertFPImmInst (MachineBasicBlock::iterator II, const XCoreInstrInfo & TII, unsigned Reg, unsigned FrameReg, int Offset) static
Definition at line 61 of file XCoreRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::isKill(), llvm_unreachable, llvm::MachineInstr::memoperands_begin(), MI, and Reg.
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().
InsertSPConstInst()
static void InsertSPConstInst (MachineBasicBlock::iterator II, const XCoreInstrInfo & TII, unsigned Reg, int Offset, RegScavenger * RS) static
Definition at line 161 of file XCoreRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, llvm_unreachable, llvm::XCoreInstrInfo::loadImmediate(), llvm::MachineInstr::memoperands_begin(), MI, Reg, llvm::RegScavenger::scavengeRegister(), and llvm::RegScavenger::setRegUsed().
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().
InsertSPImmInst()
static void InsertSPImmInst (MachineBasicBlock::iterator II, const XCoreInstrInfo & TII, unsigned Reg, int Offset) static
Definition at line 128 of file XCoreRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), isImmU6(), llvm::MachineOperand::isKill(), llvm_unreachable, llvm::MachineInstr::memoperands_begin(), MI, and Reg.
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().
isImmU16()
static bool isImmU16 (unsigned val) inline static
Definition at line 56 of file XCoreRegisterInfo.cpp.
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().
isImmU6()
static bool isImmU6 (unsigned val) inline static
Definition at line 52 of file XCoreRegisterInfo.cpp.
Referenced by InsertSPImmInst().
isImmUs()
static bool isImmUs (unsigned val) inline static
Definition at line 48 of file XCoreRegisterInfo.cpp.
Referenced by llvm::XCoreRegisterInfo::eliminateFrameIndex().