LLVM: lib/Target/XCore/XCoreTargetMachine.cpp File Reference
XCoreTargetMachine.cpp File Reference
#include "XCoreTargetMachine.h"
#include "MCTargetDesc/XCoreMCTargetDesc.h"
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCore.h"
#include "XCoreTargetObjectFile.h"
#include "XCoreTargetTransformInfo.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/TargetRegistry.h"
Functions
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveXCoreCodeModel (Optional< CodeModel::Model > CM)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Function Documentation
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM) static
Definition at line 28 of file XCoreTargetMachine.cpp.
References llvm::Optional< T >::hasValue(), llvm::NVPTX::PTXCvtMode::RM, and llvm::Reloc::Static.
getEffectiveXCoreCodeModel()
static CodeModel::Model getEffectiveXCoreCodeModel (Optional< CodeModel::Model > CM) static
Definition at line 35 of file XCoreTargetMachine.cpp.
References llvm::CodeModel::Large, llvm::report_fatal_error(), and llvm::CodeModel::Small.
LLVMInitializeXCoreTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Definition at line 108 of file XCoreTargetMachine.cpp.
References llvm::getTheXCoreTarget(), and X.