LLVM: lib/Target/XCore/MCTargetDesc/XCoreInstPrinter.cpp File Reference
XCoreInstPrinter.cpp File Reference
#include "XCoreInstPrinter.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include "XCoreGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void printExpr (const MCExpr *Expr, const MCAsmInfo *MAI, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 25 of file XCoreInstPrinter.cpp.
Function Documentation
printExpr()
static void printExpr (const MCExpr * Expr, const MCAsmInfo * MAI, raw_ostream & OS) static
Definition at line 50 of file XCoreInstPrinter.cpp.
References assert(), llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCSymbolRefExpr::getKind(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, llvm::RISCVFenceField::O, llvm::MCSymbol::print(), llvm::XCoreInstPrinter::printRegName(), and llvm::MCSymbolRefExpr::VK_None.